In [70]:
from pathlib import Path
import json
import os
import random
import sys
import time
import wave
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader

DATA_DIR = Path("/workspace/E-DAIC/original_data")
SPLIT_DIR = Path("/workspace/E-DAIC/splits")
LABEL_DIR = Path("/workspace/E-DAIC/others")

TRAIN_SPLIT_PATH = SPLIT_DIR / "train_split.csv"
VAL_SPLIT_PATH = SPLIT_DIR / "dev_split.csv"
TEST_SPLIT_PATH = SPLIT_DIR / "test_split.csv"
DETAILED_LABEL_PATH = LABEL_DIR / "Detailed_PHQ8_Labels.csv"

AUDIO_CACHE_ROOT = Path("/workspace/E-DAIC/cache/phq8_audio_egemaps")
AUDIO_CACHE_VERSION = "egemaps23_turnmean_100hz_turns120_v1"
AUDIO_CACHE_DIR = AUDIO_CACHE_ROOT / AUDIO_CACHE_VERSION
CHECKPOINT_ROOT = Path("/workspace/E-DAIC/checkpoints/phq8_audio_paperlike")

PHQ8_QUESTION_COLUMNS = ["PHQ_8NoInterest", "PHQ_8Depressed", "PHQ_8Sleep", "PHQ_8Tired", "PHQ_8Appetite", "PHQ_8Failure", "PHQ_8Concentrating", "PHQ_8Moving"]

FEATURE_RATE = 100
AUDIO_FEATURE_DIM = 23
MAX_TURNS = 120
LSTM_HIDDEN_SIZE = 50
ATTENTION_HEADS = 4
NUM_CLASSES = 4

BATCH_SIZE = 10
NUM_EPOCHS = 50
LEARNING_RATE = 5e-4
ADAM_EPSILON = 1e-8
WEIGHT_DECAY = 1e-3
MAX_GRAD_NORM = 1.0

ALPHA = 1.0
BETA = 0.5
LOSS_EPSILON = 1e-12
SEEDS = [42, 100, 1234]

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

AUDIO_CACHE_DIR.mkdir(parents=True, exist_ok=True)
CHECKPOINT_ROOT.mkdir(parents=True, exist_ok=True)

print("Python：", sys.version.split()[0])
print("PyTorch：", torch.__version__)
print("CUDA可用：", torch.cuda.is_available())
print("计算设备：", device)
print("语音特征频率：", FEATURE_RATE)
print("语音特征维度：", AUDIO_FEATURE_DIM)
print("最大对话轮数：", MAX_TURNS)
print("训练轮数：", NUM_EPOCHS)
print("随机种子：", SEEDS)
print("语音缓存目录：", AUDIO_CACHE_DIR)
print("Checkpoint目录：", CHECKPOINT_ROOT)

Python： 3.12.3
PyTorch： 2.9.0
CUDA可用： True
计算设备： cuda:0
语音特征频率： 100
语音特征维度： 23
最大对话轮数： 120
训练轮数： 50
随机种子： [42, 100, 1234]
语音缓存目录： /workspace/E-DAIC/cache/phq8_audio_egemaps/egemaps23_turnmean_100hz_turns120_v1
Checkpoint目录： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike

In [37]:
train_split_df=pd.read_csv(TRAIN_SPLIT_PATH)
test_split_df=pd.read_csv(TEST_SPLIT_PATH)
val_split_df=pd.read_csv(VAL_SPLIT_PATH)
detailed_label_df=pd.read_csv(DETAILED_LABEL_PATH)

train_metadata_df=train_split_df.merge(detailed_label_df[["Participant_ID"]+PHQ8_QUESTION_COLUMNS], on="Participant_ID",how="left",validate="one_to_one")
val_metadata_df=val_split_df.merge(detailed_label_df[["Participant_ID"]+PHQ8_QUESTION_COLUMNS], on="Participant_ID",how="left",validate="one_to_one")
test_metadata_df=test_split_df.copy()

if train_metadata_df[PHQ8_QUESTION_COLUMNS].isna().any().any():
    raise ValueError("训练集存在缺失的PHQ-8题目标签")

if val_metadata_df[PHQ8_QUESTION_COLUMNS].isna().any().any():
    raise ValueError("验证集存在缺失的PHQ-8题目标签")
train_participant_ids = set(train_metadata_df["Participant_ID"].astype(int).tolist())
val_participant_ids = set(val_metadata_df["Participant_ID"].astype(int).tolist())
test_participant_ids = set(test_metadata_df["Participant_ID"].astype(int).tolist())
if train_participant_ids & val_participant_ids:
    raise ValueError("训练集与验证集存在参与者重叠")

if train_participant_ids & test_participant_ids:
    raise ValueError("训练集与测试集存在参与者重叠")

if val_participant_ids & test_participant_ids:
    raise ValueError("验证集与测试集存在参与者重叠")

print("训练参与者：", len(train_metadata_df))
print("验证参与者：", len(val_metadata_df))
print("测试参与者：", len(test_metadata_df))
print("训练标签形状：", train_metadata_df[PHQ8_QUESTION_COLUMNS].shape)
print("验证标签形状：", val_metadata_df[PHQ8_QUESTION_COLUMNS].shape)
print("全部题目标签范围：", sorted(pd.unique(train_metadata_df[PHQ8_QUESTION_COLUMNS].to_numpy().reshape(-1)).tolist()))
print("训练、验证、测试参与者没有重叠")

训练参与者： 163
验证参与者： 55
测试参与者： 56
训练标签形状： (163, 8)
验证标签形状： (55, 8)
全部题目标签范围： [0, 1, 2, 3]
训练、验证、测试参与者没有重叠

In [51]:
all_participants_ids=sorted(train_participant_ids|val_participant_ids|test_participant_ids)
missing_wav_ids=[]
missing_transcript_ids=[]
missing_egemaps_ids=[]

for participant_id in all_participants_ids:
    participant_dir=DATA_DIR/f"{participant_id}_P"
    wav_path=participant_dir/f"{participant_id}_AUDIO.wav"
    transcript_path=participant_dir/f"{participant_id}_Transcript.csv"
    egemaps_path=participant_dir/"features"/f"{participant_id}_OpenSMILE2.3.0_egemaps.csv"

    if not wav_path.exists():
        missing_wav_ids.append(participant_id)

    if not transcript_path.exists():
        missing_transcript_ids.append(participant_id)

    if not egemaps_path.exists():
        missing_egemaps_ids.append(participant_id)

print("全部参与者数量：", len(all_participants_ids))
print("缺失WAV数量：", len(missing_wav_ids))
print("缺失转录数量：", len(missing_transcript_ids))
print("缺失eGeMAPS数量：", len(missing_egemaps_ids))
print("缺失WAV参与者：", missing_wav_ids)
print("缺失转录参与者：", missing_transcript_ids)
print("缺失eGeMAPS参与者：", missing_egemaps_ids)

if missing_wav_ids or missing_transcript_ids or missing_egemaps_ids:
    raise FileNotFoundError("语音正式输入文件不完整")

print("全部语音输入文件检查通过")

全部参与者数量： 274
缺失WAV数量： 0
缺失转录数量： 0
缺失eGeMAPS数量： 0
缺失WAV参与者： []
缺失转录参与者： []
缺失eGeMAPS参与者： []
全部语音输入文件检查通过

In [76]:
def get_audio_input_paths(participant_id):
    participant_id=int(participant_id)
    participant_dir=DATA_DIR/f"{participant_id}_P"
    wav_path=participant_dir/f"{participant_id}_AUDIO.wav"
    transcript_path=participant_dir/f"{participant_id}_Transcript.csv"
    egemaps_path=participant_dir/"features"/f"{participant_id}_OpenSMILE2.3.0_egemaps.csv"
    return wav_path,transcript_path,egemaps_path

def get_file_signature(file_path):
    file_stat=file_path.stat()
    signature={}
    signature["size"]=file_stat.st_size
    signature["mtime_ns"]=file_stat.st_mtime_ns
    return signature

def clean_audio_turn_boundaries(transcript_df,audio_duration_seconds,feature_frame_count):
    start_times=(transcript_df["Start_Time"].to_numpy(dtype=np.float64)*FEATURE_RATE).tolist()
    end_times=(transcript_df["End_Time"].to_numpy(dtype=np.float64)*FEATURE_RATE).tolist()
    maximum_valid_frame=min(audio_duration_seconds*FEATURE_RATE,feature_frame_count)
    cleaned_start_times=[]
    cleaned_end_times=[]
    previous_start_time=-float("inf")
    previous_end_time=-float("inf")

    for start_time,end_time in zip(start_times,end_times):
        if not np.isfinite(start_time) or not np.isfinite(end_time):
            continue
        if start_time < previous_start_time or end_time < previous_end_time:
            continue
        if start_time < 0 or end_time > maximum_valid_frame:
            continue

        rounded_start_time=round(start_time)
        rounded_end_time=round(end_time)

        if rounded_start_time>=rounded_end_time:
            continue
        cleaned_start_times.append(rounded_start_time)
        cleaned_end_times.append(rounded_end_time)
        previous_start_time=rounded_start_time
        previous_end_time=rounded_end_time
    if len(cleaned_start_times)==0:
        raise ValueError("清理时间边界后没有有效对话伦茨")
    return cleaned_start_times,cleaned_end_times

def get_wav_duration_seconds(wav_path):
    with wave.open(str(wav_path),"rb") as wav_file:

        frame_count = wav_file.getnframes()
        sample_rate = wav_file.getframerate()

    if sample_rate <= 0:
        raise ValueError(f"WAV采样率不正确：{wav_path}")

    duration_seconds = frame_count / sample_rate
    return float(duration_seconds)
def compute_audio_features(pparticipant_id):
    participant_id=int(pparticipant_id)
    wav_path,transcript_path,egemaps_path=get_audio_input_paths(participant_id)
    if not wav_path.exists():
        raise FileNotFoundError(f"WAV文件不存在：{wav_path}")

    if not transcript_path.exists():
        raise FileNotFoundError(f"转录文件不存在：{transcript_path}")

    if not egemaps_path.exists():
        raise FileNotFoundError(f"eGeMAPS文件不存在：{egemaps_path}")

    transcript_df=pd.read_csv(transcript_path)
    egemaps_df=pd.read_csv(egemaps_path,sep=";")
    required_transcript_columns={"Start_Time","End_Time"}
    if not required_transcript_columns.issubset(transcript_df.columns):
        raise ValueError(f"参与者{participant_id}的转录文件缺少时间列")

    if egemaps_df.shape[1] < 3:
        raise ValueError(f"参与者{participant_id}的eGeMAPS列数不足")

    audio_feature_values=egemaps_df.iloc[:,2:].to_numpy(dtype=np.float32)
    if audio_feature_values.shape[1] != AUDIO_FEATURE_DIM:
        raise ValueError(f"参与者{participant_id}的语音特征维度为{audio_feature_values.shape[1]}，预期为{AUDIO_FEATURE_DIM}")

    if not np.isfinite(audio_feature_values).all():
        raise ValueError(f"参与者{participant_id}的语音特征包含NaN或Inf")

    audio_duration_seconds=get_wav_duration_seconds(wav_path)
    start_times,end_times=clean_audio_turn_boundaries(transcript_df,audio_duration_seconds,audio_feature_values.shape[0])
    audio_feature_tensor=torch.from_numpy(audio_feature_values)
    turn_vector_list=[]

    for start_time,end_time in zip(start_times,end_times):
        turn_frames=audio_feature_tensor[start_time:end_time]
        if turn_frames.shape[0]==0:
            continue
        turn_vector=turn_frames.mean(dim=0)
        turn_vector_list.append(turn_vector)
    if len(turn_vector_list)==0:
        raise ValueError(f"参与者{participant_id}没有可用语音轮次")

    turn_vectors=torch.stack(turn_vector_list, dim=0)
    real_turn_count=min(turn_vectors.shape[0], MAX_TURNS)
    fixed_audio_features=torch.zeros((MAX_TURNS,AUDIO_FEATURE_DIM),dtype=torch.float32)
    padding_mask=torch.ones(MAX_TURNS,dtype=torch.bool)
    fixed_audio_features[:real_turn_count]=turn_vectors[:real_turn_count]
    padding_mask[:real_turn_count]=False

    if fixed_audio_features.shape != (MAX_TURNS, AUDIO_FEATURE_DIM):
        raise RuntimeError("固定长度语音特征形状错误")

    if padding_mask.shape != (MAX_TURNS,):
        raise RuntimeError("语音Padding Mask形状错误")

    if not torch.isfinite(fixed_audio_features).all():
        raise RuntimeError(f"参与者{participant_id}处理后的语音特征包含NaN或Inf")

    metadata={}
    metadata["participant_id"] = participant_id
    metadata["cache_version"] = AUDIO_CACHE_VERSION
    metadata["feature_rate"] = FEATURE_RATE
    metadata["feature_dim"] = AUDIO_FEATURE_DIM
    metadata["max_turns"] = MAX_TURNS
    metadata["original_transcript_turns"] = len(transcript_df)
    metadata["cleaned_turns"] = len(turn_vector_list)
    metadata["real_turn_count"] = real_turn_count
    metadata["audio_duration_seconds"] = audio_duration_seconds
    metadata["wav_signature"] = get_file_signature(wav_path)
    metadata["transcript_signature"] = get_file_signature(transcript_path)
    metadata["egemaps_signature"] = get_file_signature(egemaps_path)

    return fixed_audio_features, padding_mask, real_turn_count, metadata

def get_audio_cache_path(participant_id):
    participant_id=int(participant_id)
    return AUDIO_CACHE_DIR/f"{participant_id}.pt"

def audio_cache_is_valid(cache_record,participant_id):
    participant_id=int(participant_id)
    wav_path,transcript_path,egemaps_path=get_audio_input_paths(participant_id)

    if cache_record.get("participant_id") != participant_id:
        return False

    if cache_record.get("cache_version") != AUDIO_CACHE_VERSION:
        return False

    if cache_record.get("feature_rate") != FEATURE_RATE:
        return False

    if cache_record.get("feature_dim") != AUDIO_FEATURE_DIM:
        return False

    if cache_record.get("max_turns") != MAX_TURNS:
        return False

    if cache_record.get("wav_signature") != get_file_signature(wav_path):
        return False

    if cache_record.get("transcript_signature") != get_file_signature(transcript_path):
        return False

    if cache_record.get("egemaps_signature") != get_file_signature(egemaps_path):
        return False

    if cache_record["audio_features"].shape != (MAX_TURNS, AUDIO_FEATURE_DIM):
        return False

    if cache_record["padding_mask"].shape != (MAX_TURNS,):
        return False

    return True

def get_participant_audio_features(participant_id,force_recompute=False):
    participant_id=int(participant_id)
    cache_path=get_audio_cache_path(participant_id)

    if cache_path.exists() and not force_recompute:
        cache_record=torch.load(cache_path,map_location="cpu",weights_only=False)

        if audio_cache_is_valid(cache_record,participant_id):
            return cache_record["audio_features"],cache_record["padding_mask"],cache_record["real_turn_count"],True

    audio_features,padding_mask,real_turn_count,metadata=compute_audio_features(participant_id)
    cache_record=dict(metadata)
    cache_record["audio_features"]=audio_features
    cache_record["padding_mask"]=padding_mask
    temporary_cache_path=cache_path.with_suffix(".tmp")
    torch.save(cache_record,temporary_cache_path)
    temporary_cache_path.replace(cache_path)

    return audio_features,padding_mask,real_turn_count,False

In [77]:
audio_cache_rows=[]
audio_cache_hit_count=0
audio_cache_miss_count=0

for index,participant_id in enumerate(all_participants_ids):
    audio_features,padding_mask,real_turn_count,cache_hit=get_participant_audio_features(participant_id)
    if cache_hit:
        audio_cache_hit_count += 1
    else:
        audio_cache_miss_count += 1

    row = {}
    row["Participant_ID"] = participant_id
    row["Real_Turn_Count"] = real_turn_count
    row["Padding_Turn_Count"] = int(padding_mask.sum().item())
    row["Cache_Hit"] = cache_hit
    audio_cache_rows.append(row)
    audio_cache_summary_df = pd.DataFrame(audio_cache_rows)

audio_cache_summary_df = pd.DataFrame(audio_cache_rows)
print("全部参与者数量：", len(audio_cache_summary_df))
print("缓存命中数量：", audio_cache_hit_count)
print("新建缓存数量：", audio_cache_miss_count)
print("最少真实轮数：", audio_cache_summary_df["Real_Turn_Count"].min())
print("最多真实轮数：", audio_cache_summary_df["Real_Turn_Count"].max())
print("缓存文件数量：", len(list(AUDIO_CACHE_DIR.glob("*.pt"))))

display(audio_cache_summary_df.head())

全部参与者数量： 274
缓存命中数量： 274
新建缓存数量： 0
最少真实轮数： 42
最多真实轮数： 120
缓存文件数量： 274

   Participant_ID  Real_Turn_Count  Padding_Turn_Count  Cache_Hit
0             300               76                  44       True
1             301               71                  49       True
2             302               98                  22       True
3             303               93                  27       True
4             304               79                  41       True

In [78]:
def set_seed(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)

    if torch.cuda.is_available():
        torch.cuda.manual_seed(seed)
        torch.cuda.manual_seed_all(seed)

    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

In [83]:
class CachedAudioPHQ8Dataset(Dataset):
    def __init__(self,metadata_df, split_name):
        super().__init__()
        if split_name not in {"train","val"}:
            raise ValueError("CachedAudioPHQ8Dataset只支持train或val")

        self.split_name=split_name
        self.metadata_df=metadata_df.reset_index(drop=True).copy()
        self.participant_ids=self.metadata_df["Participant_ID"].astype(int).tolist()
        self.labels=torch.tensor(self.metadata_df[PHQ8_QUESTION_COLUMNS].to_numpy(),dtype=torch.long)
        audio_feature_list=[]
        padding_mask_list=[]
        real_turn_count_list=[]
        cache_hit_count=0

        for participant_id in self.participant_ids:
            audio_features,padding_mask,real_turn_count,cache_hit=get_participant_audio_features(participant_id)
            audio_feature_list.append(audio_features)
            padding_mask_list.append(padding_mask)
            real_turn_count_list.append(real_turn_count)

            if cache_hit:
                cache_hit_count+=1

        self.audio_features=torch.stack(audio_feature_list,dim=0)
        self.padding_masks=torch.stack(padding_mask_list,dim=0)
        self.real_turn_counts=torch.tensor(real_turn_count_list,dtype=torch.long)
        self.cache_hit_count=cache_hit_count
        self.cache_miss_count=len(self.participant_ids)-cache_hit_count

        if self.audio_features.shape != (len(self.participant_ids), MAX_TURNS, AUDIO_FEATURE_DIM):
            raise RuntimeError(f"{split_name}语音特征整体形状错误：{self.audio_features.shape}")

        if self.padding_masks.shape != (len(self.participant_ids), MAX_TURNS):
            raise RuntimeError(f"{split_name} Mask整体形状错误：{self.padding_masks.shape}")

        if self.labels.shape != (len(self.participant_ids), len(PHQ8_QUESTION_COLUMNS)):
            raise RuntimeError(f"{split_name}标签整体形状错误：{self.labels.shape}")

        if not torch.isfinite(self.audio_features).all():
            raise RuntimeError(f"{split_name}语音特征存在NaN或Inf")

    def __len__(self):
        return len(self.participant_ids)
    def __getitem__(self, index):
        audio_features=self.audio_features[index]
        padding_mask=self.padding_masks[index]
        labels=self.labels[index]
        return audio_features,padding_mask,labels

In [84]:
train_audio_dataset = CachedAudioPHQ8Dataset(train_metadata_df, split_name="train")
val_audio_dataset = CachedAudioPHQ8Dataset(val_metadata_df, split_name="val")

print("训练样本数：", len(train_audio_dataset))
print("验证样本数：", len(val_audio_dataset))
print("训练语音特征：", train_audio_dataset.audio_features.shape)
print("训练Mask：", train_audio_dataset.padding_masks.shape)
print("训练全部标签：", train_audio_dataset.labels.shape)
print("验证语音特征：", val_audio_dataset.audio_features.shape)
print("验证Mask：", val_audio_dataset.padding_masks.shape)
print("验证全部标签：", val_audio_dataset.labels.shape)
print("训练缓存命中：", train_audio_dataset.cache_hit_count)
print("验证缓存命中：", val_audio_dataset.cache_hit_count)

训练样本数： 163
验证样本数： 55
训练语音特征： torch.Size([163, 120, 23])
训练Mask： torch.Size([163, 120])
训练全部标签： torch.Size([163, 8])
验证语音特征： torch.Size([55, 120, 23])
验证Mask： torch.Size([55, 120])
验证全部标签： torch.Size([55, 8])
训练缓存命中： 163
验证缓存命中： 55

In [85]:
def create_audio_dataloaders(seed):
    train_generator = torch.Generator()
    train_generator.manual_seed(seed)
    train_loader = DataLoader(train_audio_dataset, batch_size=BATCH_SIZE, shuffle=True, num_workers=0, drop_last=False, generator=train_generator)
    val_loader = DataLoader(val_audio_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=0, drop_last=False)
    return train_loader, val_loader

In [86]:
set_seed(42)
train_audio_loader, val_audio_loader = create_audio_dataloaders(seed=42)
batch_audio_features, batch_audio_masks, batch_all_labels = next(iter(train_audio_loader))

print("训练批次数：", len(train_audio_loader))
print("验证批次数：", len(val_audio_loader))
print("Batch语音特征：", batch_audio_features.shape)
print("Batch Mask：", batch_audio_masks.shape)
print("Batch全部标签：", batch_all_labels.shape)
print("当前Batch的Q1标签：", batch_all_labels[:, 0])
print("语音特征类型：", batch_audio_features.dtype)
print("Mask类型：", batch_audio_masks.dtype)
print("标签类型：", batch_all_labels.dtype)

训练批次数： 17
验证批次数： 6
Batch语音特征： torch.Size([10, 120, 23])
Batch Mask： torch.Size([10, 120])
Batch全部标签： torch.Size([10, 8])
当前Batch的Q1标签： tensor([1, 0, 1, 0, 0, 0, 0, 0, 0, 1])
语音特征类型： torch.float32
Mask类型： torch.bool
标签类型： torch.int64

In [88]:
class AudioLSTMAttentionClassifier(nn.Module):
    def __init__(self):
        super().__init__()
        self.lstm = nn.LSTM(input_size=AUDIO_FEATURE_DIM, hidden_size=LSTM_HIDDEN_SIZE, batch_first=True, bidirectional=True)
        self.attention1 = nn.MultiheadAttention(embed_dim=LSTM_HIDDEN_SIZE * 2, num_heads=ATTENTION_HEADS, dropout=0.2, batch_first=True)
        self.attention2 = nn.MultiheadAttention(embed_dim=LSTM_HIDDEN_SIZE * 2, num_heads=ATTENTION_HEADS, dropout=0.2, batch_first=True)
        self.mlp = nn.Sequential(nn.Flatten(), nn.Dropout(0.2), nn.Linear(MAX_TURNS * LSTM_HIDDEN_SIZE * 2, 256), nn.ReLU(), nn.Dropout(0.2), nn.Linear(256, NUM_CLASSES))

    def encode(self, audio_features, padding_mask):
        lstm_output, _ = self.lstm(audio_features)
        attention1_output, _ = self.attention1(lstm_output, lstm_output, lstm_output, key_padding_mask=padding_mask, need_weights=False)
        attention2_output, _ = self.attention2(attention1_output, attention1_output, attention1_output, key_padding_mask=padding_mask, need_weights=False)
        return attention2_output

    def forward(self, audio_features, padding_mask):
        encoded_audio = self.encode(audio_features, padding_mask)
        logits = self.mlp(encoded_audio)
        return logits

In [89]:
set_seed(42)
audio_model = AudioLSTMAttentionClassifier().to(device)

audio_lstm_parameters = sum(parameter.numel() for parameter in audio_model.lstm.parameters() if parameter.requires_grad)
audio_attention1_parameters = sum(parameter.numel() for parameter in audio_model.attention1.parameters() if parameter.requires_grad)
audio_attention2_parameters = sum(parameter.numel() for parameter in audio_model.attention2.parameters() if parameter.requires_grad)
audio_mlp_parameters = sum(parameter.numel() for parameter in audio_model.mlp.parameters() if parameter.requires_grad)
audio_total_parameters = sum(parameter.numel() for parameter in audio_model.parameters() if parameter.requires_grad)

print("模型设备：", next(audio_model.parameters()).device)
print("LSTM参数：", f"{audio_lstm_parameters:,}")
print("Attention1参数：", f"{audio_attention1_parameters:,}")
print("Attention2参数：", f"{audio_attention2_parameters:,}")
print("MLP参数：", f"{audio_mlp_parameters:,}")
print("总可训练参数：", f"{audio_total_parameters:,}")

模型设备： cuda:0
LSTM参数： 30,000
Attention1参数： 40,400
Attention2参数： 40,400
MLP参数： 3,073,284
总可训练参数： 3,184,084

In [90]:
batch_audio_features_on_device = batch_audio_features.to(device)
batch_audio_masks_on_device = batch_audio_masks.to(device)

audio_model.eval()

with torch.no_grad():
    batch_encoded_audio = audio_model.encode(batch_audio_features_on_device, batch_audio_masks_on_device)
    batch_audio_logits = audio_model(batch_audio_features_on_device, batch_audio_masks_on_device)
    batch_audio_probabilities = torch.softmax(batch_audio_logits, dim=1)
    batch_audio_predictions = torch.argmax(batch_audio_logits, dim=1)

print("模型输入形状：", batch_audio_features_on_device.shape)
print("Audio Encoder输出：", batch_encoded_audio.shape)
print("模型Logits形状：", batch_audio_logits.shape)
print("第一个样本Logits：", batch_audio_logits[0])
print("第一个样本概率：", batch_audio_probabilities[0])
print("概率之和：", batch_audio_probabilities[0].sum().item())
print("当前Batch预测：", batch_audio_predictions)
print("当前Batch真实Q1标签：", batch_all_labels[:, 0])

模型输入形状： torch.Size([10, 120, 23])
Audio Encoder输出： torch.Size([10, 120, 100])
模型Logits形状： torch.Size([10, 4])
第一个样本Logits： tensor([0.0470, 0.0119, 0.0338, 0.0695], device='cuda:0')
第一个样本概率： tensor([0.2516, 0.2429, 0.2483, 0.2573], device='cuda:0')
概率之和： 1.0
当前Batch预测： tensor([3, 3, 3, 3, 3, 3, 3, 3, 3, 3], device='cuda:0')
当前Batch真实Q1标签： tensor([1, 0, 1, 0, 0, 0, 0, 0, 0, 1])

In [91]:
def compute_audio_question_class_weights(labels_matrix, question_index, beta):
    question_labels = labels_matrix[:, question_index]
    class_counts = torch.bincount(question_labels, minlength=NUM_CLASSES).float()

    if torch.any(class_counts == 0):
        raise ValueError(f"第{question_index + 1}题存在训练样本数量为0的类别")

    total_count = class_counts.sum()
    class_weights = (total_count / class_counts).pow(beta)
    return class_counts, class_weights

In [92]:
audio_question_class_counts = []
audio_question_class_weights = []

for question_index in range(len(PHQ8_QUESTION_COLUMNS)):
    class_counts, class_weights = compute_audio_question_class_weights(train_audio_dataset.labels, question_index, BETA)
    audio_question_class_counts.append(class_counts)
    audio_question_class_weights.append(class_weights)

audio_question_class_counts = torch.stack(audio_question_class_counts, dim=0)
audio_question_class_weights = torch.stack(audio_question_class_weights, dim=0)

print("类别数量形状：", audio_question_class_counts.shape)
print("类别权重形状：", audio_question_class_weights.shape)
print("Q1类别数量：", audio_question_class_counts[0])
print("Q1类别权重：", audio_question_class_weights[0])

类别数量形状： torch.Size([8, 4])
类别权重形状： torch.Size([8, 4])
Q1类别数量： tensor([81., 57., 20.,  5.])
Q1类别权重： tensor([1.4186, 1.6910, 2.8548, 5.7096])

In [93]:
def imbalanced_ordinal_loss(logits, labels, class_weights, alpha=1.0, epsilon=1e-12):
    probabilities = torch.softmax(logits, dim=1)
    class_ids = torch.arange(NUM_CLASSES, device=logits.device)
    distances = torch.abs(labels.unsqueeze(1) - class_ids.unsqueeze(0)).float()
    true_class_weights = class_weights[labels].unsqueeze(1)
    weighted_distances = distances * true_class_weights
    probability_penalties = -torch.log(torch.clamp(1.0 - probabilities, min=epsilon))
    sample_losses = torch.sum(probability_penalties * weighted_distances.pow(alpha), dim=1)
    loss = sample_losses.mean()
    return loss

In [94]:
set_seed(42)
audio_step_model = AudioLSTMAttentionClassifier().to(device)
audio_step_optimizer = torch.optim.AdamW(audio_step_model.parameters(), lr=LEARNING_RATE, eps=ADAM_EPSILON, weight_decay=WEIGHT_DECAY)

q1_labels = batch_all_labels[:, 0].to(device)
q1_class_weights = audio_question_class_weights[0].to(device)
batch_audio_features_on_device = batch_audio_features.to(device)
batch_audio_masks_on_device = batch_audio_masks.to(device)

audio_step_model.train()
audio_step_optimizer.zero_grad(set_to_none=True)

q1_logits = audio_step_model(batch_audio_features_on_device, batch_audio_masks_on_device)
q1_loss = imbalanced_ordinal_loss(q1_logits, q1_labels, q1_class_weights, alpha=ALPHA, epsilon=LOSS_EPSILON)

final_linear_weight_before = audio_step_model.mlp[-1].weight.detach().clone()

q1_loss.backward()
gradient_norm_before_clipping = torch.nn.utils.clip_grad_norm_(audio_step_model.parameters(), MAX_GRAD_NORM)
audio_step_optimizer.step()

final_linear_weight_after = audio_step_model.mlp[-1].weight.detach().clone()
weight_change = torch.abs(final_linear_weight_after - final_linear_weight_before)
q1_predictions = torch.argmax(q1_logits.detach(), dim=1)
q1_accuracy = (q1_predictions == q1_labels).float().mean()

print("Logits形状：", q1_logits.shape)
print("Q1标签形状：", q1_labels.shape)
print("Q1类别权重：", q1_class_weights)
print("ImbOLL形状：", q1_loss.shape)
print("ImbOLL数值：", q1_loss.item())
print("损失是否有限：", torch.isfinite(q1_loss).item())
print("裁剪前梯度长度：", gradient_norm_before_clipping.item())
print("最终Linear权重平均变化：", weight_change.mean().item())
print("最终Linear权重最大变化：", weight_change.max().item())
print("当前Batch预测：", q1_predictions)
print("当前Batch真实标签：", q1_labels)
print("当前Batch Accuracy：", q1_accuracy.item())

Logits形状： torch.Size([10, 4])
Q1标签形状： torch.Size([10])
Q1类别权重： tensor([1.4186, 1.6910, 2.8548, 5.7096], device='cuda:0')
ImbOLL形状： torch.Size([])
ImbOLL数值： 2.327353000640869
损失是否有限： True
裁剪前梯度长度： 4.088662147521973
最终Linear权重平均变化： 0.00035151789779774845
最终Linear权重最大变化： 0.0005000308156013489
当前Batch预测： tensor([3, 0, 3, 3, 3, 3, 3, 3, 3, 3], device='cuda:0')
当前Batch真实标签： tensor([1, 0, 1, 0, 0, 0, 0, 0, 0, 1], device='cuda:0')
当前Batch Accuracy： 0.10000000149011612

In [95]:
def compute_ccc(predictions, labels, epsilon=1e-12):
    predictions = predictions.float()
    labels = labels.float()
    prediction_mean = predictions.mean()
    label_mean = labels.mean()
    prediction_variance = predictions.var(correction=1)
    label_variance = labels.var(correction=1)
    centered_predictions = predictions - prediction_mean
    centered_labels = labels - label_mean
    prediction_length = torch.sqrt(torch.sum(centered_predictions ** 2))
    label_length = torch.sqrt(torch.sum(centered_labels ** 2))

    if prediction_length.item() < epsilon or label_length.item() < epsilon:
        return 0.0

    correlation = torch.sum(centered_predictions * centered_labels) / (prediction_length * label_length)
    numerator = 2.0 * correlation * torch.sqrt(prediction_variance) * torch.sqrt(label_variance)
    denominator = prediction_variance + label_variance + (prediction_mean - label_mean) ** 2
    ccc = numerator / torch.clamp(denominator, min=epsilon)
    return float(ccc.item())


def compute_audio_metrics(predictions, labels):
    predictions = predictions.cpu().long()
    labels = labels.cpu().long()
    confusion_matrix = torch.zeros((NUM_CLASSES, NUM_CLASSES), dtype=torch.long)

    for true_label, predicted_label in zip(labels, predictions):
        confusion_matrix[true_label, predicted_label] += 1

    true_positive = confusion_matrix.diag().float()
    predicted_count = confusion_matrix.sum(dim=0).float()
    actual_count = confusion_matrix.sum(dim=1).float()
    precision = true_positive / torch.clamp(predicted_count, min=1.0)
    recall = true_positive / torch.clamp(actual_count, min=1.0)
    per_class_f1 = 2.0 * precision * recall / torch.clamp(precision + recall, min=1e-12)
    accuracy = (predictions == labels).float().mean().item()
    macro_f1 = per_class_f1.mean().item()
    weighted_f1 = (per_class_f1 * actual_count).sum().item() / actual_count.sum().item()
    ccc = compute_ccc(predictions, labels)
    rmse = torch.sqrt(torch.mean((predictions.float() - labels.float()) ** 2)).item()
    mae = torch.mean(torch.abs(predictions.float() - labels.float())).item()

    metrics = {}
    metrics["accuracy"] = accuracy
    metrics["micro_f1"] = accuracy
    metrics["macro_f1"] = macro_f1
    metrics["weighted_f1"] = weighted_f1
    metrics["ccc"] = ccc
    metrics["rmse"] = rmse
    metrics["mae"] = mae
    metrics["per_class_f1"] = per_class_f1
    metrics["confusion_matrix"] = confusion_matrix
    return metrics

In [96]:
def train_audio_one_epoch(model, dataloader, optimizer, question_index, class_weights, device, max_grad_norm):
    model.train()
    total_loss = 0.0
    total_sample_count = 0
    prediction_list = []
    label_list = []
    gradient_norm_list = []

    for batch_audio_features, batch_padding_masks, batch_all_labels in dataloader:
        batch_audio_features = batch_audio_features.to(device)
        batch_padding_masks = batch_padding_masks.to(device)
        batch_labels = batch_all_labels[:, question_index].to(device)
        optimizer.zero_grad(set_to_none=True)
        logits = model(batch_audio_features, batch_padding_masks)
        loss = imbalanced_ordinal_loss(logits, batch_labels, class_weights, alpha=ALPHA, epsilon=LOSS_EPSILON)

        if not torch.isfinite(loss):
            raise RuntimeError(f"训练损失出现NaN或Inf，第{question_index + 1}题")

        loss.backward()
        gradient_norm = torch.nn.utils.clip_grad_norm_(model.parameters(), max_grad_norm)
        optimizer.step()
        predictions = torch.argmax(logits.detach(), dim=1)
        batch_size = batch_labels.shape[0]
        total_loss += loss.item() * batch_size
        total_sample_count += batch_size
        prediction_list.append(predictions.cpu())
        label_list.append(batch_labels.cpu())
        gradient_norm_list.append(float(gradient_norm.item()))

    all_predictions = torch.cat(prediction_list, dim=0)
    all_labels = torch.cat(label_list, dim=0)
    metrics = compute_audio_metrics(all_predictions, all_labels)
    metrics["loss"] = total_loss / total_sample_count
    metrics["mean_gradient_norm"] = float(np.mean(gradient_norm_list))
    return metrics

In [97]:
def evaluate_audio_question(model, dataloader, question_index, class_weights, device):
    model.eval()
    total_loss = 0.0
    total_sample_count = 0
    prediction_list = []
    label_list = []

    with torch.no_grad():
        for batch_audio_features, batch_padding_masks, batch_all_labels in dataloader:
            batch_audio_features = batch_audio_features.to(device)
            batch_padding_masks = batch_padding_masks.to(device)
            batch_labels = batch_all_labels[:, question_index].to(device)
            logits = model(batch_audio_features, batch_padding_masks)
            loss = imbalanced_ordinal_loss(logits, batch_labels, class_weights, alpha=ALPHA, epsilon=LOSS_EPSILON)

            if not torch.isfinite(loss):
                raise RuntimeError(f"验证损失出现NaN或Inf，第{question_index + 1}题")

            predictions = torch.argmax(logits, dim=1)
            batch_size = batch_labels.shape[0]
            total_loss += loss.item() * batch_size
            total_sample_count += batch_size
            prediction_list.append(predictions.cpu())
            label_list.append(batch_labels.cpu())

    all_predictions = torch.cat(prediction_list, dim=0)
    all_labels = torch.cat(label_list, dim=0)
    metrics = compute_audio_metrics(all_predictions, all_labels)
    metrics["loss"] = total_loss / total_sample_count
    metrics["predictions"] = all_predictions
    metrics["labels"] = all_labels
    return metrics

In [98]:
def print_audio_epoch_result(epoch, train_metrics, val_metrics):
    print(f"Epoch {epoch:02d}/{NUM_EPOCHS} | Train Loss={train_metrics['loss']:.6f} | Val Loss={val_metrics['loss']:.6f} | Val Acc={val_metrics['accuracy']:.4f} | Val MacroF1={val_metrics['macro_f1']:.4f} | Val CCC={val_metrics['ccc']:.4f}")

In [99]:
set_seed(42)
audio_function_test_model = AudioLSTMAttentionClassifier().to(device)
audio_function_test_optimizer = torch.optim.AdamW(audio_function_test_model.parameters(), lr=LEARNING_RATE, eps=ADAM_EPSILON, weight_decay=WEIGHT_DECAY)
function_test_train_loader, function_test_val_loader = create_audio_dataloaders(seed=42)
function_test_class_weights = audio_question_class_weights[0].to(device)

function_test_train_metrics = train_audio_one_epoch(audio_function_test_model, function_test_train_loader, audio_function_test_optimizer, question_index=0, class_weights=function_test_class_weights, device=device, max_grad_norm=MAX_GRAD_NORM)
function_test_val_metrics = evaluate_audio_question(audio_function_test_model, function_test_val_loader, question_index=0, class_weights=function_test_class_weights, device=device)

print_audio_epoch_result(1, function_test_train_metrics, function_test_val_metrics)
print("训练平均梯度长度：", function_test_train_metrics["mean_gradient_norm"])
print("验证每类F1：", function_test_val_metrics["per_class_f1"])
print("验证混淆矩阵：")
print(function_test_val_metrics["confusion_matrix"])

Epoch 01/50 | Train Loss=2.296797 | Val Loss=2.603723 | Val Acc=0.4000 | Val MacroF1=0.1429 | Val CCC=0.0000
训练平均梯度长度： 5.266138651791741
验证每类F1： tensor([0.0000, 0.5714, 0.0000, 0.0000])
验证混淆矩阵：
tensor([[ 0, 25,  0,  0],
        [ 0, 22,  0,  0],
        [ 0,  4,  0,  0],
        [ 0,  4,  0,  0]])

In [100]:
def get_audio_experiment_paths(question_index, seed):
    question_number = question_index + 1
    experiment_dir = CHECKPOINT_ROOT / f"seed_{seed}" / f"question_{question_number}"
    experiment_dir.mkdir(parents=True, exist_ok=True)
    paths = {}
    paths["experiment_dir"] = experiment_dir
    paths["best_loss"] = experiment_dir / "best_loss.pt"
    paths["best_ccc"] = experiment_dir / "best_ccc.pt"
    paths["last"] = experiment_dir / "last.pt"
    paths["history"] = experiment_dir / "history.csv"
    return paths

In [101]:
def copy_state_dict_to_cpu(state_dict):
    return {name: tensor.detach().cpu() for name, tensor in state_dict.items()}


def metrics_for_checkpoint(metrics):
    saved_metrics = {}

    for key, value in metrics.items():
        if key in {"predictions", "labels"}:
            continue

        if isinstance(value, torch.Tensor):
            saved_metrics[key] = value.detach().cpu()
        else:
            saved_metrics[key] = value

    return saved_metrics


def save_audio_checkpoint(path, checkpoint_type, model, optimizer, epoch, question_index, seed, train_metrics, val_metrics, class_counts, class_weights, best_val_loss, best_val_ccc, best_loss_epoch, best_ccc_epoch, include_optimizer):
    checkpoint = {}
    checkpoint["checkpoint_type"] = checkpoint_type
    checkpoint["epoch"] = epoch
    checkpoint["question_index"] = question_index
    checkpoint["question_number"] = question_index + 1
    checkpoint["question"] = PHQ8_QUESTION_COLUMNS[question_index]
    checkpoint["seed"] = seed
    checkpoint["model_state_dict"] = copy_state_dict_to_cpu(model.state_dict())
    checkpoint["optimizer_state_dict"] = optimizer.state_dict() if include_optimizer else None
    checkpoint["train_metrics"] = metrics_for_checkpoint(train_metrics)
    checkpoint["val_metrics"] = metrics_for_checkpoint(val_metrics)
    checkpoint["class_counts"] = class_counts.detach().cpu()
    checkpoint["class_weights"] = class_weights.detach().cpu()
    checkpoint["best_val_loss"] = best_val_loss
    checkpoint["best_val_ccc"] = best_val_ccc
    checkpoint["best_loss_epoch"] = best_loss_epoch
    checkpoint["best_ccc_epoch"] = best_ccc_epoch
    checkpoint["config"] = {"audio_feature_dim": AUDIO_FEATURE_DIM, "max_turns": MAX_TURNS, "lstm_hidden_size": LSTM_HIDDEN_SIZE, "attention_heads": ATTENTION_HEADS, "num_classes": NUM_CLASSES, "batch_size": BATCH_SIZE, "num_epochs": NUM_EPOCHS, "learning_rate": LEARNING_RATE, "adam_epsilon": ADAM_EPSILON, "weight_decay": WEIGHT_DECAY, "max_grad_norm": MAX_GRAD_NORM, "alpha": ALPHA, "beta": BETA, "audio_cache_version": AUDIO_CACHE_VERSION}
    torch.save(checkpoint, path)

In [102]:
def train_single_audio_question(question_index, seed, num_epochs=NUM_EPOCHS):
    set_seed(seed)
    paths = get_audio_experiment_paths(question_index, seed)
    train_loader, val_loader = create_audio_dataloaders(seed)
    model = AudioLSTMAttentionClassifier().to(device)
    optimizer = torch.optim.AdamW(model.parameters(), lr=LEARNING_RATE, eps=ADAM_EPSILON, weight_decay=WEIGHT_DECAY)
    class_counts = audio_question_class_counts[question_index].clone()
    class_weights_cpu = audio_question_class_weights[question_index].clone()
    class_weights = class_weights_cpu.to(device)
    best_val_loss = float("inf")
    best_val_ccc = -float("inf")
    best_loss_epoch = 0
    best_ccc_epoch = 0
    history_rows = []
    training_start_time = time.time()

    print("=" * 70)
    print(f"开始正式训练：Q{question_index + 1} {PHQ8_QUESTION_COLUMNS[question_index]}，Seed={seed}")
    print("=" * 70)

    for epoch in range(1, num_epochs + 1):
        epoch_start_time = time.time()
        train_metrics = train_audio_one_epoch(model, train_loader, optimizer, question_index, class_weights, device, MAX_GRAD_NORM)
        val_metrics = evaluate_audio_question(model, val_loader, question_index, class_weights, device)
        epoch_seconds = time.time() - epoch_start_time

        history_row = {}
        history_row["Epoch"] = epoch
        history_row["Train_Loss"] = train_metrics["loss"]
        history_row["Train_Accuracy"] = train_metrics["accuracy"]
        history_row["Train_Macro_F1"] = train_metrics["macro_f1"]
        history_row["Train_CCC"] = train_metrics["ccc"]
        history_row["Mean_Gradient_Norm"] = train_metrics["mean_gradient_norm"]
        history_row["Val_Loss"] = val_metrics["loss"]
        history_row["Val_Accuracy"] = val_metrics["accuracy"]
        history_row["Val_Macro_F1"] = val_metrics["macro_f1"]
        history_row["Val_Weighted_F1"] = val_metrics["weighted_f1"]
        history_row["Val_CCC"] = val_metrics["ccc"]
        history_row["Val_RMSE"] = val_metrics["rmse"]
        history_row["Val_MAE"] = val_metrics["mae"]
        history_row["Epoch_Seconds"] = epoch_seconds
        history_rows.append(history_row)

        if val_metrics["loss"] < best_val_loss:
            best_val_loss = val_metrics["loss"]
            best_loss_epoch = epoch
            save_audio_checkpoint(paths["best_loss"], "best_loss", model, optimizer, epoch, question_index, seed, train_metrics, val_metrics, class_counts, class_weights_cpu, best_val_loss, best_val_ccc, best_loss_epoch, best_ccc_epoch, include_optimizer=False)

        if val_metrics["ccc"] > best_val_ccc:
            best_val_ccc = val_metrics["ccc"]
            best_ccc_epoch = epoch
            save_audio_checkpoint(paths["best_ccc"], "best_ccc", model, optimizer, epoch, question_index, seed, train_metrics, val_metrics, class_counts, class_weights_cpu, best_val_loss, best_val_ccc, best_loss_epoch, best_ccc_epoch, include_optimizer=False)

        print_audio_epoch_result(epoch, train_metrics, val_metrics)

    save_audio_checkpoint(paths["last"], "last", model, optimizer, num_epochs, question_index, seed, train_metrics, val_metrics, class_counts, class_weights_cpu, best_val_loss, best_val_ccc, best_loss_epoch, best_ccc_epoch, include_optimizer=True)

    history_df = pd.DataFrame(history_rows)
    history_df.to_csv(paths["history"], index=False)
    elapsed_seconds = time.time() - training_start_time

    result = {}
    result["question_index"] = question_index
    result["question_number"] = question_index + 1
    result["question"] = PHQ8_QUESTION_COLUMNS[question_index]
    result["seed"] = seed
    result["best_val_loss"] = best_val_loss
    result["best_loss_epoch"] = best_loss_epoch
    result["best_val_ccc"] = best_val_ccc
    result["best_ccc_epoch"] = best_ccc_epoch
    result["best_loss_path"] = paths["best_loss"]
    result["best_ccc_path"] = paths["best_ccc"]
    result["last_path"] = paths["last"]
    result["history_path"] = paths["history"]
    result["history_df"] = history_df
    result["elapsed_seconds"] = elapsed_seconds

    print("=" * 70)
    print(f"Q{question_index + 1} Seed={seed}训练结束")
    print(f"最佳验证Loss：{best_val_loss:.6f}，Epoch {best_loss_epoch}")
    print(f"最佳验证CCC：{best_val_ccc:.6f}，Epoch {best_ccc_epoch}")
    print(f"总耗时：{elapsed_seconds:.2f}秒")
    print(f"Best Loss：{paths['best_loss']}")
    print(f"Best CCC：{paths['best_ccc']}")
    print(f"Last：{paths['last']}")
    print("=" * 70)

    return result

In [103]:
audio_q1_seed42_result = train_single_audio_question(question_index=0, seed=42)

======================================================================
开始正式训练：Q1 PHQ_8NoInterest，Seed=42
======================================================================
Epoch 01/50 | Train Loss=2.296797 | Val Loss=2.603723 | Val Acc=0.4000 | Val MacroF1=0.1429 | Val CCC=0.0000
Epoch 02/50 | Train Loss=2.160058 | Val Loss=2.566039 | Val Acc=0.4000 | Val MacroF1=0.1429 | Val CCC=0.0000
Epoch 03/50 | Train Loss=2.158615 | Val Loss=2.549071 | Val Acc=0.4000 | Val MacroF1=0.1429 | Val CCC=0.0000
Epoch 04/50 | Train Loss=2.180788 | Val Loss=2.565554 | Val Acc=0.4000 | Val MacroF1=0.1429 | Val CCC=0.0000
Epoch 05/50 | Train Loss=2.115467 | Val Loss=2.579630 | Val Acc=0.4000 | Val MacroF1=0.1429 | Val CCC=0.0000
Epoch 06/50 | Train Loss=2.180418 | Val Loss=2.620130 | Val Acc=0.4000 | Val MacroF1=0.1429 | Val CCC=0.0000
Epoch 07/50 | Train Loss=2.138356 | Val Loss=2.553385 | Val Acc=0.4000 | Val MacroF1=0.1429 | Val CCC=0.0000
Epoch 08/50 | Train Loss=2.133307 | Val Loss=2.552493 | Val Acc=0.4000 | Val MacroF1=0.1429 | Val CCC=0.0000
Epoch 09/50 | Train Loss=2.146451 | Val Loss=2.675855 | Val Acc=0.4727 | Val MacroF1=0.1800 | Val CCC=0.0065
Epoch 10/50 | Train Loss=2.056674 | Val Loss=2.548061 | Val Acc=0.3818 | Val MacroF1=0.1382 | Val CCC=0.0102
Epoch 11/50 | Train Loss=2.009048 | Val Loss=2.623440 | Val Acc=0.3091 | Val MacroF1=0.1561 | Val CCC=0.1421
Epoch 12/50 | Train Loss=2.135214 | Val Loss=2.892525 | Val Acc=0.1636 | Val MacroF1=0.1149 | Val CCC=0.0364
Epoch 13/50 | Train Loss=2.168587 | Val Loss=2.606687 | Val Acc=0.4000 | Val MacroF1=0.1429 | Val CCC=0.0000
Epoch 14/50 | Train Loss=2.032851 | Val Loss=2.565153 | Val Acc=0.3818 | Val MacroF1=0.2519 | Val CCC=0.1518
Epoch 15/50 | Train Loss=2.056525 | Val Loss=2.642758 | Val Acc=0.5091 | Val MacroF1=0.2688 | Val CCC=0.1263
Epoch 16/50 | Train Loss=2.079098 | Val Loss=2.558858 | Val Acc=0.2364 | Val MacroF1=0.1244 | Val CCC=0.1195
Epoch 17/50 | Train Loss=1.992453 | Val Loss=2.637340 | Val Acc=0.5455 | Val MacroF1=0.2832 | Val CCC=0.0773
Epoch 18/50 | Train Loss=2.017677 | Val Loss=2.661796 | Val Acc=0.4182 | Val MacroF1=0.2483 | Val CCC=0.1440
Epoch 19/50 | Train Loss=2.016128 | Val Loss=2.572533 | Val Acc=0.2909 | Val MacroF1=0.1466 | Val CCC=0.0908
Epoch 20/50 | Train Loss=2.050022 | Val Loss=2.594114 | Val Acc=0.3091 | Val MacroF1=0.1214 | Val CCC=0.0962
Epoch 21/50 | Train Loss=2.066184 | Val Loss=2.616794 | Val Acc=0.4000 | Val MacroF1=0.1429 | Val CCC=0.0000
Epoch 22/50 | Train Loss=1.975870 | Val Loss=2.596366 | Val Acc=0.2909 | Val MacroF1=0.1466 | Val CCC=0.0908
Epoch 23/50 | Train Loss=2.033407 | Val Loss=2.605478 | Val Acc=0.4000 | Val MacroF1=0.1429 | Val CCC=0.0000
Epoch 24/50 | Train Loss=2.038596 | Val Loss=2.558401 | Val Acc=0.2182 | Val MacroF1=0.1173 | Val CCC=0.1006
Epoch 25/50 | Train Loss=1.982426 | Val Loss=2.609590 | Val Acc=0.3636 | Val MacroF1=0.1370 | Val CCC=0.0766
Epoch 26/50 | Train Loss=2.040300 | Val Loss=2.649250 | Val Acc=0.2909 | Val MacroF1=0.1470 | Val CCC=0.1180
Epoch 27/50 | Train Loss=2.018697 | Val Loss=2.624097 | Val Acc=0.4000 | Val MacroF1=0.1429 | Val CCC=0.0000
Epoch 28/50 | Train Loss=2.006815 | Val Loss=2.641453 | Val Acc=0.2909 | Val MacroF1=0.1466 | Val CCC=0.0908
Epoch 29/50 | Train Loss=1.984325 | Val Loss=2.648231 | Val Acc=0.3273 | Val MacroF1=0.1984 | Val CCC=0.0381
Epoch 30/50 | Train Loss=1.995780 | Val Loss=2.651532 | Val Acc=0.5273 | Val MacroF1=0.2807 | Val CCC=0.0529
Epoch 31/50 | Train Loss=1.964467 | Val Loss=2.610960 | Val Acc=0.3091 | Val MacroF1=0.1232 | Val CCC=-0.0392
Epoch 32/50 | Train Loss=1.977778 | Val Loss=2.664334 | Val Acc=0.4909 | Val MacroF1=0.2626 | Val CCC=0.0465
Epoch 33/50 | Train Loss=2.013617 | Val Loss=2.623776 | Val Acc=0.2727 | Val MacroF1=0.1389 | Val CCC=0.0706
Epoch 34/50 | Train Loss=2.056307 | Val Loss=2.639621 | Val Acc=0.4364 | Val MacroF1=0.2171 | Val CCC=0.0969
Epoch 35/50 | Train Loss=2.025552 | Val Loss=2.610994 | Val Acc=0.4000 | Val MacroF1=0.1429 | Val CCC=0.0000
Epoch 36/50 | Train Loss=2.006908 | Val Loss=2.667388 | Val Acc=0.4364 | Val MacroF1=0.2151 | Val CCC=0.1179
Epoch 37/50 | Train Loss=1.933716 | Val Loss=2.623654 | Val Acc=0.3273 | Val MacroF1=0.1250 | Val CCC=0.0070
Epoch 38/50 | Train Loss=1.956660 | Val Loss=2.654174 | Val Acc=0.4000 | Val MacroF1=0.2218 | Val CCC=0.1249
Epoch 39/50 | Train Loss=1.962859 | Val Loss=2.602343 | Val Acc=0.4000 | Val MacroF1=0.1429 | Val CCC=0.0000
Epoch 40/50 | Train Loss=1.961818 | Val Loss=2.684387 | Val Acc=0.2364 | Val MacroF1=0.1282 | Val CCC=0.0037
Epoch 41/50 | Train Loss=1.952531 | Val Loss=2.651392 | Val Acc=0.4364 | Val MacroF1=0.2364 | Val CCC=0.0748
Epoch 42/50 | Train Loss=1.951777 | Val Loss=2.782875 | Val Acc=0.3636 | Val MacroF1=0.2255 | Val CCC=0.1101
Epoch 43/50 | Train Loss=2.173417 | Val Loss=2.676641 | Val Acc=0.3818 | Val MacroF1=0.1382 | Val CCC=0.0102
Epoch 44/50 | Train Loss=1.954293 | Val Loss=2.692010 | Val Acc=0.4182 | Val MacroF1=0.2442 | Val CCC=0.1077
Epoch 45/50 | Train Loss=1.919034 | Val Loss=2.631841 | Val Acc=0.4545 | Val MacroF1=0.2331 | Val CCC=0.0843
Epoch 46/50 | Train Loss=2.031444 | Val Loss=2.647437 | Val Acc=0.4182 | Val MacroF1=0.2002 | Val CCC=0.0232
Epoch 47/50 | Train Loss=1.939445 | Val Loss=2.678876 | Val Acc=0.2909 | Val MacroF1=0.1194 | Val CCC=0.0458
Epoch 48/50 | Train Loss=1.892571 | Val Loss=2.734561 | Val Acc=0.5273 | Val MacroF1=0.2802 | Val CCC=0.1349
Epoch 49/50 | Train Loss=2.176455 | Val Loss=2.652452 | Val Acc=0.3636 | Val MacroF1=0.1333 | Val CCC=0.0198
Epoch 50/50 | Train Loss=2.011734 | Val Loss=2.603335 | Val Acc=0.3636 | Val MacroF1=0.1333 | Val CCC=0.0198
======================================================================
Q1 Seed=42训练结束
最佳验证Loss：2.548061，Epoch 10
最佳验证CCC：0.151781，Epoch 14
总耗时：18.84秒
Best Loss：/workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_42/question_1/best_loss.pt
Best CCC：/workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_42/question_1/best_ccc.pt
Last：/workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_42/question_1/last.pt
======================================================================

In [104]:
print("Best Loss存在：", audio_q1_seed42_result["best_loss_path"].exists())
print("Best CCC存在：", audio_q1_seed42_result["best_ccc_path"].exists())
print("Last存在：", audio_q1_seed42_result["last_path"].exists())
print("历史记录轮数：", len(audio_q1_seed42_result["history_df"]))
display(audio_q1_seed42_result["history_df"].tail())

Best Loss存在： True
Best CCC存在： True
Last存在： True
历史记录轮数： 50

,Epoch,Train_Loss,Train_Accuracy,Train_Macro_F1,Train_CCC,Mean_Gradient_Norm,Val_Loss,Val_Accuracy,Val_Macro_F1,Val_Weighted_F1,Val_CCC,Val_RMSE,Val_MAE,Epoch_Seconds
45,46,2.031444,0.435583,0.275022,0.140930,39.993144,2.647437,0.418182,0.200181,0.333926,0.023204,0.943880,0.672727,0.364249
46,47,1.939445,0.398773,0.265614,0.191613,47.821966,2.678876,0.290909,0.119403,0.191045,0.045796,1.018019,0.818182,0.357451
47,48,1.892571,0.484663,0.365984,0.335373,28.553006,2.734561,0.527273,0.280172,0.482132,0.134901,0.990867,0.618182,0.357039
48,49,2.176455,0.521472,0.271317,0.198464,29.361758,2.652452,0.363636,0.133333,0.213333,0.019750,0.924416,0.709091,0.374563
49,50,2.011734,0.368098,0.232432,0.168344,41.008999,2.603335,0.363636,0.133333,0.213333,0.019750,0.924416,0.709091,0.385962

In [105]:
def load_audio_question_model(checkpoint_path, expected_question_index=None, expected_seed=None):
    checkpoint = torch.load(checkpoint_path, map_location="cpu", weights_only=False)

    if expected_question_index is not None and checkpoint["question_index"] != expected_question_index:
        raise RuntimeError(f"Checkpoint题目不一致：实际{checkpoint['question_index']}，预期{expected_question_index}")

    if expected_seed is not None and checkpoint["seed"] != expected_seed:
        raise RuntimeError(f"Checkpoint Seed不一致：实际{checkpoint['seed']}，预期{expected_seed}")

    model = AudioLSTMAttentionClassifier()
    load_result = model.load_state_dict(checkpoint["model_state_dict"], strict=True)
    model = model.to(device)
    model.eval()

    print("已加载Checkpoint：", checkpoint_path)
    print("Checkpoint类型：", checkpoint["checkpoint_type"])
    print("保存Epoch：", checkpoint["epoch"])
    print("题目：", checkpoint["question"])
    print("Seed：", checkpoint["seed"])
    print("缺少参数：", load_result.missing_keys)
    print("多余参数：", load_result.unexpected_keys)

    return model, checkpoint

In [106]:
audio_q1_best_loss_model, audio_q1_best_loss_checkpoint = load_audio_question_model(audio_q1_seed42_result["best_loss_path"], expected_question_index=0, expected_seed=42)
audio_q1_class_weights_device = audio_q1_best_loss_checkpoint["class_weights"].to(device)
audio_q1_best_loss_metrics = evaluate_audio_question(audio_q1_best_loss_model, val_audio_loader, question_index=0, class_weights=audio_q1_class_weights_device, device=device)
audio_q1_saved_best_loss = float(audio_q1_best_loss_checkpoint["val_metrics"]["loss"])
audio_q1_restored_best_loss = float(audio_q1_best_loss_metrics["loss"])
audio_q1_best_loss_difference = abs(audio_q1_saved_best_loss - audio_q1_restored_best_loss)

print("Checkpoint记录的Loss：", audio_q1_saved_best_loss)
print("重新计算的Loss：", audio_q1_restored_best_loss)
print("Loss差值：", audio_q1_best_loss_difference)
print("Checkpoint记录的CCC：", audio_q1_best_loss_checkpoint["val_metrics"]["ccc"])
print("重新计算的CCC：", audio_q1_best_loss_metrics["ccc"])
print("混淆矩阵：")
print(audio_q1_best_loss_metrics["confusion_matrix"])

已加载Checkpoint： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_42/question_1/best_loss.pt
Checkpoint类型： best_loss
保存Epoch： 10
题目： PHQ_8NoInterest
Seed： 42
缺少参数： []
多余参数： []
Checkpoint记录的Loss： 2.548061175779863
重新计算的Loss： 2.548061175779863
Loss差值： 0.0
Checkpoint记录的CCC： 0.01018634531646967
重新计算的CCC： 0.01018634531646967
混淆矩阵：
tensor([[ 0, 25,  0,  0],
        [ 0, 21,  1,  0],
        [ 0,  4,  0,  0],
        [ 0,  4,  0,  0]])

In [107]:
audio_q1_best_ccc_model, audio_q1_best_ccc_checkpoint = load_audio_question_model(audio_q1_seed42_result["best_ccc_path"], expected_question_index=0, expected_seed=42)
audio_q1_class_weights_device = audio_q1_best_ccc_checkpoint["class_weights"].to(device)
audio_q1_best_ccc_metrics = evaluate_audio_question(audio_q1_best_ccc_model, val_audio_loader, question_index=0, class_weights=audio_q1_class_weights_device, device=device)
audio_q1_saved_best_ccc = float(audio_q1_best_ccc_checkpoint["val_metrics"]["ccc"])
audio_q1_restored_best_ccc = float(audio_q1_best_ccc_metrics["ccc"])
audio_q1_best_ccc_difference = abs(audio_q1_saved_best_ccc - audio_q1_restored_best_ccc)

print("Checkpoint记录的CCC：", audio_q1_saved_best_ccc)
print("重新计算的CCC：", audio_q1_restored_best_ccc)
print("CCC差值：", audio_q1_best_ccc_difference)
print("Checkpoint记录的Loss：", audio_q1_best_ccc_checkpoint["val_metrics"]["loss"])
print("重新计算的Loss：", audio_q1_best_ccc_metrics["loss"])
print("Accuracy：", audio_q1_best_ccc_metrics["accuracy"])
print("Macro F1：", audio_q1_best_ccc_metrics["macro_f1"])
print("每类F1：", audio_q1_best_ccc_metrics["per_class_f1"])
print("混淆矩阵：")
print(audio_q1_best_ccc_metrics["confusion_matrix"])

已加载Checkpoint： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_42/question_1/best_ccc.pt
Checkpoint类型： best_ccc
保存Epoch： 14
题目： PHQ_8NoInterest
Seed： 42
缺少参数： []
多余参数： []
Checkpoint记录的CCC： 0.1517808735370636
重新计算的CCC： 0.1517808735370636
CCC差值： 0.0
Checkpoint记录的Loss： 2.5651531436226587
重新计算的Loss： 2.5651531436226587
Accuracy： 0.38181817531585693
Macro F1： 0.251932829618454
每类F1： tensor([0.5106, 0.3721, 0.1250, 0.0000])
混淆矩阵：
tensor([[12, 10,  3,  0],
        [ 7,  8,  7,  0],
        [ 2,  1,  1,  0],
        [ 1,  2,  1,  0]])

In [108]:
def load_completed_audio_experiment(question_index, seed):
    paths = get_audio_experiment_paths(question_index, seed)
    required_paths = [paths["best_loss"], paths["best_ccc"], paths["last"], paths["history"]]

    if not all(path.exists() for path in required_paths):
        return None

    best_loss_checkpoint = torch.load(paths["best_loss"], map_location="cpu", weights_only=False)
    best_ccc_checkpoint = torch.load(paths["best_ccc"], map_location="cpu", weights_only=False)
    last_checkpoint = torch.load(paths["last"], map_location="cpu", weights_only=False)
    history_df = pd.read_csv(paths["history"])

    if best_loss_checkpoint["question_index"] != question_index:
        return None

    if best_ccc_checkpoint["question_index"] != question_index:
        return None

    if last_checkpoint["question_index"] != question_index:
        return None

    if best_loss_checkpoint["seed"] != seed:
        return None

    if best_ccc_checkpoint["seed"] != seed:
        return None

    if last_checkpoint["seed"] != seed:
        return None

    if last_checkpoint["epoch"] != NUM_EPOCHS:
        return None

    if len(history_df) != NUM_EPOCHS:
        return None

    result = {}
    result["question_index"] = question_index
    result["question_number"] = question_index + 1
    result["question"] = PHQ8_QUESTION_COLUMNS[question_index]
    result["seed"] = seed
    result["best_val_loss"] = float(best_loss_checkpoint["val_metrics"]["loss"])
    result["best_loss_epoch"] = int(best_loss_checkpoint["epoch"])
    result["best_val_ccc"] = float(best_ccc_checkpoint["val_metrics"]["ccc"])
    result["best_ccc_epoch"] = int(best_ccc_checkpoint["epoch"])
    result["best_loss_path"] = paths["best_loss"]
    result["best_ccc_path"] = paths["best_ccc"]
    result["last_path"] = paths["last"]
    result["history_path"] = paths["history"]
    result["history_df"] = history_df
    result["elapsed_seconds"] = float(history_df["Epoch_Seconds"].sum())
    result["loaded_from_disk"] = True
    return result

In [109]:
def load_completed_audio_experiment(question_index, seed):
    paths = get_audio_experiment_paths(question_index, seed)
    required_paths = [paths["best_loss"], paths["best_ccc"], paths["last"], paths["history"]]

    if not all(path.exists() for path in required_paths):
        return None

    best_loss_checkpoint = torch.load(paths["best_loss"], map_location="cpu", weights_only=False)
    best_ccc_checkpoint = torch.load(paths["best_ccc"], map_location="cpu", weights_only=False)
    last_checkpoint = torch.load(paths["last"], map_location="cpu", weights_only=False)
    history_df = pd.read_csv(paths["history"])

    if best_loss_checkpoint["question_index"] != question_index:
        return None

    if best_ccc_checkpoint["question_index"] != question_index:
        return None

    if last_checkpoint["question_index"] != question_index:
        return None

    if best_loss_checkpoint["seed"] != seed:
        return None

    if best_ccc_checkpoint["seed"] != seed:
        return None

    if last_checkpoint["seed"] != seed:
        return None

    if last_checkpoint["epoch"] != NUM_EPOCHS:
        return None

    if len(history_df) != NUM_EPOCHS:
        return None

    result = {}
    result["question_index"] = question_index
    result["question_number"] = question_index + 1
    result["question"] = PHQ8_QUESTION_COLUMNS[question_index]
    result["seed"] = seed
    result["best_val_loss"] = float(best_loss_checkpoint["val_metrics"]["loss"])
    result["best_loss_epoch"] = int(best_loss_checkpoint["epoch"])
    result["best_val_ccc"] = float(best_ccc_checkpoint["val_metrics"]["ccc"])
    result["best_ccc_epoch"] = int(best_ccc_checkpoint["epoch"])
    result["best_loss_path"] = paths["best_loss"]
    result["best_ccc_path"] = paths["best_ccc"]
    result["last_path"] = paths["last"]
    result["history_path"] = paths["history"]
    result["history_df"] = history_df
    result["elapsed_seconds"] = float(history_df["Epoch_Seconds"].sum())
    result["loaded_from_disk"] = True
    return result

In [110]:
def train_or_load_audio_question(question_index, seed):
    completed_result = load_completed_audio_experiment(question_index, seed)

    if completed_result is not None:
        print(f"Q{question_index + 1} Seed={seed}已经完成，直接读取磁盘结果")
        return completed_result

    print(f"Q{question_index + 1} Seed={seed}尚未完成，开始正式训练")
    result = train_single_audio_question(question_index=question_index, seed=seed, num_epochs=NUM_EPOCHS)
    result["loaded_from_disk"] = False
    return result

In [111]:
def train_all_audio_questions_for_seed(seed):
    seed_results = []
    seed_start_time = time.time()

    print()
    print("#" * 80)
    print(f"开始处理Audio-only全部8道题，Seed={seed}")
    print("#" * 80)

    for question_index in range(len(PHQ8_QUESTION_COLUMNS)):
        question_result = train_or_load_audio_question(question_index, seed)
        seed_results.append(question_result)

    summary_rows = []

    for result in seed_results:
        row = {}
        row["Question_Number"] = result["question_number"]
        row["Question"] = result["question"]
        row["Seed"] = result["seed"]
        row["Best_Loss"] = result["best_val_loss"]
        row["Best_Loss_Epoch"] = result["best_loss_epoch"]
        row["Best_CCC"] = result["best_val_ccc"]
        row["Best_CCC_Epoch"] = result["best_ccc_epoch"]
        row["Loaded_From_Disk"] = result["loaded_from_disk"]
        row["Elapsed_Seconds"] = result["elapsed_seconds"]
        summary_rows.append(row)

    summary_df = pd.DataFrame(summary_rows)
    summary_path = CHECKPOINT_ROOT / f"seed_{seed}_question_summary.csv"
    summary_df.to_csv(summary_path, index=False)
    seed_elapsed_seconds = time.time() - seed_start_time

    print()
    print("#" * 80)
    print(f"Audio-only Seed={seed}的8道题全部完成")
    print(f"本次运行耗时：{seed_elapsed_seconds:.2f}秒")
    print(f"8道题平均最佳验证CCC：{summary_df['Best_CCC'].mean():.6f}")
    print(f"汇总文件：{summary_path}")
    print("#" * 80)

    return seed_results, summary_df

In [112]:
del audio_q1_best_loss_model
del audio_q1_best_ccc_model

if torch.cuda.is_available():
    torch.cuda.empty_cache()

In [113]:
audio_seed42_results, audio_seed42_summary_df = train_all_audio_questions_for_seed(seed=42)
display(audio_seed42_summary_df)

################################################################################
开始处理Audio-only全部8道题，Seed=42
################################################################################
Q1 Seed=42已经完成，直接读取磁盘结果
Q2 Seed=42尚未完成，开始正式训练
======================================================================
开始正式训练：Q2 PHQ_8Depressed，Seed=42
======================================================================
Epoch 01/50 | Train Loss=2.520217 | Val Loss=2.414230 | Val Acc=0.3455 | Val MacroF1=0.1284 | Val CCC=0.0000
Epoch 02/50 | Train Loss=2.568020 | Val Loss=2.365933 | Val Acc=0.3455 | Val MacroF1=0.1284 | Val CCC=0.0000
Epoch 03/50 | Train Loss=2.437933 | Val Loss=2.373367 | Val Acc=0.3455 | Val MacroF1=0.1284 | Val CCC=0.0000
Epoch 04/50 | Train Loss=2.434529 | Val Loss=2.331725 | Val Acc=0.3455 | Val MacroF1=0.1284 | Val CCC=0.0000
Epoch 05/50 | Train Loss=2.356787 | Val Loss=2.343744 | Val Acc=0.3455 | Val MacroF1=0.1284 | Val CCC=0.0000
Epoch 06/50 | Train Loss=2.526985 | Val Loss=2.315916 | Val Acc=0.3455 | Val MacroF1=0.1284 | Val CCC=0.0000
Epoch 07/50 | Train Loss=2.354275 | Val Loss=2.408296 | Val Acc=0.2545 | Val MacroF1=0.1761 | Val CCC=0.0018
Epoch 08/50 | Train Loss=2.364517 | Val Loss=2.321778 | Val Acc=0.4545 | Val MacroF1=0.2344 | Val CCC=0.0472
Epoch 09/50 | Train Loss=2.321125 | Val Loss=2.333372 | Val Acc=0.3455 | Val MacroF1=0.1284 | Val CCC=0.0000
Epoch 10/50 | Train Loss=2.306435 | Val Loss=2.334825 | Val Acc=0.3455 | Val MacroF1=0.1284 | Val CCC=0.0000
Epoch 11/50 | Train Loss=2.302911 | Val Loss=2.305021 | Val Acc=0.3455 | Val MacroF1=0.1284 | Val CCC=0.0000
Epoch 12/50 | Train Loss=2.247566 | Val Loss=2.314523 | Val Acc=0.2727 | Val MacroF1=0.1392 | Val CCC=0.0991
Epoch 13/50 | Train Loss=2.248841 | Val Loss=2.385015 | Val Acc=0.4000 | Val MacroF1=0.2418 | Val CCC=0.1449
Epoch 14/50 | Train Loss=2.275808 | Val Loss=2.348859 | Val Acc=0.3455 | Val MacroF1=0.1284 | Val CCC=0.0000
Epoch 15/50 | Train Loss=2.237624 | Val Loss=2.365804 | Val Acc=0.4000 | Val MacroF1=0.2410 | Val CCC=0.1668
Epoch 16/50 | Train Loss=2.285179 | Val Loss=2.336970 | Val Acc=0.3455 | Val MacroF1=0.1284 | Val CCC=0.0000
Epoch 17/50 | Train Loss=2.224688 | Val Loss=2.332616 | Val Acc=0.3091 | Val MacroF1=0.1545 | Val CCC=0.1515
Epoch 18/50 | Train Loss=2.248068 | Val Loss=2.361682 | Val Acc=0.3818 | Val MacroF1=0.2236 | Val CCC=0.1612
Epoch 19/50 | Train Loss=2.242510 | Val Loss=2.348626 | Val Acc=0.3455 | Val MacroF1=0.1284 | Val CCC=0.0000
Epoch 20/50 | Train Loss=2.224216 | Val Loss=2.353788 | Val Acc=0.4000 | Val MacroF1=0.2228 | Val CCC=0.0646
Epoch 21/50 | Train Loss=2.229330 | Val Loss=2.349492 | Val Acc=0.2545 | Val MacroF1=0.1329 | Val CCC=0.0506
Epoch 22/50 | Train Loss=2.227933 | Val Loss=2.352460 | Val Acc=0.2909 | Val MacroF1=0.1159 | Val CCC=-0.0399
Epoch 23/50 | Train Loss=2.203350 | Val Loss=2.349526 | Val Acc=0.3455 | Val MacroF1=0.1284 | Val CCC=0.0000
Epoch 24/50 | Train Loss=2.203476 | Val Loss=2.365154 | Val Acc=0.4727 | Val MacroF1=0.2424 | Val CCC=0.0690
Epoch 25/50 | Train Loss=2.277390 | Val Loss=2.358138 | Val Acc=0.3455 | Val MacroF1=0.1284 | Val CCC=0.0000
Epoch 26/50 | Train Loss=2.247622 | Val Loss=2.423349 | Val Acc=0.2545 | Val MacroF1=0.1471 | Val CCC=0.0629
Epoch 27/50 | Train Loss=2.269435 | Val Loss=2.369237 | Val Acc=0.3455 | Val MacroF1=0.1284 | Val CCC=0.0000
Epoch 28/50 | Train Loss=2.236537 | Val Loss=2.369863 | Val Acc=0.2545 | Val MacroF1=0.1329 | Val CCC=0.0506
Epoch 29/50 | Train Loss=2.222997 | Val Loss=2.367766 | Val Acc=0.2545 | Val MacroF1=0.1340 | Val CCC=0.0404
Epoch 30/50 | Train Loss=2.238750 | Val Loss=2.360006 | Val Acc=0.2545 | Val MacroF1=0.1329 | Val CCC=0.0506
Epoch 31/50 | Train Loss=2.216643 | Val Loss=2.418624 | Val Acc=0.2727 | Val MacroF1=0.1392 | Val CCC=0.0991
Epoch 32/50 | Train Loss=2.248639 | Val Loss=2.361163 | Val Acc=0.3455 | Val MacroF1=0.1284 | Val CCC=0.0000
Epoch 33/50 | Train Loss=2.228251 | Val Loss=2.374701 | Val Acc=0.4000 | Val MacroF1=0.2410 | Val CCC=0.1668
Epoch 34/50 | Train Loss=2.288050 | Val Loss=2.363398 | Val Acc=0.2545 | Val MacroF1=0.1329 | Val CCC=0.0506
Epoch 35/50 | Train Loss=2.250556 | Val Loss=2.378297 | Val Acc=0.4364 | Val MacroF1=0.2453 | Val CCC=0.1434
Epoch 36/50 | Train Loss=2.249595 | Val Loss=2.352961 | Val Acc=0.3091 | Val MacroF1=0.1545 | Val CCC=0.1515
Epoch 37/50 | Train Loss=2.214204 | Val Loss=2.362697 | Val Acc=0.2545 | Val MacroF1=0.1316 | Val CCC=0.1026
Epoch 38/50 | Train Loss=2.221101 | Val Loss=2.344221 | Val Acc=0.2727 | Val MacroF1=0.1389 | Val CCC=0.1273
Epoch 39/50 | Train Loss=2.222919 | Val Loss=2.359465 | Val Acc=0.2727 | Val MacroF1=0.1392 | Val CCC=0.0991
Epoch 40/50 | Train Loss=2.203867 | Val Loss=2.372478 | Val Acc=0.2727 | Val MacroF1=0.1392 | Val CCC=0.0991
Epoch 41/50 | Train Loss=2.205386 | Val Loss=2.392123 | Val Acc=0.2727 | Val MacroF1=0.1392 | Val CCC=0.0991
Epoch 42/50 | Train Loss=2.190823 | Val Loss=2.398351 | Val Acc=0.3818 | Val MacroF1=0.2509 | Val CCC=0.1155
Epoch 43/50 | Train Loss=2.260478 | Val Loss=2.378295 | Val Acc=0.3273 | Val MacroF1=0.1697 | Val CCC=0.0594
Epoch 44/50 | Train Loss=2.258366 | Val Loss=2.362896 | Val Acc=0.4364 | Val MacroF1=0.2805 | Val CCC=0.1439
Epoch 45/50 | Train Loss=2.232684 | Val Loss=2.399712 | Val Acc=0.2545 | Val MacroF1=0.1329 | Val CCC=0.0506
Epoch 46/50 | Train Loss=2.211291 | Val Loss=2.382853 | Val Acc=0.2909 | Val MacroF1=0.1470 | Val CCC=-0.0186
Epoch 47/50 | Train Loss=2.220485 | Val Loss=2.369573 | Val Acc=0.2727 | Val MacroF1=0.1392 | Val CCC=0.0991
Epoch 48/50 | Train Loss=2.212319 | Val Loss=2.436254 | Val Acc=0.3636 | Val MacroF1=0.2186 | Val CCC=0.0880
Epoch 49/50 | Train Loss=2.214094 | Val Loss=2.400920 | Val Acc=0.2727 | Val MacroF1=0.1392 | Val CCC=0.0991
Epoch 50/50 | Train Loss=2.202863 | Val Loss=2.387815 | Val Acc=0.2727 | Val MacroF1=0.1392 | Val CCC=0.0991
======================================================================
Q2 Seed=42训练结束
最佳验证Loss：2.305021，Epoch 11
最佳验证CCC：0.166761，Epoch 15
总耗时：18.38秒
Best Loss：/workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_42/question_2/best_loss.pt
Best CCC：/workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_42/question_2/best_ccc.pt
Last：/workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_42/question_2/last.pt
======================================================================
Q3 Seed=42尚未完成，开始正式训练
======================================================================
开始正式训练：Q3 PHQ_8Sleep，Seed=42
======================================================================
Epoch 01/50 | Train Loss=2.717201 | Val Loss=2.544262 | Val Acc=0.1818 | Val MacroF1=0.1144 | Val CCC=0.0034
Epoch 02/50 | Train Loss=2.675346 | Val Loss=2.508324 | Val Acc=0.3091 | Val MacroF1=0.1181 | Val CCC=0.0000
Epoch 03/50 | Train Loss=2.678237 | Val Loss=2.547855 | Val Acc=0.3091 | Val MacroF1=0.1181 | Val CCC=0.0000
Epoch 04/50 | Train Loss=2.679638 | Val Loss=2.548266 | Val Acc=0.1455 | Val MacroF1=0.0635 | Val CCC=0.0000
Epoch 05/50 | Train Loss=2.636058 | Val Loss=2.497745 | Val Acc=0.3091 | Val MacroF1=0.1181 | Val CCC=0.0000
Epoch 06/50 | Train Loss=2.636537 | Val Loss=2.659120 | Val Acc=0.3273 | Val MacroF1=0.1691 | Val CCC=0.0662
Epoch 07/50 | Train Loss=2.636570 | Val Loss=2.729428 | Val Acc=0.1455 | Val MacroF1=0.0635 | Val CCC=0.0000
Epoch 08/50 | Train Loss=2.663766 | Val Loss=2.876330 | Val Acc=0.3091 | Val MacroF1=0.1269 | Val CCC=0.0481
Epoch 09/50 | Train Loss=2.923831 | Val Loss=2.527945 | Val Acc=0.3636 | Val MacroF1=0.2396 | Val CCC=0.1315
Epoch 10/50 | Train Loss=2.541174 | Val Loss=2.618916 | Val Acc=0.1273 | Val MacroF1=0.0565 | Val CCC=-0.0173
Epoch 11/50 | Train Loss=2.560790 | Val Loss=2.577598 | Val Acc=0.3273 | Val MacroF1=0.1939 | Val CCC=0.0923
Epoch 12/50 | Train Loss=2.532362 | Val Loss=2.621486 | Val Acc=0.2727 | Val MacroF1=0.1784 | Val CCC=0.1177
Epoch 13/50 | Train Loss=2.591914 | Val Loss=2.559207 | Val Acc=0.3091 | Val MacroF1=0.1717 | Val CCC=0.0879
Epoch 14/50 | Train Loss=2.558948 | Val Loss=2.463115 | Val Acc=0.3273 | Val MacroF1=0.1641 | Val CCC=0.0781
Epoch 15/50 | Train Loss=2.512734 | Val Loss=2.552140 | Val Acc=0.3091 | Val MacroF1=0.1645 | Val CCC=0.0839
Epoch 16/50 | Train Loss=2.509747 | Val Loss=2.495058 | Val Acc=0.3091 | Val MacroF1=0.1751 | Val CCC=0.0647
Epoch 17/50 | Train Loss=2.478224 | Val Loss=2.564896 | Val Acc=0.3091 | Val MacroF1=0.1960 | Val CCC=-0.0081
Epoch 18/50 | Train Loss=2.505308 | Val Loss=2.484818 | Val Acc=0.3273 | Val MacroF1=0.1834 | Val CCC=0.0665
Epoch 19/50 | Train Loss=2.476013 | Val Loss=2.471032 | Val Acc=0.3273 | Val MacroF1=0.1834 | Val CCC=0.0665
Epoch 20/50 | Train Loss=2.476181 | Val Loss=2.507825 | Val Acc=0.3455 | Val MacroF1=0.2075 | Val CCC=0.0928
Epoch 21/50 | Train Loss=2.467743 | Val Loss=2.492077 | Val Acc=0.3091 | Val MacroF1=0.1751 | Val CCC=0.0647
Epoch 22/50 | Train Loss=2.489806 | Val Loss=2.477314 | Val Acc=0.3273 | Val MacroF1=0.1834 | Val CCC=0.0665
Epoch 23/50 | Train Loss=2.479679 | Val Loss=2.480928 | Val Acc=0.3273 | Val MacroF1=0.1833 | Val CCC=0.0428
Epoch 24/50 | Train Loss=2.501942 | Val Loss=2.532841 | Val Acc=0.3273 | Val MacroF1=0.1834 | Val CCC=0.0665
Epoch 25/50 | Train Loss=2.491272 | Val Loss=2.512866 | Val Acc=0.3091 | Val MacroF1=0.1751 | Val CCC=0.0647
Epoch 26/50 | Train Loss=2.496769 | Val Loss=2.493946 | Val Acc=0.3273 | Val MacroF1=0.1834 | Val CCC=0.0665
Epoch 27/50 | Train Loss=2.514486 | Val Loss=2.541191 | Val Acc=0.3273 | Val MacroF1=0.1833 | Val CCC=0.0428
Epoch 28/50 | Train Loss=2.489855 | Val Loss=2.520854 | Val Acc=0.3273 | Val MacroF1=0.1834 | Val CCC=0.0665
Epoch 29/50 | Train Loss=2.479676 | Val Loss=2.501055 | Val Acc=0.3273 | Val MacroF1=0.1834 | Val CCC=0.0665
Epoch 30/50 | Train Loss=2.467539 | Val Loss=2.485733 | Val Acc=0.3273 | Val MacroF1=0.1833 | Val CCC=0.0428
Epoch 31/50 | Train Loss=2.472588 | Val Loss=2.514693 | Val Acc=0.3273 | Val MacroF1=0.1834 | Val CCC=0.0665
Epoch 32/50 | Train Loss=2.474127 | Val Loss=2.512538 | Val Acc=0.3273 | Val MacroF1=0.1834 | Val CCC=0.0665
Epoch 33/50 | Train Loss=2.463558 | Val Loss=2.512748 | Val Acc=0.3091 | Val MacroF1=0.1751 | Val CCC=0.0647
Epoch 34/50 | Train Loss=2.450861 | Val Loss=2.528319 | Val Acc=0.3273 | Val MacroF1=0.1834 | Val CCC=0.0665
Epoch 35/50 | Train Loss=2.452952 | Val Loss=2.522525 | Val Acc=0.3455 | Val MacroF1=0.2379 | Val CCC=0.0846
Epoch 36/50 | Train Loss=2.471796 | Val Loss=2.496362 | Val Acc=0.3273 | Val MacroF1=0.1834 | Val CCC=0.0665
Epoch 37/50 | Train Loss=2.474604 | Val Loss=2.535295 | Val Acc=0.3273 | Val MacroF1=0.1834 | Val CCC=0.0665
Epoch 38/50 | Train Loss=2.459784 | Val Loss=2.510514 | Val Acc=0.3091 | Val MacroF1=0.1751 | Val CCC=0.0647
Epoch 39/50 | Train Loss=2.444037 | Val Loss=2.520402 | Val Acc=0.3273 | Val MacroF1=0.1834 | Val CCC=0.0665
Epoch 40/50 | Train Loss=2.452879 | Val Loss=2.494685 | Val Acc=0.3273 | Val MacroF1=0.1834 | Val CCC=0.0665
Epoch 41/50 | Train Loss=2.435784 | Val Loss=2.485303 | Val Acc=0.3273 | Val MacroF1=0.1834 | Val CCC=0.0665
Epoch 42/50 | Train Loss=2.438016 | Val Loss=2.511609 | Val Acc=0.3273 | Val MacroF1=0.1834 | Val CCC=0.0665
Epoch 43/50 | Train Loss=2.465671 | Val Loss=2.501232 | Val Acc=0.3273 | Val MacroF1=0.1834 | Val CCC=0.0665
Epoch 44/50 | Train Loss=2.462272 | Val Loss=2.547145 | Val Acc=0.2909 | Val MacroF1=0.1883 | Val CCC=-0.0071
Epoch 45/50 | Train Loss=2.455009 | Val Loss=2.490506 | Val Acc=0.3273 | Val MacroF1=0.1834 | Val CCC=0.0665
Epoch 46/50 | Train Loss=2.454612 | Val Loss=2.514162 | Val Acc=0.2909 | Val MacroF1=0.1681 | Val CCC=0.0851
Epoch 47/50 | Train Loss=2.436710 | Val Loss=2.511939 | Val Acc=0.3273 | Val MacroF1=0.1834 | Val CCC=0.0665
Epoch 48/50 | Train Loss=2.509818 | Val Loss=2.506697 | Val Acc=0.3091 | Val MacroF1=0.1751 | Val CCC=0.0647
Epoch 49/50 | Train Loss=2.450781 | Val Loss=2.529689 | Val Acc=0.3273 | Val MacroF1=0.1833 | Val CCC=0.0428
Epoch 50/50 | Train Loss=2.439508 | Val Loss=2.508790 | Val Acc=0.3273 | Val MacroF1=0.1834 | Val CCC=0.0665
======================================================================
Q3 Seed=42训练结束
最佳验证Loss：2.463115，Epoch 14
最佳验证CCC：0.131503，Epoch 9
总耗时：18.09秒
Best Loss：/workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_42/question_3/best_loss.pt
Best CCC：/workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_42/question_3/best_ccc.pt
Last：/workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_42/question_3/last.pt
======================================================================
Q4 Seed=42尚未完成，开始正式训练
======================================================================
开始正式训练：Q4 PHQ_8Tired，Seed=42
======================================================================
Epoch 01/50 | Train Loss=2.613529 | Val Loss=2.451019 | Val Acc=0.4182 | Val MacroF1=0.1474 | Val CCC=0.0000
Epoch 02/50 | Train Loss=2.533165 | Val Loss=2.480027 | Val Acc=0.4182 | Val MacroF1=0.1474 | Val CCC=0.0000
Epoch 03/50 | Train Loss=2.505540 | Val Loss=2.453637 | Val Acc=0.4182 | Val MacroF1=0.1474 | Val CCC=0.0000
Epoch 04/50 | Train Loss=2.494493 | Val Loss=2.451260 | Val Acc=0.4182 | Val MacroF1=0.1474 | Val CCC=0.0000
Epoch 05/50 | Train Loss=2.496620 | Val Loss=2.433294 | Val Acc=0.4182 | Val MacroF1=0.1474 | Val CCC=0.0000
Epoch 06/50 | Train Loss=2.431817 | Val Loss=2.373447 | Val Acc=0.3636 | Val MacroF1=0.2002 | Val CCC=0.1444
Epoch 07/50 | Train Loss=2.478423 | Val Loss=2.362300 | Val Acc=0.3636 | Val MacroF1=0.1860 | Val CCC=0.1626
Epoch 08/50 | Train Loss=2.466631 | Val Loss=2.376680 | Val Acc=0.3636 | Val MacroF1=0.1860 | Val CCC=0.1626
Epoch 09/50 | Train Loss=2.421812 | Val Loss=2.359317 | Val Acc=0.3818 | Val MacroF1=0.1945 | Val CCC=0.1690
Epoch 10/50 | Train Loss=2.432544 | Val Loss=2.473994 | Val Acc=0.2909 | Val MacroF1=0.1720 | Val CCC=0.0788
Epoch 11/50 | Train Loss=2.425832 | Val Loss=2.407686 | Val Acc=0.3455 | Val MacroF1=0.2353 | Val CCC=0.1893
Epoch 12/50 | Train Loss=2.418206 | Val Loss=2.368695 | Val Acc=0.4000 | Val MacroF1=0.2210 | Val CCC=0.1961
Epoch 13/50 | Train Loss=2.352744 | Val Loss=2.367002 | Val Acc=0.3636 | Val MacroF1=0.1893 | Val CCC=0.1697
Epoch 14/50 | Train Loss=2.349471 | Val Loss=2.375288 | Val Acc=0.3818 | Val MacroF1=0.1945 | Val CCC=0.1690
Epoch 15/50 | Train Loss=2.369159 | Val Loss=2.375950 | Val Acc=0.3455 | Val MacroF1=0.1945 | Val CCC=0.1456
Epoch 16/50 | Train Loss=2.366876 | Val Loss=2.387327 | Val Acc=0.3636 | Val MacroF1=0.2002 | Val CCC=0.1444
Epoch 17/50 | Train Loss=2.355448 | Val Loss=2.412238 | Val Acc=0.4000 | Val MacroF1=0.2210 | Val CCC=0.1961
Epoch 18/50 | Train Loss=2.396636 | Val Loss=2.429762 | Val Acc=0.3636 | Val MacroF1=0.2002 | Val CCC=0.1444
Epoch 19/50 | Train Loss=2.405699 | Val Loss=2.408074 | Val Acc=0.3818 | Val MacroF1=0.2113 | Val CCC=0.1895
Epoch 20/50 | Train Loss=2.330199 | Val Loss=2.409362 | Val Acc=0.3636 | Val MacroF1=0.2002 | Val CCC=0.1444
Epoch 21/50 | Train Loss=2.390649 | Val Loss=2.376084 | Val Acc=0.3636 | Val MacroF1=0.2002 | Val CCC=0.1444
Epoch 22/50 | Train Loss=2.334570 | Val Loss=2.404314 | Val Acc=0.4182 | Val MacroF1=0.2346 | Val CCC=0.1412
Epoch 23/50 | Train Loss=2.392974 | Val Loss=2.420830 | Val Acc=0.3091 | Val MacroF1=0.2107 | Val CCC=0.1867
Epoch 24/50 | Train Loss=2.427570 | Val Loss=2.391541 | Val Acc=0.4182 | Val MacroF1=0.2125 | Val CCC=0.1822
Epoch 25/50 | Train Loss=2.382189 | Val Loss=2.378965 | Val Acc=0.3818 | Val MacroF1=0.1945 | Val CCC=0.1690
Epoch 26/50 | Train Loss=2.410806 | Val Loss=2.379756 | Val Acc=0.4182 | Val MacroF1=0.2125 | Val CCC=0.1822
Epoch 27/50 | Train Loss=2.400989 | Val Loss=2.381876 | Val Acc=0.3818 | Val MacroF1=0.1945 | Val CCC=0.1690
Epoch 28/50 | Train Loss=2.422034 | Val Loss=2.348140 | Val Acc=0.4182 | Val MacroF1=0.2125 | Val CCC=0.1822
Epoch 29/50 | Train Loss=2.380831 | Val Loss=2.362224 | Val Acc=0.3636 | Val MacroF1=0.2002 | Val CCC=0.1444
Epoch 30/50 | Train Loss=2.366856 | Val Loss=2.465087 | Val Acc=0.2182 | Val MacroF1=0.1606 | Val CCC=0.2166
Epoch 31/50 | Train Loss=2.510174 | Val Loss=2.490532 | Val Acc=0.4182 | Val MacroF1=0.1474 | Val CCC=0.0000
Epoch 32/50 | Train Loss=2.427788 | Val Loss=2.385267 | Val Acc=0.3636 | Val MacroF1=0.2019 | Val CCC=0.1830
Epoch 33/50 | Train Loss=2.368149 | Val Loss=2.478004 | Val Acc=0.3636 | Val MacroF1=0.2631 | Val CCC=0.1508
Epoch 34/50 | Train Loss=2.427831 | Val Loss=2.423396 | Val Acc=0.3273 | Val MacroF1=0.1815 | Val CCC=0.1899
Epoch 35/50 | Train Loss=2.381085 | Val Loss=2.400548 | Val Acc=0.4182 | Val MacroF1=0.2125 | Val CCC=0.1822
Epoch 36/50 | Train Loss=2.353275 | Val Loss=2.367786 | Val Acc=0.3636 | Val MacroF1=0.2120 | Val CCC=0.2029
Epoch 37/50 | Train Loss=2.362913 | Val Loss=2.379655 | Val Acc=0.3636 | Val MacroF1=0.2019 | Val CCC=0.1830
Epoch 38/50 | Train Loss=2.325790 | Val Loss=2.385061 | Val Acc=0.3455 | Val MacroF1=0.1945 | Val CCC=0.1456
Epoch 39/50 | Train Loss=2.330556 | Val Loss=2.468563 | Val Acc=0.4000 | Val MacroF1=0.2889 | Val CCC=0.2409
Epoch 40/50 | Train Loss=2.413298 | Val Loss=2.464616 | Val Acc=0.3636 | Val MacroF1=0.2019 | Val CCC=0.1830
Epoch 41/50 | Train Loss=2.393253 | Val Loss=2.404242 | Val Acc=0.3091 | Val MacroF1=0.2434 | Val CCC=0.1890
Epoch 42/50 | Train Loss=2.349864 | Val Loss=2.397692 | Val Acc=0.3636 | Val MacroF1=0.1893 | Val CCC=0.1514
Epoch 43/50 | Train Loss=2.423140 | Val Loss=2.417702 | Val Acc=0.2909 | Val MacroF1=0.2081 | Val CCC=0.1543
Epoch 44/50 | Train Loss=2.389446 | Val Loss=2.403590 | Val Acc=0.3636 | Val MacroF1=0.2002 | Val CCC=0.1444
Epoch 45/50 | Train Loss=2.409507 | Val Loss=2.362059 | Val Acc=0.3636 | Val MacroF1=0.2019 | Val CCC=0.1830
Epoch 46/50 | Train Loss=2.411892 | Val Loss=2.368401 | Val Acc=0.3636 | Val MacroF1=0.2019 | Val CCC=0.1830
Epoch 47/50 | Train Loss=2.369413 | Val Loss=2.393728 | Val Acc=0.3636 | Val MacroF1=0.2002 | Val CCC=0.1444
Epoch 48/50 | Train Loss=2.344258 | Val Loss=2.382978 | Val Acc=0.3636 | Val MacroF1=0.2002 | Val CCC=0.1444
Epoch 49/50 | Train Loss=2.350869 | Val Loss=2.405361 | Val Acc=0.3818 | Val MacroF1=0.2113 | Val CCC=0.1895
Epoch 50/50 | Train Loss=2.326466 | Val Loss=2.401965 | Val Acc=0.3636 | Val MacroF1=0.2019 | Val CCC=0.1830
======================================================================
Q4 Seed=42训练结束
最佳验证Loss：2.348140，Epoch 28
最佳验证CCC：0.240907，Epoch 39
总耗时：18.07秒
Best Loss：/workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_42/question_4/best_loss.pt
Best CCC：/workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_42/question_4/best_ccc.pt
Last：/workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_42/question_4/last.pt
======================================================================
Q5 Seed=42尚未完成，开始正式训练
======================================================================
开始正式训练：Q5 PHQ_8Appetite，Seed=42
======================================================================
Epoch 01/50 | Train Loss=2.741245 | Val Loss=2.284424 | Val Acc=0.4000 | Val MacroF1=0.1429 | Val CCC=0.0000
Epoch 02/50 | Train Loss=2.617136 | Val Loss=2.256204 | Val Acc=0.4000 | Val MacroF1=0.1429 | Val CCC=0.0000
Epoch 03/50 | Train Loss=2.558080 | Val Loss=2.318887 | Val Acc=0.3455 | Val MacroF1=0.1787 | Val CCC=0.0430
Epoch 04/50 | Train Loss=2.558536 | Val Loss=2.244904 | Val Acc=0.4000 | Val MacroF1=0.1429 | Val CCC=0.0000
Epoch 05/50 | Train Loss=2.555210 | Val Loss=2.361438 | Val Acc=0.1818 | Val MacroF1=0.0781 | Val CCC=0.0196
Epoch 06/50 | Train Loss=2.592413 | Val Loss=2.246895 | Val Acc=0.4000 | Val MacroF1=0.1429 | Val CCC=0.0000
Epoch 07/50 | Train Loss=2.583462 | Val Loss=2.355712 | Val Acc=0.3091 | Val MacroF1=0.2154 | Val CCC=0.0154
Epoch 08/50 | Train Loss=2.545389 | Val Loss=2.282839 | Val Acc=0.3091 | Val MacroF1=0.1741 | Val CCC=-0.0473
Epoch 09/50 | Train Loss=2.525796 | Val Loss=2.291004 | Val Acc=0.3636 | Val MacroF1=0.1874 | Val CCC=0.0432
Epoch 10/50 | Train Loss=2.616798 | Val Loss=2.419538 | Val Acc=0.3636 | Val MacroF1=0.1874 | Val CCC=0.0432

,Question_Number,Question,Seed,Best_Loss,Best_Loss_Epoch,Best_CCC,Best_CCC_Epoch,Loaded_From_Disk,Elapsed_Seconds
0,1,PHQ_8NoInterest,42,2.548061,10,0.151781,14,True,18.595483
1,2,PHQ_8Depressed,42,2.305021,11,0.166761,15,False,18.382560
2,3,PHQ_8Sleep,42,2.463115,14,0.131503,9,False,18.087579
3,4,PHQ_8Tired,42,2.348140,28,0.240907,39,False,18.072135
4,5,PHQ_8Appetite,42,2.206802,32,0.114119,18,False,17.958508
5,6,PHQ_8Failure,42,2.249691,45,0.238375,19,False,18.162375
6,7,PHQ_8Concentrating,42,2.265645,3,0.136929,39,False,17.664063
7,8,PHQ_8Moving,42,1.781414,12,0.126379,44,False,17.733304

In [114]:
print("结果数量：", len(audio_seed42_results))
print("汇总行数：", len(audio_seed42_summary_df))
print("Best Loss文件全部存在：", all(result["best_loss_path"].exists() for result in audio_seed42_results))
print("Best CCC文件全部存在：", all(result["best_ccc_path"].exists() for result in audio_seed42_results))
print("Last文件全部存在：", all(result["last_path"].exists() for result in audio_seed42_results))

结果数量： 8
汇总行数： 8
Best Loss文件全部存在： True
Best CCC文件全部存在： True
Last文件全部存在： True

In [115]:
class CachedAudioTestDataset(Dataset):
    def __init__(self, metadata_df):
        super().__init__()
        self.metadata_df = metadata_df.reset_index(drop=True).copy()
        self.participant_ids = self.metadata_df["Participant_ID"].astype(int).tolist()
        self.total_scores = torch.tensor(self.metadata_df["PHQ_Score"].to_numpy(), dtype=torch.long)
        audio_feature_list = []
        padding_mask_list = []
        real_turn_count_list = []
        cache_hit_count = 0

        for participant_id in self.participant_ids:
            audio_features, padding_mask, real_turn_count, cache_hit = get_participant_audio_features(participant_id)
            audio_feature_list.append(audio_features)
            padding_mask_list.append(padding_mask)
            real_turn_count_list.append(real_turn_count)

            if cache_hit:
                cache_hit_count += 1

        self.audio_features = torch.stack(audio_feature_list, dim=0)
        self.padding_masks = torch.stack(padding_mask_list, dim=0)
        self.real_turn_counts = torch.tensor(real_turn_count_list, dtype=torch.long)
        self.cache_hit_count = cache_hit_count
        self.cache_miss_count = len(self.participant_ids) - cache_hit_count

        if self.audio_features.shape != (len(self.participant_ids), MAX_TURNS, AUDIO_FEATURE_DIM):
            raise RuntimeError(f"测试集语音特征形状错误：{self.audio_features.shape}")

        if self.padding_masks.shape != (len(self.participant_ids), MAX_TURNS):
            raise RuntimeError(f"测试集Mask形状错误：{self.padding_masks.shape}")

        if self.total_scores.shape != (len(self.participant_ids),):
            raise RuntimeError(f"测试集总分形状错误：{self.total_scores.shape}")

        if not torch.isfinite(self.audio_features).all():
            raise RuntimeError("测试集语音特征包含NaN或Inf")

    def __len__(self):
        return len(self.participant_ids)

    def __getitem__(self, index):
        audio_features = self.audio_features[index]
        padding_mask = self.padding_masks[index]
        total_score = self.total_scores[index]
        participant_id = self.participant_ids[index]
        return audio_features, padding_mask, total_score, participant_id

In [116]:
test_audio_dataset = CachedAudioTestDataset(test_metadata_df)
test_audio_loader = DataLoader(test_audio_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=0, drop_last=False)

test_batch_audio, test_batch_masks, test_batch_scores, test_batch_participant_ids = next(iter(test_audio_loader))

print("测试样本数：", len(test_audio_dataset))
print("测试批次数：", len(test_audio_loader))
print("测试语音特征：", test_audio_dataset.audio_features.shape)
print("测试Mask：", test_audio_dataset.padding_masks.shape)
print("测试总分：", test_audio_dataset.total_scores.shape)
print("第一批语音特征：", test_batch_audio.shape)
print("第一批Mask：", test_batch_masks.shape)
print("第一批总分：", test_batch_scores.shape)
print("第一批参与者编号：", test_batch_participant_ids)
print("缓存命中数量：", test_audio_dataset.cache_hit_count)
print("缓存未命中数量：", test_audio_dataset.cache_miss_count)

测试样本数： 56
测试批次数： 6
测试语音特征： torch.Size([56, 120, 23])
测试Mask： torch.Size([56, 120])
测试总分： torch.Size([56])
第一批语音特征： torch.Size([10, 120, 23])
第一批Mask： torch.Size([10, 120])
第一批总分： torch.Size([10])
第一批参与者编号： tensor([600, 602, 604, 605, 606, 607, 609, 615, 618, 619])
缓存命中数量： 56
缓存未命中数量： 0

In [117]:
def compute_audio_total_score_metrics(predictions, labels):
    predictions = predictions.cpu().float()
    labels = labels.cpu().float()
    ccc = compute_ccc(predictions, labels)
    rmse = torch.sqrt(torch.mean((predictions - labels) ** 2)).item()
    mae = torch.mean(torch.abs(predictions - labels)).item()
    exact_accuracy = torch.mean((predictions == labels).float()).item()
    metrics = {}
    metrics["ccc"] = ccc
    metrics["rmse"] = rmse
    metrics["mae"] = mae
    metrics["exact_accuracy"] = exact_accuracy
    return metrics

In [118]:
def evaluate_audio_seed_on_test(seed, seed_results, test_loader):
    question_count = len(PHQ8_QUESTION_COLUMNS)
    sample_count = len(test_loader.dataset)
    expected_participant_ids = torch.tensor(test_loader.dataset.participant_ids, dtype=torch.long)
    true_total_scores = test_loader.dataset.total_scores.clone()
    question_predictions = torch.empty((sample_count, question_count), dtype=torch.long)
    checkpoint_rows = []

    for question_index in range(question_count):
        question_result = seed_results[question_index]
        checkpoint_path = question_result["best_ccc_path"]
        model, checkpoint = load_audio_question_model(checkpoint_path, expected_question_index=question_index, expected_seed=seed)
        batch_prediction_list = []
        batch_participant_id_list = []
        model.eval()

        with torch.no_grad():
            for batch_audio_features, batch_padding_masks, batch_total_scores, batch_participant_ids in test_loader:
                batch_audio_features = batch_audio_features.to(device)
                batch_padding_masks = batch_padding_masks.to(device)
                logits = model(batch_audio_features, batch_padding_masks)
                batch_predictions = torch.argmax(logits, dim=1)
                batch_prediction_list.append(batch_predictions.cpu())
                batch_participant_id_list.append(batch_participant_ids.cpu())

        question_prediction = torch.cat(batch_prediction_list, dim=0)
        observed_participant_ids = torch.cat(batch_participant_id_list, dim=0)

        if not torch.equal(observed_participant_ids, expected_participant_ids):
            raise RuntimeError("测试参与者顺序不一致")

        if question_prediction.shape != (sample_count,):
            raise RuntimeError(f"Q{question_index + 1}测试预测形状错误：{question_prediction.shape}")

        question_predictions[:, question_index] = question_prediction

        checkpoint_row = {}
        checkpoint_row["Question_Number"] = question_index + 1
        checkpoint_row["Question"] = PHQ8_QUESTION_COLUMNS[question_index]
        checkpoint_row["Seed"] = seed
        checkpoint_row["Selected_Epoch"] = checkpoint["epoch"]
        checkpoint_row["Validation_CCC"] = checkpoint["val_metrics"]["ccc"]
        checkpoint_row["Checkpoint_Path"] = str(checkpoint_path)
        checkpoint_rows.append(checkpoint_row)

        print(f"Seed {seed}，Q{question_index + 1}/8测试完成")

        del model
        del checkpoint
        del logits

        if torch.cuda.is_available():
            torch.cuda.empty_cache()

    predicted_total_scores = question_predictions.sum(dim=1)
    total_metrics = compute_audio_total_score_metrics(predicted_total_scores, true_total_scores)
    prediction_df = pd.DataFrame({"Participant_ID": expected_participant_ids.numpy()})

    for question_index in range(question_count):
        prediction_df[f"Pred_Q{question_index + 1}"] = question_predictions[:, question_index].numpy()

    prediction_df["True_Total"] = true_total_scores.numpy()
    prediction_df["Predicted_Total"] = predicted_total_scores.numpy()
    prediction_df["Total_Error"] = prediction_df["Predicted_Total"] - prediction_df["True_Total"]
    prediction_df["Absolute_Total_Error"] = prediction_df["Total_Error"].abs()

    prediction_path = CHECKPOINT_ROOT / f"seed_{seed}_test_predictions_56.csv"
    checkpoint_summary_path = CHECKPOINT_ROOT / f"seed_{seed}_test_selected_checkpoints.csv"
    prediction_df.to_csv(prediction_path, index=False)
    checkpoint_df = pd.DataFrame(checkpoint_rows)
    checkpoint_df.to_csv(checkpoint_summary_path, index=False)

    result = {}
    result["seed"] = seed
    result["sample_count"] = sample_count
    result["ccc"] = total_metrics["ccc"]
    result["rmse"] = total_metrics["rmse"]
    result["mae"] = total_metrics["mae"]
    result["exact_accuracy"] = total_metrics["exact_accuracy"]
    result["question_predictions"] = question_predictions
    result["predicted_total"] = predicted_total_scores
    result["true_total"] = true_total_scores
    result["participant_ids"] = expected_participant_ids
    result["prediction_df"] = prediction_df
    result["checkpoint_df"] = checkpoint_df
    result["prediction_path"] = prediction_path
    result["checkpoint_summary_path"] = checkpoint_summary_path

    print()
    print("=" * 70)
    print(f"Audio-only Seed {seed}独立测试结果")
    print("=" * 70)
    print(f"测试参与者数量：{sample_count}")
    print(f"CCC：{result['ccc']:.6f}")
    print(f"RMSE：{result['rmse']:.6f}")
    print(f"MAE：{result['mae']:.6f}")
    print(f"完全相等比例：{result['exact_accuracy']:.6f}")
    print(f"预测总分范围：{predicted_total_scores.min().item()}～{predicted_total_scores.max().item()}")
    print(f"真实总分范围：{true_total_scores.min().item()}～{true_total_scores.max().item()}")
    print(f"预测文件：{prediction_path}")

    return result

In [119]:
audio_seed42_test_result = evaluate_audio_seed_on_test(seed=42, seed_results=audio_seed42_results, test_loader=test_audio_loader)

已加载Checkpoint： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_42/question_1/best_ccc.pt
Checkpoint类型： best_ccc
保存Epoch： 14
题目： PHQ_8NoInterest
Seed： 42
缺少参数： []
多余参数： []
Seed 42，Q1/8测试完成
已加载Checkpoint： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_42/question_2/best_ccc.pt
Checkpoint类型： best_ccc
保存Epoch： 15
题目： PHQ_8Depressed
Seed： 42
缺少参数： []
多余参数： []
Seed 42，Q2/8测试完成
已加载Checkpoint： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_42/question_3/best_ccc.pt
Checkpoint类型： best_ccc
保存Epoch： 9
题目： PHQ_8Sleep
Seed： 42
缺少参数： []
多余参数： []
Seed 42，Q3/8测试完成
已加载Checkpoint： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_42/question_4/best_ccc.pt
Checkpoint类型： best_ccc
保存Epoch： 39
题目： PHQ_8Tired
Seed： 42
缺少参数： []
多余参数： []
Seed 42，Q4/8测试完成
已加载Checkpoint： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_42/question_5/best_ccc.pt
Checkpoint类型： best_ccc
保存Epoch： 18
题目： PHQ_8Appetite
Seed： 42
缺少参数： []
多余参数： []
Seed 42，Q5/8测试完成
已加载Checkpoint： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_42/question_6/best_ccc.pt
Checkpoint类型： best_ccc
保存Epoch： 19
题目： PHQ_8Failure
Seed： 42
缺少参数： []
多余参数： []
Seed 42，Q6/8测试完成
已加载Checkpoint： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_42/question_7/best_ccc.pt
Checkpoint类型： best_ccc
保存Epoch： 39
题目： PHQ_8Concentrating
Seed： 42
缺少参数： []
多余参数： []
Seed 42，Q7/8测试完成
已加载Checkpoint： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_42/question_8/best_ccc.pt
Checkpoint类型： best_ccc
保存Epoch： 44
题目： PHQ_8Moving
Seed： 42
缺少参数： []
多余参数： []
Seed 42，Q8/8测试完成

======================================================================
Audio-only Seed 42独立测试结果
======================================================================
测试参与者数量：56
CCC：0.275914
RMSE：7.463004
MAE：5.839286
完全相等比例：0.053571
预测总分范围：2～18
真实总分范围：0～22
预测文件：/workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_42_test_predictions_56.csv

In [120]:
audio_seed100_results, audio_seed100_summary_df = train_all_audio_questions_for_seed(seed=100)
display(audio_seed100_summary_df)

audio_seed1234_results, audio_seed1234_summary_df = train_all_audio_questions_for_seed(seed=1234)
display(audio_seed1234_summary_df)

################################################################################
开始处理Audio-only全部8道题，Seed=100
################################################################################
Q1 Seed=100尚未完成，开始正式训练
======================================================================
开始正式训练：Q1 PHQ_8NoInterest，Seed=100
======================================================================
Epoch 01/50 | Train Loss=2.263386 | Val Loss=2.610214 | Val Acc=0.3273 | Val MacroF1=0.1714 | Val CCC=-0.1982
Epoch 02/50 | Train Loss=2.135978 | Val Loss=2.688951 | Val Acc=0.3818 | Val MacroF1=0.1530 | Val CCC=-0.1017
Epoch 03/50 | Train Loss=2.174554 | Val Loss=2.640226 | Val Acc=0.3636 | Val MacroF1=0.1956 | Val CCC=-0.0542
Epoch 04/50 | Train Loss=2.095424 | Val Loss=2.614568 | Val Acc=0.4000 | Val MacroF1=0.1429 | Val CCC=0.0000
Epoch 05/50 | Train Loss=2.178258 | Val Loss=2.655431 | Val Acc=0.3636 | Val MacroF1=0.1408 | Val CCC=-0.0961
Epoch 06/50 | Train Loss=2.195545 | Val Loss=2.561233 | Val Acc=0.4000 | Val MacroF1=0.1429 | Val CCC=0.0000
Epoch 07/50 | Train Loss=2.101133 | Val Loss=2.582253 | Val Acc=0.4000 | Val MacroF1=0.1429 | Val CCC=0.0000
Epoch 08/50 | Train Loss=2.163165 | Val Loss=2.529667 | Val Acc=0.3636 | Val MacroF1=0.1838 | Val CCC=0.1273
Epoch 09/50 | Train Loss=2.209269 | Val Loss=2.593212 | Val Acc=0.4000 | Val MacroF1=0.1429 | Val CCC=0.0000
Epoch 10/50 | Train Loss=2.089987 | Val Loss=2.658060 | Val Acc=0.5091 | Val MacroF1=0.2567 | Val CCC=0.0620
Epoch 11/50 | Train Loss=2.172783 | Val Loss=2.653188 | Val Acc=0.2545 | Val MacroF1=0.1361 | Val CCC=0.0255
Epoch 12/50 | Train Loss=2.101808 | Val Loss=2.619052 | Val Acc=0.5273 | Val MacroF1=0.2647 | Val CCC=0.0842
Epoch 13/50 | Train Loss=2.025270 | Val Loss=2.592323 | Val Acc=0.3636 | Val MacroF1=0.1875 | Val CCC=0.0452
Epoch 14/50 | Train Loss=2.068577 | Val Loss=2.635477 | Val Acc=0.3636 | Val MacroF1=0.2091 | Val CCC=0.1456
Epoch 15/50 | Train Loss=2.045023 | Val Loss=2.637436 | Val Acc=0.3636 | Val MacroF1=0.2016 | Val CCC=-0.0283
Epoch 16/50 | Train Loss=2.061650 | Val Loss=2.656399 | Val Acc=0.2909 | Val MacroF1=0.1470 | Val CCC=0.1180
Epoch 17/50 | Train Loss=2.034794 | Val Loss=2.573674 | Val Acc=0.3636 | Val MacroF1=0.1838 | Val CCC=0.1273
Epoch 18/50 | Train Loss=2.091373 | Val Loss=2.610604 | Val Acc=0.2909 | Val MacroF1=0.1466 | Val CCC=0.0908
Epoch 19/50 | Train Loss=2.096212 | Val Loss=2.910492 | Val Acc=0.4545 | Val MacroF1=0.2419 | Val CCC=0.1697
Epoch 20/50 | Train Loss=1.975811 | Val Loss=2.592039 | Val Acc=0.2909 | Val MacroF1=0.1468 | Val CCC=0.0400
Epoch 21/50 | Train Loss=2.003903 | Val Loss=2.649179 | Val Acc=0.4364 | Val MacroF1=0.2346 | Val CCC=0.1614
Epoch 22/50 | Train Loss=1.993702 | Val Loss=2.716636 | Val Acc=0.3636 | Val MacroF1=0.2390 | Val CCC=0.0948
Epoch 23/50 | Train Loss=2.075416 | Val Loss=2.816305 | Val Acc=0.2545 | Val MacroF1=0.1702 | Val CCC=-0.0000
Epoch 24/50 | Train Loss=2.024790 | Val Loss=2.642648 | Val Acc=0.4000 | Val MacroF1=0.1429 | Val CCC=0.0000
Epoch 25/50 | Train Loss=2.051314 | Val Loss=2.760666 | Val Acc=0.3636 | Val MacroF1=0.2161 | Val CCC=0.1008
Epoch 26/50 | Train Loss=1.996022 | Val Loss=2.752955 | Val Acc=0.2727 | Val MacroF1=0.1547 | Val CCC=-0.0809
Epoch 27/50 | Train Loss=2.076780 | Val Loss=2.620822 | Val Acc=0.2909 | Val MacroF1=0.1466 | Val CCC=0.0908
Epoch 28/50 | Train Loss=2.075961 | Val Loss=2.763310 | Val Acc=0.5273 | Val MacroF1=0.2500 | Val CCC=0.1121
Epoch 29/50 | Train Loss=2.191518 | Val Loss=2.601589 | Val Acc=0.4000 | Val MacroF1=0.1429 | Val CCC=0.0000
Epoch 30/50 | Train Loss=2.115491 | Val Loss=2.590240 | Val Acc=0.4000 | Val MacroF1=0.1429 | Val CCC=0.0000
Epoch 31/50 | Train Loss=2.076144 | Val Loss=2.647651 | Val Acc=0.5273 | Val MacroF1=0.2782 | Val CCC=0.0390
Epoch 32/50 | Train Loss=2.208399 | Val Loss=2.743424 | Val Acc=0.5091 | Val MacroF1=0.2567 | Val CCC=0.0620
Epoch 33/50 | Train Loss=2.060050 | Val Loss=2.636213 | Val Acc=0.4000 | Val MacroF1=0.1429 | Val CCC=0.0000
Epoch 34/50 | Train Loss=2.087107 | Val Loss=2.836614 | Val Acc=0.4909 | Val MacroF1=0.2832 | Val CCC=0.1639
Epoch 35/50 | Train Loss=2.073327 | Val Loss=2.563375 | Val Acc=0.2909 | Val MacroF1=0.1466 | Val CCC=0.0908
Epoch 36/50 | Train Loss=2.057040 | Val Loss=2.551481 | Val Acc=0.2909 | Val MacroF1=0.1466 | Val CCC=0.0908
Epoch 37/50 | Train Loss=2.096755 | Val Loss=2.658875 | Val Acc=0.5091 | Val MacroF1=0.2567 | Val CCC=0.0620
Epoch 38/50 | Train Loss=2.081021 | Val Loss=2.599981 | Val Acc=0.3636 | Val MacroF1=0.1838 | Val CCC=0.1273
Epoch 39/50 | Train Loss=2.093403 | Val Loss=2.538323 | Val Acc=0.4000 | Val MacroF1=0.1429 | Val CCC=0.0000
Epoch 40/50 | Train Loss=2.044575 | Val Loss=2.584084 | Val Acc=0.4000 | Val MacroF1=0.1429 | Val CCC=0.0000
Epoch 41/50 | Train Loss=2.023363 | Val Loss=2.585323 | Val Acc=0.5273 | Val MacroF1=0.2774 | Val CCC=0.1494
Epoch 42/50 | Train Loss=2.030240 | Val Loss=2.544141 | Val Acc=0.5455 | Val MacroF1=0.2928 | Val CCC=0.1288
Epoch 43/50 | Train Loss=2.023103 | Val Loss=2.563614 | Val Acc=0.4909 | Val MacroF1=0.3193 | Val CCC=0.2450
Epoch 44/50 | Train Loss=2.038806 | Val Loss=2.673505 | Val Acc=0.5455 | Val MacroF1=0.2832 | Val CCC=0.0773
Epoch 45/50 | Train Loss=2.001616 | Val Loss=2.577609 | Val Acc=0.4000 | Val MacroF1=0.1429 | Val CCC=0.0000
Epoch 46/50 | Train Loss=1.997658 | Val Loss=2.652114 | Val Acc=0.2909 | Val MacroF1=0.1470 | Val CCC=0.1180
Epoch 47/50 | Train Loss=2.078315 | Val Loss=2.597474 | Val Acc=0.5273 | Val MacroF1=0.2802 | Val CCC=0.1349
Epoch 48/50 | Train Loss=2.039008 | Val Loss=2.613122 | Val Acc=0.5455 | Val MacroF1=0.2928 | Val CCC=0.1288
Epoch 49/50 | Train Loss=2.011997 | Val Loss=2.563557 | Val Acc=0.3455 | Val MacroF1=0.1319 | Val CCC=-0.0313
Epoch 50/50 | Train Loss=1.992215 | Val Loss=2.632394 | Val Acc=0.4182 | Val MacroF1=0.2489 | Val CCC=0.1758
======================================================================
Q1 Seed=100训练结束
最佳验证Loss：2.529667，Epoch 8
最佳验证CCC：0.245012，Epoch 43
总耗时：19.17秒
Best Loss：/workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_100/question_1/best_loss.pt
Best CCC：/workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_100/question_1/best_ccc.pt
Last：/workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_100/question_1/last.pt
======================================================================
Q2 Seed=100尚未完成，开始正式训练
======================================================================
开始正式训练：Q2 PHQ_8Depressed，Seed=100
======================================================================
Epoch 01/50 | Train Loss=2.494173 | Val Loss=2.346297 | Val Acc=0.3455 | Val MacroF1=0.1284 | Val CCC=0.0000
Epoch 02/50 | Train Loss=2.398218 | Val Loss=2.356986 | Val Acc=0.3455 | Val MacroF1=0.1284 | Val CCC=0.0000
Epoch 03/50 | Train Loss=2.348593 | Val Loss=2.358079 | Val Acc=0.3455 | Val MacroF1=0.1284 | Val CCC=0.0000
Epoch 04/50 | Train Loss=2.385206 | Val Loss=2.386472 | Val Acc=0.3273 | Val MacroF1=0.1233 | Val CCC=0.0074
Epoch 05/50 | Train Loss=2.431863 | Val Loss=2.401024 | Val Acc=0.3273 | Val MacroF1=0.1286 | Val CCC=-0.0851
Epoch 06/50 | Train Loss=2.332892 | Val Loss=2.398360 | Val Acc=0.3455 | Val MacroF1=0.1284 | Val CCC=0.0000
Epoch 07/50 | Train Loss=2.284750 | Val Loss=2.396215 | Val Acc=0.2727 | Val MacroF1=0.1392 | Val CCC=0.0991
Epoch 08/50 | Train Loss=2.270078 | Val Loss=2.454307 | Val Acc=0.3273 | Val MacroF1=0.2230 | Val CCC=-0.0476
Epoch 09/50 | Train Loss=2.176322 | Val Loss=2.403009 | Val Acc=0.4182 | Val MacroF1=0.2669 | Val CCC=0.1460
Epoch 10/50 | Train Loss=2.220060 | Val Loss=2.367828 | Val Acc=0.4727 | Val MacroF1=0.2563 | Val CCC=0.0872
Epoch 11/50 | Train Loss=2.335967 | Val Loss=2.312406 | Val Acc=0.3273 | Val MacroF1=0.1304 | Val CCC=0.1063
Epoch 12/50 | Train Loss=2.335904 | Val Loss=2.364664 | Val Acc=0.2727 | Val MacroF1=0.1392 | Val CCC=0.0991
Epoch 13/50 | Train Loss=2.325187 | Val Loss=2.361443 | Val Acc=0.2727 | Val MacroF1=0.1392 | Val CCC=0.0991
Epoch 14/50 | Train Loss=2.313465 | Val Loss=2.410918 | Val Acc=0.3455 | Val MacroF1=0.1284 | Val CCC=0.0000
Epoch 15/50 | Train Loss=2.260652 | Val Loss=2.362275 | Val Acc=0.4727 | Val MacroF1=0.2424 | Val CCC=0.0690
Epoch 16/50 | Train Loss=2.347397 | Val Loss=2.418787 | Val Acc=0.2727 | Val MacroF1=0.1392 | Val CCC=0.0991
Epoch 17/50 | Train Loss=2.257155 | Val Loss=2.363357 | Val Acc=0.4364 | Val MacroF1=0.2708 | Val CCC=0.1867
Epoch 18/50 | Train Loss=2.218991 | Val Loss=2.368205 | Val Acc=0.2545 | Val MacroF1=0.1321 | Val CCC=0.0761
Epoch 19/50 | Train Loss=2.259673 | Val Loss=2.335736 | Val Acc=0.2727 | Val MacroF1=0.1392 | Val CCC=0.0991
Epoch 20/50 | Train Loss=2.230906 | Val Loss=2.379503 | Val Acc=0.3455 | Val MacroF1=0.1284 | Val CCC=0.0000
Epoch 21/50 | Train Loss=2.298121 | Val Loss=2.469623 | Val Acc=0.3091 | Val MacroF1=0.2105 | Val CCC=-0.0160
Epoch 22/50 | Train Loss=2.261697 | Val Loss=2.323801 | Val Acc=0.3455 | Val MacroF1=0.1284 | Val CCC=0.0000
Epoch 23/50 | Train Loss=2.248789 | Val Loss=2.441388 | Val Acc=0.3818 | Val MacroF1=0.2240 | Val CCC=0.1396
Epoch 24/50 | Train Loss=2.281246 | Val Loss=2.398917 | Val Acc=0.3455 | Val MacroF1=0.1284 | Val CCC=0.0000
Epoch 25/50 | Train Loss=2.254616 | Val Loss=2.397030 | Val Acc=0.4545 | Val MacroF1=0.2491 | Val CCC=0.0660
Epoch 26/50 | Train Loss=2.214150 | Val Loss=2.379985 | Val Acc=0.2727 | Val MacroF1=0.1392 | Val CCC=0.0991
Epoch 27/50 | Train Loss=2.240572 | Val Loss=2.333624 | Val Acc=0.2909 | Val MacroF1=0.1466 | Val CCC=0.1542
Epoch 28/50 | Train Loss=2.240570 | Val Loss=2.413847 | Val Acc=0.4364 | Val MacroF1=0.2285 | Val CCC=0.0675
Epoch 29/50 | Train Loss=2.241274 | Val Loss=2.398619 | Val Acc=0.2364 | Val MacroF1=0.1479 | Val CCC=0.0773
Epoch 30/50 | Train Loss=2.183406 | Val Loss=2.453363 | Val Acc=0.4727 | Val MacroF1=0.2526 | Val CCC=0.1038
Epoch 31/50 | Train Loss=2.305869 | Val Loss=2.363014 | Val Acc=0.3455 | Val MacroF1=0.1768 | Val CCC=0.0210
Epoch 32/50 | Train Loss=2.312829 | Val Loss=2.349005 | Val Acc=0.3455 | Val MacroF1=0.1284 | Val CCC=0.0000
Epoch 33/50 | Train Loss=2.290307 | Val Loss=2.407574 | Val Acc=0.4364 | Val MacroF1=0.2802 | Val CCC=0.1519
Epoch 34/50 | Train Loss=2.254314 | Val Loss=2.400630 | Val Acc=0.2909 | Val MacroF1=0.1473 | Val CCC=0.0680
Epoch 35/50 | Train Loss=2.211013 | Val Loss=2.360865 | Val Acc=0.2545 | Val MacroF1=0.1573 | Val CCC=0.0739
Epoch 36/50 | Train Loss=2.270253 | Val Loss=2.351868 | Val Acc=0.4364 | Val MacroF1=0.2427 | Val CCC=0.1151
Epoch 37/50 | Train Loss=2.250790 | Val Loss=2.356304 | Val Acc=0.2545 | Val MacroF1=0.1321 | Val CCC=0.0761
Epoch 38/50 | Train Loss=2.216724 | Val Loss=2.373863 | Val Acc=0.3455 | Val MacroF1=0.1284 | Val CCC=0.0000
Epoch 39/50 | Train Loss=2.244803 | Val Loss=2.334049 | Val Acc=0.3273 | Val MacroF1=0.2221 | Val CCC=0.1476
Epoch 40/50 | Train Loss=2.210967 | Val Loss=2.400575 | Val Acc=0.2727 | Val MacroF1=0.1392 | Val CCC=0.0991
Epoch 41/50 | Train Loss=2.335073 | Val Loss=2.376520 | Val Acc=0.3455 | Val MacroF1=0.1284 | Val CCC=0.0000
Epoch 42/50 | Train Loss=2.223292 | Val Loss=2.470295 | Val Acc=0.3091 | Val MacroF1=0.2291 | Val CCC=0.0455
Epoch 43/50 | Train Loss=2.237289 | Val Loss=2.281175 | Val Acc=0.3455 | Val MacroF1=0.1284 | Val CCC=0.0000
Epoch 44/50 | Train Loss=2.333992 | Val Loss=2.349058 | Val Acc=0.3273 | Val MacroF1=0.1981 | Val CCC=0.1208
Epoch 45/50 | Train Loss=2.204232 | Val Loss=2.351120 | Val Acc=0.2727 | Val MacroF1=0.1392 | Val CCC=0.0991
Epoch 46/50 | Train Loss=2.215480 | Val Loss=2.314730 | Val Acc=0.3455 | Val MacroF1=0.1708 | Val CCC=0.1459
Epoch 47/50 | Train Loss=2.186208 | Val Loss=2.355904 | Val Acc=0.2909 | Val MacroF1=0.1993 | Val CCC=0.0781
Epoch 48/50 | Train Loss=2.242292 | Val Loss=2.329486 | Val Acc=0.2909 | Val MacroF1=0.1888 | Val CCC=0.1074
Epoch 49/50 | Train Loss=2.244500 | Val Loss=2.359998 | Val Acc=0.3818 | Val MacroF1=0.2530 | Val CCC=0.1669
Epoch 50/50 | Train Loss=2.220626 | Val Loss=2.361124 | Val Acc=0.3818 | Val MacroF1=0.2483 | Val CCC=0.1784
======================================================================
Q2 Seed=100训练结束
最佳验证Loss：2.281175，Epoch 43
最佳验证CCC：0.186750，Epoch 17
总耗时：17.87秒
Best Loss：/workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_100/question_2/best_loss.pt
Best CCC：/workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_100/question_2/best_ccc.pt
Last：/workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_100/question_2/last.pt
======================================================================
Q3 Seed=100尚未完成，开始正式训练
======================================================================
开始正式训练：Q3 PHQ_8Sleep，Seed=100
======================================================================
Epoch 01/50 | Train Loss=2.731375 | Val Loss=2.562069 | Val Acc=0.3091 | Val MacroF1=0.1181 | Val CCC=0.0000
Epoch 02/50 | Train Loss=2.733456 | Val Loss=2.519521 | Val Acc=0.3091 | Val MacroF1=0.1181 | Val CCC=0.0000
Epoch 03/50 | Train Loss=2.688849 | Val Loss=2.534641 | Val Acc=0.3091 | Val MacroF1=0.1181 | Val CCC=0.0000
Epoch 04/50 | Train Loss=2.711211 | Val Loss=2.536248 | Val Acc=0.1455 | Val MacroF1=0.0635 | Val CCC=0.0000
Epoch 05/50 | Train Loss=2.673960 | Val Loss=2.501755 | Val Acc=0.3091 | Val MacroF1=0.1181 | Val CCC=0.0000
Epoch 06/50 | Train Loss=2.673508 | Val Loss=2.505122 | Val Acc=0.3091 | Val MacroF1=0.1181 | Val CCC=0.0000
Epoch 07/50 | Train Loss=2.650730 | Val Loss=2.542527 | Val Acc=0.3455 | Val MacroF1=0.1937 | Val CCC=0.1044
Epoch 08/50 | Train Loss=2.680906 | Val Loss=2.530982 | Val Acc=0.3273 | Val MacroF1=0.1833 | Val CCC=0.0428
Epoch 09/50 | Train Loss=2.611054 | Val Loss=2.608169 | Val Acc=0.3273 | Val MacroF1=0.1791 | Val CCC=0.0405
Epoch 10/50 | Train Loss=2.582753 | Val Loss=2.481124 | Val Acc=0.3273 | Val MacroF1=0.1838 | Val CCC=0.0720
Epoch 11/50 | Train Loss=2.554385 | Val Loss=2.500681 | Val Acc=0.3273 | Val MacroF1=0.1834 | Val CCC=0.0665
Epoch 12/50 | Train Loss=2.567048 | Val Loss=2.475836 | Val Acc=0.2909 | Val MacroF1=0.1691 | Val CCC=0.1335
Epoch 13/50 | Train Loss=2.532476 | Val Loss=2.670595 | Val Acc=0.2909 | Val MacroF1=0.1974 | Val CCC=0.1567
Epoch 14/50 | Train Loss=2.583830 | Val Loss=2.481970 | Val Acc=0.3273 | Val MacroF1=0.1833 | Val CCC=0.0428
Epoch 15/50 | Train Loss=2.548339 | Val Loss=2.475516 | Val Acc=0.3273 | Val MacroF1=0.1838 | Val CCC=0.0720
Epoch 16/50 | Train Loss=2.509832 | Val Loss=2.509513 | Val Acc=0.3091 | Val MacroF1=0.1756 | Val CCC=0.0369
Epoch 17/50 | Train Loss=2.493778 | Val Loss=2.492737 | Val Acc=0.3273 | Val MacroF1=0.1833 | Val CCC=0.0428
Epoch 18/50 | Train Loss=2.517832 | Val Loss=2.490669 | Val Acc=0.3273 | Val MacroF1=0.1833 | Val CCC=0.0428
Epoch 19/50 | Train Loss=2.481332 | Val Loss=2.485261 | Val Acc=0.3091 | Val MacroF1=0.1756 | Val CCC=0.0369
Epoch 20/50 | Train Loss=2.448786 | Val Loss=2.487727 | Val Acc=0.3273 | Val MacroF1=0.1834 | Val CCC=0.0665
Epoch 21/50 | Train Loss=2.497221 | Val Loss=2.495786 | Val Acc=0.2909 | Val MacroF1=0.1681 | Val CCC=0.0851
Epoch 22/50 | Train Loss=2.468005 | Val Loss=2.484287 | Val Acc=0.3273 | Val MacroF1=0.1834 | Val CCC=0.0665
Epoch 23/50 | Train Loss=2.439206 | Val Loss=2.499867 | Val Acc=0.3273 | Val MacroF1=0.1856 | Val CCC=0.0374
Epoch 24/50 | Train Loss=2.474497 | Val Loss=2.504541 | Val Acc=0.3273 | Val MacroF1=0.1834 | Val CCC=0.0665
Epoch 25/50 | Train Loss=2.453414 | Val Loss=2.495436 | Val Acc=0.3273 | Val MacroF1=0.1834 | Val CCC=0.0665
Epoch 26/50 | Train Loss=2.468597 | Val Loss=2.492035 | Val Acc=0.3091 | Val MacroF1=0.1751 | Val CCC=0.0647
Epoch 27/50 | Train Loss=2.459726 | Val Loss=2.521950 | Val Acc=0.3273 | Val MacroF1=0.1834 | Val CCC=0.0665
Epoch 28/50 | Train Loss=2.439179 | Val Loss=2.502117 | Val Acc=0.2909 | Val MacroF1=0.1691 | Val CCC=0.1335
Epoch 29/50 | Train Loss=2.445933 | Val Loss=2.511788 | Val Acc=0.3273 | Val MacroF1=0.1834 | Val CCC=0.0665
Epoch 30/50 | Train Loss=2.522507 | Val Loss=2.521884 | Val Acc=0.3273 | Val MacroF1=0.1833 | Val CCC=0.0428
Epoch 31/50 | Train Loss=2.491101 | Val Loss=2.513095 | Val Acc=0.3273 | Val MacroF1=0.1834 | Val CCC=0.0665
Epoch 32/50 | Train Loss=2.425661 | Val Loss=2.516329 | Val Acc=0.3273 | Val MacroF1=0.1834 | Val CCC=0.0665
Epoch 33/50 | Train Loss=2.470388 | Val Loss=2.508963 | Val Acc=0.3273 | Val MacroF1=0.1834 | Val CCC=0.0665
Epoch 34/50 | Train Loss=2.465527 | Val Loss=2.489193 | Val Acc=0.3273 | Val MacroF1=0.1833 | Val CCC=0.0428
Epoch 35/50 | Train Loss=2.482135 | Val Loss=2.538432 | Val Acc=0.3455 | Val MacroF1=0.2333 | Val CCC=0.1557
Epoch 36/50 | Train Loss=2.476683 | Val Loss=2.484441 | Val Acc=0.3273 | Val MacroF1=0.1833 | Val CCC=0.0428
Epoch 37/50 | Train Loss=2.481791 | Val Loss=2.520027 | Val Acc=0.3273 | Val MacroF1=0.1833 | Val CCC=0.0428
Epoch 38/50 | Train Loss=2.483720 | Val Loss=2.476746 | Val Acc=0.2909 | Val MacroF1=0.1673 | Val CCC=0.0356
Epoch 39/50 | Train Loss=2.489906 | Val Loss=2.533928 | Val Acc=0.3091 | Val MacroF1=0.2336 | Val CCC=0.0871
Epoch 40/50 | Train Loss=2.436451 | Val Loss=2.519601 | Val Acc=0.2909 | Val MacroF1=0.1681 | Val CCC=0.0851
Epoch 41/50 | Train Loss=2.478177 | Val Loss=2.496544 | Val Acc=0.3273 | Val MacroF1=0.1834 | Val CCC=0.0665
Epoch 42/50 | Train Loss=2.444163 | Val Loss=2.515718 | Val Acc=0.3273 | Val MacroF1=0.1834 | Val CCC=0.0665
Epoch 43/50 | Train Loss=2.425101 | Val Loss=2.497003 | Val Acc=0.3273 | Val MacroF1=0.1834 | Val CCC=0.0665
Epoch 44/50 | Train Loss=2.432382 | Val Loss=2.514518 | Val Acc=0.3273 | Val MacroF1=0.1833 | Val CCC=0.0428
Epoch 45/50 | Train Loss=2.450301 | Val Loss=2.502786 | Val Acc=0.3273 | Val MacroF1=0.1834 | Val CCC=0.0665
Epoch 46/50 | Train Loss=2.454383 | Val Loss=2.516569 | Val Acc=0.3273 | Val MacroF1=0.1833 | Val CCC=0.0428
Epoch 47/50 | Train Loss=2.441258 | Val Loss=2.509932 | Val Acc=0.3273 | Val MacroF1=0.1834 | Val CCC=0.0665
Epoch 48/50 | Train Loss=2.429774 | Val Loss=2.552816 | Val Acc=0.3091 | Val MacroF1=0.1751 | Val CCC=0.0647
Epoch 49/50 | Train Loss=2.457710 | Val Loss=2.503796 | Val Acc=0.3273 | Val MacroF1=0.1834 | Val CCC=0.0665
Epoch 50/50 | Train Loss=2.520727 | Val Loss=2.556933 | Val Acc=0.3273 | Val MacroF1=0.1833 | Val CCC=0.0428
======================================================================
Q3 Seed=100训练结束
最佳验证Loss：2.475516，Epoch 15
最佳验证CCC：0.156694，Epoch 13
总耗时：17.87秒
Best Loss：/workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_100/question_3/best_loss.pt
Best CCC：/workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_100/question_3/best_ccc.pt
Last：/workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_100/question_3/last.pt
======================================================================
Q4 Seed=100尚未完成，开始正式训练
======================================================================
开始正式训练：Q4 PHQ_8Tired，Seed=100
======================================================================
Epoch 01/50 | Train Loss=2.606589 | Val Loss=2.481314 | Val Acc=0.4182 | Val MacroF1=0.1474 | Val CCC=0.0000
Epoch 02/50 | Train Loss=2.597139 | Val Loss=2.455495 | Val Acc=0.3455 | Val MacroF1=0.1580 | Val CCC=-0.0685
Epoch 03/50 | Train Loss=2.473433 | Val Loss=2.459234 | Val Acc=0.4182 | Val MacroF1=0.1474 | Val CCC=0.0000
Epoch 04/50 | Train Loss=2.531798 | Val Loss=2.574353 | Val Acc=0.1636 | Val MacroF1=0.0703 | Val CCC=0.0000
Epoch 05/50 | Train Loss=2.513766 | Val Loss=2.440962 | Val Acc=0.4182 | Val MacroF1=0.1474 | Val CCC=0.0000
Epoch 06/50 | Train Loss=2.551194 | Val Loss=2.459939 | Val Acc=0.4182 | Val MacroF1=0.1474 | Val CCC=0.0000
Epoch 07/50 | Train Loss=2.519374 | Val Loss=2.480376 | Val Acc=0.1636 | Val MacroF1=0.0703 | Val CCC=0.0000
Epoch 08/50 | Train Loss=2.511711 | Val Loss=2.445271 | Val Acc=0.3818 | Val MacroF1=0.1945 | Val CCC=0.1690
Epoch 09/50 | Train Loss=2.444086 | Val Loss=2.349796 | Val Acc=0.4182 | Val MacroF1=0.2125 | Val CCC=0.1822
Epoch 10/50 | Train Loss=2.442674 | Val Loss=2.357648 | Val Acc=0.3818 | Val MacroF1=0.1945 | Val CCC=0.1690

,Question_Number,Question,Seed,Best_Loss,Best_Loss_Epoch,Best_CCC,Best_CCC_Epoch,Loaded_From_Disk,Elapsed_Seconds
0,1,PHQ_8NoInterest,100,2.529667,8,0.245012,43,False,19.169299
1,2,PHQ_8Depressed,100,2.281175,43,0.186750,17,False,17.870027
2,3,PHQ_8Sleep,100,2.475516,15,0.156694,13,False,17.867615
3,4,PHQ_8Tired,100,2.322259,47,0.183022,21,False,18.615410
4,5,PHQ_8Appetite,100,2.207972,7,0.083353,13,False,18.579286
5,6,PHQ_8Failure,100,2.257047,47,0.191169,23,False,18.629285
6,7,PHQ_8Concentrating,100,2.287100,4,0.130372,39,False,18.439207
7,8,PHQ_8Moving,100,1.778134,12,0.179163,20,False,18.516966

################################################################################
开始处理Audio-only全部8道题，Seed=1234
################################################################################
Q1 Seed=1234尚未完成，开始正式训练
======================================================================
开始正式训练：Q1 PHQ_8NoInterest，Seed=1234
======================================================================
Epoch 01/50 | Train Loss=2.195702 | Val Loss=2.603054 | Val Acc=0.4000 | Val MacroF1=0.1429 | Val CCC=0.0000
Epoch 02/50 | Train Loss=2.205141 | Val Loss=2.573020 | Val Acc=0.4000 | Val MacroF1=0.1429 | Val CCC=0.0000
Epoch 03/50 | Train Loss=2.141337 | Val Loss=2.565107 | Val Acc=0.4000 | Val MacroF1=0.1429 | Val CCC=0.0000
Epoch 04/50 | Train Loss=2.133400 | Val Loss=2.522752 | Val Acc=0.4000 | Val MacroF1=0.1429 | Val CCC=0.0000
Epoch 05/50 | Train Loss=2.092318 | Val Loss=2.575061 | Val Acc=0.4000 | Val MacroF1=0.1429 | Val CCC=0.0000
Epoch 06/50 | Train Loss=2.160015 | Val Loss=3.482110 | Val Acc=0.4545 | Val MacroF1=0.1562 | Val CCC=0.0000
Epoch 07/50 | Train Loss=2.223071 | Val Loss=2.581717 | Val Acc=0.4909 | Val MacroF1=0.2157 | Val CCC=0.0971
Epoch 08/50 | Train Loss=2.099409 | Val Loss=2.540779 | Val Acc=0.3636 | Val MacroF1=0.1838 | Val CCC=0.1273
Epoch 09/50 | Train Loss=2.099883 | Val Loss=2.654803 | Val Acc=0.5273 | Val MacroF1=0.2702 | Val CCC=0.0696
Epoch 10/50 | Train Loss=2.189647 | Val Loss=2.629373 | Val Acc=0.4545 | Val MacroF1=0.2122 | Val CCC=0.1723
Epoch 11/50 | Train Loss=2.054010 | Val Loss=2.549805 | Val Acc=0.5455 | Val MacroF1=0.2946 | Val CCC=0.2196
Epoch 12/50 | Train Loss=2.057148 | Val Loss=2.570621 | Val Acc=0.4727 | Val MacroF1=0.3061 | Val CCC=0.2466
Epoch 13/50 | Train Loss=2.039080 | Val Loss=2.616015 | Val Acc=0.4000 | Val MacroF1=0.1429 | Val CCC=0.0000
Epoch 14/50 | Train Loss=2.098988 | Val Loss=2.656089 | Val Acc=0.4545 | Val MacroF1=0.2122 | Val CCC=0.1723
Epoch 15/50 | Train Loss=2.066042 | Val Loss=2.542602 | Val Acc=0.3636 | Val MacroF1=0.1838 | Val CCC=0.1273
Epoch 16/50 | Train Loss=2.042535 | Val Loss=2.561645 | Val Acc=0.4000 | Val MacroF1=0.1429 | Val CCC=0.0000
Epoch 17/50 | Train Loss=2.094784 | Val Loss=2.543515 | Val Acc=0.4000 | Val MacroF1=0.1429 | Val CCC=0.0000
Epoch 18/50 | Train Loss=2.029436 | Val Loss=2.517797 | Val Acc=0.3273 | Val MacroF1=0.1649 | Val CCC=0.1374
Epoch 19/50 | Train Loss=2.052702 | Val Loss=2.537396 | Val Acc=0.3455 | Val MacroF1=0.1740 | Val CCC=0.1325
Epoch 20/50 | Train Loss=2.023032 | Val Loss=2.681509 | Val Acc=0.4909 | Val MacroF1=0.2924 | Val CCC=0.1521
Epoch 21/50 | Train Loss=2.113223 | Val Loss=2.586657 | Val Acc=0.2909 | Val MacroF1=0.1470 | Val CCC=0.1180
Epoch 22/50 | Train Loss=2.081468 | Val Loss=2.582793 | Val Acc=0.4000 | Val MacroF1=0.1429 | Val CCC=0.0000
Epoch 23/50 | Train Loss=2.028390 | Val Loss=2.560686 | Val Acc=0.4000 | Val MacroF1=0.1429 | Val CCC=0.0000
Epoch 24/50 | Train Loss=2.035267 | Val Loss=2.537637 | Val Acc=0.3818 | Val MacroF1=0.1382 | Val CCC=0.0102
Epoch 25/50 | Train Loss=2.007147 | Val Loss=2.571499 | Val Acc=0.4182 | Val MacroF1=0.2489 | Val CCC=0.1758
Epoch 26/50 | Train Loss=2.006050 | Val Loss=2.585356 | Val Acc=0.3818 | Val MacroF1=0.1419 | Val CCC=0.0693
Epoch 27/50 | Train Loss=2.010553 | Val Loss=2.562476 | Val Acc=0.3455 | Val MacroF1=0.1740 | Val CCC=0.1325
Epoch 28/50 | Train Loss=2.020304 | Val Loss=2.600562 | Val Acc=0.5273 | Val MacroF1=0.2802 | Val CCC=0.1349
Epoch 29/50 | Train Loss=2.010211 | Val Loss=2.632343 | Val Acc=0.4000 | Val MacroF1=0.1429 | Val CCC=0.0000
Epoch 30/50 | Train Loss=2.014757 | Val Loss=2.679503 | Val Acc=0.4909 | Val MacroF1=0.2924 | Val CCC=0.1521
Epoch 31/50 | Train Loss=2.017391 | Val Loss=2.654666 | Val Acc=0.4182 | Val MacroF1=0.2396 | Val CCC=0.1865
Epoch 32/50 | Train Loss=2.048905 | Val Loss=2.611591 | Val Acc=0.3273 | Val MacroF1=0.1635 | Val CCC=0.1077
Epoch 33/50 | Train Loss=2.055192 | Val Loss=2.568220 | Val Acc=0.3636 | Val MacroF1=0.1370 | Val CCC=0.0766
Epoch 34/50 | Train Loss=1.977950 | Val Loss=2.769685 | Val Acc=0.4364 | Val MacroF1=0.2328 | Val CCC=0.1286
Epoch 35/50 | Train Loss=2.076172 | Val Loss=2.619321 | Val Acc=0.5273 | Val MacroF1=0.2802 | Val CCC=0.1349
Epoch 36/50 | Train Loss=2.024974 | Val Loss=2.627908 | Val Acc=0.4182 | Val MacroF1=0.2489 | Val CCC=0.1758
Epoch 37/50 | Train Loss=2.006659 | Val Loss=2.600833 | Val Acc=0.5273 | Val MacroF1=0.2802 | Val CCC=0.1349
Epoch 38/50 | Train Loss=2.044118 | Val Loss=2.616099 | Val Acc=0.3636 | Val MacroF1=0.1838 | Val CCC=0.1273
Epoch 39/50 | Train Loss=2.006398 | Val Loss=2.640145 | Val Acc=0.4182 | Val MacroF1=0.2401 | Val CCC=0.2092
Epoch 40/50 | Train Loss=2.000695 | Val Loss=2.605161 | Val Acc=0.4000 | Val MacroF1=0.1429 | Val CCC=0.0000
Epoch 41/50 | Train Loss=2.017227 | Val Loss=2.639330 | Val Acc=0.4000 | Val MacroF1=0.1429 | Val CCC=0.0000
Epoch 42/50 | Train Loss=2.034119 | Val Loss=2.641130 | Val Acc=0.2727 | Val MacroF1=0.1389 | Val CCC=0.0706
Epoch 43/50 | Train Loss=1.977359 | Val Loss=2.625444 | Val Acc=0.4000 | Val MacroF1=0.1429 | Val CCC=0.0000
Epoch 44/50 | Train Loss=1.999837 | Val Loss=2.602909 | Val Acc=0.4000 | Val MacroF1=0.1429 | Val CCC=0.0000
Epoch 45/50 | Train Loss=2.003462 | Val Loss=2.588665 | Val Acc=0.3636 | Val MacroF1=0.1838 | Val CCC=0.1273
Epoch 46/50 | Train Loss=2.009659 | Val Loss=2.665994 | Val Acc=0.5273 | Val MacroF1=0.2782 | Val CCC=0.0390
Epoch 47/50 | Train Loss=2.016610 | Val Loss=2.701297 | Val Acc=0.5455 | Val MacroF1=0.2832 | Val CCC=0.0773
Epoch 48/50 | Train Loss=2.009668 | Val Loss=2.648986 | Val Acc=0.2909 | Val MacroF1=0.1470 | Val CCC=0.1180
Epoch 49/50 | Train Loss=2.015836 | Val Loss=2.642339 | Val Acc=0.4000 | Val MacroF1=0.1429 | Val CCC=0.0000
Epoch 50/50 | Train Loss=1.993201 | Val Loss=2.646611 | Val Acc=0.2909 | Val MacroF1=0.1470 | Val CCC=0.1180
======================================================================
Q1 Seed=1234训练结束
最佳验证Loss：2.517797，Epoch 18
最佳验证CCC：0.246618，Epoch 12
总耗时：18.50秒
Best Loss：/workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_1234/question_1/best_loss.pt
Best CCC：/workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_1234/question_1/best_ccc.pt
Last：/workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_1234/question_1/last.pt
======================================================================
Q2 Seed=1234尚未完成，开始正式训练
======================================================================
开始正式训练：Q2 PHQ_8Depressed，Seed=1234
======================================================================
Epoch 01/50 | Train Loss=2.434526 | Val Loss=2.341745 | Val Acc=0.3455 | Val MacroF1=0.1284 | Val CCC=0.0000
Epoch 02/50 | Train Loss=2.410227 | Val Loss=2.575319 | Val Acc=0.4545 | Val MacroF1=0.1562 | Val CCC=0.0000
Epoch 03/50 | Train Loss=2.440623 | Val Loss=2.383205 | Val Acc=0.3455 | Val MacroF1=0.1284 | Val CCC=0.0000
Epoch 04/50 | Train Loss=2.395011 | Val Loss=2.456884 | Val Acc=0.3455 | Val MacroF1=0.1284 | Val CCC=0.0000
Epoch 05/50 | Train Loss=2.386802 | Val Loss=2.312972 | Val Acc=0.3455 | Val MacroF1=0.1284 | Val CCC=0.0000
Epoch 06/50 | Train Loss=2.412116 | Val Loss=2.293448 | Val Acc=0.3455 | Val MacroF1=0.1284 | Val CCC=0.0000
Epoch 07/50 | Train Loss=2.440401 | Val Loss=2.356560 | Val Acc=0.3455 | Val MacroF1=0.1284 | Val CCC=0.0000
Epoch 08/50 | Train Loss=2.339143 | Val Loss=2.309113 | Val Acc=0.3455 | Val MacroF1=0.1284 | Val CCC=0.0000
Epoch 09/50 | Train Loss=2.311104 | Val Loss=2.368894 | Val Acc=0.3455 | Val MacroF1=0.1284 | Val CCC=0.0000
Epoch 10/50 | Train Loss=2.246412 | Val Loss=2.468762 | Val Acc=0.4727 | Val MacroF1=0.2729 | Val CCC=0.1746
Epoch 11/50 | Train Loss=2.355154 | Val Loss=2.278944 | Val Acc=0.3455 | Val MacroF1=0.1284 | Val CCC=0.0000
Epoch 12/50 | Train Loss=2.382576 | Val Loss=2.329305 | Val Acc=0.4727 | Val MacroF1=0.2826 | Val CCC=0.1617
Epoch 13/50 | Train Loss=2.299120 | Val Loss=2.301492 | Val Acc=0.4182 | Val MacroF1=0.2328 | Val CCC=0.0901
Epoch 14/50 | Train Loss=2.277992 | Val Loss=2.394428 | Val Acc=0.4727 | Val MacroF1=0.2351 | Val CCC=0.0848
Epoch 15/50 | Train Loss=2.246073 | Val Loss=2.333838 | Val Acc=0.2727 | Val MacroF1=0.1392 | Val CCC=0.0991
Epoch 16/50 | Train Loss=2.299862 | Val Loss=2.349351 | Val Acc=0.3091 | Val MacroF1=0.1543 | Val CCC=0.1209
Epoch 17/50 | Train Loss=2.257572 | Val Loss=2.351621 | Val Acc=0.2545 | Val MacroF1=0.1321 | Val CCC=0.0761
Epoch 18/50 | Train Loss=2.247298 | Val Loss=2.344023 | Val Acc=0.2727 | Val MacroF1=0.1392 | Val CCC=0.0991
Epoch 19/50 | Train Loss=2.243434 | Val Loss=2.345758 | Val Acc=0.2727 | Val MacroF1=0.1392 | Val CCC=0.0991
Epoch 20/50 | Train Loss=2.249403 | Val Loss=2.336572 | Val Acc=0.2545 | Val MacroF1=0.1321 | Val CCC=0.0761
Epoch 21/50 | Train Loss=2.256672 | Val Loss=2.356102 | Val Acc=0.4364 | Val MacroF1=0.2642 | Val CCC=0.1617
Epoch 22/50 | Train Loss=2.274150 | Val Loss=2.337701 | Val Acc=0.3455 | Val MacroF1=0.1721 | Val CCC=0.1793
Epoch 23/50 | Train Loss=2.274521 | Val Loss=2.365919 | Val Acc=0.3455 | Val MacroF1=0.1708 | Val CCC=0.1459
Epoch 24/50 | Train Loss=2.297415 | Val Loss=2.364075 | Val Acc=0.3455 | Val MacroF1=0.1284 | Val CCC=0.0000
Epoch 25/50 | Train Loss=2.278154 | Val Loss=2.310495 | Val Acc=0.3455 | Val MacroF1=0.1708 | Val CCC=0.1459
Epoch 26/50 | Train Loss=2.222670 | Val Loss=2.370166 | Val Acc=0.2727 | Val MacroF1=0.1557 | Val CCC=0.0589
Epoch 27/50 | Train Loss=2.212486 | Val Loss=2.401992 | Val Acc=0.4727 | Val MacroF1=0.2526 | Val CCC=0.1038
Epoch 28/50 | Train Loss=2.247985 | Val Loss=2.410410 | Val Acc=0.3455 | Val MacroF1=0.1284 | Val CCC=0.0000
Epoch 29/50 | Train Loss=2.238498 | Val Loss=2.332691 | Val Acc=0.3091 | Val MacroF1=0.1543 | Val CCC=0.1209
Epoch 30/50 | Train Loss=2.256245 | Val Loss=2.343953 | Val Acc=0.4545 | Val MacroF1=0.2852 | Val CCC=0.1854
Epoch 31/50 | Train Loss=2.256051 | Val Loss=2.379411 | Val Acc=0.3455 | Val MacroF1=0.1284 | Val CCC=0.0000
Epoch 32/50 | Train Loss=2.239931 | Val Loss=2.335037 | Val Acc=0.3091 | Val MacroF1=0.1543 | Val CCC=0.1209
Epoch 33/50 | Train Loss=2.287007 | Val Loss=2.390674 | Val Acc=0.2545 | Val MacroF1=0.1471 | Val CCC=0.0629
Epoch 34/50 | Train Loss=2.239368 | Val Loss=2.394615 | Val Acc=0.4545 | Val MacroF1=0.2344 | Val CCC=0.0472
Epoch 35/50 | Train Loss=2.258480 | Val Loss=2.384666 | Val Acc=0.3636 | Val MacroF1=0.2068 | Val CCC=0.1009
Epoch 36/50 | Train Loss=2.226190 | Val Loss=2.349237 | Val Acc=0.2727 | Val MacroF1=0.1392 | Val CCC=0.0991
Epoch 37/50 | Train Loss=2.201121 | Val Loss=2.362192 | Val Acc=0.4727 | Val MacroF1=0.2563 | Val CCC=0.0872
Epoch 38/50 | Train Loss=2.291322 | Val Loss=2.426270 | Val Acc=0.2727 | Val MacroF1=0.1392 | Val CCC=0.0991
Epoch 39/50 | Train Loss=2.213521 | Val Loss=2.366476 | Val Acc=0.3455 | Val MacroF1=0.1284 | Val CCC=0.0000
Epoch 40/50 | Train Loss=2.219464 | Val Loss=2.366360 | Val Acc=0.2545 | Val MacroF1=0.1321 | Val CCC=0.0761
Epoch 41/50 | Train Loss=2.223485 | Val Loss=2.345242 | Val Acc=0.2727 | Val MacroF1=0.1389 | Val CCC=0.1273
Epoch 42/50 | Train Loss=2.218433 | Val Loss=2.350640 | Val Acc=0.2545 | Val MacroF1=0.1321 | Val CCC=0.0761
Epoch 43/50 | Train Loss=2.257059 | Val Loss=2.361275 | Val Acc=0.2727 | Val MacroF1=0.1392 | Val CCC=0.0991
Epoch 44/50 | Train Loss=2.233023 | Val Loss=2.369664 | Val Acc=0.2545 | Val MacroF1=0.1321 | Val CCC=0.0761
Epoch 45/50 | Train Loss=2.208929 | Val Loss=2.337125 | Val Acc=0.2727 | Val MacroF1=0.1392 | Val CCC=0.0991
Epoch 46/50 | Train Loss=2.242124 | Val Loss=2.376048 | Val Acc=0.2727 | Val MacroF1=0.1392 | Val CCC=0.0991
Epoch 47/50 | Train Loss=2.230345 | Val Loss=2.366725 | Val Acc=0.2545 | Val MacroF1=0.1329 | Val CCC=0.0506
Epoch 48/50 | Train Loss=2.215079 | Val Loss=2.367334 | Val Acc=0.2545 | Val MacroF1=0.1321 | Val CCC=0.0761
Epoch 49/50 | Train Loss=2.210259 | Val Loss=2.365959 | Val Acc=0.2545 | Val MacroF1=0.1321 | Val CCC=0.0761
Epoch 50/50 | Train Loss=2.203709 | Val Loss=2.342350 | Val Acc=0.3091 | Val MacroF1=0.1543 | Val CCC=0.1209
======================================================================
Q2 Seed=1234训练结束
最佳验证Loss：2.278944，Epoch 11
最佳验证CCC：0.185385，Epoch 30
总耗时：18.47秒
Best Loss：/workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_1234/question_2/best_loss.pt
Best CCC：/workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_1234/question_2/best_ccc.pt
Last：/workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_1234/question_2/last.pt
======================================================================
Q3 Seed=1234尚未完成，开始正式训练
======================================================================
开始正式训练：Q3 PHQ_8Sleep，Seed=1234
======================================================================
Epoch 01/50 | Train Loss=2.701971 | Val Loss=2.555273 | Val Acc=0.2545 | Val MacroF1=0.1029 | Val CCC=-0.0349
Epoch 02/50 | Train Loss=2.659214 | Val Loss=2.529677 | Val Acc=0.3091 | Val MacroF1=0.1181 | Val CCC=0.0000
Epoch 03/50 | Train Loss=2.730588 | Val Loss=2.550217 | Val Acc=0.3091 | Val MacroF1=0.1181 | Val CCC=0.0000
Epoch 04/50 | Train Loss=2.697718 | Val Loss=2.543179 | Val Acc=0.3273 | Val MacroF1=0.1686 | Val CCC=-0.0342
Epoch 05/50 | Train Loss=2.619373 | Val Loss=2.537955 | Val Acc=0.3091 | Val MacroF1=0.1181 | Val CCC=0.0000
Epoch 06/50 | Train Loss=2.721338 | Val Loss=2.487866 | Val Acc=0.3273 | Val MacroF1=0.1645 | Val CCC=-0.0361
Epoch 07/50 | Train Loss=2.582021 | Val Loss=2.492778 | Val Acc=0.3273 | Val MacroF1=0.1832 | Val CCC=0.0142
Epoch 08/50 | Train Loss=2.525582 | Val Loss=2.540878 | Val Acc=0.3636 | Val MacroF1=0.2688 | Val CCC=0.0886
Epoch 09/50 | Train Loss=2.559851 | Val Loss=2.500690 | Val Acc=0.2545 | Val MacroF1=0.1521 | Val CCC=0.1287
Epoch 10/50 | Train Loss=2.550859 | Val Loss=2.523292 | Val Acc=0.2727 | Val MacroF1=0.1607 | Val CCC=0.1311
Epoch 11/50 | Train Loss=2.589943 | Val Loss=2.500976 | Val Acc=0.3273 | Val MacroF1=0.1645 | Val CCC=-0.0361
Epoch 12/50 | Train Loss=2.508314 | Val Loss=2.494576 | Val Acc=0.3091 | Val MacroF1=0.1764 | Val CCC=0.0871
Epoch 13/50 | Train Loss=2.522800 | Val Loss=2.596055 | Val Acc=0.3091 | Val MacroF1=0.1181 | Val CCC=0.0000
Epoch 14/50 | Train Loss=2.654905 | Val Loss=2.470923 | Val Acc=0.3273 | Val MacroF1=0.1833 | Val CCC=0.0428
Epoch 15/50 | Train Loss=2.486658 | Val Loss=2.595099 | Val Acc=0.2727 | Val MacroF1=0.1607 | Val CCC=0.1311
Epoch 16/50 | Train Loss=2.577868 | Val Loss=2.525311 | Val Acc=0.3455 | Val MacroF1=0.1914 | Val CCC=0.1278
Epoch 17/50 | Train Loss=2.528978 | Val Loss=2.481982 | Val Acc=0.3091 | Val MacroF1=0.1751 | Val CCC=0.0647
Epoch 18/50 | Train Loss=2.475179 | Val Loss=2.495130 | Val Acc=0.3273 | Val MacroF1=0.1833 | Val CCC=0.0428
Epoch 19/50 | Train Loss=2.470866 | Val Loss=2.494203 | Val Acc=0.2909 | Val MacroF1=0.1681 | Val CCC=0.0851
Epoch 20/50 | Train Loss=2.438590 | Val Loss=2.500613 | Val Acc=0.3273 | Val MacroF1=0.1833 | Val CCC=0.0428
Epoch 21/50 | Train Loss=2.488224 | Val Loss=2.498175 | Val Acc=0.3273 | Val MacroF1=0.1834 | Val CCC=0.0665
Epoch 22/50 | Train Loss=2.475252 | Val Loss=2.493510 | Val Acc=0.3273 | Val MacroF1=0.1834 | Val CCC=0.0665
Epoch 23/50 | Train Loss=2.480292 | Val Loss=2.484634 | Val Acc=0.3273 | Val MacroF1=0.1834 | Val CCC=0.0665
Epoch 24/50 | Train Loss=2.485196 | Val Loss=2.485752 | Val Acc=0.2909 | Val MacroF1=0.1696 | Val CCC=0.0812
Epoch 25/50 | Train Loss=2.460027 | Val Loss=2.494637 | Val Acc=0.3273 | Val MacroF1=0.1834 | Val CCC=0.0665
Epoch 26/50 | Train Loss=2.486678 | Val Loss=2.485262 | Val Acc=0.2909 | Val MacroF1=0.1681 | Val CCC=0.0851
Epoch 27/50 | Train Loss=2.453712 | Val Loss=2.491210 | Val Acc=0.3273 | Val MacroF1=0.1834 | Val CCC=0.0665
Epoch 28/50 | Train Loss=2.463255 | Val Loss=2.525436 | Val Acc=0.3273 | Val MacroF1=0.1834 | Val CCC=0.0665
Epoch 29/50 | Train Loss=2.459502 | Val Loss=2.487152 | Val Acc=0.3273 | Val MacroF1=0.1834 | Val CCC=0.0665
Epoch 30/50 | Train Loss=2.475815 | Val Loss=2.479613 | Val Acc=0.3273 | Val MacroF1=0.1833 | Val CCC=0.0428
Epoch 31/50 | Train Loss=2.465583 | Val Loss=2.485975 | Val Acc=0.3273 | Val MacroF1=0.1834 | Val CCC=0.0665
Epoch 32/50 | Train Loss=2.433561 | Val Loss=2.522312 | Val Acc=0.3273 | Val MacroF1=0.1856 | Val CCC=0.0374
Epoch 33/50 | Train Loss=2.467877 | Val Loss=2.510299 | Val Acc=0.3273 | Val MacroF1=0.1834 | Val CCC=0.0665
Epoch 34/50 | Train Loss=2.442945 | Val Loss=2.496315 | Val Acc=0.3273 | Val MacroF1=0.1834 | Val CCC=0.0665
Epoch 35/50 | Train Loss=2.453593 | Val Loss=2.527598 | Val Acc=0.3091 | Val MacroF1=0.1751 | Val CCC=0.0647
Epoch 36/50 | Train Loss=2.455079 | Val Loss=2.557630 | Val Acc=0.3273 | Val MacroF1=0.1833 | Val CCC=0.0428
Epoch 37/50 | Train Loss=2.457863 | Val Loss=2.529659 | Val Acc=0.3273 | Val MacroF1=0.1832 | Val CCC=0.0953
Epoch 38/50 | Train Loss=2.476533 | Val Loss=2.518781 | Val Acc=0.3273 | Val MacroF1=0.1833 | Val CCC=0.0428
Epoch 39/50 | Train Loss=2.467810 | Val Loss=2.522034 | Val Acc=0.3273 | Val MacroF1=0.1834 | Val CCC=0.0665
Epoch 40/50 | Train Loss=2.436542 | Val Loss=2.494801 | Val Acc=0.3273 | Val MacroF1=0.1834 | Val CCC=0.0665
Epoch 41/50 | Train Loss=2.467907 | Val Loss=2.499642 | Val Acc=0.3273 | Val MacroF1=0.1833 | Val CCC=0.0428
Epoch 42/50 | Train Loss=2.489511 | Val Loss=2.560735 | Val Acc=0.3091 | Val MacroF1=0.1751 | Val CCC=0.0647
Epoch 43/50 | Train Loss=2.461658 | Val Loss=2.504447 | Val Acc=0.3273 | Val MacroF1=0.1833 | Val CCC=0.0428
Epoch 44/50 | Train Loss=2.445353 | Val Loss=2.499332 | Val Acc=0.3091 | Val MacroF1=0.1751 | Val CCC=0.0647
Epoch 45/50 | Train Loss=2.425822 | Val Loss=2.502600 | Val Acc=0.3273 | Val MacroF1=0.1833 | Val CCC=0.0428
Epoch 46/50 | Train Loss=2.482792 | Val Loss=2.510491 | Val Acc=0.3273 | Val MacroF1=0.1834 | Val CCC=0.0665
Epoch 47/50 | Train Loss=2.449487 | Val Loss=2.485392 | Val Acc=0.3091 | Val MacroF1=0.1751 | Val CCC=0.0647
Epoch 48/50 | Train Loss=2.454126 | Val Loss=2.503296 | Val Acc=0.3273 | Val MacroF1=0.1833 | Val CCC=0.0428
Epoch 49/50 | Train Loss=2.455916 | Val Loss=2.494659 | Val Acc=0.3273 | Val MacroF1=0.1834 | Val CCC=0.0665
Epoch 50/50 | Train Loss=2.457445 | Val Loss=2.526520 | Val Acc=0.3273 | Val MacroF1=0.1833 | Val CCC=0.0428
======================================================================
Q3 Seed=1234训练结束
最佳验证Loss：2.470923，Epoch 14
最佳验证CCC：0.131100，Epoch 10
总耗时：18.49秒
Best Loss：/workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_1234/question_3/best_loss.pt
Best CCC：/workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_1234/question_3/best_ccc.pt
Last：/workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_1234/question_3/last.pt
======================================================================
Q4 Seed=1234尚未完成，开始正式训练
======================================================================
开始正式训练：Q4 PHQ_8Tired，Seed=1234
======================================================================
Epoch 01/50 | Train Loss=2.572679 | Val Loss=2.467828 | Val Acc=0.4182 | Val MacroF1=0.1474 | Val CCC=0.0000
Epoch 02/50 | Train Loss=2.526233 | Val Loss=2.427385 | Val Acc=0.4182 | Val MacroF1=0.1474 | Val CCC=0.0000
Epoch 03/50 | Train Loss=2.538406 | Val Loss=2.448365 | Val Acc=0.4182 | Val MacroF1=0.1474 | Val CCC=0.0000
Epoch 04/50 | Train Loss=2.497280 | Val Loss=2.463046 | Val Acc=0.2000 | Val MacroF1=0.1214 | Val CCC=0.0142
Epoch 05/50 | Train Loss=2.479372 | Val Loss=2.418422 | Val Acc=0.4182 | Val MacroF1=0.1474 | Val CCC=0.0000
Epoch 06/50 | Train Loss=2.511139 | Val Loss=2.557346 | Val Acc=0.4182 | Val MacroF1=0.1474 | Val CCC=0.0000
Epoch 07/50 | Train Loss=2.522887 | Val Loss=2.455588 | Val Acc=0.4182 | Val MacroF1=0.1474 | Val CCC=0.0000
Epoch 08/50 | Train Loss=2.520658 | Val Loss=2.477816 | Val Acc=0.4182 | Val MacroF1=0.2125 | Val CCC=0.1822
Epoch 09/50 | Train Loss=2.462176 | Val Loss=2.338999 | Val Acc=0.4000 | Val MacroF1=0.2033 | Val CCC=0.1755
Epoch 10/50 | Train Loss=2.525377 | Val Loss=2.417271 | Val Acc=0.3636 | Val MacroF1=0.1651 | Val CCC=-0.0006

,Question_Number,Question,Seed,Best_Loss,Best_Loss_Epoch,Best_CCC,Best_CCC_Epoch,Loaded_From_Disk,Elapsed_Seconds
0,1,PHQ_8NoInterest,1234,2.517797,18,0.246618,12,False,18.495439
1,2,PHQ_8Depressed,1234,2.278944,11,0.185385,30,False,18.469127
2,3,PHQ_8Sleep,1234,2.470923,14,0.131100,10,False,18.485166
3,4,PHQ_8Tired,1234,2.331623,31,0.190841,13,False,17.664965
4,5,PHQ_8Appetite,1234,2.221607,22,0.094828,12,False,18.170670
5,6,PHQ_8Failure,1234,2.249147,48,0.179682,35,False,17.845043
6,7,PHQ_8Concentrating,1234,2.259439,4,0.059321,20,False,17.963823
7,8,PHQ_8Moving,1234,1.764127,21,0.129527,30,False,17.929601

In [121]:
all_audio_training_results = {}
all_audio_training_results[42] = audio_seed42_results
all_audio_training_results[100] = audio_seed100_results
all_audio_training_results[1234] = audio_seed1234_results

for seed, seed_results in all_audio_training_results.items():
    print(f"Seed {seed}结果数量：", len(seed_results))
    print(f"Seed {seed} Best Loss全部存在：", all(result["best_loss_path"].exists() for result in seed_results))
    print(f"Seed {seed} Best CCC全部存在：", all(result["best_ccc_path"].exists() for result in seed_results))
    print(f"Seed {seed} Last全部存在：", all(result["last_path"].exists() for result in seed_results))

Seed 42结果数量： 8
Seed 42 Best Loss全部存在： True
Seed 42 Best CCC全部存在： True
Seed 42 Last全部存在： True
Seed 100结果数量： 8
Seed 100 Best Loss全部存在： True
Seed 100 Best CCC全部存在： True
Seed 100 Last全部存在： True
Seed 1234结果数量： 8
Seed 1234 Best Loss全部存在： True
Seed 1234 Best CCC全部存在： True
Seed 1234 Last全部存在： True

In [122]:
audio_seed100_test_result = evaluate_audio_seed_on_test(seed=100, seed_results=audio_seed100_results, test_loader=test_audio_loader)
audio_seed1234_test_result = evaluate_audio_seed_on_test(seed=1234, seed_results=audio_seed1234_results, test_loader=test_audio_loader)

已加载Checkpoint： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_100/question_1/best_ccc.pt
Checkpoint类型： best_ccc
保存Epoch： 43
题目： PHQ_8NoInterest
Seed： 100
缺少参数： []
多余参数： []
Seed 100，Q1/8测试完成
已加载Checkpoint： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_100/question_2/best_ccc.pt
Checkpoint类型： best_ccc
保存Epoch： 17
题目： PHQ_8Depressed
Seed： 100
缺少参数： []
多余参数： []
Seed 100，Q2/8测试完成
已加载Checkpoint： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_100/question_3/best_ccc.pt
Checkpoint类型： best_ccc
保存Epoch： 13
题目： PHQ_8Sleep
Seed： 100
缺少参数： []
多余参数： []
Seed 100，Q3/8测试完成
已加载Checkpoint： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_100/question_4/best_ccc.pt
Checkpoint类型： best_ccc
保存Epoch： 21
题目： PHQ_8Tired
Seed： 100
缺少参数： []
多余参数： []
Seed 100，Q4/8测试完成
已加载Checkpoint： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_100/question_5/best_ccc.pt
Checkpoint类型： best_ccc
保存Epoch： 13
题目： PHQ_8Appetite
Seed： 100
缺少参数： []
多余参数： []
Seed 100，Q5/8测试完成
已加载Checkpoint： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_100/question_6/best_ccc.pt
Checkpoint类型： best_ccc
保存Epoch： 23
题目： PHQ_8Failure
Seed： 100
缺少参数： []
多余参数： []
Seed 100，Q6/8测试完成
已加载Checkpoint： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_100/question_7/best_ccc.pt
Checkpoint类型： best_ccc
保存Epoch： 39
题目： PHQ_8Concentrating
Seed： 100
缺少参数： []
多余参数： []
Seed 100，Q7/8测试完成
已加载Checkpoint： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_100/question_8/best_ccc.pt
Checkpoint类型： best_ccc
保存Epoch： 20
题目： PHQ_8Moving
Seed： 100
缺少参数： []
多余参数： []
Seed 100，Q8/8测试完成

======================================================================
Audio-only Seed 100独立测试结果
======================================================================
测试参与者数量：56
CCC：0.237006
RMSE：6.495878
MAE：5.267857
完全相等比例：0.035714
预测总分范围：4～15
真实总分范围：0～22
预测文件：/workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_100_test_predictions_56.csv
已加载Checkpoint： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_1234/question_1/best_ccc.pt
Checkpoint类型： best_ccc
保存Epoch： 12
题目： PHQ_8NoInterest
Seed： 1234
缺少参数： []
多余参数： []
Seed 1234，Q1/8测试完成
已加载Checkpoint： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_1234/question_2/best_ccc.pt
Checkpoint类型： best_ccc
保存Epoch： 30
题目： PHQ_8Depressed
Seed： 1234
缺少参数： []
多余参数： []
Seed 1234，Q2/8测试完成
已加载Checkpoint： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_1234/question_3/best_ccc.pt
Checkpoint类型： best_ccc
保存Epoch： 10
题目： PHQ_8Sleep
Seed： 1234
缺少参数： []
多余参数： []
Seed 1234，Q3/8测试完成
已加载Checkpoint： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_1234/question_4/best_ccc.pt
Checkpoint类型： best_ccc
保存Epoch： 13
题目： PHQ_8Tired
Seed： 1234
缺少参数： []
多余参数： []
Seed 1234，Q4/8测试完成
已加载Checkpoint： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_1234/question_5/best_ccc.pt
Checkpoint类型： best_ccc
保存Epoch： 12
题目： PHQ_8Appetite
Seed： 1234
缺少参数： []
多余参数： []
Seed 1234，Q5/8测试完成
已加载Checkpoint： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_1234/question_6/best_ccc.pt
Checkpoint类型： best_ccc
保存Epoch： 35
题目： PHQ_8Failure
Seed： 1234
缺少参数： []
多余参数： []
Seed 1234，Q6/8测试完成
已加载Checkpoint： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_1234/question_7/best_ccc.pt
Checkpoint类型： best_ccc
保存Epoch： 20
题目： PHQ_8Concentrating
Seed： 1234
缺少参数： []
多余参数： []
Seed 1234，Q7/8测试完成
已加载Checkpoint： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_1234/question_8/best_ccc.pt
Checkpoint类型： best_ccc
保存Epoch： 30
题目： PHQ_8Moving
Seed： 1234
缺少参数： []
多余参数： []
Seed 1234，Q8/8测试完成

======================================================================
Audio-only Seed 1234独立测试结果
======================================================================
测试参与者数量：56
CCC：0.268115
RMSE：7.418606
MAE：5.607143
完全相等比例：0.160714
预测总分范围：1～16
真实总分范围：0～22
预测文件：/workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_1234_test_predictions_56.csv

In [123]:
all_audio_test_results = [audio_seed42_test_result, audio_seed100_test_result, audio_seed1234_test_result]
audio_test_seed_rows = []

for result in all_audio_test_results:
    row = {}
    row["Seed"] = result["seed"]
    row["Sample_Count"] = result["sample_count"]
    row["CCC"] = result["ccc"]
    row["RMSE"] = result["rmse"]
    row["MAE"] = result["mae"]
    row["Exact_Accuracy"] = result["exact_accuracy"]
    audio_test_seed_rows.append(row)

audio_test_seed_summary_df = pd.DataFrame(audio_test_seed_rows)
display(audio_test_seed_summary_df)

   Seed  Sample_Count       CCC      RMSE       MAE  Exact_Accuracy
0    42            56  0.275914  7.463004  5.839286        0.053571
1   100            56  0.237006  6.495878  5.267857        0.035714
2  1234            56  0.268115  7.418606  5.607143        0.160714

In [124]:
audio_three_seed_rows = []

for metric_name in ["CCC", "RMSE", "MAE", "Exact_Accuracy"]:
    row = {}
    row["Metric"] = metric_name
    row["Mean"] = audio_test_seed_summary_df[metric_name].mean()
    row["Std"] = audio_test_seed_summary_df[metric_name].std(ddof=1)
    audio_three_seed_rows.append(row)

audio_three_seed_summary_df = pd.DataFrame(audio_three_seed_rows)
display(audio_three_seed_summary_df)

           Metric      Mean       Std
0             CCC  0.260345  0.020585
1            RMSE  7.125829  0.546005
2             MAE  5.571429  0.287384
3  Exact_Accuracy  0.083333  0.067606

论文：ccc   0.273+- 0.021
rmse   6.67+-  0.11

MAE    5.32 +- 0.05

In [125]:
audio_test_seed_summary_path = CHECKPOINT_ROOT / "three_seed_test_results_56.csv"
audio_three_seed_summary_path = CHECKPOINT_ROOT / "three_seed_test_summary_56.csv"

audio_test_seed_summary_df.to_csv(audio_test_seed_summary_path, index=False)
audio_three_seed_summary_df.to_csv(audio_three_seed_summary_path, index=False)

print("逐Seed测试结果：", audio_test_seed_summary_path)
print("三Seed均值与标准差：", audio_three_seed_summary_path)
print("逐Seed文件存在：", audio_test_seed_summary_path.exists())
print("三Seed汇总文件存在：", audio_three_seed_summary_path.exists())

逐Seed测试结果： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/three_seed_test_results_56.csv
三Seed均值与标准差： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/three_seed_test_summary_56.csv
逐Seed文件存在： True
三Seed汇总文件存在： True

In [126]:
from pathlib import Path
import random
import sys
import time
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader

DATA_DIR = Path("/workspace/E-DAIC/original_data")
SPLIT_DIR = Path("/workspace/E-DAIC/splits")
LABEL_DIR = Path("/workspace/E-DAIC/others")

TRAIN_SPLIT_PATH = SPLIT_DIR / "train_split.csv"
VAL_SPLIT_PATH = SPLIT_DIR / "dev_split.csv"
TEST_SPLIT_PATH = SPLIT_DIR / "test_split.csv"
DETAILED_LABEL_PATH = LABEL_DIR / "Detailed_PHQ8_Labels.csv"

TEXT_CACHE_ROOT = Path("/workspace/E-DAIC/cache/phq8_text_embeddings")
AUDIO_CACHE_DIR = Path("/workspace/E-DAIC/cache/phq8_audio_egemaps/egemaps23_turnmean_100hz_turns120_v1")

TEXT_CHECKPOINT_ROOT = Path("/workspace/E-DAIC/checkpoints/phq8_text_paperlike")
AUDIO_CHECKPOINT_ROOT = Path("/workspace/E-DAIC/checkpoints/phq8_audio_paperlike")
FUSION_CHECKPOINT_ROOT = Path("/workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike")

PHQ8_QUESTION_COLUMNS = ["PHQ_8NoInterest", "PHQ_8Depressed", "PHQ_8Sleep", "PHQ_8Tired", "PHQ_8Appetite", "PHQ_8Failure", "PHQ_8Concentrating", "PHQ_8Moving"]

MAX_TURNS = 120
TEXT_FEATURE_DIM = 768
AUDIO_FEATURE_DIM = 23
ENCODER_OUTPUT_DIM = 100
NUM_CLASSES = 4
ATTENTION_HEADS = 4

BATCH_SIZE = 10
NUM_EPOCHS = 20
LEARNING_RATE = 5e-4
ADAM_EPSILON = 1e-8
WEIGHT_DECAY = 1e-3
MAX_GRAD_NORM = 1.0

FUSION_DROPOUT = 0.8
MLP_FIRST_DROPOUT = 0.8
MLP_LAST_DROPOUT = 0.5

ALPHA = 1.0
BETA = 0.5
LOSS_EPSILON = 1e-12
SEEDS = [42, 100, 1234]

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
FUSION_CHECKPOINT_ROOT.mkdir(parents=True, exist_ok=True)

print("Python：", sys.version.split()[0])
print("PyTorch：", torch.__version__)
print("计算设备：", device)
print("Text缓存目录存在：", TEXT_CACHE_ROOT.exists())
print("Audio缓存目录存在：", AUDIO_CACHE_DIR.exists())
print("Text Checkpoint目录存在：", TEXT_CHECKPOINT_ROOT.exists())
print("Audio Checkpoint目录存在：", AUDIO_CHECKPOINT_ROOT.exists())
print("Fusion Checkpoint目录：", FUSION_CHECKPOINT_ROOT)
print("融合训练轮数：", NUM_EPOCHS)
print("融合Attention Dropout：", FUSION_DROPOUT)

Python： 3.12.3
PyTorch： 2.9.0
计算设备： cuda:0
Text缓存目录存在： True
Audio缓存目录存在： True
Text Checkpoint目录存在： True
Audio Checkpoint目录存在： True
Fusion Checkpoint目录： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike
融合训练轮数： 20
融合Attention Dropout： 0.8

In [141]:
text_cache_candidates = sorted(TEXT_CACHE_ROOT.rglob("302.pt"))
audio_cache_path_302 = AUDIO_CACHE_DIR / "302.pt"
text_best_loss_path = TEXT_CHECKPOINT_ROOT /"q1_PHQ_8NoInterest"/ "seed_42"/ "best_loss.pt"
audio_best_loss_path = AUDIO_CHECKPOINT_ROOT / "seed_42" / "question_1" / "best_loss.pt"

print("找到的302文本缓存：", text_cache_candidates)
print("302语音缓存存在：", audio_cache_path_302.exists())
print("Q1文本Best Loss存在：", text_best_loss_path.exists())
print("Q1语音Best Loss存在：", audio_best_loss_path.exists())

if len(text_cache_candidates) != 1:
    raise RuntimeError(f"预期找到一个302文本缓存，实际找到{len(text_cache_candidates)}个")

TEXT_CACHE_DIR = text_cache_candidates[0].parent

text_cache_302 = torch.load(text_cache_candidates[0], map_location="cpu", weights_only=False)
audio_cache_302 = torch.load(audio_cache_path_302, map_location="cpu", weights_only=False)
text_checkpoint_302 = torch.load(text_best_loss_path, map_location="cpu", weights_only=False)
audio_checkpoint_302 = torch.load(audio_best_loss_path, map_location="cpu", weights_only=False)

print("正式Text缓存目录：", TEXT_CACHE_DIR)
print("Text缓存字段：", list(text_cache_302.keys()))
print("Audio缓存字段：", list(audio_cache_302.keys()))
print("Text Checkpoint字段：", list(text_checkpoint_302.keys()))
print("Audio Checkpoint字段：", list(audio_checkpoint_302.keys()))
print("Text模型前10个参数名：", list(text_checkpoint_302["model_state_dict"].keys())[:10])
print("Audio模型前10个参数名：", list(audio_checkpoint_302["model_state_dict"].keys())[:10])

找到的302文本缓存： [PosixPath('/workspace/E-DAIC/cache/phq8_text_embeddings/distilroberta_842eaed4_turns120_v1/302.pt')]
302语音缓存存在： True
Q1文本Best Loss存在： True
Q1语音Best Loss存在： True
正式Text缓存目录： /workspace/E-DAIC/cache/phq8_text_embeddings/distilroberta_842eaed4_turns120_v1
Text缓存字段： ['participant_id', 'model_name', 'model_revision', 'max_turns', 'embedding_dim', 'source_size', 'source_mtime_ns', 'real_turn_count', 'embeddings', 'key_padding_mask']
Audio缓存字段： ['participant_id', 'cache_version', 'feature_rate', 'feature_dim', 'max_turns', 'original_transcript_turns', 'cleaned_turns', 'real_turn_count', 'audio_duration_seconds', 'wav_signature', 'transcript_signature', 'egemaps_signature', 'audio_features', 'padding_mask']
Text Checkpoint字段： ['checkpoint_type', 'epoch', 'question_index', 'question_number', 'question_name', 'seed', 'model_state_dict', 'train_metrics', 'val_metrics', 'class_counts', 'class_weights', 'best_val_loss', 'best_val_ccc', 'best_loss_epoch', 'best_ccc_epoch', 'model_name', 'model_revision', 'max_turns', 'embedding_dim', 'lstm_hidden_size', 'num_attention_heads', 'num_classes', 'batch_size', 'num_epochs', 'learning_rate', 'optimizer_eps', 'weight_decay', 'max_grad_norm', 'alpha', 'beta']
Audio Checkpoint字段： ['checkpoint_type', 'epoch', 'question_index', 'question_number', 'question', 'seed', 'model_state_dict', 'optimizer_state_dict', 'train_metrics', 'val_metrics', 'class_counts', 'class_weights', 'best_val_loss', 'best_val_ccc', 'best_loss_epoch', 'best_ccc_epoch', 'config']
Text模型前10个参数名： ['lstm.weight_ih_l0', 'lstm.weight_hh_l0', 'lstm.bias_ih_l0', 'lstm.bias_hh_l0', 'lstm.weight_ih_l0_reverse', 'lstm.weight_hh_l0_reverse', 'lstm.bias_ih_l0_reverse', 'lstm.bias_hh_l0_reverse', 'attention.in_proj_weight', 'attention.in_proj_bias']
Audio模型前10个参数名： ['lstm.weight_ih_l0', 'lstm.weight_hh_l0', 'lstm.bias_ih_l0', 'lstm.bias_hh_l0', 'lstm.weight_ih_l0_reverse', 'lstm.weight_hh_l0_reverse', 'lstm.bias_ih_l0_reverse', 'lstm.bias_hh_l0_reverse', 'attention1.in_proj_weight', 'attention1.in_proj_bias']

In [142]:
def find_checkpoint_by_metadata(checkpoint_root, expected_seed, expected_question_index, expected_checkpoint_type):
    matched_paths = []
    candidate_paths = sorted(checkpoint_root.rglob("*.pt"))

    for checkpoint_path in candidate_paths:
        try:
            checkpoint = torch.load(checkpoint_path, map_location="cpu", weights_only=False)
        except Exception:
            continue

        if not isinstance(checkpoint, dict):
            continue

        checkpoint_seed = checkpoint.get("seed")
        checkpoint_question_index = checkpoint.get("question_index")
        checkpoint_type = checkpoint.get("checkpoint_type")

        if checkpoint_seed == expected_seed and checkpoint_question_index == expected_question_index and checkpoint_type == expected_checkpoint_type:
            matched_paths.append(checkpoint_path)

        del checkpoint

    if len(matched_paths) == 0:
        raise FileNotFoundError(f"没有找到Seed={expected_seed}、question_index={expected_question_index}、类型={expected_checkpoint_type}的Checkpoint，搜索目录：{checkpoint_root}")

    if len(matched_paths) > 1:
        print("找到多个符合条件的Checkpoint：")

        for matched_path in matched_paths:
            print(" ", matched_path)

        raise RuntimeError("符合条件的Checkpoint不唯一，需要先确认使用哪一个")

    return matched_paths[0]

In [129]:
text_best_loss_path = find_checkpoint_by_metadata(TEXT_CHECKPOINT_ROOT, expected_seed=42, expected_question_index=0, expected_checkpoint_type="best_loss")
audio_best_loss_path = find_checkpoint_by_metadata(AUDIO_CHECKPOINT_ROOT, expected_seed=42, expected_question_index=0, expected_checkpoint_type="best_loss")

print("Q1文本Best Loss：", text_best_loss_path)
print("Q1语音Best Loss：", audio_best_loss_path)
print("Q1文本Best Loss存在：", text_best_loss_path.exists())
print("Q1语音Best Loss存在：", audio_best_loss_path.exists())

Q1文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q1_PHQ_8NoInterest/seed_42/best_loss.pt
Q1语音Best Loss： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_42/question_1/best_loss.pt
Q1文本Best Loss存在： True
Q1语音Best Loss存在： True

In [130]:
text_cache_candidates = sorted(TEXT_CACHE_ROOT.rglob("302.pt"))
audio_cache_path_302 = AUDIO_CACHE_DIR / "302.pt"

print("找到的302文本缓存：", text_cache_candidates)
print("302语音缓存存在：", audio_cache_path_302.exists())

if len(text_cache_candidates) != 1:
    raise RuntimeError(f"预期找到一个302文本缓存，实际找到{len(text_cache_candidates)}个：{text_cache_candidates}")

TEXT_CACHE_DIR = text_cache_candidates[0].parent

text_cache_302 = torch.load(text_cache_candidates[0], map_location="cpu", weights_only=False)
audio_cache_302 = torch.load(audio_cache_path_302, map_location="cpu", weights_only=False)
text_checkpoint_302 = torch.load(text_best_loss_path, map_location="cpu", weights_only=False)
audio_checkpoint_302 = torch.load(audio_best_loss_path, map_location="cpu", weights_only=False)

print("正式Text缓存目录：", TEXT_CACHE_DIR)
print("Text缓存字段：", list(text_cache_302.keys()))
print("Audio缓存字段：", list(audio_cache_302.keys()))
print("Text Checkpoint字段：", list(text_checkpoint_302.keys()))
print("Audio Checkpoint字段：", list(audio_checkpoint_302.keys()))
print("Text模型前10个参数名：", list(text_checkpoint_302["model_state_dict"].keys())[:10])
print("Audio模型前10个参数名：", list(audio_checkpoint_302["model_state_dict"].keys())[:10])

找到的302文本缓存： [PosixPath('/workspace/E-DAIC/cache/phq8_text_embeddings/distilroberta_842eaed4_turns120_v1/302.pt')]
302语音缓存存在： True
正式Text缓存目录： /workspace/E-DAIC/cache/phq8_text_embeddings/distilroberta_842eaed4_turns120_v1
Text缓存字段： ['participant_id', 'model_name', 'model_revision', 'max_turns', 'embedding_dim', 'source_size', 'source_mtime_ns', 'real_turn_count', 'embeddings', 'key_padding_mask']
Audio缓存字段： ['participant_id', 'cache_version', 'feature_rate', 'feature_dim', 'max_turns', 'original_transcript_turns', 'cleaned_turns', 'real_turn_count', 'audio_duration_seconds', 'wav_signature', 'transcript_signature', 'egemaps_signature', 'audio_features', 'padding_mask']
Text Checkpoint字段： ['checkpoint_type', 'epoch', 'question_index', 'question_number', 'question_name', 'seed', 'model_state_dict', 'train_metrics', 'val_metrics', 'class_counts', 'class_weights', 'best_val_loss', 'best_val_ccc', 'best_loss_epoch', 'best_ccc_epoch', 'model_name', 'model_revision', 'max_turns', 'embedding_dim', 'lstm_hidden_size', 'num_attention_heads', 'num_classes', 'batch_size', 'num_epochs', 'learning_rate', 'optimizer_eps', 'weight_decay', 'max_grad_norm', 'alpha', 'beta']
Audio Checkpoint字段： ['checkpoint_type', 'epoch', 'question_index', 'question_number', 'question', 'seed', 'model_state_dict', 'optimizer_state_dict', 'train_metrics', 'val_metrics', 'class_counts', 'class_weights', 'best_val_loss', 'best_val_ccc', 'best_loss_epoch', 'best_ccc_epoch', 'config']
Text模型前10个参数名： ['lstm.weight_ih_l0', 'lstm.weight_hh_l0', 'lstm.bias_ih_l0', 'lstm.bias_hh_l0', 'lstm.weight_ih_l0_reverse', 'lstm.weight_hh_l0_reverse', 'lstm.bias_ih_l0_reverse', 'lstm.bias_hh_l0_reverse', 'attention.in_proj_weight', 'attention.in_proj_bias']
Audio模型前10个参数名： ['lstm.weight_ih_l0', 'lstm.weight_hh_l0', 'lstm.bias_ih_l0', 'lstm.bias_hh_l0', 'lstm.weight_ih_l0_reverse', 'lstm.weight_hh_l0_reverse', 'lstm.bias_ih_l0_reverse', 'lstm.bias_hh_l0_reverse', 'attention1.in_proj_weight', 'attention1.in_proj_bias']

In [143]:
train_split_df = pd.read_csv(TRAIN_SPLIT_PATH)
val_split_df = pd.read_csv(VAL_SPLIT_PATH)
test_split_df = pd.read_csv(TEST_SPLIT_PATH)
detailed_label_df = pd.read_csv(DETAILED_LABEL_PATH)

train_metadata_df = train_split_df.merge(detailed_label_df[["Participant_ID"] + PHQ8_QUESTION_COLUMNS], on="Participant_ID", how="left", validate="one_to_one")
val_metadata_df = val_split_df.merge(detailed_label_df[["Participant_ID"] + PHQ8_QUESTION_COLUMNS], on="Participant_ID", how="left", validate="one_to_one")
test_metadata_df = test_split_df.copy()

if train_metadata_df[PHQ8_QUESTION_COLUMNS].isna().any().any():
    raise ValueError("训练集存在缺失的8道题标签")

if val_metadata_df[PHQ8_QUESTION_COLUMNS].isna().any().any():
    raise ValueError("验证集存在缺失的8道题标签")

print("训练样本数：", len(train_metadata_df))
print("验证样本数：", len(val_metadata_df))
print("测试样本数：", len(test_metadata_df))
print("训练题目标签形状：", train_metadata_df[PHQ8_QUESTION_COLUMNS].shape)
print("验证题目标签形状：", val_metadata_df[PHQ8_QUESTION_COLUMNS].shape)

训练样本数： 163
验证样本数： 55
测试样本数： 56
训练题目标签形状： (163, 8)
验证题目标签形状： (55, 8)

In [144]:
def load_text_audio_cache(participant_id):
    participant_id = int(participant_id)
    text_cache_path = TEXT_CACHE_DIR / f"{participant_id}.pt"
    audio_cache_path = AUDIO_CACHE_DIR / f"{participant_id}.pt"

    if not text_cache_path.exists():
        raise FileNotFoundError(f"文本缓存不存在：{text_cache_path}")

    if not audio_cache_path.exists():
        raise FileNotFoundError(f"语音缓存不存在：{audio_cache_path}")

    text_cache = torch.load(text_cache_path, map_location="cpu", weights_only=False)
    audio_cache = torch.load(audio_cache_path, map_location="cpu", weights_only=False)

    if int(text_cache["participant_id"]) != participant_id:
        raise RuntimeError(f"文本缓存参与者编号错误：{participant_id}")

    if int(audio_cache["participant_id"]) != participant_id:
        raise RuntimeError(f"语音缓存参与者编号错误：{participant_id}")

    text_features = text_cache["embeddings"].float()
    text_padding_mask = text_cache["key_padding_mask"].bool()
    audio_features = audio_cache["audio_features"].float()
    audio_padding_mask = audio_cache["padding_mask"].bool()

    if text_features.shape != (MAX_TURNS, TEXT_FEATURE_DIM):
        raise RuntimeError(f"参与者{participant_id}文本形状错误：{text_features.shape}")

    if text_padding_mask.shape != (MAX_TURNS,):
        raise RuntimeError(f"参与者{participant_id}文本Mask形状错误：{text_padding_mask.shape}")

    if audio_features.shape != (MAX_TURNS, AUDIO_FEATURE_DIM):
        raise RuntimeError(f"参与者{participant_id}语音形状错误：{audio_features.shape}")

    if audio_padding_mask.shape != (MAX_TURNS,):
        raise RuntimeError(f"参与者{participant_id}语音Mask形状错误：{audio_padding_mask.shape}")

    if not torch.isfinite(text_features).all():
        raise RuntimeError(f"参与者{participant_id}文本特征包含NaN或Inf")

    if not torch.isfinite(audio_features).all():
        raise RuntimeError(f"参与者{participant_id}语音特征包含NaN或Inf")

    return text_features, text_padding_mask, audio_features, audio_padding_mask

In [145]:
class TextAudioPHQ8Dataset(Dataset):
    def __init__(self, metadata_df, split_name):
        super().__init__()

        if split_name not in {"train", "val"}:
            raise ValueError("split_name只能是train或val")

        self.split_name = split_name
        self.metadata_df = metadata_df.reset_index(drop=True).copy()
        self.participant_ids = self.metadata_df["Participant_ID"].astype(int).tolist()
        self.labels = torch.tensor(self.metadata_df[PHQ8_QUESTION_COLUMNS].to_numpy(), dtype=torch.long)
        text_feature_list = []
        text_mask_list = []
        audio_feature_list = []
        audio_mask_list = []

        for index, participant_id in enumerate(self.participant_ids):
            text_features, text_mask, audio_features, audio_mask = load_text_audio_cache(participant_id)
            text_feature_list.append(text_features)
            text_mask_list.append(text_mask)
            audio_feature_list.append(audio_features)
            audio_mask_list.append(audio_mask)

            if (index + 1) % 50 == 0 or index + 1 == len(self.participant_ids):
                print(f"{split_name}融合缓存加载进度：{index + 1}/{len(self.participant_ids)}")

        self.text_features = torch.stack(text_feature_list, dim=0)
        self.text_masks = torch.stack(text_mask_list, dim=0)
        self.audio_features = torch.stack(audio_feature_list, dim=0)
        self.audio_masks = torch.stack(audio_mask_list, dim=0)

        if self.text_features.shape != (len(self), MAX_TURNS, TEXT_FEATURE_DIM):
            raise RuntimeError(f"{split_name}文本整体形状错误：{self.text_features.shape}")

        if self.audio_features.shape != (len(self), MAX_TURNS, AUDIO_FEATURE_DIM):
            raise RuntimeError(f"{split_name}语音整体形状错误：{self.audio_features.shape}")

        if self.text_masks.shape != (len(self), MAX_TURNS):
            raise RuntimeError(f"{split_name}文本Mask形状错误：{self.text_masks.shape}")

        if self.audio_masks.shape != (len(self), MAX_TURNS):
            raise RuntimeError(f"{split_name}语音Mask形状错误：{self.audio_masks.shape}")

    def __len__(self):
        return len(self.participant_ids)

    def __getitem__(self, index):
        text_features = self.text_features[index]
        text_mask = self.text_masks[index]
        audio_features = self.audio_features[index]
        audio_mask = self.audio_masks[index]
        labels = self.labels[index]
        return text_features, text_mask, audio_features, audio_mask, labels

In [146]:
train_fusion_dataset = TextAudioPHQ8Dataset(train_metadata_df, split_name="train")
val_fusion_dataset = TextAudioPHQ8Dataset(val_metadata_df, split_name="val")

train融合缓存加载进度：50/163
train融合缓存加载进度：100/163
train融合缓存加载进度：150/163
train融合缓存加载进度：163/163
val融合缓存加载进度：50/55
val融合缓存加载进度：55/55

In [147]:
def create_fusion_dataloaders(seed):
    train_generator = torch.Generator()
    train_generator.manual_seed(seed)
    train_loader = DataLoader(train_fusion_dataset, batch_size=BATCH_SIZE, shuffle=True, num_workers=0, drop_last=False, generator=train_generator)
    val_loader = DataLoader(val_fusion_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=0, drop_last=False)
    return train_loader, val_loader

In [148]:
train_fusion_loader, val_fusion_loader = create_fusion_dataloaders(seed=42)
batch_text_features, batch_text_masks, batch_audio_features, batch_audio_masks, batch_all_labels = next(iter(train_fusion_loader))

print("训练样本数：", len(train_fusion_dataset))
print("验证样本数：", len(val_fusion_dataset))
print("训练批次数：", len(train_fusion_loader))
print("验证批次数：", len(val_fusion_loader))
print("Batch文本特征：", batch_text_features.shape)
print("Batch文本Mask：", batch_text_masks.shape)
print("Batch语音特征：", batch_audio_features.shape)
print("Batch语音Mask：", batch_audio_masks.shape)
print("Batch全部标签：", batch_all_labels.shape)
print("当前Batch Q1标签：", batch_all_labels[:, 0])

训练样本数： 163
验证样本数： 55
训练批次数： 17
验证批次数： 6
Batch文本特征： torch.Size([10, 120, 768])
Batch文本Mask： torch.Size([10, 120])
Batch语音特征： torch.Size([10, 120, 23])
Batch语音Mask： torch.Size([10, 120])
Batch全部标签： torch.Size([10, 8])
当前Batch Q1标签： tensor([1, 0, 1, 0, 0, 0, 0, 0, 0, 1])

In [149]:
class PretrainedTextEncoder(nn.Module):
    def __init__(self):
        super().__init__()
        self.lstm = nn.LSTM(input_size=TEXT_FEATURE_DIM, hidden_size=50, batch_first=True, bidirectional=True)
        self.attention = nn.MultiheadAttention(embed_dim=ENCODER_OUTPUT_DIM, num_heads=ATTENTION_HEADS, dropout=0.5, batch_first=True)

    def forward(self, text_features, text_padding_mask):
        lstm_output, _ = self.lstm(text_features)
        text_encoding, _ = self.attention(lstm_output, lstm_output, lstm_output, key_padding_mask=text_padding_mask, need_weights=False)
        return text_encoding


class PretrainedAudioEncoder(nn.Module):
    def __init__(self):
        super().__init__()
        self.lstm = nn.LSTM(input_size=AUDIO_FEATURE_DIM, hidden_size=50, batch_first=True, bidirectional=True)
        self.attention1 = nn.MultiheadAttention(embed_dim=ENCODER_OUTPUT_DIM, num_heads=ATTENTION_HEADS, dropout=0.2, batch_first=True)
        self.attention2 = nn.MultiheadAttention(embed_dim=ENCODER_OUTPUT_DIM, num_heads=ATTENTION_HEADS, dropout=0.2, batch_first=True)

    def forward(self, audio_features, audio_padding_mask):
        lstm_output, _ = self.lstm(audio_features)
        attention1_output, _ = self.attention1(lstm_output, lstm_output, lstm_output, key_padding_mask=audio_padding_mask, need_weights=False)
        audio_encoding, _ = self.attention2(attention1_output, attention1_output, attention1_output, key_padding_mask=audio_padding_mask, need_weights=False)
        return audio_encoding

In [150]:
def extract_state_dict_by_prefixes(full_state_dict, prefixes):
    selected_state_dict = {}

    for parameter_name, parameter_value in full_state_dict.items():
        if any(parameter_name.startswith(prefix) for prefix in prefixes):
            selected_state_dict[parameter_name] = parameter_value

    return selected_state_dict

In [272]:
# def load_pretrained_text_audio_encoders(question_index, seed):
#     text_checkpoint_path = find_checkpoint_by_metadata(TEXT_CHECKPOINT_ROOT, expected_seed=seed, expected_question_index=question_index, expected_checkpoint_type="best_loss")
#     audio_checkpoint_path = find_checkpoint_by_metadata(AUDIO_CHECKPOINT_ROOT, expected_seed=seed, expected_question_index=question_index, expected_checkpoint_type="best_loss")
#     text_checkpoint = torch.load(text_checkpoint_path, map_location="cpu", weights_only=False)
#     audio_checkpoint = torch.load(audio_checkpoint_path, map_location="cpu", weights_only=False)
def load_pretrained_text_audio_encoders(question_index, seed, checkpoint_type="best_loss"):
    text_checkpoint_path = find_checkpoint_by_metadata(TEXT_CHECKPOINT_ROOT, expected_seed=seed, expected_question_index=question_index, expected_checkpoint_type=checkpoint_type)
    audio_checkpoint_path = find_checkpoint_by_metadata(AUDIO_CHECKPOINT_ROOT, expected_seed=seed, expected_question_index=question_index, expected_checkpoint_type=checkpoint_type)
    text_checkpoint = torch.load(text_checkpoint_path, map_location="cpu", weights_only=False)
    audio_checkpoint = torch.load(audio_checkpoint_path, map_location="cpu", weights_only=False)
    text_encoder = PretrainedTextEncoder()
    audio_encoder = PretrainedAudioEncoder()
    text_encoder_state = extract_state_dict_by_prefixes(text_checkpoint["model_state_dict"], prefixes=("lstm.", "attention."))
    audio_encoder_state = extract_state_dict_by_prefixes(audio_checkpoint["model_state_dict"], prefixes=("lstm.", "attention1.", "attention2."))
    text_load_result = text_encoder.load_state_dict(text_encoder_state, strict=True)
    audio_load_result = audio_encoder.load_state_dict(audio_encoder_state, strict=True)

    print("文本Best Loss：", text_checkpoint_path)
    print("语音Best Loss：", audio_checkpoint_path)
    print("文本保存Epoch：", text_checkpoint["epoch"])
    print("语音保存Epoch：", audio_checkpoint["epoch"])
    print("文本缺少参数：", text_load_result.missing_keys)
    print("文本多余参数：", text_load_result.unexpected_keys)
    print("语音缺少参数：", audio_load_result.missing_keys)
    print("语音多余参数：", audio_load_result.unexpected_keys)

    return text_encoder, audio_encoder, text_checkpoint, audio_checkpoint, text_checkpoint_path, audio_checkpoint_path

In [154]:
class TextAudioQuestMF(nn.Module):
    def __init__(self, text_encoder, audio_encoder):
        super().__init__()
        self.text_encoder = text_encoder
        self.audio_encoder = audio_encoder
        self.audio_to_text_cross_attention = nn.MultiheadAttention(embed_dim=ENCODER_OUTPUT_DIM, num_heads=ATTENTION_HEADS, dropout=FUSION_DROPOUT, batch_first=True)
        self.text_to_audio_cross_attention = nn.MultiheadAttention(embed_dim=ENCODER_OUTPUT_DIM, num_heads=ATTENTION_HEADS, dropout=FUSION_DROPOUT, batch_first=True)
        self.text_self_attention = nn.MultiheadAttention(embed_dim=ENCODER_OUTPUT_DIM, num_heads=ATTENTION_HEADS, dropout=FUSION_DROPOUT, batch_first=True)
        self.audio_self_attention = nn.MultiheadAttention(embed_dim=ENCODER_OUTPUT_DIM, num_heads=ATTENTION_HEADS, dropout=FUSION_DROPOUT, batch_first=True)
        self.mlp = nn.Sequential(nn.Flatten(), nn.Dropout(MLP_FIRST_DROPOUT), nn.Linear(MAX_TURNS * ENCODER_OUTPUT_DIM * 2, 256), nn.ReLU(), nn.Dropout(MLP_LAST_DROPOUT), nn.Linear(256, NUM_CLASSES))

        for parameter in self.text_encoder.parameters():
            parameter.requires_grad = False

        self.text_encoder.eval()

    def train(self, mode=True):
        super().train(mode)
        self.text_encoder.eval()
        return self

    def forward(self, text_features, text_padding_mask, audio_features, audio_padding_mask, return_intermediates=False):
        text_encoding = self.text_encoder(text_features, text_padding_mask)
        audio_encoding = self.audio_encoder(audio_features, audio_padding_mask)
        text_encoding=text_encoding.masked_fill(text_padding_mask.unsqueeze(-1),0.0)
        audio_encoding=audio_encoding.masked_fill(audio_padding_mask.unsqueeze(-1),0.0)
        audio_to_text, _ = self.audio_to_text_cross_attention(text_encoding, audio_encoding, audio_encoding, key_padding_mask=audio_padding_mask, need_weights=False)
        text_to_audio, _ = self.text_to_audio_cross_attention(audio_encoding, text_encoding, text_encoding, key_padding_mask=text_padding_mask, need_weights=False)
        text_fused_encoding, _ = self.text_self_attention(audio_to_text, audio_to_text, audio_to_text, key_padding_mask=text_padding_mask, need_weights=False)
        audio_fused_encoding, _ = self.audio_self_attention(text_to_audio, text_to_audio, text_to_audio, key_padding_mask=audio_padding_mask, need_weights=False)
        fused_encoding = torch.cat((text_fused_encoding, audio_fused_encoding), dim=2)
        logits = self.mlp(fused_encoding)

        if return_intermediates:
            intermediates = {}
            intermediates["text_encoding"] = text_encoding
            intermediates["audio_encoding"] = audio_encoding
            intermediates["audio_to_text"] = audio_to_text
            intermediates["text_to_audio"] = text_to_audio
            intermediates["text_fused_encoding"] = text_fused_encoding
            intermediates["audio_fused_encoding"] = audio_fused_encoding
            intermediates["fused_encoding"] = fused_encoding
            return logits, intermediates

        return logits

In [155]:
set_seed(42)

(
    q1_text_encoder,
    q1_audio_encoder,
    q1_text_checkpoint,
    q1_audio_checkpoint,
    q1_text_checkpoint_path,
    q1_audio_checkpoint_path
) = load_pretrained_text_audio_encoders(
    question_index=0,
    seed=42
)

q1_fusion_model = TextAudioQuestMF(
    text_encoder=q1_text_encoder,
    audio_encoder=q1_audio_encoder
).to(device)
q1_fusion_model.train()

text_trainable = sum(
    parameter.numel()
    for parameter in q1_fusion_model.text_encoder.parameters()
    if parameter.requires_grad
)

audio_trainable = sum(
    parameter.numel()
    for parameter in q1_fusion_model.audio_encoder.parameters()
    if parameter.requires_grad
)

total_trainable = sum(
    parameter.numel()
    for parameter in q1_fusion_model.parameters()
    if parameter.requires_grad
)

print("文本编码器处于训练模式：",
      q1_fusion_model.text_encoder.training)

print("语音编码器处于训练模式：",
      q1_fusion_model.audio_encoder.training)

print("文本可训练参数：", f"{text_trainable:,}")
print("语音可训练参数：", f"{audio_trainable:,}")
print("模型总可训练参数：", f"{total_trainable:,}")

文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q1_PHQ_8NoInterest/seed_42/best_loss.pt
语音Best Loss： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_42/question_1/best_loss.pt
文本保存Epoch： 13
语音保存Epoch： 10
文本缺少参数： []
文本多余参数： []
语音缺少参数： []
语音多余参数： []
文本编码器处于训练模式： False
语音编码器处于训练模式： True
文本可训练参数： 0
语音可训练参数： 110,800
模型总可训练参数： 6,417,684

In [156]:
q1_fusion_model.eval()

with torch.no_grad():
    logits, intermediates = q1_fusion_model(
        text_features=batch_text_features.to(device),
        text_padding_mask=batch_text_masks.to(device),
        audio_features=batch_audio_features.to(device),
        audio_padding_mask=batch_audio_masks.to(device),
        return_intermediates=True
    )

print("Text编码：",
      intermediates["text_encoding"].shape)

print("Audio编码：",
      intermediates["audio_encoding"].shape)

print("Audio → Text：",
      intermediates["audio_to_text"].shape)

print("Text → Audio：",
      intermediates["text_to_audio"].shape)

print("Text融合结果：",
      intermediates["text_fused_encoding"].shape)

print("Audio融合结果：",
      intermediates["audio_fused_encoding"].shape)

print("拼接结果：",
      intermediates["fused_encoding"].shape)

print("Logits：", logits.shape)
print("Logits全部有限：", torch.isfinite(logits).all().item())

Text编码： torch.Size([10, 120, 100])
Audio编码： torch.Size([10, 120, 100])
Audio → Text： torch.Size([10, 120, 100])
Text → Audio： torch.Size([10, 120, 100])
Text融合结果： torch.Size([10, 120, 100])
Audio融合结果： torch.Size([10, 120, 100])
拼接结果： torch.Size([10, 120, 200])
Logits： torch.Size([10, 4])
Logits全部有限： True

In [157]:
text_mask = batch_text_masks.to(device)
audio_mask = batch_audio_masks.to(device)

text_padding_values = intermediates[
    "text_fused_encoding"
].masked_select(
    text_mask.unsqueeze(-1).expand_as(
        intermediates["text_fused_encoding"]
    )
)

audio_padding_values = intermediates[
    "audio_fused_encoding"
].masked_select(
    audio_mask.unsqueeze(-1).expand_as(
        intermediates["audio_fused_encoding"]
    )
)

text_padding_max = (
    text_padding_values.abs().max().item()
    if text_padding_values.numel() > 0
    else 0.0
)

audio_padding_max = (
    audio_padding_values.abs().max().item()
    if audio_padding_values.numel() > 0
    else 0.0
)

print("文本填充位置最大绝对值：", text_padding_max)
print("语音填充位置最大绝对值：", audio_padding_max)

文本填充位置最大绝对值： 0.016936179250478745
语音填充位置最大绝对值： 0.03549167886376381

In [158]:
def gradient_norm(parameters):
    squared_norm_sum = 0.0
    gradient_tensor_count = 0

    for parameter in parameters:
        if parameter.grad is not None:
            if not torch.isfinite(parameter.grad).all():
                raise RuntimeError("发现NaN或Inf梯度")

            squared_norm_sum += (
                parameter.grad.detach().pow(2).sum().item()
            )
            gradient_tensor_count += 1

    return squared_norm_sum ** 0.5, gradient_tensor_count

In [159]:
q1_fusion_model.train()
q1_fusion_model.zero_grad(set_to_none=True)

text_batch = batch_text_features.to(device)
text_mask_batch = batch_text_masks.to(device)
audio_batch = batch_audio_features.to(device)
audio_mask_batch = batch_audio_masks.to(device)

q1_labels = batch_all_labels[:, 0].to(device)

logits = q1_fusion_model(
    text_batch,
    text_mask_batch,
    audio_batch,
    audio_mask_batch
)

diagnostic_loss = F.cross_entropy(logits, q1_labels)
diagnostic_loss.backward()
text_parameters = list(
    q1_fusion_model.text_encoder.parameters()
)

audio_parameters = list(
    q1_fusion_model.audio_encoder.parameters()
)

fusion_parameters = [
    parameter
    for name, parameter in q1_fusion_model.named_parameters()
    if not name.startswith(
        ("text_encoder.", "audio_encoder.")
    )
]

text_grad_norm, text_grad_count = gradient_norm(text_parameters)
audio_grad_norm, audio_grad_count = gradient_norm(audio_parameters)
fusion_grad_norm, fusion_grad_count = gradient_norm(fusion_parameters)

print("诊断损失：", diagnostic_loss.item())

print(
    "文本梯度：",
    text_grad_norm,
    "具有梯度的参数张量数：",
    text_grad_count
)

print(
    "语音梯度：",
    audio_grad_norm,
    "具有梯度的参数张量数：",
    audio_grad_count
)

print(
    "融合层梯度：",
    fusion_grad_norm,
    "具有梯度的参数张量数：",
    fusion_grad_count
)

诊断损失： 1.3675501346588135
文本梯度： 0.0 具有梯度的参数张量数： 0
语音梯度： 0.058201306435654215 具有梯度的参数张量数： 16
融合层梯度： 0.8055883720996126 具有梯度的参数张量数： 20

In [167]:
def calculate_imboll_weights(labels, beta):
    labels = labels.long()
    class_counts = torch.bincount(labels, minlength=NUM_CLASSES)
    if torch.any(class_counts == 0):
        raise ValueError(f"存在没有训练样本的类别：{class_counts.tolist()}")
    inverse_frequency_weights = labels.numel() / class_counts.float()
    imboll_weights = inverse_frequency_weights.pow(beta)
    return class_counts, inverse_frequency_weights, imboll_weights
q1_train_labels = train_fusion_dataset.labels[:, 0]
q1_class_counts, q1_inverse_frequency_weights, q1_imboll_weights = calculate_imboll_weights(q1_train_labels, BETA)
q1_imboll_weights_device = q1_imboll_weights.to(device)

print("Q1类别数量：", q1_class_counts.tolist())
print("Q1原始逆频率权重：", q1_inverse_frequency_weights.tolist())
print("Q1经过Beta后的ImbOLL权重：", q1_imboll_weights.tolist())
print("Q1样本总数：", int(q1_class_counts.sum().item()))

Q1类别数量： [81, 57, 20, 5]
Q1原始逆频率权重： [2.012345790863037, 2.859649181365967, 8.15000057220459, 32.60000228881836]
Q1经过Beta后的ImbOLL权重： [1.4185717105865479, 1.6910496950149536, 2.854820728302002, 5.709641456604004]
Q1样本总数： 163

In [169]:
def build_imboll_distance_matrix(class_weights):
    class_ids = torch.arange(NUM_CLASSES, device=class_weights.device, dtype=class_weights.dtype)
    ordinal_distances = torch.abs(class_ids.unsqueeze(1) - class_ids.unsqueeze(0))
    distance_matrix = class_weights.unsqueeze(1) * ordinal_distances
    return distance_matrix

In [170]:
q1_distance_matrix = build_imboll_distance_matrix(q1_imboll_weights_device)

print("Q1 ImbOLL距离矩阵：")
print(q1_distance_matrix.detach().cpu())

Q1 ImbOLL距离矩阵：
tensor([[ 0.0000,  1.4186,  2.8371,  4.2557],
        [ 1.6910,  0.0000,  1.6910,  3.3821],
        [ 5.7096,  2.8548,  0.0000,  2.8548],
        [17.1289, 11.4193,  5.7096,  0.0000]])

In [172]:
def calculate_imboll_loss(logits, labels, class_weights, alpha, epsilon=LOSS_EPSILON):
    labels = labels.long()
    probabilities = torch.softmax(logits, dim=1)
    class_ids = torch.arange(logits.shape[1], device=logits.device, dtype=torch.long)
    ordinal_distances = torch.abs(labels.unsqueeze(1) - class_ids.unsqueeze(0)).to(logits.dtype)
    true_class_weights = class_weights[labels].unsqueeze(1)
    weighted_distances = (true_class_weights * ordinal_distances).pow(alpha)
    negative_log_complements = -torch.log(torch.clamp(1.0 - probabilities, min=epsilon))
    sample_losses = torch.sum(negative_log_complements * weighted_distances, dim=1)
    loss = sample_losses.mean()
    return loss
example_logits = torch.tensor([[0.2, 0.4, 1.5, -0.3]], dtype=torch.float32, device=device)
example_label = torch.tensor([0], dtype=torch.long, device=device)
example_probabilities = torch.softmax(example_logits, dim=1)
example_loss = calculate_imboll_loss(example_logits, example_label, q1_imboll_weights_device, ALPHA)

print("示例概率：", example_probabilities.detach().cpu())
print("示例真实类别：", example_label.item())
print("示例ImbOLL：", example_loss.item())

示例概率： tensor([[0.1539, 0.1880, 0.5647, 0.0934]])
示例真实类别： 0
示例ImbOLL： 3.0724897384643555

In [173]:
q1_fusion_model.train()
q1_fusion_model.zero_grad(set_to_none=True)

batch_text_features_device = batch_text_features.to(device)
batch_text_masks_device = batch_text_masks.to(device)
batch_audio_features_device = batch_audio_features.to(device)
batch_audio_masks_device = batch_audio_masks.to(device)
batch_q1_labels_device = batch_all_labels[:, 0].to(device)

q1_logits = q1_fusion_model(batch_text_features_device, batch_text_masks_device, batch_audio_features_device, batch_audio_masks_device)
q1_probabilities = torch.softmax(q1_logits, dim=1)
q1_predictions = torch.argmax(q1_logits, dim=1)
q1_imboll_loss = calculate_imboll_loss(q1_logits, batch_q1_labels_device, q1_imboll_weights_device, ALPHA)

print("Logits形状：", q1_logits.shape)
print("ImbOLL：", q1_imboll_loss.item())
print("预测概率全部有限：", torch.isfinite(q1_probabilities).all().item())
print("预测类别：", q1_predictions.detach().cpu())
print("真实类别：", batch_q1_labels_device.detach().cpu())
q1_imboll_loss.backward()

text_grad_norm, text_grad_count = gradient_norm(q1_fusion_model.text_encoder.parameters())
audio_grad_norm, audio_grad_count = gradient_norm(q1_fusion_model.audio_encoder.parameters())
fusion_parameters = [parameter for name, parameter in q1_fusion_model.named_parameters() if not name.startswith(("text_encoder.", "audio_encoder."))]
fusion_grad_norm, fusion_grad_count = gradient_norm(fusion_parameters)

print("文本梯度范数：", text_grad_norm)
print("文本梯度张量数：", text_grad_count)
print("语音梯度范数：", audio_grad_norm)
print("语音梯度张量数：", audio_grad_count)
print("融合层梯度范数：", fusion_grad_norm)
print("融合层梯度张量数：", fusion_grad_count)

Logits形状： torch.Size([10, 4])
ImbOLL： 2.2545089721679688
预测概率全部有限： True
预测类别： tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])
真实类别： tensor([1, 0, 1, 0, 0, 0, 0, 0, 0, 1])
文本梯度范数： 0.0
文本梯度张量数： 0
语音梯度范数： 0.0941634756980071
语音梯度张量数： 16
融合层梯度范数： 1.1606160427137056
融合层梯度张量数： 20

In [174]:
def calculate_sample_ccc(predictions, targets, epsilon=LOSS_EPSILON):
    predictions = predictions.float()
    targets = targets.float()
    if predictions.numel() < 2:
        raise ValueError("CCC至少需要两个样本")
    predictions_mean = predictions.mean()
    targets_mean = targets.mean()
    predictions_centered = predictions - predictions_mean
    targets_centered = targets - targets_mean
    denominator_n = predictions.numel() - 1
    covariance = torch.sum(predictions_centered * targets_centered) / denominator_n
    predictions_variance = torch.sum(predictions_centered ** 2) / denominator_n
    targets_variance = torch.sum(targets_centered ** 2) / denominator_n
    ccc = (2.0 * covariance) / (predictions_variance + targets_variance + (predictions_mean - targets_mean) ** 2 + epsilon)
    return ccc
def calculate_multiclass_metrics(predictions, targets, num_classes=NUM_CLASSES):
    predictions = predictions.long()
    targets = targets.long()
    confusion_indices = targets * num_classes + predictions
    confusion_matrix = torch.bincount(confusion_indices, minlength=num_classes * num_classes).reshape(num_classes, num_classes).float()
    true_positives = torch.diag(confusion_matrix)
    false_positives = confusion_matrix.sum(dim=0) - true_positives
    false_negatives = confusion_matrix.sum(dim=1) - true_positives
    supports = confusion_matrix.sum(dim=1)
    precision = true_positives / torch.clamp(true_positives + false_positives, min=1.0)
    recall = true_positives / torch.clamp(true_positives + false_negatives, min=1.0)
    class_f1 = 2.0 * precision * recall / torch.clamp(precision + recall, min=LOSS_EPSILON)
    accuracy = true_positives.sum() / torch.clamp(confusion_matrix.sum(), min=1.0)
    micro_f1 = 2.0 * true_positives.sum() / torch.clamp(2.0 * true_positives.sum() + false_positives.sum() + false_negatives.sum(), min=1.0)
    macro_f1 = class_f1.mean()
    weighted_f1 = torch.sum(class_f1 * supports) / torch.clamp(supports.sum(), min=1.0)
    return {"accuracy": accuracy.item(), "micro_f1": micro_f1.item(), "macro_f1": macro_f1.item(), "weighted_f1": weighted_f1.item(), "confusion_matrix": confusion_matrix.long()}

In [175]:
def run_fusion_epoch(model, dataloader, question_index, class_weights, optimizer=None):
    is_training = optimizer is not None
    if is_training:
        model.train()
    else:
        model.eval()
    total_loss = 0.0
    total_samples = 0
    prediction_batches = []
    target_batches = []
    for batch in dataloader:
        text_features, text_masks, audio_features, audio_masks, all_labels = batch
        text_features = text_features.to(device)
        text_masks = text_masks.to(device)
        audio_features = audio_features.to(device)
        audio_masks = audio_masks.to(device)
        labels = all_labels[:, question_index].to(device)
        if is_training:
            optimizer.zero_grad(set_to_none=True)
        with torch.set_grad_enabled(is_training):
            logits = model(text_features, text_masks, audio_features, audio_masks)
            loss = calculate_imboll_loss(logits, labels, class_weights, ALPHA)
            if is_training:
                loss.backward()
                torch.nn.utils.clip_grad_norm_(model.parameters(), MAX_GRAD_NORM)
                optimizer.step()
        predictions = torch.argmax(logits, dim=1)
        batch_size = labels.shape[0]
        total_loss += loss.item() * batch_size
        total_samples += batch_size
        prediction_batches.append(predictions.detach().cpu())
        target_batches.append(labels.detach().cpu())
    all_predictions = torch.cat(prediction_batches, dim=0)
    all_targets = torch.cat(target_batches, dim=0)
    average_loss = total_loss / total_samples
    classification_metrics = calculate_multiclass_metrics(all_predictions, all_targets)
    ccc = calculate_sample_ccc(all_predictions.float(), all_targets.float()).item()
    rmse = torch.sqrt(torch.mean((all_predictions.float() - all_targets.float()) ** 2)).item()
    mae = torch.mean(torch.abs(all_predictions.float() - all_targets.float())).item()
    return {"loss": average_loss, "accuracy": classification_metrics["accuracy"], "micro_f1": classification_metrics["micro_f1"], "macro_f1": classification_metrics["macro_f1"], "weighted_f1": classification_metrics["weighted_f1"], "ccc": ccc, "rmse": rmse, "mae": mae, "confusion_matrix": classification_metrics["confusion_matrix"], "predictions": all_predictions, "targets": all_targets}

In [176]:
def print_epoch_metrics(prefix, metrics):
    print(f"{prefix} Loss：{metrics['loss']:.6f}")
    print(f"{prefix} Accuracy：{metrics['accuracy']:.6f}")
    print(f"{prefix} Micro F1：{metrics['micro_f1']:.6f}")
    print(f"{prefix} Macro F1：{metrics['macro_f1']:.6f}")
    print(f"{prefix} Weighted F1：{metrics['weighted_f1']:.6f}")
    print(f"{prefix} CCC：{metrics['ccc']:.6f}")
    print(f"{prefix} RMSE：{metrics['rmse']:.6f}")
    print(f"{prefix} MAE：{metrics['mae']:.6f}")
    print(f"{prefix}混淆矩阵：")
    print(metrics["confusion_matrix"])

In [177]:
set_seed(42)

smoke_text_encoder, smoke_audio_encoder, smoke_text_checkpoint, smoke_audio_checkpoint, smoke_text_checkpoint_path, smoke_audio_checkpoint_path = load_pretrained_text_audio_encoders(question_index=0, seed=42)
smoke_model = TextAudioQuestMF(smoke_text_encoder, smoke_audio_encoder).to(device)
smoke_train_loader, smoke_val_loader = create_fusion_dataloaders(seed=42)
smoke_optimizer = torch.optim.AdamW([parameter for parameter in smoke_model.parameters() if parameter.requires_grad], lr=LEARNING_RATE, eps=ADAM_EPSILON, weight_decay=WEIGHT_DECAY)

smoke_train_metrics = run_fusion_epoch(smoke_model, smoke_train_loader, question_index=0, class_weights=q1_imboll_weights_device, optimizer=smoke_optimizer)
smoke_val_metrics = run_fusion_epoch(smoke_model, smoke_val_loader, question_index=0, class_weights=q1_imboll_weights_device, optimizer=None)

print_epoch_metrics("一轮训练", smoke_train_metrics)
print_epoch_metrics("一轮验证", smoke_val_metrics)

文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q1_PHQ_8NoInterest/seed_42/best_loss.pt
语音Best Loss： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_42/question_1/best_loss.pt
文本保存Epoch： 13
语音保存Epoch： 10
文本缺少参数： []
文本多余参数： []
语音缺少参数： []
语音多余参数： []
一轮训练 Loss：2.058525
一轮训练 Accuracy：0.435583
一轮训练 Micro F1：0.435583
一轮训练 Macro F1：0.255187
一轮训练 Weighted F1：0.418007
一轮训练 CCC：0.295829
一轮训练 RMSE：0.810211
一轮训练 MAE：0.595092
一轮训练混淆矩阵：
tensor([[43, 38,  0,  0],
        [30, 27,  0,  0],
        [ 1, 18,  1,  0],
        [ 0,  4,  1,  0]])
一轮验证 Loss：2.681503
一轮验证 Accuracy：0.490909
一轮验证 Micro F1：0.490909
一轮验证 Macro F1：0.273366
一轮验证 Weighted F1：0.409380
一轮验证 CCC：0.303162
一轮验证 RMSE：0.981650
一轮验证 MAE：0.636364
一轮验证混淆矩阵：
tensor([[23,  2,  0,  0],
        [15,  3,  4,  0],
        [ 2,  1,  1,  0],
        [ 2,  1,  1,  0]])

In [178]:
assert np.isfinite(smoke_train_metrics["loss"])
assert np.isfinite(smoke_val_metrics["loss"])
assert np.isfinite(smoke_val_metrics["ccc"])
assert 0.0 <= smoke_train_metrics["accuracy"] <= 1.0
assert 0.0 <= smoke_val_metrics["accuracy"] <= 1.0
assert -1.0 <= smoke_val_metrics["ccc"] <= 1.0

print("单Epoch训练与验证检查通过")

单Epoch训练与验证检查通过

In [179]:
def compact_fusion_metrics(metrics):
    compact_metrics = {}
    compact_metrics["loss"] = float(metrics["loss"])
    compact_metrics["accuracy"] = float(metrics["accuracy"])
    compact_metrics["micro_f1"] = float(metrics["micro_f1"])
    compact_metrics["macro_f1"] = float(metrics["macro_f1"])
    compact_metrics["weighted_f1"] = float(metrics["weighted_f1"])
    compact_metrics["ccc"] = float(metrics["ccc"])
    compact_metrics["rmse"] = float(metrics["rmse"])
    compact_metrics["mae"] = float(metrics["mae"])
    compact_metrics["confusion_matrix"] = metrics["confusion_matrix"].tolist()
    return compact_metrics

In [180]:
def create_fusion_checkpoint(model, optimizer, checkpoint_type, epoch, question_index, seed, train_metrics, val_metrics, class_counts, imboll_weights, text_checkpoint_path, audio_checkpoint_path, best_val_loss, best_val_ccc, best_loss_epoch, best_ccc_epoch):
    checkpoint = {}
    checkpoint["checkpoint_type"] = checkpoint_type
    checkpoint["epoch"] = epoch
    checkpoint["question_index"] = question_index
    checkpoint["question_number"] = question_index + 1
    checkpoint["question_name"] = PHQ8_QUESTION_COLUMNS[question_index]
    checkpoint["seed"] = seed
    checkpoint["model_state_dict"] = model.state_dict()
    checkpoint["optimizer_state_dict"] = optimizer.state_dict()
    checkpoint["train_metrics"] = compact_fusion_metrics(train_metrics)
    checkpoint["val_metrics"] = compact_fusion_metrics(val_metrics)
    checkpoint["class_counts"] = class_counts.tolist()
    checkpoint["imboll_weights"] = imboll_weights.tolist()
    checkpoint["best_val_loss"] = best_val_loss
    checkpoint["best_val_ccc"] = best_val_ccc
    checkpoint["best_loss_epoch"] = best_loss_epoch
    checkpoint["best_ccc_epoch"] = best_ccc_epoch
    checkpoint["text_checkpoint_path"] = str(text_checkpoint_path)
    checkpoint["audio_checkpoint_path"] = str(audio_checkpoint_path)
    checkpoint["config"] = {"max_turns": MAX_TURNS, "text_feature_dim": TEXT_FEATURE_DIM, "audio_feature_dim": AUDIO_FEATURE_DIM, "encoder_output_dim": ENCODER_OUTPUT_DIM, "num_classes": NUM_CLASSES, "attention_heads": ATTENTION_HEADS, "batch_size": BATCH_SIZE, "num_epochs": NUM_EPOCHS, "learning_rate": LEARNING_RATE, "adam_epsilon": ADAM_EPSILON, "weight_decay": WEIGHT_DECAY, "max_grad_norm": MAX_GRAD_NORM, "fusion_dropout": FUSION_DROPOUT, "mlp_first_dropout": MLP_FIRST_DROPOUT, "mlp_last_dropout": MLP_LAST_DROPOUT, "alpha": ALPHA, "beta": BETA}
    return checkpoint

In [181]:
def train_fusion_question(question_index, seed):
    set_seed(seed)
    question_number = question_index + 1
    question_name = PHQ8_QUESTION_COLUMNS[question_index]
    output_dir = FUSION_CHECKPOINT_ROOT / f"seed_{seed}" / f"question_{question_number}"
    output_dir.mkdir(parents=True, exist_ok=True)
    best_loss_path = output_dir / "best_loss.pt"
    best_ccc_path = output_dir / "best_ccc.pt"
    last_path = output_dir / "last.pt"
    history_path = output_dir / "history.csv"
    train_loader, val_loader = create_fusion_dataloaders(seed)
    train_labels = train_fusion_dataset.labels[:, question_index]
    class_counts, inverse_frequency_weights, imboll_weights = calculate_imboll_weights(train_labels, BETA)
    imboll_weights_device = imboll_weights.to(device)
    text_encoder, audio_encoder, text_checkpoint, audio_checkpoint, text_checkpoint_path, audio_checkpoint_path = load_pretrained_text_audio_encoders(question_index=question_index, seed=seed)
    model = TextAudioQuestMF(text_encoder=text_encoder, audio_encoder=audio_encoder).to(device)
    optimizer = torch.optim.AdamW([parameter for parameter in model.parameters() if parameter.requires_grad], lr=LEARNING_RATE, eps=ADAM_EPSILON, weight_decay=WEIGHT_DECAY)
    best_val_loss = float("inf")
    best_val_ccc = float("-inf")
    best_loss_epoch = None
    best_ccc_epoch = None
    history_rows = []
    print("=" * 100)
    print(f"开始训练：Seed={seed}，Q{question_number}，{question_name}")
    print("类别数量：", class_counts.tolist())
    print("ImbOLL权重：", imboll_weights.tolist())
    print("=" * 100)
    for epoch in range(1, NUM_EPOCHS + 1):
        epoch_start_time = time.time()
        train_metrics = run_fusion_epoch(model, train_loader, question_index, imboll_weights_device, optimizer)
        val_metrics = run_fusion_epoch(model, val_loader, question_index, imboll_weights_device, optimizer=None)
        epoch_seconds = time.time() - epoch_start_time
        history_row = {"Epoch": epoch, "Train_Loss": train_metrics["loss"], "Train_Accuracy": train_metrics["accuracy"], "Train_CCC": train_metrics["ccc"], "Train_RMSE": train_metrics["rmse"], "Train_MAE": train_metrics["mae"], "Val_Loss": val_metrics["loss"], "Val_Accuracy": val_metrics["accuracy"], "Val_Micro_F1": val_metrics["micro_f1"], "Val_Macro_F1": val_metrics["macro_f1"], "Val_Weighted_F1": val_metrics["weighted_f1"], "Val_CCC": val_metrics["ccc"], "Val_RMSE": val_metrics["rmse"], "Val_MAE": val_metrics["mae"], "Seconds": epoch_seconds}
        history_rows.append(history_row)
        if not np.isfinite(val_metrics["loss"]):
            raise RuntimeError(f"Seed={seed}，Q{question_number}在Epoch={epoch}出现非有限验证损失")
        if not np.isfinite(val_metrics["ccc"]):
            raise RuntimeError(f"Seed={seed}，Q{question_number}在Epoch={epoch}出现非有限CCC")
        if val_metrics["loss"] < best_val_loss:
            best_val_loss = val_metrics["loss"]
            best_loss_epoch = epoch
            best_loss_checkpoint = create_fusion_checkpoint(model, optimizer, "best_loss", epoch, question_index, seed, train_metrics, val_metrics, class_counts, imboll_weights, text_checkpoint_path, audio_checkpoint_path, best_val_loss, best_val_ccc, best_loss_epoch, best_ccc_epoch)
            torch.save(best_loss_checkpoint, best_loss_path)
        if val_metrics["ccc"] > best_val_ccc:
            best_val_ccc = val_metrics["ccc"]
            best_ccc_epoch = epoch
            best_ccc_checkpoint = create_fusion_checkpoint(model, optimizer, "best_ccc", epoch, question_index, seed, train_metrics, val_metrics, class_counts, imboll_weights, text_checkpoint_path, audio_checkpoint_path, best_val_loss, best_val_ccc, best_loss_epoch, best_ccc_epoch)
            torch.save(best_ccc_checkpoint, best_ccc_path)
        last_checkpoint = create_fusion_checkpoint(model, optimizer, "last", epoch, question_index, seed, train_metrics, val_metrics, class_counts, imboll_weights, text_checkpoint_path, audio_checkpoint_path, best_val_loss, best_val_ccc, best_loss_epoch, best_ccc_epoch)
        torch.save(last_checkpoint, last_path)
        pd.DataFrame(history_rows).to_csv(history_path, index=False)
        print(f"Epoch {epoch:02d}/{NUM_EPOCHS} | Train Loss {train_metrics['loss']:.6f} | Val Loss {val_metrics['loss']:.6f} | Val CCC {val_metrics['ccc']:.6f} | Val Acc {val_metrics['accuracy']:.6f} | Val RMSE {val_metrics['rmse']:.6f} | {epoch_seconds:.2f}s")
    result = {"seed": seed, "question_index": question_index, "question_number": question_number, "question_name": question_name, "best_val_loss": best_val_loss, "best_val_ccc": best_val_ccc, "best_loss_epoch": best_loss_epoch, "best_ccc_epoch": best_ccc_epoch, "best_loss_path": best_loss_path, "best_ccc_path": best_ccc_path, "last_path": last_path, "history_path": history_path}
    del model
    del optimizer
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
    print("=" * 100)
    print(f"训练完成：Seed={seed}，Q{question_number}")
    print(f"最佳Val Loss：{best_val_loss:.6f}，Epoch={best_loss_epoch}")
    print(f"最佳Val CCC：{best_val_ccc:.6f}，Epoch={best_ccc_epoch}")
    print("=" * 100)
    return result

In [182]:
for variable_name in ["q1_fusion_model", "smoke_model", "smoke_optimizer", "smoke_text_encoder", "smoke_audio_encoder"]:
    globals().pop(variable_name, None)

if torch.cuda.is_available():
    torch.cuda.empty_cache()

print("冒烟模型已释放")

冒烟模型已释放

In [183]:
q1_seed42_fusion_result = train_fusion_question(question_index=0, seed=42)

文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q1_PHQ_8NoInterest/seed_42/best_loss.pt
语音Best Loss： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_42/question_1/best_loss.pt
文本保存Epoch： 13
语音保存Epoch： 10
文本缺少参数： []
文本多余参数： []
语音缺少参数： []
语音多余参数： []
====================================================================================================
开始训练：Seed=42，Q1，PHQ_8NoInterest
类别数量： [81, 57, 20, 5]
ImbOLL权重： [1.4185717105865479, 1.6910496950149536, 2.854820728302002, 5.709641456604004]
====================================================================================================
Epoch 01/20 | Train Loss 2.058525 | Val Loss 2.681503 | Val CCC 0.303162 | Val Acc 0.490909 | Val RMSE 0.981650 | 0.85s
Epoch 02/20 | Train Loss 1.263167 | Val Loss 3.217984 | Val CCC 0.338044 | Val Acc 0.600000 | Val RMSE 0.924416 | 0.80s
Epoch 03/20 | Train Loss 1.358892 | Val Loss 2.383685 | Val CCC 0.405946 | Val Acc 0.563636 | Val RMSE 0.831209 | 0.84s
Epoch 04/20 | Train Loss 1.261398 | Val Loss 2.916068 | Val CCC 0.400501 | Val Acc 0.581818 | Val RMSE 0.797724 | 0.75s
Epoch 05/20 | Train Loss 1.174877 | Val Loss 3.031433 | Val CCC 0.309958 | Val Acc 0.545455 | Val RMSE 0.953463 | 0.74s
Epoch 06/20 | Train Loss 1.085151 | Val Loss 3.002906 | Val CCC 0.317506 | Val Acc 0.527273 | Val RMSE 0.934199 | 0.83s
Epoch 07/20 | Train Loss 1.127885 | Val Loss 3.668763 | Val CCC 0.317482 | Val Acc 0.545455 | Val RMSE 0.924416 | 0.73s
Epoch 08/20 | Train Loss 1.146497 | Val Loss 2.441431 | Val CCC 0.433067 | Val Acc 0.527273 | Val RMSE 0.831209 | 0.76s
Epoch 09/20 | Train Loss 1.089704 | Val Loss 2.814690 | Val CCC 0.441801 | Val Acc 0.545455 | Val RMSE 0.786245 | 0.75s
Epoch 10/20 | Train Loss 1.081532 | Val Loss 2.643825 | Val CCC 0.458608 | Val Acc 0.545455 | Val RMSE 0.786245 | 0.74s
Epoch 11/20 | Train Loss 1.100971 | Val Loss 3.105617 | Val CCC 0.318769 | Val Acc 0.509091 | Val RMSE 0.943880 | 0.73s
Epoch 12/20 | Train Loss 0.983552 | Val Loss 2.702756 | Val CCC 0.484603 | Val Acc 0.545455 | Val RMSE 0.786245 | 0.78s
Epoch 13/20 | Train Loss 1.050046 | Val Loss 2.969607 | Val CCC 0.461906 | Val Acc 0.563636 | Val RMSE 0.774597 | 0.74s
Epoch 14/20 | Train Loss 1.014565 | Val Loss 3.109128 | Val CCC 0.324683 | Val Acc 0.581818 | Val RMSE 0.884205 | 0.74s
Epoch 15/20 | Train Loss 1.004155 | Val Loss 2.855954 | Val CCC 0.438941 | Val Acc 0.527273 | Val RMSE 0.797724 | 0.76s
Epoch 16/20 | Train Loss 0.948821 | Val Loss 2.709793 | Val CCC 0.325702 | Val Acc 0.581818 | Val RMSE 0.904534 | 0.79s
Epoch 17/20 | Train Loss 0.991136 | Val Loss 2.609870 | Val CCC 0.459838 | Val Acc 0.545455 | Val RMSE 0.820200 | 0.73s
Epoch 18/20 | Train Loss 0.883921 | Val Loss 3.297068 | Val CCC 0.317482 | Val Acc 0.545455 | Val RMSE 0.924416 | 0.73s
Epoch 19/20 | Train Loss 1.169900 | Val Loss 2.537379 | Val CCC 0.451380 | Val Acc 0.545455 | Val RMSE 0.852803 | 0.71s
Epoch 20/20 | Train Loss 1.014850 | Val Loss 2.844314 | Val CCC 0.399671 | Val Acc 0.563636 | Val RMSE 0.809040 | 0.72s
====================================================================================================
训练完成：Seed=42，Q1
最佳Val Loss：2.383685，Epoch=3
最佳Val CCC：0.484603，Epoch=12
====================================================================================================

In [184]:
def load_fusion_model_from_checkpoint(checkpoint_path):
    checkpoint_path = Path(checkpoint_path)
    if not checkpoint_path.exists():
        raise FileNotFoundError(f"融合Checkpoint不存在：{checkpoint_path}")
    checkpoint = torch.load(checkpoint_path, map_location="cpu", weights_only=False)
    required_fields = {"checkpoint_type", "epoch", "question_index", "seed", "model_state_dict", "val_metrics", "imboll_weights"}
    missing_fields = required_fields.difference(checkpoint.keys())
    if missing_fields:
        raise RuntimeError(f"融合Checkpoint缺少字段：{sorted(missing_fields)}")
    text_encoder = PretrainedTextEncoder()
    audio_encoder = PretrainedAudioEncoder()
    model = TextAudioQuestMF(text_encoder=text_encoder, audio_encoder=audio_encoder).to(device)
    load_result = model.load_state_dict(checkpoint["model_state_dict"], strict=True)
    model.eval()
    print("Checkpoint：", checkpoint_path)
    print("类型：", checkpoint["checkpoint_type"])
    print("Epoch：", checkpoint["epoch"])
    print("缺少参数：", load_result.missing_keys)
    print("多余参数：", load_result.unexpected_keys)
    return model, checkpoint

In [185]:
def verify_fusion_checkpoint(checkpoint_path):
    model, checkpoint = load_fusion_model_from_checkpoint(checkpoint_path)
    question_index = int(checkpoint["question_index"])
    seed = int(checkpoint["seed"])
    imboll_weights = torch.tensor(checkpoint["imboll_weights"], dtype=torch.float32, device=device)
    train_loader, val_loader = create_fusion_dataloaders(seed)
    restored_metrics = run_fusion_epoch(model, val_loader, question_index, imboll_weights, optimizer=None)
    saved_metrics = checkpoint["val_metrics"]
    metric_names = ["loss", "accuracy", "micro_f1", "macro_f1", "weighted_f1", "ccc", "rmse", "mae"]
    print("保存指标与恢复指标对比：")
    for metric_name in metric_names:
        saved_value = float(saved_metrics[metric_name])
        restored_value = float(restored_metrics[metric_name])
        difference = abs(saved_value - restored_value)
        print(f"{metric_name:>12} | 保存 {saved_value:.9f} | 恢复 {restored_value:.9f} | 差值 {difference:.3e}")
        if not np.isclose(saved_value, restored_value, rtol=0.0, atol=1e-6):
            raise RuntimeError(f"{metric_name}恢复后不一致")
    saved_confusion_matrix = torch.tensor(saved_metrics["confusion_matrix"], dtype=torch.long)
    restored_confusion_matrix = restored_metrics["confusion_matrix"]
    if not torch.equal(saved_confusion_matrix, restored_confusion_matrix):
        raise RuntimeError("恢复后的混淆矩阵不一致")
    result = {"checkpoint_type": checkpoint["checkpoint_type"], "epoch": checkpoint["epoch"], "question_index": question_index, "seed": seed, "metrics": restored_metrics}
    del model
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
    print("Checkpoint恢复验证通过")
    return result

In [186]:
q1_seed42_best_loss_verification = verify_fusion_checkpoint(q1_seed42_fusion_result["best_loss_path"])

Checkpoint： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/seed_42/question_1/best_loss.pt
类型： best_loss
Epoch： 3
缺少参数： []
多余参数： []
保存指标与恢复指标对比：
        loss | 保存 2.383685307 | 恢复 2.383685307 | 差值 0.000e+00
    accuracy | 保存 0.563636363 | 恢复 0.563636363 | 差值 0.000e+00
    micro_f1 | 保存 0.563636363 | 恢复 0.563636363 | 差值 0.000e+00
    macro_f1 | 保存 0.365768313 | 恢复 0.365768313 | 差值 0.000e+00
 weighted_f1 | 保存 0.549639344 | 恢复 0.549639344 | 差值 0.000e+00
         ccc | 保存 0.405946046 | 恢复 0.405946046 | 差值 0.000e+00
        rmse | 保存 0.831209421 | 恢复 0.831209421 | 差值 0.000e+00
         mae | 保存 0.509090900 | 恢复 0.509090900 | 差值 0.000e+00
Checkpoint恢复验证通过

In [187]:
q1_seed42_best_ccc_verification = verify_fusion_checkpoint(q1_seed42_fusion_result["best_ccc_path"])

Checkpoint： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/seed_42/question_1/best_ccc.pt
类型： best_ccc
Epoch： 12
缺少参数： []
多余参数： []
保存指标与恢复指标对比：
        loss | 保存 2.702756123 | 恢复 2.702756123 | 差值 0.000e+00
    accuracy | 保存 0.545454562 | 恢复 0.545454562 | 差值 0.000e+00
    micro_f1 | 保存 0.545454562 | 恢复 0.545454562 | 差值 0.000e+00
    macro_f1 | 保存 0.352083355 | 恢复 0.352083355 | 差值 0.000e+00
 weighted_f1 | 保存 0.536515176 | 恢复 0.536515176 | 差值 0.000e+00
         ccc | 保存 0.484603375 | 恢复 0.484603375 | 差值 0.000e+00
        rmse | 保存 0.786245406 | 恢复 0.786245406 | 差值 0.000e+00
         mae | 保存 0.509090900 | 恢复 0.509090900 | 差值 0.000e+00
Checkpoint恢复验证通过

In [188]:
seed42_fusion_results = [q1_seed42_fusion_result]

for question_index in range(1, 8):
    question_result = train_fusion_question(question_index=question_index, seed=42)
    seed42_fusion_results.append(question_result)

文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q2_PHQ_8Depressed/seed_42/best_loss.pt
语音Best Loss： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_42/question_2/best_loss.pt
文本保存Epoch： 9
语音保存Epoch： 11
文本缺少参数： []
文本多余参数： []
语音缺少参数： []
语音多余参数： []
====================================================================================================
开始训练：Seed=42，Q2，PHQ_8Depressed
类别数量： [68, 63, 18, 14]
ImbOLL权重： [1.548243761062622, 1.6085091829299927, 3.009244918823242, 3.412163257598877]
====================================================================================================
Epoch 01/20 | Train Loss 2.219187 | Val Loss 2.337435 | Val CCC 0.364986 | Val Acc 0.472727 | Val RMSE 0.990867 | 0.95s
Epoch 02/20 | Train Loss 1.572842 | Val Loss 2.022577 | Val CCC 0.540718 | Val Acc 0.490909 | Val RMSE 0.852803 | 0.81s
Epoch 03/20 | Train Loss 1.679481 | Val Loss 1.995854 | Val CCC 0.536761 | Val Acc 0.527273 | Val RMSE 0.797724 | 1.20s
Epoch 04/20 | Train Loss 1.597517 | Val Loss 1.985951 | Val CCC 0.510547 | Val Acc 0.527273 | Val RMSE 0.831209 | 0.87s
Epoch 05/20 | Train Loss 1.571728 | Val Loss 1.985882 | Val CCC 0.475122 | Val Acc 0.490909 | Val RMSE 0.884205 | 0.82s
Epoch 06/20 | Train Loss 1.585503 | Val Loss 1.995511 | Val CCC 0.543212 | Val Acc 0.545455 | Val RMSE 0.820200 | 0.80s
Epoch 07/20 | Train Loss 1.499993 | Val Loss 2.175469 | Val CCC 0.466370 | Val Acc 0.509091 | Val RMSE 0.863397 | 0.79s
Epoch 08/20 | Train Loss 1.466763 | Val Loss 2.037446 | Val CCC 0.529923 | Val Acc 0.545455 | Val RMSE 0.852803 | 0.74s
Epoch 09/20 | Train Loss 1.520744 | Val Loss 2.007055 | Val CCC 0.519549 | Val Acc 0.527273 | Val RMSE 0.831209 | 0.72s
Epoch 10/20 | Train Loss 1.451767 | Val Loss 2.012818 | Val CCC 0.462230 | Val Acc 0.472727 | Val RMSE 0.924416 | 0.76s
Epoch 11/20 | Train Loss 1.563343 | Val Loss 2.275250 | Val CCC 0.493453 | Val Acc 0.545455 | Val RMSE 0.873863 | 0.72s
Epoch 12/20 | Train Loss 1.413847 | Val Loss 2.040502 | Val CCC 0.466052 | Val Acc 0.527273 | Val RMSE 0.852803 | 0.73s
Epoch 13/20 | Train Loss 1.419617 | Val Loss 2.022457 | Val CCC 0.433625 | Val Acc 0.436364 | Val RMSE 0.884205 | 0.71s
Epoch 14/20 | Train Loss 1.384292 | Val Loss 2.212295 | Val CCC 0.370837 | Val Acc 0.400000 | Val RMSE 0.873863 | 0.78s
Epoch 15/20 | Train Loss 1.618572 | Val Loss 2.419261 | Val CCC 0.453628 | Val Acc 0.527273 | Val RMSE 0.914529 | 0.72s
Epoch 16/20 | Train Loss 1.965653 | Val Loss 2.116900 | Val CCC 0.489984 | Val Acc 0.527273 | Val RMSE 0.914529 | 0.71s
Epoch 17/20 | Train Loss 1.498748 | Val Loss 2.121762 | Val CCC 0.383054 | Val Acc 0.418182 | Val RMSE 0.863397 | 0.72s
Epoch 18/20 | Train Loss 1.339116 | Val Loss 2.036379 | Val CCC 0.470467 | Val Acc 0.509091 | Val RMSE 0.894427 | 0.70s
Epoch 19/20 | Train Loss 1.418311 | Val Loss 2.117653 | Val CCC 0.431065 | Val Acc 0.454545 | Val RMSE 0.873863 | 0.75s
Epoch 20/20 | Train Loss 1.383638 | Val Loss 2.153066 | Val CCC 0.409185 | Val Acc 0.509091 | Val RMSE 0.924416 | 0.66s
====================================================================================================
训练完成：Seed=42，Q2
最佳Val Loss：1.985882，Epoch=5
最佳Val CCC：0.543212，Epoch=6
====================================================================================================
文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q3_PHQ_8Sleep/seed_42/best_loss.pt
语音Best Loss： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_42/question_3/best_loss.pt
文本保存Epoch： 9
语音保存Epoch： 14
文本缺少参数： []
文本多余参数： []
语音缺少参数： []
语音多余参数： []
====================================================================================================
开始训练：Seed=42，Q3，PHQ_8Sleep
类别数量： [69, 40, 27, 27]
ImbOLL权重： [1.5369837284088135, 2.018662929534912, 2.457038164138794, 2.457038164138794]
====================================================================================================
Epoch 01/20 | Train Loss 2.402374 | Val Loss 2.511941 | Val CCC 0.388266 | Val Acc 0.400000 | Val RMSE 1.228451 | 0.70s
Epoch 02/20 | Train Loss 1.848214 | Val Loss 2.174585 | Val CCC 0.427523 | Val Acc 0.418182 | Val RMSE 1.095445 | 0.70s
Epoch 03/20 | Train Loss 1.902915 | Val Loss 2.372281 | Val CCC 0.378986 | Val Acc 0.454545 | Val RMSE 1.183216 | 0.77s
Epoch 04/20 | Train Loss 1.787067 | Val Loss 2.731936 | Val CCC 0.452531 | Val Acc 0.472727 | Val RMSE 1.136182 | 0.76s
Epoch 05/20 | Train Loss 1.755066 | Val Loss 2.290436 | Val CCC 0.425928 | Val Acc 0.490909 | Val RMSE 1.111919 | 0.75s
Epoch 06/20 | Train Loss 1.729054 | Val Loss 2.333027 | Val CCC 0.423815 | Val Acc 0.436364 | Val RMSE 1.136182 | 0.73s
Epoch 07/20 | Train Loss 1.713972 | Val Loss 2.339076 | Val CCC 0.365772 | Val Acc 0.381818 | Val RMSE 1.078720 | 0.71s
Epoch 08/20 | Train Loss 1.750432 | Val Loss 2.332426 | Val CCC 0.409042 | Val Acc 0.436364 | Val RMSE 1.175508 | 0.71s
Epoch 09/20 | Train Loss 1.761795 | Val Loss 2.330179 | Val CCC 0.402566 | Val Acc 0.436364 | Val RMSE 1.228451 | 0.72s
Epoch 10/20 | Train Loss 1.753778 | Val Loss 2.294969 | Val CCC 0.385635 | Val Acc 0.418182 | Val RMSE 1.159937 | 0.72s
Epoch 11/20 | Train Loss 1.693462 | Val Loss 2.568447 | Val CCC 0.355461 | Val Acc 0.418182 | Val RMSE 1.221028 | 0.73s
Epoch 12/20 | Train Loss 1.698635 | Val Loss 2.164561 | Val CCC 0.360577 | Val Acc 0.454545 | Val RMSE 1.103713 | 0.69s
Epoch 13/20 | Train Loss 1.655523 | Val Loss 2.611155 | Val CCC 0.421895 | Val Acc 0.472727 | Val RMSE 1.250454 | 0.69s
Epoch 14/20 | Train Loss 1.830422 | Val Loss 2.222418 | Val CCC 0.372516 | Val Acc 0.454545 | Val RMSE 1.167748 | 0.71s
Epoch 15/20 | Train Loss 1.712717 | Val Loss 2.290292 | Val CCC 0.443546 | Val Acc 0.400000 | Val RMSE 1.167748 | 0.70s
Epoch 16/20 | Train Loss 1.674418 | Val Loss 2.598321 | Val CCC 0.386534 | Val Acc 0.472727 | Val RMSE 1.175508 | 0.70s
Epoch 17/20 | Train Loss 1.660153 | Val Loss 2.236497 | Val CCC 0.442628 | Val Acc 0.436364 | Val RMSE 1.111919 | 0.71s
Epoch 18/20 | Train Loss 1.628912 | Val Loss 2.390039 | Val CCC 0.336823 | Val Acc 0.436364 | Val RMSE 1.213560 | 0.69s
Epoch 19/20 | Train Loss 1.765667 | Val Loss 2.202281 | Val CCC 0.382653 | Val Acc 0.436364 | Val RMSE 1.111919 | 0.69s
Epoch 20/20 | Train Loss 1.618018 | Val Loss 2.684482 | Val CCC 0.429619 | Val Acc 0.472727 | Val RMSE 1.175508 | 0.70s
====================================================================================================
训练完成：Seed=42，Q3
最佳Val Loss：2.164561，Epoch=12
最佳Val CCC：0.452531，Epoch=4
====================================================================================================
文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q4_PHQ_8Tired/seed_42/best_loss.pt
语音Best Loss： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_42/question_4/best_loss.pt
文本保存Epoch： 11
语音保存Epoch： 28
文本缺少参数： []
文本多余参数： []
语音缺少参数： []
语音多余参数： []
====================================================================================================
开始训练：Seed=42，Q4，PHQ_8Tired
类别数量： [50, 65, 27, 21]
ImbOLL权重： [1.8055469989776611, 1.5835695266723633, 2.457038164138794, 2.7860195636749268]
====================================================================================================
Epoch 01/20 | Train Loss 2.483959 | Val Loss 2.340738 | Val CCC 0.243352 | Val Acc 0.400000 | Val RMSE 0.904534 | 0.69s
Epoch 02/20 | Train Loss 1.826303 | Val Loss 2.505425 | Val CCC 0.315341 | Val Acc 0.309091 | Val RMSE 1.257704 | 0.70s
Epoch 03/20 | Train Loss 1.763326 | Val Loss 2.325999 | Val CCC 0.337477 | Val Acc 0.363636 | Val RMSE 0.924416 | 0.70s
Epoch 04/20 | Train Loss 1.815210 | Val Loss 2.249264 | Val CCC 0.474041 | Val Acc 0.418182 | Val RMSE 0.863397 | 0.69s
Epoch 05/20 | Train Loss 1.677158 | Val Loss 2.274486 | Val CCC 0.305589 | Val Acc 0.400000 | Val RMSE 0.962950 | 0.73s
Epoch 06/20 | Train Loss 1.746682 | Val Loss 2.232577 | Val CCC 0.413550 | Val Acc 0.400000 | Val RMSE 0.962950 | 0.72s
Epoch 07/20 | Train Loss 1.770940 | Val Loss 2.237280 | Val CCC 0.315501 | Val Acc 0.436364 | Val RMSE 0.914529 | 0.73s
Epoch 08/20 | Train Loss 1.736191 | Val Loss 2.220324 | Val CCC 0.370153 | Val Acc 0.400000 | Val RMSE 0.904534 | 0.72s
Epoch 09/20 | Train Loss 1.701157 | Val Loss 2.264667 | Val CCC 0.344663 | Val Acc 0.381818 | Val RMSE 0.914529 | 0.71s
Epoch 10/20 | Train Loss 1.714641 | Val Loss 2.246175 | Val CCC 0.337477 | Val Acc 0.363636 | Val RMSE 0.924416 | 0.70s
Epoch 11/20 | Train Loss 1.652055 | Val Loss 2.410105 | Val CCC 0.334680 | Val Acc 0.418182 | Val RMSE 1.198484 | 0.69s
Epoch 12/20 | Train Loss 1.722896 | Val Loss 2.227090 | Val CCC 0.396879 | Val Acc 0.381818 | Val RMSE 0.972345 | 0.69s
Epoch 13/20 | Train Loss 1.602359 | Val Loss 2.238707 | Val CCC 0.361622 | Val Acc 0.345455 | Val RMSE 0.934199 | 0.70s
Epoch 14/20 | Train Loss 1.756421 | Val Loss 2.401716 | Val CCC 0.295170 | Val Acc 0.381818 | Val RMSE 0.943880 | 0.71s
Epoch 15/20 | Train Loss 1.655499 | Val Loss 2.170752 | Val CCC 0.422814 | Val Acc 0.381818 | Val RMSE 0.914529 | 0.71s
Epoch 16/20 | Train Loss 1.563907 | Val Loss 2.333565 | Val CCC 0.321794 | Val Acc 0.454545 | Val RMSE 1.111919 | 0.71s
Epoch 17/20 | Train Loss 1.525386 | Val Loss 2.377332 | Val CCC 0.376421 | Val Acc 0.381818 | Val RMSE 1.120065 | 0.69s
Epoch 18/20 | Train Loss 1.398014 | Val Loss 2.354865 | Val CCC 0.336784 | Val Acc 0.381818 | Val RMSE 1.120065 | 0.70s
Epoch 19/20 | Train Loss 1.431340 | Val Loss 2.484520 | Val CCC 0.387974 | Val Acc 0.400000 | Val RMSE 1.061731 | 0.71s
Epoch 20/20 | Train Loss 1.389485 | Val Loss 2.364706 | Val CCC 0.402689 | Val Acc 0.472727 | Val RMSE 1.009050 | 0.72s
====================================================================================================
训练完成：Seed=42，Q4
最佳Val Loss：2.170752，Epoch=15
最佳Val CCC：0.474041，Epoch=4
====================================================================================================
文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q5_PHQ_8Appetite/seed_42/best_loss.pt
语音Best Loss： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_42/question_5/best_loss.pt
文本保存Epoch： 13
语音保存Epoch： 32
文本缺少参数： []
文本多余参数： []
语音缺少参数： []
语音多余参数： []
====================================================================================================
开始训练：Seed=42，Q5，PHQ_8Appetite
类别数量： [77, 42, 24, 20]
ImbOLL权重： [1.454951286315918, 1.9700132608413696, 2.6060826778411865, 2.854820728302002]
====================================================================================================
Epoch 01/20 | Train Loss 2.443262 | Val Loss 2.126681 | Val CCC 0.358245 | Val Acc 0.418182 | Val RMSE 0.981650 | 0.70s
Epoch 02/20 | Train Loss 1.789082 | Val Loss 2.474344 | Val CCC 0.420534 | Val Acc 0.381818 | Val RMSE 1.070259 | 0.70s
Epoch 03/20 | Train Loss 1.755883 | Val Loss 2.276932 | Val CCC 0.497774 | Val Acc 0.454545 | Val RMSE 0.934199 | 0.71s
Epoch 04/20 | Train Loss 1.651788 | Val Loss 2.238364 | Val CCC 0.503828 | Val Acc 0.490909 | Val RMSE 0.884205 | 0.75s
Epoch 05/20 | Train Loss 1.687094 | Val Loss 2.715180 | Val CCC 0.459606 | Val Acc 0.454545 | Val RMSE 1.009050 | 0.70s
Epoch 06/20 | Train Loss 1.547562 | Val Loss 2.348876 | Val CCC 0.504385 | Val Acc 0.527273 | Val RMSE 0.863397 | 0.70s
Epoch 07/20 | Train Loss 1.490540 | Val Loss 2.638709 | Val CCC 0.522600 | Val Acc 0.472727 | Val RMSE 0.924416 | 0.72s
Epoch 08/20 | Train Loss 1.615020 | Val Loss 2.898222 | Val CCC 0.502406 | Val Acc 0.490909 | Val RMSE 0.962950 | 0.70s
Epoch 09/20 | Train Loss 1.501343 | Val Loss 2.361049 | Val CCC 0.421527 | Val Acc 0.472727 | Val RMSE 0.972345 | 0.70s
Epoch 10/20 | Train Loss 1.595590 | Val Loss 2.875756 | Val CCC 0.482167 | Val Acc 0.454545 | Val RMSE 0.962950 | 0.69s
Epoch 11/20 | Train Loss 1.520869 | Val Loss 3.124809 | Val CCC 0.394328 | Val Acc 0.400000 | Val RMSE 1.152073 | 0.70s
Epoch 12/20 | Train Loss 1.658121 | Val Loss 2.207417 | Val CCC 0.481930 | Val Acc 0.490909 | Val RMSE 0.884205 | 0.70s
Epoch 13/20 | Train Loss 1.454370 | Val Loss 2.627912 | Val CCC 0.455052 | Val Acc 0.436364 | Val RMSE 1.018019 | 0.72s
Epoch 14/20 | Train Loss 1.461818 | Val Loss 2.988446 | Val CCC 0.497417 | Val Acc 0.472727 | Val RMSE 0.972345 | 0.74s
Epoch 15/20 | Train Loss 1.485680 | Val Loss 2.619079 | Val CCC 0.460212 | Val Acc 0.454545 | Val RMSE 0.962950 | 0.70s
Epoch 16/20 | Train Loss 1.485253 | Val Loss 2.739797 | Val CCC 0.475431 | Val Acc 0.436364 | Val RMSE 1.018019 | 0.69s
Epoch 17/20 | Train Loss 1.484538 | Val Loss 3.177743 | Val CCC 0.465283 | Val Acc 0.436364 | Val RMSE 1.018019 | 0.70s
Epoch 18/20 | Train Loss 1.419692 | Val Loss 2.736595 | Val CCC 0.472046 | Val Acc 0.454545 | Val RMSE 0.962950 | 0.71s
Epoch 19/20 | Train Loss 1.374306 | Val Loss 3.322481 | Val CCC 0.447052 | Val Acc 0.472727 | Val RMSE 1.053134 | 0.70s
Epoch 20/20 | Train Loss 1.510086 | Val Loss 2.965659 | Val CCC 0.458987 | Val Acc 0.454545 | Val RMSE 1.009050 | 0.70s
====================================================================================================
训练完成：Seed=42，Q5
最佳Val Loss：2.126681，Epoch=1
最佳Val CCC：0.522600，Epoch=7
====================================================================================================
文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q6_PHQ_8Failure/seed_42/best_loss.pt
语音Best Loss： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_42/question_6/best_loss.pt
文本保存Epoch： 10
语音保存Epoch： 45
文本缺少参数： []
文本多余参数： []
语音缺少参数： []
语音多余参数： []
====================================================================================================
开始训练：Seed=42，Q6，PHQ_8Failure
类别数量： [76, 44, 24, 19]
ImbOLL权重： [1.4644919633865356, 1.9247195720672607, 2.6060826778411865, 2.9289839267730713]
====================================================================================================
Epoch 01/20 | Train Loss 2.275641 | Val Loss 2.003324 | Val CCC 0.449215 | Val Acc 0.472727 | Val RMSE 0.943880 | 0.70s
Epoch 02/20 | Train Loss 1.663445 | Val Loss 2.095276 | Val CCC 0.434934 | Val Acc 0.418182 | Val RMSE 1.103713 | 0.72s
Epoch 03/20 | Train Loss 1.793118 | Val Loss 2.047533 | Val CCC 0.473712 | Val Acc 0.490909 | Val RMSE 0.934199 | 0.71s
Epoch 04/20 | Train Loss 1.622331 | Val Loss 2.059062 | Val CCC 0.386196 | Val Acc 0.418182 | Val RMSE 1.078720 | 0.71s
Epoch 05/20 | Train Loss 1.740733 | Val Loss 2.008420 | Val CCC 0.387095 | Val Acc 0.418182 | Val RMSE 1.053134 | 0.72s
Epoch 06/20 | Train Loss 1.629964 | Val Loss 2.153185 | Val CCC 0.412012 | Val Acc 0.454545 | Val RMSE 1.009050 | 0.70s
Epoch 07/20 | Train Loss 1.585022 | Val Loss 2.022391 | Val CCC 0.387095 | Val Acc 0.418182 | Val RMSE 1.053134 | 0.69s
Epoch 08/20 | Train Loss 1.537735 | Val Loss 1.986292 | Val CCC 0.494710 | Val Acc 0.472727 | Val RMSE 0.924416 | 0.69s
Epoch 09/20 | Train Loss 1.585514 | Val Loss 2.176800 | Val CCC 0.468051 | Val Acc 0.436364 | Val RMSE 1.026911 | 0.69s
Epoch 10/20 | Train Loss 1.763932 | Val Loss 1.971007 | Val CCC 0.447510 | Val Acc 0.490909 | Val RMSE 0.904534 | 0.69s
Epoch 11/20 | Train Loss 1.647032 | Val Loss 2.035071 | Val CCC 0.430000 | Val Acc 0.472727 | Val RMSE 1.026911 | 0.74s
Epoch 12/20 | Train Loss 1.563010 | Val Loss 1.952753 | Val CCC 0.504489 | Val Acc 0.472727 | Val RMSE 0.894427 | 0.69s
Epoch 13/20 | Train Loss 1.578391 | Val Loss 2.002548 | Val CCC 0.430917 | Val Acc 0.400000 | Val RMSE 0.962950 | 0.68s
Epoch 14/20 | Train Loss 1.636111 | Val Loss 1.958378 | Val CCC 0.535874 | Val Acc 0.472727 | Val RMSE 0.894427 | 0.70s
Epoch 15/20 | Train Loss 1.675506 | Val Loss 2.038815 | Val CCC 0.463404 | Val Acc 0.472727 | Val RMSE 1.000000 | 0.68s
Epoch 16/20 | Train Loss 1.568357 | Val Loss 2.087789 | Val CCC 0.455869 | Val Acc 0.490909 | Val RMSE 0.990867 | 0.69s
Epoch 17/20 | Train Loss 1.534075 | Val Loss 1.989935 | Val CCC 0.493649 | Val Acc 0.454545 | Val RMSE 0.934199 | 0.69s
Epoch 18/20 | Train Loss 1.482068 | Val Loss 2.332326 | Val CCC 0.463404 | Val Acc 0.472727 | Val RMSE 1.000000 | 0.69s
Epoch 19/20 | Train Loss 1.503450 | Val Loss 2.085912 | Val CCC 0.419027 | Val Acc 0.381818 | Val RMSE 1.000000 | 0.70s
Epoch 20/20 | Train Loss 1.471822 | Val Loss 2.143353 | Val CCC 0.416329 | Val Acc 0.472727 | Val RMSE 0.943880 | 0.70s
====================================================================================================
训练完成：Seed=42，Q6
最佳Val Loss：1.952753，Epoch=12
最佳Val CCC：0.535874，Epoch=14
====================================================================================================
文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q7_PHQ_8Concentrating/seed_42/best_loss.pt
语音Best Loss： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_42/question_7/best_loss.pt
文本保存Epoch： 15
语音保存Epoch： 3
文本缺少参数： []
文本多余参数： []
语音缺少参数： []
语音多余参数： []
====================================================================================================
开始训练：Seed=42，Q7，PHQ_8Concentrating
类别数量： [93, 37, 14, 19]
ImbOLL权重： [1.323891282081604, 2.0989058017730713, 3.412163257598877, 2.9289839267730713]
====================================================================================================
Epoch 01/20 | Train Loss 2.468517 | Val Loss 2.077133 | Val CCC 0.290812 | Val Acc 0.636364 | Val RMSE 0.914529 | 0.72s
Epoch 02/20 | Train Loss 1.534720 | Val Loss 2.671878 | Val CCC 0.418915 | Val Acc 0.472727 | Val RMSE 1.167748 | 0.71s
Epoch 03/20 | Train Loss 1.623231 | Val Loss 2.219674 | Val CCC 0.512012 | Val Acc 0.490909 | Val RMSE 0.852803 | 0.70s
Epoch 04/20 | Train Loss 1.490589 | Val Loss 1.952867 | Val CCC 0.447895 | Val Acc 0.563636 | Val RMSE 0.842075 | 0.70s
Epoch 05/20 | Train Loss 1.488181 | Val Loss 1.955997 | Val CCC 0.514615 | Val Acc 0.509091 | Val RMSE 0.842075 | 0.70s
Epoch 06/20 | Train Loss 1.369774 | Val Loss 2.139473 | Val CCC 0.478841 | Val Acc 0.400000 | Val RMSE 0.904534 | 0.69s
Epoch 07/20 | Train Loss 1.373229 | Val Loss 2.079126 | Val CCC 0.453538 | Val Acc 0.490909 | Val RMSE 0.904534 | 0.70s
Epoch 08/20 | Train Loss 1.428563 | Val Loss 2.135073 | Val CCC 0.566598 | Val Acc 0.472727 | Val RMSE 0.863397 | 0.70s
Epoch 09/20 | Train Loss 1.412510 | Val Loss 2.069763 | Val CCC 0.454962 | Val Acc 0.509091 | Val RMSE 0.894427 | 0.70s
Epoch 10/20 | Train Loss 1.393952 | Val Loss 2.031226 | Val CCC 0.506607 | Val Acc 0.418182 | Val RMSE 0.863397 | 0.73s
Epoch 11/20 | Train Loss 1.462807 | Val Loss 2.342518 | Val CCC 0.444728 | Val Acc 0.472727 | Val RMSE 1.026911 | 0.73s
Epoch 12/20 | Train Loss 1.263454 | Val Loss 1.967894 | Val CCC 0.517330 | Val Acc 0.527273 | Val RMSE 0.831209 | 0.74s
Epoch 13/20 | Train Loss 1.268615 | Val Loss 2.049404 | Val CCC 0.562986 | Val Acc 0.472727 | Val RMSE 0.797724 | 0.75s
Epoch 14/20 | Train Loss 1.357306 | Val Loss 2.391877 | Val CCC 0.435514 | Val Acc 0.490909 | Val RMSE 0.962950 | 0.71s
Epoch 15/20 | Train Loss 1.358622 | Val Loss 1.994757 | Val CCC 0.512012 | Val Acc 0.490909 | Val RMSE 0.852803 | 0.71s
Epoch 16/20 | Train Loss 1.190685 | Val Loss 2.751021 | Val CCC 0.482160 | Val Acc 0.509091 | Val RMSE 0.981650 | 0.70s
Epoch 17/20 | Train Loss 1.378391 | Val Loss 2.236056 | Val CCC 0.495132 | Val Acc 0.418182 | Val RMSE 0.924416 | 0.71s
Epoch 18/20 | Train Loss 1.448386 | Val Loss 2.624604 | Val CCC 0.487898 | Val Acc 0.545455 | Val RMSE 0.904534 | 0.70s
Epoch 19/20 | Train Loss 1.353650 | Val Loss 2.030014 | Val CCC 0.512012 | Val Acc 0.490909 | Val RMSE 0.852803 | 0.70s
Epoch 20/20 | Train Loss 1.236643 | Val Loss 2.571248 | Val CCC 0.489633 | Val Acc 0.509091 | Val RMSE 0.953463 | 0.70s
====================================================================================================
训练完成：Seed=42，Q7
最佳Val Loss：1.952867，Epoch=4
最佳Val CCC：0.566598，Epoch=8
====================================================================================================
文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q8_PHQ_8Moving/seed_42/best_loss.pt
语音Best Loss： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_42/question_8/best_loss.pt
文本保存Epoch： 11
语音保存Epoch： 12
文本缺少参数： []
文本多余参数： []
语音缺少参数： []
语音多余参数： []

In [189]:
seed42_summary_rows = []

for result in seed42_fusion_results:
    summary_row = {}
    summary_row["Seed"] = result["seed"]
    summary_row["Question_Index"] = result["question_index"]
    summary_row["Question_Number"] = result["question_number"]
    summary_row["Question_Name"] = result["question_name"]
    summary_row["Best_Val_Loss"] = result["best_val_loss"]
    summary_row["Best_Loss_Epoch"] = result["best_loss_epoch"]
    summary_row["Best_Val_CCC"] = result["best_val_ccc"]
    summary_row["Best_CCC_Epoch"] = result["best_ccc_epoch"]
    summary_row["Best_Loss_Path"] = str(result["best_loss_path"])
    summary_row["Best_CCC_Path"] = str(result["best_ccc_path"])
    seed42_summary_rows.append(summary_row)

seed42_fusion_summary_df = pd.DataFrame(seed42_summary_rows)
seed42_fusion_summary_path = FUSION_CHECKPOINT_ROOT / "seed_42_question_summary.csv"
seed42_fusion_summary_df.to_csv(seed42_fusion_summary_path, index=False)

display(seed42_fusion_summary_df)
print("Seed 42汇总文件：", seed42_fusion_summary_path)

,Seed,Question_Index,Question_Number,Question_Name,Best_Val_Loss,Best_Loss_Epoch,Best_Val_CCC,Best_CCC_Epoch,Best_Loss_Path,Best_CCC_Path
0,42,0,1,PHQ_8NoInterest,2.383685,3,0.484603,12,/workspace/E-DAIC/checkpoints/phq8_text_audio_...,/workspace/E-DAIC/checkpoints/phq8_text_audio_...
1,42,1,2,PHQ_8Depressed,1.985882,5,0.543212,6,/workspace/E-DAIC/checkpoints/phq8_text_audio_...,/workspace/E-DAIC/checkpoints/phq8_text_audio_...
2,42,2,3,PHQ_8Sleep,2.164561,12,0.452531,4,/workspace/E-DAIC/checkpoints/phq8_text_audio_...,/workspace/E-DAIC/checkpoints/phq8_text_audio_...
3,42,3,4,PHQ_8Tired,2.170752,15,0.474041,4,/workspace/E-DAIC/checkpoints/phq8_text_audio_...,/workspace/E-DAIC/checkpoints/phq8_text_audio_...
4,42,4,5,PHQ_8Appetite,2.126681,1,0.522600,7,/workspace/E-DAIC/checkpoints/phq8_text_audio_...,/workspace/E-DAIC/checkpoints/phq8_text_audio_...
5,42,5,6,PHQ_8Failure,1.952753,12,0.535874,14,/workspace/E-DAIC/checkpoints/phq8_text_audio_...,/workspace/E-DAIC/checkpoints/phq8_text_audio_...
6,42,6,7,PHQ_8Concentrating,1.952867,4,0.566598,8,/workspace/E-DAIC/checkpoints/phq8_text_audio_...,/workspace/E-DAIC/checkpoints/phq8_text_audio_...
7,42,7,8,PHQ_8Moving,1.865783,1,0.344404,16,/workspace/E-DAIC/checkpoints/phq8_text_audio_...,/workspace/E-DAIC/checkpoints/phq8_text_audio_...

Seed 42汇总文件： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/seed_42_question_summary.csv

In [190]:
print("结果数量：", len(seed42_fusion_results))
print("Best Loss全部存在：", all(result["best_loss_path"].exists() for result in seed42_fusion_results))
print("Best CCC全部存在：", all(result["best_ccc_path"].exists() for result in seed42_fusion_results))
print("Last全部存在：", all(result["last_path"].exists() for result in seed42_fusion_results))
print("History全部存在：", all(result["history_path"].exists() for result in seed42_fusion_results))

结果数量： 8
Best Loss全部存在： True
Best CCC全部存在： True
Last全部存在： True
History全部存在： True

In [191]:
for result in seed42_fusion_results:
    checkpoint = torch.load(result["best_ccc_path"], map_location="cpu", weights_only=False)
    assert checkpoint["checkpoint_type"] == "best_ccc"
    assert checkpoint["seed"] == 42
    assert checkpoint["question_index"] == result["question_index"]
    print(f"Q{checkpoint['question_number']} | Epoch {checkpoint['epoch']:02d} | Val CCC {checkpoint['val_metrics']['ccc']:.6f} | Val Loss {checkpoint['val_metrics']['loss']:.6f}")

Q1 | Epoch 12 | Val CCC 0.484603 | Val Loss 2.702756
Q2 | Epoch 06 | Val CCC 0.543212 | Val Loss 1.995511
Q3 | Epoch 04 | Val CCC 0.452531 | Val Loss 2.731936
Q4 | Epoch 04 | Val CCC 0.474041 | Val Loss 2.249264
Q5 | Epoch 07 | Val CCC 0.522600 | Val Loss 2.638709
Q6 | Epoch 14 | Val CCC 0.535874 | Val Loss 1.958378
Q7 | Epoch 08 | Val CCC 0.566598 | Val Loss 2.135073
Q8 | Epoch 16 | Val CCC 0.344404 | Val Loss 2.648369

In [192]:
def predict_fusion_question(model, dataloader, question_index):
    model.eval()
    prediction_batches = []
    target_batches = []
    with torch.no_grad():
        for batch in dataloader:
            text_features, text_masks, audio_features, audio_masks, all_labels = batch
            text_features = text_features.to(device)
            text_masks = text_masks.to(device)
            audio_features = audio_features.to(device)
            audio_masks = audio_masks.to(device)
            logits = model(text_features, text_masks, audio_features, audio_masks)
            predictions = torch.argmax(logits, dim=1)
            targets = all_labels[:, question_index]
            prediction_batches.append(predictions.cpu())
            target_batches.append(targets.cpu())
    all_predictions = torch.cat(prediction_batches, dim=0)
    all_targets = torch.cat(target_batches, dim=0)
    return all_predictions, all_targets

In [193]:
def evaluate_fusion_seed_on_validation(seed):
    train_loader, val_loader = create_fusion_dataloaders(seed)
    question_prediction_columns = []
    question_target_columns = []
    question_metric_rows = []
    for question_index in range(8):
        question_number = question_index + 1
        checkpoint_path = FUSION_CHECKPOINT_ROOT / f"seed_{seed}" / f"question_{question_number}" / "best_ccc.pt"
        model, checkpoint = load_fusion_model_from_checkpoint(checkpoint_path)
        if checkpoint["seed"] != seed:
            raise RuntimeError(f"Q{question_number}的Seed不匹配")
        if checkpoint["question_index"] != question_index:
            raise RuntimeError(f"Q{question_number}的题号不匹配")
        predictions, targets = predict_fusion_question(model, val_loader, question_index)
        question_prediction_columns.append(predictions)
        question_target_columns.append(targets)
        question_ccc = calculate_sample_ccc(predictions.float(), targets.float()).item()
        question_rmse = torch.sqrt(torch.mean((predictions.float() - targets.float()) ** 2)).item()
        question_mae = torch.mean(torch.abs(predictions.float() - targets.float())).item()
        question_accuracy = torch.mean((predictions == targets).float()).item()
        question_metric_rows.append({"Question_Number": question_number, "Question_Name": PHQ8_QUESTION_COLUMNS[question_index], "Checkpoint_Epoch": checkpoint["epoch"], "CCC": question_ccc, "RMSE": question_rmse, "MAE": question_mae, "Accuracy": question_accuracy})
        del model
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
    predicted_question_scores = torch.stack(question_prediction_columns, dim=1)
    true_question_scores = torch.stack(question_target_columns, dim=1)
    expected_true_question_scores = val_fusion_dataset.labels.cpu()
    if not torch.equal(true_question_scores, expected_true_question_scores):
        raise RuntimeError("验证集8道题标签顺序不一致")
    predicted_total_scores = predicted_question_scores.sum(dim=1)
    true_total_scores = true_question_scores.sum(dim=1)
    total_ccc = calculate_sample_ccc(predicted_total_scores.float(), true_total_scores.float()).item()
    total_rmse = torch.sqrt(torch.mean((predicted_total_scores.float() - true_total_scores.float()) ** 2)).item()
    total_mae = torch.mean(torch.abs(predicted_total_scores.float() - true_total_scores.float())).item()
    exact_accuracy = torch.mean((predicted_total_scores == true_total_scores).float()).item()
    question_metrics_df = pd.DataFrame(question_metric_rows)
    prediction_df = pd.DataFrame({"Participant_ID": val_fusion_dataset.participant_ids})
    for question_index in range(8):
        prediction_df[f"Pred_Q{question_index + 1}"] = predicted_question_scores[:, question_index].numpy()
        prediction_df[f"True_Q{question_index + 1}"] = true_question_scores[:, question_index].numpy()
    prediction_df["Predicted_PHQ8_Total"] = predicted_total_scores.numpy()
    prediction_df["True_PHQ8_Total"] = true_total_scores.numpy()
    prediction_df["Error"] = prediction_df["Predicted_PHQ8_Total"] - prediction_df["True_PHQ8_Total"]
    question_metrics_path = FUSION_CHECKPOINT_ROOT / f"seed_{seed}_validation_question_metrics.csv"
    prediction_path = FUSION_CHECKPOINT_ROOT / f"seed_{seed}_validation_predictions.csv"
    question_metrics_df.to_csv(question_metrics_path, index=False)
    prediction_df.to_csv(prediction_path, index=False)
    result = {"seed": seed, "sample_count": len(prediction_df), "ccc": total_ccc, "rmse": total_rmse, "mae": total_mae, "exact_accuracy": exact_accuracy, "predicted_min": int(predicted_total_scores.min().item()), "predicted_max": int(predicted_total_scores.max().item()), "true_min": int(true_total_scores.min().item()), "true_max": int(true_total_scores.max().item()), "question_metrics_df": question_metrics_df, "prediction_df": prediction_df, "question_metrics_path": question_metrics_path, "prediction_path": prediction_path}
    return result

In [194]:
seed42_fusion_validation_result = evaluate_fusion_seed_on_validation(seed=42)

print("=" * 80)
print("Text + Audio Seed 42验证集总分结果")
print("=" * 80)
print("验证参与者数量：", seed42_fusion_validation_result["sample_count"])
print("CCC：", f"{seed42_fusion_validation_result['ccc']:.6f}")
print("RMSE：", f"{seed42_fusion_validation_result['rmse']:.6f}")
print("MAE：", f"{seed42_fusion_validation_result['mae']:.6f}")
print("完全相等比例：", f"{seed42_fusion_validation_result['exact_accuracy']:.6f}")
print("预测总分范围：", f"{seed42_fusion_validation_result['predicted_min']}～{seed42_fusion_validation_result['predicted_max']}")
print("真实总分范围：", f"{seed42_fusion_validation_result['true_min']}～{seed42_fusion_validation_result['true_max']}")
print("预测文件：", seed42_fusion_validation_result["prediction_path"])

Checkpoint： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/seed_42/question_1/best_ccc.pt
类型： best_ccc
Epoch： 12
缺少参数： []
多余参数： []
Checkpoint： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/seed_42/question_2/best_ccc.pt
类型： best_ccc
Epoch： 6
缺少参数： []
多余参数： []
Checkpoint： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/seed_42/question_3/best_ccc.pt
类型： best_ccc
Epoch： 4
缺少参数： []
多余参数： []
Checkpoint： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/seed_42/question_4/best_ccc.pt
类型： best_ccc
Epoch： 4
缺少参数： []
多余参数： []
Checkpoint： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/seed_42/question_5/best_ccc.pt
类型： best_ccc
Epoch： 7
缺少参数： []
多余参数： []
Checkpoint： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/seed_42/question_6/best_ccc.pt
类型： best_ccc
Epoch： 14
缺少参数： []
多余参数： []
Checkpoint： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/seed_42/question_7/best_ccc.pt
类型： best_ccc
Epoch： 8
缺少参数： []
多余参数： []
Checkpoint： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/seed_42/question_8/best_ccc.pt
类型： best_ccc
Epoch： 16
缺少参数： []
多余参数： []
================================================================================
Text + Audio Seed 42验证集总分结果
================================================================================
验证参与者数量： 55
CCC： 0.700692
RMSE： 4.316986
MAE： 3.181818
完全相等比例： 0.090909
预测总分范围： 0～22
真实总分范围： 0～20
预测文件： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/seed_42_validation_predictions.csv

In [195]:
display(seed42_fusion_validation_result["question_metrics_df"])

,Question_Number,Question_Name,Checkpoint_Epoch,CCC,RMSE,MAE,Accuracy
0,1,PHQ_8NoInterest,12,0.484603,0.786245,0.509091,0.545455
1,2,PHQ_8Depressed,6,0.543212,0.820200,0.527273,0.545455
2,3,PHQ_8Sleep,4,0.452531,1.136182,0.745455,0.472727
3,4,PHQ_8Tired,4,0.474041,0.863397,0.636364,0.418182
4,5,PHQ_8Appetite,7,0.522600,0.924416,0.636364,0.472727
5,6,PHQ_8Failure,14,0.535874,0.894427,0.618182,0.472727
6,7,PHQ_8Concentrating,8,0.566598,0.863397,0.600000,0.472727
7,8,PHQ_8Moving,16,0.344404,0.809040,0.509091,0.563636

In [196]:
print("验证参与者数量：", seed42_fusion_validation_result["sample_count"])
print("总分CCC：", f"{seed42_fusion_validation_result['ccc']:.6f}")
print("总分RMSE：", f"{seed42_fusion_validation_result['rmse']:.6f}")
print("总分MAE：", f"{seed42_fusion_validation_result['mae']:.6f}")
print("完全相等比例：", f"{seed42_fusion_validation_result['exact_accuracy']:.6f}")
print("预测总分范围：", f"{seed42_fusion_validation_result['predicted_min']}～{seed42_fusion_validation_result['predicted_max']}")
print("真实总分范围：", f"{seed42_fusion_validation_result['true_min']}～{seed42_fusion_validation_result['true_max']}")

验证参与者数量： 55
总分CCC： 0.700692
总分RMSE： 4.316986
总分MAE： 3.181818
完全相等比例： 0.090909
预测总分范围： 0～22
真实总分范围： 0～20

In [197]:
def train_all_fusion_questions_for_seed(seed):
    seed_results = []
    for question_index in range(8):
        question_result = train_fusion_question(question_index=question_index, seed=seed)
        seed_results.append(question_result)
    summary_rows = []
    for result in seed_results:
        summary_row = {}
        summary_row["Seed"] = result["seed"]
        summary_row["Question_Index"] = result["question_index"]
        summary_row["Question_Number"] = result["question_number"]
        summary_row["Question_Name"] = result["question_name"]
        summary_row["Best_Val_Loss"] = result["best_val_loss"]
        summary_row["Best_Loss_Epoch"] = result["best_loss_epoch"]
        summary_row["Best_Val_CCC"] = result["best_val_ccc"]
        summary_row["Best_CCC_Epoch"] = result["best_ccc_epoch"]
        summary_row["Best_Loss_Path"] = str(result["best_loss_path"])
        summary_row["Best_CCC_Path"] = str(result["best_ccc_path"])
        summary_rows.append(summary_row)
    summary_df = pd.DataFrame(summary_rows)
    summary_path = FUSION_CHECKPOINT_ROOT / f"seed_{seed}_question_summary.csv"
    summary_df.to_csv(summary_path, index=False)
    print(f"Seed {seed}全部8道题训练完成")
    print("汇总文件：", summary_path)
    return seed_results, summary_df

In [198]:
seed100_fusion_results, seed100_fusion_summary_df = train_all_fusion_questions_for_seed(seed=100)
display(seed100_fusion_summary_df)

文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q1_PHQ_8NoInterest/seed_100/best_loss.pt
语音Best Loss： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_100/question_1/best_loss.pt
文本保存Epoch： 10
语音保存Epoch： 8
文本缺少参数： []
文本多余参数： []
语音缺少参数： []
语音多余参数： []
====================================================================================================
开始训练：Seed=100，Q1，PHQ_8NoInterest
类别数量： [81, 57, 20, 5]
ImbOLL权重： [1.4185717105865479, 1.6910496950149536, 2.854820728302002, 5.709641456604004]
====================================================================================================
Epoch 01/20 | Train Loss 2.008674 | Val Loss 3.084688 | Val CCC 0.296198 | Val Acc 0.472727 | Val RMSE 1.018019 | 1.26s
Epoch 02/20 | Train Loss 1.533344 | Val Loss 3.309865 | Val CCC 0.319838 | Val Acc 0.509091 | Val RMSE 1.000000 | 0.79s
Epoch 03/20 | Train Loss 1.570934 | Val Loss 3.004611 | Val CCC 0.287760 | Val Acc 0.454545 | Val RMSE 0.953463 | 0.81s
Epoch 04/20 | Train Loss 1.592438 | Val Loss 2.486881 | Val CCC 0.311383 | Val Acc 0.472727 | Val RMSE 0.914529 | 0.79s
Epoch 05/20 | Train Loss 1.588860 | Val Loss 2.950630 | Val CCC 0.288447 | Val Acc 0.600000 | Val RMSE 0.924416 | 0.88s
Epoch 06/20 | Train Loss 1.452953 | Val Loss 2.665527 | Val CCC 0.287231 | Val Acc 0.436364 | Val RMSE 0.962950 | 0.81s
Epoch 07/20 | Train Loss 1.423281 | Val Loss 3.262508 | Val CCC 0.198043 | Val Acc 0.509091 | Val RMSE 0.924416 | 0.83s
Epoch 08/20 | Train Loss 1.517415 | Val Loss 3.444045 | Val CCC 0.253297 | Val Acc 0.563636 | Val RMSE 0.972345 | 0.80s
Epoch 09/20 | Train Loss 1.488920 | Val Loss 2.492701 | Val CCC 0.300356 | Val Acc 0.472727 | Val RMSE 0.914529 | 0.75s
Epoch 10/20 | Train Loss 1.445519 | Val Loss 3.124509 | Val CCC 0.306202 | Val Acc 0.545455 | Val RMSE 0.904534 | 0.74s
Epoch 11/20 | Train Loss 1.452551 | Val Loss 2.642231 | Val CCC 0.287043 | Val Acc 0.545455 | Val RMSE 0.873863 | 0.85s
Epoch 12/20 | Train Loss 1.442613 | Val Loss 2.778674 | Val CCC 0.361747 | Val Acc 0.509091 | Val RMSE 0.953463 | 0.74s
Epoch 13/20 | Train Loss 1.417796 | Val Loss 2.837297 | Val CCC 0.277618 | Val Acc 0.509091 | Val RMSE 0.894427 | 0.72s
Epoch 14/20 | Train Loss 1.452958 | Val Loss 2.538937 | Val CCC 0.331861 | Val Acc 0.454545 | Val RMSE 0.894427 | 0.71s
Epoch 15/20 | Train Loss 1.394194 | Val Loss 3.125757 | Val CCC 0.263217 | Val Acc 0.563636 | Val RMSE 0.972345 | 0.75s
Epoch 16/20 | Train Loss 1.379245 | Val Loss 2.845142 | Val CCC 0.332377 | Val Acc 0.490909 | Val RMSE 0.873863 | 0.70s
Epoch 17/20 | Train Loss 1.367468 | Val Loss 2.922596 | Val CCC 0.344267 | Val Acc 0.454545 | Val RMSE 0.924416 | 0.70s
Epoch 18/20 | Train Loss 1.384745 | Val Loss 3.165199 | Val CCC 0.417478 | Val Acc 0.527273 | Val RMSE 0.884205 | 0.69s
Epoch 19/20 | Train Loss 1.427390 | Val Loss 2.782300 | Val CCC 0.344267 | Val Acc 0.454545 | Val RMSE 0.924416 | 0.70s
Epoch 20/20 | Train Loss 1.290831 | Val Loss 2.855014 | Val CCC 0.306065 | Val Acc 0.418182 | Val RMSE 0.943880 | 0.70s
====================================================================================================
训练完成：Seed=100，Q1
最佳Val Loss：2.486881，Epoch=4
最佳Val CCC：0.417478，Epoch=18
====================================================================================================
文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q2_PHQ_8Depressed/seed_100/best_loss.pt
语音Best Loss： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_100/question_2/best_loss.pt
文本保存Epoch： 8
语音保存Epoch： 43
文本缺少参数： []
文本多余参数： []
语音缺少参数： []
语音多余参数： []
====================================================================================================
开始训练：Seed=100，Q2，PHQ_8Depressed
类别数量： [68, 63, 18, 14]
ImbOLL权重： [1.548243761062622, 1.6085091829299927, 3.009244918823242, 3.412163257598877]
====================================================================================================
Epoch 01/20 | Train Loss 2.304007 | Val Loss 2.149198 | Val CCC 0.335998 | Val Acc 0.509091 | Val RMSE 0.972345 | 0.78s
Epoch 02/20 | Train Loss 1.734993 | Val Loss 1.958168 | Val CCC 0.484996 | Val Acc 0.509091 | Val RMSE 0.842075 | 0.75s
Epoch 03/20 | Train Loss 1.837764 | Val Loss 1.975513 | Val CCC 0.476280 | Val Acc 0.509091 | Val RMSE 0.904534 | 0.71s
Epoch 04/20 | Train Loss 1.662867 | Val Loss 2.124657 | Val CCC 0.461402 | Val Acc 0.545455 | Val RMSE 0.924416 | 0.70s
Epoch 05/20 | Train Loss 1.671721 | Val Loss 1.974808 | Val CCC 0.468618 | Val Acc 0.436364 | Val RMSE 0.820200 | 0.70s
Epoch 06/20 | Train Loss 1.671267 | Val Loss 1.971059 | Val CCC 0.515920 | Val Acc 0.545455 | Val RMSE 0.873863 | 0.70s
Epoch 07/20 | Train Loss 1.571735 | Val Loss 1.925965 | Val CCC 0.467321 | Val Acc 0.490909 | Val RMSE 0.852803 | 0.70s
Epoch 08/20 | Train Loss 1.589908 | Val Loss 1.934015 | Val CCC 0.479371 | Val Acc 0.509091 | Val RMSE 0.924416 | 0.71s
Epoch 09/20 | Train Loss 1.664243 | Val Loss 2.092587 | Val CCC 0.479473 | Val Acc 0.527273 | Val RMSE 0.962950 | 0.70s
Epoch 10/20 | Train Loss 1.703864 | Val Loss 2.058362 | Val CCC 0.393701 | Val Acc 0.418182 | Val RMSE 0.953463 | 0.69s
Epoch 11/20 | Train Loss 1.632645 | Val Loss 1.947862 | Val CCC 0.363957 | Val Acc 0.490909 | Val RMSE 0.934199 | 0.68s
Epoch 12/20 | Train Loss 1.690679 | Val Loss 1.982267 | Val CCC 0.468981 | Val Acc 0.527273 | Val RMSE 0.943880 | 0.70s
Epoch 13/20 | Train Loss 1.606988 | Val Loss 2.001731 | Val CCC 0.405584 | Val Acc 0.400000 | Val RMSE 0.842075 | 0.69s
Epoch 14/20 | Train Loss 1.727653 | Val Loss 1.913265 | Val CCC 0.477365 | Val Acc 0.527273 | Val RMSE 0.884205 | 0.69s
Epoch 15/20 | Train Loss 1.654513 | Val Loss 1.987707 | Val CCC 0.479473 | Val Acc 0.527273 | Val RMSE 0.962950 | 0.69s
Epoch 16/20 | Train Loss 1.588466 | Val Loss 2.065831 | Val CCC 0.406701 | Val Acc 0.400000 | Val RMSE 0.904534 | 0.70s
Epoch 17/20 | Train Loss 1.588519 | Val Loss 1.910024 | Val CCC 0.484996 | Val Acc 0.509091 | Val RMSE 0.842075 | 0.69s
Epoch 18/20 | Train Loss 1.617070 | Val Loss 1.968129 | Val CCC 0.468981 | Val Acc 0.527273 | Val RMSE 0.943880 | 0.70s
Epoch 19/20 | Train Loss 1.615737 | Val Loss 1.960462 | Val CCC 0.500271 | Val Acc 0.509091 | Val RMSE 0.894427 | 0.71s
Epoch 20/20 | Train Loss 1.554562 | Val Loss 1.969791 | Val CCC 0.438782 | Val Acc 0.509091 | Val RMSE 0.953463 | 0.71s
====================================================================================================
训练完成：Seed=100，Q2
最佳Val Loss：1.910024，Epoch=17
最佳Val CCC：0.515920，Epoch=6
====================================================================================================
文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q3_PHQ_8Sleep/seed_100/best_loss.pt
语音Best Loss： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_100/question_3/best_loss.pt
文本保存Epoch： 13
语音保存Epoch： 15
文本缺少参数： []
文本多余参数： []
语音缺少参数： []
语音多余参数： []
====================================================================================================
开始训练：Seed=100，Q3，PHQ_8Sleep
类别数量： [69, 40, 27, 27]
ImbOLL权重： [1.5369837284088135, 2.018662929534912, 2.457038164138794, 2.457038164138794]
====================================================================================================
Epoch 01/20 | Train Loss 2.384868 | Val Loss 2.497796 | Val CCC 0.302095 | Val Acc 0.418182 | Val RMSE 1.228451 | 0.70s
Epoch 02/20 | Train Loss 1.799181 | Val Loss 2.464692 | Val CCC 0.295934 | Val Acc 0.454545 | Val RMSE 1.250454 | 0.71s
Epoch 03/20 | Train Loss 1.937721 | Val Loss 2.216350 | Val CCC 0.314949 | Val Acc 0.418182 | Val RMSE 1.078720 | 0.70s
Epoch 04/20 | Train Loss 1.709770 | Val Loss 2.587689 | Val CCC 0.343170 | Val Acc 0.472727 | Val RMSE 1.190874 | 0.70s
Epoch 05/20 | Train Loss 1.723078 | Val Loss 2.351433 | Val CCC 0.360660 | Val Acc 0.454545 | Val RMSE 1.190874 | 0.70s
Epoch 06/20 | Train Loss 1.728121 | Val Loss 2.346106 | Val CCC 0.379626 | Val Acc 0.472727 | Val RMSE 1.120065 | 0.70s
Epoch 07/20 | Train Loss 1.660191 | Val Loss 2.284790 | Val CCC 0.423018 | Val Acc 0.490909 | Val RMSE 1.111919 | 0.71s
Epoch 08/20 | Train Loss 1.822352 | Val Loss 2.586097 | Val CCC 0.386737 | Val Acc 0.418182 | Val RMSE 1.206045 | 0.73s
Epoch 09/20 | Train Loss 1.771543 | Val Loss 2.396507 | Val CCC 0.327786 | Val Acc 0.436364 | Val RMSE 1.198484 | 0.71s
Epoch 10/20 | Train Loss 1.676348 | Val Loss 2.351502 | Val CCC 0.398658 | Val Acc 0.454545 | Val RMSE 1.190874 | 0.73s
Epoch 11/20 | Train Loss 1.672924 | Val Loss 2.404127 | Val CCC 0.330989 | Val Acc 0.454545 | Val RMSE 1.213560 | 0.77s
Epoch 12/20 | Train Loss 1.631036 | Val Loss 2.861361 | Val CCC 0.381609 | Val Acc 0.381818 | Val RMSE 1.221028 | 0.70s
Epoch 13/20 | Train Loss 1.672357 | Val Loss 2.256698 | Val CCC 0.376207 | Val Acc 0.436364 | Val RMSE 1.111919 | 0.70s
Epoch 14/20 | Train Loss 1.579185 | Val Loss 2.461034 | Val CCC 0.379044 | Val Acc 0.436364 | Val RMSE 1.198484 | 0.70s
Epoch 15/20 | Train Loss 1.569638 | Val Loss 2.430053 | Val CCC 0.351624 | Val Acc 0.454545 | Val RMSE 1.213560 | 0.70s
Epoch 16/20 | Train Loss 1.709929 | Val Loss 2.707107 | Val CCC 0.397718 | Val Acc 0.436364 | Val RMSE 1.221028 | 0.70s
Epoch 17/20 | Train Loss 1.562052 | Val Loss 2.374373 | Val CCC 0.353345 | Val Acc 0.472727 | Val RMSE 1.183216 | 0.71s
Epoch 18/20 | Train Loss 1.626582 | Val Loss 2.573572 | Val CCC 0.260298 | Val Acc 0.418182 | Val RMSE 1.175508 | 0.70s
Epoch 19/20 | Train Loss 1.687918 | Val Loss 2.344100 | Val CCC 0.293651 | Val Acc 0.472727 | Val RMSE 1.314258 | 0.70s
Epoch 20/20 | Train Loss 1.556835 | Val Loss 2.564249 | Val CCC 0.323734 | Val Acc 0.472727 | Val RMSE 1.206045 | 0.69s
====================================================================================================
训练完成：Seed=100，Q3
最佳Val Loss：2.216350，Epoch=3
最佳Val CCC：0.423018，Epoch=7
====================================================================================================
文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q4_PHQ_8Tired/seed_100/best_loss.pt
语音Best Loss： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_100/question_4/best_loss.pt
文本保存Epoch： 8
语音保存Epoch： 47
文本缺少参数： []
文本多余参数： []
语音缺少参数： []
语音多余参数： []
====================================================================================================
开始训练：Seed=100，Q4，PHQ_8Tired
类别数量： [50, 65, 27, 21]
ImbOLL权重： [1.8055469989776611, 1.5835695266723633, 2.457038164138794, 2.7860195636749268]
====================================================================================================
Epoch 01/20 | Train Loss 2.572110 | Val Loss 2.270603 | Val CCC 0.446088 | Val Acc 0.327273 | Val RMSE 0.852803 | 0.70s
Epoch 02/20 | Train Loss 2.047003 | Val Loss 2.262309 | Val CCC 0.376293 | Val Acc 0.381818 | Val RMSE 0.914529 | 0.70s
Epoch 03/20 | Train Loss 2.035218 | Val Loss 2.118673 | Val CCC 0.337860 | Val Acc 0.327273 | Val RMSE 0.884205 | 0.70s
Epoch 04/20 | Train Loss 1.981372 | Val Loss 2.172809 | Val CCC 0.337860 | Val Acc 0.327273 | Val RMSE 0.884205 | 0.71s
Epoch 05/20 | Train Loss 1.926804 | Val Loss 2.177033 | Val CCC 0.412286 | Val Acc 0.381818 | Val RMSE 0.914529 | 0.70s
Epoch 06/20 | Train Loss 2.006398 | Val Loss 2.161907 | Val CCC 0.322238 | Val Acc 0.327273 | Val RMSE 0.884205 | 0.70s
Epoch 07/20 | Train Loss 1.858988 | Val Loss 2.115152 | Val CCC 0.361166 | Val Acc 0.345455 | Val RMSE 0.904534 | 0.70s
Epoch 08/20 | Train Loss 1.931287 | Val Loss 2.143771 | Val CCC 0.464174 | Val Acc 0.363636 | Val RMSE 0.953463 | 0.72s
Epoch 09/20 | Train Loss 1.871158 | Val Loss 2.225135 | Val CCC 0.335471 | Val Acc 0.345455 | Val RMSE 0.873863 | 0.70s
Epoch 10/20 | Train Loss 1.942812 | Val Loss 2.060219 | Val CCC 0.526778 | Val Acc 0.436364 | Val RMSE 0.914529 | 0.70s
Epoch 11/20 | Train Loss 1.946983 | Val Loss 2.192900 | Val CCC 0.319901 | Val Acc 0.363636 | Val RMSE 0.894427 | 0.70s
Epoch 12/20 | Train Loss 1.844748 | Val Loss 2.162859 | Val CCC 0.468029 | Val Acc 0.418182 | Val RMSE 0.981650 | 0.70s
Epoch 13/20 | Train Loss 1.881832 | Val Loss 2.124477 | Val CCC 0.296092 | Val Acc 0.345455 | Val RMSE 0.934199 | 0.70s
Epoch 14/20 | Train Loss 1.843750 | Val Loss 2.100200 | Val CCC 0.441520 | Val Acc 0.400000 | Val RMSE 0.873863 | 0.71s
Epoch 15/20 | Train Loss 1.881320 | Val Loss 2.264626 | Val CCC 0.335471 | Val Acc 0.345455 | Val RMSE 0.873863 | 0.70s
Epoch 16/20 | Train Loss 1.897428 | Val Loss 2.069475 | Val CCC 0.488922 | Val Acc 0.472727 | Val RMSE 0.924416 | 0.70s
Epoch 17/20 | Train Loss 1.916005 | Val Loss 2.234887 | Val CCC 0.346742 | Val Acc 0.327273 | Val RMSE 0.943880 | 0.69s
Epoch 18/20 | Train Loss 1.981185 | Val Loss 2.178306 | Val CCC 0.322238 | Val Acc 0.327273 | Val RMSE 0.884205 | 0.69s
Epoch 19/20 | Train Loss 1.870662 | Val Loss 2.100715 | Val CCC 0.342958 | Val Acc 0.327273 | Val RMSE 0.884205 | 0.69s
Epoch 20/20 | Train Loss 1.865597 | Val Loss 2.139635 | Val CCC 0.423921 | Val Acc 0.381818 | Val RMSE 1.000000 | 0.70s
====================================================================================================
训练完成：Seed=100，Q4
最佳Val Loss：2.060219，Epoch=10
最佳Val CCC：0.526778，Epoch=10
====================================================================================================
文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q5_PHQ_8Appetite/seed_100/best_loss.pt
语音Best Loss： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_100/question_5/best_loss.pt
文本保存Epoch： 11
语音保存Epoch： 7
文本缺少参数： []
文本多余参数： []
语音缺少参数： []
语音多余参数： []
====================================================================================================
开始训练：Seed=100，Q5，PHQ_8Appetite
类别数量： [77, 42, 24, 20]
ImbOLL权重： [1.454951286315918, 1.9700132608413696, 2.6060826778411865, 2.854820728302002]
====================================================================================================
Epoch 01/20 | Train Loss 2.408034 | Val Loss 2.460107 | Val CCC 0.399779 | Val Acc 0.363636 | Val RMSE 1.035725 | 0.69s
Epoch 02/20 | Train Loss 1.906615 | Val Loss 2.321902 | Val CCC 0.368364 | Val Acc 0.400000 | Val RMSE 0.990867 | 0.69s
Epoch 03/20 | Train Loss 1.884831 | Val Loss 2.367302 | Val CCC 0.367653 | Val Acc 0.400000 | Val RMSE 0.962950 | 0.69s
Epoch 04/20 | Train Loss 1.818435 | Val Loss 2.949654 | Val CCC 0.373006 | Val Acc 0.418182 | Val RMSE 1.009050 | 0.69s
Epoch 05/20 | Train Loss 1.781226 | Val Loss 2.534350 | Val CCC 0.390538 | Val Acc 0.436364 | Val RMSE 0.972345 | 0.69s
Epoch 06/20 | Train Loss 1.753590 | Val Loss 2.463456 | Val CCC 0.390538 | Val Acc 0.436364 | Val RMSE 0.972345 | 0.70s
Epoch 07/20 | Train Loss 1.755074 | Val Loss 2.549920 | Val CCC 0.409045 | Val Acc 0.454545 | Val RMSE 0.962950 | 0.68s
Epoch 08/20 | Train Loss 1.720607 | Val Loss 2.742879 | Val CCC 0.386203 | Val Acc 0.418182 | Val RMSE 0.981650 | 0.68s
Epoch 09/20 | Train Loss 1.723962 | Val Loss 2.825568 | Val CCC 0.409045 | Val Acc 0.454545 | Val RMSE 0.962950 | 0.69s
Epoch 10/20 | Train Loss 1.688501 | Val Loss 2.873442 | Val CCC 0.386614 | Val Acc 0.418182 | Val RMSE 0.981650 | 0.69s
Epoch 11/20 | Train Loss 1.679886 | Val Loss 2.294415 | Val CCC 0.386014 | Val Acc 0.418182 | Val RMSE 0.953463 | 0.68s
Epoch 12/20 | Train Loss 1.582732 | Val Loss 2.672797 | Val CCC 0.419815 | Val Acc 0.381818 | Val RMSE 1.120065 | 0.68s
Epoch 13/20 | Train Loss 1.685753 | Val Loss 3.323540 | Val CCC 0.423488 | Val Acc 0.418182 | Val RMSE 1.009050 | 0.69s
Epoch 14/20 | Train Loss 1.674090 | Val Loss 2.664791 | Val CCC 0.448965 | Val Acc 0.454545 | Val RMSE 1.009050 | 0.72s
Epoch 15/20 | Train Loss 1.650529 | Val Loss 2.329474 | Val CCC 0.436457 | Val Acc 0.490909 | Val RMSE 0.990867 | 0.69s
Epoch 16/20 | Train Loss 1.774857 | Val Loss 3.376481 | Val CCC 0.425052 | Val Acc 0.472727 | Val RMSE 1.103713 | 0.70s
Epoch 17/20 | Train Loss 1.608691 | Val Loss 3.249103 | Val CCC 0.456688 | Val Acc 0.472727 | Val RMSE 1.053134 | 0.70s
Epoch 18/20 | Train Loss 1.737078 | Val Loss 2.974497 | Val CCC 0.437966 | Val Acc 0.472727 | Val RMSE 1.053134 | 0.70s
Epoch 19/20 | Train Loss 1.661054 | Val Loss 2.648811 | Val CCC 0.448315 | Val Acc 0.454545 | Val RMSE 1.009050 | 0.70s
Epoch 20/20 | Train Loss 1.543035 | Val Loss 2.616972 | Val CCC 0.438254 | Val Acc 0.454545 | Val RMSE 1.009050 | 0.69s
====================================================================================================
训练完成：Seed=100，Q5
最佳Val Loss：2.294415，Epoch=11
最佳Val CCC：0.456688，Epoch=17
====================================================================================================
文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q6_PHQ_8Failure/seed_100/best_loss.pt
语音Best Loss： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_100/question_6/best_loss.pt
文本保存Epoch： 13
语音保存Epoch： 47
文本缺少参数： []
文本多余参数： []
语音缺少参数： []
语音多余参数： []
====================================================================================================
开始训练：Seed=100，Q6，PHQ_8Failure
类别数量： [76, 44, 24, 19]
ImbOLL权重： [1.4644919633865356, 1.9247195720672607, 2.6060826778411865, 2.9289839267730713]
====================================================================================================
Epoch 01/20 | Train Loss 2.339037 | Val Loss 2.417332 | Val CCC 0.236897 | Val Acc 0.418182 | Val RMSE 1.120065 | 0.70s
Epoch 02/20 | Train Loss 1.789659 | Val Loss 2.207105 | Val CCC 0.340127 | Val Acc 0.381818 | Val RMSE 1.070259 | 0.71s
Epoch 03/20 | Train Loss 1.660305 | Val Loss 2.173389 | Val CCC 0.277538 | Val Acc 0.363636 | Val RMSE 1.053134 | 0.70s
Epoch 04/20 | Train Loss 1.473088 | Val Loss 2.122134 | Val CCC 0.374884 | Val Acc 0.472727 | Val RMSE 1.000000 | 0.70s
Epoch 05/20 | Train Loss 1.483983 | Val Loss 2.112047 | Val CCC 0.440976 | Val Acc 0.509091 | Val RMSE 0.904534 | 0.70s
Epoch 06/20 | Train Loss 1.457483 | Val Loss 2.353563 | Val CCC 0.291644 | Val Acc 0.436364 | Val RMSE 1.070259 | 0.71s
Epoch 07/20 | Train Loss 1.472573 | Val Loss 2.161888 | Val CCC 0.392744 | Val Acc 0.454545 | Val RMSE 1.009050 | 0.70s
Epoch 08/20 | Train Loss 1.496234 | Val Loss 2.165852 | Val CCC 0.367983 | Val Acc 0.436364 | Val RMSE 0.914529 | 0.70s
Epoch 09/20 | Train Loss 1.397506 | Val Loss 2.137788 | Val CCC 0.326944 | Val Acc 0.454545 | Val RMSE 1.009050 | 0.70s
Epoch 10/20 | Train Loss 1.411636 | Val Loss 2.145600 | Val CCC 0.394098 | Val Acc 0.472727 | Val RMSE 0.981650 | 0.73s
Epoch 11/20 | Train Loss 1.281208 | Val Loss 2.208013 | Val CCC 0.342408 | Val Acc 0.418182 | Val RMSE 0.924416 | 0.71s
Epoch 12/20 | Train Loss 1.362006 | Val Loss 2.180818 | Val CCC 0.389666 | Val Acc 0.418182 | Val RMSE 1.009050 | 0.71s
Epoch 13/20 | Train Loss 1.298561 | Val Loss 2.405664 | Val CCC 0.311946 | Val Acc 0.436364 | Val RMSE 1.044466 | 0.71s
Epoch 14/20 | Train Loss 1.370382 | Val Loss 2.166668 | Val CCC 0.344146 | Val Acc 0.381818 | Val RMSE 1.053134 | 0.71s
Epoch 15/20 | Train Loss 1.370002 | Val Loss 2.157007 | Val CCC 0.363932 | Val Acc 0.436364 | Val RMSE 0.972345 | 0.71s
Epoch 16/20 | Train Loss 1.494613 | Val Loss 2.259172 | Val CCC 0.385694 | Val Acc 0.418182 | Val RMSE 1.035725 | 0.71s
Epoch 17/20 | Train Loss 1.256644 | Val Loss 2.676886 | Val CCC 0.324158 | Val Acc 0.472727 | Val RMSE 1.078720 | 0.70s
Epoch 18/20 | Train Loss 1.642407 | Val Loss 2.186012 | Val CCC 0.354135 | Val Acc 0.400000 | Val RMSE 0.962950 | 0.71s
Epoch 19/20 | Train Loss 1.472592 | Val Loss 2.208611 | Val CCC 0.366132 | Val Acc 0.418182 | Val RMSE 1.035725 | 0.71s
Epoch 20/20 | Train Loss 1.256626 | Val Loss 2.256641 | Val CCC 0.336809 | Val Acc 0.454545 | Val RMSE 1.035725 | 0.71s
====================================================================================================
训练完成：Seed=100，Q6
最佳Val Loss：2.112047，Epoch=5
最佳Val CCC：0.440976，Epoch=5
====================================================================================================
文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q7_PHQ_8Concentrating/seed_100/best_loss.pt
语音Best Loss： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_100/question_7/best_loss.pt
文本保存Epoch： 12
语音保存Epoch： 4
文本缺少参数： []
文本多余参数： []
语音缺少参数： []

,Seed,Question_Index,Question_Number,Question_Name,Best_Val_Loss,Best_Loss_Epoch,Best_Val_CCC,Best_CCC_Epoch,Best_Loss_Path,Best_CCC_Path
0,100,0,1,PHQ_8NoInterest,2.486881,4,0.417478,18,/workspace/E-DAIC/checkpoints/phq8_text_audio_...,/workspace/E-DAIC/checkpoints/phq8_text_audio_...
1,100,1,2,PHQ_8Depressed,1.910024,17,0.515920,6,/workspace/E-DAIC/checkpoints/phq8_text_audio_...,/workspace/E-DAIC/checkpoints/phq8_text_audio_...
2,100,2,3,PHQ_8Sleep,2.216350,3,0.423018,7,/workspace/E-DAIC/checkpoints/phq8_text_audio_...,/workspace/E-DAIC/checkpoints/phq8_text_audio_...
3,100,3,4,PHQ_8Tired,2.060219,10,0.526778,10,/workspace/E-DAIC/checkpoints/phq8_text_audio_...,/workspace/E-DAIC/checkpoints/phq8_text_audio_...
4,100,4,5,PHQ_8Appetite,2.294415,11,0.456688,17,/workspace/E-DAIC/checkpoints/phq8_text_audio_...,/workspace/E-DAIC/checkpoints/phq8_text_audio_...
5,100,5,6,PHQ_8Failure,2.112047,5,0.440976,5,/workspace/E-DAIC/checkpoints/phq8_text_audio_...,/workspace/E-DAIC/checkpoints/phq8_text_audio_...
6,100,6,7,PHQ_8Concentrating,2.032676,19,0.488424,18,/workspace/E-DAIC/checkpoints/phq8_text_audio_...,/workspace/E-DAIC/checkpoints/phq8_text_audio_...
7,100,7,8,PHQ_8Moving,2.263026,7,0.296571,20,/workspace/E-DAIC/checkpoints/phq8_text_audio_...,/workspace/E-DAIC/checkpoints/phq8_text_audio_...

In [270]:
seed1234_fusion_results, seed1234_fusion_summary_df = train_all_fusion_questions_for_seed(seed=1234)
display(seed1234_fusion_summary_df)

文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q1_PHQ_8NoInterest/seed_1234/best_loss.pt
语音Best Loss： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_1234/question_1/best_loss.pt
文本保存Epoch： 7
语音保存Epoch： 18
文本缺少参数： []
文本多余参数： []
语音缺少参数： []
语音多余参数： []
====================================================================================================
开始训练：Seed=1234，Q1，PHQ_8NoInterest
类别数量： [81, 57, 20, 5]
ImbOLL权重： [1.4185717105865479, 1.6910496950149536, 2.854820728302002, 5.709641456604004]
====================================================================================================
Epoch 01/20 | Train Loss 2.162262 | Val Loss 2.525034 | Val CCC 0.175429 | Val Acc 0.527273 | Val RMSE 0.990867 | 0.72s
Epoch 02/20 | Train Loss 1.636145 | Val Loss 3.339831 | Val CCC 0.282505 | Val Acc 0.472727 | Val RMSE 0.990867 | 0.73s
Epoch 03/20 | Train Loss 1.572229 | Val Loss 2.419742 | Val CCC 0.351554 | Val Acc 0.509091 | Val RMSE 0.894427 | 0.73s
Epoch 04/20 | Train Loss 1.515764 | Val Loss 2.677899 | Val CCC 0.406869 | Val Acc 0.527273 | Val RMSE 0.884205 | 0.72s
Epoch 05/20 | Train Loss 1.440375 | Val Loss 2.567060 | Val CCC 0.425187 | Val Acc 0.509091 | Val RMSE 0.863397 | 0.72s
Epoch 06/20 | Train Loss 1.473521 | Val Loss 2.755274 | Val CCC 0.294413 | Val Acc 0.563636 | Val RMSE 0.924416 | 0.73s
Epoch 07/20 | Train Loss 1.424881 | Val Loss 2.506590 | Val CCC 0.255028 | Val Acc 0.472727 | Val RMSE 0.914529 | 0.74s
Epoch 08/20 | Train Loss 1.488196 | Val Loss 2.532822 | Val CCC 0.433561 | Val Acc 0.509091 | Val RMSE 0.863397 | 0.71s
Epoch 09/20 | Train Loss 1.436843 | Val Loss 2.576082 | Val CCC 0.291920 | Val Acc 0.545455 | Val RMSE 0.904534 | 0.77s
Epoch 10/20 | Train Loss 1.506828 | Val Loss 2.525961 | Val CCC 0.425187 | Val Acc 0.509091 | Val RMSE 0.863397 | 0.72s
Epoch 11/20 | Train Loss 1.562418 | Val Loss 2.549418 | Val CCC 0.399718 | Val Acc 0.545455 | Val RMSE 0.873863 | 0.72s
Epoch 12/20 | Train Loss 1.452425 | Val Loss 2.845335 | Val CCC 0.343766 | Val Acc 0.490909 | Val RMSE 0.934199 | 0.73s
Epoch 13/20 | Train Loss 1.471891 | Val Loss 2.486420 | Val CCC 0.351554 | Val Acc 0.509091 | Val RMSE 0.894427 | 0.72s
Epoch 14/20 | Train Loss 1.376837 | Val Loss 2.666744 | Val CCC 0.399718 | Val Acc 0.545455 | Val RMSE 0.873863 | 0.73s
Epoch 15/20 | Train Loss 1.540627 | Val Loss 2.620433 | Val CCC 0.451380 | Val Acc 0.527273 | Val RMSE 0.852803 | 0.71s
Epoch 16/20 | Train Loss 1.443254 | Val Loss 2.500441 | Val CCC 0.433561 | Val Acc 0.509091 | Val RMSE 0.863397 | 0.71s
Epoch 17/20 | Train Loss 1.405663 | Val Loss 2.633121 | Val CCC 0.399718 | Val Acc 0.545455 | Val RMSE 0.873863 | 0.71s
Epoch 18/20 | Train Loss 1.423954 | Val Loss 2.793558 | Val CCC 0.282505 | Val Acc 0.472727 | Val RMSE 0.990867 | 0.73s
Epoch 19/20 | Train Loss 1.428776 | Val Loss 2.504176 | Val CCC 0.370120 | Val Acc 0.509091 | Val RMSE 0.894427 | 0.72s
Epoch 20/20 | Train Loss 1.492774 | Val Loss 2.430789 | Val CCC 0.308674 | Val Acc 0.454545 | Val RMSE 0.894427 | 0.71s
====================================================================================================
训练完成：Seed=1234，Q1
最佳Val Loss：2.419742，Epoch=3
最佳Val CCC：0.451380，Epoch=15
====================================================================================================
文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q2_PHQ_8Depressed/seed_1234/best_loss.pt
语音Best Loss： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_1234/question_2/best_loss.pt
文本保存Epoch： 12
语音保存Epoch： 11
文本缺少参数： []
文本多余参数： []
语音缺少参数： []
语音多余参数： []
====================================================================================================
开始训练：Seed=1234，Q2，PHQ_8Depressed
类别数量： [68, 63, 18, 14]
ImbOLL权重： [1.548243761062622, 1.6085091829299927, 3.009244918823242, 3.412163257598877]
====================================================================================================
Epoch 01/20 | Train Loss 2.331421 | Val Loss 2.188676 | Val CCC 0.413891 | Val Acc 0.527273 | Val RMSE 0.962950 | 0.79s
Epoch 02/20 | Train Loss 1.744628 | Val Loss 2.283653 | Val CCC 0.499531 | Val Acc 0.581818 | Val RMSE 0.852803 | 0.79s
Epoch 03/20 | Train Loss 1.560232 | Val Loss 1.943988 | Val CCC 0.488002 | Val Acc 0.509091 | Val RMSE 0.873863 | 0.75s
Epoch 04/20 | Train Loss 1.485523 | Val Loss 2.055882 | Val CCC 0.492756 | Val Acc 0.527273 | Val RMSE 0.797724 | 0.70s
Epoch 05/20 | Train Loss 1.517468 | Val Loss 1.963323 | Val CCC 0.439497 | Val Acc 0.490909 | Val RMSE 0.934199 | 0.71s
Epoch 06/20 | Train Loss 1.393613 | Val Loss 2.653039 | Val CCC 0.506875 | Val Acc 0.563636 | Val RMSE 0.894427 | 0.70s
Epoch 07/20 | Train Loss 1.460910 | Val Loss 1.916883 | Val CCC 0.519483 | Val Acc 0.545455 | Val RMSE 0.820200 | 0.72s
Epoch 08/20 | Train Loss 1.485005 | Val Loss 1.977654 | Val CCC 0.540718 | Val Acc 0.545455 | Val RMSE 0.852803 | 0.69s
Epoch 09/20 | Train Loss 1.395552 | Val Loss 2.141112 | Val CCC 0.467830 | Val Acc 0.545455 | Val RMSE 0.904534 | 0.69s
Epoch 10/20 | Train Loss 1.497957 | Val Loss 1.943275 | Val CCC 0.520590 | Val Acc 0.563636 | Val RMSE 0.809040 | 0.70s
Epoch 11/20 | Train Loss 1.386199 | Val Loss 1.999888 | Val CCC 0.450656 | Val Acc 0.527273 | Val RMSE 0.884205 | 0.69s
Epoch 12/20 | Train Loss 1.396825 | Val Loss 2.243543 | Val CCC 0.447623 | Val Acc 0.527273 | Val RMSE 0.884205 | 0.70s
Epoch 13/20 | Train Loss 1.363703 | Val Loss 2.039300 | Val CCC 0.416771 | Val Acc 0.527273 | Val RMSE 0.884205 | 0.70s
Epoch 14/20 | Train Loss 1.268197 | Val Loss 2.150285 | Val CCC 0.386659 | Val Acc 0.472727 | Val RMSE 0.884205 | 0.70s
Epoch 15/20 | Train Loss 1.379835 | Val Loss 2.068241 | Val CCC 0.400165 | Val Acc 0.490909 | Val RMSE 0.934199 | 0.66s
Epoch 16/20 | Train Loss 1.453316 | Val Loss 2.289919 | Val CCC 0.468236 | Val Acc 0.527273 | Val RMSE 0.914529 | 0.66s
Epoch 17/20 | Train Loss 1.236526 | Val Loss 2.172418 | Val CCC 0.386659 | Val Acc 0.472727 | Val RMSE 0.884205 | 0.67s
Epoch 18/20 | Train Loss 1.244901 | Val Loss 2.051568 | Val CCC 0.467368 | Val Acc 0.527273 | Val RMSE 0.914529 | 0.70s
Epoch 19/20 | Train Loss 1.382725 | Val Loss 2.711779 | Val CCC 0.239016 | Val Acc 0.418182 | Val RMSE 0.894427 | 0.70s
Epoch 20/20 | Train Loss 1.350246 | Val Loss 2.136236 | Val CCC 0.456994 | Val Acc 0.527273 | Val RMSE 0.884205 | 0.75s
====================================================================================================
训练完成：Seed=1234，Q2
最佳Val Loss：1.916883，Epoch=7
最佳Val CCC：0.540718，Epoch=8
====================================================================================================
文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q3_PHQ_8Sleep/seed_1234/best_loss.pt
语音Best Loss： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_1234/question_3/best_loss.pt
文本保存Epoch： 7
语音保存Epoch： 14
文本缺少参数： []
文本多余参数： []
语音缺少参数： []
语音多余参数： []
====================================================================================================
开始训练：Seed=1234，Q3，PHQ_8Sleep
类别数量： [69, 40, 27, 27]
ImbOLL权重： [1.5369837284088135, 2.018662929534912, 2.457038164138794, 2.457038164138794]
====================================================================================================
Epoch 01/20 | Train Loss 2.618719 | Val Loss 2.359414 | Val CCC 0.236303 | Val Acc 0.327273 | Val RMSE 1.070259 | 0.70s
Epoch 02/20 | Train Loss 2.061492 | Val Loss 2.374962 | Val CCC 0.370655 | Val Acc 0.363636 | Val RMSE 1.128152 | 0.70s
Epoch 03/20 | Train Loss 2.048543 | Val Loss 2.370894 | Val CCC 0.328507 | Val Acc 0.363636 | Val RMSE 1.159937 | 0.70s
Epoch 04/20 | Train Loss 2.147792 | Val Loss 2.298237 | Val CCC 0.319009 | Val Acc 0.363636 | Val RMSE 1.111919 | 0.72s
Epoch 05/20 | Train Loss 1.936783 | Val Loss 2.369335 | Val CCC 0.358313 | Val Acc 0.400000 | Val RMSE 1.243163 | 0.72s
Epoch 06/20 | Train Loss 1.987664 | Val Loss 2.353448 | Val CCC 0.377142 | Val Acc 0.381818 | Val RMSE 1.257704 | 0.73s
Epoch 07/20 | Train Loss 1.923412 | Val Loss 2.224471 | Val CCC 0.378530 | Val Acc 0.400000 | Val RMSE 1.103713 | 0.71s
Epoch 08/20 | Train Loss 1.928176 | Val Loss 2.257199 | Val CCC 0.370347 | Val Acc 0.400000 | Val RMSE 1.144155 | 0.70s
Epoch 09/20 | Train Loss 1.938439 | Val Loss 2.258416 | Val CCC 0.409891 | Val Acc 0.418182 | Val RMSE 1.120065 | 0.71s
Epoch 10/20 | Train Loss 1.864713 | Val Loss 2.273296 | Val CCC 0.432341 | Val Acc 0.381818 | Val RMSE 1.136182 | 0.70s
Epoch 11/20 | Train Loss 1.920257 | Val Loss 2.256924 | Val CCC 0.441932 | Val Acc 0.381818 | Val RMSE 1.136182 | 0.71s
Epoch 12/20 | Train Loss 1.879021 | Val Loss 2.208273 | Val CCC 0.361526 | Val Acc 0.400000 | Val RMSE 1.053134 | 0.71s
Epoch 13/20 | Train Loss 1.886776 | Val Loss 2.288327 | Val CCC 0.422027 | Val Acc 0.381818 | Val RMSE 1.183216 | 0.70s
Epoch 14/20 | Train Loss 1.836333 | Val Loss 2.231137 | Val CCC 0.363655 | Val Acc 0.363636 | Val RMSE 1.144155 | 0.70s
Epoch 15/20 | Train Loss 1.912682 | Val Loss 2.308080 | Val CCC 0.411888 | Val Acc 0.381818 | Val RMSE 1.183216 | 0.70s
Epoch 16/20 | Train Loss 1.926404 | Val Loss 2.276582 | Val CCC 0.397472 | Val Acc 0.381818 | Val RMSE 1.136182 | 0.70s
Epoch 17/20 | Train Loss 1.882929 | Val Loss 2.326925 | Val CCC 0.362888 | Val Acc 0.381818 | Val RMSE 1.206045 | 0.70s
Epoch 18/20 | Train Loss 1.860594 | Val Loss 2.362565 | Val CCC 0.419114 | Val Acc 0.418182 | Val RMSE 1.198484 | 0.70s
Epoch 19/20 | Train Loss 1.917834 | Val Loss 2.232457 | Val CCC 0.401196 | Val Acc 0.400000 | Val RMSE 1.078720 | 0.69s
Epoch 20/20 | Train Loss 1.880491 | Val Loss 2.326114 | Val CCC 0.369629 | Val Acc 0.418182 | Val RMSE 1.213560 | 0.71s
====================================================================================================
训练完成：Seed=1234，Q3
最佳Val Loss：2.208273，Epoch=12
最佳Val CCC：0.441932，Epoch=11
====================================================================================================
文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q4_PHQ_8Tired/seed_1234/best_loss.pt
语音Best Loss： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_1234/question_4/best_loss.pt
文本保存Epoch： 8
语音保存Epoch： 31
文本缺少参数： []
文本多余参数： []
语音缺少参数： []
语音多余参数： []
====================================================================================================
开始训练：Seed=1234，Q4，PHQ_8Tired
类别数量： [50, 65, 27, 21]
ImbOLL权重： [1.8055469989776611, 1.5835695266723633, 2.457038164138794, 2.7860195636749268]
====================================================================================================
Epoch 01/20 | Train Loss 2.583878 | Val Loss 2.271742 | Val CCC 0.367103 | Val Acc 0.327273 | Val RMSE 0.884205 | 0.70s
Epoch 02/20 | Train Loss 2.088359 | Val Loss 2.400507 | Val CCC 0.520995 | Val Acc 0.418182 | Val RMSE 0.953463 | 0.69s
Epoch 03/20 | Train Loss 1.907679 | Val Loss 2.240359 | Val CCC 0.372067 | Val Acc 0.309091 | Val RMSE 1.035725 | 0.69s
Epoch 04/20 | Train Loss 2.004643 | Val Loss 2.160751 | Val CCC 0.459546 | Val Acc 0.309091 | Val RMSE 0.924416 | 0.73s
Epoch 05/20 | Train Loss 1.858413 | Val Loss 2.143996 | Val CCC 0.366551 | Val Acc 0.345455 | Val RMSE 1.018019 | 0.70s
Epoch 06/20 | Train Loss 1.964012 | Val Loss 2.104513 | Val CCC 0.472412 | Val Acc 0.363636 | Val RMSE 0.981650 | 0.69s
Epoch 07/20 | Train Loss 1.836637 | Val Loss 2.173712 | Val CCC 0.296375 | Val Acc 0.290909 | Val RMSE 0.934199 | 0.69s
Epoch 08/20 | Train Loss 1.858679 | Val Loss 2.308880 | Val CCC 0.330667 | Val Acc 0.272727 | Val RMSE 0.972345 | 0.69s
Epoch 09/20 | Train Loss 1.835598 | Val Loss 2.171209 | Val CCC 0.438147 | Val Acc 0.400000 | Val RMSE 1.044466 | 0.69s
Epoch 10/20 | Train Loss 1.886066 | Val Loss 2.203650 | Val CCC 0.367103 | Val Acc 0.327273 | Val RMSE 0.884205 | 0.69s
Epoch 11/20 | Train Loss 1.882657 | Val Loss 2.201767 | Val CCC 0.414934 | Val Acc 0.418182 | Val RMSE 1.053134 | 0.69s
Epoch 12/20 | Train Loss 1.971620 | Val Loss 2.094325 | Val CCC 0.489164 | Val Acc 0.345455 | Val RMSE 0.873863 | 0.70s
Epoch 13/20 | Train Loss 1.913415 | Val Loss 2.154935 | Val CCC 0.367507 | Val Acc 0.327273 | Val RMSE 0.914529 | 0.70s
Epoch 14/20 | Train Loss 1.905276 | Val Loss 2.091805 | Val CCC 0.474378 | Val Acc 0.363636 | Val RMSE 0.894427 | 0.70s
Epoch 15/20 | Train Loss 1.927323 | Val Loss 2.114495 | Val CCC 0.450485 | Val Acc 0.327273 | Val RMSE 0.914529 | 0.72s
Epoch 16/20 | Train Loss 1.821720 | Val Loss 2.132378 | Val CCC 0.423104 | Val Acc 0.290909 | Val RMSE 0.934199 | 0.70s
Epoch 17/20 | Train Loss 1.778920 | Val Loss 2.202767 | Val CCC 0.399326 | Val Acc 0.363636 | Val RMSE 0.953463 | 0.71s
Epoch 18/20 | Train Loss 1.860952 | Val Loss 2.204224 | Val CCC 0.473469 | Val Acc 0.327273 | Val RMSE 1.000000 | 0.71s
Epoch 19/20 | Train Loss 1.783493 | Val Loss 2.312685 | Val CCC 0.434263 | Val Acc 0.327273 | Val RMSE 0.852803 | 0.71s
Epoch 20/20 | Train Loss 1.889507 | Val Loss 2.166928 | Val CCC 0.458307 | Val Acc 0.327273 | Val RMSE 0.943880 | 0.70s
====================================================================================================
训练完成：Seed=1234，Q4
最佳Val Loss：2.091805，Epoch=14
最佳Val CCC：0.520995，Epoch=2
====================================================================================================
文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q5_PHQ_8Appetite/seed_1234/best_loss.pt
语音Best Loss： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_1234/question_5/best_loss.pt
文本保存Epoch： 16
语音保存Epoch： 22
文本缺少参数： []
文本多余参数： []
语音缺少参数： []
语音多余参数： []
====================================================================================================
开始训练：Seed=1234，Q5，PHQ_8Appetite
类别数量： [77, 42, 24, 20]
ImbOLL权重： [1.454951286315918, 1.9700132608413696, 2.6060826778411865, 2.854820728302002]
====================================================================================================
Epoch 01/20 | Train Loss 2.906919 | Val Loss 2.244243 | Val CCC 0.219718 | Val Acc 0.345455 | Val RMSE 1.044466 | 0.70s
Epoch 02/20 | Train Loss 1.908740 | Val Loss 2.550346 | Val CCC 0.339355 | Val Acc 0.327273 | Val RMSE 1.053134 | 0.70s
Epoch 03/20 | Train Loss 1.714283 | Val Loss 2.563861 | Val CCC 0.448145 | Val Acc 0.327273 | Val RMSE 1.053134 | 0.70s
Epoch 04/20 | Train Loss 1.935074 | Val Loss 2.234225 | Val CCC 0.434830 | Val Acc 0.436364 | Val RMSE 0.914529 | 0.70s
Epoch 05/20 | Train Loss 1.767329 | Val Loss 2.289950 | Val CCC 0.433367 | Val Acc 0.345455 | Val RMSE 1.018019 | 0.69s
Epoch 06/20 | Train Loss 1.732202 | Val Loss 2.578161 | Val CCC 0.448669 | Val Acc 0.418182 | Val RMSE 1.026911 | 0.70s
Epoch 07/20 | Train Loss 1.652547 | Val Loss 2.078989 | Val CCC 0.399688 | Val Acc 0.400000 | Val RMSE 0.873863 | 0.70s
Epoch 08/20 | Train Loss 1.794441 | Val Loss 2.221579 | Val CCC 0.391359 | Val Acc 0.381818 | Val RMSE 0.972345 | 0.69s
Epoch 09/20 | Train Loss 1.792643 | Val Loss 2.353357 | Val CCC 0.439137 | Val Acc 0.418182 | Val RMSE 0.953463 | 0.72s
Epoch 10/20 | Train Loss 1.737755 | Val Loss 2.214786 | Val CCC 0.355635 | Val Acc 0.345455 | Val RMSE 1.018019 | 0.70s
Epoch 11/20 | Train Loss 1.627622 | Val Loss 2.580187 | Val CCC 0.506414 | Val Acc 0.454545 | Val RMSE 0.934199 | 0.70s
Epoch 12/20 | Train Loss 1.926217 | Val Loss 2.010600 | Val CCC 0.412087 | Val Acc 0.436364 | Val RMSE 0.852803 | 0.70s
Epoch 13/20 | Train Loss 1.698570 | Val Loss 2.543601 | Val CCC 0.399254 | Val Acc 0.363636 | Val RMSE 1.009050 | 0.71s
Epoch 14/20 | Train Loss 1.665746 | Val Loss 2.309396 | Val CCC 0.455547 | Val Acc 0.381818 | Val RMSE 0.972345 | 0.71s
Epoch 15/20 | Train Loss 1.626457 | Val Loss 2.026016 | Val CCC 0.551726 | Val Acc 0.454545 | Val RMSE 0.842075 | 0.71s
Epoch 16/20 | Train Loss 1.622724 | Val Loss 2.182572 | Val CCC 0.364468 | Val Acc 0.436364 | Val RMSE 0.972345 | 0.74s
Epoch 17/20 | Train Loss 1.656604 | Val Loss 2.636428 | Val CCC 0.438466 | Val Acc 0.381818 | Val RMSE 1.026911 | 0.73s
Epoch 18/20 | Train Loss 1.643456 | Val Loss 2.410766 | Val CCC 0.492566 | Val Acc 0.381818 | Val RMSE 1.000000 | 0.78s
Epoch 19/20 | Train Loss 1.509398 | Val Loss 2.079298 | Val CCC 0.505593 | Val Acc 0.472727 | Val RMSE 0.863397 | 0.72s
Epoch 20/20 | Train Loss 1.566928 | Val Loss 2.125534 | Val CCC 0.459514 | Val Acc 0.381818 | Val RMSE 0.943880 | 0.72s
====================================================================================================
训练完成：Seed=1234，Q5
最佳Val Loss：2.010600，Epoch=12
最佳Val CCC：0.551726，Epoch=15
====================================================================================================
文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q6_PHQ_8Failure/seed_1234/best_loss.pt
语音Best Loss： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_1234/question_6/best_loss.pt
文本保存Epoch： 10
语音保存Epoch： 48
文本缺少参数： []
文本多余参数： []
语音缺少参数： []
语音多余参数： []
====================================================================================================
开始训练：Seed=1234，Q6，PHQ_8Failure
类别数量： [76, 44, 24, 19]
ImbOLL权重： [1.4644919633865356, 1.9247195720672607, 2.6060826778411865, 2.9289839267730713]
====================================================================================================
Epoch 01/20 | Train Loss 2.252155 | Val Loss 2.220760 | Val CCC 0.429467 | Val Acc 0.490909 | Val RMSE 1.144155 | 0.72s
Epoch 02/20 | Train Loss 1.715354 | Val Loss 2.000219 | Val CCC 0.444533 | Val Acc 0.454545 | Val RMSE 0.904534 | 0.70s
Epoch 03/20 | Train Loss 1.646128 | Val Loss 2.087882 | Val CCC 0.440320 | Val Acc 0.490909 | Val RMSE 1.044466 | 0.71s
Epoch 04/20 | Train Loss 1.567697 | Val Loss 2.119040 | Val CCC 0.402430 | Val Acc 0.454545 | Val RMSE 1.061731 | 0.70s
Epoch 05/20 | Train Loss 1.591229 | Val Loss 2.086232 | Val CCC 0.451671 | Val Acc 0.490909 | Val RMSE 1.018019 | 0.70s
Epoch 06/20 | Train Loss 1.547673 | Val Loss 2.165711 | Val CCC 0.443447 | Val Acc 0.472727 | Val RMSE 1.026911 | 0.70s
Epoch 07/20 | Train Loss 1.631683 | Val Loss 2.039851 | Val CCC 0.459010 | Val Acc 0.436364 | Val RMSE 0.943880 | 0.69s
Epoch 08/20 | Train Loss 1.598637 | Val Loss 2.098389 | Val CCC 0.488922 | Val Acc 0.509091 | Val RMSE 0.924416 | 0.70s
Epoch 09/20 | Train Loss 1.519315 | Val Loss 2.076757 | Val CCC 0.446116 | Val Acc 0.472727 | Val RMSE 0.953463 | 0.70s
Epoch 10/20 | Train Loss 1.529302 | Val Loss 2.065284 | Val CCC 0.468916 | Val Acc 0.472727 | Val RMSE 0.924416 | 0.72s
Epoch 11/20 | Train Loss 1.507124 | Val Loss 2.081454 | Val CCC 0.450097 | Val Acc 0.490909 | Val RMSE 0.990867 | 0.70s
Epoch 12/20 | Train Loss 1.585613 | Val Loss 2.107034 | Val CCC 0.433046 | Val Acc 0.472727 | Val RMSE 0.972345 | 0.71s
Epoch 13/20 | Train Loss 1.560653 | Val Loss 2.170816 | Val CCC 0.447418 | Val Acc 0.490909 | Val RMSE 0.990867 | 0.71s
Epoch 14/20 | Train Loss 1.532815 | Val Loss 2.114729 | Val CCC 0.453137 | Val Acc 0.436364 | Val RMSE 1.000000 | 0.70s
Epoch 15/20 | Train Loss 1.605923 | Val Loss 2.097067 | Val CCC 0.408432 | Val Acc 0.436364 | Val RMSE 1.070259 | 0.69s
Epoch 16/20 | Train Loss 1.532550 | Val Loss 2.029122 | Val CCC 0.417722 | Val Acc 0.472727 | Val RMSE 1.000000 | 0.69s
Epoch 17/20 | Train Loss 1.619393 | Val Loss 2.137046 | Val CCC 0.437564 | Val Acc 0.472727 | Val RMSE 1.053134 | 0.69s
Epoch 18/20 | Train Loss 1.540040 | Val Loss 2.109616 | Val CCC 0.447015 | Val Acc 0.472727 | Val RMSE 1.000000 | 0.74s
Epoch 19/20 | Train Loss 1.526303 | Val Loss 2.023623 | Val CCC 0.433561 | Val Acc 0.472727 | Val RMSE 0.953463 | 0.70s
Epoch 20/20 | Train Loss 1.506634 | Val Loss 2.090957 | Val CCC 0.389115 | Val Acc 0.436364 | Val RMSE 1.044466 | 0.70s
====================================================================================================
训练完成：Seed=1234，Q6
最佳Val Loss：2.000219，Epoch=2
最佳Val CCC：0.488922，Epoch=8
====================================================================================================
文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q7_PHQ_8Concentrating/seed_1234/best_loss.pt
语音Best Loss： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_1234/question_7/best_loss.pt
文本保存Epoch： 12
语音保存Epoch： 4

,Seed,Question_Index,Question_Number,Question_Name,Best_Val_Loss,Best_Loss_Epoch,Best_Val_CCC,Best_CCC_Epoch,Best_Loss_Path,Best_CCC_Path
0,1234,0,1,PHQ_8NoInterest,2.419742,3,0.451380,15,/workspace/E-DAIC/checkpoints/phq8_text_audio_...,/workspace/E-DAIC/checkpoints/phq8_text_audio_...
1,1234,1,2,PHQ_8Depressed,1.916883,7,0.540718,8,/workspace/E-DAIC/checkpoints/phq8_text_audio_...,/workspace/E-DAIC/checkpoints/phq8_text_audio_...
2,1234,2,3,PHQ_8Sleep,2.208273,12,0.441932,11,/workspace/E-DAIC/checkpoints/phq8_text_audio_...,/workspace/E-DAIC/checkpoints/phq8_text_audio_...
3,1234,3,4,PHQ_8Tired,2.091805,14,0.520995,2,/workspace/E-DAIC/checkpoints/phq8_text_audio_...,/workspace/E-DAIC/checkpoints/phq8_text_audio_...
4,1234,4,5,PHQ_8Appetite,2.010600,12,0.551726,15,/workspace/E-DAIC/checkpoints/phq8_text_audio_...,/workspace/E-DAIC/checkpoints/phq8_text_audio_...
5,1234,5,6,PHQ_8Failure,2.000219,2,0.488922,8,/workspace/E-DAIC/checkpoints/phq8_text_audio_...,/workspace/E-DAIC/checkpoints/phq8_text_audio_...
6,1234,6,7,PHQ_8Concentrating,2.022529,10,0.507869,9,/workspace/E-DAIC/checkpoints/phq8_text_audio_...,/workspace/E-DAIC/checkpoints/phq8_text_audio_...
7,1234,7,8,PHQ_8Moving,1.793956,19,0.111695,14,/workspace/E-DAIC/checkpoints/phq8_text_audio_...,/workspace/E-DAIC/checkpoints/phq8_text_audio_...

In [200]:
all_fusion_training_results = {42: seed42_fusion_results, 100: seed100_fusion_results, 1234: seed1234_fusion_results}

for seed, seed_results in all_fusion_training_results.items():
    print("=" * 60)
    print("Seed：", seed)
    print("结果数量：", len(seed_results))
    print("Best Loss全部存在：", all(result["best_loss_path"].exists() for result in seed_results))
    print("Best CCC全部存在：", all(result["best_ccc_path"].exists() for result in seed_results))
    print("Last全部存在：", all(result["last_path"].exists() for result in seed_results))
    print("History全部存在：", all(result["history_path"].exists() for result in seed_results))

============================================================
Seed： 42
结果数量： 8
Best Loss全部存在： True
Best CCC全部存在： True
Last全部存在： True
History全部存在： True
============================================================
Seed： 100
结果数量： 8
Best Loss全部存在： True
Best CCC全部存在： True
Last全部存在： True
History全部存在： True
============================================================
Seed： 1234
结果数量： 8
Best Loss全部存在： True
Best CCC全部存在： True
Last全部存在： True
History全部存在： True

In [202]:
seed100_fusion_validation_result = evaluate_fusion_seed_on_validation(seed=100)
seed1234_fusion_validation_result = evaluate_fusion_seed_on_validation(seed=1234)

Checkpoint： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/seed_100/question_1/best_ccc.pt
类型： best_ccc
Epoch： 18
缺少参数： []
多余参数： []
Checkpoint： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/seed_100/question_2/best_ccc.pt
类型： best_ccc
Epoch： 6
缺少参数： []
多余参数： []
Checkpoint： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/seed_100/question_3/best_ccc.pt
类型： best_ccc
Epoch： 7
缺少参数： []
多余参数： []
Checkpoint： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/seed_100/question_4/best_ccc.pt
类型： best_ccc
Epoch： 10
缺少参数： []
多余参数： []
Checkpoint： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/seed_100/question_5/best_ccc.pt
类型： best_ccc
Epoch： 17
缺少参数： []
多余参数： []
Checkpoint： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/seed_100/question_6/best_ccc.pt
类型： best_ccc
Epoch： 5
缺少参数： []
多余参数： []
Checkpoint： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/seed_100/question_7/best_ccc.pt
类型： best_ccc
Epoch： 18
缺少参数： []
多余参数： []
Checkpoint： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/seed_100/question_8/best_ccc.pt
类型： best_ccc
Epoch： 20
缺少参数： []
多余参数： []
Checkpoint： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/seed_1234/question_1/best_ccc.pt
类型： best_ccc
Epoch： 15
缺少参数： []
多余参数： []
Checkpoint： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/seed_1234/question_2/best_ccc.pt
类型： best_ccc
Epoch： 8
缺少参数： []
多余参数： []
Checkpoint： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/seed_1234/question_3/best_ccc.pt
类型： best_ccc
Epoch： 11
缺少参数： []
多余参数： []
Checkpoint： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/seed_1234/question_4/best_ccc.pt
类型： best_ccc
Epoch： 2
缺少参数： []
多余参数： []
Checkpoint： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/seed_1234/question_5/best_ccc.pt
类型： best_ccc
Epoch： 15
缺少参数： []
多余参数： []
Checkpoint： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/seed_1234/question_6/best_ccc.pt
类型： best_ccc
Epoch： 8
缺少参数： []
多余参数： []
Checkpoint： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/seed_1234/question_7/best_ccc.pt
类型： best_ccc
Epoch： 9
缺少参数： []
多余参数： []
Checkpoint： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/seed_1234/question_8/best_ccc.pt
类型： best_ccc
Epoch： 14
缺少参数： []
多余参数： []

In [203]:
fusion_validation_results = [seed42_fusion_validation_result, seed100_fusion_validation_result, seed1234_fusion_validation_result]
fusion_validation_rows = []

for result in fusion_validation_results:
    validation_row = {}
    validation_row["Seed"] = result["seed"]
    validation_row["Sample_Count"] = result["sample_count"]
    validation_row["CCC"] = result["ccc"]
    validation_row["RMSE"] = result["rmse"]
    validation_row["MAE"] = result["mae"]
    validation_row["Exact_Accuracy"] = result["exact_accuracy"]
    validation_row["Predicted_Min"] = result["predicted_min"]
    validation_row["Predicted_Max"] = result["predicted_max"]
    validation_row["True_Min"] = result["true_min"]
    validation_row["True_Max"] = result["true_max"]
    fusion_validation_rows.append(validation_row)

fusion_three_seed_validation_df = pd.DataFrame(fusion_validation_rows)
fusion_three_seed_validation_path = FUSION_CHECKPOINT_ROOT / "three_seed_validation_results.csv"
fusion_three_seed_validation_df.to_csv(fusion_three_seed_validation_path, index=False)

display(fusion_three_seed_validation_df)
print("三Seed验证结果：", fusion_three_seed_validation_path)

,Seed,Sample_Count,CCC,RMSE,MAE,Exact_Accuracy,Predicted_Min,Predicted_Max,True_Min,True_Max
0,42,55,0.700692,4.316986,3.181818,0.090909,0,22,0,20
1,100,55,0.644461,4.767313,3.600000,0.072727,0,20,0,20
2,1234,55,0.636087,4.778741,3.563636,0.163636,0,19,0,20

三Seed验证结果： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/three_seed_validation_results.csv

In [204]:
class TextAudioPHQ8TestDataset(Dataset):
    def __init__(self, metadata_df):
        super().__init__()
        if "Participant_ID" not in metadata_df.columns:
            raise ValueError("测试集缺少Participant_ID列")
        if "PHQ_Score" not in metadata_df.columns:
            raise ValueError("测试集缺少PHQ_Score列")
        self.metadata_df = metadata_df.reset_index(drop=True).copy()
        self.participant_ids = self.metadata_df["Participant_ID"].astype(int).tolist()
        self.total_scores = torch.tensor(self.metadata_df["PHQ_Score"].to_numpy(), dtype=torch.long)
        text_feature_list = []
        text_mask_list = []
        audio_feature_list = []
        audio_mask_list = []
        for index, participant_id in enumerate(self.participant_ids):
            text_features, text_mask, audio_features, audio_mask = load_text_audio_cache(participant_id)
            text_feature_list.append(text_features)
            text_mask_list.append(text_mask)
            audio_feature_list.append(audio_features)
            audio_mask_list.append(audio_mask)
            if (index + 1) % 20 == 0 or index + 1 == len(self.participant_ids):
                print(f"测试缓存加载进度：{index + 1}/{len(self.participant_ids)}")
        self.text_features = torch.stack(text_feature_list, dim=0)
        self.text_masks = torch.stack(text_mask_list, dim=0)
        self.audio_features = torch.stack(audio_feature_list, dim=0)
        self.audio_masks = torch.stack(audio_mask_list, dim=0)
        if self.text_features.shape != (len(self), MAX_TURNS, TEXT_FEATURE_DIM):
            raise RuntimeError(f"测试文本形状错误：{self.text_features.shape}")
        if self.audio_features.shape != (len(self), MAX_TURNS, AUDIO_FEATURE_DIM):
            raise RuntimeError(f"测试语音形状错误：{self.audio_features.shape}")
    def __len__(self):
        return len(self.participant_ids)
    def __getitem__(self, index):
        return self.text_features[index], self.text_masks[index], self.audio_features[index], self.audio_masks[index], self.total_scores[index]

In [205]:
test_fusion_dataset = TextAudioPHQ8TestDataset(test_metadata_df)
test_fusion_loader = DataLoader(test_fusion_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=0, drop_last=False)

test_batch = next(iter(test_fusion_loader))
test_batch_text, test_batch_text_mask, test_batch_audio, test_batch_audio_mask, test_batch_total_scores = test_batch

print("测试样本数：", len(test_fusion_dataset))
print("测试批次数：", len(test_fusion_loader))
print("测试文本形状：", test_batch_text.shape)
print("测试文本Mask形状：", test_batch_text_mask.shape)
print("测试语音形状：", test_batch_audio.shape)
print("测试语音Mask形状：", test_batch_audio_mask.shape)
print("测试总分形状：", test_batch_total_scores.shape)
print("测试真实总分范围：", int(test_fusion_dataset.total_scores.min().item()), "～", int(test_fusion_dataset.total_scores.max().item()))

测试缓存加载进度：20/56
测试缓存加载进度：40/56
测试缓存加载进度：56/56
测试样本数： 56
测试批次数： 6
测试文本形状： torch.Size([10, 120, 768])
测试文本Mask形状： torch.Size([10, 120])
测试语音形状： torch.Size([10, 120, 23])
测试语音Mask形状： torch.Size([10, 120])
测试总分形状： torch.Size([10])
测试真实总分范围： 0 ～ 22

In [206]:
def predict_fusion_question_on_test(model, dataloader):
    model.eval()
    prediction_batches = []
    total_score_batches = []
    with torch.no_grad():
        for batch in dataloader:
            text_features, text_masks, audio_features, audio_masks, total_scores = batch
            text_features = text_features.to(device)
            text_masks = text_masks.to(device)
            audio_features = audio_features.to(device)
            audio_masks = audio_masks.to(device)
            logits = model(text_features, text_masks, audio_features, audio_masks)
            predictions = torch.argmax(logits, dim=1)
            prediction_batches.append(predictions.cpu())
            total_score_batches.append(total_scores.cpu())
    all_predictions = torch.cat(prediction_batches, dim=0)
    all_total_scores = torch.cat(total_score_batches, dim=0)
    return all_predictions, all_total_scores

In [207]:
def evaluate_fusion_seed_on_test(seed):
    question_prediction_columns = []
    reference_total_scores = None
    selected_checkpoint_rows = []
    for question_index in range(8):
        question_number = question_index + 1
        checkpoint_path = FUSION_CHECKPOINT_ROOT / f"seed_{seed}" / f"question_{question_number}" / "best_ccc.pt"
        model, checkpoint = load_fusion_model_from_checkpoint(checkpoint_path)
        if checkpoint["checkpoint_type"] != "best_ccc":
            raise RuntimeError(f"Q{question_number}加载的不是best_ccc")
        if checkpoint["seed"] != seed:
            raise RuntimeError(f"Q{question_number}的Seed不匹配")
        if checkpoint["question_index"] != question_index:
            raise RuntimeError(f"Q{question_number}的题号不匹配")
        predictions, total_scores = predict_fusion_question_on_test(model, test_fusion_loader)
        if reference_total_scores is None:
            reference_total_scores = total_scores
        elif not torch.equal(reference_total_scores, total_scores):
            raise RuntimeError("不同题目读取到的测试标签顺序不一致")
        question_prediction_columns.append(predictions)
        selected_checkpoint_rows.append({"Question_Number": question_number, "Question_Name": PHQ8_QUESTION_COLUMNS[question_index], "Checkpoint_Type": checkpoint["checkpoint_type"], "Checkpoint_Epoch": checkpoint["epoch"], "Validation_CCC": checkpoint["val_metrics"]["ccc"], "Checkpoint_Path": str(checkpoint_path)})
        del model
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
    predicted_question_scores = torch.stack(question_prediction_columns, dim=1)
    predicted_total_scores = predicted_question_scores.sum(dim=1)
    true_total_scores = reference_total_scores.long()
    total_ccc = calculate_sample_ccc(predicted_total_scores.float(), true_total_scores.float()).item()
    total_rmse = torch.sqrt(torch.mean((predicted_total_scores.float() - true_total_scores.float()) ** 2)).item()
    total_mae = torch.mean(torch.abs(predicted_total_scores.float() - true_total_scores.float())).item()
    exact_accuracy = torch.mean((predicted_total_scores == true_total_scores).float()).item()
    prediction_df = pd.DataFrame({"Participant_ID": test_fusion_dataset.participant_ids})
    for question_index in range(8):
        prediction_df[f"Pred_Q{question_index + 1}"] = predicted_question_scores[:, question_index].numpy()
    prediction_df["Predicted_PHQ8_Total"] = predicted_total_scores.numpy()
    prediction_df["True_PHQ8_Total"] = true_total_scores.numpy()
    prediction_df["Error"] = prediction_df["Predicted_PHQ8_Total"] - prediction_df["True_PHQ8_Total"]
    selected_checkpoint_df = pd.DataFrame(selected_checkpoint_rows)
    prediction_path = FUSION_CHECKPOINT_ROOT / f"seed_{seed}_test_predictions_{len(prediction_df)}.csv"
    selected_checkpoint_path = FUSION_CHECKPOINT_ROOT / f"seed_{seed}_test_selected_checkpoints.csv"
    prediction_df.to_csv(prediction_path, index=False)
    selected_checkpoint_df.to_csv(selected_checkpoint_path, index=False)
    result = {"seed": seed, "sample_count": len(prediction_df), "ccc": total_ccc, "rmse": total_rmse, "mae": total_mae, "exact_accuracy": exact_accuracy, "predicted_min": int(predicted_total_scores.min().item()), "predicted_max": int(predicted_total_scores.max().item()), "true_min": int(true_total_scores.min().item()), "true_max": int(true_total_scores.max().item()), "prediction_path": prediction_path, "selected_checkpoint_path": selected_checkpoint_path}
    print("=" * 80)
    print(f"Text + Audio Seed {seed}独立测试结果")
    print("=" * 80)
    print("测试参与者数量：", result["sample_count"])
    print("CCC：", f"{result['ccc']:.6f}")
    print("RMSE：", f"{result['rmse']:.6f}")
    print("MAE：", f"{result['mae']:.6f}")
    print("完全相等比例：", f"{result['exact_accuracy']:.6f}")
    print("预测总分范围：", f"{result['predicted_min']}～{result['predicted_max']}")
    print("真实总分范围：", f"{result['true_min']}～{result['true_max']}")
    print("预测文件：", result["prediction_path"])
    return result

In [208]:
seed42_fusion_test_result = evaluate_fusion_seed_on_test(seed=42)
seed100_fusion_test_result = evaluate_fusion_seed_on_test(seed=100)
seed1234_fusion_test_result = evaluate_fusion_seed_on_test(seed=1234)

Checkpoint： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/seed_42/question_1/best_ccc.pt
类型： best_ccc
Epoch： 12
缺少参数： []
多余参数： []
Checkpoint： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/seed_42/question_2/best_ccc.pt
类型： best_ccc
Epoch： 6
缺少参数： []
多余参数： []
Checkpoint： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/seed_42/question_3/best_ccc.pt
类型： best_ccc
Epoch： 4
缺少参数： []
多余参数： []
Checkpoint： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/seed_42/question_4/best_ccc.pt
类型： best_ccc
Epoch： 4
缺少参数： []
多余参数： []
Checkpoint： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/seed_42/question_5/best_ccc.pt
类型： best_ccc
Epoch： 7
缺少参数： []
多余参数： []
Checkpoint： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/seed_42/question_6/best_ccc.pt
类型： best_ccc
Epoch： 14
缺少参数： []
多余参数： []
Checkpoint： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/seed_42/question_7/best_ccc.pt
类型： best_ccc
Epoch： 8
缺少参数： []
多余参数： []
Checkpoint： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/seed_42/question_8/best_ccc.pt
类型： best_ccc
Epoch： 16
缺少参数： []
多余参数： []
================================================================================
Text + Audio Seed 42独立测试结果
================================================================================
测试参与者数量： 56
CCC： 0.580356
RMSE： 6.209152
MAE： 4.767857
完全相等比例： 0.053571
预测总分范围： 0～23
真实总分范围： 0～22
预测文件： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/seed_42_test_predictions_56.csv
Checkpoint： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/seed_100/question_1/best_ccc.pt
类型： best_ccc
Epoch： 18
缺少参数： []
多余参数： []
Checkpoint： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/seed_100/question_2/best_ccc.pt
类型： best_ccc
Epoch： 6
缺少参数： []
多余参数： []
Checkpoint： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/seed_100/question_3/best_ccc.pt
类型： best_ccc
Epoch： 7
缺少参数： []
多余参数： []
Checkpoint： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/seed_100/question_4/best_ccc.pt
类型： best_ccc
Epoch： 10
缺少参数： []
多余参数： []
Checkpoint： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/seed_100/question_5/best_ccc.pt
类型： best_ccc
Epoch： 17
缺少参数： []
多余参数： []
Checkpoint： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/seed_100/question_6/best_ccc.pt
类型： best_ccc
Epoch： 5
缺少参数： []
多余参数： []
Checkpoint： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/seed_100/question_7/best_ccc.pt
类型： best_ccc
Epoch： 18
缺少参数： []
多余参数： []
Checkpoint： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/seed_100/question_8/best_ccc.pt
类型： best_ccc
Epoch： 20
缺少参数： []
多余参数： []
================================================================================
Text + Audio Seed 100独立测试结果
================================================================================
测试参与者数量： 56
CCC： 0.655986
RMSE： 5.465803
MAE： 4.303571
完全相等比例： 0.035714
预测总分范围： 0～23
真实总分范围： 0～22
预测文件： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/seed_100_test_predictions_56.csv
Checkpoint： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/seed_1234/question_1/best_ccc.pt
类型： best_ccc
Epoch： 15
缺少参数： []
多余参数： []
Checkpoint： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/seed_1234/question_2/best_ccc.pt
类型： best_ccc
Epoch： 8
缺少参数： []
多余参数： []
Checkpoint： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/seed_1234/question_3/best_ccc.pt
类型： best_ccc
Epoch： 11
缺少参数： []
多余参数： []
Checkpoint： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/seed_1234/question_4/best_ccc.pt
类型： best_ccc
Epoch： 2
缺少参数： []
多余参数： []
Checkpoint： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/seed_1234/question_5/best_ccc.pt
类型： best_ccc
Epoch： 15
缺少参数： []
多余参数： []
Checkpoint： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/seed_1234/question_6/best_ccc.pt
类型： best_ccc
Epoch： 8
缺少参数： []
多余参数： []
Checkpoint： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/seed_1234/question_7/best_ccc.pt
类型： best_ccc
Epoch： 9
缺少参数： []
多余参数： []
Checkpoint： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/seed_1234/question_8/best_ccc.pt
类型： best_ccc
Epoch： 14
缺少参数： []
多余参数： []
================================================================================
Text + Audio Seed 1234独立测试结果
================================================================================
测试参与者数量： 56
CCC： 0.662022
RMSE： 5.203021
MAE： 3.964286
完全相等比例： 0.089286
预测总分范围： 0～20
真实总分范围： 0～22
预测文件： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/seed_1234_test_predictions_56.csv

In [209]:
fusion_test_results = [seed42_fusion_test_result, seed100_fusion_test_result, seed1234_fusion_test_result]
fusion_test_rows = []

for result in fusion_test_results:
    test_row = {}
    test_row["Seed"] = result["seed"]
    test_row["Sample_Count"] = result["sample_count"]
    test_row["CCC"] = result["ccc"]
    test_row["RMSE"] = result["rmse"]
    test_row["MAE"] = result["mae"]
    test_row["Exact_Accuracy"] = result["exact_accuracy"]
    test_row["Predicted_Min"] = result["predicted_min"]
    test_row["Predicted_Max"] = result["predicted_max"]
    test_row["True_Min"] = result["true_min"]
    test_row["True_Max"] = result["true_max"]
    fusion_test_rows.append(test_row)

fusion_test_seed_summary_df = pd.DataFrame(fusion_test_rows)
display(fusion_test_seed_summary_df)

,Seed,Sample_Count,CCC,RMSE,MAE,Exact_Accuracy,Predicted_Min,Predicted_Max,True_Min,True_Max
0,42,56,0.580356,6.209152,4.767857,0.053571,0,23,0,22
1,100,56,0.655986,5.465803,4.303571,0.035714,0,23,0,22
2,1234,56,0.662022,5.203021,3.964286,0.089286,0,20,0,22

In [210]:
fusion_three_seed_rows = []

for metric_name in ["CCC", "RMSE", "MAE", "Exact_Accuracy"]:
    metric_row = {}
    metric_row["Metric"] = metric_name
    metric_row["Mean"] = fusion_test_seed_summary_df[metric_name].mean()
    metric_row["Std"] = fusion_test_seed_summary_df[metric_name].std(ddof=1)
    fusion_three_seed_rows.append(metric_row)

fusion_three_seed_summary_df = pd.DataFrame(fusion_three_seed_rows)
display(fusion_three_seed_summary_df)

           Metric      Mean       Std
0             CCC  0.632788  0.045508
1            RMSE  5.625992  0.521843
2             MAE  4.345238  0.403403
3  Exact_Accuracy  0.059524  0.027277

In [211]:
fusion_test_seed_summary_path = FUSION_CHECKPOINT_ROOT / "three_seed_test_results_56.csv"
fusion_three_seed_summary_path = FUSION_CHECKPOINT_ROOT / "three_seed_test_summary_56.csv"

fusion_test_seed_summary_df.to_csv(fusion_test_seed_summary_path, index=False)
fusion_three_seed_summary_df.to_csv(fusion_three_seed_summary_path, index=False)

print("逐Seed测试结果：", fusion_test_seed_summary_path)
print("三Seed均值与标准差：", fusion_three_seed_summary_path)
print("逐Seed文件存在：", fusion_test_seed_summary_path.exists())
print("三Seed汇总文件存在：", fusion_three_seed_summary_path.exists())

逐Seed测试结果： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/three_seed_test_results_56.csv
三Seed均值与标准差： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/three_seed_test_summary_56.csv
逐Seed文件存在： True
三Seed汇总文件存在： True

### TCmax

In [212]:
import math


# ==================================================================================================
# Text + Audio TCMax实验配置
# 不修改原始T+A基线配置和输出
# ==================================================================================================

TCMAX_LAMBDA = 0.01
TCMAX_NUM_NEGATIVE_SETS = 1
TCMAX_VALIDATION_SEED = 2026

TCMAX_CHECKPOINT_ROOT = (
    FUSION_CHECKPOINT_ROOT
    / "tcmax_text_audio"
)


# ==================================================================================================
# 计算Text + Audio + Label的TCMax估计
# ==================================================================================================

def calculate_text_audio_tcmax(
    model,
    text_features,
    text_masks,
    audio_features,
    audio_masks,
    labels,
    positive_logits,
    num_negative_sets=TCMAX_NUM_NEGATIVE_SETS,
    permutation_generator=None,
):
    """
    使用DV/TCNE形式估计TC(Text, Audio, Label)。

    正组合：
        (text_i, audio_i, label_i)

    独立负组合：
        (text_perm_t[i], audio_perm_a[i], label_perm_y[i])

    Text、Audio和Label分别独立打乱。

    返回：
        tc_estimate
        tc_loss = -tc_estimate
        positive_term
        negative_term
    """

    if num_negative_sets < 1:
        raise ValueError("num_negative_sets必须大于或等于1")

    labels = labels.long()
    batch_size = labels.shape[0]

    positive_scores = positive_logits.gather(
        dim=1,
        index=labels.unsqueeze(1),
    ).squeeze(1)

    # 最后一个batch可能只有一个样本，此时无法构造有效的独立组合。
    if batch_size < 2:
        zero = positive_scores.sum() * 0.0

        return {
            "tc_estimate": zero,
            "tc_loss": zero,
            "positive_term": zero,
            "negative_term": zero,
            "positive_scores": positive_scores,
            "negative_scores": positive_scores.new_empty(0),
        }

    def create_permutation():
        if permutation_generator is None:
            return torch.randperm(
                batch_size,
                device=labels.device,
            )

        # 验证阶段使用CPU Generator产生固定排列，然后移动到GPU。
        return torch.randperm(
            batch_size,
            generator=permutation_generator,
            device="cpu",
        ).to(labels.device)

    negative_score_batches = []

    for _ in range(num_negative_sets):
        text_indices = create_permutation()
        audio_indices = create_permutation()
        label_indices = create_permutation()

        negative_text_features = text_features[text_indices]
        negative_text_masks = text_masks[text_indices]

        negative_audio_features = audio_features[audio_indices]
        negative_audio_masks = audio_masks[audio_indices]

        negative_labels = labels[label_indices]

        negative_logits = model(
            negative_text_features,
            negative_text_masks,
            negative_audio_features,
            negative_audio_masks,
        )

        negative_scores = negative_logits.gather(
            dim=1,
            index=negative_labels.unsqueeze(1),
        ).squeeze(1)

        negative_score_batches.append(negative_scores)

    all_negative_scores = torch.cat(
        negative_score_batches,
        dim=0,
    )

    positive_term = positive_scores.mean()

    negative_term = (
        torch.logsumexp(all_negative_scores, dim=0)
        - math.log(all_negative_scores.numel())
    )

    tc_estimate = positive_term - negative_term
    tc_loss = -tc_estimate

    return {
        "tc_estimate": tc_estimate,
        "tc_loss": tc_loss,
        "positive_term": positive_term,
        "negative_term": negative_term,
        "positive_scores": positive_scores,
        "negative_scores": all_negative_scores,
    }

In [213]:
# ==================================================================================================
# TCMax版本的单Epoch训练和验证
# ==================================================================================================

def run_fusion_epoch_tcmax(
    model,
    dataloader,
    question_index,
    class_weights,
    optimizer=None,
    lambda_tc=TCMAX_LAMBDA,
    num_negative_sets=TCMAX_NUM_NEGATIVE_SETS,
    measure_validation_tc=True,
):
    is_training = optimizer is not None

    if is_training:
        model.train()
    else:
        model.eval()

    total_objective_loss = 0.0
    total_imboll_loss = 0.0
    total_tc_loss = 0.0
    total_tc_estimate = 0.0
    total_positive_term = 0.0
    total_negative_term = 0.0
    total_samples = 0

    prediction_batches = []
    target_batches = []

    # 验证阶段使用固定排列，避免每个Epoch的Val TC仅因随机打乱而剧烈变化。
    validation_generator = None

    if not is_training and measure_validation_tc:
        validation_generator = torch.Generator(device="cpu")
        validation_generator.manual_seed(TCMAX_VALIDATION_SEED)

    for batch in dataloader:
        (
            text_features,
            text_masks,
            audio_features,
            audio_masks,
            all_labels,
        ) = batch

        text_features = text_features.to(device)
        text_masks = text_masks.to(device)

        audio_features = audio_features.to(device)
        audio_masks = audio_masks.to(device)

        labels = all_labels[:, question_index].to(device).long()

        if is_training:
            optimizer.zero_grad(set_to_none=True)

        with torch.set_grad_enabled(is_training):
            positive_logits = model(
                text_features,
                text_masks,
                audio_features,
                audio_masks,
            )

            imboll_loss = calculate_imboll_loss(
                positive_logits,
                labels,
                class_weights,
                ALPHA,
            )

            should_calculate_tc = (
                is_training
                or measure_validation_tc
            )

            if should_calculate_tc:
                tcmax_terms = calculate_text_audio_tcmax(
                    model=model,
                    text_features=text_features,
                    text_masks=text_masks,
                    audio_features=audio_features,
                    audio_masks=audio_masks,
                    labels=labels,
                    positive_logits=positive_logits,
                    num_negative_sets=num_negative_sets,
                    permutation_generator=validation_generator,
                )

                tc_estimate = tcmax_terms["tc_estimate"]
                tc_loss = tcmax_terms["tc_loss"]
                positive_term = tcmax_terms["positive_term"]
                negative_term = tcmax_terms["negative_term"]

            else:
                zero = imboll_loss * 0.0
                tc_estimate = zero
                tc_loss = zero
                positive_term = zero
                negative_term = zero

            total_loss = (
                imboll_loss
                + lambda_tc * tc_loss
            )

            if not torch.isfinite(total_loss):
                raise RuntimeError(
                    f"出现非有限TCMax损失："
                    f"ImbOLL={imboll_loss.detach().item()}，"
                    f"TC={tc_estimate.detach().item()}，"
                    f"Total={total_loss.detach().item()}"
                )

            if is_training:
                total_loss.backward()

                torch.nn.utils.clip_grad_norm_(
                    model.parameters(),
                    MAX_GRAD_NORM,
                )

                optimizer.step()

        predictions = torch.argmax(
            positive_logits,
            dim=1,
        )

        batch_size = labels.shape[0]

        total_objective_loss += (
            total_loss.detach().item()
            * batch_size
        )

        total_imboll_loss += (
            imboll_loss.detach().item()
            * batch_size
        )

        total_tc_loss += (
            tc_loss.detach().item()
            * batch_size
        )

        total_tc_estimate += (
            tc_estimate.detach().item()
            * batch_size
        )

        total_positive_term += (
            positive_term.detach().item()
            * batch_size
        )

        total_negative_term += (
            negative_term.detach().item()
            * batch_size
        )

        total_samples += batch_size

        prediction_batches.append(
            predictions.detach().cpu()
        )

        target_batches.append(
            labels.detach().cpu()
        )

    all_predictions = torch.cat(
        prediction_batches,
        dim=0,
    )

    all_targets = torch.cat(
        target_batches,
        dim=0,
    )

    average_objective_loss = (
        total_objective_loss
        / total_samples
    )

    average_imboll_loss = (
        total_imboll_loss
        / total_samples
    )

    average_tc_loss = (
        total_tc_loss
        / total_samples
    )

    average_tc_estimate = (
        total_tc_estimate
        / total_samples
    )

    average_positive_term = (
        total_positive_term
        / total_samples
    )

    average_negative_term = (
        total_negative_term
        / total_samples
    )

    classification_metrics = calculate_multiclass_metrics(
        all_predictions,
        all_targets,
    )

    float_predictions = all_predictions.float()
    float_targets = all_targets.float()

    ccc = calculate_sample_ccc(
        float_predictions,
        float_targets,
    ).item()

    rmse = torch.sqrt(
        torch.mean(
            (float_predictions - float_targets) ** 2
        )
    ).item()

    mae = torch.mean(
        torch.abs(
            float_predictions - float_targets
        )
    ).item()

    return {
        # 训练时loss是实际反向传播的总损失；
        # 验证时loss只使用ImbOLL，保证和原始基线公平比较。
        "loss": (
            average_objective_loss
            if is_training
            else average_imboll_loss
        ),
        "total_loss": average_objective_loss,
        "imboll_loss": average_imboll_loss,
        "tc_loss": average_tc_loss,
        "tc_estimate": average_tc_estimate,
        "tc_positive_term": average_positive_term,
        "tc_negative_term": average_negative_term,
        "accuracy": classification_metrics["accuracy"],
        "micro_f1": classification_metrics["micro_f1"],
        "macro_f1": classification_metrics["macro_f1"],
        "weighted_f1": classification_metrics["weighted_f1"],
        "ccc": ccc,
        "rmse": rmse,
        "mae": mae,
        "confusion_matrix": classification_metrics["confusion_matrix"],
        "predictions": all_predictions,
        "targets": all_targets,
    }

In [214]:
# ==================================================================================================
# TCMax检查点
# 先调用原来的create_fusion_checkpoint，再增加TCMax实验信息
# ==================================================================================================

def create_fusion_tcmax_checkpoint(
    model,
    optimizer,
    checkpoint_type,
    epoch,
    question_index,
    seed,
    train_metrics,
    val_metrics,
    class_counts,
    imboll_weights,
    text_checkpoint_path,
    audio_checkpoint_path,
    best_val_loss,
    best_val_ccc,
    best_loss_epoch,
    best_ccc_epoch,
    lambda_tc,
    num_negative_sets,
):
    checkpoint = create_fusion_checkpoint(
        model,
        optimizer,
        checkpoint_type,
        epoch,
        question_index,
        seed,
        train_metrics,
        val_metrics,
        class_counts,
        imboll_weights,
        text_checkpoint_path,
        audio_checkpoint_path,
        best_val_loss,
        best_val_ccc,
        best_loss_epoch,
        best_ccc_epoch,
    )

    checkpoint["experiment_type"] = "text_audio_tcmax"
    checkpoint["tcmax_lambda"] = float(lambda_tc)
    checkpoint["tcmax_num_negative_sets"] = int(
        num_negative_sets
    )
    checkpoint["tcmax_score_function"] = (
        "target_class_logit"
    )
    checkpoint["tcmax_negative_sampling"] = (
        "independent_within_batch_permutation_of_text_audio_label"
    )
    checkpoint["tcmax_validation_selection_loss"] = (
        "imboll_only"
    )

    return checkpoint

In [216]:
# ==================================================================================================
# Text + Audio + TCMax训练函数
# ==================================================================================================
def train_fusion_question_tcmax(question_index, seed, lambda_tc=TCMAX_LAMBDA, num_negative_sets=TCMAX_NUM_NEGATIVE_SETS):
    set_seed(seed)
    question_number = question_index + 1
    question_name = PHQ8_QUESTION_COLUMNS[question_index]
    lambda_tag = f"{lambda_tc:.6g}".replace("-", "m").replace(".", "p")
    output_dir = TCMAX_CHECKPOINT_ROOT / f"lambda_{lambda_tag}_neg_{num_negative_sets}" / f"seed_{seed}" / f"question_{question_number}"
    output_dir.mkdir(parents=True, exist_ok=True)
    best_loss_path = output_dir / "best_loss.pt"
    best_ccc_path = output_dir / "best_ccc.pt"
    last_path = output_dir / "last.pt"
    history_path = output_dir / "history.csv"
    train_loader, val_loader = create_fusion_dataloaders(seed)
    train_labels = train_fusion_dataset.labels[:, question_index]
    class_counts, inverse_frequency_weights, imboll_weights = calculate_imboll_weights(train_labels, BETA)
    imboll_weights_device = imboll_weights.to(device)
    text_encoder, audio_encoder, text_checkpoint, audio_checkpoint, text_checkpoint_path, audio_checkpoint_path = load_pretrained_text_audio_encoders(question_index=question_index, seed=seed)
    model = TextAudioQuestMF(text_encoder=text_encoder, audio_encoder=audio_encoder).to(device)
    optimizer = torch.optim.AdamW([parameter for parameter in model.parameters() if parameter.requires_grad], lr=LEARNING_RATE, eps=ADAM_EPSILON, weight_decay=WEIGHT_DECAY)
    best_val_loss = float("inf")
    best_val_ccc = float("-inf")
    best_loss_epoch = None
    best_ccc_epoch = None
    history_rows = []
    print("=" * 100)
    print(f"开始TCMax训练：Seed={seed}，Q{question_number}，{question_name}")
    print("实验类型：Text + Audio + TCMax")
    print(f"TCMax Lambda：{lambda_tc}")
    print(f"每批负组合集合数：{num_negative_sets}")
    print("类别数量：", class_counts.tolist())
    print("ImbOLL权重：", imboll_weights.tolist())
    print("输出目录：", output_dir)
    print("=" * 100)
    for epoch in range(1, NUM_EPOCHS + 1):
        epoch_start_time = time.time()
        train_metrics = run_fusion_epoch_tcmax(model=model, dataloader=train_loader, question_index=question_index, class_weights=imboll_weights_device, optimizer=optimizer, lambda_tc=lambda_tc, num_negative_sets=num_negative_sets, measure_validation_tc=False)
        val_metrics = run_fusion_epoch_tcmax(model=model, dataloader=val_loader, question_index=question_index, class_weights=imboll_weights_device, optimizer=None, lambda_tc=lambda_tc, num_negative_sets=num_negative_sets, measure_validation_tc=True)
        epoch_seconds = time.time() - epoch_start_time
        # 验证集选模仍然使用ImbOLL，而不是带随机负组合的TC总目标。
        val_selection_loss = val_metrics["imboll_loss"]
        history_row = {"Epoch": epoch, "Train_Loss": train_metrics["total_loss"], "Train_Total_Loss": train_metrics["total_loss"], "Train_ImbOLL_Loss": train_metrics["imboll_loss"], "Train_TC_Loss": train_metrics["tc_loss"], "Train_TC_Estimate": train_metrics["tc_estimate"], "Train_TC_Positive_Term": train_metrics["tc_positive_term"], "Train_TC_Negative_Term": train_metrics["tc_negative_term"], "Train_Accuracy": train_metrics["accuracy"], "Train_CCC": train_metrics["ccc"], "Train_RMSE": train_metrics["rmse"], "Train_MAE": train_metrics["mae"], "Val_Loss": val_selection_loss, "Val_ImbOLL_Loss": val_metrics["imboll_loss"], "Val_Total_Objective": val_metrics["total_loss"], "Val_TC_Loss": val_metrics["tc_loss"], "Val_TC_Estimate": val_metrics["tc_estimate"], "Val_TC_Positive_Term": val_metrics["tc_positive_term"], "Val_TC_Negative_Term": val_metrics["tc_negative_term"], "Val_Accuracy": val_metrics["accuracy"], "Val_Micro_F1": val_metrics["micro_f1"], "Val_Macro_F1": val_metrics["macro_f1"], "Val_Weighted_F1": val_metrics["weighted_f1"], "Val_CCC": val_metrics["ccc"], "Val_RMSE": val_metrics["rmse"], "Val_MAE": val_metrics["mae"], "TCMax_Lambda": lambda_tc, "TCMax_Negative_Sets": num_negative_sets, "Seconds": epoch_seconds}
        history_rows.append(history_row)
        if not np.isfinite(val_selection_loss):
            raise RuntimeError(f"Seed={seed}，Q{question_number}在Epoch={epoch}出现非有限验证ImbOLL")
        if not np.isfinite(val_metrics["ccc"]):
            raise RuntimeError(f"Seed={seed}，Q{question_number}在Epoch={epoch}出现非有限CCC")
        if val_selection_loss < best_val_loss:
            best_val_loss = val_selection_loss
            best_loss_epoch = epoch
            best_loss_checkpoint = create_fusion_tcmax_checkpoint(model=model, optimizer=optimizer, checkpoint_type="best_loss", epoch=epoch, question_index=question_index, seed=seed, train_metrics=train_metrics, val_metrics=val_metrics, class_counts=class_counts, imboll_weights=imboll_weights, text_checkpoint_path=text_checkpoint_path, audio_checkpoint_path=audio_checkpoint_path, best_val_loss=best_val_loss, best_val_ccc=best_val_ccc, best_loss_epoch=best_loss_epoch, best_ccc_epoch=best_ccc_epoch, lambda_tc=lambda_tc, num_negative_sets=num_negative_sets)
            torch.save(best_loss_checkpoint, best_loss_path)
        if val_metrics["ccc"] > best_val_ccc:
            best_val_ccc = val_metrics["ccc"]
            best_ccc_epoch = epoch
            best_ccc_checkpoint = create_fusion_tcmax_checkpoint(model=model, optimizer=optimizer, checkpoint_type="best_ccc", epoch=epoch, question_index=question_index, seed=seed, train_metrics=train_metrics, val_metrics=val_metrics, class_counts=class_counts, imboll_weights=imboll_weights, text_checkpoint_path=text_checkpoint_path, audio_checkpoint_path=audio_checkpoint_path, best_val_loss=best_val_loss, best_val_ccc=best_val_ccc, best_loss_epoch=best_loss_epoch, best_ccc_epoch=best_ccc_epoch, lambda_tc=lambda_tc, num_negative_sets=num_negative_sets)
            torch.save(best_ccc_checkpoint, best_ccc_path)
        last_checkpoint = create_fusion_tcmax_checkpoint(model=model, optimizer=optimizer, checkpoint_type="last", epoch=epoch, question_index=question_index, seed=seed, train_metrics=train_metrics, val_metrics=val_metrics, class_counts=class_counts, imboll_weights=imboll_weights, text_checkpoint_path=text_checkpoint_path, audio_checkpoint_path=audio_checkpoint_path, best_val_loss=best_val_loss, best_val_ccc=best_val_ccc, best_loss_epoch=best_loss_epoch, best_ccc_epoch=best_ccc_epoch, lambda_tc=lambda_tc, num_negative_sets=num_negative_sets)
        torch.save(last_checkpoint, last_path)
        pd.DataFrame(history_rows).to_csv(history_path, index=False)
        print(f"Epoch {epoch:02d}/{NUM_EPOCHS} | Train Total {train_metrics['total_loss']:.6f} | ImbOLL {train_metrics['imboll_loss']:.6f} | TC Est {train_metrics['tc_estimate']:.6f} | Val ImbOLL {val_metrics['imboll_loss']:.6f} | Val TC Est {val_metrics['tc_estimate']:.6f} | Val CCC {val_metrics['ccc']:.6f} | Val Acc {val_metrics['accuracy']:.6f} | Val RMSE {val_metrics['rmse']:.6f} | {epoch_seconds:.2f}s")
    result = {"experiment_type": "text_audio_tcmax", "seed": seed, "question_index": question_index, "question_number": question_number, "question_name": question_name, "lambda_tc": lambda_tc, "num_negative_sets": num_negative_sets, "best_val_loss": best_val_loss, "best_val_ccc": best_val_ccc, "best_loss_epoch": best_loss_epoch, "best_ccc_epoch": best_ccc_epoch, "best_loss_path": best_loss_path, "best_ccc_path": best_ccc_path, "last_path": last_path, "history_path": history_path}
    del model
    del optimizer
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
    print("=" * 100)
    print(f"TCMax训练完成：Seed={seed}，Q{question_number}")
    print(f"最佳Val ImbOLL：{best_val_loss:.6f}，Epoch={best_loss_epoch}")
    print(f"最佳Val CCC：{best_val_ccc:.6f}，Epoch={best_ccc_epoch}")
    print("=" * 100)
    return result

In [215]:
# ==================================================================================================
# TCMax烟雾测试：新建模型，不复用已经执行过基线训练的smoke_model
# ==================================================================================================
set_seed(42)

(
    tcmax_smoke_text_encoder,
    tcmax_smoke_audio_encoder,
    tcmax_smoke_text_checkpoint,
    tcmax_smoke_audio_checkpoint,
    tcmax_smoke_text_checkpoint_path,
    tcmax_smoke_audio_checkpoint_path,
) = load_pretrained_text_audio_encoders(question_index=0, seed=42)

tcmax_smoke_model = TextAudioQuestMF(tcmax_smoke_text_encoder, tcmax_smoke_audio_encoder).to(device)

(tcmax_smoke_train_loader, tcmax_smoke_val_loader) = create_fusion_dataloaders(seed=42)

tcmax_smoke_optimizer = torch.optim.AdamW([parameter for parameter in tcmax_smoke_model.parameters() if parameter.requires_grad], lr=LEARNING_RATE, eps=ADAM_EPSILON, weight_decay=WEIGHT_DECAY)

tcmax_smoke_train_metrics = run_fusion_epoch_tcmax(model=tcmax_smoke_model, dataloader=tcmax_smoke_train_loader, question_index=0, class_weights=q1_imboll_weights_device, optimizer=tcmax_smoke_optimizer, lambda_tc=TCMAX_LAMBDA, num_negative_sets=TCMAX_NUM_NEGATIVE_SETS)

tcmax_smoke_val_metrics = run_fusion_epoch_tcmax(model=tcmax_smoke_model, dataloader=tcmax_smoke_val_loader, question_index=0, class_weights=q1_imboll_weights_device, optimizer=None, lambda_tc=TCMAX_LAMBDA, num_negative_sets=TCMAX_NUM_NEGATIVE_SETS)

print("TCMax一轮训练：")
print({"total_loss": tcmax_smoke_train_metrics["total_loss"], "imboll_loss": tcmax_smoke_train_metrics["imboll_loss"], "tc_loss": tcmax_smoke_train_metrics["tc_loss"], "tc_estimate": tcmax_smoke_train_metrics["tc_estimate"], "ccc": tcmax_smoke_train_metrics["ccc"]})

print("TCMax一轮验证：")
print({"imboll_loss": tcmax_smoke_val_metrics["imboll_loss"], "tc_estimate": tcmax_smoke_val_metrics["tc_estimate"], "ccc": tcmax_smoke_val_metrics["ccc"]})

文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q1_PHQ_8NoInterest/seed_42/best_loss.pt
语音Best Loss： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_42/question_1/best_loss.pt
文本保存Epoch： 13
语音保存Epoch： 10
文本缺少参数： []
文本多余参数： []
语音缺少参数： []
语音多余参数： []
TCMax一轮训练：
{'total_loss': 2.062846410493909, 'imboll_loss': 2.060044734755908, 'tc_loss': 0.2801674886440938, 'tc_estimate': -0.2801674886440938, 'ccc': 0.30838555097579956}
TCMax一轮验证：
{'imboll_loss': 2.776166959242387, 'tc_estimate': -0.5609102899377997, 'ccc': 0.29493552446365356}

In [217]:
q1_seed42_tcmax_result = train_fusion_question_tcmax(
    question_index=0,
    seed=42,
    lambda_tc=0.01,
    num_negative_sets=1,
)

文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q1_PHQ_8NoInterest/seed_42/best_loss.pt
语音Best Loss： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_42/question_1/best_loss.pt
文本保存Epoch： 13
语音保存Epoch： 10
文本缺少参数： []
文本多余参数： []
语音缺少参数： []
语音多余参数： []
====================================================================================================
开始TCMax训练：Seed=42，Q1，PHQ_8NoInterest
实验类型：Text + Audio + TCMax
TCMax Lambda：0.01
每批负组合集合数：1
类别数量： [81, 57, 20, 5]
ImbOLL权重： [1.4185717105865479, 1.6910496950149536, 2.854820728302002, 5.709641456604004]
输出目录： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/tcmax_text_audio/lambda_0p01_neg_1/seed_42/question_1
====================================================================================================
Epoch 01/20 | Train Total 2.062846 | ImbOLL 2.060045 | TC Est -0.280167 | Val ImbOLL 2.776167 | Val TC Est -0.560910 | Val CCC 0.294936 | Val Acc 0.472727 | Val RMSE 0.990867 | 2.02s
Epoch 02/20 | Train Total 1.395509 | ImbOLL 1.386280 | TC Est -0.922897 | Val ImbOLL 3.017033 | Val TC Est -1.653427 | Val CCC 0.263217 | Val Acc 0.563636 | Val RMSE 0.972345 | 1.68s
Epoch 03/20 | Train Total 1.330751 | ImbOLL 1.322582 | TC Est -0.816907 | Val ImbOLL 2.494054 | Val TC Est -1.116477 | Val CCC 0.354915 | Val Acc 0.600000 | Val RMSE 0.894427 | 1.58s
Epoch 04/20 | Train Total 1.234098 | ImbOLL 1.222903 | TC Est -1.119469 | Val ImbOLL 2.775958 | Val TC Est -1.397750 | Val CCC 0.276271 | Val Acc 0.581818 | Val RMSE 0.934199 | 1.78s
Epoch 05/20 | Train Total 1.175586 | ImbOLL 1.164710 | TC Est -1.087601 | Val ImbOLL 2.564885 | Val TC Est -0.928457 | Val CCC 0.336296 | Val Acc 0.581818 | Val RMSE 0.904534 | 1.84s
Epoch 06/20 | Train Total 1.153249 | ImbOLL 1.149168 | TC Est -0.408108 | Val ImbOLL 2.565341 | Val TC Est -1.038309 | Val CCC 0.335924 | Val Acc 0.563636 | Val RMSE 0.914529 | 1.74s
Epoch 07/20 | Train Total 1.152500 | ImbOLL 1.138881 | TC Est -1.361912 | Val ImbOLL 3.102482 | Val TC Est -2.036326 | Val CCC 0.314890 | Val Acc 0.563636 | Val RMSE 0.914529 | 1.69s
Epoch 08/20 | Train Total 1.160279 | ImbOLL 1.151059 | TC Est -0.922014 | Val ImbOLL 2.527980 | Val TC Est -1.057503 | Val CCC 0.463934 | Val Acc 0.563636 | Val RMSE 0.809040 | 1.50s
Epoch 09/20 | Train Total 1.005949 | ImbOLL 1.001203 | TC Est -0.474595 | Val ImbOLL 2.795005 | Val TC Est -1.203682 | Val CCC 0.459547 | Val Acc 0.545455 | Val RMSE 0.786245 | 1.52s
Epoch 10/20 | Train Total 1.013993 | ImbOLL 1.008791 | TC Est -0.520194 | Val ImbOLL 3.092823 | Val TC Est -1.078212 | Val CCC 0.329385 | Val Acc 0.436364 | Val RMSE 0.852803 | 1.51s
Epoch 11/20 | Train Total 1.040249 | ImbOLL 1.037103 | TC Est -0.314600 | Val ImbOLL 3.010158 | Val TC Est -1.218956 | Val CCC 0.240230 | Val Acc 0.509091 | Val RMSE 0.972345 | 1.49s
Epoch 12/20 | Train Total 0.984827 | ImbOLL 0.979920 | TC Est -0.490733 | Val ImbOLL 2.746365 | Val TC Est -1.083888 | Val CCC 0.435614 | Val Acc 0.545455 | Val RMSE 0.820200 | 1.52s
Epoch 13/20 | Train Total 0.982597 | ImbOLL 0.981394 | TC Est -0.120296 | Val ImbOLL 2.784529 | Val TC Est -0.859311 | Val CCC 0.426330 | Val Acc 0.545455 | Val RMSE 0.820200 | 1.51s
Epoch 14/20 | Train Total 1.003534 | ImbOLL 1.002136 | TC Est -0.139785 | Val ImbOLL 2.697977 | Val TC Est -0.989908 | Val CCC 0.406229 | Val Acc 0.600000 | Val RMSE 0.842075 | 1.47s
Epoch 15/20 | Train Total 0.976749 | ImbOLL 0.970682 | TC Est -0.606730 | Val ImbOLL 3.213661 | Val TC Est -1.037654 | Val CCC 0.408964 | Val Acc 0.563636 | Val RMSE 0.809040 | 1.35s
Epoch 16/20 | Train Total 0.968680 | ImbOLL 0.970354 | TC Est 0.167396 | Val ImbOLL 2.726742 | Val TC Est -0.982561 | Val CCC 0.435614 | Val Acc 0.545455 | Val RMSE 0.820200 | 1.44s
Epoch 17/20 | Train Total 1.008580 | ImbOLL 1.001458 | TC Est -0.712215 | Val ImbOLL 2.713056 | Val TC Est -0.869169 | Val CCC 0.484603 | Val Acc 0.545455 | Val RMSE 0.786245 | 1.43s
Epoch 18/20 | Train Total 0.958637 | ImbOLL 0.955663 | TC Est -0.297418 | Val ImbOLL 2.994553 | Val TC Est -1.036473 | Val CCC 0.345926 | Val Acc 0.600000 | Val RMSE 0.894427 | 1.37s
Epoch 19/20 | Train Total 1.243012 | ImbOLL 1.243486 | TC Est 0.047424 | Val ImbOLL 2.489021 | Val TC Est -0.469579 | Val CCC 0.496848 | Val Acc 0.581818 | Val RMSE 0.797724 | 1.42s
Epoch 20/20 | Train Total 0.961228 | ImbOLL 0.963205 | TC Est 0.197683 | Val ImbOLL 2.761004 | Val TC Est -0.859647 | Val CCC 0.459547 | Val Acc 0.545455 | Val RMSE 0.786245 | 1.39s
====================================================================================================
TCMax训练完成：Seed=42，Q1
最佳Val ImbOLL：2.489021，Epoch=19
最佳Val CCC：0.496848，Epoch=19
====================================================================================================

In [218]:
baseline_history_path = FUSION_CHECKPOINT_ROOT / "seed_42" / "question_1" / "history.csv"
baseline_history = pd.read_csv(baseline_history_path)
tcmax_history = pd.read_csv(q1_seed42_tcmax_result["history_path"])
baseline_best_row = baseline_history.loc[baseline_history["Val_CCC"].idxmax()]
tcmax_best_row = tcmax_history.loc[tcmax_history["Val_CCC"].idxmax()]
comparison = pd.DataFrame([{"Experiment": "T+A Baseline", "Best_Epoch": int(baseline_best_row["Epoch"]), "Best_Val_CCC": baseline_best_row["Val_CCC"], "Val_Loss": baseline_best_row["Val_Loss"], "Val_RMSE": baseline_best_row["Val_RMSE"], "Val_MAE": baseline_best_row["Val_MAE"]}, {"Experiment": "T+A + TCMax", "Best_Epoch": int(tcmax_best_row["Epoch"]), "Best_Val_CCC": tcmax_best_row["Val_CCC"], "Val_Loss": tcmax_best_row["Val_ImbOLL_Loss"], "Val_RMSE": tcmax_best_row["Val_RMSE"], "Val_MAE": tcmax_best_row["Val_MAE"], "Val_TC_Estimate": tcmax_best_row["Val_TC_Estimate"]}])
comparison["CCC_Change_vs_Baseline"] = comparison["Best_Val_CCC"] - comparison.loc[0, "Best_Val_CCC"]
display(comparison)

,Experiment,Best_Epoch,Best_Val_CCC,Val_Loss,Val_RMSE,Val_MAE,Val_TC_Estimate,CCC_Change_vs_Baseline
0,T+A Baseline,12,0.484603,2.702756,0.786245,0.509091,NaN,0.000000
1,T+A + TCMax,19,0.496848,2.489021,0.797724,0.490909,-0.469579,0.012244

In [219]:
display(
    tcmax_history[
        [
            "Epoch",
            "Train_ImbOLL_Loss",
            "Train_TC_Estimate",
            "Val_ImbOLL_Loss",
            "Val_TC_Estimate",
            "Val_CCC",
        ]
    ]
)

,Epoch,Train_ImbOLL_Loss,Train_TC_Estimate,Val_ImbOLL_Loss,Val_TC_Estimate,Val_CCC
0,1,2.060045,-0.280167,2.776167,-0.560910,0.294936
1,2,1.386280,-0.922897,3.017033,-1.653427,0.263217
2,3,1.322582,-0.816907,2.494054,-1.116477,0.354915
3,4,1.222903,-1.119469,2.775958,-1.397750,0.276271
4,5,1.164710,-1.087601,2.564885,-0.928457,0.336296
5,6,1.149168,-0.408108,2.565341,-1.038309,0.335924
6,7,1.138881,-1.361912,3.102482,-2.036326,0.314890
7,8,1.151059,-0.922014,2.527980,-1.057503,0.463934
8,9,1.001203,-0.474595,2.795005,-1.203682,0.459547
9,10,1.008791,-0.520194,3.092823,-1.078212,0.329385
10,11,1.037103,-0.314600,3.010158,-1.218956,0.240230
11,12,0.979920,-0.490733,2.746365,-1.083888,0.435614
12,13,0.981394,-0.120296,2.784529,-0.859311,0.426330
13,14,1.002136,-0.139785,2.697977,-0.989908,0.406229
14,15,0.970682,-0.606730,3.213661,-1.037654,0.408964
15,16,0.970354,0.167396,2.726742,-0.982561,0.435614
16,17,1.001458,-0.712215,2.713056,-0.869169,0.484603
17,18,0.955663,-0.297418,2.994553,-1.036473,0.345926
18,19,1.243486,0.047424,2.489021,-0.469579,0.496848
19,20,0.963205,0.197683,2.761004,-0.859647,0.459547

In [222]:
q1_seed123_tcmax_result = train_fusion_question_tcmax(question_index=0, seed=1234, lambda_tc=0.01, num_negative_sets=1)
q1_seed2024_tcmax_result = train_fusion_question_tcmax(question_index=0, seed=100, lambda_tc=0.01, num_negative_sets=1)

文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q1_PHQ_8NoInterest/seed_1234/best_loss.pt
语音Best Loss： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_1234/question_1/best_loss.pt
文本保存Epoch： 7
语音保存Epoch： 18
文本缺少参数： []
文本多余参数： []
语音缺少参数： []
语音多余参数： []
====================================================================================================
开始TCMax训练：Seed=1234，Q1，PHQ_8NoInterest
实验类型：Text + Audio + TCMax
TCMax Lambda：0.01
每批负组合集合数：1
类别数量： [81, 57, 20, 5]
ImbOLL权重： [1.4185717105865479, 1.6910496950149536, 2.854820728302002, 5.709641456604004]
输出目录： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/tcmax_text_audio/lambda_0p01_neg_1/seed_1234/question_1
====================================================================================================
Epoch 01/20 | Train Total 2.236861 | ImbOLL 2.234992 | TC Est -0.186889 | Val ImbOLL 2.428502 | Val TC Est -0.153747 | Val CCC 0.184928 | Val Acc 0.563636 | Val RMSE 0.924416 | 2.16s
Epoch 02/20 | Train Total 1.771017 | ImbOLL 1.763589 | TC Est -0.742753 | Val ImbOLL 3.103845 | Val TC Est -2.032110 | Val CCC 0.352747 | Val Acc 0.509091 | Val RMSE 0.924416 | 1.75s
Epoch 03/20 | Train Total 1.671143 | ImbOLL 1.660007 | TC Est -1.113678 | Val ImbOLL 2.410494 | Val TC Est -1.021251 | Val CCC 0.415486 | Val Acc 0.490909 | Val RMSE 0.873863 | 1.54s
Epoch 04/20 | Train Total 1.556458 | ImbOLL 1.547947 | TC Est -0.851054 | Val ImbOLL 2.431213 | Val TC Est -0.423531 | Val CCC 0.371180 | Val Acc 0.527273 | Val RMSE 0.884205 | 1.52s
Epoch 05/20 | Train Total 1.467863 | ImbOLL 1.459567 | TC Est -0.829677 | Val ImbOLL 2.556097 | Val TC Est -0.832735 | Val CCC 0.370120 | Val Acc 0.509091 | Val RMSE 0.894427 | 1.49s
Epoch 06/20 | Train Total 1.542141 | ImbOLL 1.534606 | TC Est -0.753533 | Val ImbOLL 2.934023 | Val TC Est -0.754688 | Val CCC 0.189994 | Val Acc 0.509091 | Val RMSE 1.000000 | 1.48s
Epoch 07/20 | Train Total 1.437485 | ImbOLL 1.430454 | TC Est -0.703098 | Val ImbOLL 2.437086 | Val TC Est -0.556322 | Val CCC 0.218856 | Val Acc 0.454545 | Val RMSE 0.924416 | 1.54s
Epoch 08/20 | Train Total 1.470869 | ImbOLL 1.466350 | TC Est -0.451861 | Val ImbOLL 2.783525 | Val TC Est -0.665907 | Val CCC 0.361862 | Val Acc 0.527273 | Val RMSE 0.914529 | 1.44s
Epoch 09/20 | Train Total 1.533475 | ImbOLL 1.527081 | TC Est -0.639378 | Val ImbOLL 2.569808 | Val TC Est -0.672074 | Val CCC 0.343523 | Val Acc 0.563636 | Val RMSE 0.894427 | 1.45s
Epoch 10/20 | Train Total 1.482626 | ImbOLL 1.473883 | TC Est -0.874279 | Val ImbOLL 2.452007 | Val TC Est -0.553039 | Val CCC 0.350906 | Val Acc 0.490909 | Val RMSE 0.904534 | 1.62s
Epoch 11/20 | Train Total 1.559879 | ImbOLL 1.554601 | TC Est -0.527823 | Val ImbOLL 2.443481 | Val TC Est -0.210376 | Val CCC 0.371180 | Val Acc 0.527273 | Val RMSE 0.884205 | 1.52s
Epoch 12/20 | Train Total 1.427700 | ImbOLL 1.429120 | TC Est 0.141992 | Val ImbOLL 2.884731 | Val TC Est -0.303099 | Val CCC 0.223665 | Val Acc 0.509091 | Val RMSE 1.000000 | 1.45s
Epoch 13/20 | Train Total 1.439656 | ImbOLL 1.437433 | TC Est -0.222325 | Val ImbOLL 2.476278 | Val TC Est -0.359758 | Val CCC 0.330579 | Val Acc 0.436364 | Val RMSE 0.904534 | 1.41s
Epoch 14/20 | Train Total 1.363695 | ImbOLL 1.362872 | TC Est -0.082255 | Val ImbOLL 2.533043 | Val TC Est -0.271779 | Val CCC 0.390509 | Val Acc 0.545455 | Val RMSE 0.873863 | 1.43s
Epoch 15/20 | Train Total 1.479784 | ImbOLL 1.480048 | TC Est 0.026410 | Val ImbOLL 2.494780 | Val TC Est -0.170208 | Val CCC 0.379494 | Val Acc 0.509091 | Val RMSE 0.894427 | 1.46s
Epoch 16/20 | Train Total 1.505659 | ImbOLL 1.503639 | TC Est -0.202039 | Val ImbOLL 2.450870 | Val TC Est -0.165418 | Val CCC 0.423085 | Val Acc 0.490909 | Val RMSE 0.873863 | 1.36s
Epoch 17/20 | Train Total 1.435581 | ImbOLL 1.432414 | TC Est -0.316639 | Val ImbOLL 2.578305 | Val TC Est -0.377913 | Val CCC 0.380504 | Val Acc 0.563636 | Val RMSE 0.894427 | 1.38s
Epoch 18/20 | Train Total 1.501759 | ImbOLL 1.501112 | TC Est -0.064695 | Val ImbOLL 2.533698 | Val TC Est -0.318973 | Val CCC 0.305775 | Val Acc 0.545455 | Val RMSE 0.934199 | 1.70s
Epoch 19/20 | Train Total 1.460839 | ImbOLL 1.462058 | TC Est 0.121859 | Val ImbOLL 2.524566 | Val TC Est -0.392952 | Val CCC 0.403382 | Val Acc 0.454545 | Val RMSE 0.894427 | 1.38s
Epoch 20/20 | Train Total 1.399078 | ImbOLL 1.399484 | TC Est 0.040519 | Val ImbOLL 2.527047 | Val TC Est -0.323538 | Val CCC 0.323256 | Val Acc 0.545455 | Val RMSE 0.904534 | 1.36s
====================================================================================================
TCMax训练完成：Seed=1234，Q1
最佳Val ImbOLL：2.410494，Epoch=3
最佳Val CCC：0.423085，Epoch=16
====================================================================================================
文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q1_PHQ_8NoInterest/seed_100/best_loss.pt
语音Best Loss： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_100/question_1/best_loss.pt
文本保存Epoch： 10
语音保存Epoch： 8
文本缺少参数： []
文本多余参数： []
语音缺少参数： []
语音多余参数： []
====================================================================================================
开始TCMax训练：Seed=100，Q1，PHQ_8NoInterest
实验类型：Text + Audio + TCMax
TCMax Lambda：0.01
每批负组合集合数：1
类别数量： [81, 57, 20, 5]
ImbOLL权重： [1.4185717105865479, 1.6910496950149536, 2.854820728302002, 5.709641456604004]
输出目录： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/tcmax_text_audio/lambda_0p01_neg_1/seed_100/question_1
====================================================================================================
Epoch 01/20 | Train Total 2.044959 | ImbOLL 2.042870 | TC Est -0.208867 | Val ImbOLL 3.182810 | Val TC Est -0.502348 | Val CCC 0.200551 | Val Acc 0.454545 | Val RMSE 1.095445 | 1.43s
Epoch 02/20 | Train Total 1.619003 | ImbOLL 1.612251 | TC Est -0.675210 | Val ImbOLL 3.445698 | Val TC Est -1.547731 | Val CCC 0.391820 | Val Acc 0.490909 | Val RMSE 0.953463 | 1.41s
Epoch 03/20 | Train Total 1.687515 | ImbOLL 1.675913 | TC Est -1.160226 | Val ImbOLL 2.795959 | Val TC Est -0.871717 | Val CCC 0.326484 | Val Acc 0.490909 | Val RMSE 0.934199 | 1.32s
Epoch 04/20 | Train Total 1.572134 | ImbOLL 1.566653 | TC Est -0.548102 | Val ImbOLL 2.608511 | Val TC Est -0.242056 | Val CCC 0.257540 | Val Acc 0.545455 | Val RMSE 0.904534 | 1.32s
Epoch 05/20 | Train Total 1.535848 | ImbOLL 1.532229 | TC Est -0.361891 | Val ImbOLL 2.693609 | Val TC Est -0.124519 | Val CCC 0.390686 | Val Acc 0.509091 | Val RMSE 0.894427 | 1.31s
Epoch 06/20 | Train Total 1.423551 | ImbOLL 1.423970 | TC Est 0.041920 | Val ImbOLL 2.736028 | Val TC Est -0.345368 | Val CCC 0.344698 | Val Acc 0.509091 | Val RMSE 0.894427 | 1.30s
Epoch 07/20 | Train Total 1.410492 | ImbOLL 1.410257 | TC Est -0.023464 | Val ImbOLL 3.191025 | Val TC Est -0.666245 | Val CCC 0.294612 | Val Acc 0.545455 | Val RMSE 0.904534 | 1.30s
Epoch 08/20 | Train Total 1.475900 | ImbOLL 1.471163 | TC Est -0.473726 | Val ImbOLL 3.331795 | Val TC Est -0.805443 | Val CCC 0.368203 | Val Acc 0.600000 | Val RMSE 0.873863 | 1.29s
Epoch 09/20 | Train Total 1.450133 | ImbOLL 1.445037 | TC Est -0.509546 | Val ImbOLL 2.710057 | Val TC Est -0.541254 | Val CCC 0.251192 | Val Acc 0.472727 | Val RMSE 0.943880 | 1.30s
Epoch 10/20 | Train Total 1.405310 | ImbOLL 1.399155 | TC Est -0.615441 | Val ImbOLL 2.723245 | Val TC Est -0.456998 | Val CCC 0.232390 | Val Acc 0.454545 | Val RMSE 0.953463 | 1.30s
Epoch 11/20 | Train Total 1.429882 | ImbOLL 1.427715 | TC Est -0.216689 | Val ImbOLL 3.486163 | Val TC Est -0.581247 | Val CCC 0.267320 | Val Acc 0.581818 | Val RMSE 0.934199 | 1.47s
Epoch 12/20 | Train Total 1.492132 | ImbOLL 1.490966 | TC Est -0.116601 | Val ImbOLL 2.824502 | Val TC Est -0.356548 | Val CCC 0.365474 | Val Acc 0.472727 | Val RMSE 0.943880 | 1.43s
Epoch 13/20 | Train Total 1.559739 | ImbOLL 1.557680 | TC Est -0.205834 | Val ImbOLL 2.517769 | Val TC Est -0.260177 | Val CCC 0.256122 | Val Acc 0.545455 | Val RMSE 0.904534 | 1.36s
Epoch 14/20 | Train Total 1.457663 | ImbOLL 1.455561 | TC Est -0.210244 | Val ImbOLL 2.849166 | Val TC Est -0.346009 | Val CCC 0.364108 | Val Acc 0.527273 | Val RMSE 0.914529 | 1.33s
Epoch 15/20 | Train Total 1.438842 | ImbOLL 1.437781 | TC Est -0.106018 | Val ImbOLL 2.893435 | Val TC Est -0.329704 | Val CCC 0.307010 | Val Acc 0.490909 | Val RMSE 0.934199 | 1.38s
Epoch 16/20 | Train Total 1.470455 | ImbOLL 1.469317 | TC Est -0.113753 | Val ImbOLL 2.675914 | Val TC Est -0.296657 | Val CCC 0.276551 | Val Acc 0.527273 | Val RMSE 0.884205 | 1.45s
Epoch 17/20 | Train Total 1.355560 | ImbOLL 1.354781 | TC Est -0.077911 | Val ImbOLL 2.927402 | Val TC Est -0.510436 | Val CCC 0.401227 | Val Acc 0.527273 | Val RMSE 0.884205 | 1.38s
Epoch 18/20 | Train Total 1.420493 | ImbOLL 1.416947 | TC Est -0.354562 | Val ImbOLL 3.399082 | Val TC Est -0.776899 | Val CCC 0.252312 | Val Acc 0.490909 | Val RMSE 0.934199 | 1.43s
Epoch 19/20 | Train Total 1.423865 | ImbOLL 1.419533 | TC Est -0.433258 | Val ImbOLL 2.777760 | Val TC Est -0.385688 | Val CCC 0.256660 | Val Acc 0.436364 | Val RMSE 0.962950 | 1.38s
Epoch 20/20 | Train Total 1.346981 | ImbOLL 1.343174 | TC Est -0.380659 | Val ImbOLL 3.189006 | Val TC Est -0.563496 | Val CCC 0.345430 | Val Acc 0.509091 | Val RMSE 0.924416 | 1.38s
====================================================================================================
TCMax训练完成：Seed=100，Q1
最佳Val ImbOLL：2.517769，Epoch=13
最佳Val CCC：0.401227，Epoch=17
====================================================================================================

In [223]:
baseline_seed42_ccc = pd.read_csv(FUSION_CHECKPOINT_ROOT / "seed_42" / "question_1" / "history.csv")["Val_CCC"].max()
baseline_seed100_ccc = pd.read_csv(FUSION_CHECKPOINT_ROOT / "seed_100" / "question_1" / "history.csv")["Val_CCC"].max()
baseline_seed1234_ccc = pd.read_csv(FUSION_CHECKPOINT_ROOT / "seed_1234" / "question_1" / "history.csv")["Val_CCC"].max()

In [224]:
q1_comparison = pd.DataFrame({"Seed": [42, 100, 1234], "Baseline_CCC": [baseline_seed42_ccc, baseline_seed100_ccc, baseline_seed1234_ccc], "TCMax_CCC": [0.496848, 0.401227, 0.423085]})
q1_comparison["CCC_Change"] = q1_comparison["TCMax_CCC"] - q1_comparison["Baseline_CCC"]
display(q1_comparison)
print("Baseline Mean ± Std：", q1_comparison["Baseline_CCC"].mean(), q1_comparison["Baseline_CCC"].std(ddof=1))
print("TCMax Mean ± Std：", q1_comparison["TCMax_CCC"].mean(), q1_comparison["TCMax_CCC"].std(ddof=1))
print("平均CCC变化：", q1_comparison["CCC_Change"].mean())

   Seed  Baseline_CCC  TCMax_CCC  CCC_Change
0    42      0.484603   0.496848    0.012245
1   100      0.417478   0.401227   -0.016251
2  1234      0.451380   0.423085   -0.028295

Baseline Mean ± Std： 0.451153685649236 0.033563320903678556
TCMax Mean ± Std： 0.44038666666666665 0.050103439625771545
平均CCC变化： -0.01076701898256934

In [225]:
q1_seed42_tcmax_neg4_result = train_fusion_question_tcmax(question_index=0, seed=42, lambda_tc=0.01, num_negative_sets=4)
q1_seed100_tcmax_neg4_result = train_fusion_question_tcmax(question_index=0, seed=100, lambda_tc=0.01, num_negative_sets=4)
q1_seed1234_tcmax_neg4_result = train_fusion_question_tcmax(question_index=0, seed=1234, lambda_tc=0.01, num_negative_sets=4)

文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q1_PHQ_8NoInterest/seed_42/best_loss.pt
语音Best Loss： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_42/question_1/best_loss.pt
文本保存Epoch： 13
语音保存Epoch： 10
文本缺少参数： []
文本多余参数： []
语音缺少参数： []
语音多余参数： []
====================================================================================================
开始TCMax训练：Seed=42，Q1，PHQ_8NoInterest
实验类型：Text + Audio + TCMax
TCMax Lambda：0.01
每批负组合集合数：4
类别数量： [81, 57, 20, 5]
ImbOLL权重： [1.4185717105865479, 1.6910496950149536, 2.854820728302002, 5.709641456604004]
输出目录： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/tcmax_text_audio/lambda_0p01_neg_4/seed_42/question_1
====================================================================================================
Epoch 01/20 | Train Total 2.179019 | ImbOLL 2.178170 | TC Est -0.084934 | Val ImbOLL 2.596469 | Val TC Est -0.360573 | Val CCC 0.302873 | Val Acc 0.509091 | Val RMSE 0.972345 | 4.05s
Epoch 02/20 | Train Total 1.272620 | ImbOLL 1.266543 | TC Est -0.607703 | Val ImbOLL 3.152666 | Val TC Est -1.872716 | Val CCC 0.260641 | Val Acc 0.581818 | Val RMSE 0.962950 | 3.55s
Epoch 03/20 | Train Total 1.273550 | ImbOLL 1.251460 | TC Est -2.208990 | Val ImbOLL 2.653816 | Val TC Est -1.412205 | Val CCC 0.384268 | Val Acc 0.581818 | Val RMSE 0.873863 | 3.50s
Epoch 04/20 | Train Total 1.187077 | ImbOLL 1.178520 | TC Est -0.855715 | Val ImbOLL 2.658064 | Val TC Est -1.116082 | Val CCC 0.326816 | Val Acc 0.563636 | Val RMSE 0.914529 | 3.44s
Epoch 05/20 | Train Total 1.147068 | ImbOLL 1.140425 | TC Est -0.664246 | Val ImbOLL 2.733783 | Val TC Est -1.213775 | Val CCC 0.267049 | Val Acc 0.563636 | Val RMSE 0.943880 | 3.36s
Epoch 06/20 | Train Total 1.255376 | ImbOLL 1.248081 | TC Est -0.729575 | Val ImbOLL 2.373156 | Val TC Est -0.647772 | Val CCC 0.383761 | Val Acc 0.490909 | Val RMSE 0.852803 | 3.24s
Epoch 07/20 | Train Total 1.223399 | ImbOLL 1.212353 | TC Est -1.104558 | Val ImbOLL 2.939104 | Val TC Est -1.736837 | Val CCC 0.377158 | Val Acc 0.600000 | Val RMSE 0.842075 | 3.68s
Epoch 08/20 | Train Total 1.294556 | ImbOLL 1.283936 | TC Est -1.062074 | Val ImbOLL 2.747721 | Val TC Est -0.977416 | Val CCC 0.308503 | Val Acc 0.509091 | Val RMSE 0.943880 | 3.28s
Epoch 09/20 | Train Total 1.062923 | ImbOLL 1.058794 | TC Est -0.412957 | Val ImbOLL 2.887876 | Val TC Est -0.991752 | Val CCC 0.442875 | Val Acc 0.600000 | Val RMSE 0.786245 | 3.28s
Epoch 10/20 | Train Total 1.075808 | ImbOLL 1.069215 | TC Est -0.659254 | Val ImbOLL 2.749158 | Val TC Est -0.580446 | Val CCC 0.340990 | Val Acc 0.436364 | Val RMSE 0.852803 | 3.19s
Epoch 11/20 | Train Total 0.986279 | ImbOLL 0.982827 | TC Est -0.345156 | Val ImbOLL 2.787441 | Val TC Est -1.240625 | Val CCC 0.345926 | Val Acc 0.600000 | Val RMSE 0.894427 | 3.11s
Epoch 12/20 | Train Total 1.051393 | ImbOLL 1.040933 | TC Est -1.045974 | Val ImbOLL 2.937607 | Val TC Est -1.199107 | Val CCC 0.317532 | Val Acc 0.509091 | Val RMSE 0.943880 | 3.09s
Epoch 13/20 | Train Total 1.087888 | ImbOLL 1.083484 | TC Est -0.440412 | Val ImbOLL 3.001405 | Val TC Est -0.768535 | Val CCC 0.362983 | Val Acc 0.454545 | Val RMSE 0.842075 | 3.18s
Epoch 14/20 | Train Total 1.014819 | ImbOLL 1.011863 | TC Est -0.295571 | Val ImbOLL 2.778613 | Val TC Est -0.907867 | Val CCC 0.387947 | Val Acc 0.581818 | Val RMSE 0.831209 | 3.40s
Epoch 15/20 | Train Total 0.929265 | ImbOLL 0.922966 | TC Est -0.629843 | Val ImbOLL 3.308081 | Val TC Est -1.078749 | Val CCC 0.406881 | Val Acc 0.545455 | Val RMSE 0.820200 | 3.48s
Epoch 16/20 | Train Total 1.017165 | ImbOLL 1.013281 | TC Est -0.388317 | Val ImbOLL 2.913644 | Val TC Est -0.840824 | Val CCC 0.383761 | Val Acc 0.490909 | Val RMSE 0.852803 | 3.47s
Epoch 17/20 | Train Total 1.006587 | ImbOLL 1.005493 | TC Est -0.109366 | Val ImbOLL 2.611180 | Val TC Est -0.704321 | Val CCC 0.471300 | Val Acc 0.563636 | Val RMSE 0.809040 | 3.29s
Epoch 18/20 | Train Total 0.974559 | ImbOLL 0.973850 | TC Est -0.070895 | Val ImbOLL 2.875699 | Val TC Est -0.957095 | Val CCC 0.344793 | Val Acc 0.563636 | Val RMSE 0.914529 | 3.23s
Epoch 19/20 | Train Total 1.129509 | ImbOLL 1.126116 | TC Est -0.339353 | Val ImbOLL 2.927854 | Val TC Est -0.806979 | Val CCC 0.428817 | Val Acc 0.563636 | Val RMSE 0.809040 | 3.14s
Epoch 20/20 | Train Total 1.075619 | ImbOLL 1.072382 | TC Est -0.323720 | Val ImbOLL 2.773071 | Val TC Est -0.646084 | Val CCC 0.333914 | Val Acc 0.527273 | Val RMSE 0.863397 | 3.11s
====================================================================================================
TCMax训练完成：Seed=42，Q1
最佳Val ImbOLL：2.373156，Epoch=6
最佳Val CCC：0.471300，Epoch=17
====================================================================================================
文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q1_PHQ_8NoInterest/seed_100/best_loss.pt
语音Best Loss： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_100/question_1/best_loss.pt
文本保存Epoch： 10
语音保存Epoch： 8
文本缺少参数： []
文本多余参数： []
语音缺少参数： []
语音多余参数： []
====================================================================================================
开始TCMax训练：Seed=100，Q1，PHQ_8NoInterest
实验类型：Text + Audio + TCMax
TCMax Lambda：0.01
每批负组合集合数：4
类别数量： [81, 57, 20, 5]
ImbOLL权重： [1.4185717105865479, 1.6910496950149536, 2.854820728302002, 5.709641456604004]
输出目录： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/tcmax_text_audio/lambda_0p01_neg_4/seed_100/question_1
====================================================================================================
Epoch 01/20 | Train Total 2.092838 | ImbOLL 2.091766 | TC Est -0.107163 | Val ImbOLL 2.912450 | Val TC Est -0.372426 | Val CCC 0.312941 | Val Acc 0.472727 | Val RMSE 0.990867 | 3.13s
Epoch 02/20 | Train Total 1.579830 | ImbOLL 1.574754 | TC Est -0.507599 | Val ImbOLL 3.558788 | Val TC Est -1.609912 | Val CCC 0.310600 | Val Acc 0.472727 | Val RMSE 0.990867 | 3.19s
Epoch 03/20 | Train Total 1.728109 | ImbOLL 1.715269 | TC Est -1.283996 | Val ImbOLL 2.877052 | Val TC Est -0.763961 | Val CCC 0.250731 | Val Acc 0.509091 | Val RMSE 0.924416 | 3.41s
Epoch 04/20 | Train Total 1.542255 | ImbOLL 1.536971 | TC Est -0.528434 | Val ImbOLL 2.510112 | Val TC Est -0.306941 | Val CCC 0.322079 | Val Acc 0.472727 | Val RMSE 0.914529 | 3.54s
Epoch 05/20 | Train Total 1.528381 | ImbOLL 1.526172 | TC Est -0.220819 | Val ImbOLL 2.854937 | Val TC Est -0.654489 | Val CCC 0.284877 | Val Acc 0.527273 | Val RMSE 0.914529 | 3.34s
Epoch 06/20 | Train Total 1.529399 | ImbOLL 1.527034 | TC Est -0.236457 | Val ImbOLL 2.845413 | Val TC Est -0.680011 | Val CCC 0.352506 | Val Acc 0.472727 | Val RMSE 0.943880 | 3.30s
Epoch 07/20 | Train Total 1.495643 | ImbOLL 1.493091 | TC Est -0.255125 | Val ImbOLL 2.736570 | Val TC Est -0.569612 | Val CCC 0.272850 | Val Acc 0.527273 | Val RMSE 0.914529 | 3.27s
Epoch 08/20 | Train Total 1.389986 | ImbOLL 1.384670 | TC Est -0.531596 | Val ImbOLL 3.204997 | Val TC Est -1.249778 | Val CCC 0.326998 | Val Acc 0.545455 | Val RMSE 0.904534 | 3.11s
Epoch 09/20 | Train Total 1.523635 | ImbOLL 1.519104 | TC Est -0.453064 | Val ImbOLL 2.869052 | Val TC Est -0.773101 | Val CCC 0.286377 | Val Acc 0.490909 | Val RMSE 0.934199 | 3.17s
Epoch 10/20 | Train Total 1.450309 | ImbOLL 1.447084 | TC Est -0.322546 | Val ImbOLL 2.680646 | Val TC Est -0.664449 | Val CCC 0.253824 | Val Acc 0.472727 | Val RMSE 0.943880 | 3.16s
Epoch 11/20 | Train Total 1.453441 | ImbOLL 1.450330 | TC Est -0.311040 | Val ImbOLL 2.584339 | Val TC Est -0.493068 | Val CCC 0.261804 | Val Acc 0.509091 | Val RMSE 0.924416 | 3.15s
Epoch 12/20 | Train Total 1.353524 | ImbOLL 1.351091 | TC Est -0.243323 | Val ImbOLL 3.093961 | Val TC Est -1.021168 | Val CCC 0.294623 | Val Acc 0.490909 | Val RMSE 1.009050 | 3.15s
Epoch 13/20 | Train Total 1.403351 | ImbOLL 1.399084 | TC Est -0.426716 | Val ImbOLL 2.691899 | Val TC Est -0.817835 | Val CCC 0.267522 | Val Acc 0.472727 | Val RMSE 0.914529 | 3.14s
Epoch 14/20 | Train Total 1.514113 | ImbOLL 1.506249 | TC Est -0.786334 | Val ImbOLL 2.693183 | Val TC Est -0.822138 | Val CCC 0.287082 | Val Acc 0.472727 | Val RMSE 0.943880 | 3.13s
Epoch 15/20 | Train Total 1.313134 | ImbOLL 1.307611 | TC Est -0.552296 | Val ImbOLL 3.336861 | Val TC Est -1.366290 | Val CCC 0.319925 | Val Acc 0.509091 | Val RMSE 0.972345 | 3.14s
Epoch 16/20 | Train Total 1.403975 | ImbOLL 1.394144 | TC Est -0.983084 | Val ImbOLL 2.985528 | Val TC Est -0.862001 | Val CCC 0.344267 | Val Acc 0.454545 | Val RMSE 0.924416 | 3.12s
Epoch 17/20 | Train Total 1.419531 | ImbOLL 1.417022 | TC Est -0.250946 | Val ImbOLL 2.672522 | Val TC Est -0.475940 | Val CCC 0.306065 | Val Acc 0.418182 | Val RMSE 0.943880 | 3.12s
Epoch 18/20 | Train Total 1.344933 | ImbOLL 1.343326 | TC Est -0.160683 | Val ImbOLL 2.999943 | Val TC Est -0.792209 | Val CCC 0.345993 | Val Acc 0.527273 | Val RMSE 0.914529 | 3.12s
Epoch 19/20 | Train Total 1.411810 | ImbOLL 1.407852 | TC Est -0.395873 | Val ImbOLL 2.756020 | Val TC Est -0.655623 | Val CCC 0.287760 | Val Acc 0.454545 | Val RMSE 0.953463 | 3.12s
Epoch 20/20 | Train Total 1.349122 | ImbOLL 1.347417 | TC Est -0.170500 | Val ImbOLL 2.850666 | Val TC Est -0.709994 | Val CCC 0.344267 | Val Acc 0.454545 | Val RMSE 0.924416 | 3.12s
====================================================================================================
TCMax训练完成：Seed=100，Q1
最佳Val ImbOLL：2.510112，Epoch=4
最佳Val CCC：0.352506，Epoch=6
====================================================================================================
文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q1_PHQ_8NoInterest/seed_1234/best_loss.pt
语音Best Loss： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_1234/question_1/best_loss.pt
文本保存Epoch： 7
语音保存Epoch： 18
文本缺少参数： []
文本多余参数： []
语音缺少参数： []
语音多余参数： []
====================================================================================================
开始TCMax训练：Seed=1234，Q1，PHQ_8NoInterest
实验类型：Text + Audio + TCMax
TCMax Lambda：0.01
每批负组合集合数：4
类别数量： [81, 57, 20, 5]
ImbOLL权重： [1.4185717105865479, 1.6910496950149536, 2.854820728302002, 5.709641456604004]
输出目录： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/tcmax_text_audio/lambda_0p01_neg_4/seed_1234/question_1
====================================================================================================
Epoch 01/20 | Train Total 2.232855 | ImbOLL 2.231576 | TC Est -0.127886 | Val ImbOLL 2.722989 | Val TC Est -0.256491 | Val CCC 0.061537 | Val Acc 0.527273 | Val RMSE 1.103713 | 3.19s
Epoch 02/20 | Train Total 1.731618 | ImbOLL 1.727193 | TC Est -0.442533 | Val ImbOLL 2.850670 | Val TC Est -1.442129 | Val CCC 0.343766 | Val Acc 0.490909 | Val RMSE 0.934199 | 3.14s
Epoch 03/20 | Train Total 1.621628 | ImbOLL 1.606004 | TC Est -1.562443 | Val ImbOLL 2.415841 | Val TC Est -0.872051 | Val CCC 0.370120 | Val Acc 0.509091 | Val RMSE 0.894427 | 3.12s
Epoch 04/20 | Train Total 1.472893 | ImbOLL 1.463656 | TC Est -0.923676 | Val ImbOLL 2.537044 | Val TC Est -0.717804 | Val CCC 0.379276 | Val Acc 0.545455 | Val RMSE 0.904534 | 3.12s
Epoch 05/20 | Train Total 1.477706 | ImbOLL 1.465674 | TC Est -1.203175 | Val ImbOLL 2.483359 | Val TC Est -1.105811 | Val CCC 0.415486 | Val Acc 0.490909 | Val RMSE 0.873863 | 3.10s
Epoch 06/20 | Train Total 1.349346 | ImbOLL 1.336047 | TC Est -1.329895 | Val ImbOLL 3.181128 | Val TC Est -1.514539 | Val CCC 0.225616 | Val Acc 0.490909 | Val RMSE 1.009050 | 3.10s
Epoch 07/20 | Train Total 1.380974 | ImbOLL 1.372766 | TC Est -0.820844 | Val ImbOLL 2.546030 | Val TC Est -0.574343 | Val CCC 0.327272 | Val Acc 0.436364 | Val RMSE 0.852803 | 3.10s
Epoch 08/20 | Train Total 1.616177 | ImbOLL 1.610371 | TC Est -0.580658 | Val ImbOLL 2.733195 | Val TC Est -0.625928 | Val CCC 0.214079 | Val Acc 0.490909 | Val RMSE 1.009050 | 3.10s
Epoch 09/20 | Train Total 1.453965 | ImbOLL 1.448396 | TC Est -0.556921 | Val ImbOLL 2.517154 | Val TC Est -0.542682 | Val CCC 0.399718 | Val Acc 0.545455 | Val RMSE 0.873863 | 3.11s
Epoch 10/20 | Train Total 1.510367 | ImbOLL 1.501794 | TC Est -0.857318 | Val ImbOLL 2.468226 | Val TC Est -0.453624 | Val CCC 0.350906 | Val Acc 0.490909 | Val RMSE 0.904534 | 3.10s
Epoch 11/20 | Train Total 1.428885 | ImbOLL 1.423046 | TC Est -0.583970 | Val ImbOLL 2.580339 | Val TC Est -0.555276 | Val CCC 0.379494 | Val Acc 0.509091 | Val RMSE 0.894427 | 3.11s
Epoch 12/20 | Train Total 1.563079 | ImbOLL 1.560680 | TC Est -0.239899 | Val ImbOLL 3.077612 | Val TC Est -0.703797 | Val CCC 0.225616 | Val Acc 0.490909 | Val RMSE 1.009050 | 3.09s
Epoch 13/20 | Train Total 1.532089 | ImbOLL 1.527229 | TC Est -0.485937 | Val ImbOLL 2.380492 | Val TC Est -0.229797 | Val CCC 0.319946 | Val Acc 0.436364 | Val RMSE 0.904534 | 3.17s
Epoch 14/20 | Train Total 1.478614 | ImbOLL 1.477143 | TC Est -0.147163 | Val ImbOLL 2.568922 | Val TC Est -0.333576 | Val CCC 0.305775 | Val Acc 0.545455 | Val RMSE 0.934199 | 3.12s
Epoch 15/20 | Train Total 1.524115 | ImbOLL 1.523747 | TC Est -0.036816 | Val ImbOLL 2.474411 | Val TC Est -0.318444 | Val CCC 0.413590 | Val Acc 0.472727 | Val RMSE 0.884205 | 3.08s
Epoch 16/20 | Train Total 1.525733 | ImbOLL 1.524535 | TC Est -0.119723 | Val ImbOLL 2.451561 | Val TC Est -0.293929 | Val CCC 0.380744 | Val Acc 0.527273 | Val RMSE 0.884205 | 3.19s
Epoch 17/20 | Train Total 1.452556 | ImbOLL 1.450662 | TC Est -0.189416 | Val ImbOLL 2.573978 | Val TC Est -0.383018 | Val CCC 0.399718 | Val Acc 0.545455 | Val RMSE 0.873863 | 3.16s
Epoch 18/20 | Train Total 1.475582 | ImbOLL 1.473313 | TC Est -0.226920 | Val ImbOLL 2.623226 | Val TC Est -0.377436 | Val CCC 0.352747 | Val Acc 0.509091 | Val RMSE 0.924416 | 3.12s
Epoch 19/20 | Train Total 1.439203 | ImbOLL 1.436072 | TC Est -0.313107 | Val ImbOLL 2.490720 | Val TC Est -0.515792 | Val CCC 0.366486 | Val Acc 0.381818 | Val RMSE 0.904534 | 3.10s
Epoch 20/20 | Train Total 1.412982 | ImbOLL 1.409558 | TC Est -0.342377 | Val ImbOLL 2.519690 | Val TC Est -0.585436 | Val CCC 0.323256 | Val Acc 0.545455 | Val RMSE 0.904534 | 3.15s
====================================================================================================
TCMax训练完成：Seed=1234，Q1
最佳Val ImbOLL：2.380492，Epoch=13
最佳Val CCC：0.415486，Epoch=5
====================================================================================================

In [226]:
q1_seed42_tcmax_low_result = train_fusion_question_tcmax(question_index=0, seed=42, lambda_tc=0.001, num_negative_sets=4)
q1_seed100_tcmax_low_result = train_fusion_question_tcmax(question_index=0, seed=100, lambda_tc=0.001, num_negative_sets=4)
q1_seed1234_tcmax_low_result = train_fusion_question_tcmax(question_index=0, seed=1234, lambda_tc=0.001, num_negative_sets=4)

文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q1_PHQ_8NoInterest/seed_42/best_loss.pt
语音Best Loss： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_42/question_1/best_loss.pt
文本保存Epoch： 13
语音保存Epoch： 10
文本缺少参数： []
文本多余参数： []
语音缺少参数： []
语音多余参数： []
====================================================================================================
开始TCMax训练：Seed=42，Q1，PHQ_8NoInterest
实验类型：Text + Audio + TCMax
TCMax Lambda：0.001
每批负组合集合数：4
类别数量： [81, 57, 20, 5]
ImbOLL权重： [1.4185717105865479, 1.6910496950149536, 2.854820728302002, 5.709641456604004]
输出目录： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/tcmax_text_audio/lambda_0p001_neg_4/seed_42/question_1
====================================================================================================
Epoch 01/20 | Train Total 2.165002 | ImbOLL 2.164919 | TC Est -0.083103 | Val ImbOLL 2.612851 | Val TC Est -0.429186 | Val CCC 0.294487 | Val Acc 0.490909 | Val RMSE 0.981650 | 3.88s
Epoch 02/20 | Train Total 1.270405 | ImbOLL 1.269646 | TC Est -0.758893 | Val ImbOLL 3.171395 | Val TC Est -2.220035 | Val CCC 0.280751 | Val Acc 0.600000 | Val RMSE 0.953463 | 3.37s
Epoch 03/20 | Train Total 1.279758 | ImbOLL 1.276738 | TC Est -3.019838 | Val ImbOLL 2.754268 | Val TC Est -2.344537 | Val CCC 0.335234 | Val Acc 0.527273 | Val RMSE 0.934199 | 3.52s
Epoch 04/20 | Train Total 1.185808 | ImbOLL 1.183944 | TC Est -1.863329 | Val ImbOLL 2.759434 | Val TC Est -2.256976 | Val CCC 0.276271 | Val Acc 0.581818 | Val RMSE 0.934199 | 3.66s
Epoch 05/20 | Train Total 1.104970 | ImbOLL 1.103042 | TC Est -1.927748 | Val ImbOLL 3.013052 | Val TC Est -2.856085 | Val CCC 0.346642 | Val Acc 0.545455 | Val RMSE 0.924416 | 3.34s
Epoch 06/20 | Train Total 1.195140 | ImbOLL 1.193252 | TC Est -1.888541 | Val ImbOLL 2.512951 | Val TC Est -2.037511 | Val CCC 0.354914 | Val Acc 0.600000 | Val RMSE 0.894427 | 3.36s
Epoch 07/20 | Train Total 1.212265 | ImbOLL 1.210015 | TC Est -2.250047 | Val ImbOLL 2.854967 | Val TC Est -2.722893 | Val CCC 0.355716 | Val Acc 0.581818 | Val RMSE 0.852803 | 3.24s
Epoch 08/20 | Train Total 1.234818 | ImbOLL 1.232761 | TC Est -2.057084 | Val ImbOLL 2.777821 | Val TC Est -2.086728 | Val CCC 0.308503 | Val Acc 0.509091 | Val RMSE 0.943880 | 3.36s
Epoch 09/20 | Train Total 1.054637 | ImbOLL 1.053084 | TC Est -1.552933 | Val ImbOLL 3.248819 | Val TC Est -1.711407 | Val CCC 0.400501 | Val Acc 0.581818 | Val RMSE 0.797724 | 3.29s
Epoch 10/20 | Train Total 1.108019 | ImbOLL 1.105908 | TC Est -2.111625 | Val ImbOLL 2.833752 | Val TC Est -1.343807 | Val CCC 0.340990 | Val Acc 0.436364 | Val RMSE 0.852803 | 3.14s
Epoch 11/20 | Train Total 1.033311 | ImbOLL 1.031580 | TC Est -1.730799 | Val ImbOLL 3.038871 | Val TC Est -2.729265 | Val CCC 0.299634 | Val Acc 0.490909 | Val RMSE 0.953463 | 3.11s
Epoch 12/20 | Train Total 0.997401 | ImbOLL 0.995276 | TC Est -2.125507 | Val ImbOLL 2.661424 | Val TC Est -2.157038 | Val CCC 0.484603 | Val Acc 0.545455 | Val RMSE 0.786245 | 3.13s
Epoch 13/20 | Train Total 1.044835 | ImbOLL 1.042946 | TC Est -1.889489 | Val ImbOLL 2.974831 | Val TC Est -1.807168 | Val CCC 0.362983 | Val Acc 0.454545 | Val RMSE 0.842075 | 3.15s
Epoch 14/20 | Train Total 1.001774 | ImbOLL 0.999781 | TC Est -1.992869 | Val ImbOLL 2.884478 | Val TC Est -2.253285 | Val CCC 0.421458 | Val Acc 0.581818 | Val RMSE 0.797724 | 3.14s
Epoch 15/20 | Train Total 0.951632 | ImbOLL 0.948999 | TC Est -2.633057 | Val ImbOLL 3.022358 | Val TC Est -2.716405 | Val CCC 0.416758 | Val Acc 0.545455 | Val RMSE 0.820200 | 3.15s
Epoch 16/20 | Train Total 1.008285 | ImbOLL 1.005945 | TC Est -2.339506 | Val ImbOLL 2.703352 | Val TC Est -2.287457 | Val CCC 0.471300 | Val Acc 0.563636 | Val RMSE 0.809040 | 3.37s
Epoch 17/20 | Train Total 0.959779 | ImbOLL 0.958230 | TC Est -1.548891 | Val ImbOLL 2.688910 | Val TC Est -1.895419 | Val CCC 0.404316 | Val Acc 0.581818 | Val RMSE 0.852803 | 3.62s
Epoch 18/20 | Train Total 0.991664 | ImbOLL 0.990197 | TC Est -1.466113 | Val ImbOLL 2.824597 | Val TC Est -2.610541 | Val CCC 0.354158 | Val Acc 0.581818 | Val RMSE 0.904534 | 3.32s
Epoch 19/20 | Train Total 1.166834 | ImbOLL 1.164714 | TC Est -2.120121 | Val ImbOLL 2.863732 | Val TC Est -2.026260 | Val CCC 0.397074 | Val Acc 0.527273 | Val RMSE 0.831209 | 3.27s
Epoch 20/20 | Train Total 1.005300 | ImbOLL 1.003037 | TC Est -2.263058 | Val ImbOLL 2.707438 | Val TC Est -1.317561 | Val CCC 0.333914 | Val Acc 0.527273 | Val RMSE 0.863397 | 3.44s
====================================================================================================
TCMax训练完成：Seed=42，Q1
最佳Val ImbOLL：2.512951，Epoch=6
最佳Val CCC：0.484603，Epoch=12
====================================================================================================
文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q1_PHQ_8NoInterest/seed_100/best_loss.pt
语音Best Loss： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_100/question_1/best_loss.pt
文本保存Epoch： 10
语音保存Epoch： 8
文本缺少参数： []
文本多余参数： []
语音缺少参数： []
语音多余参数： []
====================================================================================================
开始TCMax训练：Seed=100，Q1，PHQ_8NoInterest
实验类型：Text + Audio + TCMax
TCMax Lambda：0.001
每批负组合集合数：4
类别数量： [81, 57, 20, 5]
ImbOLL权重： [1.4185717105865479, 1.6910496950149536, 2.854820728302002, 5.709641456604004]
输出目录： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/tcmax_text_audio/lambda_0p001_neg_4/seed_100/question_1
====================================================================================================
Epoch 01/20 | Train Total 2.084541 | ImbOLL 2.084410 | TC Est -0.130880 | Val ImbOLL 2.897838 | Val TC Est -0.421543 | Val CCC 0.268730 | Val Acc 0.490909 | Val RMSE 1.009050 | 3.29s
Epoch 02/20 | Train Total 1.545652 | ImbOLL 1.544808 | TC Est -0.843139 | Val ImbOLL 3.779355 | Val TC Est -2.243468 | Val CCC 0.277153 | Val Acc 0.472727 | Val RMSE 1.018019 | 3.27s
Epoch 03/20 | Train Total 1.674145 | ImbOLL 1.672167 | TC Est -1.977806 | Val ImbOLL 2.951522 | Val TC Est -1.296934 | Val CCC 0.273909 | Val Acc 0.509091 | Val RMSE 0.924416 | 3.25s
Epoch 04/20 | Train Total 1.505906 | ImbOLL 1.505004 | TC Est -0.902196 | Val ImbOLL 2.525944 | Val TC Est -0.480712 | Val CCC 0.295921 | Val Acc 0.436364 | Val RMSE 0.990867 | 3.19s
Epoch 05/20 | Train Total 1.534940 | ImbOLL 1.534333 | TC Est -0.607307 | Val ImbOLL 2.702697 | Val TC Est -1.031009 | Val CCC 0.275895 | Val Acc 0.472727 | Val RMSE 0.943880 | 3.18s
Epoch 06/20 | Train Total 1.521585 | ImbOLL 1.521064 | TC Est -0.521925 | Val ImbOLL 2.680392 | Val TC Est -0.717118 | Val CCC 0.296699 | Val Acc 0.472727 | Val RMSE 0.943880 | 3.13s
Epoch 07/20 | Train Total 1.488065 | ImbOLL 1.487641 | TC Est -0.424148 | Val ImbOLL 2.718319 | Val TC Est -0.830368 | Val CCC 0.230365 | Val Acc 0.472727 | Val RMSE 0.943880 | 3.17s
Epoch 08/20 | Train Total 1.393942 | ImbOLL 1.393126 | TC Est -0.815800 | Val ImbOLL 2.999383 | Val TC Est -1.816032 | Val CCC 0.353168 | Val Acc 0.490909 | Val RMSE 0.934199 | 3.46s
Epoch 09/20 | Train Total 1.490603 | ImbOLL 1.489753 | TC Est -0.850437 | Val ImbOLL 2.735183 | Val TC Est -1.231188 | Val CCC 0.326645 | Val Acc 0.509091 | Val RMSE 0.924416 | 3.74s
Epoch 10/20 | Train Total 1.389243 | ImbOLL 1.388290 | TC Est -0.952397 | Val ImbOLL 2.898452 | Val TC Est -1.682551 | Val CCC 0.286377 | Val Acc 0.490909 | Val RMSE 0.934199 | 3.61s
Epoch 11/20 | Train Total 1.431410 | ImbOLL 1.430426 | TC Est -0.984650 | Val ImbOLL 2.592912 | Val TC Est -1.076621 | Val CCC 0.299872 | Val Acc 0.436364 | Val RMSE 0.904534 | 3.32s
Epoch 12/20 | Train Total 1.324601 | ImbOLL 1.323679 | TC Est -0.922216 | Val ImbOLL 3.094305 | Val TC Est -1.819745 | Val CCC 0.362581 | Val Acc 0.527273 | Val RMSE 0.943880 | 3.34s
Epoch 13/20 | Train Total 1.314324 | ImbOLL 1.313225 | TC Est -1.098778 | Val ImbOLL 2.856265 | Val TC Est -1.391974 | Val CCC 0.278637 | Val Acc 0.490909 | Val RMSE 0.904534 | 3.26s
Epoch 14/20 | Train Total 1.391726 | ImbOLL 1.390263 | TC Est -1.463658 | Val ImbOLL 2.827218 | Val TC Est -1.740813 | Val CCC 0.267969 | Val Acc 0.436364 | Val RMSE 0.962950 | 3.18s
Epoch 15/20 | Train Total 1.276590 | ImbOLL 1.275259 | TC Est -1.330359 | Val ImbOLL 3.452776 | Val TC Est -2.309201 | Val CCC 0.390033 | Val Acc 0.527273 | Val RMSE 0.914529 | 3.11s
Epoch 16/20 | Train Total 1.365459 | ImbOLL 1.363544 | TC Est -1.914619 | Val ImbOLL 3.099803 | Val TC Est -1.590380 | Val CCC 0.313531 | Val Acc 0.490909 | Val RMSE 0.904534 | 2.96s
Epoch 17/20 | Train Total 1.379547 | ImbOLL 1.378683 | TC Est -0.864233 | Val ImbOLL 2.767060 | Val TC Est -0.968523 | Val CCC 0.401227 | Val Acc 0.527273 | Val RMSE 0.884205 | 2.99s
Epoch 18/20 | Train Total 1.324907 | ImbOLL 1.324301 | TC Est -0.606152 | Val ImbOLL 3.017390 | Val TC Est -1.161718 | Val CCC 0.326998 | Val Acc 0.545455 | Val RMSE 0.904534 | 3.12s
Epoch 19/20 | Train Total 1.259012 | ImbOLL 1.257851 | TC Est -1.160832 | Val ImbOLL 2.776396 | Val TC Est -1.170290 | Val CCC 0.333567 | Val Acc 0.472727 | Val RMSE 0.914529 | 3.16s
Epoch 20/20 | Train Total 1.419902 | ImbOLL 1.419289 | TC Est -0.612668 | Val ImbOLL 3.019126 | Val TC Est -1.452872 | Val CCC 0.345430 | Val Acc 0.509091 | Val RMSE 0.924416 | 3.12s
====================================================================================================
TCMax训练完成：Seed=100，Q1
最佳Val ImbOLL：2.525944，Epoch=4
最佳Val CCC：0.401227，Epoch=17
====================================================================================================
文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q1_PHQ_8NoInterest/seed_1234/best_loss.pt
语音Best Loss： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_1234/question_1/best_loss.pt
文本保存Epoch： 7
语音保存Epoch： 18
文本缺少参数： []
文本多余参数： []
语音缺少参数： []
语音多余参数： []
====================================================================================================
开始TCMax训练：Seed=1234，Q1，PHQ_8NoInterest
实验类型：Text + Audio + TCMax
TCMax Lambda：0.001
每批负组合集合数：4
类别数量： [81, 57, 20, 5]
ImbOLL权重： [1.4185717105865479, 1.6910496950149536, 2.854820728302002, 5.709641456604004]
输出目录： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/tcmax_text_audio/lambda_0p001_neg_4/seed_1234/question_1
====================================================================================================
Epoch 01/20 | Train Total 2.242250 | ImbOLL 2.242103 | TC Est -0.146688 | Val ImbOLL 2.688455 | Val TC Est -0.251518 | Val CCC 0.068691 | Val Acc 0.545455 | Val RMSE 1.095445 | 3.11s
Epoch 02/20 | Train Total 1.722323 | ImbOLL 1.721759 | TC Est -0.563520 | Val ImbOLL 3.087888 | Val TC Est -2.133197 | Val CCC 0.282505 | Val Acc 0.472727 | Val RMSE 0.990867 | 3.15s
Epoch 03/20 | Train Total 1.607297 | ImbOLL 1.605010 | TC Est -2.286655 | Val ImbOLL 2.439467 | Val TC Est -1.556085 | Val CCC 0.370120 | Val Acc 0.509091 | Val RMSE 0.894427 | 3.11s
Epoch 04/20 | Train Total 1.474423 | ImbOLL 1.472615 | TC Est -1.808675 | Val ImbOLL 2.464400 | Val TC Est -1.345842 | Val CCC 0.379494 | Val Acc 0.509091 | Val RMSE 0.894427 | 3.08s
Epoch 05/20 | Train Total 1.455773 | ImbOLL 1.453482 | TC Est -2.290866 | Val ImbOLL 2.525498 | Val TC Est -2.187211 | Val CCC 0.415486 | Val Acc 0.490909 | Val RMSE 0.873863 | 3.09s
Epoch 06/20 | Train Total 1.343512 | ImbOLL 1.340949 | TC Est -2.562628 | Val ImbOLL 3.444853 | Val TC Est -3.236926 | Val CCC 0.215410 | Val Acc 0.490909 | Val RMSE 1.009050 | 3.14s
Epoch 07/20 | Train Total 1.431968 | ImbOLL 1.429828 | TC Est -2.139909 | Val ImbOLL 2.594361 | Val TC Est -1.278153 | Val CCC 0.280889 | Val Acc 0.400000 | Val RMSE 0.873863 | 3.13s
Epoch 08/20 | Train Total 1.616872 | ImbOLL 1.615536 | TC Est -1.336008 | Val ImbOLL 2.728926 | Val TC Est -1.393796 | Val CCC 0.175068 | Val Acc 0.454545 | Val RMSE 1.026911 | 3.13s
Epoch 09/20 | Train Total 1.439933 | ImbOLL 1.438563 | TC Est -1.369912 | Val ImbOLL 2.523323 | Val TC Est -1.402964 | Val CCC 0.399718 | Val Acc 0.545455 | Val RMSE 0.873863 | 3.13s
Epoch 10/20 | Train Total 1.502164 | ImbOLL 1.499973 | TC Est -2.190315 | Val ImbOLL 2.456413 | Val TC Est -1.247620 | Val CCC 0.350906 | Val Acc 0.490909 | Val RMSE 0.904534 | 3.11s
Epoch 11/20 | Train Total 1.426915 | ImbOLL 1.425094 | TC Est -1.821598 | Val ImbOLL 2.588285 | Val TC Est -1.543579 | Val CCC 0.370120 | Val Acc 0.509091 | Val RMSE 0.894427 | 3.09s
Epoch 12/20 | Train Total 1.567268 | ImbOLL 1.566215 | TC Est -1.052669 | Val ImbOLL 2.938569 | Val TC Est -1.606209 | Val CCC 0.264009 | Val Acc 0.454545 | Val RMSE 1.000000 | 3.12s
Epoch 13/20 | Train Total 1.501729 | ImbOLL 1.500411 | TC Est -1.317716 | Val ImbOLL 2.388895 | Val TC Est -0.650530 | Val CCC 0.310048 | Val Acc 0.436364 | Val RMSE 0.904534 | 3.09s
Epoch 14/20 | Train Total 1.450688 | ImbOLL 1.449722 | TC Est -0.965988 | Val ImbOLL 2.588001 | Val TC Est -0.911383 | Val CCC 0.294413 | Val Acc 0.563636 | Val RMSE 0.924416 | 3.10s
Epoch 15/20 | Train Total 1.522973 | ImbOLL 1.522273 | TC Est -0.699558 | Val ImbOLL 2.516261 | Val TC Est -0.994429 | Val CCC 0.423085 | Val Acc 0.490909 | Val RMSE 0.873863 | 3.13s
Epoch 16/20 | Train Total 1.480843 | ImbOLL 1.479926 | TC Est -0.916947 | Val ImbOLL 2.463052 | Val TC Est -0.959091 | Val CCC 0.370120 | Val Acc 0.509091 | Val RMSE 0.894427 | 3.44s
Epoch 17/20 | Train Total 1.447941 | ImbOLL 1.446950 | TC Est -0.990884 | Val ImbOLL 2.647779 | Val TC Est -1.197713 | Val CCC 0.418414 | Val Acc 0.563636 | Val RMSE 0.863397 | 3.56s
Epoch 18/20 | Train Total 1.486388 | ImbOLL 1.485523 | TC Est -0.865116 | Val ImbOLL 2.592627 | Val TC Est -0.919222 | Val CCC 0.305775 | Val Acc 0.545455 | Val RMSE 0.934199 | 3.40s
Epoch 19/20 | Train Total 1.448154 | ImbOLL 1.447042 | TC Est -1.111833 | Val ImbOLL 2.473498 | Val TC Est -1.198472 | Val CCC 0.355148 | Val Acc 0.363636 | Val RMSE 0.943880 | 3.36s
Epoch 20/20 | Train Total 1.463997 | ImbOLL 1.462851 | TC Est -1.145982 | Val ImbOLL 2.554128 | Val TC Est -1.270052 | Val CCC 0.323256 | Val Acc 0.545455 | Val RMSE 0.904534 | 3.23s
====================================================================================================
TCMax训练完成：Seed=1234，Q1
最佳Val ImbOLL：2.388895，Epoch=13
最佳Val CCC：0.423085，Epoch=15
====================================================================================================

In [227]:
q8_seed42_tcmax_result = train_fusion_question_tcmax(question_index=7, seed=42, lambda_tc=0.01, num_negative_sets=4)
q8_seed100_tcmax_result = train_fusion_question_tcmax(question_index=7, seed=100, lambda_tc=0.01, num_negative_sets=4)
q8_seed1234_tcmax_result = train_fusion_question_tcmax(question_index=7, seed=1234, lambda_tc=0.01, num_negative_sets=4)

文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q8_PHQ_8Moving/seed_42/best_loss.pt
语音Best Loss： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_42/question_8/best_loss.pt
文本保存Epoch： 11
语音保存Epoch： 12
文本缺少参数： []
文本多余参数： []
语音缺少参数： []
语音多余参数： []
====================================================================================================
开始TCMax训练：Seed=42，Q8，PHQ_8Moving
实验类型：Text + Audio + TCMax
TCMax Lambda：0.01
每批负组合集合数：4
类别数量： [128, 20, 9, 6]
ImbOLL权重： [1.1284668445587158, 2.854820728302002, 4.2557148933410645, 5.212165355682373]
输出目录： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/tcmax_text_audio/lambda_0p01_neg_4/seed_42/question_8
====================================================================================================
Epoch 01/20 | Train Total 3.058477 | ImbOLL 3.051190 | TC Est -0.728701 | Val ImbOLL 1.806783 | Val TC Est -0.454753 | Val CCC 0.134564 | Val Acc 0.654545 | Val RMSE 0.738549 | 4.25s
Epoch 02/20 | Train Total 1.552104 | ImbOLL 1.533513 | TC Est -1.859126 | Val ImbOLL 2.506559 | Val TC Est -2.925446 | Val CCC 0.303862 | Val Acc 0.563636 | Val RMSE 0.700649 | 3.52s
Epoch 03/20 | Train Total 1.336695 | ImbOLL 1.285849 | TC Est -5.084555 | Val ImbOLL 2.101520 | Val TC Est -1.723650 | Val CCC 0.221589 | Val Acc 0.527273 | Val RMSE 0.726135 | 3.44s
Epoch 04/20 | Train Total 1.409542 | ImbOLL 1.384854 | TC Est -2.468792 | Val ImbOLL 1.894877 | Val TC Est -0.741282 | Val CCC 0.302978 | Val Acc 0.545455 | Val RMSE 0.852803 | 3.41s
Epoch 05/20 | Train Total 1.292231 | ImbOLL 1.279790 | TC Est -1.244138 | Val ImbOLL 2.803198 | Val TC Est -1.549087 | Val CCC 0.201558 | Val Acc 0.581818 | Val RMSE 0.762770 | 3.33s
Epoch 06/20 | Train Total 1.499118 | ImbOLL 1.469230 | TC Est -2.988790 | Val ImbOLL 1.840665 | Val TC Est -0.358278 | Val CCC 0.257360 | Val Acc 0.545455 | Val RMSE 0.852803 | 3.29s
Epoch 07/20 | Train Total 1.370149 | ImbOLL 1.363269 | TC Est -0.687998 | Val ImbOLL 2.365128 | Val TC Est -0.694691 | Val CCC 0.181931 | Val Acc 0.581818 | Val RMSE 0.797724 | 3.31s
Epoch 08/20 | Train Total 1.311908 | ImbOLL 1.303426 | TC Est -0.848239 | Val ImbOLL 2.008571 | Val TC Est -0.386133 | Val CCC 0.218234 | Val Acc 0.545455 | Val RMSE 0.786245 | 3.28s
Epoch 09/20 | Train Total 1.196690 | ImbOLL 1.184953 | TC Est -1.173705 | Val ImbOLL 2.159614 | Val TC Est -0.572518 | Val CCC 0.261252 | Val Acc 0.527273 | Val RMSE 0.726135 | 3.35s
Epoch 10/20 | Train Total 1.342362 | ImbOLL 1.328570 | TC Est -1.379237 | Val ImbOLL 2.222040 | Val TC Est -0.493186 | Val CCC 0.223922 | Val Acc 0.600000 | Val RMSE 0.713506 | 3.26s
Epoch 11/20 | Train Total 1.249946 | ImbOLL 1.240936 | TC Est -0.900947 | Val ImbOLL 2.629554 | Val TC Est -0.696920 | Val CCC 0.181931 | Val Acc 0.581818 | Val RMSE 0.797724 | 3.31s
Epoch 12/20 | Train Total 1.276260 | ImbOLL 1.264436 | TC Est -1.182377 | Val ImbOLL 2.141579 | Val TC Est -0.330321 | Val CCC 0.329096 | Val Acc 0.545455 | Val RMSE 0.820200 | 3.27s
Epoch 13/20 | Train Total 1.118306 | ImbOLL 1.112369 | TC Est -0.593755 | Val ImbOLL 2.141239 | Val TC Est -0.322556 | Val CCC 0.244011 | Val Acc 0.545455 | Val RMSE 0.852803 | 3.15s
Epoch 14/20 | Train Total 1.202447 | ImbOLL 1.199172 | TC Est -0.327439 | Val ImbOLL 2.518736 | Val TC Est -0.479505 | Val CCC 0.163165 | Val Acc 0.563636 | Val RMSE 0.809040 | 3.15s
Epoch 15/20 | Train Total 1.284247 | ImbOLL 1.271188 | TC Est -1.305920 | Val ImbOLL 2.638920 | Val TC Est -0.548137 | Val CCC 0.199586 | Val Acc 0.527273 | Val RMSE 0.797724 | 3.15s
Epoch 16/20 | Train Total 1.180573 | ImbOLL 1.174438 | TC Est -0.613495 | Val ImbOLL 2.848706 | Val TC Est -0.517676 | Val CCC 0.181931 | Val Acc 0.581818 | Val RMSE 0.797724 | 3.13s
Epoch 17/20 | Train Total 1.456275 | ImbOLL 1.448705 | TC Est -0.757019 | Val ImbOLL 2.498903 | Val TC Est -0.373646 | Val CCC 0.199586 | Val Acc 0.527273 | Val RMSE 0.797724 | 3.14s
Epoch 18/20 | Train Total 1.267522 | ImbOLL 1.263577 | TC Est -0.394515 | Val ImbOLL 2.277575 | Val TC Est -0.262230 | Val CCC 0.260285 | Val Acc 0.545455 | Val RMSE 0.786245 | 3.15s
Epoch 19/20 | Train Total 1.150146 | ImbOLL 1.149439 | TC Est -0.070693 | Val ImbOLL 1.954641 | Val TC Est -0.151160 | Val CCC 0.208146 | Val Acc 0.527273 | Val RMSE 0.797724 | 3.01s
Epoch 20/20 | Train Total 1.254643 | ImbOLL 1.247956 | TC Est -0.668641 | Val ImbOLL 4.439386 | Val TC Est -1.067457 | Val CCC 0.236772 | Val Acc 0.618182 | Val RMSE 0.700649 | 2.91s
====================================================================================================
TCMax训练完成：Seed=42，Q8
最佳Val ImbOLL：1.806783，Epoch=1
最佳Val CCC：0.329096，Epoch=12
====================================================================================================
文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q8_PHQ_8Moving/seed_100/best_loss.pt
语音Best Loss： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_100/question_8/best_loss.pt
文本保存Epoch： 12
语音保存Epoch： 12
文本缺少参数： []
文本多余参数： []
语音缺少参数： []
语音多余参数： []
====================================================================================================
开始TCMax训练：Seed=100，Q8，PHQ_8Moving
实验类型：Text + Audio + TCMax
TCMax Lambda：0.01
每批负组合集合数：4
类别数量： [128, 20, 9, 6]
ImbOLL权重： [1.1284668445587158, 2.854820728302002, 4.2557148933410645, 5.212165355682373]
输出目录： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/tcmax_text_audio/lambda_0p01_neg_4/seed_100/question_8
====================================================================================================
Epoch 01/20 | Train Total 1.945703 | ImbOLL 1.943168 | TC Est -0.253468 | Val ImbOLL 2.331608 | Val TC Est -0.576958 | Val CCC -0.008657 | Val Acc 0.690909 | Val RMSE 0.786245 | 2.94s
Epoch 02/20 | Train Total 1.359091 | ImbOLL 1.346511 | TC Est -1.257918 | Val ImbOLL 3.324568 | Val TC Est -2.581672 | Val CCC 0.276907 | Val Acc 0.600000 | Val RMSE 0.786245 | 2.92s
Epoch 03/20 | Train Total 1.461976 | ImbOLL 1.417350 | TC Est -4.462565 | Val ImbOLL 2.601437 | Val TC Est -2.186057 | Val CCC 0.191011 | Val Acc 0.527273 | Val RMSE 0.924416 | 3.07s
Epoch 04/20 | Train Total 1.272586 | ImbOLL 1.238700 | TC Est -3.388631 | Val ImbOLL 3.719530 | Val TC Est -2.874413 | Val CCC 0.276907 | Val Acc 0.600000 | Val RMSE 0.786245 | 3.09s
Epoch 05/20 | Train Total 1.308257 | ImbOLL 1.272130 | TC Est -3.612720 | Val ImbOLL 2.522638 | Val TC Est -1.286432 | Val CCC 0.250113 | Val Acc 0.527273 | Val RMSE 0.797724 | 3.10s
Epoch 06/20 | Train Total 1.281226 | ImbOLL 1.269384 | TC Est -1.184133 | Val ImbOLL 3.224764 | Val TC Est -1.521849 | Val CCC 0.289210 | Val Acc 0.581818 | Val RMSE 0.762770 | 3.11s
Epoch 07/20 | Train Total 1.236860 | ImbOLL 1.216768 | TC Est -2.009123 | Val ImbOLL 2.850146 | Val TC Est -1.359479 | Val CCC 0.317865 | Val Acc 0.527273 | Val RMSE 0.762770 | 3.41s
Epoch 08/20 | Train Total 1.292479 | ImbOLL 1.267524 | TC Est -2.495502 | Val ImbOLL 3.934589 | Val TC Est -1.716363 | Val CCC 0.138644 | Val Acc 0.563636 | Val RMSE 0.774597 | 3.46s
Epoch 09/20 | Train Total 1.317899 | ImbOLL 1.305525 | TC Est -1.237404 | Val ImbOLL 2.703799 | Val TC Est -0.653355 | Val CCC 0.183649 | Val Acc 0.545455 | Val RMSE 0.884205 | 3.44s
Epoch 10/20 | Train Total 1.375904 | ImbOLL 1.371816 | TC Est -0.408756 | Val ImbOLL 2.479608 | Val TC Est -0.473273 | Val CCC 0.199586 | Val Acc 0.527273 | Val RMSE 0.797724 | 3.45s
Epoch 11/20 | Train Total 1.208501 | ImbOLL 1.196838 | TC Est -1.166320 | Val ImbOLL 3.607942 | Val TC Est -1.184047 | Val CCC 0.207383 | Val Acc 0.581818 | Val RMSE 0.863397 | 3.45s
Epoch 12/20 | Train Total 1.158627 | ImbOLL 1.151623 | TC Est -0.700435 | Val ImbOLL 2.624679 | Val TC Est -0.576055 | Val CCC 0.204978 | Val Acc 0.527273 | Val RMSE 0.914529 | 3.25s
Epoch 13/20 | Train Total 1.365145 | ImbOLL 1.358086 | TC Est -0.705867 | Val ImbOLL 2.924719 | Val TC Est -0.574617 | Val CCC 0.209662 | Val Acc 0.545455 | Val RMSE 0.786245 | 3.12s
Epoch 14/20 | Train Total 1.241980 | ImbOLL 1.236118 | TC Est -0.586120 | Val ImbOLL 3.232037 | Val TC Est -0.708095 | Val CCC 0.270809 | Val Acc 0.563636 | Val RMSE 0.774597 | 3.11s
Epoch 15/20 | Train Total 1.262781 | ImbOLL 1.258139 | TC Est -0.464272 | Val ImbOLL 3.059877 | Val TC Est -0.638556 | Val CCC 0.117961 | Val Acc 0.545455 | Val RMSE 0.786245 | 3.13s
Epoch 16/20 | Train Total 1.295949 | ImbOLL 1.287138 | TC Est -0.881068 | Val ImbOLL 2.798360 | Val TC Est -0.525039 | Val CCC 0.198742 | Val Acc 0.509091 | Val RMSE 0.842075 | 3.15s
Epoch 17/20 | Train Total 1.219863 | ImbOLL 1.218184 | TC Est -0.167847 | Val ImbOLL 3.034102 | Val TC Est -0.576001 | Val CCC 0.315007 | Val Acc 0.600000 | Val RMSE 0.750757 | 3.11s
Epoch 18/20 | Train Total 1.558435 | ImbOLL 1.554056 | TC Est -0.437902 | Val ImbOLL 3.457311 | Val TC Est -0.722648 | Val CCC 0.180810 | Val Acc 0.600000 | Val RMSE 0.750757 | 3.10s
Epoch 19/20 | Train Total 1.190537 | ImbOLL 1.189351 | TC Est -0.118645 | Val ImbOLL 2.867214 | Val TC Est -0.505538 | Val CCC 0.168402 | Val Acc 0.527273 | Val RMSE 0.894427 | 3.15s
Epoch 20/20 | Train Total 1.244382 | ImbOLL 1.239723 | TC Est -0.465849 | Val ImbOLL 3.312303 | Val TC Est -0.689402 | Val CCC 0.191721 | Val Acc 0.563636 | Val RMSE 0.894427 | 3.12s
====================================================================================================
TCMax训练完成：Seed=100，Q8
最佳Val ImbOLL：2.331608，Epoch=1
最佳Val CCC：0.317865，Epoch=7
====================================================================================================
文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q8_PHQ_8Moving/seed_1234/best_loss.pt
语音Best Loss： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_1234/question_8/best_loss.pt
文本保存Epoch： 1
语音保存Epoch： 21
文本缺少参数： []
文本多余参数： []
语音缺少参数： []
语音多余参数： []
====================================================================================================
开始TCMax训练：Seed=1234，Q8，PHQ_8Moving
实验类型：Text + Audio + TCMax
TCMax Lambda：0.01
每批负组合集合数：4
类别数量： [128, 20, 9, 6]
ImbOLL权重： [1.1284668445587158, 2.854820728302002, 4.2557148933410645, 5.212165355682373]
输出目录： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/tcmax_text_audio/lambda_0p01_neg_4/seed_1234/question_8
====================================================================================================
Epoch 01/20 | Train Total 2.253562 | ImbOLL 2.251543 | TC Est -0.201842 | Val ImbOLL 2.149393 | Val TC Est -0.232921 | Val CCC 0.000000 | Val Acc 0.709091 | Val RMSE 0.774597 | 3.20s
Epoch 02/20 | Train Total 2.166284 | ImbOLL 2.164004 | TC Est -0.228010 | Val ImbOLL 1.914445 | Val TC Est -0.185164 | Val CCC 0.099528 | Val Acc 0.654545 | Val RMSE 0.750757 | 3.38s
Epoch 03/20 | Train Total 2.051076 | ImbOLL 2.047555 | TC Est -0.352127 | Val ImbOLL 1.916640 | Val TC Est -0.225859 | Val CCC 0.089148 | Val Acc 0.636364 | Val RMSE 0.762770 | 3.84s
Epoch 04/20 | Train Total 2.002246 | ImbOLL 1.998452 | TC Est -0.379490 | Val ImbOLL 2.107937 | Val TC Est -0.363770 | Val CCC 0.111695 | Val Acc 0.654545 | Val RMSE 0.750757 | 3.37s
Epoch 05/20 | Train Total 2.008325 | ImbOLL 2.003220 | TC Est -0.510519 | Val ImbOLL 1.848006 | Val TC Est -0.187200 | Val CCC 0.000000 | Val Acc 0.709091 | Val RMSE 0.774597 | 3.31s
Epoch 06/20 | Train Total 2.016074 | ImbOLL 2.013560 | TC Est -0.251351 | Val ImbOLL 1.969624 | Val TC Est -0.278291 | Val CCC 0.111695 | Val Acc 0.654545 | Val RMSE 0.750757 | 3.26s
Epoch 07/20 | Train Total 2.156230 | ImbOLL 2.150895 | TC Est -0.533525 | Val ImbOLL 1.840568 | Val TC Est -0.156971 | Val CCC 0.101218 | Val Acc 0.636364 | Val RMSE 0.762770 | 3.26s
Epoch 08/20 | Train Total 1.967470 | ImbOLL 1.963363 | TC Est -0.410715 | Val ImbOLL 2.523945 | Val TC Est -0.794743 | Val CCC 0.076744 | Val Acc 0.636364 | Val RMSE 0.762770 | 3.25s
Epoch 09/20 | Train Total 2.144734 | ImbOLL 2.138305 | TC Est -0.642924 | Val ImbOLL 1.797540 | Val TC Est -0.152257 | Val CCC 0.101218 | Val Acc 0.636364 | Val RMSE 0.762770 | 3.14s
Epoch 10/20 | Train Total 2.051927 | ImbOLL 2.047106 | TC Est -0.482094 | Val ImbOLL 1.997834 | Val TC Est -0.293497 | Val CCC 0.076744 | Val Acc 0.636364 | Val RMSE 0.762770 | 3.13s
Epoch 11/20 | Train Total 1.968719 | ImbOLL 1.964923 | TC Est -0.379600 | Val ImbOLL 1.998185 | Val TC Est -0.354888 | Val CCC 0.099528 | Val Acc 0.654545 | Val RMSE 0.750757 | 3.15s
Epoch 12/20 | Train Total 2.084133 | ImbOLL 2.080065 | TC Est -0.406856 | Val ImbOLL 1.864215 | Val TC Est -0.222648 | Val CCC 0.076744 | Val Acc 0.636364 | Val RMSE 0.762770 | 3.51s
Epoch 13/20 | Train Total 2.004784 | ImbOLL 1.999895 | TC Est -0.488863 | Val ImbOLL 2.171990 | Val TC Est -0.524017 | Val CCC 0.099528 | Val Acc 0.654545 | Val RMSE 0.750757 | 3.73s
Epoch 14/20 | Train Total 2.017452 | ImbOLL 2.014377 | TC Est -0.307534 | Val ImbOLL 1.846395 | Val TC Est -0.273592 | Val CCC 0.076744 | Val Acc 0.636364 | Val RMSE 0.762770 | 3.37s
Epoch 15/20 | Train Total 2.490513 | ImbOLL 2.482659 | TC Est -0.785402 | Val ImbOLL 1.837126 | Val TC Est -0.198515 | Val CCC 0.089148 | Val Acc 0.636364 | Val RMSE 0.762770 | 3.30s
Epoch 16/20 | Train Total 1.964695 | ImbOLL 1.961807 | TC Est -0.288876 | Val ImbOLL 1.870506 | Val TC Est -0.137689 | Val CCC 0.079207 | Val Acc 0.618182 | Val RMSE 0.774597 | 3.32s
Epoch 17/20 | Train Total 2.904761 | ImbOLL 2.891831 | TC Est -1.293070 | Val ImbOLL 3.069685 | Val TC Est -1.156504 | Val CCC 0.099528 | Val Acc 0.654545 | Val RMSE 0.750757 | 3.33s
Epoch 18/20 | Train Total 2.144318 | ImbOLL 2.136924 | TC Est -0.739355 | Val ImbOLL 1.812420 | Val TC Est -0.117901 | Val CCC 0.083770 | Val Acc 0.527273 | Val RMSE 0.797724 | 3.11s
Epoch 19/20 | Train Total 1.927627 | ImbOLL 1.925053 | TC Est -0.257377 | Val ImbOLL 1.865407 | Val TC Est -0.327210 | Val CCC 0.099528 | Val Acc 0.654545 | Val RMSE 0.750757 | 2.95s
Epoch 20/20 | Train Total 2.138256 | ImbOLL 2.133135 | TC Est -0.512194 | Val ImbOLL 1.805179 | Val TC Est -0.238790 | Val CCC 0.111695 | Val Acc 0.654545 | Val RMSE 0.750757 | 2.96s
====================================================================================================
TCMax训练完成：Seed=1234，Q8
最佳Val ImbOLL：1.797540，Epoch=9
最佳Val CCC：0.111695，Epoch=4
====================================================================================================

In [228]:
AUDIO_CONTRAST_LAMBDA = 0.01
AUDIO_CONTRAST_MARGIN = 0.0
AUDIO_CONTRAST_NUM_NEGATIVE_SETS = 1
AUDIO_CONTRAST_VALIDATION_SEED = 2026
AUDIO_CONTRAST_CHECKPOINT_ROOT = FUSION_CHECKPOINT_ROOT / "directional_audio_contrast"

In [229]:
def create_audio_derangement_indices(batch_size, tensor_device, generator=None):
    if batch_size < 2:
        return torch.arange(batch_size, device=tensor_device)
    if generator is None:
        shift = int(torch.randint(1, batch_size, (1,), device=tensor_device).item())
    else:
        shift = int(torch.randint(1, batch_size, (1,), generator=generator, device="cpu").item())
    return torch.roll(torch.arange(batch_size, device=tensor_device), shifts=shift)

In [230]:
def calculate_directional_audio_contrast(model, text_features, text_masks, audio_features, audio_masks, labels, positive_logits, margin=AUDIO_CONTRAST_MARGIN, num_negative_sets=AUDIO_CONTRAST_NUM_NEGATIVE_SETS, permutation_generator=None):
    if num_negative_sets < 1:
        raise ValueError("num_negative_sets必须大于或等于1")
    labels = labels.long()
    batch_size = labels.shape[0]
    positive_log_probabilities = torch.log_softmax(positive_logits, dim=1)
    positive_scores = positive_log_probabilities.gather(dim=1, index=labels.unsqueeze(1)).squeeze(1)
    if batch_size < 2:
        zero = positive_scores.sum() * 0.0
        return {"audio_contrast_loss": zero, "positive_score": zero, "negative_score": zero, "score_gap": zero, "pairwise_accuracy": zero}
    negative_score_batches = []
    for _ in range(num_negative_sets):
        audio_indices = create_audio_derangement_indices(batch_size, labels.device, permutation_generator)
        negative_audio_features = audio_features[audio_indices]
        negative_audio_masks = audio_masks[audio_indices]
        negative_logits = model(text_features, text_masks, negative_audio_features, negative_audio_masks)
        negative_log_probabilities = torch.log_softmax(negative_logits, dim=1)
        negative_scores = negative_log_probabilities.gather(dim=1, index=labels.unsqueeze(1)).squeeze(1)
        negative_score_batches.append(negative_scores)
    all_negative_scores = torch.cat(negative_score_batches, dim=0)
    repeated_positive_scores = positive_scores.repeat(num_negative_sets)
    score_gaps = repeated_positive_scores - all_negative_scores
    audio_contrast_loss = torch.nn.functional.softplus(margin - score_gaps).mean()
    pairwise_accuracy = (score_gaps > 0.0).to(positive_logits.dtype).mean()
    return {"audio_contrast_loss": audio_contrast_loss, "positive_score": repeated_positive_scores.mean(), "negative_score": all_negative_scores.mean(), "score_gap": score_gaps.mean(), "pairwise_accuracy": pairwise_accuracy}

In [231]:
def run_fusion_epoch_audio_contrast(model, dataloader, question_index, class_weights, optimizer=None, lambda_audio=AUDIO_CONTRAST_LAMBDA, margin=AUDIO_CONTRAST_MARGIN, num_negative_sets=AUDIO_CONTRAST_NUM_NEGATIVE_SETS, measure_validation_contrast=True):
    is_training = optimizer is not None
    if is_training:
        model.train()
    else:
        model.eval()
    total_objective_loss = 0.0
    total_imboll_loss = 0.0
    total_audio_contrast_loss = 0.0
    total_positive_score = 0.0
    total_negative_score = 0.0
    total_score_gap = 0.0
    total_pairwise_accuracy = 0.0
    total_samples = 0
    prediction_batches = []
    target_batches = []
    validation_generator = None
    if not is_training and measure_validation_contrast:
        validation_generator = torch.Generator(device="cpu")
        validation_generator.manual_seed(AUDIO_CONTRAST_VALIDATION_SEED)
    for batch in dataloader:
        text_features, text_masks, audio_features, audio_masks, all_labels = batch
        text_features = text_features.to(device)
        text_masks = text_masks.to(device)
        audio_features = audio_features.to(device)
        audio_masks = audio_masks.to(device)
        labels = all_labels[:, question_index].to(device).long()
        if is_training:
            optimizer.zero_grad(set_to_none=True)
        with torch.set_grad_enabled(is_training):
            positive_logits = model(text_features, text_masks, audio_features, audio_masks)
            imboll_loss = calculate_imboll_loss(positive_logits, labels, class_weights, ALPHA)
            should_calculate_contrast = is_training or measure_validation_contrast
            if should_calculate_contrast:
                contrast_terms = calculate_directional_audio_contrast(model, text_features, text_masks, audio_features, audio_masks, labels, positive_logits, margin, num_negative_sets, validation_generator)
                audio_contrast_loss = contrast_terms["audio_contrast_loss"]
                positive_score = contrast_terms["positive_score"]
                negative_score = contrast_terms["negative_score"]
                score_gap = contrast_terms["score_gap"]
                pairwise_accuracy = contrast_terms["pairwise_accuracy"]
            else:
                zero = imboll_loss * 0.0
                audio_contrast_loss = zero
                positive_score = zero
                negative_score = zero
                score_gap = zero
                pairwise_accuracy = zero
            total_loss = imboll_loss + lambda_audio * audio_contrast_loss
            if not torch.isfinite(total_loss):
                raise RuntimeError(f"出现非有限定向Audio损失：ImbOLL={imboll_loss.detach().item()}，AudioContrast={audio_contrast_loss.detach().item()}，Total={total_loss.detach().item()}")
            if is_training:
                total_loss.backward()
                torch.nn.utils.clip_grad_norm_(model.parameters(), MAX_GRAD_NORM)
                optimizer.step()
        predictions = torch.argmax(positive_logits, dim=1)
        batch_size = labels.shape[0]
        total_objective_loss += total_loss.detach().item() * batch_size
        total_imboll_loss += imboll_loss.detach().item() * batch_size
        total_audio_contrast_loss += audio_contrast_loss.detach().item() * batch_size
        total_positive_score += positive_score.detach().item() * batch_size
        total_negative_score += negative_score.detach().item() * batch_size
        total_score_gap += score_gap.detach().item() * batch_size
        total_pairwise_accuracy += pairwise_accuracy.detach().item() * batch_size
        total_samples += batch_size
        prediction_batches.append(predictions.detach().cpu())
        target_batches.append(labels.detach().cpu())
    all_predictions = torch.cat(prediction_batches, dim=0)
    all_targets = torch.cat(target_batches, dim=0)
    average_objective_loss = total_objective_loss / total_samples
    average_imboll_loss = total_imboll_loss / total_samples
    average_audio_contrast_loss = total_audio_contrast_loss / total_samples
    average_positive_score = total_positive_score / total_samples
    average_negative_score = total_negative_score / total_samples
    average_score_gap = total_score_gap / total_samples
    average_pairwise_accuracy = total_pairwise_accuracy / total_samples
    classification_metrics = calculate_multiclass_metrics(all_predictions, all_targets)
    float_predictions = all_predictions.float()
    float_targets = all_targets.float()
    ccc = calculate_sample_ccc(float_predictions, float_targets).item()
    rmse = torch.sqrt(torch.mean((float_predictions - float_targets) ** 2)).item()
    mae = torch.mean(torch.abs(float_predictions - float_targets)).item()
    return {"loss": average_objective_loss if is_training else average_imboll_loss, "total_loss": average_objective_loss, "imboll_loss": average_imboll_loss, "audio_contrast_loss": average_audio_contrast_loss, "positive_score": average_positive_score, "negative_score": average_negative_score, "score_gap": average_score_gap, "pairwise_accuracy": average_pairwise_accuracy, "accuracy": classification_metrics["accuracy"], "micro_f1": classification_metrics["micro_f1"], "macro_f1": classification_metrics["macro_f1"], "weighted_f1": classification_metrics["weighted_f1"], "ccc": ccc, "rmse": rmse, "mae": mae, "confusion_matrix": classification_metrics["confusion_matrix"], "predictions": all_predictions, "targets": all_targets}

In [232]:
set_seed(42)
audio_contrast_text_encoder, audio_contrast_audio_encoder, _, _, _, _ = load_pretrained_text_audio_encoders(question_index=7, seed=42)
audio_contrast_smoke_model = TextAudioQuestMF(audio_contrast_text_encoder, audio_contrast_audio_encoder).to(device)
audio_contrast_train_loader, audio_contrast_val_loader = create_fusion_dataloaders(seed=42)
q8_train_labels = train_fusion_dataset.labels[:, 7]
_, _, q8_imboll_weights = calculate_imboll_weights(q8_train_labels, BETA)
q8_imboll_weights_device = q8_imboll_weights.to(device)
audio_contrast_smoke_optimizer = torch.optim.AdamW([parameter for parameter in audio_contrast_smoke_model.parameters() if parameter.requires_grad], lr=LEARNING_RATE, eps=ADAM_EPSILON, weight_decay=WEIGHT_DECAY)
audio_contrast_smoke_train_metrics = run_fusion_epoch_audio_contrast(audio_contrast_smoke_model, audio_contrast_train_loader, question_index=7, class_weights=q8_imboll_weights_device, optimizer=audio_contrast_smoke_optimizer)
audio_contrast_smoke_val_metrics = run_fusion_epoch_audio_contrast(audio_contrast_smoke_model, audio_contrast_val_loader, question_index=7, class_weights=q8_imboll_weights_device, optimizer=None)
print({key: audio_contrast_smoke_train_metrics[key] for key in ["total_loss", "imboll_loss", "audio_contrast_loss", "score_gap", "pairwise_accuracy", "ccc"]})
print({key: audio_contrast_smoke_val_metrics[key] for key in ["imboll_loss", "audio_contrast_loss", "score_gap", "pairwise_accuracy", "ccc"]})

文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q8_PHQ_8Moving/seed_42/best_loss.pt
语音Best Loss： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_42/question_8/best_loss.pt
文本保存Epoch： 11
语音保存Epoch： 12
文本缺少参数： []
文本多余参数： []
语音缺少参数： []
语音多余参数： []
{'total_loss': 2.699870407947002, 'imboll_loss': 2.692877487902261, 'audio_contrast_loss': 0.6992915130100368, 'score_gap': 0.1444248457329792, 'pairwise_accuracy': 0.546012281823012, 'ccc': 0.05228118225932121}
{'imboll_loss': 1.810570164160295, 'audio_contrast_loss': 0.6907699270681902, 'score_gap': 0.04585832763801922, 'pairwise_accuracy': 0.472727278416807, 'ccc': 0.20139183104038239}

In [251]:
def create_fusion_audio_contrast_checkpoint(model, optimizer, checkpoint_type, epoch, question_index, seed, train_metrics, val_metrics, class_counts, imboll_weights, text_checkpoint_path, audio_checkpoint_path, best_val_loss, best_val_ccc, best_loss_epoch, best_ccc_epoch, lambda_audio, margin, num_negative_sets):
    checkpoint = create_fusion_checkpoint(model, optimizer, checkpoint_type, epoch, question_index, seed, train_metrics, val_metrics, class_counts, imboll_weights, text_checkpoint_path, audio_checkpoint_path, best_val_loss, best_val_ccc, best_loss_epoch, best_ccc_epoch)
    checkpoint["experiment_type"] = "text_audio_label_aware_audio_contrast"
    checkpoint["audio_contrast_lambda"] = float(lambda_audio)
    checkpoint["audio_contrast_margin"] = float(margin)
    checkpoint["audio_contrast_num_negative_sets"] = int(num_negative_sets)
    checkpoint["audio_contrast_score_function"] = "target_class_log_probability"
    checkpoint["audio_contrast_text_fixed"] = True
    checkpoint["audio_contrast_label_fixed"] = True
    checkpoint["audio_contrast_negative_sampling"] = "different_label_audio_within_batch"
    return checkpoint

In [279]:
def train_fusion_question_audio_contrast(question_index, seed, lambda_audio=AUDIO_CONTRAST_LAMBDA, margin=AUDIO_CONTRAST_MARGIN, num_negative_sets=AUDIO_CONTRAST_NUM_NEGATIVE_SETS,encoder_checkpoint_type="best_loss"):
    set_seed(seed)
    question_number = question_index + 1
    question_name = PHQ8_QUESTION_COLUMNS[question_index]
    lambda_tag = f"{lambda_audio:.6g}".replace("-", "m").replace(".", "p")
    margin_tag = f"{margin:.6g}".replace("-", "m").replace(".", "p")
    output_dir = AUDIO_CONTRAST_CHECKPOINT_ROOT / f"lambda_{lambda_tag}_margin_{margin_tag}_neg_{num_negative_sets}" / f"seed_{seed}" / f"question_{question_number}"
    output_dir.mkdir(parents=True, exist_ok=True)
    best_loss_path = output_dir / "best_loss.pt"
    best_ccc_path = output_dir / "best_ccc.pt"
    last_path = output_dir / "last.pt"
    history_path = output_dir / "history.csv"
    train_loader, val_loader = create_fusion_dataloaders(seed)
    train_labels = train_fusion_dataset.labels[:, question_index]
    class_counts, inverse_frequency_weights, imboll_weights = calculate_imboll_weights(train_labels, BETA)
    imboll_weights_device = imboll_weights.to(device)
    text_encoder, audio_encoder, text_checkpoint, audio_checkpoint, text_checkpoint_path, audio_checkpoint_path = load_pretrained_text_audio_encoders(question_index=question_index, seed=seed, checkpoint_type=encoder_checkpoint_type)
    if encoder_checkpoint_type == "best_ccc" and text_checkpoint_path.name != "best_ccc.pt":
        raise RuntimeError(f"Text加载的不是best_ccc：{text_checkpoint_path}")
    if encoder_checkpoint_type == "best_ccc" and audio_checkpoint_path.name != "best_ccc.pt":
        raise RuntimeError(f"Audio加载的不是best_ccc：{audio_checkpoint_path}")
    model = TextAudioQuestMF(text_encoder=text_encoder, audio_encoder=audio_encoder).to(device)
    optimizer = torch.optim.AdamW([parameter for parameter in model.parameters() if parameter.requires_grad], lr=LEARNING_RATE, eps=ADAM_EPSILON, weight_decay=WEIGHT_DECAY)
    best_val_loss = float("inf")
    best_val_ccc = float("-inf")
    best_loss_epoch = None
    best_ccc_epoch = None
    history_rows = []
    print("=" * 100)
    print(f"开始定向Audio训练：Seed={seed}，Q{question_number}，{question_name}")
    print(f"Lambda={lambda_audio}，Margin={margin}，Negative Sets={num_negative_sets}")
    print("Text固定：True，Label固定：True，只打乱Audio：True")
    print("类别数量：", class_counts.tolist())
    print("输出目录：", output_dir)
    print("=" * 100)
    for epoch in range(1, NUM_EPOCHS + 1):
        epoch_start_time = time.time()
        train_metrics = run_fusion_epoch_audio_contrast(model, train_loader, question_index, imboll_weights_device, optimizer, lambda_audio, margin, num_negative_sets, False)
        val_metrics = run_fusion_epoch_audio_contrast(model, val_loader, question_index, imboll_weights_device, None, lambda_audio, margin, num_negative_sets, True)
        epoch_seconds = time.time() - epoch_start_time
        val_selection_loss = val_metrics["imboll_loss"]
        history_row = {"Epoch": epoch, "Train_Loss": train_metrics["total_loss"], "Train_ImbOLL_Loss": train_metrics["imboll_loss"], "Train_Audio_Contrast_Loss": train_metrics["audio_contrast_loss"], "Train_Positive_Score": train_metrics["positive_score"], "Train_Negative_Score": train_metrics["negative_score"], "Train_Score_Gap": train_metrics["score_gap"], "Train_Pairwise_Accuracy": train_metrics["pairwise_accuracy"], "Train_Accuracy": train_metrics["accuracy"], "Train_CCC": train_metrics["ccc"], "Train_RMSE": train_metrics["rmse"], "Train_MAE": train_metrics["mae"], "Val_Loss": val_selection_loss, "Val_ImbOLL_Loss": val_metrics["imboll_loss"], "Val_Total_Objective": val_metrics["total_loss"], "Val_Audio_Contrast_Loss": val_metrics["audio_contrast_loss"], "Val_Positive_Score": val_metrics["positive_score"], "Val_Negative_Score": val_metrics["negative_score"], "Val_Score_Gap": val_metrics["score_gap"], "Val_Pairwise_Accuracy": val_metrics["pairwise_accuracy"], "Val_Accuracy": val_metrics["accuracy"], "Val_Micro_F1": val_metrics["micro_f1"], "Val_Macro_F1": val_metrics["macro_f1"], "Val_Weighted_F1": val_metrics["weighted_f1"], "Val_CCC": val_metrics["ccc"], "Val_RMSE": val_metrics["rmse"], "Val_MAE": val_metrics["mae"], "Audio_Contrast_Lambda": lambda_audio, "Audio_Contrast_Margin": margin, "Audio_Contrast_Negative_Sets": num_negative_sets, "Seconds": epoch_seconds}
        history_row["Encoder_Checkpoint_Type"] = encoder_checkpoint_type
        history_rows.append(history_row)
        if not np.isfinite(val_selection_loss):
            raise RuntimeError(f"Seed={seed}，Q{question_number}在Epoch={epoch}出现非有限验证ImbOLL")
        if not np.isfinite(val_metrics["ccc"]):
            raise RuntimeError(f"Seed={seed}，Q{question_number}在Epoch={epoch}出现非有限CCC")
        if val_selection_loss < best_val_loss:
            best_val_loss = val_selection_loss
            best_loss_epoch = epoch
            best_loss_checkpoint = create_fusion_audio_contrast_checkpoint(model, optimizer, "best_loss", epoch, question_index, seed, train_metrics, val_metrics, class_counts, imboll_weights, text_checkpoint_path, audio_checkpoint_path, best_val_loss, best_val_ccc, best_loss_epoch, best_ccc_epoch, lambda_audio, margin, num_negative_sets)
            torch.save(best_loss_checkpoint, best_loss_path)
        if val_metrics["ccc"] > best_val_ccc:
            best_val_ccc = val_metrics["ccc"]
            best_ccc_epoch = epoch
            best_ccc_checkpoint = create_fusion_audio_contrast_checkpoint(model, optimizer, "best_ccc", epoch, question_index, seed, train_metrics, val_metrics, class_counts, imboll_weights, text_checkpoint_path, audio_checkpoint_path, best_val_loss, best_val_ccc, best_loss_epoch, best_ccc_epoch, lambda_audio, margin, num_negative_sets)
            torch.save(best_ccc_checkpoint, best_ccc_path)
        last_checkpoint = create_fusion_audio_contrast_checkpoint(model, optimizer, "last", epoch, question_index, seed, train_metrics, val_metrics, class_counts, imboll_weights, text_checkpoint_path, audio_checkpoint_path, best_val_loss, best_val_ccc, best_loss_epoch, best_ccc_epoch, lambda_audio, margin, num_negative_sets)
        torch.save(last_checkpoint, last_path)
        pd.DataFrame(history_rows).to_csv(history_path, index=False)
        print(f"Epoch {epoch:02d}/{NUM_EPOCHS} | Train Total {train_metrics['total_loss']:.6f} | Contrast {train_metrics['audio_contrast_loss']:.6f} | Train Gap {train_metrics['score_gap']:.6f} | Val ImbOLL {val_metrics['imboll_loss']:.6f} | Val Gap {val_metrics['score_gap']:.6f} | Val Pair {val_metrics['pairwise_accuracy']:.6f} | Val CCC {val_metrics['ccc']:.6f} | {epoch_seconds:.2f}s")
    result = {"experiment_type": "text_audio_directional_audio_contrast", "seed": seed, "question_index": question_index, "question_number": question_number, "question_name": question_name, "lambda_audio": lambda_audio, "margin": margin, "num_negative_sets": num_negative_sets, "best_val_loss": best_val_loss, "best_val_ccc": best_val_ccc, "best_loss_epoch": best_loss_epoch, "best_ccc_epoch": best_ccc_epoch, "best_loss_path": best_loss_path, "best_ccc_path": best_ccc_path, "last_path": last_path, "history_path": history_path}
    result["encoder_checkpoint_type"] = encoder_checkpoint_type
    del model
    del optimizer
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
    print("=" * 100)
    print(f"定向Audio训练完成：Seed={seed}，Q{question_number}")
    print(f"最佳Val ImbOLL：{best_val_loss:.6f}，Epoch={best_loss_epoch}")
    print(f"最佳Val CCC：{best_val_ccc:.6f}，Epoch={best_ccc_epoch}")
    print("=" * 100)
    return result

In [235]:
del audio_contrast_smoke_model
del audio_contrast_smoke_optimizer
torch.cuda.empty_cache()

In [236]:
q8_seed42_audio_contrast_result = train_fusion_question_audio_contrast(question_index=7, seed=42, lambda_audio=0.01, margin=0.0, num_negative_sets=1)
q8_seed100_audio_contrast_result = train_fusion_question_audio_contrast(question_index=7, seed=100, lambda_audio=0.01, margin=0.0, num_negative_sets=1)
q8_seed1234_audio_contrast_result = train_fusion_question_audio_contrast(question_index=7, seed=1234, lambda_audio=0.01, margin=0.0, num_negative_sets=1)

文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q8_PHQ_8Moving/seed_42/best_loss.pt
语音Best Loss： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_42/question_8/best_loss.pt
文本保存Epoch： 11
语音保存Epoch： 12
文本缺少参数： []
文本多余参数： []
语音缺少参数： []
语音多余参数： []
====================================================================================================
开始定向Audio训练：Seed=42，Q8，PHQ_8Moving
Lambda=0.01，Margin=0.0，Negative Sets=1
Text固定：True，Label固定：True，只打乱Audio：True
类别数量： [128, 20, 9, 6]
输出目录： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/directional_audio_contrast/lambda_0p01_margin_0_neg_1/seed_42/question_8
====================================================================================================
Epoch 01/20 | Train Total 2.699870 | Contrast 0.699292 | Train Gap 0.144425 | Val ImbOLL 1.810570 | Val Gap 0.045858 | Val Pair 0.472727 | Val CCC 0.201392 | 1.66s
Epoch 02/20 | Train Total 1.414516 | Contrast 0.703128 | Train Gap -0.000646 | Val ImbOLL 3.196010 | Val Gap 0.001536 | Val Pair 0.472727 | Val CCC 0.281276 | 1.60s
Epoch 03/20 | Train Total 1.364850 | Contrast 0.702860 | Train Gap -0.000927 | Val ImbOLL 1.932331 | Val Gap 0.003155 | Val Pair 0.527273 | Val CCC 0.199813 | 1.65s
Epoch 04/20 | Train Total 1.461142 | Contrast 0.698657 | Train Gap 0.015497 | Val ImbOLL 2.178667 | Val Gap 0.000926 | Val Pair 0.545455 | Val CCC 0.217020 | 1.63s
Epoch 05/20 | Train Total 1.324536 | Contrast 0.685606 | Train Gap 0.029259 | Val ImbOLL 2.486270 | Val Gap -0.004694 | Val Pair 0.436364 | Val CCC 0.230231 | 1.63s
Epoch 06/20 | Train Total 1.453953 | Contrast 0.700986 | Train Gap -0.000288 | Val ImbOLL 2.069626 | Val Gap -0.008115 | Val Pair 0.527273 | Val CCC 0.228568 | 1.56s
Epoch 07/20 | Train Total 1.292286 | Contrast 0.701144 | Train Gap -0.003754 | Val ImbOLL 2.563378 | Val Gap -0.003309 | Val Pair 0.454545 | Val CCC 0.275319 | 1.63s
Epoch 08/20 | Train Total 1.258347 | Contrast 0.681702 | Train Gap 0.034867 | Val ImbOLL 2.529678 | Val Gap -0.003761 | Val Pair 0.472727 | Val CCC 0.163165 | 2.12s
Epoch 09/20 | Train Total 1.295906 | Contrast 0.706802 | Train Gap -0.004269 | Val ImbOLL 2.149052 | Val Gap -0.016234 | Val Pair 0.490909 | Val CCC 0.199813 | 1.56s
Epoch 10/20 | Train Total 1.496872 | Contrast 0.719549 | Train Gap -0.020790 | Val ImbOLL 2.882869 | Val Gap -0.004759 | Val Pair 0.436364 | Val CCC 0.317345 | 1.64s
Epoch 11/20 | Train Total 1.247478 | Contrast 0.695716 | Train Gap 0.016020 | Val ImbOLL 2.695648 | Val Gap -0.001120 | Val Pair 0.472727 | Val CCC 0.260285 | 1.58s
Epoch 12/20 | Train Total 1.405783 | Contrast 0.700863 | Train Gap 0.016410 | Val ImbOLL 2.522167 | Val Gap -0.002441 | Val Pair 0.545455 | Val CCC 0.237091 | 1.66s
Epoch 13/20 | Train Total 1.203514 | Contrast 0.711473 | Train Gap -0.017022 | Val ImbOLL 2.306304 | Val Gap -0.001252 | Val Pair 0.563636 | Val CCC 0.260285 | 1.59s
Epoch 14/20 | Train Total 1.169666 | Contrast 0.688025 | Train Gap 0.031971 | Val ImbOLL 2.551462 | Val Gap -0.006788 | Val Pair 0.454545 | Val CCC 0.163165 | 1.51s
Epoch 15/20 | Train Total 1.331919 | Contrast 0.720183 | Train Gap -0.026254 | Val ImbOLL 2.963509 | Val Gap -0.008746 | Val Pair 0.509091 | Val CCC 0.200699 | 1.46s
Epoch 16/20 | Train Total 1.206501 | Contrast 0.694512 | Train Gap 0.014964 | Val ImbOLL 2.606256 | Val Gap -0.024526 | Val Pair 0.472727 | Val CCC 0.226612 | 1.44s
Epoch 17/20 | Train Total 1.334023 | Contrast 0.676705 | Train Gap 0.058379 | Val ImbOLL 2.445040 | Val Gap 0.002992 | Val Pair 0.436364 | Val CCC 0.137932 | 1.64s
Epoch 18/20 | Train Total 1.273320 | Contrast 0.688409 | Train Gap 0.073059 | Val ImbOLL 2.404136 | Val Gap -0.053287 | Val Pair 0.563636 | Val CCC 0.200103 | 1.93s
Epoch 19/20 | Train Total 1.307226 | Contrast 0.705578 | Train Gap 0.038666 | Val ImbOLL 2.519765 | Val Gap -0.006149 | Val Pair 0.454545 | Val CCC 0.181931 | 1.53s
Epoch 20/20 | Train Total 1.344765 | Contrast 0.709485 | Train Gap -0.011211 | Val ImbOLL 3.233695 | Val Gap -0.001948 | Val Pair 0.454545 | Val CCC 0.213682 | 1.54s
====================================================================================================
定向Audio训练完成：Seed=42，Q8
最佳Val ImbOLL：1.810570，Epoch=1
最佳Val CCC：0.317345，Epoch=10
====================================================================================================
文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q8_PHQ_8Moving/seed_100/best_loss.pt
语音Best Loss： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_100/question_8/best_loss.pt
文本保存Epoch： 12
语音保存Epoch： 12
文本缺少参数： []
文本多余参数： []
语音缺少参数： []
语音多余参数： []
====================================================================================================
开始定向Audio训练：Seed=100，Q8，PHQ_8Moving
Lambda=0.01，Margin=0.0，Negative Sets=1
Text固定：True，Label固定：True，只打乱Audio：True
类别数量： [128, 20, 9, 6]
输出目录： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/directional_audio_contrast/lambda_0p01_margin_0_neg_1/seed_100/question_8
====================================================================================================
Epoch 01/20 | Train Total 1.927429 | Contrast 0.711049 | Train Gap 0.024090 | Val ImbOLL 2.377220 | Val Gap 0.045322 | Val Pair 0.509091 | Val CCC -0.031154 | 1.41s
Epoch 02/20 | Train Total 1.464353 | Contrast 0.698169 | Train Gap 0.034166 | Val ImbOLL 3.533132 | Val Gap 0.003832 | Val Pair 0.509091 | Val CCC 0.200347 | 1.57s
Epoch 03/20 | Train Total 1.423416 | Contrast 0.701926 | Train Gap 0.001743 | Val ImbOLL 2.640730 | Val Gap 0.003979 | Val Pair 0.581818 | Val CCC 0.198807 | 1.48s
Epoch 04/20 | Train Total 1.130560 | Contrast 0.672125 | Train Gap 0.064247 | Val ImbOLL 4.486848 | Val Gap -0.002183 | Val Pair 0.381818 | Val CCC 0.130778 | 1.36s
Epoch 05/20 | Train Total 1.373249 | Contrast 0.691148 | Train Gap 0.032568 | Val ImbOLL 3.869160 | Val Gap 0.017079 | Val Pair 0.527273 | Val CCC 0.199034 | 1.53s
Epoch 06/20 | Train Total 1.305531 | Contrast 0.714603 | Train Gap -0.008692 | Val ImbOLL 4.227907 | Val Gap 0.008416 | Val Pair 0.527273 | Val CCC 0.190909 | 1.53s
Epoch 07/20 | Train Total 1.311772 | Contrast 0.740024 | Train Gap -0.071210 | Val ImbOLL 2.619053 | Val Gap 0.010327 | Val Pair 0.490909 | Val CCC 0.163415 | 1.36s
Epoch 08/20 | Train Total 1.477539 | Contrast 0.693771 | Train Gap 0.019023 | Val ImbOLL 5.155265 | Val Gap 0.008673 | Val Pair 0.527273 | Val CCC 0.168446 | 1.37s
Epoch 09/20 | Train Total 1.327514 | Contrast 0.697198 | Train Gap 0.032533 | Val ImbOLL 3.113538 | Val Gap 0.009309 | Val Pair 0.527273 | Val CCC 0.162897 | 1.40s
Epoch 10/20 | Train Total 1.363017 | Contrast 0.693104 | Train Gap 0.031041 | Val ImbOLL 2.898795 | Val Gap 0.013814 | Val Pair 0.490909 | Val CCC 0.260285 | 1.64s
Epoch 11/20 | Train Total 1.234564 | Contrast 0.693611 | Train Gap 0.011112 | Val ImbOLL 3.069671 | Val Gap 0.017437 | Val Pair 0.527273 | Val CCC 0.153291 | 1.55s
Epoch 12/20 | Train Total 1.211274 | Contrast 0.706647 | Train Gap -0.002008 | Val ImbOLL 2.966011 | Val Gap 0.066230 | Val Pair 0.490909 | Val CCC 0.215471 | 1.43s
Epoch 13/20 | Train Total 1.420799 | Contrast 0.682695 | Train Gap 0.090004 | Val ImbOLL 3.290483 | Val Gap 0.018749 | Val Pair 0.563636 | Val CCC 0.138644 | 1.38s
Epoch 14/20 | Train Total 1.266145 | Contrast 0.703877 | Train Gap -0.003904 | Val ImbOLL 3.413479 | Val Gap 0.003765 | Val Pair 0.545455 | Val CCC 0.239447 | 1.44s
Epoch 15/20 | Train Total 1.237716 | Contrast 0.702712 | Train Gap 0.008709 | Val ImbOLL 3.061664 | Val Gap 0.007001 | Val Pair 0.563636 | Val CCC 0.249431 | 1.49s
Epoch 16/20 | Train Total 1.447779 | Contrast 0.721593 | Train Gap -0.024468 | Val ImbOLL 2.822716 | Val Gap 0.009566 | Val Pair 0.563636 | Val CCC 0.260499 | 1.45s
Epoch 17/20 | Train Total 1.217259 | Contrast 0.711251 | Train Gap -0.011600 | Val ImbOLL 3.667350 | Val Gap 0.008324 | Val Pair 0.490909 | Val CCC 0.259347 | 1.47s
Epoch 18/20 | Train Total 1.669505 | Contrast 0.696446 | Train Gap 0.021407 | Val ImbOLL 3.941811 | Val Gap 0.007596 | Val Pair 0.563636 | Val CCC 0.210824 | 1.49s
Epoch 19/20 | Train Total 1.225384 | Contrast 0.703991 | Train Gap 0.002117 | Val ImbOLL 3.094144 | Val Gap 0.058560 | Val Pair 0.581818 | Val CCC 0.135813 | 1.48s
Epoch 20/20 | Train Total 1.187852 | Contrast 0.669839 | Train Gap 0.096464 | Val ImbOLL 3.382282 | Val Gap 0.075651 | Val Pair 0.581818 | Val CCC 0.249431 | 1.45s
====================================================================================================
定向Audio训练完成：Seed=100，Q8
最佳Val ImbOLL：2.377220，Epoch=1
最佳Val CCC：0.260499，Epoch=16
====================================================================================================
文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q8_PHQ_8Moving/seed_1234/best_loss.pt
语音Best Loss： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_1234/question_8/best_loss.pt
文本保存Epoch： 1
语音保存Epoch： 21
文本缺少参数： []
文本多余参数： []
语音缺少参数： []
语音多余参数： []
====================================================================================================
开始定向Audio训练：Seed=1234，Q8，PHQ_8Moving
Lambda=0.01，Margin=0.0，Negative Sets=1
Text固定：True，Label固定：True，只打乱Audio：True
类别数量： [128, 20, 9, 6]
输出目录： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/directional_audio_contrast/lambda_0p01_margin_0_neg_1/seed_1234/question_8
====================================================================================================
Epoch 01/20 | Train Total 2.411026 | Contrast 0.683206 | Train Gap 0.083968 | Val ImbOLL 1.853980 | Val Gap 0.035168 | Val Pair 0.472727 | Val CCC 0.000000 | 1.48s
Epoch 02/20 | Train Total 2.197210 | Contrast 0.716917 | Train Gap 0.027781 | Val ImbOLL 1.837559 | Val Gap 0.042362 | Val Pair 0.472727 | Val CCC 0.099528 | 1.43s
Epoch 03/20 | Train Total 2.065817 | Contrast 0.684780 | Train Gap 0.102248 | Val ImbOLL 1.900843 | Val Gap 0.072535 | Val Pair 0.472727 | Val CCC 0.111695 | 1.34s
Epoch 04/20 | Train Total 2.003645 | Contrast 0.684099 | Train Gap 0.068557 | Val ImbOLL 2.047634 | Val Gap 0.041953 | Val Pair 0.490909 | Val CCC 0.000000 | 1.39s
Epoch 05/20 | Train Total 2.155936 | Contrast 0.696209 | Train Gap 0.068106 | Val ImbOLL 1.933845 | Val Gap 0.028929 | Val Pair 0.472727 | Val CCC 0.000000 | 1.45s
Epoch 06/20 | Train Total 2.021216 | Contrast 0.674799 | Train Gap 0.108682 | Val ImbOLL 2.182754 | Val Gap 0.095078 | Val Pair 0.490909 | Val CCC 0.111695 | 1.39s
Epoch 07/20 | Train Total 2.270018 | Contrast 0.703046 | Train Gap 0.148729 | Val ImbOLL 1.825834 | Val Gap 0.062697 | Val Pair 0.527273 | Val CCC 0.089148 | 1.38s
Epoch 08/20 | Train Total 1.905005 | Contrast 0.690199 | Train Gap 0.149319 | Val ImbOLL 2.246124 | Val Gap 0.096719 | Val Pair 0.472727 | Val CCC 0.089148 | 1.41s
Epoch 09/20 | Train Total 2.061625 | Contrast 0.750233 | Train Gap 0.077518 | Val ImbOLL 1.813030 | Val Gap 0.024114 | Val Pair 0.490909 | Val CCC 0.091177 | 1.44s
Epoch 10/20 | Train Total 2.273923 | Contrast 0.720632 | Train Gap 0.100077 | Val ImbOLL 1.913995 | Val Gap 0.042891 | Val Pair 0.527273 | Val CCC 0.099528 | 1.44s
Epoch 11/20 | Train Total 1.965122 | Contrast 0.670609 | Train Gap 0.161881 | Val ImbOLL 1.894984 | Val Gap 0.054910 | Val Pair 0.527273 | Val CCC 0.089148 | 1.47s
Epoch 12/20 | Train Total 1.959311 | Contrast 0.703355 | Train Gap 0.127744 | Val ImbOLL 2.098428 | Val Gap 0.079275 | Val Pair 0.527273 | Val CCC 0.089148 | 1.35s
Epoch 13/20 | Train Total 1.961693 | Contrast 0.748969 | Train Gap 0.224103 | Val ImbOLL 1.907314 | Val Gap 0.074942 | Val Pair 0.509091 | Val CCC 0.099528 | 1.32s
Epoch 14/20 | Train Total 2.014815 | Contrast 0.697814 | Train Gap 0.081459 | Val ImbOLL 1.852868 | Val Gap 0.043100 | Val Pair 0.509091 | Val CCC 0.111695 | 1.35s
Epoch 15/20 | Train Total 2.688207 | Contrast 0.711457 | Train Gap 0.253600 | Val ImbOLL 1.873482 | Val Gap 0.023025 | Val Pair 0.509091 | Val CCC 0.089148 | 1.43s
Epoch 16/20 | Train Total 1.915303 | Contrast 0.690500 | Train Gap 0.157413 | Val ImbOLL 1.856262 | Val Gap -0.000056 | Val Pair 0.490909 | Val CCC 0.079207 | 1.35s
Epoch 17/20 | Train Total 2.393985 | Contrast 0.757995 | Train Gap 0.071316 | Val ImbOLL 2.229984 | Val Gap 0.091930 | Val Pair 0.509091 | Val CCC 0.099528 | 1.34s
Epoch 18/20 | Train Total 2.074756 | Contrast 0.708753 | Train Gap 0.105621 | Val ImbOLL 1.872534 | Val Gap 0.009434 | Val Pair 0.490909 | Val CCC 0.179163 | 1.33s
Epoch 19/20 | Train Total 1.986741 | Contrast 0.717617 | Train Gap 0.036327 | Val ImbOLL 1.843831 | Val Gap 0.041643 | Val Pair 0.527273 | Val CCC 0.101218 | 1.33s
Epoch 20/20 | Train Total 1.922458 | Contrast 0.738697 | Train Gap 0.215116 | Val ImbOLL 1.900887 | Val Gap 0.099814 | Val Pair 0.509091 | Val CCC 0.099528 | 1.35s
====================================================================================================
定向Audio训练完成：Seed=1234，Q8
最佳Val ImbOLL：1.813030，Epoch=9
最佳Val CCC：0.179163，Epoch=18
====================================================================================================

In [237]:
def get_best_audio_contrast_row(result):
    history = pd.read_csv(result["history_path"])
    return history.loc[history["Val_CCC"].idxmax()]

q8_seed42_audio_row = get_best_audio_contrast_row(q8_seed42_audio_contrast_result)
q8_seed100_audio_row = get_best_audio_contrast_row(q8_seed100_audio_contrast_result)
q8_seed1234_audio_row = get_best_audio_contrast_row(q8_seed1234_audio_contrast_result)

q8_audio_diagnostics = pd.DataFrame([{"Seed": 42, "Val_CCC": q8_seed42_audio_row["Val_CCC"], "Val_Score_Gap": q8_seed42_audio_row["Val_Score_Gap"], "Val_Pairwise_Accuracy": q8_seed42_audio_row["Val_Pairwise_Accuracy"], "Val_Contrast_Loss": q8_seed42_audio_row["Val_Audio_Contrast_Loss"]}, {"Seed": 100, "Val_CCC": q8_seed100_audio_row["Val_CCC"], "Val_Score_Gap": q8_seed100_audio_row["Val_Score_Gap"], "Val_Pairwise_Accuracy": q8_seed100_audio_row["Val_Pairwise_Accuracy"], "Val_Contrast_Loss": q8_seed100_audio_row["Val_Audio_Contrast_Loss"]}, {"Seed": 1234, "Val_CCC": q8_seed1234_audio_row["Val_CCC"], "Val_Score_Gap": q8_seed1234_audio_row["Val_Score_Gap"], "Val_Pairwise_Accuracy": q8_seed1234_audio_row["Val_Pairwise_Accuracy"], "Val_Contrast_Loss": q8_seed1234_audio_row["Val_Audio_Contrast_Loss"]}])

display(q8_audio_diagnostics)

   Seed   Val_CCC  Val_Score_Gap  Val_Pairwise_Accuracy  Val_Contrast_Loss
0    42  0.317345      -0.004759               0.436364           0.695760
1   100  0.260499       0.009566               0.563636           0.688840
2  1234  0.179163       0.009434               0.490909           0.698876

In [238]:
for seed, row in [(42, q8_seed42_audio_row), (100, q8_seed100_audio_row), (1234, q8_seed1234_audio_row)]:
    print({"Seed": seed, "Train_Gap": row["Train_Score_Gap"], "Train_Pair": row["Train_Pairwise_Accuracy"], "Val_Gap": row["Val_Score_Gap"], "Val_Pair": row["Val_Pairwise_Accuracy"], "Val_CCC": row["Val_CCC"]})

{'Seed': 42, 'Train_Gap': np.float64(-0.0207897936982428), 'Train_Pair': np.float64(0.4723926475442991), 'Val_Gap': np.float64(-0.0047587235458195), 'Val_Pair': np.float64(0.4363636401566592), 'Val_CCC': np.float64(0.3173450231552124)}
{'Seed': 100, 'Train_Gap': np.float64(-0.0244682600630298), 'Train_Pair': np.float64(0.4662576785848185), 'Val_Gap': np.float64(0.0095662069506943), 'Val_Pair': np.float64(0.563636376099153), 'Val_CCC': np.float64(0.2604990899562835)}
{'Seed': 1234, 'Train_Gap': np.float64(0.1056207110705368), 'Train_Pair': np.float64(0.5766871260719065), 'Val_Gap': np.float64(0.009434108368375), 'Val_Pair': np.float64(0.4909090995788574), 'Val_CCC': np.float64(0.1791628152132034)}

In [239]:
q8_seed42_audio_contrast_lambda_0p1_result = train_fusion_question_audio_contrast(question_index=7, seed=42, lambda_audio=0.1, margin=0.0, num_negative_sets=1)

文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q8_PHQ_8Moving/seed_42/best_loss.pt
语音Best Loss： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_42/question_8/best_loss.pt
文本保存Epoch： 11
语音保存Epoch： 12
文本缺少参数： []
文本多余参数： []
语音缺少参数： []
语音多余参数： []
====================================================================================================
开始定向Audio训练：Seed=42，Q8，PHQ_8Moving
Lambda=0.1，Margin=0.0，Negative Sets=1
Text固定：True，Label固定：True，只打乱Audio：True
类别数量： [128, 20, 9, 6]
输出目录： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/directional_audio_contrast/lambda_0p1_margin_0_neg_1/seed_42/question_8
====================================================================================================
Epoch 01/20 | Train Total 2.731598 | Contrast 0.701667 | Train Gap 0.150915 | Val ImbOLL 1.805295 | Val Gap 0.050060 | Val Pair 0.472727 | Val CCC 0.201392 | 2.10s
Epoch 02/20 | Train Total 1.519645 | Contrast 0.702638 | Train Gap 0.003532 | Val ImbOLL 2.790766 | Val Gap -0.000325 | Val Pair 0.363636 | Val CCC 0.344404 | 1.63s
Epoch 03/20 | Train Total 1.414559 | Contrast 0.699401 | Train Gap 0.006373 | Val ImbOLL 2.403059 | Val Gap 0.001916 | Val Pair 0.509091 | Val CCC 0.221589 | 1.62s
Epoch 04/20 | Train Total 1.569748 | Contrast 0.700308 | Train Gap 0.027444 | Val ImbOLL 2.124941 | Val Gap 0.002449 | Val Pair 0.527273 | Val CCC 0.344404 | 1.51s
Epoch 05/20 | Train Total 1.420310 | Contrast 0.693940 | Train Gap 0.020531 | Val ImbOLL 2.776853 | Val Gap -0.000203 | Val Pair 0.472727 | Val CCC 0.244778 | 1.66s
Epoch 06/20 | Train Total 1.649918 | Contrast 0.702450 | Train Gap -0.004936 | Val ImbOLL 2.188370 | Val Gap -0.001116 | Val Pair 0.436364 | Val CCC 0.224752 | 1.54s
Epoch 07/20 | Train Total 1.352390 | Contrast 0.694470 | Train Gap 0.010583 | Val ImbOLL 2.497366 | Val Gap -0.001674 | Val Pair 0.490909 | Val CCC 0.218234 | 1.52s
Epoch 08/20 | Train Total 1.314344 | Contrast 0.677766 | Train Gap 0.043858 | Val ImbOLL 2.401332 | Val Gap -0.002723 | Val Pair 0.527273 | Val CCC 0.278332 | 1.49s
Epoch 09/20 | Train Total 1.338622 | Contrast 0.699663 | Train Gap 0.006718 | Val ImbOLL 2.164566 | Val Gap -0.020833 | Val Pair 0.545455 | Val CCC 0.162897 | 1.47s
Epoch 10/20 | Train Total 1.623300 | Contrast 0.717324 | Train Gap -0.019803 | Val ImbOLL 2.327630 | Val Gap 0.021138 | Val Pair 0.400000 | Val CCC 0.266001 | 1.44s
Epoch 11/20 | Train Total 1.360782 | Contrast 0.702047 | Train Gap -0.000571 | Val ImbOLL 2.745315 | Val Gap 0.008773 | Val Pair 0.490909 | Val CCC 0.275319 | 1.49s
Epoch 12/20 | Train Total 1.474064 | Contrast 0.699838 | Train Gap 0.013361 | Val ImbOLL 2.272552 | Val Gap -0.001721 | Val Pair 0.454545 | Val CCC 0.260285 | 1.39s
Epoch 13/20 | Train Total 1.325451 | Contrast 0.722666 | Train Gap -0.042406 | Val ImbOLL 2.381515 | Val Gap 0.001250 | Val Pair 0.472727 | Val CCC 0.226612 | 1.41s
Epoch 14/20 | Train Total 1.242542 | Contrast 0.688638 | Train Gap 0.034562 | Val ImbOLL 2.648069 | Val Gap 0.000142 | Val Pair 0.418182 | Val CCC 0.244778 | 1.38s
Epoch 15/20 | Train Total 1.344371 | Contrast 0.709563 | Train Gap -0.013588 | Val ImbOLL 3.044487 | Val Gap 0.000359 | Val Pair 0.400000 | Val CCC 0.179163 | 1.40s
Epoch 16/20 | Train Total 1.287254 | Contrast 0.712688 | Train Gap -0.019188 | Val ImbOLL 2.796051 | Val Gap -0.001136 | Val Pair 0.381818 | Val CCC 0.163165 | 1.45s
Epoch 17/20 | Train Total 1.507319 | Contrast 0.691821 | Train Gap 0.028436 | Val ImbOLL 2.484691 | Val Gap -0.000783 | Val Pair 0.418182 | Val CCC 0.278332 | 1.48s
Epoch 18/20 | Train Total 1.307349 | Contrast 0.714311 | Train Gap -0.018153 | Val ImbOLL 2.267376 | Val Gap -0.000715 | Val Pair 0.490909 | Val CCC 0.242426 | 1.42s
Epoch 19/20 | Train Total 1.229705 | Contrast 0.704606 | Train Gap 0.006192 | Val ImbOLL 2.305152 | Val Gap -0.002276 | Val Pair 0.545455 | Val CCC 0.199586 | 1.96s
Epoch 20/20 | Train Total 1.445509 | Contrast 0.701556 | Train Gap -0.002887 | Val ImbOLL 3.836304 | Val Gap -0.006692 | Val Pair 0.454545 | Val CCC 0.233707 | 1.39s
====================================================================================================
定向Audio训练完成：Seed=42，Q8
最佳Val ImbOLL：1.805295，Epoch=1
最佳Val CCC：0.344404，Epoch=2
====================================================================================================

In [240]:
q8_seed42_audio_contrast_lambda_0p1_history = pd.read_csv(q8_seed42_audio_contrast_lambda_0p1_result["history_path"])
display(q8_seed42_audio_contrast_lambda_0p1_history[["Epoch", "Train_Audio_Contrast_Loss", "Train_Score_Gap", "Train_Pairwise_Accuracy", "Val_Audio_Contrast_Loss", "Val_Score_Gap", "Val_Pairwise_Accuracy", "Val_CCC"]])

,Epoch,Train_Audio_Contrast_Loss,Train_Score_Gap,Train_Pairwise_Accuracy,Val_Audio_Contrast_Loss,Val_Score_Gap,Val_Pairwise_Accuracy,Val_CCC
0,1,0.701667,0.150915,0.552147,0.691978,0.050060,0.472727,0.201392
1,2,0.702638,0.003532,0.472393,0.693326,-0.000325,0.363636,0.344404
2,3,0.699401,0.006373,0.490798,0.692204,0.001916,0.509091,0.221589
3,4,0.700308,0.027444,0.539877,0.691958,0.002449,0.527273,0.344404
4,5,0.693940,0.020531,0.539877,0.693261,-0.000203,0.472727,0.244778
5,6,0.702450,-0.004936,0.521472,0.693746,-0.001116,0.436364,0.224752
6,7,0.694470,0.010583,0.466258,0.694146,-0.001674,0.490909,0.218234
7,8,0.677766,0.043858,0.558282,0.694883,-0.002723,0.527273,0.278332
8,9,0.699663,0.006718,0.490798,0.706371,-0.020833,0.545455,0.162897
9,10,0.717324,-0.019803,0.496933,0.688281,0.021138,0.400000,0.266001
10,11,0.702047,-0.000571,0.546012,0.689035,0.008773,0.490909,0.275319
11,12,0.699838,0.013361,0.460123,0.694024,-0.001721,0.454545,0.260285
12,13,0.722666,-0.042406,0.429448,0.692534,0.001250,0.472727,0.226612
13,14,0.688638,0.034562,0.453988,0.693077,0.000142,0.418182,0.244778
14,15,0.709563,-0.013588,0.515337,0.692972,0.000359,0.400000,0.179163
15,16,0.712688,-0.019188,0.496933,0.693729,-0.001136,0.381818,0.163165
16,17,0.691821,0.028436,0.478528,0.693557,-0.000783,0.418182,0.278332
17,18,0.714311,-0.018153,0.447853,0.693552,-0.000715,0.490909,0.242426
18,19,0.704606,0.006192,0.564417,0.694398,-0.002276,0.545455,0.199586
19,20,0.701556,-0.002887,0.496933,0.697245,-0.006692,0.454545,0.233707

In [241]:
print("最大Train Pair：", q8_seed42_audio_contrast_lambda_0p1_history["Train_Pairwise_Accuracy"].max())
print("最大Val Pair：", q8_seed42_audio_contrast_lambda_0p1_history["Val_Pairwise_Accuracy"].max())
print("最后一轮Train Pair：", q8_seed42_audio_contrast_lambda_0p1_history.iloc[-1]["Train_Pairwise_Accuracy"])
print("最后一轮Val Pair：", q8_seed42_audio_contrast_lambda_0p1_history.iloc[-1]["Val_Pairwise_Accuracy"])
print("最佳Val CCC：", q8_seed42_audio_contrast_lambda_0p1_history["Val_CCC"].max())

最大Train Pair： 0.5644171837648732
最大Val Pair： 0.5454545590010557
最后一轮Train Pair： 0.496932523382222
最后一轮Val Pair： 0.4545454613187096
最佳Val CCC： 0.3444039821624756

In [243]:
q8_labels = torch.as_tensor(train_fusion_dataset.labels[:, 7]).long()
q8_class_counts = torch.bincount(q8_labels, minlength=NUM_CLASSES)
q8_sample_count = q8_labels.numel()
print(q8_class_counts)
q8_expected_same_label_rate = (q8_class_counts * (q8_class_counts - 1)).sum().float().div(q8_sample_count * (q8_sample_count - 1)).item()
print("Q8类别数量：", q8_class_counts.tolist())
print("随机打乱后仍为相同标签的概率：", q8_expected_same_label_rate)
print("真正不同标签负样本的概率：", 1.0 - q8_expected_same_label_rate)

tensor([128,  20,   9,   6])
Q8类别数量： [128, 20, 9, 6]
随机打乱后仍为相同标签的概率： 0.6338710784912109
真正不同标签负样本的概率： 0.36612892150878906

In [244]:
def sample_different_label_audio_indices(labels, generator=None):
    batch_size = labels.shape[0]
    different_label_mask = labels.unsqueeze(1) != labels.unsqueeze(0)
    valid_mask = different_label_mask.any(dim=1)
    if generator is None:
        random_scores = torch.rand((batch_size, batch_size), device=labels.device)
    else:
        random_scores = torch.rand((batch_size, batch_size), generator=generator, device="cpu").to(labels.device)
    random_scores = random_scores.masked_fill(~different_label_mask, -1.0)
    negative_indices = torch.argmax(random_scores, dim=1)
    negative_indices = torch.where(valid_mask, negative_indices, torch.arange(batch_size, device=labels.device))
    return negative_indices, valid_mask

In [248]:
q8_sampler_labels = q8_labels.to(device)
audio_indices, valid_mask = sample_different_label_audio_indices(q8_sampler_labels, generator=None)
print("有效样本比例：", valid_mask.float().mean().item())
print("是否全部为不同标签：", torch.all(q8_sampler_labels[audio_indices][valid_mask] != q8_sampler_labels[valid_mask]).item())

有效样本比例： 1.0
是否全部为不同标签： True

In [249]:
def calculate_directional_audio_contrast(model, text_features, text_masks, audio_features, audio_masks, labels, positive_logits, margin=AUDIO_CONTRAST_MARGIN, num_negative_sets=AUDIO_CONTRAST_NUM_NEGATIVE_SETS, permutation_generator=None):
    if num_negative_sets < 1:
        raise ValueError("num_negative_sets必须大于或等于1")
    labels = labels.long()
    positive_log_probabilities = torch.log_softmax(positive_logits, dim=1)
    positive_scores = positive_log_probabilities.gather(dim=1, index=labels.unsqueeze(1)).squeeze(1)
    valid_positive_score_batches = []
    valid_negative_score_batches = []
    for _ in range(num_negative_sets):
        audio_indices, valid_mask = sample_different_label_audio_indices(labels, generator=permutation_generator)
        if not valid_mask.any():
            continue
        negative_audio_features = audio_features[audio_indices]
        negative_audio_masks = audio_masks[audio_indices]
        negative_logits = model(text_features, text_masks, negative_audio_features, negative_audio_masks)
        negative_log_probabilities = torch.log_softmax(negative_logits, dim=1)
        negative_scores = negative_log_probabilities.gather(dim=1, index=labels.unsqueeze(1)).squeeze(1)
        valid_positive_score_batches.append(positive_scores[valid_mask])
        valid_negative_score_batches.append(negative_scores[valid_mask])
    if len(valid_negative_score_batches) == 0:
        zero = positive_scores.sum() * 0.0
        return {"audio_contrast_loss": zero, "positive_score": zero, "negative_score": zero, "score_gap": zero, "pairwise_accuracy": zero}
    all_positive_scores = torch.cat(valid_positive_score_batches, dim=0)
    all_negative_scores = torch.cat(valid_negative_score_batches, dim=0)
    score_gaps = all_positive_scores - all_negative_scores
    audio_contrast_loss = torch.nn.functional.softplus(margin - score_gaps).mean()
    pairwise_accuracy = (score_gaps > 0.0).to(positive_logits.dtype).mean()
    return {"audio_contrast_loss": audio_contrast_loss, "positive_score": all_positive_scores.mean(), "negative_score": all_negative_scores.mean(), "score_gap": score_gaps.mean(), "pairwise_accuracy": pairwise_accuracy}

In [250]:
AUDIO_CONTRAST_CHECKPOINT_ROOT = FUSION_CHECKPOINT_ROOT / "label_aware_directional_audio_contrast"

In [252]:
q8_seed42_label_aware_audio_result = train_fusion_question_audio_contrast(question_index=7, seed=42, lambda_audio=0.1, margin=0.0, num_negative_sets=1)

文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q8_PHQ_8Moving/seed_42/best_loss.pt
语音Best Loss： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_42/question_8/best_loss.pt
文本保存Epoch： 11
语音保存Epoch： 12
文本缺少参数： []
文本多余参数： []
语音缺少参数： []
语音多余参数： []
====================================================================================================
开始定向Audio训练：Seed=42，Q8，PHQ_8Moving
Lambda=0.1，Margin=0.0，Negative Sets=1
Text固定：True，Label固定：True，只打乱Audio：True
类别数量： [128, 20, 9, 6]
输出目录： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/label_aware_directional_audio_contrast/lambda_0p1_margin_0_neg_1/seed_42/question_8
====================================================================================================
Epoch 01/20 | Train Total 3.043979 | Contrast 0.631625 | Train Gap 0.132835 | Val ImbOLL 1.803658 | Val Gap -0.012360 | Val Pair 0.418182 | Val CCC 0.266001 | 2.15s
Epoch 02/20 | Train Total 1.484569 | Contrast 0.616008 | Train Gap 0.030237 | Val ImbOLL 3.521623 | Val Gap -0.000715 | Val Pair 0.400000 | Val CCC 0.283230 | 1.55s
Epoch 03/20 | Train Total 1.542495 | Contrast 0.669183 | Train Gap -0.011670 | Val ImbOLL 2.382593 | Val Gap 0.001091 | Val Pair 0.436364 | Val CCC 0.262452 | 1.50s
Epoch 04/20 | Train Total 1.457965 | Contrast 0.655983 | Train Gap -0.005951 | Val ImbOLL 2.355967 | Val Gap 0.000198 | Val Pair 0.600000 | Val CCC 0.269767 | 1.55s
Epoch 05/20 | Train Total 1.319339 | Contrast 0.631756 | Train Gap 0.032024 | Val ImbOLL 2.713884 | Val Gap 0.001261 | Val Pair 0.636364 | Val CCC 0.301673 | 1.58s
Epoch 06/20 | Train Total 1.565463 | Contrast 0.685733 | Train Gap 0.002334 | Val ImbOLL 2.085842 | Val Gap 0.001592 | Val Pair 0.690909 | Val CCC 0.269767 | 1.61s
Epoch 07/20 | Train Total 1.351724 | Contrast 0.591139 | Train Gap 0.016916 | Val ImbOLL 2.310896 | Val Gap 0.001880 | Val Pair 0.490909 | Val CCC 0.268652 | 1.37s
Epoch 08/20 | Train Total 1.373058 | Contrast 0.706043 | Train Gap -0.006206 | Val ImbOLL 2.776219 | Val Gap 0.000914 | Val Pair 0.436364 | Val CCC 0.255943 | 1.48s
Epoch 09/20 | Train Total 1.334913 | Contrast 0.673634 | Train Gap -0.024645 | Val ImbOLL 2.132914 | Val Gap 0.003028 | Val Pair 0.600000 | Val CCC 0.199813 | 1.43s
Epoch 10/20 | Train Total 1.514464 | Contrast 0.619871 | Train Gap -0.004342 | Val ImbOLL 2.316183 | Val Gap -0.000013 | Val Pair 0.563636 | Val CCC 0.344404 | 1.35s
Epoch 11/20 | Train Total 1.263329 | Contrast 0.597629 | Train Gap 0.008800 | Val ImbOLL 3.082265 | Val Gap 0.000048 | Val Pair 0.654545 | Val CCC 0.226612 | 1.30s
Epoch 12/20 | Train Total 1.488010 | Contrast 0.626197 | Train Gap 0.056145 | Val ImbOLL 2.602492 | Val Gap 0.000600 | Val Pair 0.581818 | Val CCC 0.267135 | 1.42s
Epoch 13/20 | Train Total 1.251716 | Contrast 0.636769 | Train Gap 0.052157 | Val ImbOLL 2.321700 | Val Gap 0.000478 | Val Pair 0.454545 | Val CCC 0.199586 | 1.40s
Epoch 14/20 | Train Total 1.319077 | Contrast 0.666186 | Train Gap 0.003594 | Val ImbOLL 2.646900 | Val Gap 0.002144 | Val Pair 0.636364 | Val CCC 0.218234 | 1.42s
Epoch 15/20 | Train Total 1.427674 | Contrast 0.675118 | Train Gap -0.038394 | Val ImbOLL 2.817611 | Val Gap 0.003525 | Val Pair 0.618182 | Val CCC 0.163165 | 1.42s
Epoch 16/20 | Train Total 1.287547 | Contrast 0.687163 | Train Gap 0.008129 | Val ImbOLL 2.518409 | Val Gap 0.008357 | Val Pair 0.563636 | Val CCC 0.230231 | 1.33s
Epoch 17/20 | Train Total 1.511290 | Contrast 0.597526 | Train Gap 0.016107 | Val ImbOLL 2.609934 | Val Gap -0.003112 | Val Pair 0.363636 | Val CCC 0.218234 | 1.35s
Epoch 18/20 | Train Total 1.415197 | Contrast 0.634042 | Train Gap 0.020116 | Val ImbOLL 2.483531 | Val Gap -0.000085 | Val Pair 0.418182 | Val CCC 0.199586 | 1.35s
Epoch 19/20 | Train Total 1.318822 | Contrast 0.678410 | Train Gap 0.018052 | Val ImbOLL 2.052030 | Val Gap 0.001135 | Val Pair 0.509091 | Val CCC 0.181141 | 1.41s
Epoch 20/20 | Train Total 1.428241 | Contrast 0.657862 | Train Gap -0.015447 | Val ImbOLL 4.061865 | Val Gap 0.004168 | Val Pair 0.563636 | Val CCC 0.172821 | 1.36s
====================================================================================================
定向Audio训练完成：Seed=42，Q8
最佳Val ImbOLL：1.803658，Epoch=1
最佳Val CCC：0.344404，Epoch=10
====================================================================================================

In [253]:
q8_seed42_label_aware_history = pd.read_csv(q8_seed42_label_aware_audio_result["history_path"])
q8_seed42_label_aware_best_row = q8_seed42_label_aware_history.loc[q8_seed42_label_aware_history["Val_CCC"].idxmax()]
print("最佳CCC行：", q8_seed42_label_aware_best_row[["Epoch", "Val_CCC", "Train_Score_Gap", "Train_Pairwise_Accuracy", "Val_Score_Gap", "Val_Pairwise_Accuracy", "Val_Audio_Contrast_Loss"]].to_dict())
print("最大Train Pair：", q8_seed42_label_aware_history["Train_Pairwise_Accuracy"].max())
print("最大Val Pair：", q8_seed42_label_aware_history["Val_Pairwise_Accuracy"].max())
print("最后一轮Train Pair：", q8_seed42_label_aware_history.iloc[-1]["Train_Pairwise_Accuracy"])
print("最后一轮Val Pair：", q8_seed42_label_aware_history.iloc[-1]["Val_Pairwise_Accuracy"])
display(q8_seed42_label_aware_history[["Epoch", "Train_Score_Gap", "Train_Pairwise_Accuracy", "Val_Score_Gap", "Val_Pairwise_Accuracy", "Val_Audio_Contrast_Loss", "Val_CCC"]])

最佳CCC行： {'Epoch': 10.0, 'Val_CCC': 0.3444039821624756, 'Train_Score_Gap': -0.0043419964748657, 'Train_Pairwise_Accuracy': 0.4233128931259085, 'Val_Score_Gap': -1.281957917275246e-05, 'Val_Pairwise_Accuracy': 0.5636363679712469, 'Val_Audio_Contrast_Loss': 0.6931559876962141}
最大Train Pair： 0.5460122776177764
最大Val Pair： 0.6909090930765326
最后一轮Train Pair： 0.4785276126642168
最后一轮Val Pair： 0.5636363652619448

,Epoch,Train_Score_Gap,Train_Pairwise_Accuracy,Val_Score_Gap,Val_Pairwise_Accuracy,Val_Audio_Contrast_Loss,Val_CCC
0,1,0.132835,0.447853,-0.012360,0.418182,0.699722,0.266001
1,2,0.030237,0.429448,-0.000715,0.400000,0.693507,0.283230
2,3,-0.011670,0.411043,0.001091,0.436364,0.692642,0.262452
3,4,-0.005951,0.429448,0.000198,0.600000,0.693059,0.269767
4,5,0.032024,0.496933,0.001261,0.636364,0.692535,0.301673
5,6,0.002334,0.478528,0.001592,0.690909,0.692372,0.269767
6,7,0.016916,0.441718,0.001880,0.490909,0.692216,0.268652
7,8,-0.006206,0.472393,0.000914,0.436364,0.692695,0.255943
8,9,-0.024645,0.429448,0.003028,0.600000,0.691682,0.199813
9,10,-0.004342,0.423313,-0.000013,0.563636,0.693156,0.344404
10,11,0.008800,0.453988,0.000048,0.654545,0.693128,0.226612
11,12,0.056145,0.453988,0.000600,0.581818,0.692851,0.267135
12,13,0.052157,0.509202,0.000478,0.454545,0.692914,0.199586
13,14,0.003594,0.490798,0.002144,0.636364,0.692112,0.218234
14,15,-0.038394,0.398773,0.003525,0.618182,0.691467,0.163165
15,16,0.008129,0.546012,0.008357,0.563636,0.689409,0.230231
16,17,0.016107,0.441718,-0.003112,0.363636,0.695245,0.218234
17,18,0.020116,0.484663,-0.000085,0.418182,0.693258,0.199586
18,19,0.018052,0.484663,0.001135,0.509091,0.692730,0.181141
19,20,-0.015447,0.478528,0.004168,0.563636,0.691504,0.172821

In [254]:
AUDIO_CONTRAST_CHECKPOINT_ROOT = FUSION_CHECKPOINT_ROOT / "label_aware_deterministic_audio_contrast"

In [259]:
def calculate_directional_audio_contrast(model, text_features, text_masks, audio_features, audio_masks, labels, positive_logits, margin=AUDIO_CONTRAST_MARGIN, num_negative_sets=AUDIO_CONTRAST_NUM_NEGATIVE_SETS, permutation_generator=None):
    if num_negative_sets < 1:
        raise ValueError("num_negative_sets必须大于或等于1")
    labels = labels.long()
    sampled_negative_sets = []
    for _ in range(num_negative_sets):
        audio_indices, valid_mask = sample_different_label_audio_indices(labels, generator=permutation_generator)
        if valid_mask.any():
            sampled_negative_sets.append((audio_indices, valid_mask))
    if len(sampled_negative_sets) == 0:
        zero = positive_logits.sum() * 0.0
        return {"audio_contrast_loss": zero, "positive_score": zero, "negative_score": zero, "score_gap": zero, "pairwise_accuracy": zero}
    was_training = model.training
    try:
        if was_training:
            model.eval()
        with torch.backends.cudnn.flags(enabled=False):
            contrast_positive_logits = model(text_features, text_masks, audio_features, audio_masks)
            contrast_positive_log_probabilities = torch.log_softmax(contrast_positive_logits, dim=1)
            contrast_positive_scores = contrast_positive_log_probabilities.gather(dim=1, index=labels.unsqueeze(1)).squeeze(1)
            valid_positive_score_batches = []
            valid_negative_score_batches = []
            for audio_indices, valid_mask in sampled_negative_sets:
                negative_audio_features = audio_features[audio_indices]
                negative_audio_masks = audio_masks[audio_indices]
                contrast_negative_logits = model(text_features, text_masks, negative_audio_features, negative_audio_masks)
                contrast_negative_log_probabilities = torch.log_softmax(contrast_negative_logits, dim=1)
                contrast_negative_scores = contrast_negative_log_probabilities.gather(dim=1, index=labels.unsqueeze(1)).squeeze(1)
                valid_positive_score_batches.append(contrast_positive_scores[valid_mask])
                valid_negative_score_batches.append(contrast_negative_scores[valid_mask])
    finally:
        if was_training:
            model.train()
    all_positive_scores = torch.cat(valid_positive_score_batches, dim=0)
    all_negative_scores = torch.cat(valid_negative_score_batches, dim=0)
    score_gaps = all_positive_scores - all_negative_scores
    audio_contrast_loss = torch.nn.functional.softplus(margin - score_gaps).mean()
    pairwise_accuracy = (score_gaps > 0.0).to(positive_logits.dtype).mean()
    return {"audio_contrast_loss": audio_contrast_loss, "positive_score": all_positive_scores.mean(), "negative_score": all_negative_scores.mean(), "score_gap": score_gaps.mean(), "pairwise_accuracy": pairwise_accuracy}

In [260]:
def create_fusion_audio_contrast_checkpoint(model, optimizer, checkpoint_type, epoch, question_index, seed, train_metrics, val_metrics, class_counts, imboll_weights, text_checkpoint_path, audio_checkpoint_path, best_val_loss, best_val_ccc, best_loss_epoch, best_ccc_epoch, lambda_audio, margin, num_negative_sets):
    checkpoint = create_fusion_checkpoint(model, optimizer, checkpoint_type, epoch, question_index, seed, train_metrics, val_metrics, class_counts, imboll_weights, text_checkpoint_path, audio_checkpoint_path, best_val_loss, best_val_ccc, best_loss_epoch, best_ccc_epoch)
    checkpoint["experiment_type"] = "text_audio_label_aware_deterministic_audio_contrast"
    checkpoint["audio_contrast_lambda"] = float(lambda_audio)
    checkpoint["audio_contrast_margin"] = float(margin)
    checkpoint["audio_contrast_num_negative_sets"] = int(num_negative_sets)
    checkpoint["audio_contrast_score_function"] = "target_class_log_probability"
    checkpoint["audio_contrast_text_fixed"] = True
    checkpoint["audio_contrast_label_fixed"] = True
    checkpoint["audio_contrast_negative_sampling"] = "different_label_audio_within_batch"
    checkpoint["audio_contrast_dropout_mode"] = "disabled_for_positive_and_negative_contrast_forwards"
    return checkpoint

In [280]:
def train_fusion_question_label_aware_deterministic_audio_contrast(question_index, seed, lambda_audio=0.1, margin=0.0, num_negative_sets=1, encoder_checkpoint_type="best_ccc"):
    result = train_fusion_question_audio_contrast(question_index=question_index, seed=seed, lambda_audio=lambda_audio, margin=margin, num_negative_sets=num_negative_sets, encoder_checkpoint_type=encoder_checkpoint_type)
    result["experiment_type"] = "text_audio_label_aware_deterministic_audio_contrast_best_ccc_encoders"
    return result

In [ ]:
q8_seed42_deterministic_audio_result = train_fusion_question_label_aware_deterministic_audio_contrast(question_index=7, seed=42, lambda_audio=0.1, margin=0.0, num_negative_sets=1)

In [263]:
q8_seed42_deterministic_history = pd.read_csv(q8_seed42_deterministic_audio_result["history_path"])
q8_seed42_deterministic_best_row = q8_seed42_deterministic_history.loc[q8_seed42_deterministic_history["Val_CCC"].idxmax()]
print(q8_seed42_deterministic_best_row[["Epoch", "Train_Audio_Contrast_Loss", "Train_Score_Gap", "Train_Pairwise_Accuracy", "Val_Audio_Contrast_Loss", "Val_Score_Gap", "Val_Pairwise_Accuracy", "Val_CCC"]].to_dict())
display(q8_seed42_deterministic_history[["Epoch", "Train_Audio_Contrast_Loss", "Train_Score_Gap", "Train_Pairwise_Accuracy", "Val_Audio_Contrast_Loss", "Val_Score_Gap", "Val_Pairwise_Accuracy", "Val_CCC"]])

{'Epoch': 12.0, 'Train_Audio_Contrast_Loss': 0.6365378758658661, 'Train_Score_Gap': 0.0027376376492388, 'Train_Pairwise_Accuracy': 0.5705521607691525, 'Val_Audio_Contrast_Loss': 0.6924244815653021, 'Val_Score_Gap': 0.0015122308501635, 'Val_Pairwise_Accuracy': 0.6727272868156433, 'Val_CCC': 0.3598466515541076}

,Epoch,Train_Audio_Contrast_Loss,Train_Score_Gap,Train_Pairwise_Accuracy,Val_Audio_Contrast_Loss,Val_Score_Gap,Val_Pairwise_Accuracy,Val_CCC
0,1,0.609594,0.113061,0.595092,0.698709,-0.010470,0.436364,0.223922
1,2,0.608643,0.008510,0.355828,0.693188,-0.000050,0.509091,0.267135
2,3,0.649973,0.001431,0.380368,0.692683,0.001134,0.472727,0.229003
3,4,0.636793,0.002608,0.355828,0.693657,-0.001000,0.581818,0.317577
4,5,0.638490,-0.001023,0.546012,0.692237,0.001889,0.600000,0.172821
5,6,0.679299,0.002430,0.472393,0.693228,0.000150,0.345455,0.267719
6,7,0.593545,0.003927,0.312883,0.694040,-0.001682,0.327273,0.206927
7,8,0.693072,0.000286,0.374233,0.693400,-0.000448,0.400000,0.163165
8,9,0.650173,0.001008,0.386503,0.692025,0.002293,0.618182,0.199813
9,10,0.606559,0.003212,0.619632,0.692525,0.001317,0.618182,0.317345
10,11,0.594400,0.001941,0.546012,0.692812,0.000704,0.600000,0.260285
11,12,0.636538,0.002738,0.570552,0.692424,0.001512,0.672727,0.359847
12,13,0.649680,0.001972,0.435583,0.692509,0.001399,0.654545,0.181141
13,14,0.648907,0.004250,0.533742,0.691352,0.004723,0.563636,0.181931
14,15,0.649325,0.029456,0.429448,0.692626,0.002347,0.527273,0.163165
15,16,0.677260,0.006810,0.564417,0.692787,0.000818,0.563636,0.244778
16,17,0.594465,0.001866,0.380368,0.692806,0.000778,0.581818,0.199586
17,18,0.636843,0.002229,0.546012,0.692163,0.002175,0.600000,0.181141
18,19,0.678526,0.003895,0.588957,0.692275,0.002139,0.600000,0.163165
19,20,0.636347,0.004805,0.576687,0.691049,0.009642,0.600000,0.181931

In [264]:
q8_seed42_baseline_history = pd.read_csv(FUSION_CHECKPOINT_ROOT / "seed_42" / "question_8" / "history.csv")
q8_seed42_baseline_ccc = q8_seed42_baseline_history["Val_CCC"].max()
print("Q8 Seed 42基线CCC：", q8_seed42_baseline_ccc)
print("确定性Audio CCC：", q8_seed42_deterministic_history["Val_CCC"].max())
print("CCC变化：", q8_seed42_deterministic_history["Val_CCC"].max() - q8_seed42_baseline_ccc)

Q8 Seed 42基线CCC： 0.3444039821624756
确定性Audio CCC： 0.3598466515541076
CCC变化： 0.015442669391632025

In [265]:
q8_seed100_deterministic_audio_result = train_fusion_question_label_aware_deterministic_audio_contrast(question_index=7, seed=100, lambda_audio=0.1, margin=0.0, num_negative_sets=1)
q8_seed1234_deterministic_audio_result = train_fusion_question_label_aware_deterministic_audio_contrast(question_index=7, seed=1234, lambda_audio=0.1, margin=0.0, num_negative_sets=1)

文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q8_PHQ_8Moving/seed_100/best_loss.pt
语音Best Loss： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_100/question_8/best_loss.pt
文本保存Epoch： 12
语音保存Epoch： 12
文本缺少参数： []
文本多余参数： []
语音缺少参数： []
语音多余参数： []
====================================================================================================
开始定向Audio训练：Seed=100，Q8，PHQ_8Moving
Lambda=0.1，Margin=0.0，Negative Sets=1
Text固定：True，Label固定：True，只打乱Audio：True
类别数量： [128, 20, 9, 6]
输出目录： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/label_aware_deterministic_audio_contrast/lambda_0p1_margin_0_neg_1/seed_100/question_8
====================================================================================================
Epoch 01/20 | Train Total 1.854322 | Contrast 0.619196 | Train Gap 0.053925 | Val ImbOLL 2.648616 | Val Gap -0.007759 | Val Pair 0.581818 | Val CCC -0.031154 | 6.26s
Epoch 02/20 | Train Total 1.484695 | Contrast 0.599608 | Train Gap 0.035946 | Val ImbOLL 3.442812 | Val Gap -0.002813 | Val Pair 0.563636 | Val CCC 0.161482 | 5.66s
Epoch 03/20 | Train Total 1.609550 | Contrast 0.637859 | Train Gap 0.000109 | Val ImbOLL 2.903889 | Val Gap 0.002320 | Val Pair 0.545455 | Val CCC 0.235405 | 5.42s
Epoch 04/20 | Train Total 1.445818 | Contrast 0.636254 | Train Gap 0.003763 | Val ImbOLL 4.601480 | Val Gap 0.004855 | Val Pair 0.600000 | Val CCC 0.207383 | 5.47s
Epoch 05/20 | Train Total 1.571462 | Contrast 0.641548 | Train Gap 0.020984 | Val ImbOLL 3.091989 | Val Gap 0.001894 | Val Pair 0.418182 | Val CCC 0.175788 | 5.71s
Epoch 06/20 | Train Total 1.297699 | Contrast 0.562538 | Train Gap 0.008574 | Val ImbOLL 4.445761 | Val Gap 0.000579 | Val Pair 0.472727 | Val CCC 0.228688 | 4.97s
Epoch 07/20 | Train Total 1.419582 | Contrast 0.642004 | Train Gap 0.021386 | Val ImbOLL 2.952558 | Val Gap 0.017484 | Val Pair 0.400000 | Val CCC 0.177158 | 5.96s
Epoch 08/20 | Train Total 1.448467 | Contrast 0.562710 | Train Gap 0.012207 | Val ImbOLL 4.079315 | Val Gap 0.006521 | Val Pair 0.654545 | Val CCC 0.190855 | 4.91s
Epoch 09/20 | Train Total 1.448920 | Contrast 0.643701 | Train Gap 0.021428 | Val ImbOLL 2.924878 | Val Gap 0.004789 | Val Pair 0.672727 | Val CCC 0.175788 | 5.44s
Epoch 10/20 | Train Total 1.434580 | Contrast 0.672870 | Train Gap 0.019081 | Val ImbOLL 2.733282 | Val Gap 0.004722 | Val Pair 0.600000 | Val CCC 0.198742 | 5.34s
Epoch 11/20 | Train Total 1.263845 | Contrast 0.637066 | Train Gap 0.003309 | Val ImbOLL 3.309569 | Val Gap 0.007610 | Val Pair 0.600000 | Val CCC 0.183649 | 4.99s
Epoch 12/20 | Train Total 1.241327 | Contrast 0.677412 | Train Gap 0.044283 | Val ImbOLL 3.167058 | Val Gap 0.063096 | Val Pair 0.545455 | Val CCC 0.154998 | 5.59s
Epoch 13/20 | Train Total 1.386521 | Contrast 0.637450 | Train Gap 0.043611 | Val ImbOLL 3.890639 | Val Gap 0.004187 | Val Pair 0.545455 | Val CCC 0.228688 | 5.00s
Epoch 14/20 | Train Total 1.268789 | Contrast 0.558538 | Train Gap 0.017289 | Val ImbOLL 3.661142 | Val Gap 0.008064 | Val Pair 0.563636 | Val CCC 0.260285 | 4.67s
Epoch 15/20 | Train Total 1.360823 | Contrast 0.544570 | Train Gap 0.019430 | Val ImbOLL 3.176758 | Val Gap 0.007840 | Val Pair 0.654545 | Val CCC 0.162897 | 4.38s
Epoch 16/20 | Train Total 1.374428 | Contrast 0.628417 | Train Gap 0.038861 | Val ImbOLL 3.561394 | Val Gap 0.039741 | Val Pair 0.618182 | Val CCC 0.224752 | 4.82s
Epoch 17/20 | Train Total 1.335148 | Contrast 0.682029 | Train Gap 0.043363 | Val ImbOLL 3.239777 | Val Gap 0.018829 | Val Pair 0.636364 | Val CCC 0.278332 | 5.10s
Epoch 18/20 | Train Total 1.651981 | Contrast 0.587503 | Train Gap 0.019371 | Val ImbOLL 3.452954 | Val Gap 0.009196 | Val Pair 0.600000 | Val CCC 0.259347 | 4.61s
Epoch 19/20 | Train Total 1.199085 | Contrast 0.582678 | Train Gap 0.032910 | Val ImbOLL 2.971952 | Val Gap 0.020677 | Val Pair 0.690909 | Val CCC 0.176246 | 4.60s
Epoch 20/20 | Train Total 1.275150 | Contrast 0.544434 | Train Gap 0.037214 | Val ImbOLL 3.176961 | Val Gap 0.055635 | Val Pair 0.600000 | Val CCC 0.232367 | 4.34s
====================================================================================================
定向Audio训练完成：Seed=100，Q8
最佳Val ImbOLL：2.648616，Epoch=1
最佳Val CCC：0.278332，Epoch=17
====================================================================================================
文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q8_PHQ_8Moving/seed_1234/best_loss.pt
语音Best Loss： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_1234/question_8/best_loss.pt
文本保存Epoch： 1
语音保存Epoch： 21
文本缺少参数： []
文本多余参数： []
语音缺少参数： []
语音多余参数： []
====================================================================================================
开始定向Audio训练：Seed=1234，Q8，PHQ_8Moving
Lambda=0.1，Margin=0.0，Negative Sets=1
Text固定：True，Label固定：True，只打乱Audio：True
类别数量： [128, 20, 9, 6]
输出目录： /workspace/E-DAIC/checkpoints/phq8_text_audio_paperlike/label_aware_deterministic_audio_contrast/lambda_0p1_margin_0_neg_1/seed_1234/question_8
====================================================================================================
Epoch 01/20 | Train Total 2.587352 | Contrast 0.641495 | Train Gap 0.073770 | Val ImbOLL 1.950624 | Val Gap 0.007379 | Val Pair 0.636364 | Val CCC 0.000000 | 5.18s
Epoch 02/20 | Train Total 2.322343 | Contrast 0.578489 | Train Gap 0.133048 | Val ImbOLL 2.130730 | Val Gap 0.024139 | Val Pair 0.581818 | Val CCC 0.000000 | 5.77s
Epoch 03/20 | Train Total 2.150401 | Contrast 0.585184 | Train Gap 0.178370 | Val ImbOLL 2.040605 | Val Gap 0.086359 | Val Pair 0.600000 | Val CCC 0.111695 | 6.34s
Epoch 04/20 | Train Total 2.014099 | Contrast 0.541855 | Train Gap 0.317332 | Val ImbOLL 2.086816 | Val Gap 0.079662 | Val Pair 0.600000 | Val CCC 0.089148 | 5.64s
Epoch 05/20 | Train Total 2.169662 | Contrast 0.737205 | Train Gap 0.043364 | Val ImbOLL 1.828126 | Val Gap 0.017599 | Val Pair 0.581818 | Val CCC 0.076744 | 5.43s
Epoch 06/20 | Train Total 1.994749 | Contrast 0.585544 | Train Gap 0.117194 | Val ImbOLL 1.875236 | Val Gap 0.040484 | Val Pair 0.581818 | Val CCC 0.076744 | 5.16s
Epoch 07/20 | Train Total 2.268225 | Contrast 0.618743 | Train Gap 0.117244 | Val ImbOLL 1.853978 | Val Gap 0.024608 | Val Pair 0.563636 | Val CCC 0.076744 | 5.34s
Epoch 08/20 | Train Total 1.995777 | Contrast 0.638144 | Train Gap 0.148901 | Val ImbOLL 1.993903 | Val Gap 0.048110 | Val Pair 0.545455 | Val CCC 0.076744 | 5.53s
Epoch 09/20 | Train Total 2.128000 | Contrast 0.630255 | Train Gap 0.197032 | Val ImbOLL 1.877173 | Val Gap 0.058095 | Val Pair 0.563636 | Val CCC 0.089148 | 5.84s
Epoch 10/20 | Train Total 2.582678 | Contrast 0.563815 | Train Gap 0.330416 | Val ImbOLL 1.838865 | Val Gap 0.037640 | Val Pair 0.545455 | Val CCC 0.089148 | 5.16s
Epoch 11/20 | Train Total 2.003826 | Contrast 0.614805 | Train Gap 0.184476 | Val ImbOLL 1.963652 | Val Gap 0.052473 | Val Pair 0.636364 | Val CCC 0.111695 | 5.51s
Epoch 12/20 | Train Total 2.006923 | Contrast 0.502635 | Train Gap 0.398416 | Val ImbOLL 2.176283 | Val Gap 0.064470 | Val Pair 0.600000 | Val CCC 0.111695 | 5.39s
Epoch 13/20 | Train Total 2.135588 | Contrast 0.577893 | Train Gap 0.460835 | Val ImbOLL 1.971415 | Val Gap 0.048135 | Val Pair 0.545455 | Val CCC 0.111695 | 5.32s
Epoch 14/20 | Train Total 2.014620 | Contrast 0.592828 | Train Gap 0.161019 | Val ImbOLL 1.801481 | Val Gap 0.013898 | Val Pair 0.636364 | Val CCC 0.076744 | 5.05s
Epoch 15/20 | Train Total 2.305898 | Contrast 0.621786 | Train Gap 0.221300 | Val ImbOLL 1.838635 | Val Gap 0.026683 | Val Pair 0.563636 | Val CCC 0.111695 | 5.22s
Epoch 16/20 | Train Total 1.998399 | Contrast 0.593143 | Train Gap 0.237315 | Val ImbOLL 1.916963 | Val Gap 0.106634 | Val Pair 0.509091 | Val CCC 0.114211 | 4.92s
Epoch 17/20 | Train Total 2.820896 | Contrast 0.671792 | Train Gap 0.505970 | Val ImbOLL 2.712224 | Val Gap 0.050629 | Val Pair 0.654545 | Val CCC 0.099528 | 5.45s
Epoch 18/20 | Train Total 2.124593 | Contrast 0.651100 | Train Gap 0.283425 | Val ImbOLL 1.801359 | Val Gap 0.064634 | Val Pair 0.563636 | Val CCC 0.091177 | 5.27s
Epoch 19/20 | Train Total 2.043258 | Contrast 0.521672 | Train Gap 0.126986 | Val ImbOLL 1.789791 | Val Gap 0.043570 | Val Pair 0.581818 | Val CCC 0.057493 | 4.86s
Epoch 20/20 | Train Total 1.950688 | Contrast 0.553936 | Train Gap 0.307719 | Val ImbOLL 1.914893 | Val Gap 0.039580 | Val Pair 0.581818 | Val CCC 0.111695 | 5.27s
====================================================================================================
定向Audio训练完成：Seed=1234，Q8
最佳Val ImbOLL：1.789791，Epoch=19
最佳Val CCC：0.114211，Epoch=16
====================================================================================================

In [266]:
q8_seed100_deterministic_history = pd.read_csv(q8_seed100_deterministic_audio_result["history_path"])
q8_seed1234_deterministic_history = pd.read_csv(q8_seed1234_deterministic_audio_result["history_path"])
q8_seed100_baseline_history = pd.read_csv(FUSION_CHECKPOINT_ROOT / "seed_100" / "question_8" / "history.csv")
q8_seed1234_baseline_history = pd.read_csv(FUSION_CHECKPOINT_ROOT / "seed_1234" / "question_8" / "history.csv")
q8_deterministic_comparison = pd.DataFrame({"Seed": [42, 100, 1234], "Baseline_CCC": [q8_seed42_baseline_history["Val_CCC"].max(), q8_seed100_baseline_history["Val_CCC"].max(), q8_seed1234_baseline_history["Val_CCC"].max()], "Deterministic_Audio_CCC": [q8_seed42_deterministic_history["Val_CCC"].max(), q8_seed100_deterministic_history["Val_CCC"].max(), q8_seed1234_deterministic_history["Val_CCC"].max()]})
q8_deterministic_comparison["CCC_Change"] = q8_deterministic_comparison["Deterministic_Audio_CCC"] - q8_deterministic_comparison["Baseline_CCC"]
display(q8_deterministic_comparison)
print("基线Mean ± Std：", q8_deterministic_comparison["Baseline_CCC"].mean(), q8_deterministic_comparison["Baseline_CCC"].std(ddof=1))
print("定向Audio Mean ± Std：", q8_deterministic_comparison["Deterministic_Audio_CCC"].mean(), q8_deterministic_comparison["Deterministic_Audio_CCC"].std(ddof=1))
print("平均配对变化：", q8_deterministic_comparison["CCC_Change"].mean())

   Seed  Baseline_CCC  Deterministic_Audio_CCC  CCC_Change
0    42      0.344404                 0.359847    0.015443
1   100      0.296571                 0.278332   -0.018239
2  1234      0.111695                 0.114211    0.002516

基线Mean ± Std： 0.2508901705344518 0.12289596307617623
定向Audio Mean ± Std： 0.25079659372568125 0.12511135255730063
平均配对变化： -9.357680877052539e-05

In [267]:
for seed in [42, 100, 1234]:
    text_path = find_checkpoint_by_metadata(TEXT_CHECKPOINT_ROOT, expected_seed=seed, expected_question_index=7, expected_checkpoint_type="best_loss")
    audio_path = find_checkpoint_by_metadata(AUDIO_CHECKPOINT_ROOT, expected_seed=seed, expected_question_index=7, expected_checkpoint_type="best_loss")
    text_checkpoint = torch.load(text_path, map_location="cpu", weights_only=False)
    audio_checkpoint = torch.load(audio_path, map_location="cpu", weights_only=False)
    print({"Seed": seed, "Text_Best_CCC": text_checkpoint.get("best_val_ccc"), "Text_Best_Loss": text_checkpoint.get("best_val_loss"), "Audio_Best_CCC": audio_checkpoint.get("best_val_ccc"), "Audio_Best_Loss": audio_checkpoint.get("best_val_loss"), "Text_Path": str(text_path), "Audio_Path": str(audio_path)})

{'Seed': 42, 'Text_Best_CCC': 0.2790893316268921, 'Text_Best_Loss': 1.678180369463834, 'Audio_Best_CCC': 0.0, 'Audio_Best_Loss': 1.7814135551452637, 'Text_Path': '/workspace/E-DAIC/checkpoints/phq8_text_paperlike/q8_PHQ_8Moving/seed_42/best_loss.pt', 'Audio_Path': '/workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_42/question_8/best_loss.pt'}
{'Seed': 100, 'Text_Best_CCC': 0.2043190598487854, 'Text_Best_Loss': 1.7342357202009722, 'Audio_Best_CCC': 0.09952832758426666, 'Audio_Best_Loss': 1.7781342701478438, 'Text_Path': '/workspace/E-DAIC/checkpoints/phq8_text_paperlike/q8_PHQ_8Moving/seed_100/best_loss.pt', 'Audio_Path': '/workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_100/question_8/best_loss.pt'}
{'Seed': 1234, 'Text_Best_CCC': 0.0, 'Text_Best_Loss': 1.7919207486239346, 'Audio_Best_CCC': 0.11169521510601044, 'Audio_Best_Loss': 1.7641272328116677, 'Text_Path': '/workspace/E-DAIC/checkpoints/phq8_text_paperlike/q8_PHQ_8Moving/seed_1234/best_loss.pt', 'Audio_Path': '/workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_1234/question_8/best_loss.pt'}

In [268]:
q8_seed1234_baseline_checkpoint = torch.load(FUSION_CHECKPOINT_ROOT / "seed_1234" / "question_8" / "best_ccc.pt", map_location="cpu", weights_only=False)
print(q8_seed1234_baseline_checkpoint.keys())
print(q8_seed1234_baseline_checkpoint.get("val_metrics", {}).get("confusion_matrix"))
print(torch.bincount(q8_seed1234_baseline_checkpoint.get("val_metrics", {}).get("predictions").long(), minlength=NUM_CLASSES))

dict_keys(['checkpoint_type', 'epoch', 'question_index', 'question_number', 'question_name', 'seed', 'model_state_dict', 'optimizer_state_dict', 'train_metrics', 'val_metrics', 'class_counts', 'imboll_weights', 'best_val_loss', 'best_val_ccc', 'best_loss_epoch', 'best_ccc_epoch', 'text_checkpoint_path', 'audio_checkpoint_path', 'config'])
[[34, 5, 0, 0], [10, 2, 0, 0], [3, 0, 0, 0], [0, 1, 0, 0]]

AttributeError: 'NoneType' object has no attribute 'long'

In [269]:
for seed in [42, 100, 1234]:
    for checkpoint_type in ["best_loss", "best_ccc"]:
        text_path = find_checkpoint_by_metadata(TEXT_CHECKPOINT_ROOT, expected_seed=seed, expected_question_index=7, expected_checkpoint_type=checkpoint_type)
        audio_path = find_checkpoint_by_metadata(AUDIO_CHECKPOINT_ROOT, expected_seed=seed, expected_question_index=7, expected_checkpoint_type=checkpoint_type)
        text_checkpoint = torch.load(text_path, map_location="cpu", weights_only=False)
        audio_checkpoint = torch.load(audio_path, map_location="cpu", weights_only=False)
        print({"Seed": seed, "Type": checkpoint_type, "Text_Current_CCC": text_checkpoint.get("val_metrics", {}).get("ccc"), "Audio_Current_CCC": audio_checkpoint.get("val_metrics", {}).get("ccc"), "Text_Epoch": text_checkpoint.get("epoch"), "Audio_Epoch": audio_checkpoint.get("epoch")})

{'Seed': 42, 'Type': 'best_loss', 'Text_Current_CCC': 0.2790893316268921, 'Audio_Current_CCC': 0.10121756792068481, 'Text_Epoch': 11, 'Audio_Epoch': 12}
{'Seed': 42, 'Type': 'best_ccc', 'Text_Current_CCC': 0.33740898966789246, 'Audio_Current_CCC': 0.1263793408870697, 'Text_Epoch': 12, 'Audio_Epoch': 44}
{'Seed': 100, 'Type': 'best_loss', 'Text_Current_CCC': 0.2043190598487854, 'Audio_Current_CCC': 0.09117738902568817, 'Text_Epoch': 12, 'Audio_Epoch': 12}
{'Seed': 100, 'Type': 'best_ccc', 'Text_Current_CCC': 0.25735971331596375, 'Audio_Current_CCC': 0.17916281521320343, 'Text_Epoch': 14, 'Audio_Epoch': 20}
{'Seed': 1234, 'Type': 'best_loss', 'Text_Current_CCC': 0.0, 'Audio_Current_CCC': 0.023355869576334953, 'Text_Epoch': 1, 'Audio_Epoch': 21}
{'Seed': 1234, 'Type': 'best_ccc', 'Text_Current_CCC': 0.2839356064796448, 'Audio_Current_CCC': 0.12952688336372375, 'Text_Epoch': 13, 'Audio_Epoch': 30}

In [271]:
for question_index, question_name in enumerate(PHQ8_QUESTION_COLUMNS):
    train_question_labels = torch.as_tensor(train_fusion_dataset.labels[:, question_index]).long()
    val_question_labels = torch.as_tensor(val_fusion_dataset.labels[:, question_index]).long()
    train_question_counts = torch.bincount(train_question_labels, minlength=NUM_CLASSES)
    val_question_counts = torch.bincount(val_question_labels, minlength=NUM_CLASSES)
    print({"Question": question_index + 1, "Name": question_name, "Train_Counts": train_question_counts.tolist(), "Val_Counts": val_question_counts.tolist()})

{'Question': 1, 'Name': 'PHQ_8NoInterest', 'Train_Counts': [81, 57, 20, 5], 'Val_Counts': [25, 22, 4, 4]}
{'Question': 2, 'Name': 'PHQ_8Depressed', 'Train_Counts': [68, 63, 18, 14], 'Val_Counts': [25, 19, 7, 4]}
{'Question': 3, 'Name': 'PHQ_8Sleep', 'Train_Counts': [69, 40, 27, 27], 'Val_Counts': [22, 17, 8, 8]}
{'Question': 4, 'Name': 'PHQ_8Tired', 'Train_Counts': [50, 65, 27, 21], 'Val_Counts': [16, 23, 9, 7]}
{'Question': 5, 'Name': 'PHQ_8Appetite', 'Train_Counts': [77, 42, 24, 20], 'Val_Counts': [19, 22, 10, 4]}
{'Question': 6, 'Name': 'PHQ_8Failure', 'Train_Counts': [76, 44, 24, 19], 'Val_Counts': [25, 17, 8, 5]}
{'Question': 7, 'Name': 'PHQ_8Concentrating', 'Train_Counts': [93, 37, 14, 19], 'Val_Counts': [31, 13, 8, 3]}
{'Question': 8, 'Name': 'PHQ_8Moving', 'Train_Counts': [128, 20, 9, 6], 'Val_Counts': [39, 12, 3, 1]}

In [273]:
FUSION_BEST_CCC_ENCODER_CHECKPOINT_ROOT = FUSION_CHECKPOINT_ROOT.parent / f"{FUSION_CHECKPOINT_ROOT.name}_best_ccc_encoders"

In [274]:
def create_fusion_best_ccc_encoder_checkpoint(model, optimizer, checkpoint_type, epoch, question_index, seed, train_metrics, val_metrics, class_counts, imboll_weights, text_checkpoint_path, audio_checkpoint_path, best_val_loss, best_val_ccc, best_loss_epoch, best_ccc_epoch):
    checkpoint = create_fusion_checkpoint(model, optimizer, checkpoint_type, epoch, question_index, seed, train_metrics, val_metrics, class_counts, imboll_weights, text_checkpoint_path, audio_checkpoint_path, best_val_loss, best_val_ccc, best_loss_epoch, best_ccc_epoch)
    checkpoint["experiment_type"] = "text_audio_best_ccc_encoders"
    checkpoint["encoder_checkpoint_type"] = "best_ccc"
    return checkpoint

In [275]:
def train_fusion_question_best_ccc_encoders(question_index, seed):
    set_seed(seed)
    question_number = question_index + 1
    question_name = PHQ8_QUESTION_COLUMNS[question_index]
    output_dir = FUSION_BEST_CCC_ENCODER_CHECKPOINT_ROOT / f"seed_{seed}" / f"question_{question_number}"
    output_dir.mkdir(parents=True, exist_ok=True)
    best_loss_path = output_dir / "best_loss.pt"
    best_ccc_path = output_dir / "best_ccc.pt"
    last_path = output_dir / "last.pt"
    history_path = output_dir / "history.csv"
    train_loader, val_loader = create_fusion_dataloaders(seed)
    train_labels = train_fusion_dataset.labels[:, question_index]
    class_counts, inverse_frequency_weights, imboll_weights = calculate_imboll_weights(train_labels, BETA)
    imboll_weights_device = imboll_weights.to(device)
    text_encoder, audio_encoder, text_checkpoint, audio_checkpoint, text_checkpoint_path, audio_checkpoint_path = load_pretrained_text_audio_encoders(question_index=question_index, seed=seed, checkpoint_type="best_ccc")
    model = TextAudioQuestMF(text_encoder=text_encoder, audio_encoder=audio_encoder).to(device)
    optimizer = torch.optim.AdamW([parameter for parameter in model.parameters() if parameter.requires_grad], lr=LEARNING_RATE, eps=ADAM_EPSILON, weight_decay=WEIGHT_DECAY)
    best_val_loss = float("inf")
    best_val_ccc = float("-inf")
    best_loss_epoch = None
    best_ccc_epoch = None
    history_rows = []
    print("=" * 100)
    print(f"开始训练Best-CCC编码器版本：Seed={seed}，Q{question_number}，{question_name}")
    print("编码器检查点类型：best_ccc")
    print("文本检查点：", text_checkpoint_path)
    print("语音检查点：", audio_checkpoint_path)
    print("类别数量：", class_counts.tolist())
    print("=" * 100)
    for epoch in range(1, NUM_EPOCHS + 1):
        epoch_start_time = time.time()
        train_metrics = run_fusion_epoch(model, train_loader, question_index, imboll_weights_device, optimizer)
        val_metrics = run_fusion_epoch(model, val_loader, question_index, imboll_weights_device, optimizer=None)
        epoch_seconds = time.time() - epoch_start_time
        history_row = {"Epoch": epoch, "Train_Loss": train_metrics["loss"], "Train_Accuracy": train_metrics["accuracy"], "Train_CCC": train_metrics["ccc"], "Train_RMSE": train_metrics["rmse"], "Train_MAE": train_metrics["mae"], "Val_Loss": val_metrics["loss"], "Val_Accuracy": val_metrics["accuracy"], "Val_Micro_F1": val_metrics["micro_f1"], "Val_Macro_F1": val_metrics["macro_f1"], "Val_Weighted_F1": val_metrics["weighted_f1"], "Val_CCC": val_metrics["ccc"], "Val_RMSE": val_metrics["rmse"], "Val_MAE": val_metrics["mae"], "Seconds": epoch_seconds}
        history_rows.append(history_row)
        if not np.isfinite(val_metrics["loss"]):
            raise RuntimeError(f"Seed={seed}，Q{question_number}在Epoch={epoch}出现非有限验证损失")
        if not np.isfinite(val_metrics["ccc"]):
            raise RuntimeError(f"Seed={seed}，Q{question_number}在Epoch={epoch}出现非有限CCC")
        if val_metrics["loss"] < best_val_loss:
            best_val_loss = val_metrics["loss"]
            best_loss_epoch = epoch
            best_loss_checkpoint = create_fusion_best_ccc_encoder_checkpoint(model, optimizer, "best_loss", epoch, question_index, seed, train_metrics, val_metrics, class_counts, imboll_weights, text_checkpoint_path, audio_checkpoint_path, best_val_loss, best_val_ccc, best_loss_epoch, best_ccc_epoch)
            torch.save(best_loss_checkpoint, best_loss_path)
        if val_metrics["ccc"] > best_val_ccc:
            best_val_ccc = val_metrics["ccc"]
            best_ccc_epoch = epoch
            best_ccc_checkpoint = create_fusion_best_ccc_encoder_checkpoint(model, optimizer, "best_ccc", epoch, question_index, seed, train_metrics, val_metrics, class_counts, imboll_weights, text_checkpoint_path, audio_checkpoint_path, best_val_loss, best_val_ccc, best_loss_epoch, best_ccc_epoch)
            torch.save(best_ccc_checkpoint, best_ccc_path)
        last_checkpoint = create_fusion_best_ccc_encoder_checkpoint(model, optimizer, "last", epoch, question_index, seed, train_metrics, val_metrics, class_counts, imboll_weights, text_checkpoint_path, audio_checkpoint_path, best_val_loss, best_val_ccc, best_loss_epoch, best_ccc_epoch)
        torch.save(last_checkpoint, last_path)
        pd.DataFrame(history_rows).to_csv(history_path, index=False)
        print(f"Epoch {epoch:02d}/{NUM_EPOCHS} | Train Loss {train_metrics['loss']:.6f} | Val Loss {val_metrics['loss']:.6f} | Val CCC {val_metrics['ccc']:.6f} | Val Acc {val_metrics['accuracy']:.6f} | Val RMSE {val_metrics['rmse']:.6f} | {epoch_seconds:.2f}s")
    result = {"experiment_type": "text_audio_best_ccc_encoders", "encoder_checkpoint_type": "best_ccc", "seed": seed, "question_index": question_index, "question_number": question_number, "question_name": question_name, "best_val_loss": best_val_loss, "best_val_ccc": best_val_ccc, "best_loss_epoch": best_loss_epoch, "best_ccc_epoch": best_ccc_epoch, "best_loss_path": best_loss_path, "best_ccc_path": best_ccc_path, "last_path": last_path, "history_path": history_path}
    del model
    del optimizer
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
    print("=" * 100)
    print(f"Best-CCC编码器版本训练完成：Seed={seed}，Q{question_number}")
    print(f"最佳Val Loss：{best_val_loss:.6f}，Epoch={best_loss_epoch}")
    print(f"最佳Val CCC：{best_val_ccc:.6f}，Epoch={best_ccc_epoch}")
    print("=" * 100)
    return result

In [276]:
q8_seed42_best_ccc_encoder_result = train_fusion_question_best_ccc_encoders(question_index=7, seed=42)
q8_seed100_best_ccc_encoder_result = train_fusion_question_best_ccc_encoders(question_index=7, seed=100)
q8_seed1234_best_ccc_encoder_result = train_fusion_question_best_ccc_encoders(question_index=7, seed=1234)

文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q8_PHQ_8Moving/seed_42/best_ccc.pt
语音Best Loss： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_42/question_8/best_ccc.pt
文本保存Epoch： 12
语音保存Epoch： 44
文本缺少参数： []
文本多余参数： []
语音缺少参数： []
语音多余参数： []
====================================================================================================
开始训练Best-CCC编码器版本：Seed=42，Q8，PHQ_8Moving
编码器检查点类型：best_ccc
文本检查点： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q8_PHQ_8Moving/seed_42/best_ccc.pt
语音检查点： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_42/question_8/best_ccc.pt
类别数量： [128, 20, 9, 6]
====================================================================================================
Epoch 01/20 | Train Loss 2.746542 | Val Loss 1.990569 | Val CCC 0.134101 | Val Acc 0.690909 | Val RMSE 0.726135 | 1.50s
Epoch 02/20 | Train Loss 1.290186 | Val Loss 2.848801 | Val CCC 0.356175 | Val Acc 0.618182 | Val RMSE 0.774597 | 1.00s
Epoch 03/20 | Train Loss 1.436498 | Val Loss 2.169817 | Val CCC 0.275278 | Val Acc 0.563636 | Val RMSE 0.700649 | 1.46s
Epoch 04/20 | Train Loss 1.138206 | Val Loss 2.363530 | Val CCC 0.380641 | Val Acc 0.563636 | Val RMSE 0.738549 | 0.97s
Epoch 05/20 | Train Loss 1.165872 | Val Loss 2.813916 | Val CCC 0.180810 | Val Acc 0.600000 | Val RMSE 0.750757 | 0.88s
Epoch 06/20 | Train Loss 1.264930 | Val Loss 2.048574 | Val CCC 0.240340 | Val Acc 0.563636 | Val RMSE 0.738549 | 0.86s
Epoch 07/20 | Train Loss 1.158236 | Val Loss 2.595425 | Val CCC 0.223922 | Val Acc 0.600000 | Val RMSE 0.713506 | 0.90s
Epoch 08/20 | Train Loss 1.119952 | Val Loss 2.345725 | Val CCC 0.179894 | Val Acc 0.581818 | Val RMSE 0.762770 | 0.84s
Epoch 09/20 | Train Loss 1.362612 | Val Loss 3.153930 | Val CCC 0.180810 | Val Acc 0.600000 | Val RMSE 0.750757 | 0.89s
Epoch 10/20 | Train Loss 1.259655 | Val Loss 2.319640 | Val CCC 0.261252 | Val Acc 0.581818 | Val RMSE 0.726135 | 1.41s
Epoch 11/20 | Train Loss 1.061871 | Val Loss 3.505446 | Val CCC 0.236772 | Val Acc 0.618182 | Val RMSE 0.700649 | 0.89s
Epoch 12/20 | Train Loss 1.199412 | Val Loss 2.042388 | Val CCC 0.297685 | Val Acc 0.581818 | Val RMSE 0.687552 | 0.81s
Epoch 13/20 | Train Loss 1.051530 | Val Loss 2.436364 | Val CCC 0.350479 | Val Acc 0.600000 | Val RMSE 0.750757 | 0.85s
Epoch 14/20 | Train Loss 0.966944 | Val Loss 3.557970 | Val CCC 0.202306 | Val Acc 0.618182 | Val RMSE 0.738549 | 0.84s
Epoch 15/20 | Train Loss 1.183790 | Val Loss 2.788903 | Val CCC 0.190873 | Val Acc 0.600000 | Val RMSE 0.750757 | 0.81s
Epoch 16/20 | Train Loss 1.012655 | Val Loss 3.092686 | Val CCC 0.388024 | Val Acc 0.618182 | Val RMSE 0.738549 | 0.83s
Epoch 17/20 | Train Loss 1.179615 | Val Loss 2.944675 | Val CCC 0.270809 | Val Acc 0.618182 | Val RMSE 0.774597 | 0.93s
Epoch 18/20 | Train Loss 1.079014 | Val Loss 2.792669 | Val CCC 0.200699 | Val Acc 0.600000 | Val RMSE 0.750757 | 1.00s
Epoch 19/20 | Train Loss 1.102528 | Val Loss 3.304233 | Val CCC 0.256160 | Val Acc 0.636364 | Val RMSE 0.762770 | 0.84s
Epoch 20/20 | Train Loss 1.131006 | Val Loss 4.421369 | Val CCC 0.151623 | Val Acc 0.600000 | Val RMSE 0.786245 | 0.90s
====================================================================================================
Best-CCC编码器版本训练完成：Seed=42，Q8
最佳Val Loss：1.990569，Epoch=1
最佳Val CCC：0.388024，Epoch=16
====================================================================================================
文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q8_PHQ_8Moving/seed_100/best_ccc.pt
语音Best Loss： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_100/question_8/best_ccc.pt
文本保存Epoch： 14
语音保存Epoch： 20
文本缺少参数： []
文本多余参数： []
语音缺少参数： []
语音多余参数： []
====================================================================================================
开始训练Best-CCC编码器版本：Seed=100，Q8，PHQ_8Moving
编码器检查点类型：best_ccc
文本检查点： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q8_PHQ_8Moving/seed_100/best_ccc.pt
语音检查点： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_100/question_8/best_ccc.pt
类别数量： [128, 20, 9, 6]
====================================================================================================
Epoch 01/20 | Train Loss 1.681855 | Val Loss 2.408969 | Val CCC 0.168446 | Val Acc 0.563636 | Val RMSE 0.738549 | 0.87s
Epoch 02/20 | Train Loss 1.205324 | Val Loss 4.541974 | Val CCC 0.190909 | Val Acc 0.581818 | Val RMSE 0.726135 | 1.00s
Epoch 03/20 | Train Loss 1.238511 | Val Loss 3.089473 | Val CCC 0.167272 | Val Acc 0.509091 | Val RMSE 0.873863 | 0.78s
Epoch 04/20 | Train Loss 1.149105 | Val Loss 4.279468 | Val CCC 0.248815 | Val Acc 0.600000 | Val RMSE 0.820200 | 1.24s
Epoch 05/20 | Train Loss 1.396508 | Val Loss 3.340971 | Val CCC 0.198397 | Val Acc 0.527273 | Val RMSE 0.863397 | 0.84s
Epoch 06/20 | Train Loss 1.118064 | Val Loss 4.880864 | Val CCC 0.180810 | Val Acc 0.600000 | Val RMSE 0.750757 | 0.82s
Epoch 07/20 | Train Loss 1.348960 | Val Loss 3.615291 | Val CCC 0.215724 | Val Acc 0.563636 | Val RMSE 0.842075 | 0.85s
Epoch 08/20 | Train Loss 1.138057 | Val Loss 3.875186 | Val CCC 0.117961 | Val Acc 0.545455 | Val RMSE 0.786245 | 0.96s
Epoch 09/20 | Train Loss 1.213833 | Val Loss 3.293352 | Val CCC 0.270809 | Val Acc 0.563636 | Val RMSE 0.774597 | 1.34s
Epoch 10/20 | Train Loss 1.336079 | Val Loss 3.043514 | Val CCC 0.241270 | Val Acc 0.545455 | Val RMSE 0.884205 | 0.84s
Epoch 11/20 | Train Loss 1.077599 | Val Loss 3.215474 | Val CCC 0.199418 | Val Acc 0.545455 | Val RMSE 0.852803 | 0.80s
Epoch 12/20 | Train Loss 1.243259 | Val Loss 3.414146 | Val CCC 0.207383 | Val Acc 0.581818 | Val RMSE 0.863397 | 0.84s
Epoch 13/20 | Train Loss 1.227258 | Val Loss 3.702790 | Val CCC 0.251494 | Val Acc 0.618182 | Val RMSE 0.738549 | 0.88s
Epoch 14/20 | Train Loss 1.220090 | Val Loss 4.025105 | Val CCC 0.307812 | Val Acc 0.600000 | Val RMSE 0.750757 | 0.86s
Epoch 15/20 | Train Loss 1.170147 | Val Loss 2.949711 | Val CCC 0.171121 | Val Acc 0.545455 | Val RMSE 0.786245 | 0.81s
Epoch 16/20 | Train Loss 1.398757 | Val Loss 3.767862 | Val CCC 0.199418 | Val Acc 0.545455 | Val RMSE 0.852803 | 1.29s
Epoch 17/20 | Train Loss 1.060247 | Val Loss 3.759288 | Val CCC 0.314689 | Val Acc 0.636364 | Val RMSE 0.726135 | 0.87s
Epoch 18/20 | Train Loss 1.283595 | Val Loss 3.567137 | Val CCC 0.276907 | Val Acc 0.600000 | Val RMSE 0.786245 | 0.87s
Epoch 19/20 | Train Loss 1.054527 | Val Loss 3.358357 | Val CCC 0.232188 | Val Acc 0.581818 | Val RMSE 0.831209 | 0.74s
Epoch 20/20 | Train Loss 1.083345 | Val Loss 3.327689 | Val CCC 0.289210 | Val Acc 0.581818 | Val RMSE 0.762770 | 0.79s
====================================================================================================
Best-CCC编码器版本训练完成：Seed=100，Q8
最佳Val Loss：2.408969，Epoch=1
最佳Val CCC：0.314689，Epoch=17
====================================================================================================
文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q8_PHQ_8Moving/seed_1234/best_ccc.pt
语音Best Loss： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_1234/question_8/best_ccc.pt
文本保存Epoch： 13
语音保存Epoch： 30
文本缺少参数： []
文本多余参数： []
语音缺少参数： []
语音多余参数： []
====================================================================================================
开始训练Best-CCC编码器版本：Seed=1234，Q8，PHQ_8Moving
编码器检查点类型：best_ccc
文本检查点： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q8_PHQ_8Moving/seed_1234/best_ccc.pt
语音检查点： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_1234/question_8/best_ccc.pt
类别数量： [128, 20, 9, 6]
====================================================================================================
Epoch 01/20 | Train Loss 2.079865 | Val Loss 2.542931 | Val CCC 0.099528 | Val Acc 0.654545 | Val RMSE 0.750757 | 0.88s
Epoch 02/20 | Train Loss 1.198755 | Val Loss 4.100831 | Val CCC 0.183256 | Val Acc 0.618182 | Val RMSE 0.809040 | 0.81s
Epoch 03/20 | Train Loss 1.216757 | Val Loss 3.842878 | Val CCC 0.208207 | Val Acc 0.563636 | Val RMSE 0.842075 | 0.76s
Epoch 04/20 | Train Loss 1.058008 | Val Loss 5.264952 | Val CCC 0.283936 | Val Acc 0.654545 | Val RMSE 0.674200 | 0.77s
Epoch 05/20 | Train Loss 1.103995 | Val Loss 5.298870 | Val CCC 0.159592 | Val Acc 0.581818 | Val RMSE 0.762770 | 0.84s
Epoch 06/20 | Train Loss 1.436493 | Val Loss 5.849439 | Val CCC 0.159592 | Val Acc 0.581818 | Val RMSE 0.762770 | 0.78s
Epoch 07/20 | Train Loss 1.020636 | Val Loss 4.224184 | Val CCC 0.159592 | Val Acc 0.581818 | Val RMSE 0.762770 | 0.81s
Epoch 08/20 | Train Loss 1.106624 | Val Loss 4.353799 | Val CCC 0.159592 | Val Acc 0.581818 | Val RMSE 0.762770 | 0.97s
Epoch 09/20 | Train Loss 0.973662 | Val Loss 4.527952 | Val CCC 0.153889 | Val Acc 0.563636 | Val RMSE 0.809040 | 0.86s
Epoch 10/20 | Train Loss 1.112555 | Val Loss 4.782021 | Val CCC 0.159592 | Val Acc 0.581818 | Val RMSE 0.762770 | 0.91s
Epoch 11/20 | Train Loss 1.114542 | Val Loss 6.435098 | Val CCC 0.159592 | Val Acc 0.581818 | Val RMSE 0.762770 | 0.84s
Epoch 12/20 | Train Loss 1.110541 | Val Loss 5.244346 | Val CCC 0.208207 | Val Acc 0.563636 | Val RMSE 0.842075 | 0.89s
Epoch 13/20 | Train Loss 1.039390 | Val Loss 7.735812 | Val CCC 0.246153 | Val Acc 0.654545 | Val RMSE 0.713506 | 0.89s
Epoch 14/20 | Train Loss 1.099177 | Val Loss 5.207345 | Val CCC 0.208207 | Val Acc 0.563636 | Val RMSE 0.842075 | 0.91s
Epoch 15/20 | Train Loss 1.140547 | Val Loss 4.065094 | Val CCC 0.234365 | Val Acc 0.563636 | Val RMSE 0.809040 | 0.76s
Epoch 16/20 | Train Loss 0.984154 | Val Loss 3.889349 | Val CCC 0.159592 | Val Acc 0.581818 | Val RMSE 0.762770 | 0.85s
Epoch 17/20 | Train Loss 1.079322 | Val Loss 3.343008 | Val CCC 0.215724 | Val Acc 0.563636 | Val RMSE 0.842075 | 0.78s
Epoch 18/20 | Train Loss 1.018225 | Val Loss 7.467352 | Val CCC 0.242751 | Val Acc 0.636364 | Val RMSE 0.884205 | 0.77s
Epoch 19/20 | Train Loss 1.355479 | Val Loss 5.240802 | Val CCC 0.278129 | Val Acc 0.600000 | Val RMSE 0.820200 | 0.74s
Epoch 20/20 | Train Loss 0.966138 | Val Loss 3.322244 | Val CCC 0.291190 | Val Acc 0.600000 | Val RMSE 0.820200 | 1.13s
====================================================================================================
Best-CCC编码器版本训练完成：Seed=1234，Q8
最佳Val Loss：2.542931，Epoch=1
最佳Val CCC：0.291190，Epoch=20
====================================================================================================

In [277]:
q8_encoder_checkpoint_comparison = pd.DataFrame({"Seed": [42, 100, 1234], "Best_Loss_Encoder_CCC": [0.3444039821624756, 0.2965708374977112, 0.11169521510601044], "Best_CCC_Encoder_CCC": [q8_seed42_best_ccc_encoder_result["best_val_ccc"], q8_seed100_best_ccc_encoder_result["best_val_ccc"], q8_seed1234_best_ccc_encoder_result["best_val_ccc"]]})
q8_encoder_checkpoint_comparison["CCC_Change"] = q8_encoder_checkpoint_comparison["Best_CCC_Encoder_CCC"] - q8_encoder_checkpoint_comparison["Best_Loss_Encoder_CCC"]
display(q8_encoder_checkpoint_comparison)
print("原始Mean ± Std：", q8_encoder_checkpoint_comparison["Best_Loss_Encoder_CCC"].mean(), q8_encoder_checkpoint_comparison["Best_Loss_Encoder_CCC"].std(ddof=1))
print("Best-CCC编码器Mean ± Std：", q8_encoder_checkpoint_comparison["Best_CCC_Encoder_CCC"].mean(), q8_encoder_checkpoint_comparison["Best_CCC_Encoder_CCC"].std(ddof=1))

   Seed  Best_Loss_Encoder_CCC  Best_CCC_Encoder_CCC  CCC_Change
0    42               0.344404              0.388024    0.043620
1   100               0.296571              0.314689    0.018118
2  1234               0.111695              0.291190    0.179494

原始Mean ± Std： 0.2508900115887324 0.12289587445488095
Best-CCC编码器Mean ± Std： 0.3313007056713104 0.05050935662022826

In [278]:
AUDIO_CONTRAST_CHECKPOINT_ROOT = FUSION_CHECKPOINT_ROOT.parent / "phq8_text_audio_label_aware_deterministic_best_ccc_encoders"

In [281]:
q8_seed42_final_audio_result = train_fusion_question_label_aware_deterministic_audio_contrast(question_index=7, seed=42, lambda_audio=0.1, margin=0.0, num_negative_sets=1, encoder_checkpoint_type="best_ccc")
q8_seed100_final_audio_result = train_fusion_question_label_aware_deterministic_audio_contrast(question_index=7, seed=100, lambda_audio=0.1, margin=0.0, num_negative_sets=1, encoder_checkpoint_type="best_ccc")
q8_seed1234_final_audio_result = train_fusion_question_label_aware_deterministic_audio_contrast(question_index=7, seed=1234, lambda_audio=0.1, margin=0.0, num_negative_sets=1, encoder_checkpoint_type="best_ccc")

文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q8_PHQ_8Moving/seed_42/best_ccc.pt
语音Best Loss： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_42/question_8/best_ccc.pt
文本保存Epoch： 12
语音保存Epoch： 44
文本缺少参数： []
文本多余参数： []
语音缺少参数： []
语音多余参数： []
====================================================================================================
开始定向Audio训练：Seed=42，Q8，PHQ_8Moving
Lambda=0.1，Margin=0.0，Negative Sets=1
Text固定：True，Label固定：True，只打乱Audio：True
类别数量： [128, 20, 9, 6]
输出目录： /workspace/E-DAIC/checkpoints/phq8_text_audio_label_aware_deterministic_best_ccc_encoders/lambda_0p1_margin_0_neg_1/seed_42/question_8
====================================================================================================
Epoch 01/20 | Train Total 3.096949 | Contrast 0.602836 | Train Gap 0.193233 | Val ImbOLL 2.164485 | Val Gap -0.020220 | Val Pair 0.472727 | Val CCC 0.074137 | 6.19s
Epoch 02/20 | Train Total 1.403739 | Contrast 0.619338 | Train Gap 0.010127 | Val ImbOLL 3.491480 | Val Gap -0.000128 | Val Pair 0.400000 | Val CCC 0.405585 | 5.53s
Epoch 03/20 | Train Total 1.683149 | Contrast 0.650435 | Train Gap 0.000719 | Val ImbOLL 2.484164 | Val Gap 0.005195 | Val Pair 0.400000 | Val CCC 0.275278 | 6.01s
Epoch 04/20 | Train Total 1.303792 | Contrast 0.637142 | Train Gap 0.005821 | Val ImbOLL 2.205538 | Val Gap -0.000926 | Val Pair 0.400000 | Val CCC 0.326196 | 5.76s
Epoch 05/20 | Train Total 1.247914 | Contrast 0.639038 | Train Gap -0.001588 | Val ImbOLL 3.169157 | Val Gap -0.001165 | Val Pair 0.418182 | Val CCC 0.202306 | 6.27s
Epoch 06/20 | Train Total 1.555148 | Contrast 0.680483 | Train Gap -0.000178 | Val ImbOLL 2.179534 | Val Gap 0.000251 | Val Pair 0.472727 | Val CCC 0.427725 | 5.83s
Epoch 07/20 | Train Total 1.134120 | Contrast 0.595669 | Train Gap -0.000639 | Val ImbOLL 2.823722 | Val Gap -0.000019 | Val Pair 0.381818 | Val CCC 0.213682 | 4.94s
Epoch 08/20 | Train Total 1.175700 | Contrast 0.693225 | Train Gap -0.000089 | Val ImbOLL 2.708375 | Val Gap -0.000785 | Val Pair 0.436364 | Val CCC 0.361990 | 5.88s
Epoch 09/20 | Train Total 1.285868 | Contrast 0.650919 | Train Gap -0.000572 | Val ImbOLL 2.749091 | Val Gap 0.000248 | Val Pair 0.563636 | Val CCC 0.201392 | 5.73s
Epoch 10/20 | Train Total 1.320086 | Contrast 0.607705 | Train Gap 0.000793 | Val ImbOLL 2.321790 | Val Gap 0.000598 | Val Pair 0.490909 | Val CCC 0.179163 | 5.32s
Epoch 11/20 | Train Total 1.129471 | Contrast 0.595064 | Train Gap 0.000565 | Val ImbOLL 3.262648 | Val Gap 0.000717 | Val Pair 0.581818 | Val CCC 0.180810 | 5.08s
Epoch 12/20 | Train Total 1.465329 | Contrast 0.636393 | Train Gap 0.003017 | Val ImbOLL 2.847653 | Val Gap 0.000568 | Val Pair 0.454545 | Val CCC 0.388024 | 5.22s
Epoch 13/20 | Train Total 1.207944 | Contrast 0.649990 | Train Gap 0.001282 | Val ImbOLL 2.018277 | Val Gap -0.000093 | Val Pair 0.400000 | Val CCC 0.275278 | 5.28s
Epoch 14/20 | Train Total 1.181403 | Contrast 0.650432 | Train Gap 0.000433 | Val ImbOLL 3.040937 | Val Gap -0.000005 | Val Pair 0.418182 | Val CCC 0.301430 | 5.43s
Epoch 15/20 | Train Total 1.188652 | Contrast 0.650399 | Train Gap 0.000502 | Val ImbOLL 2.568228 | Val Gap 0.001180 | Val Pair 0.472727 | Val CCC 0.201392 | 5.26s
Epoch 16/20 | Train Total 1.167365 | Contrast 0.679082 | Train Gap 0.002870 | Val ImbOLL 2.996197 | Val Gap 0.001147 | Val Pair 0.490909 | Val CCC 0.337409 | 5.26s
Epoch 17/20 | Train Total 1.338777 | Contrast 0.593895 | Train Gap 0.002956 | Val ImbOLL 2.613597 | Val Gap 0.001658 | Val Pair 0.490909 | Val CCC 0.308574 | 4.73s
Epoch 18/20 | Train Total 1.101965 | Contrast 0.636718 | Train Gap 0.002478 | Val ImbOLL 3.239465 | Val Gap 0.001171 | Val Pair 0.454545 | Val CCC 0.180810 | 5.01s
Epoch 19/20 | Train Total 1.404813 | Contrast 0.678815 | Train Gap 0.003347 | Val ImbOLL 2.590986 | Val Gap 0.001284 | Val Pair 0.454545 | Val CCC 0.246760 | 5.27s
Epoch 20/20 | Train Total 1.202933 | Contrast 0.638455 | Train Gap -0.000692 | Val ImbOLL 3.025259 | Val Gap 0.006578 | Val Pair 0.472727 | Val CCC 0.180810 | 5.19s
====================================================================================================
定向Audio训练完成：Seed=42，Q8
最佳Val ImbOLL：2.018277，Epoch=13
最佳Val CCC：0.427725，Epoch=6
====================================================================================================
文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q8_PHQ_8Moving/seed_100/best_ccc.pt
语音Best Loss： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_100/question_8/best_ccc.pt
文本保存Epoch： 14
语音保存Epoch： 20
文本缺少参数： []
文本多余参数： []
语音缺少参数： []
语音多余参数： []
====================================================================================================
开始定向Audio训练：Seed=100，Q8，PHQ_8Moving
Lambda=0.1，Margin=0.0，Negative Sets=1
Text固定：True，Label固定：True，只打乱Audio：True
类别数量： [128, 20, 9, 6]
输出目录： /workspace/E-DAIC/checkpoints/phq8_text_audio_label_aware_deterministic_best_ccc_encoders/lambda_0p1_margin_0_neg_1/seed_100/question_8
====================================================================================================
Epoch 01/20 | Train Total 1.732098 | Contrast 0.624327 | Train Gap 0.040756 | Val ImbOLL 2.685027 | Val Gap -0.028031 | Val Pair 0.418182 | Val CCC 0.213682 | 5.18s
Epoch 02/20 | Train Total 1.238360 | Contrast 0.603394 | Train Gap 0.012604 | Val ImbOLL 4.231942 | Val Gap -0.007479 | Val Pair 0.490909 | Val CCC 0.161482 | 5.28s
Epoch 03/20 | Train Total 1.412928 | Contrast 0.637806 | Train Gap 0.000256 | Val ImbOLL 2.953361 | Val Gap -0.001095 | Val Pair 0.545455 | Val CCC 0.198397 | 5.82s
Epoch 04/20 | Train Total 1.299981 | Contrast 0.636470 | Train Gap 0.003145 | Val ImbOLL 4.404242 | Val Gap 0.003126 | Val Pair 0.472727 | Val CCC 0.191742 | 5.46s
Epoch 05/20 | Train Total 1.309437 | Contrast 0.639788 | Train Gap 0.027888 | Val ImbOLL 3.336086 | Val Gap 0.029105 | Val Pair 0.436364 | Val CCC 0.215471 | 5.53s
Epoch 06/20 | Train Total 1.210988 | Contrast 0.554076 | Train Gap 0.028877 | Val ImbOLL 4.853721 | Val Gap -0.000548 | Val Pair 0.600000 | Val CCC 0.180810 | 4.95s
Epoch 07/20 | Train Total 1.368198 | Contrast 0.647540 | Train Gap 0.006682 | Val ImbOLL 3.934534 | Val Gap 0.006239 | Val Pair 0.436364 | Val CCC 0.215724 | 5.72s
Epoch 08/20 | Train Total 1.207138 | Contrast 0.560800 | Train Gap 0.012507 | Val ImbOLL 4.312016 | Val Gap -0.002151 | Val Pair 0.400000 | Val CCC 0.159592 | 4.90s
Epoch 09/20 | Train Total 1.355349 | Contrast 0.642943 | Train Gap 0.019149 | Val ImbOLL 3.096776 | Val Gap 0.013174 | Val Pair 0.618182 | Val CCC 0.199418 | 5.74s
Epoch 10/20 | Train Total 1.329533 | Contrast 0.676424 | Train Gap 0.011779 | Val ImbOLL 2.733775 | Val Gap 0.015069 | Val Pair 0.636364 | Val CCC 0.252605 | 5.47s
Epoch 11/20 | Train Total 1.213828 | Contrast 0.637464 | Train Gap 0.004407 | Val ImbOLL 3.047696 | Val Gap 0.013610 | Val Pair 0.600000 | Val CCC 0.270809 | 5.24s
Epoch 12/20 | Train Total 1.133734 | Contrast 0.670438 | Train Gap 0.080855 | Val ImbOLL 4.094697 | Val Gap 0.038246 | Val Pair 0.563636 | Val CCC 0.232188 | 5.82s
Epoch 13/20 | Train Total 1.225527 | Contrast 0.647602 | Train Gap 0.030477 | Val ImbOLL 4.137072 | Val Gap 0.016581 | Val Pair 0.490909 | Val CCC 0.307812 | 5.37s
Epoch 14/20 | Train Total 1.219712 | Contrast 0.552848 | Train Gap 0.033152 | Val ImbOLL 4.527687 | Val Gap 0.020417 | Val Pair 0.454545 | Val CCC 0.307812 | 5.16s
Epoch 15/20 | Train Total 1.282767 | Contrast 0.538666 | Train Gap 0.043508 | Val ImbOLL 3.158446 | Val Gap 0.106549 | Val Pair 0.472727 | Val CCC 0.135579 | 4.84s
Epoch 16/20 | Train Total 1.494825 | Contrast 0.634699 | Train Gap 0.043233 | Val ImbOLL 3.885865 | Val Gap 0.016576 | Val Pair 0.527273 | Val CCC 0.260285 | 5.10s
Epoch 17/20 | Train Total 1.227001 | Contrast 0.671741 | Train Gap 0.022673 | Val ImbOLL 3.563015 | Val Gap 0.019115 | Val Pair 0.509091 | Val CCC 0.289210 | 5.52s
Epoch 18/20 | Train Total 1.481486 | Contrast 0.589726 | Train Gap 0.014077 | Val ImbOLL 3.551787 | Val Gap 0.023002 | Val Pair 0.545455 | Val CCC 0.314689 | 5.07s
Epoch 19/20 | Train Total 1.013192 | Contrast 0.584912 | Train Gap 0.031184 | Val ImbOLL 3.439685 | Val Gap 0.046432 | Val Pair 0.545455 | Val CCC 0.289210 | 4.79s
Epoch 20/20 | Train Total 1.083751 | Contrast 0.540650 | Train Gap 0.057131 | Val ImbOLL 3.061055 | Val Gap 0.119626 | Val Pair 0.618182 | Val CCC 0.218234 | 4.65s
====================================================================================================
定向Audio训练完成：Seed=100，Q8
最佳Val ImbOLL：2.685027，Epoch=1
最佳Val CCC：0.314689，Epoch=18
====================================================================================================
文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q8_PHQ_8Moving/seed_1234/best_ccc.pt
语音Best Loss： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_1234/question_8/best_ccc.pt
文本保存Epoch： 13
语音保存Epoch： 30
文本缺少参数： []
文本多余参数： []
语音缺少参数： []
语音多余参数： []
====================================================================================================
开始定向Audio训练：Seed=1234，Q8，PHQ_8Moving
Lambda=0.1，Margin=0.0，Negative Sets=1
Text固定：True，Label固定：True，只打乱Audio：True
类别数量： [128, 20, 9, 6]
输出目录： /workspace/E-DAIC/checkpoints/phq8_text_audio_label_aware_deterministic_best_ccc_encoders/lambda_0p1_margin_0_neg_1/seed_1234/question_8
====================================================================================================
Epoch 01/20 | Train Total 2.373088 | Contrast 0.644836 | Train Gap 0.046427 | Val ImbOLL 2.669705 | Val Gap -0.010227 | Val Pair 0.327273 | Val CCC 0.215998 | 5.67s
Epoch 02/20 | Train Total 1.327485 | Contrast 0.605881 | Train Gap 0.016316 | Val ImbOLL 5.007875 | Val Gap -0.002147 | Val Pair 0.309091 | Val CCC 0.230953 | 5.18s
Epoch 03/20 | Train Total 1.283322 | Contrast 0.647920 | Train Gap 0.006342 | Val ImbOLL 3.446895 | Val Gap -0.001691 | Val Pair 0.436364 | Val CCC 0.215724 | 5.38s
Epoch 04/20 | Train Total 1.080542 | Contrast 0.590740 | Train Gap 0.013063 | Val ImbOLL 4.278665 | Val Gap -0.002768 | Val Pair 0.436364 | Val CCC 0.159592 | 4.92s
Epoch 05/20 | Train Total 1.142451 | Contrast 0.599483 | Train Gap 0.021563 | Val ImbOLL 5.826367 | Val Gap -0.000464 | Val Pair 0.381818 | Val CCC 0.211348 | 5.70s
Epoch 06/20 | Train Total 1.432936 | Contrast 0.608167 | Train Gap 0.000788 | Val ImbOLL 4.953783 | Val Gap 0.003058 | Val Pair 0.418182 | Val CCC 0.159592 | 5.64s
Epoch 07/20 | Train Total 1.134485 | Contrast 0.650683 | Train Gap 0.001628 | Val ImbOLL 4.204210 | Val Gap 0.002064 | Val Pair 0.618182 | Val CCC 0.172821 | 5.78s
Epoch 08/20 | Train Total 1.164124 | Contrast 0.678302 | Train Gap 0.004806 | Val ImbOLL 4.515618 | Val Gap 0.001887 | Val Pair 0.472727 | Val CCC 0.153889 | 5.61s
Epoch 09/20 | Train Total 1.068606 | Contrast 0.634307 | Train Gap 0.008505 | Val ImbOLL 4.777852 | Val Gap 0.004114 | Val Pair 0.418182 | Val CCC 0.159592 | 5.33s
Epoch 10/20 | Train Total 1.052515 | Contrast 0.568189 | Train Gap -0.002804 | Val ImbOLL 4.642918 | Val Gap 0.001843 | Val Pair 0.400000 | Val CCC 0.208207 | 4.87s
Epoch 11/20 | Train Total 1.128222 | Contrast 0.641087 | Train Gap -0.004075 | Val ImbOLL 4.852643 | Val Gap 0.007750 | Val Pair 0.418182 | Val CCC 0.159592 | 5.30s
Epoch 12/20 | Train Total 1.077803 | Contrast 0.611330 | Train Gap -0.003943 | Val ImbOLL 6.082558 | Val Gap -0.000721 | Val Pair 0.400000 | Val CCC 0.211348 | 5.33s
Epoch 13/20 | Train Total 1.082751 | Contrast 0.604027 | Train Gap 0.008663 | Val ImbOLL 5.716887 | Val Gap 0.003528 | Val Pair 0.545455 | Val CCC 0.246153 | 5.28s
Epoch 14/20 | Train Total 1.063036 | Contrast 0.635729 | Train Gap 0.008239 | Val ImbOLL 4.838806 | Val Gap 0.003364 | Val Pair 0.472727 | Val CCC 0.221966 | 5.25s
Epoch 15/20 | Train Total 1.292415 | Contrast 0.648819 | Train Gap 0.005498 | Val ImbOLL 3.480168 | Val Gap 0.005131 | Val Pair 0.454545 | Val CCC 0.294954 | 5.45s
Epoch 16/20 | Train Total 1.120031 | Contrast 0.609643 | Train Gap 0.002327 | Val ImbOLL 3.821589 | Val Gap 0.018635 | Val Pair 0.581818 | Val CCC 0.180810 | 5.19s
Epoch 17/20 | Train Total 1.021711 | Contrast 0.685109 | Train Gap 0.025222 | Val ImbOLL 3.777182 | Val Gap 0.016400 | Val Pair 0.345455 | Val CCC 0.294954 | 5.78s
Epoch 18/20 | Train Total 0.980505 | Contrast 0.683635 | Train Gap -0.003545 | Val ImbOLL 4.389473 | Val Gap 0.012230 | Val Pair 0.545455 | Val CCC 0.153889 | 5.35s
Epoch 19/20 | Train Total 1.249274 | Contrast 0.551083 | Train Gap 0.008166 | Val ImbOLL 5.203519 | Val Gap 0.041761 | Val Pair 0.527273 | Val CCC 0.218473 | 4.48s
Epoch 20/20 | Train Total 0.972604 | Contrast 0.638865 | Train Gap 0.007496 | Val ImbOLL 2.764211 | Val Gap 0.034368 | Val Pair 0.418182 | Val CCC 0.344404 | 4.98s
====================================================================================================
定向Audio训练完成：Seed=1234，Q8
最佳Val ImbOLL：2.669705，Epoch=1
最佳Val CCC：0.344404，Epoch=20
====================================================================================================

In [283]:
FINAL_SEEDS = [42, 100, 1234]
FINAL_QUESTION_INDICES = list(range(8))
FINAL_AUDIO_CONTRAST_LAMBDA = 0.1
FINAL_AUDIO_CONTRAST_MARGIN = 0.0
FINAL_AUDIO_CONTRAST_NEGATIVE_SETS = 1
FUSION_BEST_CCC_ENCODER_CHECKPOINT_ROOT = FUSION_CHECKPOINT_ROOT.parent / f"{FUSION_CHECKPOINT_ROOT.name}_best_ccc_encoders"
AUDIO_CONTRAST_CHECKPOINT_ROOT = FUSION_CHECKPOINT_ROOT.parent / "phq8_text_audio_label_aware_deterministic_best_ccc_encoders"

In [284]:
def load_completed_question_result(output_dir, question_index, seed, experiment_type):
    output_dir = Path(output_dir)
    history_path = output_dir / "history.csv"
    best_loss_path = output_dir / "best_loss.pt"
    best_ccc_path = output_dir / "best_ccc.pt"
    last_path = output_dir / "last.pt"
    if not history_path.exists():
        return None
    history = pd.read_csv(history_path)
    if len(history) < NUM_EPOCHS:
        return None
    if not best_loss_path.exists() or not best_ccc_path.exists() or not last_path.exists():
        return None
    best_loss_row_index = history["Val_Loss"].idxmin()
    best_ccc_row_index = history["Val_CCC"].idxmax()
    best_val_loss = float(history.loc[best_loss_row_index, "Val_Loss"])
    best_val_ccc = float(history.loc[best_ccc_row_index, "Val_CCC"])
    best_loss_epoch = int(history.loc[best_loss_row_index, "Epoch"])
    best_ccc_epoch = int(history.loc[best_ccc_row_index, "Epoch"])
    return {"experiment_type": experiment_type, "seed": seed, "question_index": question_index, "question_number": question_index + 1, "question_name": PHQ8_QUESTION_COLUMNS[question_index], "best_val_loss": best_val_loss, "best_val_ccc": best_val_ccc, "best_loss_epoch": best_loss_epoch, "best_ccc_epoch": best_ccc_epoch, "best_loss_path": best_loss_path, "best_ccc_path": best_ccc_path, "last_path": last_path, "history_path": history_path}

In [285]:
def get_best_ccc_baseline_output_dir(question_index, seed):
    return FUSION_BEST_CCC_ENCODER_CHECKPOINT_ROOT / f"seed_{seed}" / f"question_{question_index + 1}"

def get_directional_audio_output_dir(question_index, seed):
    lambda_tag = f"{FINAL_AUDIO_CONTRAST_LAMBDA:.6g}".replace("-", "m").replace(".", "p")
    margin_tag = f"{FINAL_AUDIO_CONTRAST_MARGIN:.6g}".replace("-", "m").replace(".", "p")
    return AUDIO_CONTRAST_CHECKPOINT_ROOT / f"lambda_{lambda_tag}_margin_{margin_tag}_neg_{FINAL_AUDIO_CONTRAST_NEGATIVE_SETS}" / f"seed_{seed}" / f"question_{question_index + 1}"

In [288]:
final_best_ccc_baseline_results = {}
final_directional_audio_results = {}

for question_index in FINAL_QUESTION_INDICES:
    for seed in FINAL_SEEDS:
        baseline_output_dir = get_best_ccc_baseline_output_dir(question_index, seed)
        baseline_result = load_completed_question_result(baseline_output_dir, question_index, seed, "text_audio_best_ccc_encoders")
        if baseline_result is None:
            print(f"开始训练基线：Seed={seed}，Q{question_index + 1}")
            baseline_result = train_fusion_question_best_ccc_encoders(question_index=question_index, seed=seed)
        else:
            print(f"跳过已完成基线：Seed={seed}，Q{question_index + 1}，CCC={baseline_result['best_val_ccc']:.6f}")
        final_best_ccc_baseline_results[(question_index, seed)] = baseline_result
        directional_output_dir = get_directional_audio_output_dir(question_index, seed)
        directional_result = load_completed_question_result(directional_output_dir, question_index, seed, "text_audio_label_aware_deterministic_audio_contrast_best_ccc_encoders")
        if directional_result is None:
            print(f"开始训练定向Audio：Seed={seed}，Q{question_index + 1}")
            directional_result = train_fusion_question_label_aware_deterministic_audio_contrast(question_index=question_index, seed=seed, lambda_audio=FINAL_AUDIO_CONTRAST_LAMBDA, margin=FINAL_AUDIO_CONTRAST_MARGIN, num_negative_sets=FINAL_AUDIO_CONTRAST_NEGATIVE_SETS, encoder_checkpoint_type="best_ccc")
        else:
            print(f"跳过已完成定向Audio：Seed={seed}，Q{question_index + 1}，CCC={directional_result['best_val_ccc']:.6f}")
        final_directional_audio_results[(question_index, seed)] = directional_result
        print(f"完成配对：Seed={seed}，Q{question_index + 1}，Baseline={baseline_result['best_val_ccc']:.6f}，Directional={directional_result['best_val_ccc']:.6f}，Change={directional_result['best_val_ccc'] - baseline_result['best_val_ccc']:.6f}")

跳过已完成基线：Seed=42，Q1，CCC=0.461966
开始训练定向Audio：Seed=42，Q1
文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q1_PHQ_8NoInterest/seed_42/best_ccc.pt
语音Best Loss： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_42/question_1/best_ccc.pt
文本保存Epoch： 9
语音保存Epoch： 14
文本缺少参数： []
文本多余参数： []
语音缺少参数： []
语音多余参数： []
====================================================================================================
开始定向Audio训练：Seed=42，Q1，PHQ_8NoInterest
Lambda=0.1，Margin=0.0，Negative Sets=1
Text固定：True，Label固定：True，只打乱Audio：True
类别数量： [81, 57, 20, 5]
输出目录： /workspace/E-DAIC/checkpoints/phq8_text_audio_label_aware_deterministic_best_ccc_encoders/lambda_0p1_margin_0_neg_1/seed_42/question_1
====================================================================================================
Epoch 01/20 | Train Total 2.139447 | Contrast 0.658275 | Train Gap 0.062142 | Val ImbOLL 2.367797 | Val Gap -0.051313 | Val Pair 0.545455 | Val CCC 0.387652 | 5.98s
Epoch 02/20 | Train Total 1.602852 | Contrast 0.692744 | Train Gap 0.008210 | Val ImbOLL 2.953332 | Val Gap -0.030663 | Val Pair 0.400000 | Val CCC 0.381247 | 5.80s
Epoch 03/20 | Train Total 1.496962 | Contrast 0.686312 | Train Gap 0.019198 | Val ImbOLL 2.421411 | Val Gap -0.061862 | Val Pair 0.345455 | Val CCC 0.458923 | 5.89s
Epoch 04/20 | Train Total 1.512484 | Contrast 0.692086 | Train Gap 0.011072 | Val ImbOLL 2.576044 | Val Gap -0.042599 | Val Pair 0.345455 | Val CCC 0.286377 | 5.76s
Epoch 05/20 | Train Total 1.513185 | Contrast 0.674864 | Train Gap 0.021944 | Val ImbOLL 2.629066 | Val Gap -0.043583 | Val Pair 0.400000 | Val CCC 0.344380 | 5.52s
Epoch 06/20 | Train Total 1.505601 | Contrast 0.694664 | Train Gap 0.007456 | Val ImbOLL 2.524499 | Val Gap -0.054161 | Val Pair 0.327273 | Val CCC 0.411482 | 5.87s
Epoch 07/20 | Train Total 1.466620 | Contrast 0.689870 | Train Gap 0.015074 | Val ImbOLL 2.574917 | Val Gap -0.047981 | Val Pair 0.309091 | Val CCC 0.325189 | 5.92s
Epoch 08/20 | Train Total 1.475523 | Contrast 0.679669 | Train Gap 0.037147 | Val ImbOLL 2.558409 | Val Gap -0.037793 | Val Pair 0.272727 | Val CCC 0.297493 | 6.01s
Epoch 09/20 | Train Total 1.498762 | Contrast 0.684302 | Train Gap 0.022959 | Val ImbOLL 2.366577 | Val Gap -0.045512 | Val Pair 0.345455 | Val CCC 0.419851 | 5.66s
Epoch 10/20 | Train Total 1.464487 | Contrast 0.682150 | Train Gap 0.011736 | Val ImbOLL 2.375940 | Val Gap -0.063491 | Val Pair 0.345455 | Val CCC 0.419851 | 5.69s
Epoch 11/20 | Train Total 1.509293 | Contrast 0.689466 | Train Gap 0.011626 | Val ImbOLL 2.729621 | Val Gap -0.019125 | Val Pair 0.381818 | Val CCC 0.269527 | 6.03s
Epoch 12/20 | Train Total 1.440126 | Contrast 0.684692 | Train Gap 0.022947 | Val ImbOLL 2.414153 | Val Gap -0.042923 | Val Pair 0.345455 | Val CCC 0.450448 | 5.65s
Epoch 13/20 | Train Total 1.375886 | Contrast 0.688503 | Train Gap 0.017534 | Val ImbOLL 2.532418 | Val Gap -0.036421 | Val Pair 0.309091 | Val CCC 0.361862 | 5.76s
Epoch 14/20 | Train Total 1.372151 | Contrast 0.685307 | Train Gap 0.022965 | Val ImbOLL 2.563624 | Val Gap -0.036197 | Val Pair 0.509091 | Val CCC 0.481013 | 5.58s
Epoch 15/20 | Train Total 1.361429 | Contrast 0.682825 | Train Gap 0.038959 | Val ImbOLL 2.489636 | Val Gap -0.054752 | Val Pair 0.345455 | Val CCC 0.392601 | 5.51s
Epoch 16/20 | Train Total 1.320567 | Contrast 0.686912 | Train Gap 0.022985 | Val ImbOLL 2.695140 | Val Gap -0.042564 | Val Pair 0.545455 | Val CCC 0.353436 | 5.76s
Epoch 17/20 | Train Total 1.381249 | Contrast 0.688890 | Train Gap 0.013962 | Val ImbOLL 2.583171 | Val Gap -0.046708 | Val Pair 0.418182 | Val CCC 0.343766 | 5.72s
Epoch 18/20 | Train Total 1.368260 | Contrast 0.685254 | Train Gap 0.024543 | Val ImbOLL 3.245670 | Val Gap -0.046848 | Val Pair 0.600000 | Val CCC 0.267048 | 5.93s
Epoch 19/20 | Train Total 1.471960 | Contrast 0.683888 | Train Gap 0.052674 | Val ImbOLL 2.633253 | Val Gap -0.050083 | Val Pair 0.545455 | Val CCC 0.380146 | 5.67s
Epoch 20/20 | Train Total 1.347496 | Contrast 0.688990 | Train Gap 0.027352 | Val ImbOLL 2.577885 | Val Gap -0.021920 | Val Pair 0.545455 | Val CCC 0.439318 | 5.77s
====================================================================================================
定向Audio训练完成：Seed=42，Q1
最佳Val ImbOLL：2.366577，Epoch=9
最佳Val CCC：0.481013，Epoch=14
====================================================================================================
完成配对：Seed=42，Q1，Baseline=0.461966，Directional=0.481013，Change=0.019048
开始训练基线：Seed=100，Q1
文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q1_PHQ_8NoInterest/seed_100/best_ccc.pt
语音Best Loss： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_100/question_1/best_ccc.pt
文本保存Epoch： 13
语音保存Epoch： 43
文本缺少参数： []
文本多余参数： []
语音缺少参数： []
语音多余参数： []
====================================================================================================
开始训练Best-CCC编码器版本：Seed=100，Q1，PHQ_8NoInterest
编码器检查点类型：best_ccc
文本检查点： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q1_PHQ_8NoInterest/seed_100/best_ccc.pt
语音检查点： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_100/question_1/best_ccc.pt
类别数量： [81, 57, 20, 5]
====================================================================================================
Epoch 01/20 | Train Loss 1.913170 | Val Loss 3.521148 | Val CCC 0.343696 | Val Acc 0.509091 | Val RMSE 1.000000 | 0.83s
Epoch 02/20 | Train Loss 1.505922 | Val Loss 2.894744 | Val CCC 0.336055 | Val Acc 0.509091 | Val RMSE 0.943880 | 0.82s
Epoch 03/20 | Train Loss 1.275915 | Val Loss 3.160136 | Val CCC 0.325081 | Val Acc 0.454545 | Val RMSE 0.953463 | 0.82s
Epoch 04/20 | Train Loss 1.411554 | Val Loss 2.843477 | Val CCC 0.345346 | Val Acc 0.490909 | Val RMSE 0.904534 | 0.82s
Epoch 05/20 | Train Loss 1.372305 | Val Loss 2.633746 | Val CCC 0.342759 | Val Acc 0.509091 | Val RMSE 0.863397 | 0.79s
Epoch 06/20 | Train Loss 1.339269 | Val Loss 3.388228 | Val CCC 0.327709 | Val Acc 0.527273 | Val RMSE 0.934199 | 0.78s
Epoch 07/20 | Train Loss 1.239319 | Val Loss 3.157479 | Val CCC 0.328120 | Val Acc 0.563636 | Val RMSE 0.914529 | 0.77s
Epoch 08/20 | Train Loss 1.278475 | Val Loss 3.772337 | Val CCC 0.287715 | Val Acc 0.527273 | Val RMSE 0.934199 | 0.78s
Epoch 09/20 | Train Loss 1.265579 | Val Loss 3.423113 | Val CCC 0.338044 | Val Acc 0.545455 | Val RMSE 0.924416 | 0.77s
Epoch 10/20 | Train Loss 1.306599 | Val Loss 2.764618 | Val CCC 0.345346 | Val Acc 0.490909 | Val RMSE 0.904534 | 0.80s
Epoch 11/20 | Train Loss 1.281642 | Val Loss 2.843299 | Val CCC 0.320989 | Val Acc 0.509091 | Val RMSE 0.863397 | 0.79s
Epoch 12/20 | Train Loss 1.251667 | Val Loss 3.138323 | Val CCC 0.318755 | Val Acc 0.472727 | Val RMSE 0.962950 | 0.81s
Epoch 13/20 | Train Loss 1.199178 | Val Loss 2.731995 | Val CCC 0.342759 | Val Acc 0.509091 | Val RMSE 0.863397 | 0.79s
Epoch 14/20 | Train Loss 1.300649 | Val Loss 3.262102 | Val CCC 0.364837 | Val Acc 0.509091 | Val RMSE 0.894427 | 0.79s
Epoch 15/20 | Train Loss 1.216727 | Val Loss 2.735941 | Val CCC 0.335924 | Val Acc 0.472727 | Val RMSE 0.914529 | 0.80s
Epoch 16/20 | Train Loss 1.209602 | Val Loss 3.153348 | Val CCC 0.406229 | Val Acc 0.545455 | Val RMSE 0.842075 | 0.84s
Epoch 17/20 | Train Loss 1.132679 | Val Loss 2.868103 | Val CCC 0.300019 | Val Acc 0.472727 | Val RMSE 0.962950 | 0.80s
Epoch 18/20 | Train Loss 1.163183 | Val Loss 3.642860 | Val CCC 0.280224 | Val Acc 0.472727 | Val RMSE 0.962950 | 0.82s
Epoch 19/20 | Train Loss 1.302245 | Val Loss 3.068491 | Val CCC 0.317506 | Val Acc 0.472727 | Val RMSE 0.934199 | 0.82s
Epoch 20/20 | Train Loss 1.119164 | Val Loss 3.027617 | Val CCC 0.384268 | Val Acc 0.490909 | Val RMSE 0.873863 | 0.79s
====================================================================================================
Best-CCC编码器版本训练完成：Seed=100，Q1
最佳Val Loss：2.633746，Epoch=5
最佳Val CCC：0.406229，Epoch=16
====================================================================================================
开始训练定向Audio：Seed=100，Q1
文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q1_PHQ_8NoInterest/seed_100/best_ccc.pt
语音Best Loss： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_100/question_1/best_ccc.pt
文本保存Epoch： 13
语音保存Epoch： 43
文本缺少参数： []
文本多余参数： []
语音缺少参数： []
语音多余参数： []
====================================================================================================
开始定向Audio训练：Seed=100，Q1，PHQ_8NoInterest
Lambda=0.1，Margin=0.0，Negative Sets=1
Text固定：True，Label固定：True，只打乱Audio：True
类别数量： [81, 57, 20, 5]
输出目录： /workspace/E-DAIC/checkpoints/phq8_text_audio_label_aware_deterministic_best_ccc_encoders/lambda_0p1_margin_0_neg_1/seed_100/question_1
====================================================================================================
Epoch 01/20 | Train Total 2.028944 | Contrast 0.684984 | Train Gap 0.040790 | Val ImbOLL 3.728808 | Val Gap -0.014137 | Val Pair 0.618182 | Val CCC 0.295370 | 5.81s
Epoch 02/20 | Train Total 1.576316 | Contrast 0.690579 | Train Gap 0.008698 | Val ImbOLL 3.382211 | Val Gap -0.011689 | Val Pair 0.636364 | Val CCC 0.354740 | 5.68s
Epoch 03/20 | Train Total 1.485815 | Contrast 0.671216 | Train Gap 0.024743 | Val ImbOLL 2.927762 | Val Gap -0.046599 | Val Pair 0.327273 | Val CCC 0.344052 | 5.84s
Epoch 04/20 | Train Total 1.379932 | Contrast 0.672155 | Train Gap 0.030988 | Val ImbOLL 2.810332 | Val Gap -0.071083 | Val Pair 0.327273 | Val CCC 0.343523 | 5.48s
Epoch 05/20 | Train Total 1.348017 | Contrast 0.678459 | Train Gap 0.043276 | Val ImbOLL 2.601115 | Val Gap -0.071376 | Val Pair 0.327273 | Val CCC 0.322135 | 6.06s
Epoch 06/20 | Train Total 1.337253 | Contrast 0.666912 | Train Gap 0.038839 | Val ImbOLL 3.612551 | Val Gap -0.031300 | Val Pair 0.527273 | Val CCC 0.356234 | 5.84s
Epoch 07/20 | Train Total 1.374747 | Contrast 0.685949 | Train Gap 0.032652 | Val ImbOLL 2.796833 | Val Gap -0.053831 | Val Pair 0.327273 | Val CCC 0.311741 | 5.79s
Epoch 08/20 | Train Total 1.395433 | Contrast 0.683577 | Train Gap 0.033684 | Val ImbOLL 3.554835 | Val Gap -0.016823 | Val Pair 0.545455 | Val CCC 0.327709 | 5.73s
Epoch 09/20 | Train Total 1.331056 | Contrast 0.681207 | Train Gap 0.032522 | Val ImbOLL 3.346634 | Val Gap -0.033913 | Val Pair 0.527273 | Val CCC 0.308503 | 5.89s
Epoch 10/20 | Train Total 1.317475 | Contrast 0.689044 | Train Gap 0.013256 | Val ImbOLL 2.926126 | Val Gap -0.032074 | Val Pair 0.490909 | Val CCC 0.289018 | 5.72s
Epoch 11/20 | Train Total 1.262185 | Contrast 0.687069 | Train Gap 0.026530 | Val ImbOLL 2.963370 | Val Gap -0.105840 | Val Pair 0.490909 | Val CCC 0.342255 | 5.97s
Epoch 12/20 | Train Total 1.263715 | Contrast 0.679823 | Train Gap 0.048958 | Val ImbOLL 3.429507 | Val Gap -0.032863 | Val Pair 0.545455 | Val CCC 0.318769 | 5.61s
Epoch 13/20 | Train Total 1.227267 | Contrast 0.687225 | Train Gap 0.017933 | Val ImbOLL 2.707676 | Val Gap -0.058922 | Val Pair 0.400000 | Val CCC 0.363479 | 5.70s
Epoch 14/20 | Train Total 1.436681 | Contrast 0.678578 | Train Gap 0.077243 | Val ImbOLL 4.108620 | Val Gap -0.038879 | Val Pair 0.545455 | Val CCC 0.318769 | 5.73s
Epoch 15/20 | Train Total 1.329260 | Contrast 0.668486 | Train Gap 0.037415 | Val ImbOLL 2.724264 | Val Gap -0.026672 | Val Pair 0.454545 | Val CCC 0.395314 | 5.50s
Epoch 16/20 | Train Total 1.196618 | Contrast 0.670979 | Train Gap 0.036296 | Val ImbOLL 3.009723 | Val Gap -0.019396 | Val Pair 0.545455 | Val CCC 0.280224 | 5.43s
Epoch 17/20 | Train Total 1.245164 | Contrast 0.686594 | Train Gap 0.033191 | Val ImbOLL 2.955933 | Val Gap -0.031418 | Val Pair 0.472727 | Val CCC 0.354585 | 5.84s
Epoch 18/20 | Train Total 1.295726 | Contrast 0.688761 | Train Gap 0.015929 | Val ImbOLL 3.055897 | Val Gap -0.041606 | Val Pair 0.436364 | Val CCC 0.384268 | 5.59s
Epoch 19/20 | Train Total 1.220748 | Contrast 0.680148 | Train Gap 0.039700 | Val ImbOLL 2.922165 | Val Gap -0.020329 | Val Pair 0.490909 | Val CCC 0.317506 | 5.77s
Epoch 20/20 | Train Total 1.163589 | Contrast 0.674073 | Train Gap 0.058322 | Val ImbOLL 3.313472 | Val Gap -0.051383 | Val Pair 0.527273 | Val CCC 0.254632 | 6.08s
====================================================================================================
定向Audio训练完成：Seed=100，Q1
最佳Val ImbOLL：2.601115，Epoch=5
最佳Val CCC：0.395314，Epoch=15
====================================================================================================
完成配对：Seed=100，Q1，Baseline=0.406229，Directional=0.395314，Change=-0.010915
开始训练基线：Seed=1234，Q1
文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q1_PHQ_8NoInterest/seed_1234/best_ccc.pt
语音Best Loss： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_1234/question_1/best_ccc.pt
文本保存Epoch： 11
语音保存Epoch： 12
文本缺少参数： []
文本多余参数： []
语音缺少参数： []
语音多余参数： []
====================================================================================================
开始训练Best-CCC编码器版本：Seed=1234，Q1，PHQ_8NoInterest
编码器检查点类型：best_ccc
文本检查点： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q1_PHQ_8NoInterest/seed_1234/best_ccc.pt
语音检查点： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_1234/question_1/best_ccc.pt
类别数量： [81, 57, 20, 5]
====================================================================================================
Epoch 01/20 | Train Loss 2.047107 | Val Loss 2.458007 | Val CCC 0.447762 | Val Acc 0.545455 | Val RMSE 0.842075 | 0.83s
Epoch 02/20 | Train Loss 1.385235 | Val Loss 2.866319 | Val CCC 0.303154 | Val Acc 0.563636 | Val RMSE 0.894427 | 0.77s
Epoch 03/20 | Train Loss 1.327181 | Val Loss 2.376792 | Val CCC 0.308920 | Val Acc 0.563636 | Val RMSE 0.863397 | 0.77s
Epoch 04/20 | Train Loss 1.353718 | Val Loss 2.867493 | Val CCC 0.395889 | Val Acc 0.581818 | Val RMSE 0.852803 | 0.77s
Epoch 05/20 | Train Loss 1.318023 | Val Loss 2.534017 | Val CCC 0.363479 | Val Acc 0.527273 | Val RMSE 0.884205 | 0.79s
Epoch 06/20 | Train Loss 1.277149 | Val Loss 2.891899 | Val CCC 0.365843 | Val Acc 0.581818 | Val RMSE 0.884205 | 0.78s
Epoch 07/20 | Train Loss 1.262101 | Val Loss 2.487398 | Val CCC 0.307688 | Val Acc 0.509091 | Val RMSE 0.863397 | 0.79s
Epoch 08/20 | Train Loss 1.362833 | Val Loss 2.405519 | Val CCC 0.322170 | Val Acc 0.527273 | Val RMSE 0.884205 | 0.83s
Epoch 09/20 | Train Loss 1.245871 | Val Loss 2.555437 | Val CCC 0.354883 | Val Acc 0.563636 | Val RMSE 0.863397 | 0.79s
Epoch 10/20 | Train Loss 1.292331 | Val Loss 2.629207 | Val CCC 0.354883 | Val Acc 0.563636 | Val RMSE 0.863397 | 0.86s
Epoch 11/20 | Train Loss 1.329493 | Val Loss 2.566045 | Val CCC 0.354883 | Val Acc 0.563636 | Val RMSE 0.863397 | 0.73s
Epoch 12/20 | Train Loss 1.274752 | Val Loss 3.255968 | Val CCC 0.280751 | Val Acc 0.600000 | Val RMSE 0.953463 | 0.77s
Epoch 13/20 | Train Loss 1.246548 | Val Loss 2.602092 | Val CCC 0.333589 | Val Acc 0.545455 | Val RMSE 0.873863 | 0.73s
Epoch 14/20 | Train Loss 1.163001 | Val Loss 2.661582 | Val CCC 0.333589 | Val Acc 0.545455 | Val RMSE 0.873863 | 0.73s
Epoch 15/20 | Train Loss 1.274185 | Val Loss 2.647513 | Val CCC 0.376128 | Val Acc 0.563636 | Val RMSE 0.831209 | 0.75s
Epoch 16/20 | Train Loss 1.332435 | Val Loss 3.368287 | Val CCC 0.291452 | Val Acc 0.509091 | Val RMSE 0.972345 | 0.73s
Epoch 17/20 | Train Loss 1.296769 | Val Loss 3.422014 | Val CCC 0.299634 | Val Acc 0.545455 | Val RMSE 0.953463 | 0.74s
Epoch 18/20 | Train Loss 1.242420 | Val Loss 2.700828 | Val CCC 0.354883 | Val Acc 0.563636 | Val RMSE 0.863397 | 0.75s
Epoch 19/20 | Train Loss 1.103255 | Val Loss 2.540017 | Val CCC 0.331457 | Val Acc 0.509091 | Val RMSE 0.863397 | 0.75s
Epoch 20/20 | Train Loss 1.248224 | Val Loss 2.733544 | Val CCC 0.433719 | Val Acc 0.563636 | Val RMSE 0.774597 | 0.76s
====================================================================================================
Best-CCC编码器版本训练完成：Seed=1234，Q1
最佳Val Loss：2.376792，Epoch=3
最佳Val CCC：0.447762，Epoch=1
====================================================================================================
开始训练定向Audio：Seed=1234，Q1
文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q1_PHQ_8NoInterest/seed_1234/best_ccc.pt
语音Best Loss： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_1234/question_1/best_ccc.pt
文本保存Epoch： 11
语音保存Epoch： 12
文本缺少参数： []
文本多余参数： []
语音缺少参数： []
语音多余参数： []
====================================================================================================
开始定向Audio训练：Seed=1234，Q1，PHQ_8NoInterest
Lambda=0.1，Margin=0.0，Negative Sets=1
Text固定：True，Label固定：True，只打乱Audio：True
类别数量： [81, 57, 20, 5]
输出目录： /workspace/E-DAIC/checkpoints/phq8_text_audio_label_aware_deterministic_best_ccc_encoders/lambda_0p1_margin_0_neg_1/seed_1234/question_1
====================================================================================================
Epoch 01/20 | Train Total 2.085061 | Contrast 0.679932 | Train Gap 0.041086 | Val ImbOLL 2.429572 | Val Gap -0.033756 | Val Pair 0.418182 | Val CCC 0.418412 | 5.78s
Epoch 02/20 | Train Total 1.586231 | Contrast 0.695653 | Train Gap 0.008430 | Val ImbOLL 2.818915 | Val Gap -0.059493 | Val Pair 0.309091 | Val CCC 0.365477 | 5.74s
Epoch 03/20 | Train Total 1.521997 | Contrast 0.668699 | Train Gap 0.031829 | Val ImbOLL 2.365676 | Val Gap -0.030360 | Val Pair 0.363636 | Val CCC 0.312135 | 5.56s
Epoch 04/20 | Train Total 1.430815 | Contrast 0.685004 | Train Gap 0.018520 | Val ImbOLL 2.633539 | Val Gap -0.032266 | Val Pair 0.381818 | Val CCC 0.303154 | 5.83s
Epoch 05/20 | Train Total 1.393205 | Contrast 0.685467 | Train Gap 0.017873 | Val ImbOLL 2.528533 | Val Gap -0.036810 | Val Pair 0.400000 | Val CCC 0.444196 | 5.67s
Epoch 06/20 | Train Total 1.365300 | Contrast 0.687705 | Train Gap 0.017375 | Val ImbOLL 3.074417 | Val Gap -0.050905 | Val Pair 0.400000 | Val CCC 0.237074 | 5.90s
Epoch 07/20 | Train Total 1.293820 | Contrast 0.687501 | Train Gap 0.021832 | Val ImbOLL 2.468584 | Val Gap -0.070391 | Val Pair 0.381818 | Val CCC 0.403008 | 5.64s
Epoch 08/20 | Train Total 1.447379 | Contrast 0.668621 | Train Gap 0.032966 | Val ImbOLL 2.632828 | Val Gap -0.053740 | Val Pair 0.381818 | Val CCC 0.364454 | 5.38s
Epoch 09/20 | Train Total 1.322649 | Contrast 0.668451 | Train Gap 0.029071 | Val ImbOLL 2.489543 | Val Gap -0.070406 | Val Pair 0.400000 | Val CCC 0.276551 | 5.41s
Epoch 10/20 | Train Total 1.314674 | Contrast 0.682647 | Train Gap 0.025896 | Val ImbOLL 2.605766 | Val Gap -0.053806 | Val Pair 0.400000 | Val CCC 0.333589 | 5.58s
Epoch 11/20 | Train Total 1.346677 | Contrast 0.681926 | Train Gap 0.035422 | Val ImbOLL 2.600502 | Val Gap -0.087592 | Val Pair 0.400000 | Val CCC 0.355289 | 5.70s
Epoch 12/20 | Train Total 1.348409 | Contrast 0.687078 | Train Gap 0.018456 | Val ImbOLL 3.090626 | Val Gap -0.033555 | Val Pair 0.363636 | Val CCC 0.249031 | 5.62s
Epoch 13/20 | Train Total 1.349729 | Contrast 0.682984 | Train Gap 0.025767 | Val ImbOLL 2.476015 | Val Gap -0.066721 | Val Pair 0.381818 | Val CCC 0.410504 | 5.67s
Epoch 14/20 | Train Total 1.284955 | Contrast 0.687804 | Train Gap 0.026490 | Val ImbOLL 2.821252 | Val Gap -0.107683 | Val Pair 0.363636 | Val CCC 0.278958 | 5.98s
Epoch 15/20 | Train Total 1.288990 | Contrast 0.681568 | Train Gap 0.038710 | Val ImbOLL 2.505176 | Val Gap -0.101648 | Val Pair 0.345455 | Val CCC 0.438353 | 5.66s
Epoch 16/20 | Train Total 1.253746 | Contrast 0.665958 | Train Gap 0.071751 | Val ImbOLL 2.755738 | Val Gap -0.066847 | Val Pair 0.363636 | Val CCC 0.335406 | 5.91s
Epoch 17/20 | Train Total 1.227584 | Contrast 0.692208 | Train Gap 0.038830 | Val ImbOLL 2.865897 | Val Gap -0.112616 | Val Pair 0.381818 | Val CCC 0.317560 | 5.81s
Epoch 18/20 | Train Total 1.322796 | Contrast 0.681091 | Train Gap 0.048887 | Val ImbOLL 3.423563 | Val Gap -0.071906 | Val Pair 0.381818 | Val CCC 0.223027 | 5.77s
Epoch 19/20 | Train Total 1.280530 | Contrast 0.654430 | Train Gap 0.121243 | Val ImbOLL 2.645837 | Val Gap -0.138476 | Val Pair 0.381818 | Val CCC 0.363966 | 5.64s
Epoch 20/20 | Train Total 1.282957 | Contrast 0.681598 | Train Gap 0.048302 | Val ImbOLL 2.591864 | Val Gap -0.113564 | Val Pair 0.363636 | Val CCC 0.342113 | 5.56s
====================================================================================================

In [289]:
paired_question_rows = []

for question_index in FINAL_QUESTION_INDICES:
    for seed in FINAL_SEEDS:
        baseline_result = final_best_ccc_baseline_results[(question_index, seed)]
        directional_result = final_directional_audio_results[(question_index, seed)]
        paired_question_rows.append({"Question_Index": question_index, "Question_Number": question_index + 1, "Question_Name": PHQ8_QUESTION_COLUMNS[question_index], "Seed": seed, "Baseline_CCC": baseline_result["best_val_ccc"], "Directional_Audio_CCC": directional_result["best_val_ccc"], "CCC_Change": directional_result["best_val_ccc"] - baseline_result["best_val_ccc"], "Baseline_Best_Epoch": baseline_result["best_ccc_epoch"], "Directional_Best_Epoch": directional_result["best_ccc_epoch"]})

paired_question_results = pd.DataFrame(paired_question_rows)
display(paired_question_results)

,Question_Index,Question_Number,Question_Name,Seed,Baseline_CCC,Directional_Audio_CCC,CCC_Change,Baseline_Best_Epoch,Directional_Best_Epoch
0,0,1,PHQ_8NoInterest,42,0.461966,0.481013,1.904786e-02,6,14
1,0,1,PHQ_8NoInterest,100,0.406229,0.395314,-1.091495e-02,16,15
2,0,1,PHQ_8NoInterest,1234,0.447762,0.444196,-3.565490e-03,1,5
3,1,2,PHQ_8Depressed,42,0.515744,0.528385,1.264054e-02,5,2
4,1,2,PHQ_8Depressed,100,0.492937,0.502262,9.325296e-03,4,14
5,1,2,PHQ_8Depressed,1234,0.513291,0.531648,1.835692e-02,5,11
6,2,3,PHQ_8Sleep,42,0.500697,0.500697,-5.960464e-08,7,15
7,2,3,PHQ_8Sleep,100,0.434638,0.446400,1.176217e-02,7,13
8,2,3,PHQ_8Sleep,1234,0.399652,0.418473,1.882121e-02,13,16
9,3,4,PHQ_8Tired,42,0.503766,0.436482,-6.728438e-02,15,19
10,3,4,PHQ_8Tired,100,0.474075,0.478611,4.535645e-03,15,11
11,3,4,PHQ_8Tired,1234,0.604490,0.554677,-4.981256e-02,6,9
12,4,5,PHQ_8Appetite,42,0.591709,0.579163,-1.254624e-02,9,9
13,4,5,PHQ_8Appetite,100,0.502340,0.483778,-1.856172e-02,11,11
14,4,5,PHQ_8Appetite,1234,0.501509,0.512211,1.070130e-02,12,17
15,5,6,PHQ_8Failure,42,0.536422,0.522436,-1.398587e-02,11,9
16,5,6,PHQ_8Failure,100,0.467631,0.426870,-4.076046e-02,11,6
17,5,6,PHQ_8Failure,1234,0.543955,0.548734,4.778802e-03,9,2
18,6,7,PHQ_8Concentrating,42,0.556817,0.537205,-1.961225e-02,2,12
19,6,7,PHQ_8Concentrating,100,0.542044,0.545758,3.714442e-03,4,11
20,6,7,PHQ_8Concentrating,1234,0.532294,0.535596,3.301919e-03,13,14
21,7,8,PHQ_8Moving,42,0.388024,0.427725,3.970116e-02,16,6
22,7,8,PHQ_8Moving,100,0.314689,0.314689,0.000000e+00,17,18
23,7,8,PHQ_8Moving,1234,0.291190,0.344404,5.321440e-02,20,20

In [290]:
paired_question_summary = paired_question_results.groupby(["Question_Index", "Question_Number", "Question_Name"], as_index=False).agg(Baseline_Mean_CCC=("Baseline_CCC", "mean"), Baseline_Std_CCC=("Baseline_CCC", "std"), Directional_Mean_CCC=("Directional_Audio_CCC", "mean"), Directional_Std_CCC=("Directional_Audio_CCC", "std"), Mean_CCC_Change=("CCC_Change", "mean"), Improved_Seeds=("CCC_Change", lambda values: int((values > 0).sum())), Unchanged_Seeds=("CCC_Change", lambda values: int(np.isclose(values, 0.0).sum())), Decreased_Seeds=("CCC_Change", lambda values: int((values < 0).sum())))
display(paired_question_summary)

,Question_Index,Question_Number,Question_Name,Baseline_Mean_CCC,Baseline_Std_CCC,Directional_Mean_CCC,Directional_Std_CCC,Mean_CCC_Change,Improved_Seeds,Unchanged_Seeds,Decreased_Seeds
0,0,1,PHQ_8NoInterest,0.438652,0.028963,0.440175,0.042991,0.001522,1,0,2
1,1,2,PHQ_8Depressed,0.507324,0.012520,0.520765,0.016107,0.013441,3,0,0
2,2,3,PHQ_8Sleep,0.444996,0.051313,0.455190,0.041811,0.010194,2,0,1
3,3,4,PHQ_8Tired,0.527444,0.068355,0.489923,0.059904,-0.037520,1,0,2
4,4,5,PHQ_8Appetite,0.531853,0.051839,0.525050,0.048971,-0.006802,1,0,2
5,5,6,PHQ_8Failure,0.516003,0.042060,0.499347,0.064129,-0.016656,1,0,2
6,6,7,PHQ_8Concentrating,0.543718,0.012347,0.539520,0.005462,-0.004199,2,0,1
7,7,8,PHQ_8Moving,0.331301,0.050509,0.362273,0.058598,0.030972,2,1,0

In [291]:
print("24组配对中的平均CCC变化：", paired_question_results["CCC_Change"].mean())
print("提高的Question-Seed数量：", int((paired_question_results["CCC_Change"] > 0).sum()))
print("持平的Question-Seed数量：", int(np.isclose(paired_question_results["CCC_Change"], 0.0).sum()))
print("下降的Question-Seed数量：", int((paired_question_results["CCC_Change"] < 0).sum()))
print("平均基线CCC：", paired_question_results["Baseline_CCC"].mean())
print("平均定向Audio CCC：", paired_question_results["Directional_Audio_CCC"].mean())

24组配对中的平均CCC变化： -0.001130929837624232
提高的Question-Seed数量： 13
持平的Question-Seed数量： 1
下降的Question-Seed数量： 10
平均基线CCC： 0.4801612322529157
平均定向Audio CCC： 0.4790303024152915

In [292]:
AUDIO_CONTRAST_CHECKPOINT_ROOT.mkdir(parents=True, exist_ok=True)
paired_question_results.to_csv(AUDIO_CONTRAST_CHECKPOINT_ROOT / "paired_question_seed_results.csv", index=False)
paired_question_summary.to_csv(AUDIO_CONTRAST_CHECKPOINT_ROOT / "paired_question_summary.csv", index=False)

In [293]:
AUDIO_AUX_CHECKPOINT_ROOT = Path("/workspace/E-DAIC/checkpoints/phq8_fusion_audio_aux_best_ccc")
AUDIO_AUX_LAMBDA = 0.1

class TextAudioQuestMFAudioAux(nn.Module):
    def __init__(self, text_encoder, audio_encoder):
        super().__init__()
        self.text_encoder = text_encoder
        self.audio_encoder = audio_encoder
        self.audio_to_text_cross_attention = nn.MultiheadAttention(embed_dim=ENCODER_OUTPUT_DIM, num_heads=ATTENTION_HEADS, dropout=FUSION_DROPOUT, batch_first=True)
        self.text_to_audio_cross_attention = nn.MultiheadAttention(embed_dim=ENCODER_OUTPUT_DIM, num_heads=ATTENTION_HEADS, dropout=FUSION_DROPOUT, batch_first=True)
        self.text_self_attention = nn.MultiheadAttention(embed_dim=ENCODER_OUTPUT_DIM, num_heads=ATTENTION_HEADS, dropout=FUSION_DROPOUT, batch_first=True)
        self.audio_self_attention = nn.MultiheadAttention(embed_dim=ENCODER_OUTPUT_DIM, num_heads=ATTENTION_HEADS, dropout=FUSION_DROPOUT, batch_first=True)
        self.mlp = nn.Sequential(nn.Flatten(), nn.Dropout(MLP_FIRST_DROPOUT), nn.Linear(MAX_TURNS * ENCODER_OUTPUT_DIM * 2, 256), nn.ReLU(), nn.Dropout(MLP_LAST_DROPOUT), nn.Linear(256, NUM_CLASSES))
        self.audio_aux_head = nn.Sequential(nn.LayerNorm(ENCODER_OUTPUT_DIM), nn.Dropout(FUSION_DROPOUT), nn.Linear(ENCODER_OUTPUT_DIM, NUM_CLASSES))
        for parameter in self.text_encoder.parameters():
            parameter.requires_grad = False
        self.text_encoder.eval()

    def train(self, mode=True):
        super().train(mode)
        self.text_encoder.eval()
        return self

    def forward(self, text_features, text_padding_mask, audio_features, audio_padding_mask, return_intermediates=False):
        text_encoding = self.text_encoder(text_features, text_padding_mask)
        audio_encoding = self.audio_encoder(audio_features, audio_padding_mask)
        text_encoding = text_encoding.masked_fill(text_padding_mask.unsqueeze(-1), 0.0)
        audio_encoding = audio_encoding.masked_fill(audio_padding_mask.unsqueeze(-1), 0.0)
        audio_valid_mask = (~audio_padding_mask).unsqueeze(-1).to(audio_encoding.dtype)
        audio_sum = torch.sum(audio_encoding * audio_valid_mask, dim=1)
        audio_count = torch.sum(audio_valid_mask, dim=1).clamp_min(1.0)
        audio_pooled = audio_sum / audio_count
        audio_aux_logits = self.audio_aux_head(audio_pooled)
        audio_to_text, _ = self.audio_to_text_cross_attention(text_encoding, audio_encoding, audio_encoding, key_padding_mask=audio_padding_mask, need_weights=False)
        text_to_audio, _ = self.text_to_audio_cross_attention(audio_encoding, text_encoding, text_encoding, key_padding_mask=text_padding_mask, need_weights=False)
        text_fused_encoding, _ = self.text_self_attention(audio_to_text, audio_to_text, audio_to_text, key_padding_mask=text_padding_mask, need_weights=False)
        audio_fused_encoding, _ = self.audio_self_attention(text_to_audio, text_to_audio, text_to_audio, key_padding_mask=audio_padding_mask, need_weights=False)
        fused_encoding = torch.cat((text_fused_encoding, audio_fused_encoding), dim=2)
        fusion_logits = self.mlp(fused_encoding)
        if return_intermediates:
            intermediates = {"text_encoding": text_encoding, "audio_encoding": audio_encoding, "audio_pooled": audio_pooled, "audio_to_text": audio_to_text, "text_to_audio": text_to_audio, "text_fused_encoding": text_fused_encoding, "audio_fused_encoding": audio_fused_encoding, "fused_encoding": fused_encoding}
            return fusion_logits, audio_aux_logits, intermediates
        return fusion_logits, audio_aux_logits

In [294]:
def run_fusion_epoch_audio_aux(model, dataloader, question_index, class_weights, lambda_audio_aux, optimizer=None):
    is_training = optimizer is not None
    if is_training:
        model.train()
    else:
        model.eval()
    total_combined_loss = 0.0
    total_fusion_loss = 0.0
    total_audio_aux_loss = 0.0
    total_samples = 0
    fusion_prediction_batches = []
    audio_aux_prediction_batches = []
    target_batches = []
    for batch in dataloader:
        text_features, text_masks, audio_features, audio_masks, all_labels = batch
        text_features = text_features.to(device)
        text_masks = text_masks.to(device)
        audio_features = audio_features.to(device)
        audio_masks = audio_masks.to(device)
        labels = all_labels[:, question_index].to(device)
        if is_training:
            optimizer.zero_grad(set_to_none=True)
        with torch.set_grad_enabled(is_training):
            fusion_logits, audio_aux_logits = model(text_features, text_masks, audio_features, audio_masks)
            fusion_loss = calculate_imboll_loss(fusion_logits, labels, class_weights, ALPHA)
            audio_aux_loss = calculate_imboll_loss(audio_aux_logits, labels, class_weights, ALPHA)
            combined_loss = fusion_loss + lambda_audio_aux * audio_aux_loss
            if is_training:
                combined_loss.backward()
                torch.nn.utils.clip_grad_norm_(model.parameters(), MAX_GRAD_NORM)
                optimizer.step()
        fusion_predictions = torch.argmax(fusion_logits, dim=1)
        audio_aux_predictions = torch.argmax(audio_aux_logits, dim=1)
        batch_size = labels.shape[0]
        total_combined_loss += combined_loss.item() * batch_size
        total_fusion_loss += fusion_loss.item() * batch_size
        total_audio_aux_loss += audio_aux_loss.item() * batch_size
        total_samples += batch_size
        fusion_prediction_batches.append(fusion_predictions.detach().cpu())
        audio_aux_prediction_batches.append(audio_aux_predictions.detach().cpu())
        target_batches.append(labels.detach().cpu())
    fusion_predictions = torch.cat(fusion_prediction_batches, dim=0)
    audio_aux_predictions = torch.cat(audio_aux_prediction_batches, dim=0)
    all_targets = torch.cat(target_batches, dim=0)
    fusion_metrics = calculate_multiclass_metrics(fusion_predictions, all_targets)
    audio_aux_metrics = calculate_multiclass_metrics(audio_aux_predictions, all_targets)
    fusion_ccc = calculate_sample_ccc(fusion_predictions.float(), all_targets.float()).item()
    audio_aux_ccc = calculate_sample_ccc(audio_aux_predictions.float(), all_targets.float()).item()
    fusion_rmse = torch.sqrt(torch.mean((fusion_predictions.float() - all_targets.float()) ** 2)).item()
    fusion_mae = torch.mean(torch.abs(fusion_predictions.float() - all_targets.float())).item()
    return {"loss": total_combined_loss / total_samples, "total_loss": total_combined_loss / total_samples, "fusion_imboll_loss": total_fusion_loss / total_samples, "audio_aux_imboll_loss": total_audio_aux_loss / total_samples, "accuracy": fusion_metrics["accuracy"], "micro_f1": fusion_metrics["micro_f1"], "macro_f1": fusion_metrics["macro_f1"], "weighted_f1": fusion_metrics["weighted_f1"], "ccc": fusion_ccc, "rmse": fusion_rmse, "mae": fusion_mae, "confusion_matrix": fusion_metrics["confusion_matrix"], "predictions": fusion_predictions, "targets": all_targets, "audio_aux_accuracy": audio_aux_metrics["accuracy"], "audio_aux_macro_f1": audio_aux_metrics["macro_f1"], "audio_aux_ccc": audio_aux_ccc, "audio_aux_confusion_matrix": audio_aux_metrics["confusion_matrix"], "audio_aux_predictions": audio_aux_predictions}

In [295]:
def calculate_gradient_group_norm(gradients):
    squared_norm = sum(gradient.detach().float().pow(2).sum().item() for gradient in gradients if gradient is not None)
    return squared_norm ** 0.5

def check_audio_aux_gradient_routing(model, dataloader, question_index, class_weights):
    model.train()
    batch = next(iter(dataloader))
    text_features, text_masks, audio_features, audio_masks, all_labels = batch
    text_features = text_features.to(device)
    text_masks = text_masks.to(device)
    audio_features = audio_features.to(device)
    audio_masks = audio_masks.to(device)
    labels = all_labels[:, question_index].to(device)
    fusion_logits, audio_aux_logits = model(text_features, text_masks, audio_features, audio_masks)
    audio_aux_loss = calculate_imboll_loss(audio_aux_logits, labels, class_weights, ALPHA)
    audio_parameters = [parameter for parameter in model.audio_encoder.parameters() if parameter.requires_grad]
    audio_aux_head_parameters = [parameter for parameter in model.audio_aux_head.parameters() if parameter.requires_grad]
    fusion_parameters = list(model.audio_to_text_cross_attention.parameters()) + list(model.text_to_audio_cross_attention.parameters()) + list(model.text_self_attention.parameters()) + list(model.audio_self_attention.parameters()) + list(model.mlp.parameters())
    tracked_parameters = audio_parameters + audio_aux_head_parameters + fusion_parameters
    gradients = torch.autograd.grad(audio_aux_loss, tracked_parameters, allow_unused=True)
    audio_end = len(audio_parameters)
    audio_aux_head_end = audio_end + len(audio_aux_head_parameters)
    audio_gradients = gradients[:audio_end]
    audio_aux_head_gradients = gradients[audio_end:audio_aux_head_end]
    fusion_gradients = gradients[audio_aux_head_end:]
    result = {"Audio_Encoder_Aux_Grad": calculate_gradient_group_norm(audio_gradients), "Audio_Aux_Head_Grad": calculate_gradient_group_norm(audio_aux_head_gradients), "Fusion_Blocks_Aux_Grad": calculate_gradient_group_norm(fusion_gradients), "Trainable_Text_Parameters": sum(parameter.numel() for parameter in model.text_encoder.parameters() if parameter.requires_grad)}
    model.zero_grad(set_to_none=True)
    print(result)
    return result

In [296]:
set_seed(42)
q8_class_counts, q8_inverse_frequency_weights, q8_imboll_weights = calculate_imboll_weights(train_fusion_dataset.labels[:, 7], BETA)
q8_imboll_weights_device = q8_imboll_weights.to(device)
q8_smoke_text_encoder, q8_smoke_audio_encoder, _, _, _, _ = load_pretrained_text_audio_encoders(question_index=7, seed=42, checkpoint_type="best_ccc")
q8_audio_aux_smoke_model = TextAudioQuestMFAudioAux(q8_smoke_text_encoder, q8_smoke_audio_encoder).to(device)
q8_smoke_train_loader, q8_smoke_val_loader = create_fusion_dataloaders(seed=42)
q8_audio_aux_gradient_result = check_audio_aux_gradient_routing(q8_audio_aux_smoke_model, q8_smoke_train_loader, question_index=7, class_weights=q8_imboll_weights_device)
del q8_audio_aux_smoke_model
if torch.cuda.is_available():
    torch.cuda.empty_cache()

文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q8_PHQ_8Moving/seed_42/best_ccc.pt
语音Best Loss： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_42/question_8/best_ccc.pt
文本保存Epoch： 12
语音保存Epoch： 44
文本缺少参数： []
文本多余参数： []
语音缺少参数： []
语音多余参数： []
{'Audio_Encoder_Aux_Grad': 42.70122988274316, 'Audio_Aux_Head_Grad': 11.26226592148774, 'Fusion_Blocks_Aux_Grad': 0.0, 'Trainable_Text_Parameters': 0}

In [297]:
def create_fusion_audio_aux_checkpoint(model, optimizer, checkpoint_type, epoch, question_index, seed, train_metrics, val_metrics, class_counts, imboll_weights, text_checkpoint_path, audio_checkpoint_path, lambda_audio_aux, best_val_fusion_loss, best_val_fusion_ccc, best_val_audio_aux_ccc, best_fusion_loss_epoch, best_fusion_ccc_epoch, best_audio_aux_ccc_epoch):
    checkpoint = {"experiment_type": "fusion_audio_auxiliary_imboll", "checkpoint_type": checkpoint_type, "epoch": epoch, "question_index": question_index, "question_number": question_index + 1, "question_name": PHQ8_QUESTION_COLUMNS[question_index], "seed": seed, "model_state_dict": model.state_dict(), "optimizer_state_dict": optimizer.state_dict(), "train_metrics": train_metrics, "val_metrics": val_metrics, "class_counts": class_counts, "imboll_weights": imboll_weights, "text_checkpoint_path": str(text_checkpoint_path), "audio_checkpoint_path": str(audio_checkpoint_path), "encoder_checkpoint_type": "best_ccc", "lambda_audio_aux": lambda_audio_aux, "best_val_fusion_loss": best_val_fusion_loss, "best_val_fusion_ccc": best_val_fusion_ccc, "best_val_audio_aux_ccc": best_val_audio_aux_ccc, "best_fusion_loss_epoch": best_fusion_loss_epoch, "best_fusion_ccc_epoch": best_fusion_ccc_epoch, "best_audio_aux_ccc_epoch": best_audio_aux_ccc_epoch}
    return checkpoint

In [298]:
def train_fusion_question_audio_aux(question_index, seed, lambda_audio_aux=0.1):
    set_seed(seed)
    question_number = question_index + 1
    question_name = PHQ8_QUESTION_COLUMNS[question_index]
    output_dir = AUDIO_AUX_CHECKPOINT_ROOT / f"seed_{seed}" / f"question_{question_number}"
    output_dir.mkdir(parents=True, exist_ok=True)
    best_fusion_loss_path = output_dir / "best_fusion_imboll.pt"
    best_fusion_ccc_path = output_dir / "best_fusion_ccc.pt"
    best_audio_aux_ccc_path = output_dir / "best_audio_aux_ccc.pt"
    last_path = output_dir / "last.pt"
    history_path = output_dir / "history.csv"
    train_loader, val_loader = create_fusion_dataloaders(seed)
    train_labels = train_fusion_dataset.labels[:, question_index]
    class_counts, inverse_frequency_weights, imboll_weights = calculate_imboll_weights(train_labels, BETA)
    imboll_weights_device = imboll_weights.to(device)
    text_encoder, audio_encoder, _, _, text_checkpoint_path, audio_checkpoint_path = load_pretrained_text_audio_encoders(question_index=question_index, seed=seed, checkpoint_type="best_ccc")
    model = TextAudioQuestMFAudioAux(text_encoder=text_encoder, audio_encoder=audio_encoder).to(device)
    optimizer = torch.optim.AdamW([parameter for parameter in model.parameters() if parameter.requires_grad], lr=LEARNING_RATE, eps=ADAM_EPSILON, weight_decay=WEIGHT_DECAY)
    best_val_fusion_loss = float("inf")
    best_val_fusion_ccc = float("-inf")
    best_val_audio_aux_ccc = float("-inf")
    best_fusion_loss_epoch = None
    best_fusion_ccc_epoch = None
    best_audio_aux_ccc_epoch = None
    history_rows = []
    print("=" * 100)
    print(f"开始Audio辅助监督训练：Seed={seed}，Q{question_number}，{question_name}")
    print(f"Lambda Audio Aux：{lambda_audio_aux}")
    print("单模态初始化：best_ccc")
    print("类别数量：", class_counts.tolist())
    print("=" * 100)
    for epoch in range(1, NUM_EPOCHS + 1):
        epoch_start_time = time.time()
        train_metrics = run_fusion_epoch_audio_aux(model, train_loader, question_index, imboll_weights_device, lambda_audio_aux, optimizer)
        val_metrics = run_fusion_epoch_audio_aux(model, val_loader, question_index, imboll_weights_device, lambda_audio_aux, optimizer=None)
        epoch_seconds = time.time() - epoch_start_time
        history_row = {"Epoch": epoch, "Train_Total_Loss": train_metrics["total_loss"], "Train_Fusion_ImbOLL": train_metrics["fusion_imboll_loss"], "Train_Audio_Aux_ImbOLL": train_metrics["audio_aux_imboll_loss"], "Train_Fusion_CCC": train_metrics["ccc"], "Train_Audio_Aux_CCC": train_metrics["audio_aux_ccc"], "Val_Total_Loss": val_metrics["total_loss"], "Val_Fusion_ImbOLL": val_metrics["fusion_imboll_loss"], "Val_Audio_Aux_ImbOLL": val_metrics["audio_aux_imboll_loss"], "Val_Fusion_Accuracy": val_metrics["accuracy"], "Val_Fusion_Macro_F1": val_metrics["macro_f1"], "Val_Fusion_CCC": val_metrics["ccc"], "Val_Audio_Aux_Accuracy": val_metrics["audio_aux_accuracy"], "Val_Audio_Aux_Macro_F1": val_metrics["audio_aux_macro_f1"], "Val_Audio_Aux_CCC": val_metrics["audio_aux_ccc"], "Val_RMSE": val_metrics["rmse"], "Val_MAE": val_metrics["mae"], "Seconds": epoch_seconds}
        history_rows.append(history_row)
        if not np.isfinite(val_metrics["fusion_imboll_loss"]):
            raise RuntimeError(f"Seed={seed}，Q{question_number}在Epoch={epoch}出现非有限Fusion ImbOLL")
        if not np.isfinite(val_metrics["ccc"]):
            raise RuntimeError(f"Seed={seed}，Q{question_number}在Epoch={epoch}出现非有限Fusion CCC")
        if not np.isfinite(val_metrics["audio_aux_ccc"]):
            raise RuntimeError(f"Seed={seed}，Q{question_number}在Epoch={epoch}出现非有限Audio Aux CCC")
        improved_fusion_loss = val_metrics["fusion_imboll_loss"] < best_val_fusion_loss
        improved_fusion_ccc = val_metrics["ccc"] > best_val_fusion_ccc
        improved_audio_aux_ccc = val_metrics["audio_aux_ccc"] > best_val_audio_aux_ccc
        if improved_fusion_loss:
            best_val_fusion_loss = val_metrics["fusion_imboll_loss"]
            best_fusion_loss_epoch = epoch
        if improved_fusion_ccc:
            best_val_fusion_ccc = val_metrics["ccc"]
            best_fusion_ccc_epoch = epoch
        if improved_audio_aux_ccc:
            best_val_audio_aux_ccc = val_metrics["audio_aux_ccc"]
            best_audio_aux_ccc_epoch = epoch
        if improved_fusion_loss:
            checkpoint = create_fusion_audio_aux_checkpoint(model, optimizer, "best_fusion_imboll", epoch, question_index, seed, train_metrics, val_metrics, class_counts, imboll_weights, text_checkpoint_path, audio_checkpoint_path, lambda_audio_aux, best_val_fusion_loss, best_val_fusion_ccc, best_val_audio_aux_ccc, best_fusion_loss_epoch, best_fusion_ccc_epoch, best_audio_aux_ccc_epoch)
            torch.save(checkpoint, best_fusion_loss_path)
        if improved_fusion_ccc:
            checkpoint = create_fusion_audio_aux_checkpoint(model, optimizer, "best_fusion_ccc", epoch, question_index, seed, train_metrics, val_metrics, class_counts, imboll_weights, text_checkpoint_path, audio_checkpoint_path, lambda_audio_aux, best_val_fusion_loss, best_val_fusion_ccc, best_val_audio_aux_ccc, best_fusion_loss_epoch, best_fusion_ccc_epoch, best_audio_aux_ccc_epoch)
            torch.save(checkpoint, best_fusion_ccc_path)
        if improved_audio_aux_ccc:
            checkpoint = create_fusion_audio_aux_checkpoint(model, optimizer, "best_audio_aux_ccc", epoch, question_index, seed, train_metrics, val_metrics, class_counts, imboll_weights, text_checkpoint_path, audio_checkpoint_path, lambda_audio_aux, best_val_fusion_loss, best_val_fusion_ccc, best_val_audio_aux_ccc, best_fusion_loss_epoch, best_fusion_ccc_epoch, best_audio_aux_ccc_epoch)
            torch.save(checkpoint, best_audio_aux_ccc_path)
        last_checkpoint = create_fusion_audio_aux_checkpoint(model, optimizer, "last", epoch, question_index, seed, train_metrics, val_metrics, class_counts, imboll_weights, text_checkpoint_path, audio_checkpoint_path, lambda_audio_aux, best_val_fusion_loss, best_val_fusion_ccc, best_val_audio_aux_ccc, best_fusion_loss_epoch, best_fusion_ccc_epoch, best_audio_aux_ccc_epoch)
        torch.save(last_checkpoint, last_path)
        pd.DataFrame(history_rows).to_csv(history_path, index=False)
        print(f"Epoch {epoch:02d}/{NUM_EPOCHS} | Train Fusion CCC {train_metrics['ccc']:.6f} | Train Audio CCC {train_metrics['audio_aux_ccc']:.6f} | Val Fusion ImbOLL {val_metrics['fusion_imboll_loss']:.6f} | Val Fusion CCC {val_metrics['ccc']:.6f} | Val Audio CCC {val_metrics['audio_aux_ccc']:.6f} | {epoch_seconds:.2f}s")
    result = {"seed": seed, "question_index": question_index, "question_number": question_number, "question_name": question_name, "lambda_audio_aux": lambda_audio_aux, "best_val_fusion_loss": best_val_fusion_loss, "best_val_fusion_ccc": best_val_fusion_ccc, "best_val_audio_aux_ccc": best_val_audio_aux_ccc, "best_fusion_loss_epoch": best_fusion_loss_epoch, "best_fusion_ccc_epoch": best_fusion_ccc_epoch, "best_audio_aux_ccc_epoch": best_audio_aux_ccc_epoch, "best_fusion_loss_path": best_fusion_loss_path, "best_fusion_ccc_path": best_fusion_ccc_path, "best_audio_aux_ccc_path": best_audio_aux_ccc_path, "last_path": last_path, "history_path": history_path}
    del model
    del optimizer
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
    print("=" * 100)
    print(f"Audio辅助监督训练完成：Seed={seed}，Q{question_number}")
    print(f"最佳Val Fusion ImbOLL：{best_val_fusion_loss:.6f}，Epoch={best_fusion_loss_epoch}")
    print(f"最佳Val Fusion CCC：{best_val_fusion_ccc:.6f}，Epoch={best_fusion_ccc_epoch}")
    print(f"最佳Val Audio Aux CCC：{best_val_audio_aux_ccc:.6f}，Epoch={best_audio_aux_ccc_epoch}")
    print("=" * 100)
    return result

In [299]:
q8_seed42_audio_aux_result = train_fusion_question_audio_aux(question_index=7, seed=42, lambda_audio_aux=0.1)

文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q8_PHQ_8Moving/seed_42/best_ccc.pt
语音Best Loss： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_42/question_8/best_ccc.pt
文本保存Epoch： 12
语音保存Epoch： 44
文本缺少参数： []
文本多余参数： []
语音缺少参数： []
语音多余参数： []
====================================================================================================
开始Audio辅助监督训练：Seed=42，Q8，PHQ_8Moving
Lambda Audio Aux：0.1
单模态初始化：best_ccc
类别数量： [128, 20, 9, 6]
====================================================================================================
Epoch 01/20 | Train Fusion CCC 0.177927 | Train Audio CCC 0.019987 | Val Fusion ImbOLL 2.012310 | Val Fusion CCC 0.134101 | Val Audio CCC 0.142991 | 1.16s
Epoch 02/20 | Train Fusion CCC 0.575613 | Train Audio CCC 0.158087 | Val Fusion ImbOLL 2.701980 | Val Fusion CCC 0.355560 | Val Audio CCC 0.079207 | 0.98s
Epoch 03/20 | Train Fusion CCC 0.658504 | Train Audio CCC 0.178318 | Val Fusion ImbOLL 2.081773 | Val Fusion CCC 0.240340 | Val Audio CCC 0.146697 | 1.18s
Epoch 04/20 | Train Fusion CCC 0.645635 | Train Audio CCC 0.085594 | Val Fusion ImbOLL 2.353838 | Val Fusion CCC 0.344000 | Val Audio CCC 0.101218 | 1.23s
Epoch 05/20 | Train Fusion CCC 0.666851 | Train Audio CCC 0.142206 | Val Fusion ImbOLL 3.322460 | Val Fusion CCC 0.299699 | Val Audio CCC 0.057493 | 1.22s
Epoch 06/20 | Train Fusion CCC 0.681777 | Train Audio CCC 0.208416 | Val Fusion ImbOLL 1.844741 | Val Fusion CCC 0.199272 | Val Audio CCC 0.076744 | 1.46s
Epoch 07/20 | Train Fusion CCC 0.654741 | Train Audio CCC 0.080973 | Val Fusion ImbOLL 2.400862 | Val Fusion CCC 0.352481 | Val Audio CCC 0.101218 | 1.30s
Epoch 08/20 | Train Fusion CCC 0.700625 | Train Audio CCC 0.018146 | Val Fusion ImbOLL 2.514917 | Val Fusion CCC 0.190873 | Val Audio CCC 0.126379 | 0.95s
Epoch 09/20 | Train Fusion CCC 0.665431 | Train Audio CCC 0.130282 | Val Fusion ImbOLL 2.472495 | Val Fusion CCC 0.239906 | Val Audio CCC 0.076744 | 1.18s
Epoch 10/20 | Train Fusion CCC 0.691896 | Train Audio CCC -0.008186 | Val Fusion ImbOLL 2.193501 | Val Fusion CCC 0.297685 | Val Audio CCC 0.101218 | 0.99s
Epoch 11/20 | Train Fusion CCC 0.732607 | Train Audio CCC -0.007238 | Val Fusion ImbOLL 3.907945 | Val Fusion CCC 0.272205 | Val Audio CCC 0.079207 | 1.04s
Epoch 12/20 | Train Fusion CCC 0.681050 | Train Audio CCC 0.145627 | Val Fusion ImbOLL 2.193750 | Val Fusion CCC 0.444857 | Val Audio CCC 0.076744 | 1.22s
Epoch 13/20 | Train Fusion CCC 0.712765 | Train Audio CCC 0.129243 | Val Fusion ImbOLL 2.266304 | Val Fusion CCC 0.309508 | Val Audio CCC 0.135284 | 0.95s
Epoch 14/20 | Train Fusion CCC 0.679340 | Train Audio CCC 0.135666 | Val Fusion ImbOLL 2.598086 | Val Fusion CCC 0.180810 | Val Audio CCC 0.091177 | 1.15s
Epoch 15/20 | Train Fusion CCC 0.689219 | Train Audio CCC 0.089601 | Val Fusion ImbOLL 2.939688 | Val Fusion CCC 0.180810 | Val Audio CCC 0.171727 | 0.89s
Epoch 16/20 | Train Fusion CCC 0.738969 | Train Audio CCC 0.072309 | Val Fusion ImbOLL 2.741240 | Val Fusion CCC 0.326618 | Val Audio CCC 0.089148 | 1.14s
Epoch 17/20 | Train Fusion CCC 0.720141 | Train Audio CCC 0.102067 | Val Fusion ImbOLL 2.604276 | Val Fusion CCC 0.398343 | Val Audio CCC 0.099528 | 0.86s
Epoch 18/20 | Train Fusion CCC 0.709364 | Train Audio CCC 0.183598 | Val Fusion ImbOLL 3.249849 | Val Fusion CCC 0.180810 | Val Audio CCC 0.076744 | 1.11s
Epoch 19/20 | Train Fusion CCC 0.699923 | Train Audio CCC 0.103135 | Val Fusion ImbOLL 2.885615 | Val Fusion CCC 0.332828 | Val Audio CCC 0.089148 | 1.07s
Epoch 20/20 | Train Fusion CCC 0.710984 | Train Audio CCC 0.186025 | Val Fusion ImbOLL 3.452312 | Val Fusion CCC 0.243102 | Val Audio CCC 0.099528 | 0.96s
====================================================================================================
Audio辅助监督训练完成：Seed=42，Q8
最佳Val Fusion ImbOLL：1.844741，Epoch=6
最佳Val Fusion CCC：0.444857，Epoch=12
最佳Val Audio Aux CCC：0.171727，Epoch=15
====================================================================================================

In [300]:
q8_seed100_audio_aux_result = train_fusion_question_audio_aux(question_index=7, seed=100, lambda_audio_aux=0.1)
q8_seed1234_audio_aux_result = train_fusion_question_audio_aux(question_index=7, seed=1234, lambda_audio_aux=0.1)

文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q8_PHQ_8Moving/seed_100/best_ccc.pt
语音Best Loss： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_100/question_8/best_ccc.pt
文本保存Epoch： 14
语音保存Epoch： 20
文本缺少参数： []
文本多余参数： []
语音缺少参数： []
语音多余参数： []
====================================================================================================
开始Audio辅助监督训练：Seed=100，Q8，PHQ_8Moving
Lambda Audio Aux：0.1
单模态初始化：best_ccc
类别数量： [128, 20, 9, 6]
====================================================================================================
Epoch 01/20 | Train Fusion CCC 0.377254 | Train Audio CCC -0.075053 | Val Fusion ImbOLL 2.757789 | Val Fusion CCC 0.180810 | Val Audio CCC 0.111695 | 1.63s
Epoch 02/20 | Train Fusion CCC 0.636810 | Train Audio CCC 0.007309 | Val Fusion ImbOLL 4.306805 | Val Fusion CCC 0.124419 | Val Audio CCC 0.076744 | 1.21s
Epoch 03/20 | Train Fusion CCC 0.655113 | Train Audio CCC -0.061999 | Val Fusion ImbOLL 3.157558 | Val Fusion CCC 0.198397 | Val Audio CCC 0.079207 | 1.42s
Epoch 04/20 | Train Fusion CCC 0.670604 | Train Audio CCC 0.095040 | Val Fusion ImbOLL 4.154633 | Val Fusion CCC 0.326618 | Val Audio CCC 0.079207 | 1.06s
Epoch 05/20 | Train Fusion CCC 0.687787 | Train Audio CCC 0.090944 | Val Fusion ImbOLL 2.880046 | Val Fusion CCC 0.223072 | Val Audio CCC 0.099528 | 1.19s
Epoch 06/20 | Train Fusion CCC 0.701116 | Train Audio CCC 0.148227 | Val Fusion ImbOLL 4.665145 | Val Fusion CCC 0.326618 | Val Audio CCC 0.000000 | 1.30s
Epoch 07/20 | Train Fusion CCC 0.709954 | Train Audio CCC 0.160144 | Val Fusion ImbOLL 3.205131 | Val Fusion CCC 0.210824 | Val Audio CCC 0.000000 | 1.68s
Epoch 08/20 | Train Fusion CCC 0.706882 | Train Audio CCC 0.070482 | Val Fusion ImbOLL 4.420843 | Val Fusion CCC 0.307812 | Val Audio CCC 0.099528 | 1.24s
Epoch 09/20 | Train Fusion CCC 0.675878 | Train Audio CCC 0.062712 | Val Fusion ImbOLL 3.065625 | Val Fusion CCC 0.102841 | Val Audio CCC 0.101218 | 1.28s
Epoch 10/20 | Train Fusion CCC 0.690807 | Train Audio CCC 0.131568 | Val Fusion ImbOLL 3.965770 | Val Fusion CCC 0.211959 | Val Audio CCC 0.079207 | 1.19s
Epoch 11/20 | Train Fusion CCC 0.688079 | Train Audio CCC 0.087568 | Val Fusion ImbOLL 3.375152 | Val Fusion CCC 0.276907 | Val Audio CCC 0.128254 | 1.17s
Epoch 12/20 | Train Fusion CCC 0.745729 | Train Audio CCC 0.150610 | Val Fusion ImbOLL 3.361043 | Val Fusion CCC 0.307812 | Val Audio CCC 0.111695 | 1.10s
Epoch 13/20 | Train Fusion CCC 0.661488 | Train Audio CCC 0.017071 | Val Fusion ImbOLL 3.100257 | Val Fusion CCC 0.089148 | Val Audio CCC 0.114211 | 1.17s
Epoch 14/20 | Train Fusion CCC 0.726529 | Train Audio CCC 0.159379 | Val Fusion ImbOLL 4.065864 | Val Fusion CCC 0.307812 | Val Audio CCC 0.000000 | 1.22s
Epoch 15/20 | Train Fusion CCC 0.689548 | Train Audio CCC 0.067471 | Val Fusion ImbOLL 3.035563 | Val Fusion CCC 0.256160 | Val Audio CCC 0.111695 | 1.11s
Epoch 16/20 | Train Fusion CCC 0.747401 | Train Audio CCC 0.249870 | Val Fusion ImbOLL 2.649063 | Val Fusion CCC 0.298878 | Val Audio CCC 0.099528 | 1.59s
Epoch 17/20 | Train Fusion CCC 0.696235 | Train Audio CCC 0.160672 | Val Fusion ImbOLL 3.393061 | Val Fusion CCC 0.275446 | Val Audio CCC 0.091177 | 1.17s
Epoch 18/20 | Train Fusion CCC 0.698695 | Train Audio CCC 0.311893 | Val Fusion ImbOLL 4.063747 | Val Fusion CCC 0.207383 | Val Audio CCC 0.000000 | 1.27s
Epoch 19/20 | Train Fusion CCC 0.707807 | Train Audio CCC 0.201341 | Val Fusion ImbOLL 3.140040 | Val Fusion CCC 0.259347 | Val Audio CCC 0.000000 | 1.23s
Epoch 20/20 | Train Fusion CCC 0.679304 | Train Audio CCC 0.001054 | Val Fusion ImbOLL 2.649823 | Val Fusion CCC 0.242426 | Val Audio CCC 0.079207 | 1.71s
====================================================================================================
Audio辅助监督训练完成：Seed=100，Q8
最佳Val Fusion ImbOLL：2.649063，Epoch=16
最佳Val Fusion CCC：0.326618，Epoch=4
最佳Val Audio Aux CCC：0.128254，Epoch=11
====================================================================================================
文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q8_PHQ_8Moving/seed_1234/best_ccc.pt
语音Best Loss： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_1234/question_8/best_ccc.pt
文本保存Epoch： 13
语音保存Epoch： 30
文本缺少参数： []
文本多余参数： []
语音缺少参数： []
语音多余参数： []
====================================================================================================
开始Audio辅助监督训练：Seed=1234，Q8，PHQ_8Moving
Lambda Audio Aux：0.1
单模态初始化：best_ccc
类别数量： [128, 20, 9, 6]
====================================================================================================
Epoch 01/20 | Train Fusion CCC 0.112151 | Train Audio CCC 0.028589 | Val Fusion ImbOLL 2.771195 | Val Fusion CCC -0.008657 | Val Audio CCC 0.076744 | 1.16s
Epoch 02/20 | Train Fusion CCC 0.638928 | Train Audio CCC 0.166299 | Val Fusion ImbOLL 3.603896 | Val Fusion CCC 0.211348 | Val Audio CCC -0.023068 | 1.19s
Epoch 03/20 | Train Fusion CCC 0.642315 | Train Audio CCC 0.061956 | Val Fusion ImbOLL 4.344959 | Val Fusion CCC 0.234365 | Val Audio CCC 0.076744 | 1.62s
Epoch 04/20 | Train Fusion CCC 0.750701 | Train Audio CCC -0.002926 | Val Fusion ImbOLL 3.913491 | Val Fusion CCC 0.190909 | Val Audio CCC 0.101218 | 1.12s
Epoch 05/20 | Train Fusion CCC 0.670152 | Train Audio CCC 0.145189 | Val Fusion ImbOLL 4.916834 | Val Fusion CCC 0.234365 | Val Audio CCC 0.079207 | 1.12s
Epoch 06/20 | Train Fusion CCC 0.722090 | Train Audio CCC 0.135036 | Val Fusion ImbOLL 3.776512 | Val Fusion CCC 0.270809 | Val Audio CCC 0.099528 | 1.21s
Epoch 07/20 | Train Fusion CCC 0.746886 | Train Audio CCC 0.062450 | Val Fusion ImbOLL 5.579012 | Val Fusion CCC 0.278129 | Val Audio CCC 0.101218 | 1.46s
Epoch 08/20 | Train Fusion CCC 0.748245 | Train Audio CCC 0.099518 | Val Fusion ImbOLL 5.560311 | Val Fusion CCC 0.234365 | Val Audio CCC 0.083770 | 1.34s
Epoch 09/20 | Train Fusion CCC 0.719558 | Train Audio CCC 0.082914 | Val Fusion ImbOLL 5.763466 | Val Fusion CCC 0.153889 | Val Audio CCC 0.111695 | 1.42s
Epoch 10/20 | Train Fusion CCC 0.742476 | Train Audio CCC 0.071186 | Val Fusion ImbOLL 4.898304 | Val Fusion CCC 0.159592 | Val Audio CCC 0.000000 | 0.98s
Epoch 11/20 | Train Fusion CCC 0.697684 | Train Audio CCC 0.087934 | Val Fusion ImbOLL 5.951071 | Val Fusion CCC 0.180810 | Val Audio CCC 0.099528 | 1.46s
Epoch 12/20 | Train Fusion CCC 0.735718 | Train Audio CCC 0.125371 | Val Fusion ImbOLL 6.148006 | Val Fusion CCC 0.224084 | Val Audio CCC 0.089148 | 1.13s
Epoch 13/20 | Train Fusion CCC 0.705334 | Train Audio CCC 0.220506 | Val Fusion ImbOLL 7.884068 | Val Fusion CCC 0.246153 | Val Audio CCC 0.099528 | 1.19s
Epoch 14/20 | Train Fusion CCC 0.688865 | Train Audio CCC 0.164774 | Val Fusion ImbOLL 3.573062 | Val Fusion CCC 0.268719 | Val Audio CCC 0.089148 | 1.16s
Epoch 15/20 | Train Fusion CCC 0.694863 | Train Audio CCC 0.191576 | Val Fusion ImbOLL 4.740970 | Val Fusion CCC 0.200083 | Val Audio CCC 0.099528 | 1.17s
Epoch 16/20 | Train Fusion CCC 0.670109 | Train Audio CCC 0.224061 | Val Fusion ImbOLL 3.199568 | Val Fusion CCC 0.138644 | Val Audio CCC 0.088401 | 1.16s
Epoch 17/20 | Train Fusion CCC 0.720650 | Train Audio CCC 0.101703 | Val Fusion ImbOLL 3.750114 | Val Fusion CCC 0.161482 | Val Audio CCC 0.099528 | 1.21s
Epoch 18/20 | Train Fusion CCC 0.794143 | Train Audio CCC 0.078501 | Val Fusion ImbOLL 7.576446 | Val Fusion CCC 0.192893 | Val Audio CCC 0.179163 | 1.07s
Epoch 19/20 | Train Fusion CCC 0.704184 | Train Audio CCC 0.091650 | Val Fusion ImbOLL 3.606908 | Val Fusion CCC 0.268719 | Val Audio CCC 0.099528 | 1.22s
Epoch 20/20 | Train Fusion CCC 0.786102 | Train Audio CCC 0.086776 | Val Fusion ImbOLL 3.665108 | Val Fusion CCC 0.295822 | Val Audio CCC 0.076744 | 0.87s
====================================================================================================
Audio辅助监督训练完成：Seed=1234，Q8
最佳Val Fusion ImbOLL：2.771195，Epoch=1
最佳Val Fusion CCC：0.295822，Epoch=20
最佳Val Audio Aux CCC：0.179163，Epoch=18
====================================================================================================

In [302]:
q8_best_ccc_baselines = {42: 0.3880239725112915, 100: 0.3146892488002777, 1234: 0.29118987917900085}
q8_audio_aux_results = [q8_seed42_audio_aux_result, q8_seed100_audio_aux_result, q8_seed1234_audio_aux_result]
q8_audio_aux_comparison_rows = []
for result in q8_audio_aux_results:
    seed = result["seed"]
    baseline_ccc = q8_best_ccc_baselines[seed]
    audio_aux_fusion_ccc = result["best_val_fusion_ccc"]
    q8_audio_aux_comparison_rows.append({"Seed": seed, "Baseline_CCC": baseline_ccc, "Audio_Aux_Fusion_CCC": audio_aux_fusion_ccc, "CCC_Change": audio_aux_fusion_ccc - baseline_ccc, "Best_Audio_Aux_CCC": result["best_val_audio_aux_ccc"], "Fusion_Epoch": result["best_fusion_ccc_epoch"], "Audio_Aux_Epoch": result["best_audio_aux_ccc_epoch"]})
q8_audio_aux_comparison = pd.DataFrame(q8_audio_aux_comparison_rows)
display(q8_audio_aux_comparison)
print("平均基线CCC：", q8_audio_aux_comparison["Baseline_CCC"].mean())
print("平均Audio辅助Fusion CCC：", q8_audio_aux_comparison["Audio_Aux_Fusion_CCC"].mean())
print("平均CCC变化：", q8_audio_aux_comparison["CCC_Change"].mean())

,Seed,Baseline_CCC,Audio_Aux_Fusion_CCC,CCC_Change,Best_Audio_Aux_CCC,Fusion_Epoch,Audio_Aux_Epoch
0,42,0.388024,0.444857,0.056833,0.171727,12,15
1,100,0.314689,0.326618,0.011929,0.128254,4,11
2,1234,0.291190,0.295822,0.004632,0.179163,20,18

平均基线CCC： 0.3313010334968567
平均Audio辅助Fusion CCC： 0.35576552152633667
平均CCC变化： 0.02446448802947998