In [1]:
from pathlib import Path
import gc
import random
import sys
import time
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader

In [2]:
DATA_DIR = Path("/workspace/E-DAIC/original_data")
SPLIT_DIR = Path("/workspace/E-DAIC/splits")
LABEL_DIR = Path("/workspace/E-DAIC/others")
TRAIN_SPLIT_PATH = SPLIT_DIR / "train_split.csv"
VAL_SPLIT_PATH = SPLIT_DIR / "dev_split.csv"
TEST_SPLIT_PATH = SPLIT_DIR / "test_split.csv"
DETAILED_LABEL_PATH = LABEL_DIR / "Detailed_PHQ8_Labels.csv"

TEXT_CACHE_ROOT = Path("/workspace/E-DAIC/cache/phq8_text_embeddings")
AUDIO_CACHE_DIR = Path("/workspace/E-DAIC/cache/phq8_audio_egemaps/egemaps23_turnmean_100hz_turns120_v1")
VIDEO_CACHE_DIR = Path("/workspace/E-DAIC/cache/phq8_video_resnet/resnet2048_turnmean_turns120_v1")

TEXT_CHECKPOINT_ROOT = Path("/workspace/E-DAIC/checkpoints/phq8_text_paperlike")
AUDIO_CHECKPOINT_ROOT = Path("/workspace/E-DAIC/checkpoints/phq8_audio_paperlike")
VIDEO_CHECKPOINT_ROOT = Path("/workspace/E-DAIC/checkpoints/phq8_video_paperlike")
TAV_CHECKPOINT_ROOT = Path("/workspace/E-DAIC/checkpoints/phq8_text_audio_video_nopostzero")

TAV_CHECKPOINT_ROOT.mkdir(parents=True, exist_ok=True)

In [3]:
PHQ8_QUESTION_COLUMNS = ["PHQ_8NoInterest", "PHQ_8Depressed", "PHQ_8Sleep", "PHQ_8Tired", "PHQ_8Appetite", "PHQ_8Failure", "PHQ_8Concentrating", "PHQ_8Moving"]
MAX_TURNS = 120
TEXT_FEATURE_DIM = 768
AUDIO_FEATURE_DIM = 23
VIDEO_FEATURE_DIM = 2048
ENCODER_OUTPUT_DIM = 100
FUSED_MODALITY_DIM = ENCODER_OUTPUT_DIM * 2
FINAL_FUSION_DIM = FUSED_MODALITY_DIM * 3
NUM_CLASSES = 4
ATTENTION_HEADS = 4
BATCH_SIZE = 10
NUM_EPOCHS = 20
LEARNING_RATE = 5e-4
ADAM_EPSILON = 1e-8
WEIGHT_DECAY = 1e-3
MAX_GRAD_NORM = 1.0
FUSION_DROPOUT = 0.8
MLP_FIRST_DROPOUT = 0.8
MLP_LAST_DROPOUT = 0.5
ALPHA = 1.0
BETA = 0.5
LOSS_EPSILON = 1e-12
SEEDS = [42, 100, 1234]
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

In [4]:
print("Python：", sys.version.split()[0])
print("PyTorch：", torch.__version__)
print("设备：", device)
print("单个编码器输出维度：", ENCODER_OUTPUT_DIM)
print("单个模态融合后维度：", FUSED_MODALITY_DIM)
print("三个模态最终拼接维度：", FINAL_FUSION_DIM)
print("Flatten后维度：", MAX_TURNS * FINAL_FUSION_DIM)
print("Text缓存根目录存在：", TEXT_CACHE_ROOT.exists())
print("Audio缓存目录存在：", AUDIO_CACHE_DIR.exists())
print("Video缓存目录存在：", VIDEO_CACHE_DIR.exists())
print("Text Checkpoint存在：", TEXT_CHECKPOINT_ROOT.exists())
print("Audio Checkpoint存在：", AUDIO_CHECKPOINT_ROOT.exists())
print("Video Checkpoint存在：", VIDEO_CHECKPOINT_ROOT.exists())
print("TAV输出目录：", TAV_CHECKPOINT_ROOT)

Python： 3.12.3
PyTorch： 2.9.0
设备： cuda:0
单个编码器输出维度： 100
单个模态融合后维度： 200
三个模态最终拼接维度： 600
Flatten后维度： 72000
Text缓存根目录存在： True
Audio缓存目录存在： True
Video缓存目录存在： True
Text Checkpoint存在： True
Audio Checkpoint存在： True
Video Checkpoint存在： True
TAV输出目录： /workspace/E-DAIC/checkpoints/phq8_text_audio_video_nopostzero

In [10]:
text_cache_candidates = sorted(TEXT_CACHE_ROOT.rglob("302.pt"))
print("找到的302文本缓存：", text_cache_candidates)
if len(text_cache_candidates) != 1:
    raise RuntimeError(f"预期找到一个302文本缓存，实际找到{len(text_cache_candidates)}个：{text_cache_candidates}")
TEXT_CACHE_DIR = text_cache_candidates[0].parent
print("正式文本缓存目录：", TEXT_CACHE_DIR)

找到的302文本缓存： [PosixPath('/workspace/E-DAIC/cache/phq8_text_embeddings/distilroberta_842eaed4_turns120_v1/302.pt')]
正式文本缓存目录： /workspace/E-DAIC/cache/phq8_text_embeddings/distilroberta_842eaed4_turns120_v1

In [7]:
text_cache_path_302 = TEXT_CACHE_DIR / "302.pt"
audio_cache_path_302 = AUDIO_CACHE_DIR / "302.pt"
video_cache_path_302 = VIDEO_CACHE_DIR / "302.pt"
print("302 Text缓存存在：", text_cache_path_302.exists())
print("302 Audio缓存存在：", audio_cache_path_302.exists())
print("302 Video缓存存在：", video_cache_path_302.exists())
text_cache_path_302 = TEXT_CACHE_DIR / "302.pt"
audio_cache_path_302 = AUDIO_CACHE_DIR / "302.pt"
video_cache_path_302 = VIDEO_CACHE_DIR / "302.pt"
print("302 Text缓存存在：", text_cache_path_302.exists())
print("302 Audio缓存存在：", audio_cache_path_302.exists())
print("302 Video缓存存在：", video_cache_path_302.exists())

302 Text缓存存在： True
302 Audio缓存存在： True
302 Video缓存存在： True
302 Text缓存存在： True
302 Audio缓存存在： True
302 Video缓存存在： True

In [15]:
def get_single_modality_best_loss_paths(question_index,seed):
    question_number=question_index+1
    question_name=PHQ8_QUESTION_COLUMNS[question_index]
    text_checkpoint_path=TEXT_CHECKPOINT_ROOT/f"q{question_number}_{question_name}"/f"seed_{seed}"/"best_loss.pt"
    audio_checkpoint_path=AUDIO_CHECKPOINT_ROOT/f"seed_{seed}"/f"question_{question_number}"/"best_loss.pt"
    video_checkpoint_path=VIDEO_CHECKPOINT_ROOT/f"seed_{seed}"/f"question_{question_number}"/"best_loss.pt"
    return text_checkpoint_path,audio_checkpoint_path,video_checkpoint_path

In [19]:
q1_text_best_loss_path, q1_audio_best_loss_path, q1_video_best_loss_path = get_single_modality_best_loss_paths(question_index=0, seed=42)
print("Q1 Text Best Loss：", q1_text_best_loss_path)
print("Q1 Audio Best Loss：", q1_audio_best_loss_path)
print("Q1 Video Best Loss：", q1_video_best_loss_path)
print("Q1 Text Best Loss存在：", q1_text_best_loss_path.exists())
print("Q1 Audio Best Loss存在：", q1_audio_best_loss_path.exists())
print("Q1 Video Best Loss存在：", q1_video_best_loss_path.exists())

Q1 Text Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q1_PHQ_8NoInterest/seed_42/best_loss.pt
Q1 Audio Best Loss： /workspace/E-DAIC/checkpoints/phq8_audio_paperlike/seed_42/question_1/best_loss.pt
Q1 Video Best Loss： /workspace/E-DAIC/checkpoints/phq8_video_paperlike/seed_42/question_1/best_loss.pt
Q1 Text Best Loss存在： True
Q1 Audio Best Loss存在： True
Q1 Video Best Loss存在： True

In [20]:
text_cache_302 = torch.load(text_cache_path_302, map_location="cpu", weights_only=False)
audio_cache_302 = torch.load(audio_cache_path_302, map_location="cpu", weights_only=False)
video_cache_302 = torch.load(video_cache_path_302, map_location="cpu", weights_only=False)

In [21]:
text_features_302 = text_cache_302["embeddings"].float()
text_mask_302 = text_cache_302["key_padding_mask"].bool()
audio_features_302 = audio_cache_302["audio_features"].float()
audio_mask_302 = audio_cache_302["padding_mask"].bool()
video_features_302 = video_cache_302["video_features"].float()
video_mask_302 = video_cache_302["padding_mask"].bool()

In [22]:
print("Text特征：", text_features_302.shape)
print("Text Mask：", text_mask_302.shape)
print("Audio特征：", audio_features_302.shape)
print("Audio Mask：", audio_mask_302.shape)
print("Video特征：", video_features_302.shape)
print("Video Mask：", video_mask_302.shape)
print("Text真实轮数：", int((~text_mask_302).sum()))
print("Audio真实轮数：", int((~audio_mask_302).sum()))
print("Video真实轮数：", int((~video_mask_302).sum()))
print("Text全部有限：", bool(torch.isfinite(text_features_302).all()))
print("Audio全部有限：", bool(torch.isfinite(audio_features_302).all()))
print("Video全部有限：", bool(torch.isfinite(video_features_302).all()))

Text特征： torch.Size([120, 768])
Text Mask： torch.Size([120])
Audio特征： torch.Size([120, 23])
Audio Mask： torch.Size([120])
Video特征： torch.Size([120, 2048])
Video Mask： torch.Size([120])
Text真实轮数： 99
Audio真实轮数： 98
Video真实轮数： 98
Text全部有限： True
Audio全部有限： True
Video全部有限： True

In [26]:
text_checkpoint_302 = torch.load(q1_text_best_loss_path, map_location="cpu", weights_only=False)
audio_checkpoint_302 = torch.load(q1_audio_best_loss_path, map_location="cpu", weights_only=False)
video_checkpoint_302 = torch.load(q1_video_best_loss_path, map_location="cpu", weights_only=False)
def validate_single_modality_checkpoint(checkpoint, expected_seed, expected_question_index, expected_modality):
    if checkpoint["seed"] != expected_seed:
        raise RuntimeError(f"{expected_modality} Seed错误：{checkpoint['seed']}")
    if checkpoint["question_index"] != expected_question_index:
        raise RuntimeError(f"{expected_modality}题目索引错误：{checkpoint['question_index']}")
    if checkpoint["checkpoint_type"] != "best_loss":
        raise RuntimeError(f"{expected_modality}类型错误：{checkpoint['checkpoint_type']}")
    print(f"{expected_modality} Checkpoint验证通过")
validate_single_modality_checkpoint(text_checkpoint_302, expected_seed=42, expected_question_index=0, expected_modality="Text")
validate_single_modality_checkpoint(audio_checkpoint_302, expected_seed=42, expected_question_index=0, expected_modality="Audio")
validate_single_modality_checkpoint(video_checkpoint_302, expected_seed=42, expected_question_index=0, expected_modality="Video")

Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过

In [27]:
print("Text前10个参数名：", list(text_checkpoint_302["model_state_dict"].keys())[:10])
print("Audio前10个参数名：", list(audio_checkpoint_302["model_state_dict"].keys())[:10])
print("Video前10个参数名：", list(video_checkpoint_302["model_state_dict"].keys())[:10])

Text前10个参数名： ['lstm.weight_ih_l0', 'lstm.weight_hh_l0', 'lstm.bias_ih_l0', 'lstm.bias_hh_l0', 'lstm.weight_ih_l0_reverse', 'lstm.weight_hh_l0_reverse', 'lstm.bias_ih_l0_reverse', 'lstm.bias_hh_l0_reverse', 'attention.in_proj_weight', 'attention.in_proj_bias']
Audio前10个参数名： ['lstm.weight_ih_l0', 'lstm.weight_hh_l0', 'lstm.bias_ih_l0', 'lstm.bias_hh_l0', 'lstm.weight_ih_l0_reverse', 'lstm.weight_hh_l0_reverse', 'lstm.bias_ih_l0_reverse', 'lstm.bias_hh_l0_reverse', 'attention1.in_proj_weight', 'attention1.in_proj_bias']
Video前10个参数名： ['lstm.weight_ih_l0', 'lstm.weight_hh_l0', 'lstm.bias_ih_l0', 'lstm.bias_hh_l0', 'lstm.weight_ih_l0_reverse', 'lstm.weight_hh_l0_reverse', 'lstm.bias_ih_l0_reverse', 'lstm.bias_hh_l0_reverse', 'attention1.in_proj_weight', 'attention1.in_proj_bias']

In [28]:
train_split_df = pd.read_csv(TRAIN_SPLIT_PATH)
val_split_df = pd.read_csv(VAL_SPLIT_PATH)
detailed_label_df = pd.read_csv(DETAILED_LABEL_PATH)
train_metadata_df = train_split_df.merge(detailed_label_df[["Participant_ID"] + PHQ8_QUESTION_COLUMNS], on="Participant_ID", how="left", validate="one_to_one")
val_metadata_df = val_split_df.merge(detailed_label_df[["Participant_ID"] + PHQ8_QUESTION_COLUMNS], on="Participant_ID", how="left", validate="one_to_one")
if train_metadata_df[PHQ8_QUESTION_COLUMNS].isna().any().any():
    raise RuntimeError("训练集存在缺失的题目标签")
if val_metadata_df[PHQ8_QUESTION_COLUMNS].isna().any().any():
    raise RuntimeError("验证集存在缺失的题目标签")
print("训练参与者数量：", len(train_metadata_df))
print("验证参与者数量：", len(val_metadata_df))
print("训练标签形状：", train_metadata_df[PHQ8_QUESTION_COLUMNS].shape)
print("验证标签形状：", val_metadata_df[PHQ8_QUESTION_COLUMNS].shape)

训练参与者数量： 163
验证参与者数量： 55
训练标签形状： (163, 8)
验证标签形状： (55, 8)

In [30]:
def load_text_audio_video_cache(participant_id):
    participant_id = int(participant_id)
    text_cache_path = TEXT_CACHE_DIR / f"{participant_id}.pt"
    audio_cache_path = AUDIO_CACHE_DIR / f"{participant_id}.pt"
    video_cache_path = VIDEO_CACHE_DIR / f"{participant_id}.pt"
    if not text_cache_path.exists():
        raise FileNotFoundError(f"Text缓存不存在：{text_cache_path}")
    if not audio_cache_path.exists():
        raise FileNotFoundError(f"Audio缓存不存在：{audio_cache_path}")
    if not video_cache_path.exists():
        raise FileNotFoundError(f"Video缓存不存在：{video_cache_path}")
    text_cache = torch.load(text_cache_path, map_location="cpu", weights_only=False)
    audio_cache = torch.load(audio_cache_path, map_location="cpu", weights_only=False)
    video_cache = torch.load(video_cache_path, map_location="cpu", weights_only=False)
    text_features = text_cache["embeddings"].float()
    text_mask = text_cache["key_padding_mask"].bool()
    audio_features = audio_cache["audio_features"].float()
    audio_mask = audio_cache["padding_mask"].bool()
    video_features = video_cache["video_features"].float()
    video_mask = video_cache["padding_mask"].bool()
    if text_features.shape != (MAX_TURNS, TEXT_FEATURE_DIM):
        raise RuntimeError(f"参与者{participant_id} Text形状错误：{text_features.shape}")
    if audio_features.shape != (MAX_TURNS, AUDIO_FEATURE_DIM):
        raise RuntimeError(f"参与者{participant_id} Audio形状错误：{audio_features.shape}")
    if video_features.shape != (MAX_TURNS, VIDEO_FEATURE_DIM):
        raise RuntimeError(f"参与者{participant_id} Video形状错误：{video_features.shape}")
    if text_mask.shape != (MAX_TURNS,):
        raise RuntimeError(f"参与者{participant_id} Text Mask错误：{text_mask.shape}")
    if audio_mask.shape != (MAX_TURNS,):
        raise RuntimeError(f"参与者{participant_id} Audio Mask错误：{audio_mask.shape}")
    if video_mask.shape != (MAX_TURNS,):
        raise RuntimeError(f"参与者{participant_id} Video Mask错误：{video_mask.shape}")
    if not torch.isfinite(text_features).all():
        raise RuntimeError(f"参与者{participant_id} Text包含NaN或Inf")
    if not torch.isfinite(audio_features).all():
        raise RuntimeError(f"参与者{participant_id} Audio包含NaN或Inf")
    if not torch.isfinite(video_features).all():
        raise RuntimeError(f"参与者{participant_id} Video包含NaN或Inf")
    return text_features, text_mask, audio_features, audio_mask, video_features, video_mask

In [29]:
class TextAudioVideoPHQ8Dataset(Dataset):
    def __init__(self, metadata_df, split_name):
        super().__init__()
        self.split_name = split_name
        self.metadata_df = metadata_df.reset_index(drop=True).copy()
        self.participant_ids = self.metadata_df["Participant_ID"].astype(int).tolist()
        self.labels = torch.tensor(self.metadata_df[PHQ8_QUESTION_COLUMNS].to_numpy(), dtype=torch.long)
        text_feature_list = []
        text_mask_list = []
        audio_feature_list = []
        audio_mask_list = []
        video_feature_list = []
        video_mask_list = []
        for index, participant_id in enumerate(self.participant_ids):
            text_features, text_mask, audio_features, audio_mask, video_features, video_mask = load_text_audio_video_cache(participant_id)
            text_feature_list.append(text_features)
            text_mask_list.append(text_mask)
            audio_feature_list.append(audio_features)
            audio_mask_list.append(audio_mask)
            video_feature_list.append(video_features)
            video_mask_list.append(video_mask)
            if (index + 1) % 50 == 0 or index + 1 == len(self.participant_ids):
                print(f"{split_name}缓存加载进度：{index + 1}/{len(self.participant_ids)}")
        self.text_features = torch.stack(text_feature_list, dim=0)
        self.text_masks = torch.stack(text_mask_list, dim=0)
        self.audio_features = torch.stack(audio_feature_list, dim=0)
        self.audio_masks = torch.stack(audio_mask_list, dim=0)
        self.video_features = torch.stack(video_feature_list, dim=0)
        self.video_masks = torch.stack(video_mask_list, dim=0)

    def __len__(self):
        return len(self.participant_ids)

    def __getitem__(self, index):
        return self.text_features[index], self.text_masks[index], self.audio_features[index], self.audio_masks[index], self.video_features[index], self.video_masks[index], self.labels[index]

In [31]:
tav_train_dataset = TextAudioVideoPHQ8Dataset(train_metadata_df, split_name="train")
tav_val_dataset = TextAudioVideoPHQ8Dataset(val_metadata_df, split_name="val")
print("训练Text：", tav_train_dataset.text_features.shape)
print("训练Audio：", tav_train_dataset.audio_features.shape)
print("训练Video：", tav_train_dataset.video_features.shape)
print("训练Text Mask：", tav_train_dataset.text_masks.shape)
print("训练Audio Mask：", tav_train_dataset.audio_masks.shape)
print("训练Video Mask：", tav_train_dataset.video_masks.shape)
print("训练Labels：", tav_train_dataset.labels.shape)

train缓存加载进度：50/163
train缓存加载进度：100/163
train缓存加载进度：150/163
train缓存加载进度：163/163
val缓存加载进度：50/55
val缓存加载进度：55/55
训练Text： torch.Size([163, 120, 768])
训练Audio： torch.Size([163, 120, 23])
训练Video： torch.Size([163, 120, 2048])
训练Text Mask： torch.Size([163, 120])
训练Audio Mask： torch.Size([163, 120])
训练Video Mask： torch.Size([163, 120])
训练Labels： torch.Size([163, 8])

In [32]:
def create_tav_dataloaders(seed):
    train_generator = torch.Generator()
    train_generator.manual_seed(seed)
    train_loader = DataLoader(tav_train_dataset, batch_size=BATCH_SIZE, shuffle=True, num_workers=0, drop_last=False, generator=train_generator)
    val_loader = DataLoader(tav_val_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=0, drop_last=False)
    return train_loader, val_loader

In [33]:
tav_train_loader, tav_val_loader = create_tav_dataloaders(seed=42)
batch_text_features, batch_text_masks, batch_audio_features, batch_audio_masks, batch_video_features, batch_video_masks, batch_all_labels = next(iter(tav_train_loader))

In [34]:
print("Text Batch：", batch_text_features.shape)
print("Text Mask：", batch_text_masks.shape)
print("Audio Batch：", batch_audio_features.shape)
print("Audio Mask：", batch_audio_masks.shape)
print("Video Batch：", batch_video_features.shape)
print("Video Mask：", batch_video_masks.shape)
print("Labels：", batch_all_labels.shape)
print("Q1标签：", batch_all_labels[:, 0])

Text Batch： torch.Size([10, 120, 768])
Text Mask： torch.Size([10, 120])
Audio Batch： torch.Size([10, 120, 23])
Audio Mask： torch.Size([10, 120])
Video Batch： torch.Size([10, 120, 2048])
Video Mask： torch.Size([10, 120])
Labels： torch.Size([10, 8])
Q1标签： tensor([1, 0, 1, 0, 0, 0, 0, 0, 0, 1])

In [35]:
def set_seed(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed(seed)
        torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

In [36]:
class PretrainedTextEncoder(nn.Module):
    def __init__(self):
        super().__init__()
        self.lstm = nn.LSTM(input_size=TEXT_FEATURE_DIM, hidden_size=50, batch_first=True, bidirectional=True)
        self.attention = nn.MultiheadAttention(embed_dim=ENCODER_OUTPUT_DIM, num_heads=ATTENTION_HEADS, dropout=0.5, batch_first=True)

    def forward(self, text_features, text_padding_mask):
        lstm_output, _ = self.lstm(text_features)
        text_encoding, _ = self.attention(lstm_output, lstm_output, lstm_output, key_padding_mask=text_padding_mask, need_weights=False)
        return text_encoding

In [37]:
class PretrainedAudioEncoder(nn.Module):
    def __init__(self):
        super().__init__()
        self.lstm = nn.LSTM(input_size=AUDIO_FEATURE_DIM, hidden_size=50, batch_first=True, bidirectional=True)
        self.attention1 = nn.MultiheadAttention(embed_dim=ENCODER_OUTPUT_DIM, num_heads=ATTENTION_HEADS, dropout=0.2, batch_first=True)
        self.attention2 = nn.MultiheadAttention(embed_dim=ENCODER_OUTPUT_DIM, num_heads=ATTENTION_HEADS, dropout=0.2, batch_first=True)

    def forward(self, audio_features, audio_padding_mask):
        lstm_output, _ = self.lstm(audio_features)
        attention1_output, _ = self.attention1(lstm_output, lstm_output, lstm_output, key_padding_mask=audio_padding_mask, need_weights=False)
        audio_encoding, _ = self.attention2(attention1_output, attention1_output, attention1_output, key_padding_mask=audio_padding_mask, need_weights=False)
        return audio_encoding

In [38]:
class PretrainedVideoEncoder(nn.Module):
    def __init__(self):
        super().__init__()
        self.lstm = nn.LSTM(input_size=VIDEO_FEATURE_DIM, hidden_size=50, batch_first=True, bidirectional=True)
        self.attention1 = nn.MultiheadAttention(embed_dim=ENCODER_OUTPUT_DIM, num_heads=ATTENTION_HEADS, dropout=0.2, batch_first=True)
        self.attention2 = nn.MultiheadAttention(embed_dim=ENCODER_OUTPUT_DIM, num_heads=ATTENTION_HEADS, dropout=0.2, batch_first=True)

    def forward(self, video_features, video_padding_mask):
        lstm_output, _ = self.lstm(video_features)
        attention1_output, _ = self.attention1(lstm_output, lstm_output, lstm_output, key_padding_mask=video_padding_mask, need_weights=False)
        video_encoding, _ = self.attention2(attention1_output, attention1_output, attention1_output, key_padding_mask=video_padding_mask, need_weights=False)
        return video_encoding

In [39]:
def extract_state_dict_by_prefixes(full_state_dict, prefixes):
    selected_state_dict = {}
    for parameter_name, parameter_value in full_state_dict.items():
        if any(parameter_name.startswith(prefix) for prefix in prefixes):
            selected_state_dict[parameter_name] = parameter_value
    return selected_state_dict

In [40]:
def load_pretrained_tav_encoders(question_index, seed):
    text_checkpoint_path, audio_checkpoint_path, video_checkpoint_path = get_single_modality_best_loss_paths(question_index, seed)
    text_checkpoint = torch.load(text_checkpoint_path, map_location="cpu", weights_only=False)
    audio_checkpoint = torch.load(audio_checkpoint_path, map_location="cpu", weights_only=False)
    video_checkpoint = torch.load(video_checkpoint_path, map_location="cpu", weights_only=False)
    validate_single_modality_checkpoint(text_checkpoint, seed, question_index, "Text")
    validate_single_modality_checkpoint(audio_checkpoint, seed, question_index, "Audio")
    validate_single_modality_checkpoint(video_checkpoint, seed, question_index, "Video")
    text_encoder = PretrainedTextEncoder()
    audio_encoder = PretrainedAudioEncoder()
    video_encoder = PretrainedVideoEncoder()
    text_encoder_state = extract_state_dict_by_prefixes(text_checkpoint["model_state_dict"], prefixes=("lstm.", "attention."))
    audio_encoder_state = extract_state_dict_by_prefixes(audio_checkpoint["model_state_dict"], prefixes=("lstm.", "attention1.", "attention2."))
    video_encoder_state = extract_state_dict_by_prefixes(video_checkpoint["model_state_dict"], prefixes=("lstm.", "attention1.", "attention2."))
    text_load_result = text_encoder.load_state_dict(text_encoder_state, strict=True)
    audio_load_result = audio_encoder.load_state_dict(audio_encoder_state, strict=True)
    video_load_result = video_encoder.load_state_dict(video_encoder_state, strict=True)
    print("Text保存Epoch：", text_checkpoint["epoch"])
    print("Audio保存Epoch：", audio_checkpoint["epoch"])
    print("Video保存Epoch：", video_checkpoint["epoch"])
    print("Text缺少参数：", text_load_result.missing_keys)
    print("Text多余参数：", text_load_result.unexpected_keys)
    print("Audio缺少参数：", audio_load_result.missing_keys)
    print("Audio多余参数：", audio_load_result.unexpected_keys)
    print("Video缺少参数：", video_load_result.missing_keys)
    print("Video多余参数：", video_load_result.unexpected_keys)
    return text_encoder, audio_encoder, video_encoder, text_checkpoint, audio_checkpoint, video_checkpoint, text_checkpoint_path, audio_checkpoint_path, video_checkpoint_path

In [41]:
set_seed(42)
q1_text_encoder, q1_audio_encoder, q1_video_encoder, q1_text_checkpoint, q1_audio_checkpoint, q1_video_checkpoint, q1_text_checkpoint_path, q1_audio_checkpoint_path, q1_video_checkpoint_path = load_pretrained_tav_encoders(question_index=0, seed=42)

Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 13
Audio保存Epoch： 10
Video保存Epoch： 2
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []

In [42]:
q1_text_encoder = q1_text_encoder.to(device)
q1_audio_encoder = q1_audio_encoder.to(device)
q1_video_encoder = q1_video_encoder.to(device)
q1_text_encoder.eval()
q1_audio_encoder.eval()
q1_video_encoder.eval()

PretrainedVideoEncoder(
  (lstm): LSTM(2048, 50, batch_first=True, bidirectional=True)
  (attention1): MultiheadAttention(
    (out_proj): NonDynamicallyQuantizableLinear(in_features=100, out_features=100, bias=True)
  )
  (attention2): MultiheadAttention(
    (out_proj): NonDynamicallyQuantizableLinear(in_features=100, out_features=100, bias=True)
  )
)

In [43]:
with torch.no_grad():
    diagnostic_text_encoding = q1_text_encoder(batch_text_features.to(device), batch_text_masks.to(device))
    diagnostic_audio_encoding = q1_audio_encoder(batch_audio_features.to(device), batch_audio_masks.to(device))
    diagnostic_video_encoding = q1_video_encoder(batch_video_features.to(device), batch_video_masks.to(device))

In [44]:
print("Text编码：", diagnostic_text_encoding.shape)
print("Audio编码：", diagnostic_audio_encoding.shape)
print("Video编码：", diagnostic_video_encoding.shape)
print("Text编码全部有限：", bool(torch.isfinite(diagnostic_text_encoding).all()))
print("Audio编码全部有限：", bool(torch.isfinite(diagnostic_audio_encoding).all()))
print("Video编码全部有限：", bool(torch.isfinite(diagnostic_video_encoding).all()))
print("Text编码器参数：", f"{sum(parameter.numel() for parameter in q1_text_encoder.parameters()):,}")
print("Audio编码器参数：", f"{sum(parameter.numel() for parameter in q1_audio_encoder.parameters()):,}")
print("Video编码器参数：", f"{sum(parameter.numel() for parameter in q1_video_encoder.parameters()):,}")

Text编码： torch.Size([10, 120, 100])
Audio编码： torch.Size([10, 120, 100])
Video编码： torch.Size([10, 120, 100])
Text编码全部有限： True
Audio编码全部有限： True
Video编码全部有限： True
Text编码器参数： 368,400
Audio编码器参数： 110,800
Video编码器参数： 920,800

In [53]:
class TextAudioVideoQuestMF(nn.Module):
    def __init__(self, text_encoder, audio_encoder, video_encoder):
        super().__init__()
        self.text_encoder = text_encoder
        self.audio_encoder = audio_encoder
        self.video_encoder = video_encoder
        self.audio_to_text_cross_attention = nn.MultiheadAttention(embed_dim=ENCODER_OUTPUT_DIM, num_heads=ATTENTION_HEADS, dropout=FUSION_DROPOUT, batch_first=True)
        self.video_to_text_cross_attention = nn.MultiheadAttention(embed_dim=ENCODER_OUTPUT_DIM, num_heads=ATTENTION_HEADS, dropout=FUSION_DROPOUT, batch_first=True)
        self.text_to_audio_cross_attention = nn.MultiheadAttention(embed_dim=ENCODER_OUTPUT_DIM, num_heads=ATTENTION_HEADS, dropout=FUSION_DROPOUT, batch_first=True)
        self.video_to_audio_cross_attention = nn.MultiheadAttention(embed_dim=ENCODER_OUTPUT_DIM, num_heads=ATTENTION_HEADS, dropout=FUSION_DROPOUT, batch_first=True)
        self.text_to_video_cross_attention = nn.MultiheadAttention(embed_dim=ENCODER_OUTPUT_DIM, num_heads=ATTENTION_HEADS, dropout=FUSION_DROPOUT, batch_first=True)
        self.audio_to_video_cross_attention = nn.MultiheadAttention(embed_dim=ENCODER_OUTPUT_DIM, num_heads=ATTENTION_HEADS, dropout=FUSION_DROPOUT, batch_first=True)
        self.text_self_attention = nn.MultiheadAttention(embed_dim=FUSED_MODALITY_DIM, num_heads=ATTENTION_HEADS, dropout=FUSION_DROPOUT, batch_first=True)
        self.audio_self_attention = nn.MultiheadAttention(embed_dim=FUSED_MODALITY_DIM, num_heads=ATTENTION_HEADS, dropout=FUSION_DROPOUT, batch_first=True)
        self.video_self_attention = nn.MultiheadAttention(embed_dim=FUSED_MODALITY_DIM, num_heads=ATTENTION_HEADS, dropout=FUSION_DROPOUT, batch_first=True)
        self.mlp = nn.Sequential(nn.Flatten(), nn.Dropout(MLP_FIRST_DROPOUT), nn.Linear(MAX_TURNS * FINAL_FUSION_DIM, 256), nn.ReLU(), nn.Dropout(MLP_LAST_DROPOUT), nn.Linear(256, NUM_CLASSES))
        for parameter in self.text_encoder.parameters():
            parameter.requires_grad = False
        self.text_encoder.eval()

    def train(self, mode=True):
        super().train(mode)
        self.text_encoder.eval()
        return self
    def forward(self, text_features, text_padding_mask, audio_features, audio_padding_mask, video_features, video_padding_mask, return_intermediates=False):
        text_encoding = self.text_encoder(text_features, text_padding_mask)
        audio_encoding = self.audio_encoder(audio_features, audio_padding_mask)
        video_encoding = self.video_encoder(video_features, video_padding_mask)
        audio_to_text, _ = self.audio_to_text_cross_attention(text_encoding, audio_encoding, audio_encoding, key_padding_mask=audio_padding_mask, need_weights=False)
        video_to_text, _ = self.video_to_text_cross_attention(text_encoding, video_encoding, video_encoding, key_padding_mask=video_padding_mask, need_weights=False)
        text_cross_fused = torch.cat((audio_to_text, video_to_text), dim=2)
        audio_to_text, _ = self.audio_to_text_cross_attention(text_encoding, audio_encoding, audio_encoding, key_padding_mask=audio_padding_mask, need_weights=False)
        video_to_text, _ = self.video_to_text_cross_attention(text_encoding, video_encoding, video_encoding, key_padding_mask=video_padding_mask, need_weights=False)
        text_cross_fused = torch.cat((audio_to_text, video_to_text), dim=2)
        text_to_audio, _ = self.text_to_audio_cross_attention(audio_encoding, text_encoding, text_encoding, key_padding_mask=text_padding_mask, need_weights=False)
        video_to_audio, _ = self.video_to_audio_cross_attention(audio_encoding, video_encoding, video_encoding, key_padding_mask=video_padding_mask, need_weights=False)
        audio_cross_fused = torch.cat((text_to_audio, video_to_audio), dim=2)
        text_to_video, _ = self.text_to_video_cross_attention(video_encoding, text_encoding, text_encoding, key_padding_mask=text_padding_mask, need_weights=False)
        audio_to_video, _ = self.audio_to_video_cross_attention(video_encoding, audio_encoding, audio_encoding, key_padding_mask=audio_padding_mask, need_weights=False)
        video_cross_fused = torch.cat((text_to_video, audio_to_video), dim=2)
        text_fused_encoding, _ = self.text_self_attention(text_cross_fused, text_cross_fused, text_cross_fused, key_padding_mask=text_padding_mask, need_weights=False)
        audio_fused_encoding, _ = self.audio_self_attention(audio_cross_fused, audio_cross_fused, audio_cross_fused, key_padding_mask=audio_padding_mask, need_weights=False)
        video_fused_encoding, _ = self.video_self_attention(video_cross_fused, video_cross_fused, video_cross_fused, key_padding_mask=video_padding_mask, need_weights=False)
        final_fused_encoding = torch.cat((text_fused_encoding, audio_fused_encoding, video_fused_encoding), dim=2)
        logits = self.mlp(final_fused_encoding)
        if return_intermediates:
            intermediates = {}
            intermediates["text_encoding"] = text_encoding
            intermediates["audio_encoding"] = audio_encoding
            intermediates["video_encoding"] = video_encoding
            intermediates["audio_to_text"] = audio_to_text
            intermediates["video_to_text"] = video_to_text
            intermediates["text_to_audio"] = text_to_audio
            intermediates["video_to_audio"] = video_to_audio
            intermediates["text_to_video"] = text_to_video
            intermediates["audio_to_video"] = audio_to_video
            intermediates["text_cross_fused"] = text_cross_fused
            intermediates["audio_cross_fused"] = audio_cross_fused
            intermediates["video_cross_fused"] = video_cross_fused
            intermediates["text_fused_encoding"] = text_fused_encoding
            intermediates["audio_fused_encoding"] = audio_fused_encoding
            intermediates["video_fused_encoding"] = video_fused_encoding
            intermediates["final_fused_encoding"] = final_fused_encoding
            return logits, intermediates
        return logits

In [54]:
set_seed(42)
q1_text_encoder, q1_audio_encoder, q1_video_encoder, q1_text_checkpoint, q1_audio_checkpoint, q1_video_checkpoint, q1_text_checkpoint_path, q1_audio_checkpoint_path, q1_video_checkpoint_path = load_pretrained_tav_encoders(question_index=0, seed=42)
q1_tav_model = TextAudioVideoQuestMF(q1_text_encoder, q1_audio_encoder, q1_video_encoder).to(device)
q1_tav_model.train()
text_trainable_parameters = sum(parameter.numel() for parameter in q1_tav_model.text_encoder.parameters() if parameter.requires_grad)
audio_trainable_parameters = sum(parameter.numel() for parameter in q1_tav_model.audio_encoder.parameters() if parameter.requires_grad)
video_trainable_parameters = sum(parameter.numel() for parameter in q1_tav_model.video_encoder.parameters() if parameter.requires_grad)
total_trainable_parameters = sum(parameter.numel() for parameter in q1_tav_model.parameters() if parameter.requires_grad)
print("Text可训练参数：", f"{text_trainable_parameters:,}")
print("Audio可训练参数：", f"{audio_trainable_parameters:,}")
print("Video可训练参数：", f"{video_trainable_parameters:,}")
print("模型总可训练参数：", f"{total_trainable_parameters:,}")
print("Text训练模式：", q1_tav_model.text_encoder.training)
print("Audio训练模式：", q1_tav_model.audio_encoder.training)
print("Video训练模式：", q1_tav_model.video_encoder.training)

Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 13
Audio保存Epoch： 10
Video保存Epoch： 2
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
Text可训练参数： 0
Audio可训练参数： 110,800
Video可训练参数： 920,800
模型总可训练参数： 20,189,684
Text训练模式： False
Audio训练模式： True
Video训练模式： True

In [55]:
q1_tav_model.eval()
with torch.no_grad():
    q1_tav_logits, q1_tav_intermediates = q1_tav_model(batch_text_features.to(device), batch_text_masks.to(device), batch_audio_features.to(device), batch_audio_masks.to(device), batch_video_features.to(device), batch_video_masks.to(device), return_intermediates=True)
print("Text编码：", q1_tav_intermediates["text_encoding"].shape)
print("Audio编码：", q1_tav_intermediates["audio_encoding"].shape)
print("Video编码：", q1_tav_intermediates["video_encoding"].shape)
print("Text Cross融合：", q1_tav_intermediates["text_cross_fused"].shape)
print("Audio Cross融合：", q1_tav_intermediates["audio_cross_fused"].shape)
print("Video Cross融合：", q1_tav_intermediates["video_cross_fused"].shape)
print("最终融合：", q1_tav_intermediates["final_fused_encoding"].shape)
print("最终Logits：", q1_tav_logits.shape)
print("Logits全部有限：", bool(torch.isfinite(q1_tav_logits).all()))

Text编码： torch.Size([10, 120, 100])
Audio编码： torch.Size([10, 120, 100])
Video编码： torch.Size([10, 120, 100])
Text Cross融合： torch.Size([10, 120, 200])
Audio Cross融合： torch.Size([10, 120, 200])
Video Cross融合： torch.Size([10, 120, 200])
最终融合： torch.Size([10, 120, 600])
最终Logits： torch.Size([10, 4])
Logits全部有限： True

In [56]:
class ImbOLLLoss(nn.Module):
    def __init__(self, class_weights, alpha=1.0, epsilon=1e-12):
        super().__init__()
        self.register_buffer("class_weights", class_weights.float())
        self.alpha = alpha
        self.epsilon = epsilon

    def forward(self, logits, targets):
        probabilities = torch.softmax(logits, dim=1)
        class_indices = torch.arange(logits.shape[1], device=logits.device).view(1, -1)
        ordinal_distances = torch.abs(targets.view(-1, 1) - class_indices).float()
        sample_weights = self.class_weights[targets].view(-1, 1)
        weighted_distances = torch.pow(sample_weights * ordinal_distances, self.alpha)
        losses = -torch.log(1.0 - probabilities + self.epsilon) * weighted_distances
        return losses.sum(dim=1).mean()

In [57]:
def calculate_gradient_statistics(parameters):
    squared_gradient_sum = 0.0
    gradient_tensor_count = 0
    for parameter in parameters:
        if parameter.grad is not None:
            squared_gradient_sum += parameter.grad.detach().pow(2).sum().item()
            gradient_tensor_count += 1
    return squared_gradient_sum ** 0.5, gradient_tensor_count

In [58]:
q1_train_labels = tav_train_dataset.labels[:, 0]
q1_class_counts = torch.bincount(q1_train_labels, minlength=NUM_CLASSES)
q1_class_weights = torch.pow(len(q1_train_labels) / q1_class_counts.float(), BETA)
q1_criterion = ImbOLLLoss(q1_class_weights, alpha=ALPHA).to(device)
q1_optimizer = torch.optim.AdamW((parameter for parameter in q1_tav_model.parameters() if parameter.requires_grad), lr=LEARNING_RATE, eps=ADAM_EPSILON, weight_decay=WEIGHT_DECAY)
q1_tav_model.train()
q1_optimizer.zero_grad(set_to_none=True)
diagnostic_logits = q1_tav_model(batch_text_features.to(device), batch_text_masks.to(device), batch_audio_features.to(device), batch_audio_masks.to(device), batch_video_features.to(device), batch_video_masks.to(device))
diagnostic_targets = batch_all_labels[:, 0].to(device)
diagnostic_loss = q1_criterion(diagnostic_logits, diagnostic_targets)
diagnostic_loss.backward()

In [59]:
text_gradient_norm, text_gradient_count = calculate_gradient_statistics(q1_tav_model.text_encoder.parameters())
audio_gradient_norm, audio_gradient_count = calculate_gradient_statistics(q1_tav_model.audio_encoder.parameters())
video_gradient_norm, video_gradient_count = calculate_gradient_statistics(q1_tav_model.video_encoder.parameters())
fusion_parameters = [parameter for name, parameter in q1_tav_model.named_parameters() if not name.startswith(("text_encoder.", "audio_encoder.", "video_encoder."))]
fusion_gradient_norm, fusion_gradient_count = calculate_gradient_statistics(fusion_parameters)
print("ImbOLL：", diagnostic_loss.item())
print("Text梯度：", text_gradient_norm, "张量数：", text_gradient_count)
print("Audio梯度：", audio_gradient_norm, "张量数：", audio_gradient_count)
print("Video梯度：", video_gradient_norm, "张量数：", video_gradient_count)
print("融合层梯度：", fusion_gradient_norm, "张量数：", fusion_gradient_count)

ImbOLL： 2.2597131729125977
Text梯度： 0.0 张量数： 0
Audio梯度： 0.10996090520211597 张量数： 16
Video梯度： 0.033924439019880244 张量数： 16
融合层梯度： 1.2980884886728683 张量数： 40

In [60]:
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score

In [61]:
def calculate_ccc(predictions, targets, epsilon=1e-12):
    predictions = predictions.double()
    targets = targets.double()
    prediction_mean = predictions.mean()
    target_mean = targets.mean()
    covariance = ((predictions - prediction_mean) * (targets - target_mean)).mean()
    prediction_variance = ((predictions - prediction_mean) ** 2).mean()
    target_variance = ((targets - target_mean) ** 2).mean()
    ccc = (2.0 * covariance) / (prediction_variance + target_variance + (prediction_mean - target_mean) ** 2 + epsilon)
    return float(ccc.item())

In [62]:
def calculate_question_metrics(predictions, targets):
    predictions = predictions.long()
    targets = targets.long()
    predictions_numpy = predictions.numpy()
    targets_numpy = targets.numpy()
    accuracy = accuracy_score(targets_numpy, predictions_numpy)
    micro_f1 = f1_score(targets_numpy, predictions_numpy, labels=list(range(NUM_CLASSES)), average="micro", zero_division=0)
    macro_f1 = f1_score(targets_numpy, predictions_numpy, labels=list(range(NUM_CLASSES)), average="macro", zero_division=0)
    weighted_f1 = f1_score(targets_numpy, predictions_numpy, labels=list(range(NUM_CLASSES)), average="weighted", zero_division=0)
    matrix = confusion_matrix(targets_numpy, predictions_numpy, labels=list(range(NUM_CLASSES)))
    rmse = float(torch.sqrt(torch.mean((predictions.float() - targets.float()) ** 2)).item())
    mae = float(torch.mean(torch.abs(predictions.float() - targets.float())).item())
    ccc = calculate_ccc(predictions, targets)
    return {"accuracy": accuracy, "micro_f1": micro_f1, "macro_f1": macro_f1, "weighted_f1": weighted_f1, "ccc": ccc, "rmse": rmse, "mae": mae, "confusion_matrix": torch.tensor(matrix)}

In [63]:
def run_tav_epoch(model, data_loader, question_index, criterion, optimizer=None):
    is_training = optimizer is not None
    if is_training:
        model.train()
    else:
        model.eval()
    total_loss = 0.0
    total_samples = 0
    prediction_list = []
    target_list = []
    for text_features, text_masks, audio_features, audio_masks, video_features, video_masks, all_labels in data_loader:
        text_features = text_features.to(device)
        text_masks = text_masks.to(device)
        audio_features = audio_features.to(device)
        audio_masks = audio_masks.to(device)
        video_features = video_features.to(device)
        video_masks = video_masks.to(device)
        targets = all_labels[:, question_index].to(device)
        if is_training:
            optimizer.zero_grad(set_to_none=True)
        with torch.set_grad_enabled(is_training):
            logits = model(text_features, text_masks, audio_features, audio_masks, video_features, video_masks)
            loss = criterion(logits, targets)
            if is_training:
                loss.backward()
                torch.nn.utils.clip_grad_norm_(model.parameters(), MAX_GRAD_NORM)
                optimizer.step()
        batch_size = targets.shape[0]
        total_loss += loss.item() * batch_size
        total_samples += batch_size
        prediction_list.append(logits.argmax(dim=1).detach().cpu())
        target_list.append(targets.detach().cpu())
    predictions = torch.cat(prediction_list)
    targets = torch.cat(target_list)
    metrics = calculate_question_metrics(predictions, targets)
    metrics["loss"] = total_loss / total_samples
    metrics["predictions"] = predictions
    metrics["targets"] = targets
    return metrics

In [64]:
del q1_tav_model
gc.collect()
if torch.cuda.is_available():
    torch.cuda.empty_cache()

In [65]:
set_seed(42)
tav_train_loader, tav_val_loader = create_tav_dataloaders(seed=42)
q1_text_encoder, q1_audio_encoder, q1_video_encoder, q1_text_checkpoint, q1_audio_checkpoint, q1_video_checkpoint, q1_text_checkpoint_path, q1_audio_checkpoint_path, q1_video_checkpoint_path = load_pretrained_tav_encoders(question_index=0, seed=42)
q1_tav_model = TextAudioVideoQuestMF(q1_text_encoder, q1_audio_encoder, q1_video_encoder).to(device)
q1_train_labels = tav_train_dataset.labels[:, 0]
q1_class_counts = torch.bincount(q1_train_labels, minlength=NUM_CLASSES)
q1_class_weights = torch.pow(len(q1_train_labels) / q1_class_counts.float(), BETA)
q1_criterion = ImbOLLLoss(q1_class_weights, alpha=ALPHA).to(device)
q1_optimizer = torch.optim.AdamW((parameter for parameter in q1_tav_model.parameters() if parameter.requires_grad), lr=LEARNING_RATE, eps=ADAM_EPSILON, weight_decay=WEIGHT_DECAY)

Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 13
Audio保存Epoch： 10
Video保存Epoch： 2
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []

In [66]:
q1_train_metrics = run_tav_epoch(q1_tav_model, tav_train_loader, question_index=0, criterion=q1_criterion, optimizer=q1_optimizer)
q1_val_metrics = run_tav_epoch(q1_tav_model, tav_val_loader, question_index=0, criterion=q1_criterion)

In [67]:
print(f"Train Loss：{q1_train_metrics['loss']:.6f}")
print(f"Train CCC：{q1_train_metrics['ccc']:.6f}")
print(f"Train Accuracy：{q1_train_metrics['accuracy']:.6f}")
print(f"Val Loss：{q1_val_metrics['loss']:.6f}")
print(f"Val CCC：{q1_val_metrics['ccc']:.6f}")
print(f"Val Accuracy：{q1_val_metrics['accuracy']:.6f}")
print(f"Val RMSE：{q1_val_metrics['rmse']:.6f}")
print(f"Val MAE：{q1_val_metrics['mae']:.6f}")
print("Val混淆矩阵：")
print(q1_val_metrics["confusion_matrix"])

Train Loss：2.006856
Train CCC：0.408225
Train Accuracy：0.503067
Val Loss：2.558830
Val CCC：0.302995
Val Accuracy：0.418182
Val RMSE：1.095445
Val MAE：0.763636
Val混淆矩阵：
tensor([[19,  1,  5,  0],
        [ 8,  1, 13,  0],
        [ 1,  0,  3,  0],
        [ 2,  0,  2,  0]])

In [68]:
def compact_metrics(metrics):
    return {"loss": float(metrics["loss"]), "accuracy": float(metrics["accuracy"]), "micro_f1": float(metrics["micro_f1"]), "macro_f1": float(metrics["macro_f1"]), "weighted_f1": float(metrics["weighted_f1"]), "ccc": float(metrics["ccc"]), "rmse": float(metrics["rmse"]), "mae": float(metrics["mae"]), "confusion_matrix": metrics["confusion_matrix"].tolist()}

In [69]:
def save_tav_checkpoint(path, checkpoint_type, epoch, question_index, seed, model, optimizer, train_metrics, val_metrics, class_counts, class_weights, best_val_loss, best_val_ccc, best_loss_epoch, best_ccc_epoch, text_checkpoint_path, audio_checkpoint_path, video_checkpoint_path):
    checkpoint = {}
    checkpoint["checkpoint_type"] = checkpoint_type
    checkpoint["epoch"] = epoch
    checkpoint["question_index"] = question_index
    checkpoint["question_number"] = question_index + 1
    checkpoint["question_name"] = PHQ8_QUESTION_COLUMNS[question_index]
    checkpoint["seed"] = seed
    checkpoint["model_state_dict"] = model.state_dict()
    checkpoint["optimizer_state_dict"] = optimizer.state_dict()
    checkpoint["train_metrics"] = compact_metrics(train_metrics)
    checkpoint["val_metrics"] = compact_metrics(val_metrics)
    checkpoint["class_counts"] = class_counts.tolist()
    checkpoint["class_weights"] = class_weights.tolist()
    checkpoint["best_val_loss"] = float(best_val_loss)
    checkpoint["best_val_ccc"] = float(best_val_ccc)
    checkpoint["best_loss_epoch"] = int(best_loss_epoch)
    checkpoint["best_ccc_epoch"] = int(best_ccc_epoch)
    checkpoint["text_pretrained_checkpoint"] = str(text_checkpoint_path)
    checkpoint["audio_pretrained_checkpoint"] = str(audio_checkpoint_path)
    checkpoint["video_pretrained_checkpoint"] = str(video_checkpoint_path)
    checkpoint["fusion_variant"] = "three_modality_nopostzero"
    checkpoint["config"] = {"max_turns": MAX_TURNS, "text_feature_dim": TEXT_FEATURE_DIM, "audio_feature_dim": AUDIO_FEATURE_DIM, "video_feature_dim": VIDEO_FEATURE_DIM, "encoder_output_dim": ENCODER_OUTPUT_DIM, "per_target_fusion_dim": FUSED_MODALITY_DIM, "final_fusion_dim": FINAL_FUSION_DIM, "attention_heads": ATTENTION_HEADS, "fusion_dropout": FUSION_DROPOUT, "batch_size": BATCH_SIZE, "num_epochs": NUM_EPOCHS, "learning_rate": LEARNING_RATE, "weight_decay": WEIGHT_DECAY, "alpha": ALPHA, "beta": BETA, "text_frozen": True, "postzero": False}
    torch.save(checkpoint, path)

In [70]:
def train_tav_question(seed, question_index):
    set_seed(seed)
    train_loader, val_loader = create_tav_dataloaders(seed)
    text_encoder, audio_encoder, video_encoder, text_checkpoint, audio_checkpoint, video_checkpoint, text_checkpoint_path, audio_checkpoint_path, video_checkpoint_path = load_pretrained_tav_encoders(question_index, seed)
    model = TextAudioVideoQuestMF(text_encoder, audio_encoder, video_encoder).to(device)
    train_labels = tav_train_dataset.labels[:, question_index]
    class_counts = torch.bincount(train_labels, minlength=NUM_CLASSES)
    class_weights = torch.pow(len(train_labels) / class_counts.float(), BETA)
    criterion = ImbOLLLoss(class_weights, alpha=ALPHA).to(device)
    optimizer = torch.optim.AdamW((parameter for parameter in model.parameters() if parameter.requires_grad), lr=LEARNING_RATE, eps=ADAM_EPSILON, weight_decay=WEIGHT_DECAY)
    checkpoint_dir = TAV_CHECKPOINT_ROOT / f"seed_{seed}" / f"question_{question_index + 1}"
    checkpoint_dir.mkdir(parents=True, exist_ok=True)
    best_loss_path = checkpoint_dir / "best_loss.pt"
    best_ccc_path = checkpoint_dir / "best_ccc.pt"
    last_path = checkpoint_dir / "last.pt"
    history_path = checkpoint_dir / "history.csv"
    best_val_loss = float("inf")
    best_val_ccc = float("-inf")
    best_loss_epoch = -1
    best_ccc_epoch = -1
    history_rows = []
    print("=" * 100)
    print(f"开始训练T+A+V：Seed={seed}，Q{question_index + 1}，{PHQ8_QUESTION_COLUMNS[question_index]}")
    print("类别数量：", class_counts.tolist())
    print("=" * 100)
    for epoch in range(1, NUM_EPOCHS + 1):
        epoch_start_time = time.perf_counter()
        train_metrics = run_tav_epoch(model, train_loader, question_index, criterion, optimizer)
        val_metrics = run_tav_epoch(model, val_loader, question_index, criterion)
        elapsed_seconds = time.perf_counter() - epoch_start_time
        improved_loss = val_metrics["loss"] < best_val_loss
        improved_ccc = val_metrics["ccc"] > best_val_ccc
        if improved_loss:
            best_val_loss = val_metrics["loss"]
            best_loss_epoch = epoch
        if improved_ccc:
            best_val_ccc = val_metrics["ccc"]
            best_ccc_epoch = epoch
        if improved_loss:
            save_tav_checkpoint(best_loss_path, "best_loss", epoch, question_index, seed, model, optimizer, train_metrics, val_metrics, class_counts, class_weights, best_val_loss, best_val_ccc, best_loss_epoch, best_ccc_epoch, text_checkpoint_path, audio_checkpoint_path, video_checkpoint_path)
        if improved_ccc:
            save_tav_checkpoint(best_ccc_path, "best_ccc", epoch, question_index, seed, model, optimizer, train_metrics, val_metrics, class_counts, class_weights, best_val_loss, best_val_ccc, best_loss_epoch, best_ccc_epoch, text_checkpoint_path, audio_checkpoint_path, video_checkpoint_path)
        history_rows.append({"Epoch": epoch, "Train_Loss": train_metrics["loss"], "Train_CCC": train_metrics["ccc"], "Train_Accuracy": train_metrics["accuracy"], "Val_Loss": val_metrics["loss"], "Val_CCC": val_metrics["ccc"], "Val_Accuracy": val_metrics["accuracy"], "Val_RMSE": val_metrics["rmse"], "Val_MAE": val_metrics["mae"], "Elapsed_Seconds": elapsed_seconds})
        print(f"Epoch {epoch:02d}/{NUM_EPOCHS} | Train Loss {train_metrics['loss']:.6f} | Val Loss {val_metrics['loss']:.6f} | Val CCC {val_metrics['ccc']:.6f} | Val Acc {val_metrics['accuracy']:.6f} | {elapsed_seconds:.2f}s")
    save_tav_checkpoint(last_path, "last", NUM_EPOCHS, question_index, seed, model, optimizer, train_metrics, val_metrics, class_counts, class_weights, best_val_loss, best_val_ccc, best_loss_epoch, best_ccc_epoch, text_checkpoint_path, audio_checkpoint_path, video_checkpoint_path)
    pd.DataFrame(history_rows).to_csv(history_path, index=False)
    print("=" * 100)
    print(f"训练完成：Seed={seed}，Q{question_index + 1}")
    print(f"最佳Val Loss：{best_val_loss:.6f}，Epoch={best_loss_epoch}")
    print(f"最佳Val CCC：{best_val_ccc:.6f}，Epoch={best_ccc_epoch}")
    return {"seed": seed, "question_index": question_index, "best_val_loss": best_val_loss, "best_val_ccc": best_val_ccc, "best_loss_epoch": best_loss_epoch, "best_ccc_epoch": best_ccc_epoch, "best_loss_path": best_loss_path, "best_ccc_path": best_ccc_path, "last_path": last_path, "history_path": history_path}

In [71]:
tav_q1_seed42_result = train_tav_question(seed=42, question_index=0)

Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 13
Audio保存Epoch： 10
Video保存Epoch： 2
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
====================================================================================================
开始训练T+A+V：Seed=42，Q1，PHQ_8NoInterest
类别数量： [81, 57, 20, 5]
====================================================================================================
Epoch 01/20 | Train Loss 2.006856 | Val Loss 2.558830 | Val CCC 0.302995 | Val Acc 0.418182 | 1.75s
Epoch 02/20 | Train Loss 1.353113 | Val Loss 3.167231 | Val CCC 0.301075 | Val Acc 0.509091 | 1.50s
Epoch 03/20 | Train Loss 1.315467 | Val Loss 2.404885 | Val CCC 0.402174 | Val Acc 0.527273 | 1.48s
Epoch 04/20 | Train Loss 1.151039 | Val Loss 2.720844 | Val CCC 0.366395 | Val Acc 0.618182 | 1.39s
Epoch 05/20 | Train Loss 1.049124 | Val Loss 3.566317 | Val CCC 0.283608 | Val Acc 0.490909 | 1.38s
Epoch 06/20 | Train Loss 1.170496 | Val Loss 3.037740 | Val CCC 0.326187 | Val Acc 0.527273 | 1.37s
Epoch 07/20 | Train Loss 1.224841 | Val Loss 3.473085 | Val CCC 0.327217 | Val Acc 0.527273 | 1.50s
Epoch 08/20 | Train Loss 1.253058 | Val Loss 2.528922 | Val CCC 0.308087 | Val Acc 0.509091 | 1.33s
Epoch 09/20 | Train Loss 1.026716 | Val Loss 2.946120 | Val CCC 0.364418 | Val Acc 0.527273 | 1.33s
Epoch 10/20 | Train Loss 1.263206 | Val Loss 3.678361 | Val CCC 0.291693 | Val Acc 0.436364 | 1.34s
Epoch 11/20 | Train Loss 1.071246 | Val Loss 3.191269 | Val CCC 0.266667 | Val Acc 0.563636 | 1.43s
Epoch 12/20 | Train Loss 0.948820 | Val Loss 2.998254 | Val CCC 0.404117 | Val Acc 0.581818 | 1.38s
Epoch 13/20 | Train Loss 1.148925 | Val Loss 2.415516 | Val CCC 0.430473 | Val Acc 0.454545 | 1.35s
Epoch 14/20 | Train Loss 1.073136 | Val Loss 2.935996 | Val CCC 0.335609 | Val Acc 0.563636 | 1.35s
Epoch 15/20 | Train Loss 1.105006 | Val Loss 2.735362 | Val CCC 0.320988 | Val Acc 0.454545 | 1.38s
Epoch 16/20 | Train Loss 0.991439 | Val Loss 4.278530 | Val CCC 0.202058 | Val Acc 0.509091 | 1.45s
Epoch 17/20 | Train Loss 0.991653 | Val Loss 2.911823 | Val CCC 0.485416 | Val Acc 0.600000 | 1.33s
Epoch 18/20 | Train Loss 0.968210 | Val Loss 4.497463 | Val CCC 0.302465 | Val Acc 0.490909 | 1.34s
Epoch 19/20 | Train Loss 1.229669 | Val Loss 3.531540 | Val CCC 0.368977 | Val Acc 0.490909 | 1.34s
Epoch 20/20 | Train Loss 1.154960 | Val Loss 2.992489 | Val CCC 0.254907 | Val Acc 0.563636 | 1.32s
====================================================================================================
训练完成：Seed=42，Q1
最佳Val Loss：2.404885，Epoch=3
最佳Val CCC：0.485416，Epoch=17

In [72]:
q1_tav_best_ccc_path = TAV_CHECKPOINT_ROOT / "seed_42" / "question_1" / "best_ccc.pt"
q1_tav_saved_checkpoint = torch.load(q1_tav_best_ccc_path, map_location="cpu", weights_only=False)
q1_tav_loaded_items = load_pretrained_tav_encoders(question_index=0, seed=42)
q1_tav_restored_text_encoder = q1_tav_loaded_items[0]
q1_tav_restored_audio_encoder = q1_tav_loaded_items[1]
q1_tav_restored_video_encoder = q1_tav_loaded_items[2]
q1_tav_restored_model = TextAudioVideoQuestMF(q1_tav_restored_text_encoder, q1_tav_restored_audio_encoder, q1_tav_restored_video_encoder).to(device)
q1_tav_load_result = q1_tav_restored_model.load_state_dict(q1_tav_saved_checkpoint["model_state_dict"], strict=True)
q1_tav_saved_class_weights = torch.as_tensor(q1_tav_saved_checkpoint["class_weights"], dtype=torch.float32, device=device)
q1_tav_restored_criterion = ImbOLLLoss(q1_tav_saved_class_weights)
_, q1_tav_restore_val_loader = create_tav_dataloaders(seed=42)
q1_tav_restored_metrics = run_tav_epoch(q1_tav_restored_model, q1_tav_restore_val_loader, 0, q1_tav_restored_criterion, optimizer=None)
print("Checkpoint：", q1_tav_best_ccc_path)
print("Checkpoint类型：", q1_tav_saved_checkpoint["checkpoint_type"])
print("保存Epoch：", q1_tav_saved_checkpoint["epoch"])
print("缺少参数：", q1_tav_load_result.missing_keys)
print("多余参数：", q1_tav_load_result.unexpected_keys)
for metric_name in ["loss", "accuracy", "micro_f1", "macro_f1", "weighted_f1", "ccc", "rmse", "mae"]:
    saved_value = float(q1_tav_saved_checkpoint["val_metrics"][metric_name])
    restored_value = float(q1_tav_restored_metrics[metric_name])
    difference = abs(saved_value - restored_value)
    print(f"{metric_name:>12} | 保存 {saved_value:.9f} | 恢复 {restored_value:.9f} | 差值 {difference:.3e}")
    assert difference < 1e-6
print("T+A+V Q1 Checkpoint恢复验证通过")

Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 13
Audio保存Epoch： 10
Video保存Epoch： 2
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
Checkpoint： /workspace/E-DAIC/checkpoints/phq8_text_audio_video_nopostzero/seed_42/question_1/best_ccc.pt
Checkpoint类型： best_ccc
保存Epoch： 17
缺少参数： []
多余参数： []
        loss | 保存 2.911822818 | 恢复 2.911822818 | 差值 0.000e+00
    accuracy | 保存 0.600000000 | 恢复 0.600000000 | 差值 0.000e+00
    micro_f1 | 保存 0.600000000 | 恢复 0.600000000 | 差值 0.000e+00
    macro_f1 | 保存 0.383134413 | 恢复 0.383134413 | 差值 0.000e+00
 weighted_f1 | 保存 0.580929500 | 恢复 0.580929500 | 差值 0.000e+00
         ccc | 保存 0.485415520 | 恢复 0.485415520 | 差值 0.000e+00
        rmse | 保存 0.786245406 | 恢复 0.786245406 | 差值 0.000e+00
         mae | 保存 0.472727269 | 恢复 0.472727269 | 差值 0.000e+00
T+A+V Q1 Checkpoint恢复验证通过

In [74]:
tav_seed42_results = []

for question_index in range(1, 8):
    current_result = train_tav_question(seed=42, question_index=question_index)
    tav_seed42_results.append(current_result)
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 9
Audio保存Epoch： 11
Video保存Epoch： 8
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
====================================================================================================
开始训练T+A+V：Seed=42，Q2，PHQ_8Depressed
类别数量： [68, 63, 18, 14]
====================================================================================================
Epoch 01/20 | Train Loss 2.206376 | Val Loss 2.053315 | Val CCC 0.360000 | Val Acc 0.418182 | 1.60s
Epoch 02/20 | Train Loss 1.661960 | Val Loss 2.038682 | Val CCC 0.581463 | Val Acc 0.509091 | 1.56s
Epoch 03/20 | Train Loss 1.808136 | Val Loss 2.046854 | Val CCC 0.373510 | Val Acc 0.527273 | 1.40s
Epoch 04/20 | Train Loss 1.585796 | Val Loss 2.019823 | Val CCC 0.551268 | Val Acc 0.490909 | 1.90s
Epoch 05/20 | Train Loss 1.603923 | Val Loss 2.027655 | Val CCC 0.536703 | Val Acc 0.527273 | 1.39s
Epoch 06/20 | Train Loss 1.690335 | Val Loss 1.969212 | Val CCC 0.568627 | Val Acc 0.490909 | 1.37s
Epoch 07/20 | Train Loss 1.568156 | Val Loss 1.980830 | Val CCC 0.498331 | Val Acc 0.527273 | 1.37s
Epoch 08/20 | Train Loss 1.561943 | Val Loss 2.098892 | Val CCC 0.498480 | Val Acc 0.545455 | 1.38s
Epoch 09/20 | Train Loss 1.532354 | Val Loss 2.042748 | Val CCC 0.490526 | Val Acc 0.563636 | 1.37s
Epoch 10/20 | Train Loss 1.433732 | Val Loss 2.034161 | Val CCC 0.395881 | Val Acc 0.400000 | 1.36s
Epoch 11/20 | Train Loss 1.404951 | Val Loss 2.101061 | Val CCC 0.530806 | Val Acc 0.509091 | 1.36s
Epoch 12/20 | Train Loss 1.492883 | Val Loss 2.098656 | Val CCC 0.511111 | Val Acc 0.509091 | 1.37s
Epoch 13/20 | Train Loss 1.482054 | Val Loss 1.960164 | Val CCC 0.531148 | Val Acc 0.509091 | 1.36s
Epoch 14/20 | Train Loss 1.410677 | Val Loss 2.166486 | Val CCC 0.407359 | Val Acc 0.418182 | 1.36s
Epoch 15/20 | Train Loss 1.600727 | Val Loss 2.671006 | Val CCC 0.363893 | Val Acc 0.418182 | 1.36s
Epoch 16/20 | Train Loss 1.424967 | Val Loss 2.233774 | Val CCC 0.483673 | Val Acc 0.490909 | 1.37s
Epoch 17/20 | Train Loss 1.497095 | Val Loss 2.141565 | Val CCC 0.436234 | Val Acc 0.527273 | 1.35s
Epoch 18/20 | Train Loss 1.348913 | Val Loss 3.462377 | Val CCC 0.504174 | Val Acc 0.545455 | 1.35s
Epoch 19/20 | Train Loss 1.490916 | Val Loss 2.304280 | Val CCC 0.419525 | Val Acc 0.490909 | 1.36s
Epoch 20/20 | Train Loss 1.351217 | Val Loss 2.964535 | Val CCC 0.409396 | Val Acc 0.600000 | 1.33s
====================================================================================================
训练完成：Seed=42，Q2
最佳Val Loss：1.960164，Epoch=13
最佳Val CCC：0.581463，Epoch=2
Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 9
Audio保存Epoch： 14
Video保存Epoch： 14
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
====================================================================================================
开始训练T+A+V：Seed=42，Q3，PHQ_8Sleep
类别数量： [69, 40, 27, 27]
====================================================================================================
Epoch 01/20 | Train Loss 2.284347 | Val Loss 2.917359 | Val CCC 0.416366 | Val Acc 0.436364 | 1.38s
Epoch 02/20 | Train Loss 1.910171 | Val Loss 2.262345 | Val CCC 0.263181 | Val Acc 0.363636 | 1.34s
Epoch 03/20 | Train Loss 1.812231 | Val Loss 2.720309 | Val CCC 0.409300 | Val Acc 0.363636 | 1.33s
Epoch 04/20 | Train Loss 1.753882 | Val Loss 2.244637 | Val CCC 0.460317 | Val Acc 0.436364 | 1.34s
Epoch 05/20 | Train Loss 1.873155 | Val Loss 2.203615 | Val CCC 0.420252 | Val Acc 0.418182 | 1.34s
Epoch 06/20 | Train Loss 1.757897 | Val Loss 2.376050 | Val CCC 0.379032 | Val Acc 0.454545 | 1.37s
Epoch 07/20 | Train Loss 1.702154 | Val Loss 2.436192 | Val CCC 0.470863 | Val Acc 0.490909 | 1.35s
Epoch 08/20 | Train Loss 1.600495 | Val Loss 2.662258 | Val CCC 0.458805 | Val Acc 0.454545 | 1.39s
Epoch 09/20 | Train Loss 1.612461 | Val Loss 2.667212 | Val CCC 0.481487 | Val Acc 0.418182 | 1.34s
Epoch 10/20 | Train Loss 1.816100 | Val Loss 2.465066 | Val CCC 0.482536 | Val Acc 0.436364 | 1.35s
Epoch 11/20 | Train Loss 1.630428 | Val Loss 2.896378 | Val CCC 0.476480 | Val Acc 0.472727 | 1.34s
Epoch 12/20 | Train Loss 1.535530 | Val Loss 2.363794 | Val CCC 0.286285 | Val Acc 0.400000 | 1.35s
Epoch 13/20 | Train Loss 1.515155 | Val Loss 2.768912 | Val CCC 0.487288 | Val Acc 0.436364 | 1.36s
Epoch 14/20 | Train Loss 1.474494 | Val Loss 2.716303 | Val CCC 0.450344 | Val Acc 0.454545 | 1.37s
Epoch 15/20 | Train Loss 1.570672 | Val Loss 2.437697 | Val CCC 0.350028 | Val Acc 0.381818 | 1.36s
Epoch 16/20 | Train Loss 1.688062 | Val Loss 2.881578 | Val CCC 0.331916 | Val Acc 0.400000 | 1.35s
Epoch 17/20 | Train Loss 1.574131 | Val Loss 2.564275 | Val CCC 0.361317 | Val Acc 0.363636 | 1.36s
Epoch 18/20 | Train Loss 1.625161 | Val Loss 3.384716 | Val CCC 0.357367 | Val Acc 0.509091 | 1.36s
Epoch 19/20 | Train Loss 1.473819 | Val Loss 2.475363 | Val CCC 0.372007 | Val Acc 0.400000 | 1.35s
Epoch 20/20 | Train Loss 1.445792 | Val Loss 2.542741 | Val CCC 0.427746 | Val Acc 0.472727 | 1.34s
====================================================================================================
训练完成：Seed=42，Q3
最佳Val Loss：2.203615，Epoch=5
最佳Val CCC：0.487288，Epoch=13
Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 11
Audio保存Epoch： 28
Video保存Epoch： 7
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
====================================================================================================
开始训练T+A+V：Seed=42，Q4，PHQ_8Tired
类别数量： [50, 65, 27, 21]
====================================================================================================
Epoch 01/20 | Train Loss 2.386300 | Val Loss 2.237422 | Val CCC 0.290771 | Val Acc 0.345455 | 1.35s
Epoch 02/20 | Train Loss 1.782192 | Val Loss 3.107777 | Val CCC 0.204975 | Val Acc 0.363636 | 1.38s
Epoch 03/20 | Train Loss 1.852873 | Val Loss 2.320769 | Val CCC 0.342831 | Val Acc 0.327273 | 1.36s
Epoch 04/20 | Train Loss 1.789882 | Val Loss 2.229909 | Val CCC 0.344560 | Val Acc 0.381818 | 1.35s
Epoch 05/20 | Train Loss 1.694946 | Val Loss 2.462131 | Val CCC 0.370671 | Val Acc 0.363636 | 1.35s
Epoch 06/20 | Train Loss 1.905493 | Val Loss 2.209791 | Val CCC 0.378609 | Val Acc 0.345455 | 1.36s
Epoch 07/20 | Train Loss 1.710606 | Val Loss 2.421062 | Val CCC 0.301218 | Val Acc 0.400000 | 1.36s
Epoch 08/20 | Train Loss 1.803999 | Val Loss 2.188520 | Val CCC 0.406851 | Val Acc 0.345455 | 1.35s
Epoch 09/20 | Train Loss 1.638050 | Val Loss 2.147697 | Val CCC 0.367519 | Val Acc 0.436364 | 1.38s
Epoch 10/20 | Train Loss 1.500452 | Val Loss 2.258235 | Val CCC 0.375937 | Val Acc 0.363636 | 1.35s
Epoch 11/20 | Train Loss 1.529861 | Val Loss 2.467450 | Val CCC 0.418381 | Val Acc 0.436364 | 1.35s
Epoch 12/20 | Train Loss 1.365529 | Val Loss 3.738606 | Val CCC 0.318279 | Val Acc 0.363636 | 1.36s
Epoch 13/20 | Train Loss 1.666493 | Val Loss 2.560461 | Val CCC 0.318803 | Val Acc 0.381818 | 1.36s
Epoch 14/20 | Train Loss 1.365965 | Val Loss 2.518796 | Val CCC 0.234806 | Val Acc 0.290909 | 1.35s
Epoch 15/20 | Train Loss 1.485856 | Val Loss 2.355304 | Val CCC 0.402971 | Val Acc 0.400000 | 1.34s
Epoch 16/20 | Train Loss 1.457173 | Val Loss 2.979748 | Val CCC 0.358247 | Val Acc 0.381818 | 1.35s
Epoch 17/20 | Train Loss 1.305315 | Val Loss 2.727502 | Val CCC 0.395604 | Val Acc 0.345455 | 1.34s
Epoch 18/20 | Train Loss 1.467120 | Val Loss 2.680879 | Val CCC 0.360360 | Val Acc 0.309091 | 1.35s
Epoch 19/20 | Train Loss 1.394642 | Val Loss 2.430286 | Val CCC 0.426975 | Val Acc 0.381818 | 1.35s
Epoch 20/20 | Train Loss 1.341331 | Val Loss 2.970592 | Val CCC 0.349058 | Val Acc 0.381818 | 1.37s
====================================================================================================
训练完成：Seed=42，Q4
最佳Val Loss：2.147697，Epoch=9
最佳Val CCC：0.426975，Epoch=19
Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 13
Audio保存Epoch： 32
Video保存Epoch： 2
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
====================================================================================================
开始训练T+A+V：Seed=42，Q5，PHQ_8Appetite
类别数量： [77, 42, 24, 20]
====================================================================================================
Epoch 01/20 | Train Loss 2.536134 | Val Loss 2.846351 | Val CCC 0.247996 | Val Acc 0.327273 | 1.37s
Epoch 02/20 | Train Loss 1.821114 | Val Loss 2.148924 | Val CCC 0.429131 | Val Acc 0.418182 | 1.37s
Epoch 03/20 | Train Loss 1.781154 | Val Loss 2.323166 | Val CCC 0.475314 | Val Acc 0.436364 | 1.32s
Epoch 04/20 | Train Loss 1.580699 | Val Loss 2.645126 | Val CCC 0.455216 | Val Acc 0.472727 | 1.31s
Epoch 05/20 | Train Loss 1.572389 | Val Loss 3.775849 | Val CCC 0.481754 | Val Acc 0.436364 | 1.34s
Epoch 06/20 | Train Loss 1.601320 | Val Loss 2.871345 | Val CCC 0.483100 | Val Acc 0.436364 | 1.35s
Epoch 07/20 | Train Loss 1.553547 | Val Loss 2.583371 | Val CCC 0.532578 | Val Acc 0.509091 | 1.35s
Epoch 08/20 | Train Loss 1.705763 | Val Loss 2.547682 | Val CCC 0.352683 | Val Acc 0.418182 | 1.36s
Epoch 09/20 | Train Loss 1.676042 | Val Loss 2.525960 | Val CCC 0.534724 | Val Acc 0.490909 | 1.35s
Epoch 10/20 | Train Loss 1.604095 | Val Loss 2.467558 | Val CCC 0.551549 | Val Acc 0.509091 | 1.36s
Epoch 11/20 | Train Loss 1.436456 | Val Loss 3.583623 | Val CCC 0.364649 | Val Acc 0.381818 | 1.37s
Epoch 12/20 | Train Loss 1.563276 | Val Loss 2.618400 | Val CCC 0.435500 | Val Acc 0.454545 | 1.37s
Epoch 13/20 | Train Loss 1.639896 | Val Loss 2.522011 | Val CCC 0.470655 | Val Acc 0.490909 | 1.35s
Epoch 14/20 | Train Loss 1.580759 | Val Loss 3.407768 | Val CCC 0.454646 | Val Acc 0.454545 | 1.35s
Epoch 15/20 | Train Loss 1.686880 | Val Loss 2.997573 | Val CCC 0.434749 | Val Acc 0.472727 | 1.34s
Epoch 16/20 | Train Loss 1.586504 | Val Loss 3.473588 | Val CCC 0.460863 | Val Acc 0.418182 | 1.33s
Epoch 17/20 | Train Loss 1.606384 | Val Loss 3.465336 | Val CCC 0.454771 | Val Acc 0.418182 | 1.34s
Epoch 18/20 | Train Loss 1.596139 | Val Loss 2.791635 | Val CCC 0.474589 | Val Acc 0.472727 | 1.35s
Epoch 19/20 | Train Loss 1.444124 | Val Loss 2.884051 | Val CCC 0.514649 | Val Acc 0.527273 | 1.35s
Epoch 20/20 | Train Loss 1.387906 | Val Loss 3.476979 | Val CCC 0.421802 | Val Acc 0.400000 | 1.36s
====================================================================================================
训练完成：Seed=42，Q5
最佳Val Loss：2.148924，Epoch=2
最佳Val CCC：0.551549，Epoch=10
Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 10
Audio保存Epoch： 45
Video保存Epoch： 24
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
====================================================================================================
开始训练T+A+V：Seed=42，Q6，PHQ_8Failure
类别数量： [76, 44, 24, 19]
====================================================================================================
Epoch 01/20 | Train Loss 2.204635 | Val Loss 2.132263 | Val CCC 0.460101 | Val Acc 0.418182 | 1.42s
Epoch 02/20 | Train Loss 1.733368 | Val Loss 1.981472 | Val CCC 0.559312 | Val Acc 0.472727 | 1.34s
Epoch 03/20 | Train Loss 1.773186 | Val Loss 2.143096 | Val CCC 0.399648 | Val Acc 0.400000 | 1.33s
Epoch 04/20 | Train Loss 1.675124 | Val Loss 2.180389 | Val CCC 0.514117 | Val Acc 0.490909 | 1.33s
Epoch 05/20 | Train Loss 1.891784 | Val Loss 1.997399 | Val CCC 0.424396 | Val Acc 0.418182 | 1.34s
Epoch 06/20 | Train Loss 1.597435 | Val Loss 2.032471 | Val CCC 0.427282 | Val Acc 0.436364 | 1.35s
Epoch 07/20 | Train Loss 1.560425 | Val Loss 1.898807 | Val CCC 0.479495 | Val Acc 0.490909 | 1.33s
Epoch 08/20 | Train Loss 1.511077 | Val Loss 1.984373 | Val CCC 0.518785 | Val Acc 0.490909 | 1.36s
Epoch 09/20 | Train Loss 1.622652 | Val Loss 2.260782 | Val CCC 0.311038 | Val Acc 0.509091 | 1.34s
Epoch 10/20 | Train Loss 1.483046 | Val Loss 2.071138 | Val CCC 0.398298 | Val Acc 0.436364 | 1.33s
Epoch 11/20 | Train Loss 1.469679 | Val Loss 2.194209 | Val CCC 0.396767 | Val Acc 0.490909 | 1.32s
Epoch 12/20 | Train Loss 1.465914 | Val Loss 2.116690 | Val CCC 0.373005 | Val Acc 0.418182 | 1.34s
Epoch 13/20 | Train Loss 1.495853 | Val Loss 2.069519 | Val CCC 0.464286 | Val Acc 0.454545 | 1.32s
Epoch 14/20 | Train Loss 1.584968 | Val Loss 2.222443 | Val CCC 0.438474 | Val Acc 0.490909 | 1.34s
Epoch 15/20 | Train Loss 1.389340 | Val Loss 2.002987 | Val CCC 0.423852 | Val Acc 0.490909 | 1.31s
Epoch 16/20 | Train Loss 1.371363 | Val Loss 2.154743 | Val CCC 0.344554 | Val Acc 0.490909 | 1.31s
Epoch 17/20 | Train Loss 1.188346 | Val Loss 2.309522 | Val CCC 0.391643 | Val Acc 0.454545 | 1.35s
Epoch 18/20 | Train Loss 1.505425 | Val Loss 2.494368 | Val CCC 0.415344 | Val Acc 0.490909 | 1.36s
Epoch 19/20 | Train Loss 1.806056 | Val Loss 2.205413 | Val CCC 0.433202 | Val Acc 0.418182 | 1.37s
Epoch 20/20 | Train Loss 1.376031 | Val Loss 2.541105 | Val CCC 0.421672 | Val Acc 0.509091 | 1.38s
====================================================================================================
训练完成：Seed=42，Q6
最佳Val Loss：1.898807，Epoch=7
最佳Val CCC：0.559312，Epoch=2
Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 15
Audio保存Epoch： 3
Video保存Epoch： 1
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
====================================================================================================
开始训练T+A+V：Seed=42，Q7，PHQ_8Concentrating
类别数量： [93, 37, 14, 19]
====================================================================================================
Epoch 01/20 | Train Loss 2.262033 | Val Loss 2.299217 | Val CCC 0.471073 | Val Acc 0.600000 | 1.39s
Epoch 02/20 | Train Loss 1.636331 | Val Loss 2.837278 | Val CCC 0.467979 | Val Acc 0.581818 | 1.35s
Epoch 03/20 | Train Loss 1.683695 | Val Loss 2.081472 | Val CCC 0.592928 | Val Acc 0.509091 | 1.36s
Epoch 04/20 | Train Loss 1.573191 | Val Loss 2.117583 | Val CCC 0.447876 | Val Acc 0.563636 | 1.34s
Epoch 05/20 | Train Loss 1.489021 | Val Loss 1.982872 | Val CCC 0.430642 | Val Acc 0.545455 | 1.34s
Epoch 06/20 | Train Loss 1.408063 | Val Loss 2.032952 | Val CCC 0.503047 | Val Acc 0.436364 | 1.35s
Epoch 07/20 | Train Loss 1.424430 | Val Loss 2.427142 | Val CCC 0.476755 | Val Acc 0.472727 | 1.35s
Epoch 08/20 | Train Loss 1.547004 | Val Loss 2.066295 | Val CCC 0.524784 | Val Acc 0.527273 | 1.34s
Epoch 09/20 | Train Loss 1.458124 | Val Loss 2.010649 | Val CCC 0.517321 | Val Acc 0.527273 | 1.34s
Epoch 10/20 | Train Loss 1.392468 | Val Loss 1.964126 | Val CCC 0.542647 | Val Acc 0.418182 | 1.33s
Epoch 11/20 | Train Loss 1.424981 | Val Loss 2.291446 | Val CCC 0.461931 | Val Acc 0.527273 | 1.34s
Epoch 12/20 | Train Loss 1.405377 | Val Loss 1.992232 | Val CCC 0.470466 | Val Acc 0.545455 | 1.36s
Epoch 13/20 | Train Loss 1.354118 | Val Loss 1.971545 | Val CCC 0.520160 | Val Acc 0.545455 | 1.34s
Epoch 14/20 | Train Loss 1.365662 | Val Loss 2.135333 | Val CCC 0.450539 | Val Acc 0.454545 | 1.35s
Epoch 15/20 | Train Loss 1.317824 | Val Loss 2.180588 | Val CCC 0.572816 | Val Acc 0.472727 | 1.34s
Epoch 16/20 | Train Loss 1.306647 | Val Loss 3.148622 | Val CCC 0.433768 | Val Acc 0.490909 | 1.34s
Epoch 17/20 | Train Loss 1.501272 | Val Loss 2.110323 | Val CCC 0.516854 | Val Acc 0.436364 | 1.34s
Epoch 18/20 | Train Loss 1.401894 | Val Loss 2.661281 | Val CCC 0.495413 | Val Acc 0.527273 | 1.34s
Epoch 19/20 | Train Loss 1.365912 | Val Loss 2.383449 | Val CCC 0.505591 | Val Acc 0.618182 | 1.34s
Epoch 20/20 | Train Loss 1.482249 | Val Loss 1.932818 | Val CCC 0.482929 | Val Acc 0.527273 | 1.36s
====================================================================================================
训练完成：Seed=42，Q7
最佳Val Loss：1.932818，Epoch=20
最佳Val CCC：0.592928，Epoch=3
Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 11
Audio保存Epoch： 12
Video保存Epoch： 2
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
====================================================================================================
开始训练T+A+V：Seed=42，Q8，PHQ_8Moving
类别数量： [128, 20, 9, 6]
====================================================================================================
Epoch 01/20 | Train Loss 2.404161 | Val Loss 1.952270 | Val CCC 0.213440 | Val Acc 0.454545 | 1.36s
Epoch 02/20 | Train Loss 1.461189 | Val Loss 4.001039 | Val CCC 0.294598 | Val Acc 0.618182 | 1.35s
Epoch 03/20 | Train Loss 1.429041 | Val Loss 1.820172 | Val CCC 0.156898 | Val Acc 0.436364 | 1.38s
Epoch 04/20 | Train Loss 1.509354 | Val Loss 2.170886 | Val CCC 0.226995 | Val Acc 0.527273 | 1.35s
Epoch 05/20 | Train Loss 1.390815 | Val Loss 2.740644 | Val CCC 0.239092 | Val Acc 0.618182 | 1.35s
Epoch 06/20 | Train Loss 1.445397 | Val Loss 1.708942 | Val CCC 0.162437 | Val Acc 0.454545 | 1.35s
Epoch 07/20 | Train Loss 1.463967 | Val Loss 2.266442 | Val CCC 0.256320 | Val Acc 0.545455 | 1.35s
Epoch 08/20 | Train Loss 1.226703 | Val Loss 2.831563 | Val CCC 0.261745 | Val Acc 0.545455 | 1.34s
Epoch 09/20 | Train Loss 1.279802 | Val Loss 2.562577 | Val CCC 0.262452 | Val Acc 0.545455 | 1.35s
Epoch 10/20 | Train Loss 1.769237 | Val Loss 2.025181 | Val CCC 0.332828 | Val Acc 0.581818 | 1.50s
Epoch 11/20 | Train Loss 1.243227 | Val Loss 2.941084 | Val CCC 0.284074 | Val Acc 0.600000 | 1.52s
Epoch 12/20 | Train Loss 1.267023 | Val Loss 2.359710 | Val CCC 0.210762 | Val Acc 0.581818 | 1.52s
Epoch 13/20 | Train Loss 1.281538 | Val Loss 2.211228 | Val CCC 0.307467 | Val Acc 0.581818 | 1.51s
Epoch 14/20 | Train Loss 1.367514 | Val Loss 2.399225 | Val CCC 0.291188 | Val Acc 0.600000 | 1.42s
Epoch 15/20 | Train Loss 1.226480 | Val Loss 3.043184 | Val CCC 0.201302 | Val Acc 0.581818 | 1.39s
Epoch 16/20 | Train Loss 1.299329 | Val Loss 2.612960 | Val CCC 0.332828 | Val Acc 0.581818 | 1.39s
Epoch 17/20 | Train Loss 1.380289 | Val Loss 2.435051 | Val CCC 0.259579 | Val Acc 0.563636 | 1.39s
Epoch 18/20 | Train Loss 1.464662 | Val Loss 2.677792 | Val CCC 0.201302 | Val Acc 0.581818 | 1.39s
Epoch 19/20 | Train Loss 1.280221 | Val Loss 2.275283 | Val CCC 0.315353 | Val Acc 0.563636 | 1.39s
Epoch 20/20 | Train Loss 1.440081 | Val Loss 3.392214 | Val CCC 0.201452 | Val Acc 0.581818 | 1.38s
====================================================================================================
训练完成：Seed=42，Q8
最佳Val Loss：1.708942，Epoch=6
最佳Val CCC：0.332828，Epoch=10

In [75]:
tav_seed42_question_rows = []

for question_index, question_name in enumerate(PHQ8_QUESTION_COLUMNS):
    checkpoint_path = TAV_CHECKPOINT_ROOT / "seed_42" / f"question_{question_index + 1}" / "best_ccc.pt"
    checkpoint = torch.load(checkpoint_path, map_location="cpu", weights_only=False)
    val_metrics = checkpoint["val_metrics"]
    row = {}
    row["Question_Number"] = question_index + 1
    row["Question_Name"] = question_name
    row["Checkpoint_Epoch"] = checkpoint["epoch"]
    row["CCC"] = val_metrics["ccc"]
    row["RMSE"] = val_metrics["rmse"]
    row["MAE"] = val_metrics["mae"]
    row["Accuracy"] = val_metrics["accuracy"]
    tav_seed42_question_rows.append(row)

tav_seed42_question_summary_df = pd.DataFrame(tav_seed42_question_rows)
display(tav_seed42_question_summary_df)

,Question_Number,Question_Name,Checkpoint_Epoch,CCC,RMSE,MAE,Accuracy
0,1,PHQ_8NoInterest,17,0.485416,0.786245,0.472727,0.600000
1,2,PHQ_8Depressed,2,0.581463,0.842075,0.563636,0.509091
2,3,PHQ_8Sleep,13,0.487288,1.095445,0.763636,0.436364
3,4,PHQ_8Tired,19,0.426975,1.000000,0.745455,0.381818
4,5,PHQ_8Appetite,10,0.551549,0.904534,0.600000,0.509091
5,6,PHQ_8Failure,2,0.559312,0.863397,0.600000,0.472727
6,7,PHQ_8Concentrating,3,0.592928,0.809040,0.545455,0.509091
7,8,PHQ_8Moving,10,0.332828,0.762770,0.472727,0.581818

In [76]:
for question_index in range(8):
    question_dir = TAV_CHECKPOINT_ROOT / "seed_42" / f"question_{question_index + 1}"
    best_loss_exists = (question_dir / "best_loss.pt").exists()
    best_ccc_exists = (question_dir / "best_ccc.pt").exists()
    last_exists = (question_dir / "last.pt").exists()
    history_exists = (question_dir / "history.csv").exists()
    print(f"Q{question_index + 1} | Best Loss {best_loss_exists} | Best CCC {best_ccc_exists} | Last {last_exists} | History {history_exists}")

Q1 | Best Loss True | Best CCC True | Last True | History True
Q2 | Best Loss True | Best CCC True | Last True | History True
Q3 | Best Loss True | Best CCC True | Last True | History True
Q4 | Best Loss True | Best CCC True | Last True | History True
Q5 | Best Loss True | Best CCC True | Last True | History True
Q6 | Best Loss True | Best CCC True | Last True | History True
Q7 | Best Loss True | Best CCC True | Last True | History True
Q8 | Best Loss True | Best CCC True | Last True | History True

In [81]:
def evaluate_tav_seed_on_validation(seed):
    _, validation_loader = create_tav_dataloaders(seed=seed)
    question_prediction_list = []
    question_true_list = []

    for question_index in range(8):
        checkpoint_path = TAV_CHECKPOINT_ROOT / f"seed_{seed}" / f"question_{question_index + 1}" / "best_ccc.pt"
        checkpoint = torch.load(checkpoint_path, map_location="cpu", weights_only=False)
        loaded_items = load_pretrained_tav_encoders(question_index=question_index, seed=seed)
        text_encoder = loaded_items[0]
        audio_encoder = loaded_items[1]
        video_encoder = loaded_items[2]
        model = TextAudioVideoQuestMF(text_encoder, audio_encoder, video_encoder).to(device)
        load_result = model.load_state_dict(checkpoint["model_state_dict"], strict=True)
        model.eval()
        prediction_chunks = []
        true_chunks = []

        with torch.no_grad():
            for batch in validation_loader:
                text_features, text_masks, audio_features, audio_masks, video_features, video_masks, all_labels = batch
                logits = model(text_features.to(device), text_masks.to(device), audio_features.to(device), audio_masks.to(device), video_features.to(device), video_masks.to(device))
                predictions = torch.argmax(logits, dim=1).cpu()
                true_labels = all_labels[:, question_index].cpu()
                prediction_chunks.append(predictions)
                true_chunks.append(true_labels)

        question_predictions = torch.cat(prediction_chunks, dim=0)
        question_true = torch.cat(true_chunks, dim=0)
        question_prediction_list.append(question_predictions)
        question_true_list.append(question_true)
        print(f"Q{question_index + 1} | Epoch {checkpoint['epoch']:02d} | 样本 {len(question_predictions)} | 参数完整 {len(load_result.missing_keys) == 0 and len(load_result.unexpected_keys) == 0}")
        del model
        gc.collect()

        if torch.cuda.is_available():
            torch.cuda.empty_cache()

    predicted_question_matrix = torch.stack(question_prediction_list, dim=1).numpy()
    true_question_matrix = torch.stack(question_true_list, dim=1).numpy()
    predicted_totals = predicted_question_matrix.sum(axis=1)
    true_totals = true_question_matrix.sum(axis=1)
    total_ccc = float(calculate_ccc(torch.from_numpy(predicted_totals), torch.from_numpy(true_totals)))
    total_rmse = float(np.sqrt(np.mean((predicted_totals - true_totals) ** 2)))
    total_mae = float(np.mean(np.abs(predicted_totals - true_totals)))
    exact_accuracy = float(np.mean(predicted_totals == true_totals))
    participant_ids = val_metadata_df["Participant_ID"].astype(int).to_numpy()
    prediction_df = pd.DataFrame({"Participant_ID": participant_ids})

    for question_index in range(8):
        prediction_df[f"Predicted_Q{question_index + 1}"] = predicted_question_matrix[:, question_index]
        prediction_df[f"True_Q{question_index + 1}"] = true_question_matrix[:, question_index]

    prediction_df["Predicted_Total"] = predicted_totals
    prediction_df["True_Total"] = true_totals
    prediction_path = TAV_CHECKPOINT_ROOT / f"seed_{seed}_validation_predictions.csv"
    prediction_df.to_csv(prediction_path, index=False)
    result = {}
    result["seed"] = seed
    result["sample_count"] = len(prediction_df)
    result["ccc"] = total_ccc
    result["rmse"] = total_rmse
    result["mae"] = total_mae
    result["exact_accuracy"] = exact_accuracy
    result["prediction_path"] = prediction_path
    result["prediction_df"] = prediction_df
    return result

In [82]:
tav_seed42_validation_result = evaluate_tav_seed_on_validation(seed=42)
print("=" * 70)
print("验证参与者数量：", tav_seed42_validation_result["sample_count"])
print(f"总分CCC：{tav_seed42_validation_result['ccc']:.6f}")
print(f"总分RMSE：{tav_seed42_validation_result['rmse']:.6f}")
print(f"总分MAE：{tav_seed42_validation_result['mae']:.6f}")
print(f"完全相等比例：{tav_seed42_validation_result['exact_accuracy']:.6f}")
print("预测总分范围：", tav_seed42_validation_result["prediction_df"]["Predicted_Total"].min(), "～", tav_seed42_validation_result["prediction_df"]["Predicted_Total"].max())
print("真实总分范围：", tav_seed42_validation_result["prediction_df"]["True_Total"].min(), "～", tav_seed42_validation_result["prediction_df"]["True_Total"].max())
print("预测文件：", tav_seed42_validation_result["prediction_path"])

Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 13
Audio保存Epoch： 10
Video保存Epoch： 2
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
Q1 | Epoch 17 | 样本 55 | 参数完整 True
Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 9
Audio保存Epoch： 11
Video保存Epoch： 8
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
Q2 | Epoch 02 | 样本 55 | 参数完整 True
Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 9
Audio保存Epoch： 14
Video保存Epoch： 14
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
Q3 | Epoch 13 | 样本 55 | 参数完整 True
Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 11
Audio保存Epoch： 28
Video保存Epoch： 7
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
Q4 | Epoch 19 | 样本 55 | 参数完整 True
Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 13
Audio保存Epoch： 32
Video保存Epoch： 2
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
Q5 | Epoch 10 | 样本 55 | 参数完整 True
Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 10
Audio保存Epoch： 45
Video保存Epoch： 24
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
Q6 | Epoch 02 | 样本 55 | 参数完整 True
Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 15
Audio保存Epoch： 3
Video保存Epoch： 1
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
Q7 | Epoch 03 | 样本 55 | 参数完整 True
Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 11
Audio保存Epoch： 12
Video保存Epoch： 2
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
Q8 | Epoch 10 | 样本 55 | 参数完整 True
======================================================================
验证参与者数量： 55
总分CCC：0.710736
总分RMSE：4.297991
总分MAE：3.309091
完全相等比例：0.072727
预测总分范围： 0 ～ 22
真实总分范围： 0 ～ 20
预测文件： /workspace/E-DAIC/checkpoints/phq8_text_audio_video_nopostzero/seed_42_validation_predictions.csv

In [83]:
print("验证参与者数量：", tav_seed42_validation_result["sample_count"])
print(f"总分CCC：{tav_seed42_validation_result['ccc']:.6f}")
print(f"总分RMSE：{tav_seed42_validation_result['rmse']:.6f}")
print(f"总分MAE：{tav_seed42_validation_result['mae']:.6f}")
print(f"完全相等比例：{tav_seed42_validation_result['exact_accuracy']:.6f}")

验证参与者数量： 55
总分CCC：0.710736
总分RMSE：4.297991
总分MAE：3.309091
完全相等比例：0.072727

In [84]:
tav_remaining_seed_results = {}

for seed in [100, 1234]:
    seed_results = []
    print("=" * 100)
    print(f"开始完整训练 Seed={seed}")
    print("=" * 100)

    for question_index in range(8):
        current_result = train_tav_question(seed=seed, question_index=question_index)
        seed_results.append(current_result)
        gc.collect()

        if torch.cuda.is_available():
            torch.cuda.empty_cache()

    tav_remaining_seed_results[seed] = seed_results

====================================================================================================
开始完整训练 Seed=100
====================================================================================================
Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 10
Audio保存Epoch： 8
Video保存Epoch： 14
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
====================================================================================================
开始训练T+A+V：Seed=100，Q1，PHQ_8NoInterest
类别数量： [81, 57, 20, 5]
====================================================================================================
Epoch 01/20 | Train Loss 1.850259 | Val Loss 3.728074 | Val CCC 0.462073 | Val Acc 0.490909 | 1.61s
Epoch 02/20 | Train Loss 1.673218 | Val Loss 4.422473 | Val CCC 0.119191 | Val Acc 0.545455 | 1.68s
Epoch 03/20 | Train Loss 1.514468 | Val Loss 3.713111 | Val CCC 0.279369 | Val Acc 0.490909 | 2.09s
Epoch 04/20 | Train Loss 1.757857 | Val Loss 4.124222 | Val CCC 0.265955 | Val Acc 0.509091 | 1.62s
Epoch 05/20 | Train Loss 1.671832 | Val Loss 2.786579 | Val CCC 0.286848 | Val Acc 0.472727 | 1.66s
Epoch 06/20 | Train Loss 1.407892 | Val Loss 2.999182 | Val CCC 0.413368 | Val Acc 0.545455 | 1.48s
Epoch 07/20 | Train Loss 1.438666 | Val Loss 2.843956 | Val CCC 0.365496 | Val Acc 0.563636 | 1.58s
Epoch 08/20 | Train Loss 1.413405 | Val Loss 3.108295 | Val CCC 0.503817 | Val Acc 0.545455 | 1.41s
Epoch 09/20 | Train Loss 1.411399 | Val Loss 2.700068 | Val CCC 0.417057 | Val Acc 0.527273 | 1.37s
Epoch 10/20 | Train Loss 1.342904 | Val Loss 3.228398 | Val CCC 0.318122 | Val Acc 0.563636 | 1.38s
Epoch 11/20 | Train Loss 1.447148 | Val Loss 2.432544 | Val CCC 0.289149 | Val Acc 0.527273 | 1.37s
Epoch 12/20 | Train Loss 1.340342 | Val Loss 4.207129 | Val CCC 0.259040 | Val Acc 0.527273 | 1.36s
Epoch 13/20 | Train Loss 1.449204 | Val Loss 2.732198 | Val CCC 0.312909 | Val Acc 0.545455 | 1.34s
Epoch 14/20 | Train Loss 1.320419 | Val Loss 2.601784 | Val CCC 0.391465 | Val Acc 0.490909 | 1.37s
Epoch 15/20 | Train Loss 1.310939 | Val Loss 2.931595 | Val CCC 0.382022 | Val Acc 0.490909 | 1.36s
Epoch 16/20 | Train Loss 1.585217 | Val Loss 3.334543 | Val CCC 0.223567 | Val Acc 0.363636 | 1.36s
Epoch 17/20 | Train Loss 1.489377 | Val Loss 2.683524 | Val CCC 0.320988 | Val Acc 0.490909 | 1.36s
Epoch 18/20 | Train Loss 1.311443 | Val Loss 2.947797 | Val CCC 0.337349 | Val Acc 0.545455 | 1.34s
Epoch 19/20 | Train Loss 1.364021 | Val Loss 3.103920 | Val CCC 0.332929 | Val Acc 0.527273 | 1.34s
Epoch 20/20 | Train Loss 1.296106 | Val Loss 3.371960 | Val CCC 0.288410 | Val Acc 0.581818 | 1.34s
====================================================================================================
训练完成：Seed=100，Q1
最佳Val Loss：2.432544，Epoch=11
最佳Val CCC：0.503817，Epoch=8
Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 8
Audio保存Epoch： 43
Video保存Epoch： 2
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
====================================================================================================
开始训练T+A+V：Seed=100，Q2，PHQ_8Depressed
类别数量： [68, 63, 18, 14]
====================================================================================================
Epoch 01/20 | Train Loss 2.165653 | Val Loss 2.401168 | Val CCC 0.455296 | Val Acc 0.454545 | 1.36s
Epoch 02/20 | Train Loss 1.871801 | Val Loss 2.222372 | Val CCC 0.461224 | Val Acc 0.527273 | 1.35s
Epoch 03/20 | Train Loss 1.749648 | Val Loss 1.982298 | Val CCC 0.405090 | Val Acc 0.490909 | 1.36s
Epoch 04/20 | Train Loss 1.689756 | Val Loss 2.392343 | Val CCC 0.485793 | Val Acc 0.527273 | 1.38s
Epoch 05/20 | Train Loss 1.753681 | Val Loss 1.952698 | Val CCC 0.476190 | Val Acc 0.527273 | 1.39s
Epoch 06/20 | Train Loss 1.828065 | Val Loss 2.040151 | Val CCC 0.436433 | Val Acc 0.527273 | 1.36s
Epoch 07/20 | Train Loss 1.617945 | Val Loss 1.923349 | Val CCC 0.506726 | Val Acc 0.545455 | 1.38s
Epoch 08/20 | Train Loss 1.661950 | Val Loss 1.919521 | Val CCC 0.493947 | Val Acc 0.527273 | 1.37s
Epoch 09/20 | Train Loss 1.766257 | Val Loss 2.124823 | Val CCC 0.455046 | Val Acc 0.527273 | 1.37s
Epoch 10/20 | Train Loss 1.758849 | Val Loss 1.942608 | Val CCC 0.434579 | Val Acc 0.472727 | 1.36s
Epoch 11/20 | Train Loss 1.594711 | Val Loss 1.967357 | Val CCC 0.423810 | Val Acc 0.418182 | 1.37s
Epoch 12/20 | Train Loss 1.600372 | Val Loss 2.056039 | Val CCC 0.438438 | Val Acc 0.490909 | 1.36s
Epoch 13/20 | Train Loss 1.519941 | Val Loss 2.078538 | Val CCC 0.222222 | Val Acc 0.400000 | 1.37s
Epoch 14/20 | Train Loss 1.800554 | Val Loss 2.025127 | Val CCC 0.511485 | Val Acc 0.454545 | 1.37s
Epoch 15/20 | Train Loss 1.819555 | Val Loss 2.116574 | Val CCC 0.521739 | Val Acc 0.545455 | 1.37s
Epoch 16/20 | Train Loss 1.681523 | Val Loss 1.970436 | Val CCC 0.459016 | Val Acc 0.509091 | 1.37s
Epoch 17/20 | Train Loss 1.649455 | Val Loss 1.953475 | Val CCC 0.510593 | Val Acc 0.509091 | 1.36s
Epoch 18/20 | Train Loss 1.616380 | Val Loss 1.951387 | Val CCC 0.446043 | Val Acc 0.509091 | 1.36s
Epoch 19/20 | Train Loss 1.553220 | Val Loss 2.011564 | Val CCC 0.529718 | Val Acc 0.563636 | 1.38s
Epoch 20/20 | Train Loss 1.548775 | Val Loss 1.996815 | Val CCC 0.466245 | Val Acc 0.527273 | 1.38s
====================================================================================================
训练完成：Seed=100，Q2
最佳Val Loss：1.919521，Epoch=8
最佳Val CCC：0.529718，Epoch=19
Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 13
Audio保存Epoch： 15
Video保存Epoch： 9
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
====================================================================================================
开始训练T+A+V：Seed=100，Q3，PHQ_8Sleep
类别数量： [69, 40, 27, 27]
====================================================================================================
Epoch 01/20 | Train Loss 2.346328 | Val Loss 3.001645 | Val CCC 0.366855 | Val Acc 0.381818 | 1.37s
Epoch 02/20 | Train Loss 1.990204 | Val Loss 2.537125 | Val CCC 0.346253 | Val Acc 0.400000 | 1.35s
Epoch 03/20 | Train Loss 1.913052 | Val Loss 2.318458 | Val CCC 0.423018 | Val Acc 0.490909 | 1.36s
Epoch 04/20 | Train Loss 1.861760 | Val Loss 2.753398 | Val CCC 0.347120 | Val Acc 0.381818 | 1.38s
Epoch 05/20 | Train Loss 1.811163 | Val Loss 2.482032 | Val CCC 0.341367 | Val Acc 0.400000 | 1.38s
Epoch 06/20 | Train Loss 1.598365 | Val Loss 2.396184 | Val CCC 0.387187 | Val Acc 0.436364 | 1.37s
Epoch 07/20 | Train Loss 1.839278 | Val Loss 2.240718 | Val CCC 0.360902 | Val Acc 0.436364 | 1.37s
Epoch 08/20 | Train Loss 1.667317 | Val Loss 2.334961 | Val CCC 0.359638 | Val Acc 0.472727 | 1.36s
Epoch 09/20 | Train Loss 1.594497 | Val Loss 2.698393 | Val CCC 0.334574 | Val Acc 0.400000 | 1.36s
Epoch 10/20 | Train Loss 1.737323 | Val Loss 2.434396 | Val CCC 0.355410 | Val Acc 0.454545 | 1.36s
Epoch 11/20 | Train Loss 1.776763 | Val Loss 2.300732 | Val CCC 0.314703 | Val Acc 0.472727 | 1.37s
Epoch 12/20 | Train Loss 1.704171 | Val Loss 2.775294 | Val CCC 0.370073 | Val Acc 0.381818 | 1.47s
Epoch 13/20 | Train Loss 1.597763 | Val Loss 2.228409 | Val CCC 0.370754 | Val Acc 0.472727 | 1.40s
Epoch 14/20 | Train Loss 1.545616 | Val Loss 2.343888 | Val CCC 0.338167 | Val Acc 0.472727 | 1.54s
Epoch 15/20 | Train Loss 1.582480 | Val Loss 2.374241 | Val CCC 0.328378 | Val Acc 0.472727 | 1.41s
Epoch 16/20 | Train Loss 1.660752 | Val Loss 2.881906 | Val CCC 0.365291 | Val Acc 0.400000 | 1.44s
Epoch 17/20 | Train Loss 1.595150 | Val Loss 2.438994 | Val CCC 0.279476 | Val Acc 0.454545 | 1.35s
Epoch 18/20 | Train Loss 1.490452 | Val Loss 2.596073 | Val CCC 0.370709 | Val Acc 0.472727 | 1.33s
Epoch 19/20 | Train Loss 1.759204 | Val Loss 2.895897 | Val CCC 0.300518 | Val Acc 0.400000 | 1.34s
Epoch 20/20 | Train Loss 1.611320 | Val Loss 2.395025 | Val CCC 0.304749 | Val Acc 0.490909 | 1.33s
====================================================================================================
训练完成：Seed=100，Q3
最佳Val Loss：2.228409，Epoch=13
最佳Val CCC：0.423018，Epoch=3
Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 8
Audio保存Epoch： 47
Video保存Epoch： 6
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
====================================================================================================
开始训练T+A+V：Seed=100，Q4，PHQ_8Tired
类别数量： [50, 65, 27, 21]
====================================================================================================
Epoch 01/20 | Train Loss 2.409517 | Val Loss 2.226434 | Val CCC 0.423260 | Val Acc 0.272727 | 1.37s
Epoch 02/20 | Train Loss 2.084653 | Val Loss 2.207460 | Val CCC 0.302385 | Val Acc 0.345455 | 1.39s
Epoch 03/20 | Train Loss 2.008375 | Val Loss 2.291484 | Val CCC 0.380398 | Val Acc 0.381818 | 1.41s
Epoch 04/20 | Train Loss 2.162880 | Val Loss 2.152463 | Val CCC 0.382699 | Val Acc 0.363636 | 1.38s
Epoch 05/20 | Train Loss 2.036357 | Val Loss 2.217993 | Val CCC 0.229598 | Val Acc 0.327273 | 1.41s
Epoch 06/20 | Train Loss 1.932614 | Val Loss 2.119654 | Val CCC 0.382699 | Val Acc 0.363636 | 1.37s
Epoch 07/20 | Train Loss 1.945780 | Val Loss 2.137074 | Val CCC 0.322155 | Val Acc 0.327273 | 1.38s
Epoch 08/20 | Train Loss 1.866076 | Val Loss 2.099699 | Val CCC 0.374210 | Val Acc 0.345455 | 1.37s
Epoch 09/20 | Train Loss 1.910193 | Val Loss 2.220951 | Val CCC 0.288722 | Val Acc 0.327273 | 1.44s
Epoch 10/20 | Train Loss 1.954086 | Val Loss 2.134646 | Val CCC 0.482218 | Val Acc 0.400000 | 1.80s
Epoch 11/20 | Train Loss 1.995310 | Val Loss 2.518571 | Val CCC 0.288722 | Val Acc 0.327273 | 1.39s
Epoch 12/20 | Train Loss 1.837575 | Val Loss 2.207658 | Val CCC 0.285302 | Val Acc 0.290909 | 1.37s
Epoch 13/20 | Train Loss 1.901649 | Val Loss 2.156453 | Val CCC 0.475282 | Val Acc 0.400000 | 1.39s
Epoch 14/20 | Train Loss 1.831557 | Val Loss 2.158004 | Val CCC 0.350161 | Val Acc 0.309091 | 1.41s
Epoch 15/20 | Train Loss 1.784854 | Val Loss 2.190715 | Val CCC 0.241268 | Val Acc 0.309091 | 1.41s
Epoch 16/20 | Train Loss 1.850330 | Val Loss 2.196126 | Val CCC 0.398725 | Val Acc 0.381818 | 1.41s
Epoch 17/20 | Train Loss 1.791905 | Val Loss 2.439211 | Val CCC 0.354262 | Val Acc 0.327273 | 1.38s
Epoch 18/20 | Train Loss 1.807904 | Val Loss 2.247032 | Val CCC 0.354027 | Val Acc 0.363636 | 1.37s
Epoch 19/20 | Train Loss 1.764452 | Val Loss 2.672371 | Val CCC 0.342013 | Val Acc 0.345455 | 1.39s
Epoch 20/20 | Train Loss 1.924138 | Val Loss 2.378622 | Val CCC 0.352941 | Val Acc 0.381818 | 1.37s
====================================================================================================
训练完成：Seed=100，Q4
最佳Val Loss：2.099699，Epoch=8
最佳Val CCC：0.482218，Epoch=10
Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 11
Audio保存Epoch： 7
Video保存Epoch： 3
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
====================================================================================================
开始训练T+A+V：Seed=100，Q5，PHQ_8Appetite
类别数量： [77, 42, 24, 20]
====================================================================================================
Epoch 01/20 | Train Loss 2.323378 | Val Loss 2.624781 | Val CCC 0.244090 | Val Acc 0.327273 | 1.38s
Epoch 02/20 | Train Loss 2.133036 | Val Loss 2.178924 | Val CCC 0.406660 | Val Acc 0.436364 | 1.39s
Epoch 03/20 | Train Loss 1.862767 | Val Loss 2.331067 | Val CCC 0.390769 | Val Acc 0.418182 | 1.38s
Epoch 04/20 | Train Loss 1.935343 | Val Loss 3.015046 | Val CCC 0.402056 | Val Acc 0.436364 | 1.39s
Epoch 05/20 | Train Loss 1.951218 | Val Loss 2.928348 | Val CCC 0.355972 | Val Acc 0.400000 | 1.38s
Epoch 06/20 | Train Loss 1.798939 | Val Loss 2.642144 | Val CCC 0.386210 | Val Acc 0.418182 | 1.37s
Epoch 07/20 | Train Loss 1.760273 | Val Loss 2.491998 | Val CCC 0.389932 | Val Acc 0.436364 | 1.36s
Epoch 08/20 | Train Loss 1.726055 | Val Loss 2.843224 | Val CCC 0.389259 | Val Acc 0.436364 | 1.37s
Epoch 09/20 | Train Loss 1.656330 | Val Loss 2.768842 | Val CCC 0.426366 | Val Acc 0.472727 | 1.36s
Epoch 10/20 | Train Loss 1.665809 | Val Loss 2.839170 | Val CCC 0.436358 | Val Acc 0.436364 | 1.38s
Epoch 11/20 | Train Loss 1.741868 | Val Loss 2.344340 | Val CCC 0.463069 | Val Acc 0.509091 | 1.37s
Epoch 12/20 | Train Loss 1.658435 | Val Loss 2.571246 | Val CCC 0.467883 | Val Acc 0.418182 | 1.38s
Epoch 13/20 | Train Loss 1.686732 | Val Loss 3.596082 | Val CCC 0.419331 | Val Acc 0.400000 | 1.38s
Epoch 14/20 | Train Loss 1.671319 | Val Loss 2.615258 | Val CCC 0.507095 | Val Acc 0.509091 | 1.36s
Epoch 15/20 | Train Loss 1.664209 | Val Loss 2.917939 | Val CCC 0.452845 | Val Acc 0.472727 | 1.37s
Epoch 16/20 | Train Loss 1.632321 | Val Loss 3.527434 | Val CCC 0.464231 | Val Acc 0.472727 | 1.36s
Epoch 17/20 | Train Loss 1.639220 | Val Loss 3.850418 | Val CCC 0.446478 | Val Acc 0.436364 | 1.38s
Epoch 18/20 | Train Loss 1.811888 | Val Loss 4.262056 | Val CCC 0.441381 | Val Acc 0.418182 | 1.37s
Epoch 19/20 | Train Loss 1.798590 | Val Loss 2.471257 | Val CCC 0.388248 | Val Acc 0.418182 | 1.37s
Epoch 20/20 | Train Loss 1.749115 | Val Loss 2.096761 | Val CCC 0.428802 | Val Acc 0.509091 | 1.35s
====================================================================================================
训练完成：Seed=100，Q5
最佳Val Loss：2.096761，Epoch=20
最佳Val CCC：0.507095，Epoch=14
Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 13
Audio保存Epoch： 47
Video保存Epoch： 3
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
====================================================================================================
开始训练T+A+V：Seed=100，Q6，PHQ_8Failure
类别数量： [76, 44, 24, 19]
====================================================================================================
Epoch 01/20 | Train Loss 2.170129 | Val Loss 2.151131 | Val CCC 0.362617 | Val Acc 0.400000 | 1.38s
Epoch 02/20 | Train Loss 1.849698 | Val Loss 2.694646 | Val CCC 0.263347 | Val Acc 0.436364 | 1.38s
Epoch 03/20 | Train Loss 1.734763 | Val Loss 2.512760 | Val CCC 0.362645 | Val Acc 0.454545 | 1.39s
Epoch 04/20 | Train Loss 1.665078 | Val Loss 2.364631 | Val CCC 0.289123 | Val Acc 0.400000 | 1.40s
Epoch 05/20 | Train Loss 1.684534 | Val Loss 2.293218 | Val CCC 0.402306 | Val Acc 0.490909 | 1.38s
Epoch 06/20 | Train Loss 1.701495 | Val Loss 2.735054 | Val CCC 0.304736 | Val Acc 0.418182 | 1.38s
Epoch 07/20 | Train Loss 1.512652 | Val Loss 2.165728 | Val CCC 0.331017 | Val Acc 0.454545 | 1.36s
Epoch 08/20 | Train Loss 1.562574 | Val Loss 2.403250 | Val CCC 0.324910 | Val Acc 0.345455 | 1.36s
Epoch 09/20 | Train Loss 1.509363 | Val Loss 2.084786 | Val CCC 0.394218 | Val Acc 0.454545 | 1.35s
Epoch 10/20 | Train Loss 1.523776 | Val Loss 2.206108 | Val CCC 0.274848 | Val Acc 0.381818 | 1.36s
Epoch 11/20 | Train Loss 1.441418 | Val Loss 2.278532 | Val CCC 0.448496 | Val Acc 0.472727 | 1.37s
Epoch 12/20 | Train Loss 1.552154 | Val Loss 2.132710 | Val CCC 0.367816 | Val Acc 0.436364 | 1.37s
Epoch 13/20 | Train Loss 1.383223 | Val Loss 2.444910 | Val CCC 0.385003 | Val Acc 0.436364 | 1.37s
Epoch 14/20 | Train Loss 1.330050 | Val Loss 2.373139 | Val CCC 0.391221 | Val Acc 0.436364 | 1.37s
Epoch 15/20 | Train Loss 1.344039 | Val Loss 2.275838 | Val CCC 0.375546 | Val Acc 0.436364 | 1.36s
Epoch 16/20 | Train Loss 1.634652 | Val Loss 2.176691 | Val CCC 0.346904 | Val Acc 0.418182 | 1.36s
Epoch 17/20 | Train Loss 1.358378 | Val Loss 2.479815 | Val CCC 0.368594 | Val Acc 0.454545 | 1.37s
Epoch 18/20 | Train Loss 1.480065 | Val Loss 2.472867 | Val CCC 0.362934 | Val Acc 0.490909 | 1.37s
Epoch 19/20 | Train Loss 1.479614 | Val Loss 2.091664 | Val CCC 0.358066 | Val Acc 0.418182 | 1.38s
Epoch 20/20 | Train Loss 1.286027 | Val Loss 2.380926 | Val CCC 0.389115 | Val Acc 0.436364 | 1.39s
====================================================================================================
训练完成：Seed=100，Q6
最佳Val Loss：2.084786，Epoch=9
最佳Val CCC：0.448496，Epoch=11
Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 12
Audio保存Epoch： 4
Video保存Epoch： 2
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
====================================================================================================
开始训练T+A+V：Seed=100，Q7，PHQ_8Concentrating
类别数量： [93, 37, 14, 19]
====================================================================================================
Epoch 01/20 | Train Loss 2.397668 | Val Loss 2.734193 | Val CCC 0.119416 | Val Acc 0.363636 | 1.53s
Epoch 02/20 | Train Loss 1.858301 | Val Loss 2.340278 | Val CCC 0.334620 | Val Acc 0.509091 | 1.48s
Epoch 03/20 | Train Loss 1.497534 | Val Loss 3.462857 | Val CCC 0.468496 | Val Acc 0.563636 | 1.34s
Epoch 04/20 | Train Loss 2.265517 | Val Loss 2.457304 | Val CCC 0.491814 | Val Acc 0.600000 | 1.35s
Epoch 05/20 | Train Loss 1.658743 | Val Loss 2.454841 | Val CCC 0.432258 | Val Acc 0.600000 | 1.35s
Epoch 06/20 | Train Loss 1.501041 | Val Loss 2.304448 | Val CCC 0.454122 | Val Acc 0.381818 | 1.33s
Epoch 07/20 | Train Loss 1.474932 | Val Loss 2.407448 | Val CCC 0.449213 | Val Acc 0.454545 | 1.33s
Epoch 08/20 | Train Loss 1.484097 | Val Loss 2.076249 | Val CCC 0.395928 | Val Acc 0.509091 | 1.33s
Epoch 09/20 | Train Loss 1.397809 | Val Loss 2.278036 | Val CCC 0.331307 | Val Acc 0.545455 | 1.34s
Epoch 10/20 | Train Loss 1.617528 | Val Loss 3.046253 | Val CCC 0.469149 | Val Acc 0.563636 | 1.34s
Epoch 11/20 | Train Loss 1.610022 | Val Loss 2.226083 | Val CCC 0.463415 | Val Acc 0.418182 | 1.33s
Epoch 12/20 | Train Loss 1.496672 | Val Loss 2.090744 | Val CCC 0.421317 | Val Acc 0.527273 | 1.33s
Epoch 13/20 | Train Loss 1.685602 | Val Loss 2.368414 | Val CCC 0.426230 | Val Acc 0.581818 | 1.34s
Epoch 14/20 | Train Loss 1.355352 | Val Loss 2.094575 | Val CCC 0.447741 | Val Acc 0.418182 | 1.36s
Epoch 15/20 | Train Loss 1.318821 | Val Loss 2.276733 | Val CCC 0.448622 | Val Acc 0.636364 | 1.36s
Epoch 16/20 | Train Loss 1.212981 | Val Loss 3.120291 | Val CCC 0.489350 | Val Acc 0.600000 | 1.38s
Epoch 17/20 | Train Loss 1.283283 | Val Loss 2.240943 | Val CCC 0.503979 | Val Acc 0.545455 | 1.37s
Epoch 18/20 | Train Loss 1.441491 | Val Loss 2.229649 | Val CCC 0.452144 | Val Acc 0.472727 | 1.37s
Epoch 19/20 | Train Loss 1.411881 | Val Loss 2.363160 | Val CCC 0.446498 | Val Acc 0.381818 | 1.37s
Epoch 20/20 | Train Loss 1.486376 | Val Loss 2.317326 | Val CCC 0.430688 | Val Acc 0.436364 | 1.38s
====================================================================================================
训练完成：Seed=100，Q7
最佳Val Loss：2.076249，Epoch=8
最佳Val CCC：0.503979，Epoch=17
Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 12
Audio保存Epoch： 12
Video保存Epoch： 9
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
====================================================================================================
开始训练T+A+V：Seed=100，Q8，PHQ_8Moving
类别数量： [128, 20, 9, 6]
====================================================================================================
Epoch 01/20 | Train Loss 1.663780 | Val Loss 3.876034 | Val CCC 0.190766 | Val Acc 0.581818 | 1.35s
Epoch 02/20 | Train Loss 1.392694 | Val Loss 5.237925 | Val CCC 0.044944 | Val Acc 0.581818 | 1.34s
Epoch 03/20 | Train Loss 1.400785 | Val Loss 2.559386 | Val CCC 0.265403 | Val Acc 0.545455 | 1.34s
Epoch 04/20 | Train Loss 1.159135 | Val Loss 4.477334 | Val CCC 0.122029 | Val Acc 0.600000 | 1.33s
Epoch 05/20 | Train Loss 1.415221 | Val Loss 3.196399 | Val CCC 0.250097 | Val Acc 0.527273 | 1.33s
Epoch 06/20 | Train Loss 1.252092 | Val Loss 4.658992 | Val CCC 0.163407 | Val Acc 0.618182 | 1.35s
Epoch 07/20 | Train Loss 1.221485 | Val Loss 3.005365 | Val CCC 0.322002 | Val Acc 0.563636 | 1.34s
Epoch 08/20 | Train Loss 1.474013 | Val Loss 4.439156 | Val CCC 0.295206 | Val Acc 0.618182 | 1.34s
Epoch 09/20 | Train Loss 1.407472 | Val Loss 3.573303 | Val CCC 0.266667 | Val Acc 0.581818 | 1.35s

In [85]:
for seed in SEEDS:
    best_loss_flags = []
    best_ccc_flags = []
    last_flags = []
    history_flags = []

    for question_index in range(8):
        question_dir = TAV_CHECKPOINT_ROOT / f"seed_{seed}" / f"question_{question_index + 1}"
        best_loss_flags.append((question_dir / "best_loss.pt").exists())
        best_ccc_flags.append((question_dir / "best_ccc.pt").exists())
        last_flags.append((question_dir / "last.pt").exists())
        history_flags.append((question_dir / "history.csv").exists())

    print("=" * 70)
    print("Seed：", seed)
    print("问题数量：", len(best_ccc_flags))
    print("Best Loss全部存在：", all(best_loss_flags))
    print("Best CCC全部存在：", all(best_ccc_flags))
    print("Last全部存在：", all(last_flags))
    print("History全部存在：", all(history_flags))

======================================================================
Seed： 42
问题数量： 8
Best Loss全部存在： True
Best CCC全部存在： True
Last全部存在： True
History全部存在： True
======================================================================
Seed： 100
问题数量： 8
Best Loss全部存在： True
Best CCC全部存在： True
Last全部存在： True
History全部存在： True
======================================================================
Seed： 1234
问题数量： 8
Best Loss全部存在： True
Best CCC全部存在： True
Last全部存在： True
History全部存在： True

In [86]:
tav_seed100_validation_result = evaluate_tav_seed_on_validation(seed=100)
tav_seed1234_validation_result = evaluate_tav_seed_on_validation(seed=1234)
tav_validation_results = [tav_seed42_validation_result, tav_seed100_validation_result, tav_seed1234_validation_result]
tav_validation_rows = []

for result in tav_validation_results:
    row = {}
    row["Seed"] = result["seed"]
    row["Sample_Count"] = result["sample_count"]
    row["CCC"] = result["ccc"]
    row["RMSE"] = result["rmse"]
    row["MAE"] = result["mae"]
    row["Exact_Accuracy"] = result["exact_accuracy"]
    tav_validation_rows.append(row)

tav_validation_seed_df = pd.DataFrame(tav_validation_rows)
display(tav_validation_seed_df)

Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 10
Audio保存Epoch： 8
Video保存Epoch： 14
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
Q1 | Epoch 08 | 样本 55 | 参数完整 True
Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 8
Audio保存Epoch： 43
Video保存Epoch： 2
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
Q2 | Epoch 19 | 样本 55 | 参数完整 True
Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 13
Audio保存Epoch： 15
Video保存Epoch： 9
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
Q3 | Epoch 03 | 样本 55 | 参数完整 True
Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 8
Audio保存Epoch： 47
Video保存Epoch： 6
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
Q4 | Epoch 10 | 样本 55 | 参数完整 True
Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 11
Audio保存Epoch： 7
Video保存Epoch： 3
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
Q5 | Epoch 14 | 样本 55 | 参数完整 True
Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 13
Audio保存Epoch： 47
Video保存Epoch： 3
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
Q6 | Epoch 11 | 样本 55 | 参数完整 True
Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 12
Audio保存Epoch： 4
Video保存Epoch： 2
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
Q7 | Epoch 17 | 样本 55 | 参数完整 True
Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 12
Audio保存Epoch： 12
Video保存Epoch： 9
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
Q8 | Epoch 07 | 样本 55 | 参数完整 True
Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 7
Audio保存Epoch： 18
Video保存Epoch： 15
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
Q1 | Epoch 03 | 样本 55 | 参数完整 True
Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 12
Audio保存Epoch： 11
Video保存Epoch： 2
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
Q2 | Epoch 01 | 样本 55 | 参数完整 True
Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 7
Audio保存Epoch： 14
Video保存Epoch： 13
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
Q3 | Epoch 07 | 样本 55 | 参数完整 True
Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 8
Audio保存Epoch： 31
Video保存Epoch： 9
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
Q4 | Epoch 02 | 样本 55 | 参数完整 True
Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 16
Audio保存Epoch： 22
Video保存Epoch： 2
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
Q5 | Epoch 16 | 样本 55 | 参数完整 True
Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 10
Audio保存Epoch： 48
Video保存Epoch： 42
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
Q6 | Epoch 03 | 样本 55 | 参数完整 True
Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 12
Audio保存Epoch： 4
Video保存Epoch： 1
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
Q7 | Epoch 18 | 样本 55 | 参数完整 True
Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 1
Audio保存Epoch： 21
Video保存Epoch： 5
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
Q8 | Epoch 17 | 样本 55 | 参数完整 True

   Seed  Sample_Count       CCC      RMSE       MAE  Exact_Accuracy
0    42            55  0.710736  4.297991  3.309091        0.072727
1   100            55  0.655306  4.494441  3.472727        0.072727
2  1234            55  0.676513  4.498485  3.654545        0.072727

In [87]:
tav_validation_summary_rows = []

for metric_name in ["CCC", "RMSE", "MAE", "Exact_Accuracy"]:
    row = {}
    row["Metric"] = metric_name
    row["Mean"] = tav_validation_seed_df[metric_name].mean()
    row["Std"] = tav_validation_seed_df[metric_name].std(ddof=1)
    tav_validation_summary_rows.append(row)

tav_validation_summary_df = pd.DataFrame(tav_validation_summary_rows)
display(tav_validation_summary_df)

           Metric      Mean       Std
0             CCC  0.680852  0.027969
1            RMSE  4.430306  0.114606
2             MAE  3.478788  0.172807
3  Exact_Accuracy  0.072727  0.000000

In [88]:
tav_validation_seed_path = TAV_CHECKPOINT_ROOT / "three_seed_validation_results.csv"
tav_validation_summary_path = TAV_CHECKPOINT_ROOT / "three_seed_validation_summary.csv"
tav_validation_seed_df.to_csv(tav_validation_seed_path, index=False)
tav_validation_summary_df.to_csv(tav_validation_summary_path, index=False)
print("逐Seed验证结果：", tav_validation_seed_path)
print("三Seed验证汇总：", tav_validation_summary_path)

逐Seed验证结果： /workspace/E-DAIC/checkpoints/phq8_text_audio_video_nopostzero/three_seed_validation_results.csv
三Seed验证汇总： /workspace/E-DAIC/checkpoints/phq8_text_audio_video_nopostzero/three_seed_validation_summary.csv

In [89]:
class TextAudioVideoPHQ8TestDataset(Dataset):
    def __init__(self, metadata_df):
        super().__init__()
        self.metadata_df = metadata_df.reset_index(drop=True).copy()

        if "PHQ8_Score" in self.metadata_df.columns:
            score_column = "PHQ8_Score"
        elif "PHQ_Score" in self.metadata_df.columns:
            score_column = "PHQ_Score"
        else:
            raise KeyError(f"测试数据缺少PHQ总分字段，现有字段：{self.metadata_df.columns.tolist()}")

        self.participant_ids = self.metadata_df["Participant_ID"].astype(int).tolist()
        self.true_totals = torch.tensor(self.metadata_df[score_column].to_numpy(), dtype=torch.long)
        text_feature_list = []
        text_mask_list = []
        audio_feature_list = []
        audio_mask_list = []
        video_feature_list = []
        video_mask_list = []

        for index, participant_id in enumerate(self.participant_ids):
            text_features, text_mask, audio_features, audio_mask, video_features, video_mask = load_text_audio_video_cache(participant_id)
            text_feature_list.append(text_features)
            text_mask_list.append(text_mask)
            audio_feature_list.append(audio_features)
            audio_mask_list.append(audio_mask)
            video_feature_list.append(video_features)
            video_mask_list.append(video_mask)

            if (index + 1) % 20 == 0 or index + 1 == len(self.participant_ids):
                print(f"test Dataset加载进度：{index + 1}/{len(self.participant_ids)}")

        self.text_features = torch.stack(text_feature_list, dim=0)
        self.text_masks = torch.stack(text_mask_list, dim=0)
        self.audio_features = torch.stack(audio_feature_list, dim=0)
        self.audio_masks = torch.stack(audio_mask_list, dim=0)
        self.video_features = torch.stack(video_feature_list, dim=0)
        self.video_masks = torch.stack(video_mask_list, dim=0)

        if self.text_features.shape != (len(self), MAX_TURNS, TEXT_FEATURE_DIM):
            raise RuntimeError(f"测试文本特征形状错误：{self.text_features.shape}")

        if self.audio_features.shape != (len(self), MAX_TURNS, AUDIO_FEATURE_DIM):
            raise RuntimeError(f"测试语音特征形状错误：{self.audio_features.shape}")

        if self.video_features.shape != (len(self), MAX_TURNS, VIDEO_FEATURE_DIM):
            raise RuntimeError(f"测试视频特征形状错误：{self.video_features.shape}")

    def __len__(self):
        return len(self.participant_ids)

    def __getitem__(self, index):
        participant_id = torch.tensor(self.participant_ids[index], dtype=torch.long)
        return self.text_features[index], self.text_masks[index], self.audio_features[index], self.audio_masks[index], self.video_features[index], self.video_masks[index], self.true_totals[index], participant_id

In [91]:
test_metadata_df = pd.read_csv(TEST_SPLIT_PATH)
test_metadata_df["Participant_ID"] = test_metadata_df["Participant_ID"].astype(int)
print("测试集路径：", TEST_SPLIT_PATH)
print("测试参与者数量：", len(test_metadata_df))
print("测试集字段：", test_metadata_df.columns.tolist())
print("参与者是否唯一：", test_metadata_df["Participant_ID"].is_unique)
print("总分是否缺失：", test_metadata_df["PHQ_Score"].isna().any())

测试集路径： /workspace/E-DAIC/splits/test_split.csv
测试参与者数量： 56
测试集字段： ['Participant_ID', 'Gender', 'PHQ_Binary', 'PHQ_Score', 'PCL-C (PTSD)', 'PTSD Severity']
参与者是否唯一： True
总分是否缺失： False

In [92]:
tav_test_dataset = TextAudioVideoPHQ8TestDataset(test_metadata_df)
tav_test_loader = DataLoader(tav_test_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=0, drop_last=False)
test_batch = next(iter(tav_test_loader))
test_text_features, test_text_masks, test_audio_features, test_audio_masks, test_video_features, test_video_masks, test_true_totals, test_participant_ids = test_batch
print("测试参与者数量：", len(tav_test_dataset))
print("测试批次数：", len(tav_test_loader))
print("测试文本特征：", test_text_features.shape)
print("测试文本Mask：", test_text_masks.shape)
print("测试语音特征：", test_audio_features.shape)
print("测试语音Mask：", test_audio_masks.shape)
print("测试视频特征：", test_video_features.shape)
print("测试视频Mask：", test_video_masks.shape)
print("测试真实总分：", test_true_totals.shape)
print("测试参与者：", test_participant_ids)
print("文本全部有限：", torch.isfinite(test_text_features).all().item())
print("语音全部有限：", torch.isfinite(test_audio_features).all().item())
print("视频全部有限：", torch.isfinite(test_video_features).all().item())
print("真实总分范围：", test_true_totals.min().item(), "～", test_true_totals.max().item())

test Dataset加载进度：20/56
test Dataset加载进度：40/56
test Dataset加载进度：56/56
测试参与者数量： 56
测试批次数： 6
测试文本特征： torch.Size([10, 120, 768])
测试文本Mask： torch.Size([10, 120])
测试语音特征： torch.Size([10, 120, 23])
测试语音Mask： torch.Size([10, 120])
测试视频特征： torch.Size([10, 120, 2048])
测试视频Mask： torch.Size([10, 120])
测试真实总分： torch.Size([10])
测试参与者： tensor([600, 602, 604, 605, 606, 607, 609, 615, 618, 619])
文本全部有限： True
语音全部有限： True
视频全部有限： True
真实总分范围： 0 ～ 13

In [93]:
print("完整测试集真实总分范围：", tav_test_dataset.true_totals.min().item(), "～", tav_test_dataset.true_totals.max().item())

完整测试集真实总分范围： 0 ～ 22

In [94]:
def evaluate_tav_seed_on_test(seed):
    question_prediction_list = []
    reference_true_totals = None
    reference_participant_ids = None

    for question_index in range(8):
        checkpoint_path = TAV_CHECKPOINT_ROOT / f"seed_{seed}" / f"question_{question_index + 1}" / "best_ccc.pt"
        checkpoint = torch.load(checkpoint_path, map_location="cpu", weights_only=False)
        loaded_items = load_pretrained_tav_encoders(question_index=question_index, seed=seed)
        text_encoder = loaded_items[0]
        audio_encoder = loaded_items[1]
        video_encoder = loaded_items[2]
        model = TextAudioVideoQuestMF(text_encoder, audio_encoder, video_encoder).to(device)
        load_result = model.load_state_dict(checkpoint["model_state_dict"], strict=True)
        model.eval()
        prediction_chunks = []
        true_total_chunks = []
        participant_id_chunks = []

        with torch.no_grad():
            for batch in tav_test_loader:
                text_features, text_masks, audio_features, audio_masks, video_features, video_masks, true_totals, participant_ids = batch
                logits = model(text_features.to(device), text_masks.to(device), audio_features.to(device), audio_masks.to(device), video_features.to(device), video_masks.to(device))
                predictions = torch.argmax(logits, dim=1).cpu()
                prediction_chunks.append(predictions)
                true_total_chunks.append(true_totals.cpu())
                participant_id_chunks.append(participant_ids.cpu())

        question_predictions = torch.cat(prediction_chunks, dim=0)
        current_true_totals = torch.cat(true_total_chunks, dim=0)
        current_participant_ids = torch.cat(participant_id_chunks, dim=0)
        question_prediction_list.append(question_predictions)

        if reference_true_totals is None:
            reference_true_totals = current_true_totals
            reference_participant_ids = current_participant_ids
        else:
            assert torch.equal(reference_true_totals, current_true_totals)
            assert torch.equal(reference_participant_ids, current_participant_ids)

        parameters_complete = len(load_result.missing_keys) == 0 and len(load_result.unexpected_keys) == 0
        print(f"Seed {seed} | Q{question_index + 1} | Epoch {checkpoint['epoch']:02d} | 样本 {len(question_predictions)} | 参数完整 {parameters_complete}")
        del model
        gc.collect()

        if torch.cuda.is_available():
            torch.cuda.empty_cache()

    predicted_question_matrix = torch.stack(question_prediction_list, dim=1)
    predicted_totals = predicted_question_matrix.sum(dim=1)
    total_ccc = float(calculate_ccc(predicted_totals, reference_true_totals))
    total_rmse = float(torch.sqrt(torch.mean((predicted_totals.double() - reference_true_totals.double()) ** 2)).item())
    total_mae = float(torch.mean(torch.abs(predicted_totals.double() - reference_true_totals.double())).item())
    exact_accuracy = float(torch.mean((predicted_totals == reference_true_totals).double()).item())
    prediction_df = pd.DataFrame({"Participant_ID": reference_participant_ids.numpy()})

    for question_index in range(8):
        prediction_df[f"Predicted_Q{question_index + 1}"] = predicted_question_matrix[:, question_index].numpy()

    prediction_df["Predicted_Total"] = predicted_totals.numpy()
    prediction_df["True_Total"] = reference_true_totals.numpy()
    prediction_path = TAV_CHECKPOINT_ROOT / f"seed_{seed}_test_predictions_56.csv"
    prediction_df.to_csv(prediction_path, index=False)
    result = {}
    result["seed"] = seed
    result["sample_count"] = len(prediction_df)
    result["ccc"] = total_ccc
    result["rmse"] = total_rmse
    result["mae"] = total_mae
    result["exact_accuracy"] = exact_accuracy
    result["predicted_min"] = int(predicted_totals.min().item())
    result["predicted_max"] = int(predicted_totals.max().item())
    result["true_min"] = int(reference_true_totals.min().item())
    result["true_max"] = int(reference_true_totals.max().item())
    result["prediction_path"] = prediction_path
    return result

In [95]:
tav_test_results = []

for seed in SEEDS:
    seed_result = evaluate_tav_seed_on_test(seed=seed)
    tav_test_results.append(seed_result)
    print("=" * 80)
    print("Seed：", seed)
    print("测试人数：", seed_result["sample_count"])
    print(f"CCC：{seed_result['ccc']:.6f}")
    print(f"RMSE：{seed_result['rmse']:.6f}")
    print(f"MAE：{seed_result['mae']:.6f}")
    print(f"完全相等比例：{seed_result['exact_accuracy']:.6f}")
    print("预测范围：", seed_result["predicted_min"], "～", seed_result["predicted_max"])
    print("真实范围：", seed_result["true_min"], "～", seed_result["true_max"])

Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 13
Audio保存Epoch： 10
Video保存Epoch： 2
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
Seed 42 | Q1 | Epoch 17 | 样本 56 | 参数完整 True
Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 9
Audio保存Epoch： 11
Video保存Epoch： 8
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
Seed 42 | Q2 | Epoch 02 | 样本 56 | 参数完整 True
Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 9
Audio保存Epoch： 14
Video保存Epoch： 14
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
Seed 42 | Q3 | Epoch 13 | 样本 56 | 参数完整 True
Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 11
Audio保存Epoch： 28
Video保存Epoch： 7
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
Seed 42 | Q4 | Epoch 19 | 样本 56 | 参数完整 True
Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 13
Audio保存Epoch： 32
Video保存Epoch： 2
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
Seed 42 | Q5 | Epoch 10 | 样本 56 | 参数完整 True
Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 10
Audio保存Epoch： 45
Video保存Epoch： 24
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
Seed 42 | Q6 | Epoch 02 | 样本 56 | 参数完整 True
Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 15
Audio保存Epoch： 3
Video保存Epoch： 1
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
Seed 42 | Q7 | Epoch 03 | 样本 56 | 参数完整 True
Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 11
Audio保存Epoch： 12
Video保存Epoch： 2
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
Seed 42 | Q8 | Epoch 10 | 样本 56 | 参数完整 True
================================================================================
Seed： 42
测试人数： 56
CCC：0.620632
RMSE：6.037088
MAE：4.589286
完全相等比例：0.142857
预测范围： 0 ～ 23
真实范围： 0 ～ 22
Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 10
Audio保存Epoch： 8
Video保存Epoch： 14
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
Seed 100 | Q1 | Epoch 08 | 样本 56 | 参数完整 True
Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 8
Audio保存Epoch： 43
Video保存Epoch： 2
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
Seed 100 | Q2 | Epoch 19 | 样本 56 | 参数完整 True
Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 13
Audio保存Epoch： 15
Video保存Epoch： 9
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
Seed 100 | Q3 | Epoch 03 | 样本 56 | 参数完整 True
Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 8
Audio保存Epoch： 47
Video保存Epoch： 6
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
Seed 100 | Q4 | Epoch 10 | 样本 56 | 参数完整 True
Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 11
Audio保存Epoch： 7
Video保存Epoch： 3
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
Seed 100 | Q5 | Epoch 14 | 样本 56 | 参数完整 True
Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 13
Audio保存Epoch： 47
Video保存Epoch： 3
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
Seed 100 | Q6 | Epoch 11 | 样本 56 | 参数完整 True
Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 12
Audio保存Epoch： 4
Video保存Epoch： 2
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
Seed 100 | Q7 | Epoch 17 | 样本 56 | 参数完整 True
Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 12
Audio保存Epoch： 12
Video保存Epoch： 9
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
Seed 100 | Q8 | Epoch 07 | 样本 56 | 参数完整 True
================================================================================
Seed： 100
测试人数： 56
CCC：0.637954
RMSE：5.335193
MAE：4.178571
完全相等比例：0.089286
预测范围： 0 ～ 20
真实范围： 0 ～ 22
Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 7
Audio保存Epoch： 18
Video保存Epoch： 15
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
Seed 1234 | Q1 | Epoch 03 | 样本 56 | 参数完整 True
Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 12
Audio保存Epoch： 11
Video保存Epoch： 2
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
Seed 1234 | Q2 | Epoch 01 | 样本 56 | 参数完整 True
Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 7
Audio保存Epoch： 14
Video保存Epoch： 13
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
Seed 1234 | Q3 | Epoch 07 | 样本 56 | 参数完整 True
Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 8
Audio保存Epoch： 31
Video保存Epoch： 9
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
Seed 1234 | Q4 | Epoch 02 | 样本 56 | 参数完整 True
Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 16
Audio保存Epoch： 22
Video保存Epoch： 2
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
Seed 1234 | Q5 | Epoch 16 | 样本 56 | 参数完整 True
Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 10
Audio保存Epoch： 48
Video保存Epoch： 42
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
Seed 1234 | Q6 | Epoch 03 | 样本 56 | 参数完整 True
Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 12
Audio保存Epoch： 4
Video保存Epoch： 1
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
Seed 1234 | Q7 | Epoch 18 | 样本 56 | 参数完整 True
Text Checkpoint验证通过
Audio Checkpoint验证通过
Video Checkpoint验证通过
Text保存Epoch： 1
Audio保存Epoch： 21
Video保存Epoch： 5
Text缺少参数： []
Text多余参数： []
Audio缺少参数： []
Audio多余参数： []
Video缺少参数： []
Video多余参数： []
Seed 1234 | Q8 | Epoch 17 | 样本 56 | 参数完整 True
================================================================================
Seed： 1234
测试人数： 56
CCC：0.684662
RMSE：4.895333
MAE：3.750000
完全相等比例：0.071429
预测范围： 0 ～ 21
真实范围： 0 ～ 22

In [96]:
tav_test_rows = []

for result in tav_test_results:
    row = {}
    row["Seed"] = result["seed"]
    row["Sample_Count"] = result["sample_count"]
    row["CCC"] = result["ccc"]
    row["RMSE"] = result["rmse"]
    row["MAE"] = result["mae"]
    row["Exact_Accuracy"] = result["exact_accuracy"]
    tav_test_rows.append(row)

tav_test_seed_df = pd.DataFrame(tav_test_rows)
display(tav_test_seed_df)

   Seed  Sample_Count       CCC      RMSE       MAE  Exact_Accuracy
0    42            56  0.620632  6.037088  4.589286        0.142857
1   100            56  0.637954  5.335193  4.178571        0.089286
2  1234            56  0.684662  4.895333  3.750000        0.071429

In [97]:
tav_test_summary_rows = []

for metric_name in ["CCC", "RMSE", "MAE", "Exact_Accuracy"]:
    row = {}
    row["Metric"] = metric_name
    row["Mean"] = tav_test_seed_df[metric_name].mean()
    row["Std"] = tav_test_seed_df[metric_name].std(ddof=1)
    tav_test_summary_rows.append(row)

tav_test_summary_df = pd.DataFrame(tav_test_summary_rows)
display(tav_test_summary_df)

           Metric      Mean       Std
0             CCC  0.647749  0.033120
1            RMSE  5.422538  0.575867
2             MAE  4.172619  0.419675
3  Exact_Accuracy  0.101190  0.037173

In [98]:
tav_test_seed_path = TAV_CHECKPOINT_ROOT / "three_seed_test_results_56.csv"
tav_test_summary_path = TAV_CHECKPOINT_ROOT / "three_seed_test_summary_56.csv"
tav_test_seed_df.to_csv(tav_test_seed_path, index=False)
tav_test_summary_df.to_csv(tav_test_summary_path, index=False)
print("逐Seed测试结果：", tav_test_seed_path)
print("三Seed测试汇总：", tav_test_summary_path)

逐Seed测试结果： /workspace/E-DAIC/checkpoints/phq8_text_audio_video_nopostzero/three_seed_test_results_56.csv
三Seed测试汇总： /workspace/E-DAIC/checkpoints/phq8_text_audio_video_nopostzero/three_seed_test_summary_56.csv

In [99]:
VIDEO_EXCLUDED_TEST_ID = 637
tav_candidate55_rows = []

for seed in SEEDS:
    prediction_path = TAV_CHECKPOINT_ROOT / f"seed_{seed}_test_predictions_56.csv"
    prediction_df = pd.read_csv(prediction_path)
    candidate55_df = prediction_df[prediction_df["Participant_ID"] != VIDEO_EXCLUDED_TEST_ID].reset_index(drop=True)
    predicted_totals = torch.tensor(candidate55_df["Predicted_Total"].to_numpy(), dtype=torch.float64)
    true_totals = torch.tensor(candidate55_df["True_Total"].to_numpy(), dtype=torch.float64)
    ccc = float(calculate_ccc(predicted_totals, true_totals))
    rmse = float(torch.sqrt(torch.mean((predicted_totals - true_totals) ** 2)).item())
    mae = float(torch.mean(torch.abs(predicted_totals - true_totals)).item())
    exact_accuracy = float(torch.mean((predicted_totals == true_totals).double()).item())
    row = {}
    row["Seed"] = seed
    row["Sample_Count"] = len(candidate55_df)
    row["Excluded_ID"] = VIDEO_EXCLUDED_TEST_ID
    row["CCC"] = ccc
    row["RMSE"] = rmse
    row["MAE"] = mae
    row["Exact_Accuracy"] = exact_accuracy
    tav_candidate55_rows.append(row)

tav_candidate55_seed_df = pd.DataFrame(tav_candidate55_rows)
display(tav_candidate55_seed_df)

   Seed  Sample_Count  Excluded_ID       CCC      RMSE  MAE  Exact_Accuracy
0    42            55          637  0.609042  6.067799  4.6        0.145455
1   100            55          637  0.623071  5.368257  4.2        0.090909
2  1234            55          637  0.672867  4.937795  3.8        0.072727

In [100]:
tav_candidate55_summary_rows = []

for metric_name in ["CCC", "RMSE", "MAE", "Exact_Accuracy"]:
    row = {}
    row["Metric"] = metric_name
    row["Mean"] = tav_candidate55_seed_df[metric_name].mean()
    row["Std"] = tav_candidate55_seed_df[metric_name].std(ddof=1)
    tav_candidate55_summary_rows.append(row)

tav_candidate55_summary_df = pd.DataFrame(tav_candidate55_summary_rows)
display(tav_candidate55_summary_df)

           Metric      Mean       Std
0             CCC  0.634993  0.033542
1            RMSE  5.457950  0.570316
2             MAE  4.200000  0.400000
3  Exact_Accuracy  0.103030  0.037848

In [101]:
tav_candidate55_seed_path = TAV_CHECKPOINT_ROOT / "three_seed_test_results_candidate55.csv"
tav_candidate55_summary_path = TAV_CHECKPOINT_ROOT / "three_seed_test_summary_candidate55.csv"
tav_candidate55_seed_df.to_csv(tav_candidate55_seed_path, index=False)
tav_candidate55_summary_df.to_csv(tav_candidate55_summary_path, index=False)
print("Candidate55逐Seed结果：", tav_candidate55_seed_path)
print("Candidate55汇总结果：", tav_candidate55_summary_path)

Candidate55逐Seed结果： /workspace/E-DAIC/checkpoints/phq8_text_audio_video_nopostzero/three_seed_test_results_candidate55.csv
Candidate55汇总结果： /workspace/E-DAIC/checkpoints/phq8_text_audio_video_nopostzero/three_seed_test_summary_candidate55.csv