In [1]:
from pathlib import Path
import hashlib
import random
import sys
import time
import librosa
import numpy as np
import pandas as pd
import scipy.io as sio
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader

DATA_DIR = Path("/workspace/E-DAIC/original_data")
SPLIT_DIR = Path("/workspace/E-DAIC/splits")
LABEL_DIR = Path("/workspace/E-DAIC/others")

TRAIN_SPLIT_PATH = SPLIT_DIR / "train_split.csv"
VAL_SPLIT_PATH = SPLIT_DIR / "dev_split.csv"
TEST_SPLIT_PATH = SPLIT_DIR / "test_split.csv"
DETAILED_LABEL_PATH = LABEL_DIR / "Detailed_PHQ8_Labels.csv"

VIDEO_CACHE_DIR = Path("/workspace/E-DAIC/cache/phq8_video_resnet/resnet2048_turnmean_turns120_v1")
VIDEO_CHECKPOINT_ROOT = Path("/workspace/E-DAIC/checkpoints/phq8_video_paperlike")

PHQ8_QUESTION_COLUMNS = ["PHQ_8NoInterest", "PHQ_8Depressed", "PHQ_8Sleep", "PHQ_8Tired", "PHQ_8Appetite", "PHQ_8Failure", "PHQ_8Concentrating", "PHQ_8Moving"]

MAX_TURNS = 120
VIDEO_FEATURE_DIM = 2048
LSTM_HIDDEN_SIZE = 50
ENCODER_OUTPUT_DIM = 100
NUM_CLASSES = 4
ATTENTION_HEADS = 4

BATCH_SIZE = 10
NUM_EPOCHS = 50
LEARNING_RATE = 5e-4
ADAM_EPSILON = 1e-8
WEIGHT_DECAY = 1e-3
MAX_GRAD_NORM = 1.0

ATTENTION_DROPOUT = 0.2
MLP_FIRST_DROPOUT = 0.2
MLP_LAST_DROPOUT = 0.2

ALPHA = 1.0
BETA = 0.5
LOSS_EPSILON = 1e-12
SEEDS = [42, 100, 1234]

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

print("Python：", sys.version.split()[0])
print("PyTorch：", torch.__version__)
print("设备：", device)
print("数据目录存在：", DATA_DIR.exists())
print("训练划分存在：", TRAIN_SPLIT_PATH.exists())
print("验证划分存在：", VAL_SPLIT_PATH.exists())
print("测试划分存在：", TEST_SPLIT_PATH.exists())
print("详细标签存在：", DETAILED_LABEL_PATH.exists())
print("视频缓存目录：", VIDEO_CACHE_DIR)
print("视频Checkpoint目录：", VIDEO_CHECKPOINT_ROOT)

Python： 3.12.3
PyTorch： 2.9.0
设备： cuda:0
数据目录存在： True
训练划分存在： True
验证划分存在： True
测试划分存在： True
详细标签存在： True
视频缓存目录： /workspace/E-DAIC/cache/phq8_video_resnet/resnet2048_turnmean_turns120_v1
视频Checkpoint目录： /workspace/E-DAIC/checkpoints/phq8_video_paperlike

### 读取元数据

In [2]:
train_split_df = pd.read_csv(TRAIN_SPLIT_PATH)
val_split_df = pd.read_csv(VAL_SPLIT_PATH)
test_split_df = pd.read_csv(TEST_SPLIT_PATH)
detailed_label_df = pd.read_csv(DETAILED_LABEL_PATH)

train_metadata_df = train_split_df.merge(detailed_label_df[["Participant_ID"] + PHQ8_QUESTION_COLUMNS], on="Participant_ID", how="left", validate="one_to_one")
val_metadata_df = val_split_df.merge(detailed_label_df[["Participant_ID"] + PHQ8_QUESTION_COLUMNS], on="Participant_ID", how="left", validate="one_to_one")
test_metadata_df = test_split_df.copy()

if train_metadata_df[PHQ8_QUESTION_COLUMNS].isna().any().any():
    raise ValueError("训练集存在缺失的逐题标签")

if val_metadata_df[PHQ8_QUESTION_COLUMNS].isna().any().any():
    raise ValueError("验证集存在缺失的逐题标签")

print("训练人数：", len(train_metadata_df))
print("验证人数：", len(val_metadata_df))
print("测试人数：", len(test_metadata_df))
print("训练逐题标签形状：", train_metadata_df[PHQ8_QUESTION_COLUMNS].shape)
print("验证逐题标签形状：", val_metadata_df[PHQ8_QUESTION_COLUMNS].shape)

训练人数： 163
验证人数： 55
测试人数： 56
训练逐题标签形状： (163, 8)
验证逐题标签形状： (55, 8)

### 文件路径函数

In [3]:
def get_video_feature_path(participant_id):
    participant_id = int(participant_id)
    return DATA_DIR / f"{participant_id}_P" / "features" / f"{participant_id}_CNN_ResNet.mat"

def get_audio_path(participant_id):
    participant_id = int(participant_id)
    return DATA_DIR / f"{participant_id}_P" / f"{participant_id}_AUDIO.wav"

def get_transcript_path(participant_id):
    participant_id = int(participant_id)
    return DATA_DIR / f"{participant_id}_P" / f"{participant_id}_Transcript.csv"

### 检查视觉文件头

In [9]:
def inspect_video_participant(participant_id, split_name):
    participant_id = int(participant_id)
    video_path = get_video_feature_path(participant_id)
    audio_path = get_audio_path(participant_id)
    transcript_path = get_transcript_path(participant_id)
    result = {"Participant_ID": participant_id, "Split": split_name, "Video_Path": str(video_path), "Video_Exists": video_path.exists(), "Audio_Exists": audio_path.exists(), "Transcript_Exists": transcript_path.exists(), "Feature_Exists": False, "Frame_Count": None, "Feature_Dim": None, "Audio_Duration": None, "Estimated_Rate": None, "Error": None}
    if not video_path.exists() or not audio_path.exists() or not transcript_path.exists():
        return result
    try:
        variable_metadata = sio.whosmat(video_path)
        print(variable_metadata)
        feature_metadata = [variable for variable in variable_metadata if variable[0] == "feature"]
        if len(feature_metadata) != 1:
            result["Error"] = f"feature字段数量为{len(feature_metadata)}"
            return result
        feature_shape = feature_metadata[0][1]
        result["Feature_Exists"] = True
        result["Frame_Count"] = int(feature_shape[0])
        result["Feature_Dim"] = int(feature_shape[1]) if len(feature_shape) == 2 else None
        result["Audio_Duration"] = float(librosa.get_duration(path=audio_path))
        result["Estimated_Rate"] = result["Frame_Count"] / result["Audio_Duration"] if result["Audio_Duration"] > 0 else None
    except Exception as exception:
        result["Error"] = repr(exception)
    return result

In [10]:
video_inventory_rows = []

for split_name, metadata_df in {"train": train_metadata_df, "val": val_metadata_df, "test": test_metadata_df}.items():
    for participant_id in metadata_df["Participant_ID"].astype(int).tolist():
        video_inventory_rows.append(inspect_video_participant(participant_id, split_name))

video_inventory_df = pd.DataFrame(video_inventory_rows)

print("扫描数量：", len(video_inventory_df))
display(video_inventory_df.head())

[('feature', (22766, 2048), 'single')]
[('feature', (29565, 2048), 'single')]
[('feature', (23780, 2048), 'single')]
[('feature', (51122, 2048), 'single')]
[('feature', (37167, 2048), 'single')]
[('feature', (26031, 2048), 'single')]
[('feature', (21391, 2048), 'single')]
[('feature', (25609, 2048), 'single')]
[('feature', (23810, 2048), 'single')]
[('feature', (23945, 2048), 'single')]
[('feature', (22848, 2048), 'single')]
[('feature', (46873, 2048), 'single')]
[('feature', (29561, 2048), 'single')]
[('feature', (26337, 2048), 'single')]
[('feature', (17833, 2048), 'single')]
[('feature', (20603, 2048), 'single')]
[('feature', (31412, 2048), 'single')]
[('feature', (25110, 2048), 'single')]
[('feature', (21640, 2048), 'single')]
[('feature', (26251, 2048), 'single')]
[('feature', (20982, 2048), 'single')]
[('feature', (20427, 2048), 'single')]
[('feature', (31956, 2048), 'single')]
[('feature', (21192, 2048), 'single')]
[('feature', (23146, 2048), 'single')]
[('feature', (26228, 2048), 'single')]
[('feature', (29081, 2048), 'single')]
[('feature', (24902, 2048), 'single')]
[('feature', (56137, 2048), 'single')]
[('feature', (17906, 2048), 'single')]
[('feature', (25892, 2048), 'single')]
[('feature', (17980, 2048), 'single')]
[('feature', (26027, 2048), 'single')]
[('feature', (23818, 2048), 'single')]
[('feature', (36656, 2048), 'single')]
[('feature', (21584, 2048), 'single')]
[('feature', (36479, 2048), 'single')]
[('feature', (23090, 2048), 'single')]
[('feature', (22808, 2048), 'single')]
[('feature', (23584, 2048), 'single')]
[('feature', (17306, 2048), 'single')]
[('feature', (20242, 2048), 'single')]
[('feature', (28624, 2048), 'single')]
[('feature', (12447, 2048), 'single')]
[('feature', (19438, 2048), 'single')]
[('feature', (31012, 2048), 'single')]
[('feature', (13214, 2048), 'single')]
[('feature', (19260, 2048), 'single')]
[('feature', (17710, 2048), 'single')]
[('feature', (36814, 2048), 'single')]
[('feature', (53447, 2048), 'single')]
[('feature', (39381, 2048), 'single')]
[('feature', (49112, 2048), 'single')]
[('feature', (40645, 2048), 'single')]
[('feature', (31236, 2048), 'single')]
[('feature', (36262, 2048), 'single')]
[('feature', (45416, 2048), 'single')]
[('feature', (18636, 2048), 'single')]
[('feature', (30772, 2048), 'single')]
[('feature', (39851, 2048), 'single')]
[('feature', (26208, 2048), 'single')]
[('feature', (30065, 2048), 'single')]
[('feature', (58989, 2048), 'single')]
[('feature', (41074, 2048), 'single')]
[('feature', (31707, 2048), 'single')]
[('feature', (16091, 2048), 'single')]
[('feature', (31185, 2048), 'single')]
[('feature', (18084, 2048), 'single')]
[('feature', (28597, 2048), 'single')]
[('feature', (40703, 2048), 'single')]
[('feature', (20405, 2048), 'single')]
[('feature', (19671, 2048), 'single')]
[('feature', (26678, 2048), 'single')]
[('feature', (23413, 2048), 'single')]
[('feature', (28599, 2048), 'single')]
[('feature', (22022, 2048), 'single')]
[('feature', (28104, 2048), 'single')]
[('feature', (25878, 2048), 'single')]
[('feature', (33920, 2048), 'single')]
[('feature', (47107, 2048), 'single')]
[('feature', (21656, 2048), 'single')]
[('feature', (37575, 2048), 'single')]
[('feature', (30974, 2048), 'single')]
[('feature', (31951, 2048), 'single')]
[('feature', (41492, 2048), 'single')]
[('feature', (29906, 2048), 'single')]
[('feature', (29532, 2048), 'single')]
[('feature', (25977, 2048), 'single')]
[('feature', (26590, 2048), 'single')]
[('feature', (32680, 2048), 'single')]
[('feature', (27189, 2048), 'single')]
[('feature', (31468, 2048), 'single')]
[('feature', (25110, 2048), 'single')]
[('feature', (40039, 2048), 'single')]
[('feature', (31881, 2048), 'single')]
[('feature', (25704, 2048), 'single')]
[('feature', (26154, 2048), 'single')]
[('feature', (21127, 2048), 'single')]
[('feature', (28726, 2048), 'single')]
[('feature', (27264, 2048), 'single')]
[('feature', (28079, 2048), 'single')]
[('feature', (39597, 2048), 'single')]
[('feature', (20637, 2048), 'single')]
[('feature', (42901, 2048), 'single')]
[('feature', (38541, 2048), 'single')]
[('feature', (42426, 2048), 'single')]
[('feature', (21040, 2048), 'single')]
[('feature', (39317, 2048), 'single')]
[('feature', (21290, 2048), 'single')]
[('feature', (29955, 2048), 'single')]
[('feature', (24610, 2048), 'single')]
[('feature', (30893, 2048), 'single')]
[('feature', (38256, 2048), 'single')]
[('feature', (26673, 2048), 'single')]
[('feature', (30969, 2048), 'single')]
[('feature', (26485, 2048), 'single')]
[('feature', (28871, 2048), 'single')]
[('feature', (28494, 2048), 'single')]
[('feature', (29254, 2048), 'single')]
[('feature', (29446, 2048), 'single')]
[('feature', (28952, 2048), 'single')]
[('feature', (25039, 2048), 'single')]
[('feature', (29410, 2048), 'single')]
[('feature', (46997, 2048), 'single')]
[('feature', (30074, 2048), 'single')]
[('feature', (33799, 2048), 'single')]
[('feature', (28662, 2048), 'single')]
[('feature', (29862, 2048), 'single')]
[('feature', (27092, 2048), 'single')]
[('feature', (27822, 2048), 'single')]
[('feature', (18265, 2048), 'single')]
[('feature', (37341, 2048), 'single')]
[('feature', (28087, 2048), 'single')]
[('feature', (33491, 2048), 'single')]
[('feature', (30570, 2048), 'single')]
[('feature', (47313, 2048), 'single')]
[('feature', (18082, 2048), 'single')]
[('feature', (30710, 2048), 'single')]
[('feature', (26549, 2048), 'single')]
[('feature', (21141, 2048), 'single')]
[('feature', (20740, 2048), 'single')]
[('feature', (26451, 2048), 'single')]
[('feature', (27375, 2048), 'single')]
[('feature', (21157, 2048), 'single')]
[('feature', (43445, 2048), 'single')]
[('feature', (41540, 2048), 'single')]
[('feature', (27219, 2048), 'single')]
[('feature', (34946, 2048), 'single')]
[('feature', (50760, 2048), 'single')]
[('feature', (22649, 2048), 'single')]
[('feature', (16692, 2048), 'single')]
[('feature', (32080, 2048), 'single')]
[('feature', (25416, 2048), 'single')]
[('feature', (18057, 2048), 'single')]
[('feature', (27012, 2048), 'single')]
[('feature', (41733, 2048), 'single')]
[('feature', (32202, 2048), 'single')]
[('feature', (16175, 2048), 'single')]
[('feature', (45204, 2048), 'single')]
[('feature', (31754, 2048), 'single')]
[('feature', (21988, 2048), 'single')]
[('feature', (24391, 2048), 'single')]
[('feature', (26110, 2048), 'single')]
[('feature', (19458, 2048), 'single')]
[('feature', (24721, 2048), 'single')]
[('feature', (25744, 2048), 'single')]
[('feature', (24395, 2048), 'single')]
[('feature', (25480, 2048), 'single')]
[('feature', (24658, 2048), 'single')]
[('feature', (25524, 2048), 'single')]
[('feature', (29400, 2048), 'single')]
[('feature', (28337, 2048), 'single')]
[('feature', (27819, 2048), 'single')]
[('feature', (32718, 2048), 'single')]
[('feature', (18348, 2048), 'single')]
[('feature', (26455, 2048), 'single')]
[('feature', (41585, 2048), 'single')]
[('feature', (27356, 2048), 'single')]
[('feature', (37951, 2048), 'single')]
[('feature', (38631, 2048), 'single')]
[('feature', (32681, 2048), 'single')]
[('feature', (24728, 2048), 'single')]
[('feature', (24935, 2048), 'single')]
[('feature', (18904, 2048), 'single')]
[('feature', (28027, 2048), 'single')]
[('feature', (24999, 2048), 'single')]
[('feature', (21477, 2048), 'single')]
[('feature', (25709, 2048), 'single')]
[('feature', (23423, 2048), 'single')]
[('feature', (29878, 2048), 'single')]
[('feature', (34644, 2048), 'single')]
[('feature', (25019, 2048), 'single')]
[('feature', (24055, 2048), 'single')]
[('feature', (35550, 2048), 'single')]
[('feature', (25487, 2048), 'single')]
[('feature', (29141, 2048), 'single')]
[('feature', (28502, 2048), 'single')]
[('feature', (36390, 2048), 'single')]
[('feature', (35654, 2048), 'single')]
[('feature', (24126, 2048), 'single')]
[('feature', (22511, 2048), 'single')]
[('feature', (34905, 2048), 'single')]
[('feature', (28193, 2048), 'single')]
[('feature', (16000, 2048), 'single')]
[('feature', (17617, 2048), 'single')]
[('feature', (27311, 2048), 'single')]
[('feature', (25970, 2048), 'single')]
[('feature', (29864, 2048), 'single')]
[('feature', (20472, 2048), 'single')]
[('feature', (40921, 2048), 'single')]
[('feature', (108830, 2048), 'single')]
[('feature', (35901, 2048), 'single')]
[('feature', (19947, 2048), 'single')]
[('feature', (25905, 2048), 'single')]
[('feature', (19150, 2048), 'single')]
[('feature', (33368, 2048), 'single')]
[('feature', (43364, 2048), 'single')]
[('feature', (23710, 2048), 'single')]
[('feature', (20579, 2048), 'single')]
[('feature', (25550, 2048), 'single')]
[('feature', (18832, 2048), 'single')]
[('feature', (24269, 2048), 'single')]
[('feature', (15880, 2048), 'single')]
[('feature', (23773, 2048), 'single')]
[('feature', (34818, 2048), 'single')]
[('feature', (36787, 2048), 'single')]
[('feature', (26721, 2048), 'single')]
[('feature', (35059, 2048), 'single')]
[('feature', (34747, 2048), 'single')]
[('feature', (24875, 2048), 'single')]
[('feature', (45242, 2048), 'single')]
[('feature', (25481, 2048), 'single')]
[('feature', (34693, 2048), 'single')]
[('feature', (18335, 2048), 'single')]
[('feature', (41914, 2048), 'single')]
[('feature', (18571, 2048), 'single')]
[('feature', (24524, 2048), 'single')]
[('feature', (15925, 2048), 'single')]
[('feature', (50605, 2048), 'single')]
[('feature', (37358, 2048), 'single')]
[('feature', (15752, 2048), 'single')]
[('feature', (24406, 2048), 'single')]
[('feature', (29761, 2048), 'single')]
[('feature', (31071, 2048), 'single')]
[('feature', (17600, 2048), 'single')]
[('feature', (28599, 2048), 'single')]
[('feature', (25653, 2048), 'single')]
[('feature', (22912, 2048), 'single')]
[('feature', (29646, 2048), 'single')]
[('feature', (38357, 2048), 'single')]
[('feature', (37609, 2048), 'single')]
[('feature', (26839, 2048), 'single')]
[('feature', (35950, 2048), 'single')]
[('feature', (36163, 2048), 'single')]
[('feature', (42273, 2048), 'single')]
[('feature', (17500, 2048), 'single')]
[('feature', (37161, 2048), 'single')]
[('feature', (22048, 2048), 'single')]
[('feature', (38516, 2048), 'single')]
[('feature', (33811, 2048), 'single')]
[('feature', (26702, 2048), 'single')]
[('feature', (38940, 2048), 'single')]
[('feature', (20752, 2048), 'single')]
[('feature', (22907, 2048), 'single')]
[('feature', (21987, 2048), 'single')]
[('feature', (23580, 2048), 'single')]
[('feature', (26882, 2048), 'single')]
[('feature', (24592, 2048), 'single')]
[('feature', (24998, 2048), 'single')]
[('feature', (36781, 2048), 'single')]
[('feature', (39099, 2048), 'single')]
[('feature', (29091, 2048), 'single')]
[('feature', (29387, 2048), 'single')]
[('feature', (38456, 2048), 'single')]
扫描数量： 274

,Participant_ID,Split,Video_Path,Video_Exists,Audio_Exists,Transcript_Exists,Feature_Exists,Frame_Count,Feature_Dim,Audio_Duration,Estimated_Rate,Error
0,302,train,/workspace/E-DAIC/original_data/302_P/features...,True,True,True,True,22766,2048,758.8,30.002636,None
1,303,train,/workspace/E-DAIC/original_data/303_P/features...,True,True,True,True,29565,2048,985.3,30.006090,None
2,304,train,/workspace/E-DAIC/original_data/304_P/features...,True,True,True,True,23780,2048,792.6,30.002523,None
3,305,train,/workspace/E-DAIC/original_data/305_P/features...,True,True,True,True,51122,2048,1704.0,30.001174,None
4,307,train,/workspace/E-DAIC/original_data/307_P/features...,True,True,True,True,37167,2048,1238.8,30.002422,None

In [11]:
invalid_video_df = video_inventory_df[(video_inventory_df["Video_Exists"] != True) | (video_inventory_df["Audio_Exists"] != True) | (video_inventory_df["Transcript_Exists"] != True) | (video_inventory_df["Feature_Exists"] != True) | (video_inventory_df["Feature_Dim"] != VIDEO_FEATURE_DIM) | (video_inventory_df["Frame_Count"].fillna(0) <= 0)]

print("缺失或损坏文件数量：", len(invalid_video_df))
display(invalid_video_df)

缺失或损坏文件数量： 0

Empty DataFrame
Columns: [Participant_ID, Split, Video_Path, Video_Exists, Audio_Exists, Transcript_Exists, Feature_Exists, Frame_Count, Feature_Dim, Audio_Duration, Estimated_Rate, Error]
Index: []

### 识别可能被截断的视频

In [12]:
valid_video_df = video_inventory_df[(video_inventory_df["Feature_Exists"] == True) & (video_inventory_df["Feature_Dim"] == VIDEO_FEATURE_DIM) & (video_inventory_df["Frame_Count"] > 0) & video_inventory_df["Estimated_Rate"].notna()].copy()
median_video_rate = valid_video_df["Estimated_Rate"].median()
valid_video_df["Rate_Ratio"] = valid_video_df["Estimated_Rate"] / median_video_rate
video_rate_outliers_df = valid_video_df[(valid_video_df["Rate_Ratio"] < 0.8) | (valid_video_df["Rate_Ratio"] > 1.2)].copy()

print("有效视觉文件数量：", len(valid_video_df))
print("估计采样率最小值：", valid_video_df["Estimated_Rate"].min())
print("估计采样率中位数：", median_video_rate)
print("估计采样率最大值：", valid_video_df["Estimated_Rate"].max())
print("采样率异常数量：", len(video_rate_outliers_df))

display(video_rate_outliers_df[["Participant_ID", "Split", "Frame_Count", "Audio_Duration", "Estimated_Rate", "Rate_Ratio"]])

有效视觉文件数量： 274
估计采样率最小值： 15.784537886306437
估计采样率中位数： 30.001217879611822
估计采样率最大值： 79.14909090909092
采样率异常数量： 3

,Participant_ID,Split,Frame_Count,Audio_Duration,Estimated_Rate,Rate_Ratio
157,692,train,16175,1024.7370,15.784538,0.526130
210,627,val,108830,1375.0000,79.149091,2.638196
239,637,test,37358,1686.6265,22.149539,0.738288

In [13]:
invalid_participant_ids = set(invalid_video_df["Participant_ID"].astype(int).tolist())
rate_outlier_participant_ids = set(video_rate_outliers_df["Participant_ID"].astype(int).tolist())
video_exclusion_candidate_ids = sorted(invalid_participant_ids.union(rate_outlier_participant_ids))

print("全部排除候选：", video_exclusion_candidate_ids)

for split_name in ["train", "val", "test"]:
    split_candidate_ids = sorted(video_inventory_df[(video_inventory_df["Split"] == split_name) & (video_inventory_df["Participant_ID"].isin(video_exclusion_candidate_ids))]["Participant_ID"].astype(int).tolist())
    print(f"{split_name}排除候选：", split_candidate_ids)

全部排除候选： [627, 637, 692]
train排除候选： [692]
val排除候选： [627]
test排除候选： [637]

In [14]:
sample_participant_id = int(valid_video_df.iloc[0]["Participant_ID"])
sample_video_path = get_video_feature_path(sample_participant_id)
sample_video_mat = sio.loadmat(sample_video_path)
sample_video_features = sample_video_mat["feature"]
sample_audio_duration = librosa.get_duration(path=get_audio_path(sample_participant_id))
sample_transcript_df = pd.read_csv(get_transcript_path(sample_participant_id))

print("示例参与者：", sample_participant_id)
print("MAT字段：", [key for key in sample_video_mat.keys() if not key.startswith("__")])
print("ResNet特征形状：", sample_video_features.shape)
print("ResNet特征类型：", sample_video_features.dtype)
print("全部有限：", np.isfinite(sample_video_features).all())
print("音频时长：", sample_audio_duration)
print("视觉估计采样率：", len(sample_video_features) / sample_audio_duration)
print("转录轮数：", len(sample_transcript_df))
print("转录字段：", sample_transcript_df.columns.tolist())

示例参与者： 302
MAT字段： ['feature']
ResNet特征形状： (22766, 2048)
ResNet特征类型： float32
全部有限： True
音频时长： 758.8
视觉估计采样率： 30.00263574064312
转录轮数： 99
转录字段： ['Start_Time', 'End_Time', 'Text', 'Confidence']

In [20]:
VIDEO_EXCLUDED_IDS = set()

video_train_metadata_df = train_metadata_df.reset_index(drop=True).copy()
video_val_metadata_df = val_metadata_df.reset_index(drop=True).copy()
video_test_metadata_df = test_metadata_df.reset_index(drop=True).copy()

assert len(video_train_metadata_df) == 163
assert len(video_val_metadata_df) == 55
assert len(video_test_metadata_df) == 56

print("Video训练人数：", len(video_train_metadata_df))
print("Video验证人数：", len(video_val_metadata_df))
print("Video测试人数：", len(video_test_metadata_df))
print("训练集包含692：", 692 in video_train_metadata_df["Participant_ID"].tolist())
print("验证集包含627：", 627 in video_val_metadata_df["Participant_ID"].tolist())
print("测试集包含637：", 637 in video_test_metadata_df["Participant_ID"].tolist())

Video训练人数： 163
Video验证人数： 55
Video测试人数： 56
训练集包含692： True
验证集包含627： True
测试集包含637： True

In [22]:
def get_file_signature(file_path):
    file_path = Path(file_path)
    file_stat = file_path.stat()
    return {"size": int(file_stat.st_size), "mtime_ns": int(file_stat.st_mtime_ns)}

In [23]:
def create_video_turn_intervals(transcript_df, frame_count, audio_duration):
    if audio_duration <= 0:
        raise ValueError("音频时长必须大于0")
    video_rate = frame_count / audio_duration
    start_times = transcript_df["Start_Time"].to_numpy(dtype=np.float64) * video_rate
    end_times = transcript_df["End_Time"].to_numpy(dtype=np.float64) * video_rate
    cleaned_intervals = []
    kept_turn_indices = []
    previous_start = float("-inf")
    previous_end = float("-inf")
    for turn_index, (start_time, end_time) in enumerate(zip(start_times, end_times)):
        if not np.isfinite(start_time) or not np.isfinite(end_time):
            continue
        if start_time < 0 or end_time < 0:
            continue
        if start_time < previous_start or end_time < previous_end:
            continue
        if start_time > frame_count or end_time > frame_count:
            continue
        start_index = int(round(start_time))
        end_index = int(round(end_time))
        start_index = max(0, min(start_index, frame_count))
        end_index = max(0, min(end_index, frame_count))
        if end_index <= start_index:
            continue
        cleaned_intervals.append((start_index, end_index))
        kept_turn_indices.append(turn_index)
        previous_start = start_time

        previous_end = end_time
    if len(cleaned_intervals) == 0:
        raise RuntimeError("清理后没有有效视觉轮次")
    return cleaned_intervals, kept_turn_indices, video_rate

### 生成单个参与者的视频缓存

In [24]:
VIDEO_CACHE_VERSION = "resnet2048_turnmean_turns120_v1"
VIDEO_CACHE_DIR.mkdir(parents=True, exist_ok=True)

In [25]:
def create_video_cache(participant_id, force_rebuild=False):
    participant_id = int(participant_id)
    if participant_id in VIDEO_EXCLUDED_IDS:
        raise ValueError(f"参与者{participant_id}位于视觉排除列表")
    video_path = get_video_feature_path(participant_id)
    audio_path = get_audio_path(participant_id)
    transcript_path = get_transcript_path(participant_id)
    cache_path = VIDEO_CACHE_DIR / f"{participant_id}.pt"
    if not video_path.exists():
        raise FileNotFoundError(f"视觉文件不存在：{video_path}")
    if not audio_path.exists():
        raise FileNotFoundError(f"音频文件不存在：{audio_path}")
    if not transcript_path.exists():
        raise FileNotFoundError(f"转录文件不存在：{transcript_path}")
    video_signature = get_file_signature(video_path)
    audio_signature = get_file_signature(audio_path)
    transcript_signature = get_file_signature(transcript_path)
    if cache_path.exists() and not force_rebuild:
        try:
            existing_cache = torch.load(cache_path, map_location="cpu", weights_only=False)
            signatures_match = existing_cache.get("video_signature") == video_signature and existing_cache.get("audio_signature") == audio_signature and existing_cache.get("transcript_signature") == transcript_signature
            configuration_matches = existing_cache.get("cache_version") == VIDEO_CACHE_VERSION and existing_cache.get("feature_dim") == VIDEO_FEATURE_DIM and existing_cache.get("max_turns") == MAX_TURNS
            shape_matches = tuple(existing_cache.get("video_features", torch.empty(0)).shape) == (MAX_TURNS, VIDEO_FEATURE_DIM) and tuple(existing_cache.get("padding_mask", torch.empty(0)).shape) == (MAX_TURNS,)
            if signatures_match and configuration_matches and shape_matches:
                return cache_path, existing_cache, False
        except Exception:
            pass
    transcript_df = pd.read_csv(transcript_path)
    required_transcript_columns = {"Start_Time", "End_Time"}
    if not required_transcript_columns.issubset(transcript_df.columns):
        raise RuntimeError(f"参与者{participant_id}转录文件缺少时间字段")
    video_mat = sio.loadmat(video_path)
    if "feature" not in video_mat:
        raise RuntimeError(f"参与者{participant_id}的MAT文件缺少feature字段")
    raw_video_features = np.asarray(video_mat["feature"], dtype=np.float32)
    if raw_video_features.ndim != 2 or raw_video_features.shape[1] != VIDEO_FEATURE_DIM:
        raise RuntimeError(f"参与者{participant_id}视觉特征形状错误：{raw_video_features.shape}")
    if not np.isfinite(raw_video_features).all():
        raise RuntimeError(f"参与者{participant_id}原始视觉特征包含NaN或Inf")
    frame_count = int(raw_video_features.shape[0])
    audio_duration = float(librosa.get_duration(path=audio_path))
    cleaned_intervals, kept_turn_indices, video_rate = create_video_turn_intervals(transcript_df, frame_count, audio_duration)
    turn_mean_list = []
    valid_turn_indices = []
    valid_frame_intervals = []
    for original_turn_index, (start_index, end_index) in zip(kept_turn_indices, cleaned_intervals):
        turn_segment = raw_video_features[start_index:end_index]
        if turn_segment.shape[0] == 0:
            continue
        turn_mean = np.mean(turn_segment, axis=0, dtype=np.float32)
        if not np.isfinite(turn_mean).all():
            continue
        turn_mean_list.append(torch.from_numpy(turn_mean))
        valid_turn_indices.append(int(original_turn_index))
        valid_frame_intervals.append((int(start_index), int(end_index)))
    if len(turn_mean_list) == 0:
        raise RuntimeError(f"参与者{participant_id}没有可用的视频轮次")
    all_turn_means = torch.stack(turn_mean_list, dim=0).float()
    all_turn_means = F.normalize(all_turn_means, p=2, dim=1, eps=LOSS_EPSILON)
    real_turn_count = min(all_turn_means.shape[0], MAX_TURNS)
    video_features = torch.zeros((MAX_TURNS, VIDEO_FEATURE_DIM), dtype=torch.float32)
    padding_mask = torch.ones((MAX_TURNS,), dtype=torch.bool)
    video_features[:real_turn_count] = all_turn_means[:real_turn_count]
    padding_mask[:real_turn_count] = False
    cache = {"participant_id": participant_id, "cache_version": VIDEO_CACHE_VERSION, "feature_dim": VIDEO_FEATURE_DIM, "max_turns": MAX_TURNS, "frame_count": frame_count, "audio_duration_seconds": audio_duration, "estimated_video_rate": video_rate, "original_transcript_turns": len(transcript_df), "cleaned_turns": len(turn_mean_list), "real_turn_count": real_turn_count, "kept_turn_indices": valid_turn_indices[:MAX_TURNS], "frame_intervals": valid_frame_intervals[:MAX_TURNS], "video_features": video_features, "padding_mask": padding_mask, "video_signature": video_signature, "audio_signature": audio_signature, "transcript_signature": transcript_signature}
    temporary_cache_path = cache_path.with_suffix(".tmp")
    torch.save(cache, temporary_cache_path)
    temporary_cache_path.replace(cache_path)
    return cache_path, cache, True

In [26]:
def validate_video_cache(cache):
    participant_id = int(cache["participant_id"])
    video_features = cache["video_features"]
    padding_mask = cache["padding_mask"]
    real_turn_count = int(cache["real_turn_count"])
    if video_features.shape != (MAX_TURNS, VIDEO_FEATURE_DIM):
        raise RuntimeError(f"参与者{participant_id}缓存形状错误：{video_features.shape}")
    if padding_mask.shape != (MAX_TURNS,):
        raise RuntimeError(f"参与者{participant_id}的Mask形状错误")
    if video_features.dtype != torch.float32:
        raise RuntimeError(f"参与者{participant_id}缓存类型错误：{video_features.dtype}")
    if padding_mask.dtype != torch.bool:
        raise RuntimeError(f"参与者{participant_id}的Mask类型错误")
    if not torch.isfinite(video_features).all():
        raise RuntimeError(f"参与者{participant_id}缓存包含NaN或Inf")
    if int((~padding_mask).sum().item()) != real_turn_count:
        raise RuntimeError(f"参与者{participant_id}真实轮次数与Mask不一致")
    if padding_mask[:real_turn_count].any() or not padding_mask[real_turn_count:].all():
        raise RuntimeError(f"参与者{participant_id}的Mask不是前真后补齐结构")
    if real_turn_count < MAX_TURNS and torch.count_nonzero(video_features[real_turn_count:]).item() != 0:
        raise RuntimeError(f"参与者{participant_id}填充位置不是0")
    real_features = video_features[:real_turn_count]
    real_norms = torch.linalg.vector_norm(real_features, ord=2, dim=1)
    nonzero_norms = real_norms[real_norms > LOSS_EPSILON]
    if nonzero_norms.numel() > 0 and not torch.allclose(nonzero_norms, torch.ones_like(nonzero_norms), atol=1e-5, rtol=1e-5):
        raise RuntimeError(f"参与者{participant_id}的L2归一化错误")
    return {"participant_id": participant_id, "frame_count": cache["frame_count"], "estimated_video_rate": cache["estimated_video_rate"], "original_turns": cache["original_transcript_turns"], "cleaned_turns": cache["cleaned_turns"], "real_turn_count": real_turn_count, "minimum_nonzero_norm": float(nonzero_norms.min().item()) if nonzero_norms.numel() > 0 else 0.0, "maximum_nonzero_norm": float(nonzero_norms.max().item()) if nonzero_norms.numel() > 0 else 0.0}

In [29]:
video_cache_test_rows = []

for participant_id in [302, 627, 692]:
    cache_path, cache, cache_created = create_video_cache(participant_id, force_rebuild=True)
    validation_result = validate_video_cache(cache)
    validation_result["cache_path"] = str(cache_path)
    validation_result["cache_created"] = cache_created
    video_cache_test_rows.append(validation_result)

video_cache_test_df = pd.DataFrame(video_cache_test_rows)
display(video_cache_test_df)

,participant_id,frame_count,estimated_video_rate,original_turns,cleaned_turns,real_turn_count,minimum_nonzero_norm,maximum_nonzero_norm,cache_path,cache_created
0,302,22766,30.002636,99,98,98,1.0,1.0,/workspace/E-DAIC/cache/phq8_video_resnet/resn...,True
1,627,108830,79.149091,154,154,120,1.0,1.0,/workspace/E-DAIC/cache/phq8_video_resnet/resn...,True
2,692,16175,15.784538,57,57,57,1.0,1.0,/workspace/E-DAIC/cache/phq8_video_resnet/resn...,True

In [30]:
for participant_id in [302, 627, 692]:
    cache = torch.load(VIDEO_CACHE_DIR / f"{participant_id}.pt", map_location="cpu", weights_only=False)
    print("=" * 70)
    print("参与者：", participant_id)
    print("估计视频采样率：", cache["estimated_video_rate"])
    print("原始转录轮数：", cache["original_transcript_turns"])
    print("清理后轮数：", cache["cleaned_turns"])
    print("模型实际轮数：", cache["real_turn_count"])
    print("特征形状：", cache["video_features"].shape)
    print("Mask真实轮数：", int((~cache["padding_mask"]).sum().item()))
    print("全部有限：", torch.isfinite(cache["video_features"]).all().item())

======================================================================
参与者： 302
估计视频采样率： 30.00263574064312
原始转录轮数： 99
清理后轮数： 98
模型实际轮数： 98
特征形状： torch.Size([120, 2048])
Mask真实轮数： 98
全部有限： True
======================================================================
参与者： 627
估计视频采样率： 79.14909090909092
原始转录轮数： 154
清理后轮数： 154
模型实际轮数： 120
特征形状： torch.Size([120, 2048])
Mask真实轮数： 120
全部有限： True
======================================================================
参与者： 692
估计视频采样率： 15.784537886306437
原始转录轮数： 57
清理后轮数： 57
模型实际轮数： 57
特征形状： torch.Size([120, 2048])
Mask真实轮数： 57
全部有限： True

In [31]:
import gc

train_participant_ids = video_train_metadata_df["Participant_ID"].astype(int).tolist()
val_participant_ids = video_val_metadata_df["Participant_ID"].astype(int).tolist()
test_participant_ids = video_test_metadata_df["Participant_ID"].astype(int).tolist()

if set(train_participant_ids).intersection(val_participant_ids):
    raise RuntimeError("训练集和验证集存在重复参与者")

if set(train_participant_ids).intersection(test_participant_ids):
    raise RuntimeError("训练集和测试集存在重复参与者")

if set(val_participant_ids).intersection(test_participant_ids):
    raise RuntimeError("验证集和测试集存在重复参与者")

participant_split_map = {}

for participant_id in train_participant_ids:
    participant_split_map[participant_id] = "train"

for participant_id in val_participant_ids:
    participant_split_map[participant_id] = "val"

for participant_id in test_participant_ids:
    participant_split_map[participant_id] = "test"

all_video_participant_ids = sorted(participant_split_map.keys())

print("训练参与者：", len(train_participant_ids))
print("验证参与者：", len(val_participant_ids))
print("测试参与者：", len(test_participant_ids))
print("全部唯一参与者：", len(all_video_participant_ids))

训练参与者： 163
验证参与者： 55
测试参与者： 56
全部唯一参与者： 274

In [32]:
video_cache_manifest_rows = []
video_cache_error_rows = []
created_cache_count = 0
reused_cache_count = 0
cache_start_time = time.time()

for participant_index, participant_id in enumerate(all_video_participant_ids):
    participant_start_time = time.time()
    try:
        cache_path, cache, cache_created = create_video_cache(participant_id, force_rebuild=False)
        validation_result = validate_video_cache(cache)
        manifest_row = {}
        manifest_row["Participant_ID"] = participant_id
        manifest_row["Split"] = participant_split_map[participant_id]
        manifest_row["Cache_Path"] = str(cache_path)
        manifest_row["Cache_Created"] = cache_created
        manifest_row["Frame_Count"] = validation_result["frame_count"]
        manifest_row["Estimated_Video_Rate"] = validation_result["estimated_video_rate"]
        manifest_row["Original_Turns"] = validation_result["original_turns"]
        manifest_row["Cleaned_Turns"] = validation_result["cleaned_turns"]
        manifest_row["Real_Turn_Count"] = validation_result["real_turn_count"]
        manifest_row["Minimum_Nonzero_Norm"] = validation_result["minimum_nonzero_norm"]
        manifest_row["Maximum_Nonzero_Norm"] = validation_result["maximum_nonzero_norm"]
        manifest_row["Seconds"] = time.time() - participant_start_time
        video_cache_manifest_rows.append(manifest_row)
        if cache_created:
            created_cache_count += 1
        else:
            reused_cache_count += 1
        del cache
    except Exception as exception:
        video_cache_error_rows.append({"Participant_ID": participant_id, "Split": participant_split_map[participant_id], "Error": repr(exception)})
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
    if (participant_index + 1) % 10 == 0 or participant_index + 1 == len(all_video_participant_ids):
        elapsed_seconds = time.time() - cache_start_time
        print(f"视频缓存进度：{participant_index + 1}/{len(all_video_participant_ids)} | 新建：{created_cache_count} | 复用：{reused_cache_count} | 错误：{len(video_cache_error_rows)} | 用时：{elapsed_seconds:.1f}s")

视频缓存进度：10/274 | 新建：9 | 复用：1 | 错误：0 | 用时：4.1s
视频缓存进度：20/274 | 新建：19 | 复用：1 | 错误：0 | 用时：7.8s
视频缓存进度：30/274 | 新建：29 | 复用：1 | 错误：0 | 用时：11.4s
视频缓存进度：40/274 | 新建：39 | 复用：1 | 错误：0 | 用时：15.0s
视频缓存进度：50/274 | 新建：49 | 复用：1 | 错误：0 | 用时：18.4s
视频缓存进度：60/274 | 新建：59 | 复用：1 | 错误：0 | 用时：21.4s
视频缓存进度：70/274 | 新建：69 | 复用：1 | 错误：0 | 用时：25.6s
视频缓存进度：80/274 | 新建：79 | 复用：1 | 错误：0 | 用时：29.7s
视频缓存进度：90/274 | 新建：89 | 复用：1 | 错误：0 | 用时：33.3s
视频缓存进度：100/274 | 新建：99 | 复用：1 | 错误：0 | 用时：36.4s
视频缓存进度：110/274 | 新建：109 | 复用：1 | 错误：0 | 用时：40.3s
视频缓存进度：120/274 | 新建：119 | 复用：1 | 错误：0 | 用时：43.9s
视频缓存进度：130/274 | 新建：129 | 复用：1 | 错误：0 | 用时：47.4s
视频缓存进度：140/274 | 新建：139 | 复用：1 | 错误：0 | 用时：51.3s
视频缓存进度：150/274 | 新建：149 | 复用：1 | 错误：0 | 用时：54.9s
视频缓存进度：160/274 | 新建：159 | 复用：1 | 错误：0 | 用时：58.3s
视频缓存进度：170/274 | 新建：169 | 复用：1 | 错误：0 | 用时：61.9s
视频缓存进度：180/274 | 新建：179 | 复用：1 | 错误：0 | 用时：65.5s
视频缓存进度：190/274 | 新建：189 | 复用：1 | 错误：0 | 用时：68.7s
视频缓存进度：200/274 | 新建：199 | 复用：1 | 错误：0 | 用时：72.2s
视频缓存进度：210/274 | 新建：209 | 复用：1 | 错误：0 | 用时：75.9s
视频缓存进度：220/274 | 新建：218 | 复用：2 | 错误：0 | 用时：79.5s
视频缓存进度：230/274 | 新建：228 | 复用：2 | 错误：0 | 用时：82.6s
视频缓存进度：240/274 | 新建：238 | 复用：2 | 错误：0 | 用时：86.4s
视频缓存进度：250/274 | 新建：248 | 复用：2 | 错误：0 | 用时：90.0s
视频缓存进度：260/274 | 新建：257 | 复用：3 | 错误：0 | 用时：93.7s
视频缓存进度：270/274 | 新建：267 | 复用：3 | 错误：0 | 用时：97.0s
视频缓存进度：274/274 | 新建：271 | 复用：3 | 错误：0 | 用时：98.6s

#### 检查生成错误

In [33]:
video_cache_error_df = pd.DataFrame(video_cache_error_rows)

print("缓存错误数量：", len(video_cache_error_df))

if len(video_cache_error_df) > 0:
    display(video_cache_error_df)
    raise RuntimeError("存在视频缓存生成错误，禁止进入模型训练")

print("全部视频缓存生成成功")

缓存错误数量： 0
全部视频缓存生成成功

#### 保存缓存清单#%%

In [35]:
video_cache_manifest_df = pd.DataFrame(video_cache_manifest_rows).sort_values(["Split", "Participant_ID"]).reset_index(drop=True)
video_cache_manifest_path = VIDEO_CACHE_DIR / "cache_manifest.csv"
video_cache_manifest_df.to_csv(video_cache_manifest_path, index=False)

display(video_cache_manifest_df.head())
print("缓存清单：", video_cache_manifest_path)

,Participant_ID,Split,Cache_Path,Cache_Created,Frame_Count,Estimated_Video_Rate,Original_Turns,Cleaned_Turns,Real_Turn_Count,Minimum_Nonzero_Norm,Maximum_Nonzero_Norm,Seconds
0,600,test,/workspace/E-DAIC/cache/phq8_video_resnet/resn...,True,20579,30.007728,70,70,70,1.0,1.0,0.138849
1,602,test,/workspace/E-DAIC/cache/phq8_video_resnet/resn...,True,25550,32.845261,55,54,54,1.0,1.0,0.200553
2,604,test,/workspace/E-DAIC/cache/phq8_video_resnet/resn...,True,18832,30.044192,57,57,57,1.0,1.0,0.103916
3,605,test,/workspace/E-DAIC/cache/phq8_video_resnet/resn...,True,24269,30.014346,59,59,59,1.0,1.0,0.164316
4,606,test,/workspace/E-DAIC/cache/phq8_video_resnet/resn...,True,15880,30.008126,54,54,54,1.0,1.0,0.095459

缓存清单： /workspace/E-DAIC/cache/phq8_video_resnet/resnet2048_turnmean_turns120_v1/cache_manifest.csv

#### 全局缓存验收

In [36]:
expected_cache_paths = [VIDEO_CACHE_DIR / f"{participant_id}.pt" for participant_id in all_video_participant_ids]
missing_cache_paths = [cache_path for cache_path in expected_cache_paths if not cache_path.exists()]

print("预期缓存数量：", len(expected_cache_paths))
print("实际存在数量：", sum(cache_path.exists() for cache_path in expected_cache_paths))
print("缺失缓存数量：", len(missing_cache_paths))
print("新建缓存数量：", created_cache_count)
print("复用缓存数量：", reused_cache_count)
print("全部特征维度正确：", (video_cache_manifest_df["Minimum_Nonzero_Norm"] > 0).all())
print("全部真实轮数合法：", video_cache_manifest_df["Real_Turn_Count"].between(1, MAX_TURNS).all())
print("达到120轮的参与者数量：", int((video_cache_manifest_df["Real_Turn_Count"] == MAX_TURNS).sum()))
print("真实轮数最小值：", int(video_cache_manifest_df["Real_Turn_Count"].min()))
print("真实轮数中位数：", float(video_cache_manifest_df["Real_Turn_Count"].median()))
print("真实轮数最大值：", int(video_cache_manifest_df["Real_Turn_Count"].max()))

if missing_cache_paths:
    raise RuntimeError(f"存在缺失缓存：{missing_cache_paths[:10]}")

预期缓存数量： 274
实际存在数量： 274
缺失缓存数量： 0
新建缓存数量： 271
复用缓存数量： 3
全部特征维度正确： True
全部真实轮数合法： True
达到120轮的参与者数量： 50
真实轮数最小值： 42
真实轮数中位数： 88.0
真实轮数最大值： 120

In [37]:
video_cache_split_summary_df = video_cache_manifest_df.groupby("Split").agg(Participant_Count=("Participant_ID", "count"), Mean_Original_Turns=("Original_Turns", "mean"), Mean_Cleaned_Turns=("Cleaned_Turns", "mean"), Mean_Real_Turns=("Real_Turn_Count", "mean"), Min_Video_Rate=("Estimated_Video_Rate", "min"), Median_Video_Rate=("Estimated_Video_Rate", "median"), Max_Video_Rate=("Estimated_Video_Rate", "max"), Total_Seconds=("Seconds", "sum")).reset_index()

display(video_cache_split_summary_df)

,Split,Participant_Count,Mean_Original_Turns,Mean_Cleaned_Turns,Mean_Real_Turns,Min_Video_Rate,Median_Video_Rate,Max_Video_Rate,Total_Seconds
0,test,56,99.482143,99.196429,93.357143,22.149539,30.000241,32.845261,12.225127
1,train,163,92.803681,92.503067,88.128834,15.784538,30.001637,32.490017,37.192718
2,val,55,96.072727,95.727273,92.327273,26.163300,30.001165,79.149091,11.185398

### 建立 Video Dataset

In [39]:
class VideoPHQ8Dataset(Dataset):
    def __init__(self, metadata_df, split_name):
        super().__init__()
        if split_name not in {"train", "val"}:
            raise ValueError("split_name只能是train或val")
        self.split_name = split_name
        self.metadata_df = metadata_df.reset_index(drop=True).copy()
        self.participant_ids = self.metadata_df["Participant_ID"].astype(int).tolist()
        self.labels = torch.tensor(self.metadata_df[PHQ8_QUESTION_COLUMNS].to_numpy(), dtype=torch.long)
        video_feature_list = []
        video_mask_list = []
        for index, participant_id in enumerate(self.participant_ids):
            cache_path = VIDEO_CACHE_DIR / f"{participant_id}.pt"
            if not cache_path.exists():
                raise FileNotFoundError(f"Video缓存不存在：{cache_path}")
            cache = torch.load(cache_path, map_location="cpu", weights_only=False)
            video_features = cache["video_features"].float()
            video_padding_mask = cache["padding_mask"].bool()
            if int(cache["participant_id"]) != participant_id:
                raise RuntimeError(f"缓存参与者编号错误：预期{participant_id}，实际{cache['participant_id']}")
            if video_features.shape != (MAX_TURNS, VIDEO_FEATURE_DIM):
                raise RuntimeError(f"参与者{participant_id}特征形状错误：{video_features.shape}")
            if video_padding_mask.shape != (MAX_TURNS,):
                raise RuntimeError(f"参与者{participant_id}Mask形状错误：{video_padding_mask.shape}")
            if not torch.isfinite(video_features).all():
                raise RuntimeError(f"参与者{participant_id}特征包含NaN或Inf")
            if int((~video_padding_mask).sum().item()) != int(cache["real_turn_count"]):
                raise RuntimeError(f"参与者{participant_id}真实轮数与Mask不一致")
            video_feature_list.append(video_features)
            video_mask_list.append(video_padding_mask)
            if (index + 1) % 50 == 0 or index + 1 == len(self.participant_ids):
                print(f"{split_name} Dataset加载进度：{index + 1}/{len(self.participant_ids)}")
        self.video_features = torch.stack(video_feature_list, dim=0)
        self.video_masks = torch.stack(video_mask_list, dim=0)
        if self.video_features.shape != (len(self.participant_ids), MAX_TURNS, VIDEO_FEATURE_DIM):
            raise RuntimeError(f"{split_name}整体特征形状错误：{self.video_features.shape}")
        if self.video_masks.shape != (len(self.participant_ids), MAX_TURNS):
            raise RuntimeError(f"{split_name}整体Mask形状错误：{self.video_masks.shape}")
        if self.labels.shape != (len(self.participant_ids), len(PHQ8_QUESTION_COLUMNS)):
            raise RuntimeError(f"{split_name}标签形状错误：{self.labels.shape}")

    def __len__(self):
        return len(self.participant_ids)

    def __getitem__(self, index):
        return self.video_features[index], self.video_masks[index], self.labels[index]

In [40]:
video_train_dataset = VideoPHQ8Dataset(video_train_metadata_df, split_name="train")
video_val_dataset = VideoPHQ8Dataset(video_val_metadata_df, split_name="val")
print("Video训练样本数：", len(video_train_dataset))
print("Video验证样本数：", len(video_val_dataset))
print("训练特征整体形状：", video_train_dataset.video_features.shape)
print("验证特征整体形状：", video_val_dataset.video_features.shape)
print("训练Mask整体形状：", video_train_dataset.video_masks.shape)
print("验证Mask整体形状：", video_val_dataset.video_masks.shape)
print("训练标签整体形状：", video_train_dataset.labels.shape)
print("验证标签整体形状：", video_val_dataset.labels.shape)

train Dataset加载进度：50/163
train Dataset加载进度：100/163
train Dataset加载进度：150/163
train Dataset加载进度：163/163
val Dataset加载进度：50/55
val Dataset加载进度：55/55
Video训练样本数： 163
Video验证样本数： 55
训练特征整体形状： torch.Size([163, 120, 2048])
验证特征整体形状： torch.Size([55, 120, 2048])
训练Mask整体形状： torch.Size([163, 120])
验证Mask整体形状： torch.Size([55, 120])
训练标签整体形状： torch.Size([163, 8])
验证标签整体形状： torch.Size([55, 8])

In [41]:
def create_video_dataloaders(seed):
    train_generator = torch.Generator()
    train_generator.manual_seed(seed)
    train_loader = DataLoader(video_train_dataset, batch_size=BATCH_SIZE, shuffle=True, num_workers=0, drop_last=False, generator=train_generator)
    val_loader = DataLoader(video_val_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=0, drop_last=False)
    return train_loader, val_loader

In [42]:
video_train_loader, video_val_loader = create_video_dataloaders(seed=42)
batch_video_features, batch_video_masks, batch_all_labels = next(iter(video_train_loader))
print("训练批次数：", len(video_train_loader))
print("验证批次数：", len(video_val_loader))
print("Batch Video特征：", batch_video_features.shape)
print("Batch Video Mask：", batch_video_masks.shape)
print("Batch全部标签：", batch_all_labels.shape)
print("Batch Q1标签：", batch_all_labels[:, 0])
print("Video特征全部有限：", bool(torch.isfinite(batch_video_features).all()))
print("每名参与者真实轮数：", (~batch_video_masks).sum(dim=1))
print("标签范围：", int(batch_all_labels.min()), "～", int(batch_all_labels.max()))

训练批次数： 17
验证批次数： 6
Batch Video特征： torch.Size([10, 120, 2048])
Batch Video Mask： torch.Size([10, 120])
Batch全部标签： torch.Size([10, 8])
Batch Q1标签： tensor([1, 0, 1, 0, 0, 0, 0, 0, 0, 1])
Video特征全部有限： True
每名参与者真实轮数： tensor([120,  64,  66,  56, 120,  42,  84,  88, 114, 115])
标签范围： 0 ～ 3

### 定义 Video-only 模型|

In [43]:
class VideoOnlyQuestModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.lstm = nn.LSTM(input_size=VIDEO_FEATURE_DIM, hidden_size=50, batch_first=True, bidirectional=True)
        self.attention1 = nn.MultiheadAttention(embed_dim=100, num_heads=ATTENTION_HEADS, dropout=0.2, batch_first=True)
        self.attention2 = nn.MultiheadAttention(embed_dim=100, num_heads=ATTENTION_HEADS, dropout=0.2, batch_first=True)
        self.mlp = nn.Sequential(nn.Flatten(), nn.Dropout(0.2), nn.Linear(MAX_TURNS * 100, 256), nn.ReLU(), nn.Dropout(0.2), nn.Linear(256, NUM_CLASSES))

    def forward(self, video_features, video_padding_mask, return_intermediates=False):
        lstm_output, _ = self.lstm(video_features)
        attention1_output, _ = self.attention1(lstm_output, lstm_output, lstm_output, key_padding_mask=video_padding_mask, need_weights=False)
        attention1_output = attention1_output.masked_fill(video_padding_mask.unsqueeze(-1), 0.0)
        attention2_output, _ = self.attention2(attention1_output, attention1_output, attention1_output, key_padding_mask=video_padding_mask, need_weights=False)
        attention2_output = attention2_output.masked_fill(video_padding_mask.unsqueeze(-1), 0.0)
        logits = self.mlp(attention2_output)
        if return_intermediates:
            return logits, {"lstm_output": lstm_output, "attention1_output": attention1_output, "attention2_output": attention2_output}
        return logits

In [45]:
def set_seed(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed(seed)
        torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

In [46]:
set_seed(42)
video_q1_model = VideoOnlyQuestModel().to(device)
video_q1_model.eval()
with torch.no_grad():
    video_logits, video_intermediates = video_q1_model(batch_video_features.to(device), batch_video_masks.to(device), return_intermediates=True)
    video_probabilities = torch.softmax(video_logits, dim=1)
print("输入特征：", batch_video_features.shape)
print("LSTM输出：", video_intermediates["lstm_output"].shape)
print("第一层Attention：", video_intermediates["attention1_output"].shape)
print("第二层Attention：", video_intermediates["attention2_output"].shape)
print("最终Logits：", video_logits.shape)
print("第一个样本概率：", video_probabilities[0])
print("概率之和：", video_probabilities[0].sum().item())
print("Logits全部有限：", bool(torch.isfinite(video_logits).all()))
print("模型总参数：", f"{sum(parameter.numel() for parameter in video_q1_model.parameters()):,}")
print("模型可训练参数：", f"{sum(parameter.numel() for parameter in video_q1_model.parameters() if parameter.requires_grad):,}")

输入特征： torch.Size([10, 120, 2048])
LSTM输出： torch.Size([10, 120, 100])
第一层Attention： torch.Size([10, 120, 100])
第二层Attention： torch.Size([10, 120, 100])
最终Logits： torch.Size([10, 4])
第一个样本概率： tensor([0.2558, 0.2634, 0.2384, 0.2424], device='cuda:0')
概率之和： 1.0
Logits全部有限： True
模型总参数： 3,994,084
模型可训练参数： 3,994,084

In [47]:
class ImbOLLLoss(nn.Module):
    def __init__(self, class_weights, alpha=1.0, epsilon=1e-12):
        super().__init__()
        self.register_buffer("class_weights", class_weights.float())
        self.alpha = alpha
        self.epsilon = epsilon

    def forward(self, logits, targets):
        probabilities = torch.softmax(logits, dim=1)
        class_indices = torch.arange(logits.shape[1], device=logits.device).view(1, -1)
        ordinal_distances = torch.abs(targets.view(-1, 1) - class_indices).float()
        sample_weights = self.class_weights[targets].view(-1, 1)
        weighted_distances = torch.pow(sample_weights * ordinal_distances, self.alpha)
        losses = -torch.log(1.0 - probabilities + self.epsilon) * weighted_distances
        return losses.sum(dim=1).mean()

In [48]:
q1_train_labels = video_train_dataset.labels[:, 0]
q1_class_counts = torch.bincount(q1_train_labels, minlength=NUM_CLASSES)
q1_class_weights = torch.pow(len(q1_train_labels) / q1_class_counts.float(), BETA)
q1_criterion = ImbOLLLoss(q1_class_weights, alpha=ALPHA).to(device)
print("Q1类别数量：", q1_class_counts.tolist())
print("Q1 ImbOLL权重：", q1_class_weights.tolist())

Q1类别数量： [81, 57, 20, 5]
Q1 ImbOLL权重： [1.4185717105865479, 1.6910496950149536, 2.854820728302002, 5.709641456604004]

In [49]:
set_seed(42)
video_q1_model = VideoOnlyQuestModel().to(device)
video_q1_optimizer = torch.optim.AdamW(video_q1_model.parameters(), lr=LEARNING_RATE, eps=ADAM_EPSILON, weight_decay=WEIGHT_DECAY)
video_q1_model.train()
diagnostic_video_features = batch_video_features.to(device)
diagnostic_video_masks = batch_video_masks.to(device)
diagnostic_q1_labels = batch_all_labels[:, 0].to(device)
video_q1_optimizer.zero_grad(set_to_none=True)
diagnostic_logits = video_q1_model(diagnostic_video_features, diagnostic_video_masks)
diagnostic_loss = q1_criterion(diagnostic_logits, diagnostic_q1_labels)
diagnostic_loss.backward()
gradient_norm_before_clipping = torch.sqrt(sum(parameter.grad.detach().pow(2).sum() for parameter in video_q1_model.parameters() if parameter.grad is not None)).item()
gradient_tensor_count = sum(parameter.grad is not None for parameter in video_q1_model.parameters())
torch.nn.utils.clip_grad_norm_(video_q1_model.parameters(), MAX_GRAD_NORM)
video_q1_optimizer.step()
print("Logits形状：", diagnostic_logits.shape)
print("ImbOLL：", diagnostic_loss.item())
print("预测概率全部有限：", bool(torch.isfinite(torch.softmax(diagnostic_logits, dim=1)).all()))
print("预测类别：", diagnostic_logits.argmax(dim=1))
print("真实类别：", diagnostic_q1_labels)
print("梯度范数：", gradient_norm_before_clipping)
print("具有梯度的参数张量数：", gradient_tensor_count)

Logits形状： torch.Size([10, 4])
ImbOLL： 2.24094557762146
预测概率全部有限： True
预测类别： tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
真实类别： tensor([1, 0, 1, 0, 0, 0, 0, 0, 0, 1], device='cuda:0')
梯度范数： 1.0265271663665771
具有梯度的参数张量数： 20

In [50]:
def calculate_ccc(predictions, targets, epsilon=1e-12):
    predictions = predictions.double()
    targets = targets.double()
    prediction_mean = predictions.mean()
    target_mean = targets.mean()
    covariance = ((predictions - prediction_mean) * (targets - target_mean)).mean()
    prediction_variance = ((predictions - prediction_mean) ** 2).mean()
    target_variance = ((targets - target_mean) ** 2).mean()
    ccc = (2.0 * covariance) / (prediction_variance + target_variance + (prediction_mean - target_mean) ** 2 + epsilon)
    return float(ccc.item())

In [51]:
def calculate_video_metrics(predictions, targets):
    predictions = predictions.long()
    targets = targets.long()
    confusion_matrix = torch.zeros(NUM_CLASSES, NUM_CLASSES, dtype=torch.long)
    for target, prediction in zip(targets, predictions):
        confusion_matrix[target, prediction] += 1
    accuracy = float((predictions == targets).float().mean().item())
    class_f1_scores = []
    class_supports = []
    for class_index in range(NUM_CLASSES):
        true_positive = confusion_matrix[class_index, class_index].item()
        false_positive = confusion_matrix[:, class_index].sum().item() - true_positive
        false_negative = confusion_matrix[class_index, :].sum().item() - true_positive
        precision = true_positive / (true_positive + false_positive) if true_positive + false_positive > 0 else 0.0
        recall = true_positive / (true_positive + false_negative) if true_positive + false_negative > 0 else 0.0
        class_f1 = 2.0 * precision * recall / (precision + recall) if precision + recall > 0 else 0.0
        class_f1_scores.append(class_f1)
        class_supports.append(confusion_matrix[class_index, :].sum().item())
    macro_f1 = float(sum(class_f1_scores) / NUM_CLASSES)
    weighted_f1 = float(sum(class_f1_scores[index] * class_supports[index] for index in range(NUM_CLASSES)) / len(targets))
    rmse = float(torch.sqrt(torch.mean((predictions.float() - targets.float()) ** 2)).item())
    mae = float(torch.mean(torch.abs(predictions.float() - targets.float())).item())
    ccc = calculate_ccc(predictions, targets)
    return {"accuracy": accuracy, "micro_f1": accuracy, "macro_f1": macro_f1, "weighted_f1": weighted_f1, "ccc": ccc, "rmse": rmse, "mae": mae, "confusion_matrix": confusion_matrix}

In [52]:
def run_video_epoch(model, data_loader, question_index, criterion, optimizer=None):
    is_training = optimizer is not None
    if is_training:
        model.train()
    else:
        model.eval()
    total_loss = 0.0
    total_samples = 0
    prediction_list = []
    target_list = []
    for video_features, video_masks, all_labels in data_loader:
        video_features = video_features.to(device)
        video_masks = video_masks.to(device)
        targets = all_labels[:, question_index].to(device)
        if is_training:
            optimizer.zero_grad(set_to_none=True)
        with torch.set_grad_enabled(is_training):
            logits = model(video_features, video_masks)
            loss = criterion(logits, targets)
            if is_training:
                loss.backward()
                torch.nn.utils.clip_grad_norm_(model.parameters(), MAX_GRAD_NORM)
                optimizer.step()
        batch_size = targets.shape[0]
        total_loss += loss.item() * batch_size
        total_samples += batch_size
        prediction_list.append(logits.argmax(dim=1).detach().cpu())
        target_list.append(targets.detach().cpu())
    predictions = torch.cat(prediction_list)
    targets = torch.cat(target_list)
    metrics = calculate_video_metrics(predictions, targets)
    metrics["loss"] = total_loss / total_samples
    metrics["predictions"] = predictions
    metrics["targets"] = targets
    return metrics

In [53]:
set_seed(42)
video_train_loader, video_val_loader = create_video_dataloaders(seed=42)
video_q1_model = VideoOnlyQuestModel().to(device)
q1_train_labels = video_train_dataset.labels[:, 0]
q1_class_counts = torch.bincount(q1_train_labels, minlength=NUM_CLASSES)
q1_class_weights = torch.pow(len(q1_train_labels) / q1_class_counts.float(), BETA)
q1_criterion = ImbOLLLoss(q1_class_weights, alpha=ALPHA).to(device)
video_q1_optimizer = torch.optim.AdamW(video_q1_model.parameters(), lr=LEARNING_RATE, eps=ADAM_EPSILON, weight_decay=WEIGHT_DECAY)
video_q1_train_metrics = run_video_epoch(video_q1_model, video_train_loader, question_index=0, criterion=q1_criterion, optimizer=video_q1_optimizer)
video_q1_val_metrics = run_video_epoch(video_q1_model, video_val_loader, question_index=0, criterion=q1_criterion)

In [54]:
print(f"一轮训练 Loss：{video_q1_train_metrics['loss']:.6f}")
print(f"一轮训练 Accuracy：{video_q1_train_metrics['accuracy']:.6f}")
print(f"一轮训练 Micro F1：{video_q1_train_metrics['micro_f1']:.6f}")
print(f"一轮训练 Macro F1：{video_q1_train_metrics['macro_f1']:.6f}")
print(f"一轮训练 Weighted F1：{video_q1_train_metrics['weighted_f1']:.6f}")
print(f"一轮训练 CCC：{video_q1_train_metrics['ccc']:.6f}")
print(f"一轮训练 RMSE：{video_q1_train_metrics['rmse']:.6f}")
print(f"一轮训练 MAE：{video_q1_train_metrics['mae']:.6f}")
print("一轮训练混淆矩阵：")
print(video_q1_train_metrics["confusion_matrix"])
print(f"一轮验证 Loss：{video_q1_val_metrics['loss']:.6f}")
print(f"一轮验证 Accuracy：{video_q1_val_metrics['accuracy']:.6f}")
print(f"一轮验证 Micro F1：{video_q1_val_metrics['micro_f1']:.6f}")
print(f"一轮验证 Macro F1：{video_q1_val_metrics['macro_f1']:.6f}")
print(f"一轮验证 Weighted F1：{video_q1_val_metrics['weighted_f1']:.6f}")
print(f"一轮验证 CCC：{video_q1_val_metrics['ccc']:.6f}")
print(f"一轮验证 RMSE：{video_q1_val_metrics['rmse']:.6f}")
print(f"一轮验证 MAE：{video_q1_val_metrics['mae']:.6f}")
print("一轮验证混淆矩阵：")
print(video_q1_val_metrics["confusion_matrix"])

一轮训练 Loss：2.385463
一轮训练 Accuracy：0.398773
一轮训练 Micro F1：0.398773
一轮训练 Macro F1：0.244706
一轮训练 Weighted F1：0.355641
一轮训练 CCC：-0.026707
一轮训练 RMSE：0.959294
一轮训练 MAE：0.699386
一轮训练混淆矩阵：
tensor([[20, 59,  2,  0],
        [12, 43,  2,  0],
        [ 7, 11,  2,  0],
        [ 2,  3,  0,  0]])
一轮验证 Loss：2.537260
一轮验证 Accuracy：0.381818
一轮验证 Micro F1：0.381818
一轮验证 Macro F1：0.261029
一轮验证 Weighted F1：0.394920
一轮验证 CCC：0.237715
一轮验证 RMSE：1.095445
一轮验证 MAE：0.800000
一轮验证混淆矩阵：
tensor([[14,  5,  6,  0],
        [ 7,  5, 10,  0],
        [ 1,  1,  2,  0],
        [ 1,  1,  2,  0]])

In [56]:
import time
def compact_video_metrics(metrics):
    return {"loss": float(metrics["loss"]), "accuracy": float(metrics["accuracy"]), "micro_f1": float(metrics["micro_f1"]), "macro_f1": float(metrics["macro_f1"]), "weighted_f1": float(metrics["weighted_f1"]), "ccc": float(metrics["ccc"]), "rmse": float(metrics["rmse"]), "mae": float(metrics["mae"]), "confusion_matrix": metrics["confusion_matrix"].tolist()}

In [57]:
def save_video_checkpoint(path, checkpoint_type, epoch, question_index, seed, model, optimizer, train_metrics, val_metrics, class_counts, class_weights, best_val_loss, best_val_ccc, best_loss_epoch, best_ccc_epoch):
    checkpoint = {}
    checkpoint["checkpoint_type"] = checkpoint_type
    checkpoint["epoch"] = epoch
    checkpoint["question_index"] = question_index
    checkpoint["question_number"] = question_index + 1
    checkpoint["question"] = PHQ8_QUESTION_COLUMNS[question_index]
    checkpoint["seed"] = seed
    checkpoint["model_state_dict"] = model.state_dict()
    checkpoint["optimizer_state_dict"] = optimizer.state_dict()
    checkpoint["train_metrics"] = compact_video_metrics(train_metrics)
    checkpoint["val_metrics"] = compact_video_metrics(val_metrics)
    checkpoint["class_counts"] = class_counts.tolist()
    checkpoint["class_weights"] = class_weights.tolist()
    checkpoint["best_val_loss"] = float(best_val_loss)
    checkpoint["best_val_ccc"] = float(best_val_ccc)
    checkpoint["best_loss_epoch"] = int(best_loss_epoch)
    checkpoint["best_ccc_epoch"] = int(best_ccc_epoch)
    checkpoint["config"] = {"max_turns": MAX_TURNS, "video_feature_dim": VIDEO_FEATURE_DIM, "lstm_hidden_size": 50, "encoder_output_dim": 100, "attention_heads": ATTENTION_HEADS, "attention_dropout": 0.2, "mlp_dropout": 0.2, "num_classes": NUM_CLASSES, "batch_size": BATCH_SIZE, "num_epochs": NUM_EPOCHS, "learning_rate": LEARNING_RATE, "adam_epsilon": ADAM_EPSILON, "weight_decay": WEIGHT_DECAY, "max_grad_norm": MAX_GRAD_NORM, "alpha": ALPHA, "beta": BETA}
    torch.save(checkpoint, path)

In [58]:
def train_video_question(seed, question_index):
    set_seed(seed)
    train_loader, val_loader = create_video_dataloaders(seed)
    model = VideoOnlyQuestModel().to(device)
    train_labels = video_train_dataset.labels[:, question_index]
    class_counts = torch.bincount(train_labels, minlength=NUM_CLASSES)
    class_weights = torch.pow(len(train_labels) / class_counts.float(), BETA)
    criterion = ImbOLLLoss(class_weights, alpha=ALPHA).to(device)
    optimizer = torch.optim.AdamW(model.parameters(), lr=LEARNING_RATE, eps=ADAM_EPSILON, weight_decay=WEIGHT_DECAY)
    checkpoint_dir = VIDEO_CHECKPOINT_ROOT / f"seed_{seed}" / f"question_{question_index + 1}"
    checkpoint_dir.mkdir(parents=True, exist_ok=True)
    best_loss_path = checkpoint_dir / "best_loss.pt"
    best_ccc_path = checkpoint_dir / "best_ccc.pt"
    last_path = checkpoint_dir / "last.pt"
    history_path = checkpoint_dir / "history.csv"
    best_val_loss = float("inf")
    best_val_ccc = float("-inf")
    best_loss_epoch = -1
    best_ccc_epoch = -1
    history_rows = []
    print("=" * 100)
    print(f"开始训练：Seed={seed}，Q{question_index + 1}，{PHQ8_QUESTION_COLUMNS[question_index]}")
    print("类别数量：", class_counts.tolist())
    print("ImbOLL权重：", class_weights.tolist())
    print("=" * 100)
    for epoch in range(1, NUM_EPOCHS + 1):
        epoch_start_time = time.perf_counter()
        train_metrics = run_video_epoch(model, train_loader, question_index, criterion, optimizer)
        val_metrics = run_video_epoch(model, val_loader, question_index, criterion)
        elapsed_seconds = time.perf_counter() - epoch_start_time
        improved_loss = val_metrics["loss"] < best_val_loss
        improved_ccc = val_metrics["ccc"] > best_val_ccc
        if improved_loss:
            best_val_loss = val_metrics["loss"]
            best_loss_epoch = epoch
        if improved_ccc:
            best_val_ccc = val_metrics["ccc"]
            best_ccc_epoch = epoch
        if improved_loss:
            save_video_checkpoint(best_loss_path, "best_loss", epoch, question_index, seed, model, optimizer, train_metrics, val_metrics, class_counts, class_weights, best_val_loss, best_val_ccc, best_loss_epoch, best_ccc_epoch)
        if improved_ccc:
            save_video_checkpoint(best_ccc_path, "best_ccc", epoch, question_index, seed, model, optimizer, train_metrics, val_metrics, class_counts, class_weights, best_val_loss, best_val_ccc, best_loss_epoch, best_ccc_epoch)
        history_rows.append({"Epoch": epoch, "Train_Loss": train_metrics["loss"], "Train_Accuracy": train_metrics["accuracy"], "Train_CCC": train_metrics["ccc"], "Train_RMSE": train_metrics["rmse"], "Train_MAE": train_metrics["mae"], "Val_Loss": val_metrics["loss"], "Val_Accuracy": val_metrics["accuracy"], "Val_CCC": val_metrics["ccc"], "Val_RMSE": val_metrics["rmse"], "Val_MAE": val_metrics["mae"], "Elapsed_Seconds": elapsed_seconds})
        print(f"Epoch {epoch:02d}/{NUM_EPOCHS} | Train Loss {train_metrics['loss']:.6f} | Val Loss {val_metrics['loss']:.6f} | Val CCC {val_metrics['ccc']:.6f} | Val Acc {val_metrics['accuracy']:.6f} | Val RMSE {val_metrics['rmse']:.6f} | {elapsed_seconds:.2f}s")
    save_video_checkpoint(last_path, "last", NUM_EPOCHS, question_index, seed, model, optimizer, train_metrics, val_metrics, class_counts, class_weights, best_val_loss, best_val_ccc, best_loss_epoch, best_ccc_epoch)
    history_df = pd.DataFrame(history_rows)
    history_df.to_csv(history_path, index=False)
    print("=" * 100)
    print(f"训练完成：Seed={seed}，Q{question_index + 1}")
    print(f"最佳Val Loss：{best_val_loss:.6f}，Epoch={best_loss_epoch}")
    print(f"最佳Val CCC：{best_val_ccc:.6f}，Epoch={best_ccc_epoch}")
    print("=" * 100)
    return {"seed": seed, "question_index": question_index, "question_number": question_index + 1, "question": PHQ8_QUESTION_COLUMNS[question_index], "best_val_loss": best_val_loss, "best_val_ccc": best_val_ccc, "best_loss_epoch": best_loss_epoch, "best_ccc_epoch": best_ccc_epoch, "best_loss_path": best_loss_path, "best_ccc_path": best_ccc_path, "last_path": last_path, "history_path": history_path}

In [59]:
video_q1_seed42_result = train_video_question(seed=42, question_index=0)

====================================================================================================
开始训练：Seed=42，Q1，PHQ_8NoInterest
类别数量： [81, 57, 20, 5]
ImbOLL权重： [1.4185717105865479, 1.6910496950149536, 2.854820728302002, 5.709641456604004]
====================================================================================================
Epoch 01/50 | Train Loss 2.385463 | Val Loss 2.537260 | Val CCC 0.237715 | Val Acc 0.381818 | Val RMSE 1.095445 | 1.06s
Epoch 02/50 | Train Loss 2.096551 | Val Loss 2.502337 | Val CCC 0.272326 | Val Acc 0.490909 | Val RMSE 0.934199 | 0.66s
Epoch 03/50 | Train Loss 2.107416 | Val Loss 2.646679 | Val CCC 0.259259 | Val Acc 0.436364 | Val RMSE 0.934199 | 0.72s
Epoch 04/50 | Train Loss 2.042489 | Val Loss 2.551044 | Val CCC 0.220674 | Val Acc 0.418182 | Val RMSE 1.053134 | 0.60s
Epoch 05/50 | Train Loss 2.013167 | Val Loss 2.517005 | Val CCC 0.210687 | Val Acc 0.509091 | Val RMSE 0.924416 | 0.51s
Epoch 06/50 | Train Loss 2.075038 | Val Loss 2.546816 | Val CCC 0.000000 | Val Acc 0.400000 | Val RMSE 0.904534 | 0.66s
Epoch 07/50 | Train Loss 2.046445 | Val Loss 2.679875 | Val CCC 0.024160 | Val Acc 0.454545 | Val RMSE 0.924416 | 0.53s
Epoch 08/50 | Train Loss 2.000705 | Val Loss 2.566922 | Val CCC 0.209012 | Val Acc 0.436364 | Val RMSE 1.044466 | 0.48s
Epoch 09/50 | Train Loss 2.011819 | Val Loss 2.608779 | Val CCC 0.213139 | Val Acc 0.418182 | Val RMSE 0.943880 | 0.47s
Epoch 10/50 | Train Loss 1.942958 | Val Loss 2.562707 | Val CCC 0.000000 | Val Acc 0.436364 | Val RMSE 0.962950 | 0.45s
Epoch 11/50 | Train Loss 1.933852 | Val Loss 2.598288 | Val CCC 0.175916 | Val Acc 0.381818 | Val RMSE 0.990867 | 0.61s
Epoch 12/50 | Train Loss 1.963896 | Val Loss 2.888610 | Val CCC 0.115839 | Val Acc 0.381818 | Val RMSE 1.111919 | 0.47s
Epoch 13/50 | Train Loss 2.019615 | Val Loss 2.570756 | Val CCC 0.159771 | Val Acc 0.490909 | Val RMSE 0.934199 | 0.46s
Epoch 14/50 | Train Loss 1.907274 | Val Loss 2.562789 | Val CCC 0.045068 | Val Acc 0.454545 | Val RMSE 0.924416 | 0.44s
Epoch 15/50 | Train Loss 1.890342 | Val Loss 2.652983 | Val CCC 0.176432 | Val Acc 0.472727 | Val RMSE 0.914529 | 0.45s
Epoch 16/50 | Train Loss 1.927334 | Val Loss 2.577648 | Val CCC 0.126451 | Val Acc 0.363636 | Val RMSE 0.972345 | 0.45s
Epoch 17/50 | Train Loss 1.797880 | Val Loss 4.505794 | Val CCC -0.020688 | Val Acc 0.436364 | Val RMSE 1.053134 | 0.45s
Epoch 18/50 | Train Loss 2.013593 | Val Loss 2.983514 | Val CCC 0.069486 | Val Acc 0.454545 | Val RMSE 1.009050 | 0.46s
Epoch 19/50 | Train Loss 1.978464 | Val Loss 2.603439 | Val CCC 0.080367 | Val Acc 0.345455 | Val RMSE 1.061731 | 0.43s
Epoch 20/50 | Train Loss 1.867172 | Val Loss 3.893287 | Val CCC -0.056291 | Val Acc 0.436364 | Val RMSE 1.026911 | 0.45s
Epoch 21/50 | Train Loss 1.829515 | Val Loss 4.603723 | Val CCC -0.059344 | Val Acc 0.363636 | Val RMSE 1.159937 | 0.45s
Epoch 22/50 | Train Loss 1.786111 | Val Loss 2.941058 | Val CCC -0.014650 | Val Acc 0.381818 | Val RMSE 1.111919 | 0.45s
Epoch 23/50 | Train Loss 1.707911 | Val Loss 3.356688 | Val CCC 0.099024 | Val Acc 0.327273 | Val RMSE 1.272078 | 0.44s
Epoch 24/50 | Train Loss 1.926082 | Val Loss 3.207302 | Val CCC 0.204204 | Val Acc 0.454545 | Val RMSE 0.981650 | 0.44s
Epoch 25/50 | Train Loss 1.901854 | Val Loss 4.353218 | Val CCC 0.249454 | Val Acc 0.545455 | Val RMSE 0.953463 | 0.44s
Epoch 26/50 | Train Loss 1.808493 | Val Loss 2.733351 | Val CCC 0.190200 | Val Acc 0.418182 | Val RMSE 1.053134 | 0.44s
Epoch 27/50 | Train Loss 1.776946 | Val Loss 2.918373 | Val CCC 0.097244 | Val Acc 0.490909 | Val RMSE 0.981650 | 0.45s
Epoch 28/50 | Train Loss 1.753807 | Val Loss 2.970761 | Val CCC 0.236994 | Val Acc 0.436364 | Val RMSE 0.934199 | 0.46s
Epoch 29/50 | Train Loss 1.800469 | Val Loss 2.986210 | Val CCC 0.080170 | Val Acc 0.418182 | Val RMSE 1.070259 | 0.46s
Epoch 30/50 | Train Loss 1.699414 | Val Loss 3.011573 | Val CCC 0.156280 | Val Acc 0.363636 | Val RMSE 1.078720 | 0.46s
Epoch 31/50 | Train Loss 1.784578 | Val Loss 2.857342 | Val CCC 0.172580 | Val Acc 0.418182 | Val RMSE 0.981650 | 0.44s
Epoch 32/50 | Train Loss 1.559815 | Val Loss 3.740600 | Val CCC 0.069899 | Val Acc 0.545455 | Val RMSE 1.044466 | 0.44s
Epoch 33/50 | Train Loss 1.677983 | Val Loss 3.102182 | Val CCC 0.251701 | Val Acc 0.400000 | Val RMSE 1.078720 | 0.45s
Epoch 34/50 | Train Loss 1.573397 | Val Loss 5.720116 | Val CCC 0.039779 | Val Acc 0.472727 | Val RMSE 1.198484 | 0.46s
Epoch 35/50 | Train Loss 1.519657 | Val Loss 3.656650 | Val CCC 0.183763 | Val Acc 0.400000 | Val RMSE 1.111919 | 0.46s
Epoch 36/50 | Train Loss 1.864186 | Val Loss 4.071821 | Val CCC 0.038462 | Val Acc 0.509091 | Val RMSE 1.044466 | 0.45s
Epoch 37/50 | Train Loss 1.419255 | Val Loss 3.849874 | Val CCC 0.065534 | Val Acc 0.400000 | Val RMSE 1.128152 | 0.45s
Epoch 38/50 | Train Loss 1.523999 | Val Loss 5.617355 | Val CCC 0.142412 | Val Acc 0.418182 | Val RMSE 1.044466 | 0.44s
Epoch 39/50 | Train Loss 1.396186 | Val Loss 3.940797 | Val CCC 0.042216 | Val Acc 0.418182 | Val RMSE 1.095445 | 0.44s
Epoch 40/50 | Train Loss 1.484738 | Val Loss 3.988929 | Val CCC 0.112707 | Val Acc 0.381818 | Val RMSE 1.152073 | 0.44s
Epoch 41/50 | Train Loss 1.376655 | Val Loss 5.605758 | Val CCC 0.125413 | Val Acc 0.454545 | Val RMSE 0.981650 | 0.44s
Epoch 42/50 | Train Loss 1.376054 | Val Loss 4.839609 | Val CCC 0.115515 | Val Acc 0.418182 | Val RMSE 1.136182 | 0.45s
Epoch 43/50 | Train Loss 1.265405 | Val Loss 3.684971 | Val CCC 0.152015 | Val Acc 0.436364 | Val RMSE 1.018019 | 0.46s
Epoch 44/50 | Train Loss 1.169336 | Val Loss 4.496272 | Val CCC 0.049240 | Val Acc 0.381818 | Val RMSE 1.095445 | 0.46s
Epoch 45/50 | Train Loss 1.211452 | Val Loss 7.167796 | Val CCC -0.025189 | Val Acc 0.418182 | Val RMSE 1.159937 | 0.46s
Epoch 46/50 | Train Loss 1.429642 | Val Loss 4.957985 | Val CCC 0.151807 | Val Acc 0.545455 | Val RMSE 1.078720 | 0.45s
Epoch 47/50 | Train Loss 1.239448 | Val Loss 4.038360 | Val CCC 0.214876 | Val Acc 0.436364 | Val RMSE 1.018019 | 0.45s
Epoch 48/50 | Train Loss 1.347747 | Val Loss 4.113521 | Val CCC 0.087645 | Val Acc 0.400000 | Val RMSE 1.103713 | 0.45s
Epoch 49/50 | Train Loss 1.044109 | Val Loss 4.618233 | Val CCC 0.211321 | Val Acc 0.472727 | Val RMSE 1.018019 | 0.45s
Epoch 50/50 | Train Loss 1.087783 | Val Loss 12.867533 | Val CCC -0.032864 | Val Acc 0.490909 | Val RMSE 1.206045 | 0.44s
====================================================================================================
训练完成：Seed=42，Q1
最佳Val Loss：2.502337，Epoch=2
最佳Val CCC：0.272326，Epoch=2
====================================================================================================

In [60]:
print("Best Loss存在：", video_q1_seed42_result["best_loss_path"].exists())
print("Best CCC存在：", video_q1_seed42_result["best_ccc_path"].exists())
print("Last存在：", video_q1_seed42_result["last_path"].exists())
print("History存在：", video_q1_seed42_result["history_path"].exists())
print("Best Loss路径：", video_q1_seed42_result["best_loss_path"])
print("Best CCC路径：", video_q1_seed42_result["best_ccc_path"])

Best Loss存在： True
Best CCC存在： True
Last存在： True
History存在： True
Best Loss路径： /workspace/E-DAIC/checkpoints/phq8_video_paperlike/seed_42/question_1/best_loss.pt
Best CCC路径： /workspace/E-DAIC/checkpoints/phq8_video_paperlike/seed_42/question_1/best_ccc.pt

In [61]:
video_q1_best_ccc_path = video_q1_seed42_result["best_ccc_path"]
video_q1_checkpoint = torch.load(video_q1_best_ccc_path, map_location="cpu", weights_only=False)
restored_video_q1_model = VideoOnlyQuestModel().to(device)
load_result = restored_video_q1_model.load_state_dict(video_q1_checkpoint["model_state_dict"], strict=True)
restored_q1_class_weights = torch.tensor(video_q1_checkpoint["class_weights"], dtype=torch.float32)
restored_q1_criterion = ImbOLLLoss(restored_q1_class_weights, alpha=ALPHA).to(device)
_, restored_video_val_loader = create_video_dataloaders(seed=42)
restored_q1_val_metrics = run_video_epoch(restored_video_q1_model, restored_video_val_loader, question_index=0, criterion=restored_q1_criterion)
print("Checkpoint：", video_q1_best_ccc_path)
print("类型：", video_q1_checkpoint["checkpoint_type"])
print("Epoch：", video_q1_checkpoint["epoch"])
print("缺少参数：", load_result.missing_keys)
print("多余参数：", load_result.unexpected_keys)

Checkpoint： /workspace/E-DAIC/checkpoints/phq8_video_paperlike/seed_42/question_1/best_ccc.pt
类型： best_ccc
Epoch： 2
缺少参数： []
多余参数： []

In [62]:
checkpoint_metric_names = ["loss", "accuracy", "micro_f1", "macro_f1", "weighted_f1", "ccc", "rmse", "mae"]
print("保存指标与恢复指标对比：")
for metric_name in checkpoint_metric_names:
    saved_value = float(video_q1_checkpoint["val_metrics"][metric_name])
    restored_value = float(restored_q1_val_metrics[metric_name])
    difference = abs(saved_value - restored_value)
    print(f"{metric_name:>12} | 保存 {saved_value:.9f} | 恢复 {restored_value:.9f} | 差值 {difference:.3e}")

保存指标与恢复指标对比：
        loss | 保存 2.502336784 | 恢复 2.502336784 | 差值 0.000e+00
    accuracy | 保存 0.490909100 | 恢复 0.490909100 | 差值 0.000e+00
    micro_f1 | 保存 0.490909100 | 恢复 0.490909100 | 差值 0.000e+00
    macro_f1 | 保存 0.320833333 | 恢复 0.320833333 | 差值 0.000e+00
 weighted_f1 | 保存 0.479696970 | 恢复 0.479696970 | 差值 0.000e+00
         ccc | 保存 0.272326351 | 恢复 0.272326351 | 差值 0.000e+00
        rmse | 保存 0.934198737 | 恢复 0.934198737 | 差值 0.000e+00
         mae | 保存 0.618181825 | 恢复 0.618181825 | 差值 0.000e+00

In [63]:
maximum_metric_difference = max(abs(float(video_q1_checkpoint["val_metrics"][metric_name]) - float(restored_q1_val_metrics[metric_name])) for metric_name in checkpoint_metric_names)
assert load_result.missing_keys == []
assert load_result.unexpected_keys == []
assert maximum_metric_difference < 1e-6
assert torch.equal(torch.tensor(video_q1_checkpoint["val_metrics"]["confusion_matrix"]), restored_q1_val_metrics["confusion_matrix"])
print("最大指标差值：", maximum_metric_difference)
print("Checkpoint恢复验证通过")

最大指标差值： 0.0
Checkpoint恢复验证通过

In [64]:
import gc

In [65]:
video_seed42_results = [video_q1_seed42_result]
for question_index in range(1, len(PHQ8_QUESTION_COLUMNS)):
    question_result = train_video_question(seed=42, question_index=question_index)
    video_seed42_results.append(question_result)
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

====================================================================================================
开始训练：Seed=42，Q2，PHQ_8Depressed
类别数量： [68, 63, 18, 14]
ImbOLL权重： [1.548243761062622, 1.6085091829299927, 3.009244918823242, 3.412163257598877]
====================================================================================================
Epoch 01/50 | Train Loss 2.506367 | Val Loss 2.334554 | Val CCC 0.141844 | Val Acc 0.363636 | Val RMSE 1.000000 | 0.75s
Epoch 02/50 | Train Loss 2.337957 | Val Loss 2.340672 | Val CCC 0.096051 | Val Acc 0.327273 | Val RMSE 1.183216 | 0.63s
Epoch 03/50 | Train Loss 2.313057 | Val Loss 2.353148 | Val CCC 0.061805 | Val Acc 0.272727 | Val RMSE 1.120065 | 0.55s
Epoch 04/50 | Train Loss 2.304281 | Val Loss 2.311789 | Val CCC 0.224460 | Val Acc 0.418182 | Val RMSE 0.943880 | 0.63s
Epoch 05/50 | Train Loss 2.229037 | Val Loss 2.381508 | Val CCC 0.126984 | Val Acc 0.272727 | Val RMSE 1.000000 | 0.48s
Epoch 06/50 | Train Loss 2.328542 | Val Loss 2.334506 | Val CCC 0.000000 | Val Acc 0.345455 | Val RMSE 0.934199 | 0.59s
Epoch 07/50 | Train Loss 2.265647 | Val Loss 2.409309 | Val CCC 0.151235 | Val Acc 0.309091 | Val RMSE 0.953463 | 0.50s
Epoch 08/50 | Train Loss 2.236086 | Val Loss 2.309061 | Val CCC 0.171014 | Val Acc 0.363636 | Val RMSE 0.972345 | 0.50s
Epoch 09/50 | Train Loss 2.226354 | Val Loss 2.345692 | Val CCC 0.099518 | Val Acc 0.381818 | Val RMSE 0.962950 | 0.50s
Epoch 10/50 | Train Loss 2.236382 | Val Loss 2.353743 | Val CCC 0.031088 | Val Acc 0.327273 | Val RMSE 0.962950 | 0.62s
Epoch 11/50 | Train Loss 2.214454 | Val Loss 2.423322 | Val CCC 0.121485 | Val Acc 0.290909 | Val RMSE 1.136182 | 0.46s
Epoch 12/50 | Train Loss 2.215352 | Val Loss 2.444115 | Val CCC 0.071344 | Val Acc 0.200000 | Val RMSE 1.136182 | 0.45s
Epoch 13/50 | Train Loss 2.190305 | Val Loss 2.404619 | Val CCC 0.081146 | Val Acc 0.309091 | Val RMSE 1.128152 | 0.46s
Epoch 14/50 | Train Loss 2.229669 | Val Loss 2.330184 | Val CCC 0.010791 | Val Acc 0.400000 | Val RMSE 0.953463 | 0.47s
Epoch 15/50 | Train Loss 2.232035 | Val Loss 2.419206 | Val CCC 0.118467 | Val Acc 0.327273 | Val RMSE 1.120065 | 0.55s
Epoch 16/50 | Train Loss 2.198327 | Val Loss 2.504864 | Val CCC -0.129870 | Val Acc 0.163636 | Val RMSE 1.257704 | 0.48s
Epoch 17/50 | Train Loss 2.112068 | Val Loss 2.601029 | Val CCC 0.161290 | Val Acc 0.418182 | Val RMSE 0.972345 | 0.47s
Epoch 18/50 | Train Loss 2.036236 | Val Loss 3.550547 | Val CCC 0.059134 | Val Acc 0.363636 | Val RMSE 1.213560 | 0.45s
Epoch 19/50 | Train Loss 2.231684 | Val Loss 3.042803 | Val CCC 0.109827 | Val Acc 0.218182 | Val RMSE 1.235829 | 0.60s
Epoch 20/50 | Train Loss 2.150469 | Val Loss 2.535051 | Val CCC 0.080268 | Val Acc 0.400000 | Val RMSE 0.953463 | 0.47s
Epoch 21/50 | Train Loss 1.988620 | Val Loss 2.715506 | Val CCC 0.056404 | Val Acc 0.309091 | Val RMSE 1.152073 | 0.48s
Epoch 22/50 | Train Loss 2.085083 | Val Loss 2.788260 | Val CCC 0.029412 | Val Acc 0.327273 | Val RMSE 1.044466 | 0.46s
Epoch 23/50 | Train Loss 1.815011 | Val Loss 2.933824 | Val CCC -0.014184 | Val Acc 0.218182 | Val RMSE 1.190874 | 0.43s
Epoch 24/50 | Train Loss 1.805389 | Val Loss 2.704031 | Val CCC 0.145363 | Val Acc 0.381818 | Val RMSE 1.061731 | 0.44s
Epoch 25/50 | Train Loss 1.993235 | Val Loss 2.902793 | Val CCC 0.080780 | Val Acc 0.418182 | Val RMSE 1.044466 | 0.44s
Epoch 26/50 | Train Loss 1.786303 | Val Loss 3.300547 | Val CCC 0.117925 | Val Acc 0.290909 | Val RMSE 1.111919 | 0.44s
Epoch 27/50 | Train Loss 1.806724 | Val Loss 5.256577 | Val CCC 0.061706 | Val Acc 0.290909 | Val RMSE 1.307322 | 0.48s
Epoch 28/50 | Train Loss 2.117210 | Val Loss 2.882389 | Val CCC 0.078680 | Val Acc 0.236364 | Val RMSE 1.095445 | 0.45s
Epoch 29/50 | Train Loss 1.847277 | Val Loss 4.845665 | Val CCC 0.127877 | Val Acc 0.290909 | Val RMSE 1.300350 | 0.48s
Epoch 30/50 | Train Loss 1.716961 | Val Loss 3.234635 | Val CCC 0.080268 | Val Acc 0.400000 | Val RMSE 0.953463 | 0.45s
Epoch 31/50 | Train Loss 2.105555 | Val Loss 2.789027 | Val CCC 0.169811 | Val Acc 0.309091 | Val RMSE 1.078720 | 0.45s
Epoch 32/50 | Train Loss 1.679206 | Val Loss 3.213733 | Val CCC 0.110742 | Val Acc 0.363636 | Val RMSE 1.152073 | 0.45s
Epoch 33/50 | Train Loss 1.821273 | Val Loss 3.398022 | Val CCC 0.002706 | Val Acc 0.309091 | Val RMSE 1.103713 | 0.45s
Epoch 34/50 | Train Loss 1.664074 | Val Loss 3.071356 | Val CCC 0.110512 | Val Acc 0.381818 | Val RMSE 1.044466 | 0.45s
Epoch 35/50 | Train Loss 1.604092 | Val Loss 4.310749 | Val CCC 0.110032 | Val Acc 0.327273 | Val RMSE 1.167748 | 0.47s
Epoch 36/50 | Train Loss 2.205881 | Val Loss 2.899126 | Val CCC 0.091981 | Val Acc 0.436364 | Val RMSE 1.128152 | 0.47s
Epoch 37/50 | Train Loss 1.920627 | Val Loss 2.640440 | Val CCC 0.126609 | Val Acc 0.290909 | Val RMSE 1.159937 | 0.47s
Epoch 38/50 | Train Loss 1.669210 | Val Loss 2.943282 | Val CCC 0.057143 | Val Acc 0.236364 | Val RMSE 1.144155 | 0.44s
Epoch 39/50 | Train Loss 1.998309 | Val Loss 2.935799 | Val CCC 0.121786 | Val Acc 0.454545 | Val RMSE 1.035725 | 0.44s
Epoch 40/50 | Train Loss 1.573177 | Val Loss 2.980252 | Val CCC 0.040268 | Val Acc 0.400000 | Val RMSE 1.087115 | 0.45s
Epoch 41/50 | Train Loss 1.552615 | Val Loss 3.429047 | Val CCC 0.069130 | Val Acc 0.345455 | Val RMSE 1.136182 | 0.46s
Epoch 42/50 | Train Loss 1.451947 | Val Loss 3.588563 | Val CCC 0.174442 | Val Acc 0.345455 | Val RMSE 1.159937 | 0.45s
Epoch 43/50 | Train Loss 1.861248 | Val Loss 3.307747 | Val CCC 0.172702 | Val Acc 0.436364 | Val RMSE 0.990867 | 0.44s
Epoch 44/50 | Train Loss 1.646661 | Val Loss 3.037089 | Val CCC 0.118040 | Val Acc 0.290909 | Val RMSE 1.144155 | 0.47s
Epoch 45/50 | Train Loss 1.557280 | Val Loss 3.374437 | Val CCC 0.123894 | Val Acc 0.327273 | Val RMSE 1.070259 | 0.46s
Epoch 46/50 | Train Loss 1.454442 | Val Loss 3.465688 | Val CCC 0.086225 | Val Acc 0.400000 | Val RMSE 1.198484 | 0.45s
Epoch 47/50 | Train Loss 1.588198 | Val Loss 3.668778 | Val CCC 0.077764 | Val Acc 0.327273 | Val RMSE 1.120065 | 0.45s
Epoch 48/50 | Train Loss 1.650165 | Val Loss 3.855918 | Val CCC 0.102314 | Val Acc 0.363636 | Val RMSE 1.103713 | 0.46s
Epoch 49/50 | Train Loss 1.417137 | Val Loss 4.942227 | Val CCC 0.050633 | Val Acc 0.418182 | Val RMSE 1.167748 | 0.49s
Epoch 50/50 | Train Loss 1.492726 | Val Loss 4.368189 | Val CCC 0.147175 | Val Acc 0.454545 | Val RMSE 1.035725 | 0.48s
====================================================================================================
训练完成：Seed=42，Q2
最佳Val Loss：2.309061，Epoch=8
最佳Val CCC：0.224460，Epoch=4
====================================================================================================
====================================================================================================
开始训练：Seed=42，Q3，PHQ_8Sleep
类别数量： [69, 40, 27, 27]
ImbOLL权重： [1.5369837284088135, 2.018662929534912, 2.457038164138794, 2.457038164138794]
====================================================================================================
Epoch 01/50 | Train Loss 2.793642 | Val Loss 2.547048 | Val CCC 0.168998 | Val Acc 0.290909 | Val RMSE 1.213560 | 0.45s
Epoch 02/50 | Train Loss 2.610713 | Val Loss 2.480359 | Val CCC 0.091686 | Val Acc 0.327273 | Val RMSE 1.026911 | 0.44s
Epoch 03/50 | Train Loss 2.601342 | Val Loss 2.511641 | Val CCC 0.036914 | Val Acc 0.309091 | Val RMSE 1.159937 | 0.46s
Epoch 04/50 | Train Loss 2.559279 | Val Loss 2.535834 | Val CCC 0.121709 | Val Acc 0.254545 | Val RMSE 1.159937 | 0.46s
Epoch 05/50 | Train Loss 2.539041 | Val Loss 2.451661 | Val CCC 0.014240 | Val Acc 0.327273 | Val RMSE 1.152073 | 0.45s
Epoch 06/50 | Train Loss 2.554989 | Val Loss 2.649442 | Val CCC 0.150485 | Val Acc 0.272727 | Val RMSE 1.128152 | 0.46s
Epoch 07/50 | Train Loss 2.566143 | Val Loss 2.469725 | Val CCC 0.061600 | Val Acc 0.309091 | Val RMSE 1.183216 | 0.46s
Epoch 08/50 | Train Loss 2.531176 | Val Loss 2.452697 | Val CCC 0.072022 | Val Acc 0.327273 | Val RMSE 1.103713 | 0.45s
Epoch 09/50 | Train Loss 2.515065 | Val Loss 2.460455 | Val CCC 0.081264 | Val Acc 0.254545 | Val RMSE 1.159937 | 0.45s
Epoch 10/50 | Train Loss 2.494211 | Val Loss 2.432234 | Val CCC 0.159878 | Val Acc 0.345455 | Val RMSE 1.044466 | 0.45s
Epoch 11/50 | Train Loss 2.435572 | Val Loss 2.508021 | Val CCC 0.054898 | Val Acc 0.254545 | Val RMSE 1.183216 | 0.45s
Epoch 12/50 | Train Loss 2.424973 | Val Loss 2.479512 | Val CCC 0.137454 | Val Acc 0.309091 | Val RMSE 1.111919 | 0.46s
Epoch 13/50 | Train Loss 2.402112 | Val Loss 2.458251 | Val CCC 0.134313 | Val Acc 0.290909 | Val RMSE 1.167748 | 0.45s
Epoch 14/50 | Train Loss 2.339137 | Val Loss 2.410559 | Val CCC 0.206407 | Val Acc 0.309091 | Val RMSE 1.035725 | 0.45s
Epoch 15/50 | Train Loss 2.316887 | Val Loss 2.542909 | Val CCC 0.187380 | Val Acc 0.345455 | Val RMSE 1.243163 | 0.44s
Epoch 16/50 | Train Loss 2.392095 | Val Loss 2.493539 | Val CCC 0.058737 | Val Acc 0.254545 | Val RMSE 1.213560 | 0.42s
Epoch 17/50 | Train Loss 2.293662 | Val Loss 2.513561 | Val CCC 0.139299 | Val Acc 0.327273 | Val RMSE 1.136182 | 0.42s
Epoch 18/50 | Train Loss 2.204323 | Val Loss 2.895081 | Val CCC 0.157853 | Val Acc 0.363636 | Val RMSE 1.328020 | 0.43s
Epoch 19/50 | Train Loss 2.186000 | Val Loss 2.772327 | Val CCC 0.119129 | Val Acc 0.309091 | Val RMSE 1.272078 | 0.46s
Epoch 20/50 | Train Loss 2.171656 | Val Loss 2.768938 | Val CCC 0.237469 | Val Acc 0.472727 | Val RMSE 1.190874 | 0.45s
Epoch 21/50 | Train Loss 2.095958 | Val Loss 2.613632 | Val CCC 0.309804 | Val Acc 0.381818 | Val RMSE 1.078720 | 0.46s
Epoch 22/50 | Train Loss 2.028146 | Val Loss 2.561089 | Val CCC 0.131516 | Val Acc 0.309091 | Val RMSE 1.152073 | 0.46s
Epoch 23/50 | Train Loss 2.072085 | Val Loss 2.658750 | Val CCC 0.241079 | Val Acc 0.363636 | Val RMSE 1.257704 | 0.47s
Epoch 24/50 | Train Loss 2.098264 | Val Loss 2.700515 | Val CCC 0.153846 | Val Acc 0.327273 | Val RMSE 1.167748 | 0.46s
Epoch 25/50 | Train Loss 1.875255 | Val Loss 2.828661 | Val CCC 0.224155 | Val Acc 0.363636 | Val RMSE 1.152073 | 0.44s
Epoch 26/50 | Train Loss 2.138621 | Val Loss 2.483823 | Val CCC 0.157734 | Val Acc 0.345455 | Val RMSE 1.206045 | 0.45s
Epoch 27/50 | Train Loss 1.886984 | Val Loss 3.138849 | Val CCC 0.284940 | Val Acc 0.327273 | Val RMSE 1.321157 | 0.45s
Epoch 28/50 | Train Loss 1.825369 | Val Loss 3.894860 | Val CCC 0.276616 | Val Acc 0.381818 | Val RMSE 1.314258 | 0.45s
Epoch 29/50 | Train Loss 1.813580 | Val Loss 3.863689 | Val CCC 0.241329 | Val Acc 0.363636 | Val RMSE 1.368476 | 0.45s
Epoch 30/50 | Train Loss 1.800422 | Val Loss 2.901554 | Val CCC 0.157009 | Val Acc 0.254545 | Val RMSE 1.221028 | 0.44s
Epoch 31/50 | Train Loss 1.926442 | Val Loss 3.169769 | Val CCC 0.274725 | Val Acc 0.345455 | Val RMSE 1.044466 | 0.48s
Epoch 32/50 | Train Loss 1.912449 | Val Loss 2.914373 | Val CCC 0.283675 | Val Acc 0.363636 | Val RMSE 1.152073 | 0.46s
Epoch 33/50 | Train Loss 1.682517 | Val Loss 3.756492 | Val CCC 0.205510 | Val Acc 0.327273 | Val RMSE 1.328020 | 0.45s
Epoch 34/50 | Train Loss 2.190916 | Val Loss 3.342801 | Val CCC 0.167887 | Val Acc 0.327273 | Val RMSE 1.300350 | 0.45s
Epoch 35/50 | Train Loss 1.681131 | Val Loss 3.835612 | Val CCC 0.216867 | Val Acc 0.272727 | Val RMSE 1.286291 | 0.45s
Epoch 36/50 | Train Loss 1.879273 | Val Loss 4.735128 | Val CCC 0.221262 | Val Acc 0.272727 | Val RMSE 1.464737 | 0.45s
Epoch 37/50 | Train Loss 1.729597 | Val Loss 3.477626 | Val CCC 0.210637 | Val Acc 0.345455 | Val RMSE 1.111919 | 0.45s
Epoch 38/50 | Train Loss 1.679529 | Val Loss 3.633006 | Val CCC 0.075852 | Val Acc 0.290909 | Val RMSE 1.381699 | 0.46s
Epoch 39/50 | Train Loss 1.593362 | Val Loss 4.024990 | Val CCC 0.127807 | Val Acc 0.290909 | Val RMSE 1.355125 | 0.47s
Epoch 40/50 | Train Loss 1.734308 | Val Loss 3.189142 | Val CCC 0.119446 | Val Acc 0.272727 | Val RMSE 1.272078 | 0.46s
Epoch 41/50 | Train Loss 1.672774 | Val Loss 3.432454 | Val CCC 0.239789 | Val Acc 0.345455 | Val RMSE 1.272078 | 0.45s
Epoch 42/50 | Train Loss 1.573405 | Val Loss 3.700155 | Val CCC 0.163771 | Val Acc 0.309091 | Val RMSE 1.128152 | 0.45s
Epoch 43/50 | Train Loss 1.534314 | Val Loss 4.705109 | Val CCC 0.300492 | Val Acc 0.309091 | Val RMSE 1.167748 | 0.45s
Epoch 44/50 | Train Loss 1.543443 | Val Loss 4.314355 | Val CCC 0.140172 | Val Acc 0.272727 | Val RMSE 1.272078 | 0.45s
Epoch 45/50 | Train Loss 1.504814 | Val Loss 3.536772 | Val CCC 0.223551 | Val Acc 0.345455 | Val RMSE 1.243163 | 0.45s
Epoch 46/50 | Train Loss 1.862314 | Val Loss 5.433786 | Val CCC 0.212650 | Val Acc 0.327273 | Val RMSE 1.414214 | 0.44s
Epoch 47/50 | Train Loss 1.578429 | Val Loss 3.961329 | Val CCC 0.189263 | Val Acc 0.400000 | Val RMSE 1.213560 | 0.44s
Epoch 48/50 | Train Loss 1.533031 | Val Loss 4.218351 | Val CCC 0.154273 | Val Acc 0.309091 | Val RMSE 1.489356 | 0.44s
Epoch 49/50 | Train Loss 1.504641 | Val Loss 4.237060 | Val CCC 0.254699 | Val Acc 0.327273 | Val RMSE 1.300350 | 0.44s
Epoch 50/50 | Train Loss 1.493716 | Val Loss 5.654362 | Val CCC 0.188267 | Val Acc 0.309091 | Val RMSE 1.470930 | 0.44s
====================================================================================================
训练完成：Seed=42，Q3
最佳Val Loss：2.410559，Epoch=14
最佳Val CCC：0.309804，Epoch=21
====================================================================================================
====================================================================================================
开始训练：Seed=42，Q4，PHQ_8Tired
类别数量： [50, 65, 27, 21]
ImbOLL权重： [1.8055469989776611, 1.5835695266723633, 2.457038164138794, 2.7860195636749268]
====================================================================================================
Epoch 01/50 | Train Loss 2.631580 | Val Loss 2.457827 | Val CCC 0.097938 | Val Acc 0.272727 | Val RMSE 1.128152 | 0.47s
Epoch 02/50 | Train Loss 2.454493 | Val Loss 2.401158 | Val CCC 0.162607 | Val Acc 0.363636 | Val RMSE 0.953463 | 0.47s
Epoch 03/50 | Train Loss 2.449169 | Val Loss 2.408052 | Val CCC 0.144409 | Val Acc 0.363636 | Val RMSE 0.981650 | 0.46s
Epoch 04/50 | Train Loss 2.443988 | Val Loss 2.465505 | Val CCC 0.149856 | Val Acc 0.309091 | Val RMSE 1.035725 | 0.44s
Epoch 05/50 | Train Loss 2.420907 | Val Loss 2.386935 | Val CCC 0.144409 | Val Acc 0.363636 | Val RMSE 0.981650 | 0.44s
Epoch 06/50 | Train Loss 2.395952 | Val Loss 2.407029 | Val CCC 0.086379 | Val Acc 0.345455 | Val RMSE 1.044466 | 0.45s
Epoch 07/50 | Train Loss 2.433675 | Val Loss 2.385631 | Val CCC 0.183007 | Val Acc 0.363636 | Val RMSE 0.953463 | 0.45s
Epoch 08/50 | Train Loss 2.406259 | Val Loss 2.447327 | Val CCC 0.183007 | Val Acc 0.363636 | Val RMSE 0.953463 | 0.44s
Epoch 09/50 | Train Loss 2.397671 | Val Loss 2.395697 | Val CCC 0.202899 | Val Acc 0.418182 | Val RMSE 0.924416 | 0.45s
Epoch 10/50 | Train Loss 2.368439 | Val Loss 2.468730 | Val CCC 0.042838 | Val Acc 0.309091 | Val RMSE 1.087115 | 0.48s
Epoch 11/50 | Train Loss 2.325691 | Val Loss 2.446908 | Val CCC 0.145570 | Val Acc 0.345455 | Val RMSE 0.990867 | 0.45s
Epoch 12/50 | Train Loss 2.286277 | Val Loss 2.456435 | Val CCC 0.144409 | Val Acc 0.363636 | Val RMSE 0.981650 | 0.45s
Epoch 13/50 | Train Loss 2.257313 | Val Loss 2.557501 | Val CCC 0.123894 | Val Acc 0.290909 | Val RMSE 1.070259 | 0.45s
Epoch 14/50 | Train Loss 2.272038 | Val Loss 2.525278 | Val CCC 0.069934 | Val Acc 0.363636 | Val RMSE 1.035725 | 0.45s
Epoch 15/50 | Train Loss 2.250532 | Val Loss 2.574708 | Val CCC 0.002387 | Val Acc 0.309091 | Val RMSE 1.175508 | 0.45s
Epoch 16/50 | Train Loss 2.280936 | Val Loss 2.607951 | Val CCC 0.088694 | Val Acc 0.309091 | Val RMSE 1.111919 | 0.45s
Epoch 17/50 | Train Loss 2.120968 | Val Loss 2.582728 | Val CCC -0.037736 | Val Acc 0.400000 | Val RMSE 1.061731 | 0.45s
Epoch 18/50 | Train Loss 2.127280 | Val Loss 2.710258 | Val CCC 0.169760 | Val Acc 0.363636 | Val RMSE 1.053134 | 0.45s
Epoch 19/50 | Train Loss 2.028702 | Val Loss 2.621715 | Val CCC 0.158350 | Val Acc 0.327273 | Val RMSE 1.120065 | 0.45s
Epoch 20/50 | Train Loss 1.915565 | Val Loss 3.264366 | Val CCC 0.065516 | Val Acc 0.127273 | Val RMSE 1.507557 | 0.45s
Epoch 21/50 | Train Loss 1.876373 | Val Loss 2.654138 | Val CCC 0.263442 | Val Acc 0.363636 | Val RMSE 1.103713 | 0.44s
Epoch 22/50 | Train Loss 1.795294 | Val Loss 2.943158 | Val CCC 0.126689 | Val Acc 0.236364 | Val RMSE 1.307322 | 0.46s
Epoch 23/50 | Train Loss 1.923083 | Val Loss 2.718682 | Val CCC 0.179104 | Val Acc 0.236364 | Val RMSE 1.293340 | 0.46s
Epoch 24/50 | Train Loss 1.831346 | Val Loss 2.751594 | Val CCC 0.248292 | Val Acc 0.418182 | Val RMSE 1.144155 | 0.45s
Epoch 25/50 | Train Loss 1.808017 | Val Loss 2.658286 | Val CCC 0.220332 | Val Acc 0.400000 | Val RMSE 1.128152 | 0.45s
Epoch 26/50 | Train Loss 1.679685 | Val Loss 3.454752 | Val CCC 0.091810 | Val Acc 0.272727 | Val RMSE 1.348400 | 0.45s
Epoch 27/50 | Train Loss 1.885123 | Val Loss 3.010506 | Val CCC 0.280129 | Val Acc 0.327273 | Val RMSE 1.183216 | 0.45s
Epoch 28/50 | Train Loss 1.788697 | Val Loss 3.332646 | Val CCC 0.231301 | Val Acc 0.290909 | Val RMSE 1.286291 | 0.45s
Epoch 29/50 | Train Loss 1.728060 | Val Loss 2.958562 | Val CCC 0.303030 | Val Acc 0.472727 | Val RMSE 1.120065 | 0.46s
Epoch 30/50 | Train Loss 1.527927 | Val Loss 3.249646 | Val CCC 0.293578 | Val Acc 0.418182 | Val RMSE 1.183216 | 0.47s
Epoch 31/50 | Train Loss 1.627135 | Val Loss 4.034960 | Val CCC 0.214165 | Val Acc 0.254545 | Val RMSE 1.300350 | 0.45s
Epoch 32/50 | Train Loss 1.814917 | Val Loss 3.742842 | Val CCC 0.150265 | Val Acc 0.363636 | Val RMSE 1.152073 | 0.45s
Epoch 33/50 | Train Loss 1.775421 | Val Loss 3.171834 | Val CCC 0.177239 | Val Acc 0.345455 | Val RMSE 1.198484 | 0.45s
Epoch 34/50 | Train Loss 2.110966 | Val Loss 3.166275 | Val CCC 0.249555 | Val Acc 0.381818 | Val RMSE 1.120065 | 0.45s
Epoch 35/50 | Train Loss 1.658287 | Val Loss 2.776482 | Val CCC 0.317669 | Val Acc 0.472727 | Val RMSE 1.095445 | 0.45s
Epoch 36/50 | Train Loss 1.558656 | Val Loss 3.493355 | Val CCC 0.280048 | Val Acc 0.345455 | Val RMSE 1.095445 | 0.46s
Epoch 37/50 | Train Loss 1.706373 | Val Loss 3.092737 | Val CCC 0.253394 | Val Acc 0.418182 | Val RMSE 1.167748 | 0.45s
Epoch 38/50 | Train Loss 1.502795 | Val Loss 2.994421 | Val CCC 0.258267 | Val Acc 0.309091 | Val RMSE 1.152073 | 0.45s
Epoch 39/50 | Train Loss 1.487957 | Val Loss 3.875929 | Val CCC 0.241867 | Val Acc 0.363636 | Val RMSE 1.167748 | 0.45s
Epoch 40/50 | Train Loss 1.648526 | Val Loss 3.301501 | Val CCC 0.340570 | Val Acc 0.381818 | Val RMSE 1.159937 | 0.45s
Epoch 41/50 | Train Loss 1.342126 | Val Loss 3.491519 | Val CCC 0.209654 | Val Acc 0.363636 | Val RMSE 1.190874 | 0.45s
Epoch 42/50 | Train Loss 1.340849 | Val Loss 5.657993 | Val CCC 0.231824 | Val Acc 0.254545 | Val RMSE 1.394796 | 0.45s
Epoch 43/50 | Train Loss 1.692831 | Val Loss 3.973545 | Val CCC 0.160888 | Val Acc 0.290909 | Val RMSE 1.095445 | 0.48s
Epoch 44/50 | Train Loss 1.819740 | Val Loss 3.128054 | Val CCC 0.312885 | Val Acc 0.472727 | Val RMSE 1.103713 | 0.46s
Epoch 45/50 | Train Loss 1.318644 | Val Loss 5.059335 | Val CCC 0.335613 | Val Acc 0.309091 | Val RMSE 1.228451 | 0.46s
Epoch 46/50 | Train Loss 1.362776 | Val Loss 4.515103 | Val CCC 0.277567 | Val Acc 0.454545 | Val RMSE 1.175508 | 0.45s
Epoch 47/50 | Train Loss 1.235557 | Val Loss 5.330390 | Val CCC 0.160749 | Val Acc 0.254545 | Val RMSE 1.355125 | 0.45s
Epoch 48/50 | Train Loss 1.714820 | Val Loss 6.170778 | Val CCC 0.124480 | Val Acc 0.181818 | Val RMSE 1.420627 | 0.46s
Epoch 49/50 | Train Loss 1.356110 | Val Loss 3.733978 | Val CCC 0.292870 | Val Acc 0.345455 | Val RMSE 1.183216 | 0.45s
Epoch 50/50 | Train Loss 1.205434 | Val Loss 6.038292 | Val CCC 0.278400 | Val Acc 0.309091 | Val RMSE 1.221028 | 0.46s
====================================================================================================
训练完成：Seed=42，Q4
最佳Val Loss：2.385631，Epoch=7
最佳Val CCC：0.340570，Epoch=40
====================================================================================================
====================================================================================================
开始训练：Seed=42，Q5，PHQ_8Appetite

In [66]:
print("Seed 42结果数量：", len(video_seed42_results))
print("Best Loss全部存在：", all(result["best_loss_path"].exists() for result in video_seed42_results))
print("Best CCC全部存在：", all(result["best_ccc_path"].exists() for result in video_seed42_results))
print("Last全部存在：", all(result["last_path"].exists() for result in video_seed42_results))
print("History全部存在：", all(result["history_path"].exists() for result in video_seed42_results))

Seed 42结果数量： 8
Best Loss全部存在： True
Best CCC全部存在： True
Last全部存在： True
History全部存在： True

In [67]:
video_seed42_summary_rows = []
for result in video_seed42_results:
    video_seed42_summary_rows.append({"Seed": result["seed"], "Question_Index": result["question_index"], "Question_Number": result["question_number"], "Question_Name": result["question"], "Best_Val_Loss": result["best_val_loss"], "Best_Loss_Epoch": result["best_loss_epoch"], "Best_Val_CCC": result["best_val_ccc"], "Best_CCC_Epoch": result["best_ccc_epoch"]})
video_seed42_summary_df = pd.DataFrame(video_seed42_summary_rows)
video_seed42_summary_path = VIDEO_CHECKPOINT_ROOT / "seed_42_question_summary.csv"
video_seed42_summary_df.to_csv(video_seed42_summary_path, index=False)
display(video_seed42_summary_df)
print("汇总文件：", video_seed42_summary_path)

,Seed,Question_Index,Question_Number,Question_Name,Best_Val_Loss,Best_Loss_Epoch,Best_Val_CCC,Best_CCC_Epoch
0,42,0,1,PHQ_8NoInterest,2.502337,2,0.272326,2
1,42,1,2,PHQ_8Depressed,2.309061,8,0.224460,4
2,42,2,3,PHQ_8Sleep,2.410559,14,0.309804,21
3,42,3,4,PHQ_8Tired,2.385631,7,0.340570,40
4,42,4,5,PHQ_8Appetite,2.233981,2,0.144876,27
5,42,5,6,PHQ_8Failure,2.260065,24,0.429989,41
6,42,6,7,PHQ_8Concentrating,2.333310,1,0.188525,9
7,42,7,8,PHQ_8Moving,1.807733,2,0.226757,10

汇总文件： /workspace/E-DAIC/checkpoints/phq8_video_paperlike/seed_42_question_summary.csv

In [68]:
video_seed42_best_ccc_rows = []
for result in video_seed42_results:
    checkpoint = torch.load(result["best_ccc_path"], map_location="cpu", weights_only=False)
    video_seed42_best_ccc_rows.append({"Question_Number": checkpoint["question_number"], "Question_Name": checkpoint["question"], "Checkpoint_Epoch": checkpoint["epoch"], "CCC": checkpoint["val_metrics"]["ccc"], "RMSE": checkpoint["val_metrics"]["rmse"], "MAE": checkpoint["val_metrics"]["mae"], "Accuracy": checkpoint["val_metrics"]["accuracy"]})
video_seed42_best_ccc_df = pd.DataFrame(video_seed42_best_ccc_rows)
display(video_seed42_best_ccc_df)

,Question_Number,Question_Name,Checkpoint_Epoch,CCC,RMSE,MAE,Accuracy
0,1,PHQ_8NoInterest,2,0.272326,0.934199,0.618182,0.490909
1,2,PHQ_8Depressed,4,0.224460,0.943880,0.672727,0.418182
2,3,PHQ_8Sleep,21,0.309804,1.078720,0.800000,0.381818
3,4,PHQ_8Tired,40,0.340570,1.159937,0.836364,0.381818
4,5,PHQ_8Appetite,27,0.144876,1.264911,0.981818,0.290909
5,6,PHQ_8Failure,41,0.429989,0.924416,0.672727,0.418182
6,7,PHQ_8Concentrating,9,0.188525,0.990867,0.727273,0.400000
7,8,PHQ_8Moving,10,0.226757,0.750757,0.527273,0.490909

In [69]:
def evaluate_video_seed_on_validation(seed):
    val_loader = DataLoader(video_val_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=0, drop_last=False)
    question_prediction_list = []
    selected_checkpoint_rows = []
    for question_index in range(len(PHQ8_QUESTION_COLUMNS)):
        checkpoint_path = VIDEO_CHECKPOINT_ROOT / f"seed_{seed}" / f"question_{question_index + 1}" / "best_ccc.pt"
        if not checkpoint_path.exists():
            raise FileNotFoundError(f"Checkpoint不存在：{checkpoint_path}")
        checkpoint = torch.load(checkpoint_path, map_location="cpu", weights_only=False)
        if checkpoint["seed"] != seed:
            raise RuntimeError(f"Checkpoint Seed错误：{checkpoint_path}")
        if checkpoint["question_index"] != question_index:
            raise RuntimeError(f"Checkpoint题号错误：{checkpoint_path}")
        if checkpoint["checkpoint_type"] != "best_ccc":
            raise RuntimeError(f"Checkpoint类型错误：{checkpoint_path}")
        model = VideoOnlyQuestModel().to(device)
        load_result = model.load_state_dict(checkpoint["model_state_dict"], strict=True)
        if load_result.missing_keys or load_result.unexpected_keys:
            raise RuntimeError(f"Checkpoint参数不一致：{checkpoint_path}")
        model.eval()
        batch_prediction_list = []
        with torch.no_grad():
            for video_features, video_masks, all_labels in val_loader:
                logits = model(video_features.to(device), video_masks.to(device))
                predictions = logits.argmax(dim=1)
                batch_prediction_list.append(predictions.cpu())
        question_predictions = torch.cat(batch_prediction_list)
        if len(question_predictions) != len(video_val_dataset):
            raise RuntimeError(f"Q{question_index + 1}预测数量错误")
        question_prediction_list.append(question_predictions)
        selected_checkpoint_rows.append({"Seed": seed, "Question_Index": question_index, "Question_Number": question_index + 1, "Question_Name": PHQ8_QUESTION_COLUMNS[question_index], "Checkpoint_Path": str(checkpoint_path), "Checkpoint_Epoch": checkpoint["epoch"], "Val_CCC": checkpoint["val_metrics"]["ccc"]})
        print(f"Q{question_index + 1} | Epoch {checkpoint['epoch']:02d} | Val CCC {checkpoint['val_metrics']['ccc']:.6f}")
        del model
        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
    question_predictions = torch.stack(question_prediction_list, dim=1)
    question_targets = video_val_dataset.labels.clone()
    predicted_totals = question_predictions.sum(dim=1)
    true_totals = question_targets.sum(dim=1)
    total_ccc = calculate_ccc(predicted_totals, true_totals)
    total_rmse = float(torch.sqrt(torch.mean((predicted_totals.float() - true_totals.float()) ** 2)).item())
    total_mae = float(torch.mean(torch.abs(predicted_totals.float() - true_totals.float())).item())
    exact_accuracy = float((predicted_totals == true_totals).float().mean().item())
    prediction_df = pd.DataFrame({"Participant_ID": video_val_dataset.participant_ids})
    for question_index in range(len(PHQ8_QUESTION_COLUMNS)):
        prediction_df[f"Q{question_index + 1}_Predicted"] = question_predictions[:, question_index].numpy()
        prediction_df[f"Q{question_index + 1}_True"] = question_targets[:, question_index].numpy()
    prediction_df["Predicted_Total"] = predicted_totals.numpy()
    prediction_df["True_Total"] = true_totals.numpy()
    prediction_path = VIDEO_CHECKPOINT_ROOT / f"seed_{seed}_validation_predictions.csv"
    selected_checkpoint_path = VIDEO_CHECKPOINT_ROOT / f"seed_{seed}_validation_selected_checkpoints.csv"
    prediction_df.to_csv(prediction_path, index=False)
    pd.DataFrame(selected_checkpoint_rows).to_csv(selected_checkpoint_path, index=False)
    print("=" * 70)
    print("验证参与者数量：", len(prediction_df))
    print(f"总分CCC：{total_ccc:.6f}")
    print(f"总分RMSE：{total_rmse:.6f}")
    print(f"总分MAE：{total_mae:.6f}")
    print(f"完全相等比例：{exact_accuracy:.6f}")
    print(f"预测总分范围：{int(predicted_totals.min())}～{int(predicted_totals.max())}")
    print(f"真实总分范围：{int(true_totals.min())}～{int(true_totals.max())}")
    print("预测文件：", prediction_path)
    return {"seed": seed, "sample_count": len(prediction_df), "ccc": total_ccc, "rmse": total_rmse, "mae": total_mae, "exact_accuracy": exact_accuracy, "question_predictions": question_predictions, "question_targets": question_targets, "predicted_totals": predicted_totals, "true_totals": true_totals, "prediction_path": prediction_path, "selected_checkpoint_path": selected_checkpoint_path}

In [70]:
video_seed42_validation_result = evaluate_video_seed_on_validation(seed=42)

Q1 | Epoch 02 | Val CCC 0.272326
Q2 | Epoch 04 | Val CCC 0.224460
Q3 | Epoch 21 | Val CCC 0.309804
Q4 | Epoch 40 | Val CCC 0.340570
Q5 | Epoch 27 | Val CCC 0.144876
Q6 | Epoch 41 | Val CCC 0.429989
Q7 | Epoch 09 | Val CCC 0.188525
Q8 | Epoch 10 | Val CCC 0.226757
======================================================================
验证参与者数量： 55
总分CCC：0.356659
总分RMSE：5.642372
总分MAE：4.600000
完全相等比例：0.090909
预测总分范围：0～16
真实总分范围：0～20
预测文件： /workspace/E-DAIC/checkpoints/phq8_video_paperlike/seed_42_validation_predictions.csv

In [71]:
def train_all_video_questions_for_seed(seed):
    seed_results = []
    print("#" * 100)
    print(f"开始训练Video-only全部问题：Seed={seed}")
    print("#" * 100)
    for question_index in range(len(PHQ8_QUESTION_COLUMNS)):
        result = train_video_question(seed=seed, question_index=question_index)
        seed_results.append(result)
        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
    summary_rows = []
    for result in seed_results:
        summary_rows.append({"Seed": result["seed"], "Question_Index": result["question_index"], "Question_Number": result["question_number"], "Question_Name": result["question"], "Best_Val_Loss": result["best_val_loss"], "Best_Loss_Epoch": result["best_loss_epoch"], "Best_Val_CCC": result["best_val_ccc"], "Best_CCC_Epoch": result["best_ccc_epoch"]})
    summary_df = pd.DataFrame(summary_rows)
    summary_path = VIDEO_CHECKPOINT_ROOT / f"seed_{seed}_question_summary.csv"
    summary_df.to_csv(summary_path, index=False)
    print(f"Seed {seed}全部问题训练完成")
    print("汇总文件：", summary_path)
    return seed_results, summary_df

In [72]:
video_seed100_results, video_seed100_summary_df = train_all_video_questions_for_seed(seed=100)
display(video_seed100_summary_df)

####################################################################################################
开始训练Video-only全部问题：Seed=100
####################################################################################################
====================================================================================================
开始训练：Seed=100，Q1，PHQ_8NoInterest
类别数量： [81, 57, 20, 5]
ImbOLL权重： [1.4185717105865479, 1.6910496950149536, 2.854820728302002, 5.709641456604004]
====================================================================================================
Epoch 01/50 | Train Loss 2.276058 | Val Loss 2.608974 | Val CCC 0.170616 | Val Acc 0.436364 | Val RMSE 1.128152 | 0.64s
Epoch 02/50 | Train Loss 2.078172 | Val Loss 2.485649 | Val CCC 0.000000 | Val Acc 0.400000 | Val RMSE 0.904534 | 0.74s
Epoch 03/50 | Train Loss 2.134733 | Val Loss 2.543665 | Val CCC 0.195122 | Val Acc 0.436364 | Val RMSE 0.934199 | 0.73s
Epoch 04/50 | Train Loss 2.041648 | Val Loss 2.625105 | Val CCC -0.030445 | Val Acc 0.436364 | Val RMSE 0.934199 | 0.50s
Epoch 05/50 | Train Loss 2.009647 | Val Loss 2.560080 | Val CCC 0.151473 | Val Acc 0.509091 | Val RMSE 0.894427 | 0.50s
Epoch 06/50 | Train Loss 2.049656 | Val Loss 2.505982 | Val CCC 0.279613 | Val Acc 0.472727 | Val RMSE 0.914529 | 0.51s
Epoch 07/50 | Train Loss 2.054391 | Val Loss 2.627572 | Val CCC 0.242061 | Val Acc 0.472727 | Val RMSE 0.914529 | 0.64s
Epoch 08/50 | Train Loss 2.025910 | Val Loss 2.500856 | Val CCC 0.206731 | Val Acc 0.381818 | Val RMSE 1.044466 | 0.46s
Epoch 09/50 | Train Loss 2.005843 | Val Loss 2.615255 | Val CCC 0.004433 | Val Acc 0.418182 | Val RMSE 0.943880 | 0.63s
Epoch 10/50 | Train Loss 1.967278 | Val Loss 2.535756 | Val CCC 0.198770 | Val Acc 0.436364 | Val RMSE 0.904534 | 0.52s
Epoch 11/50 | Train Loss 1.948927 | Val Loss 2.546183 | Val CCC 0.024160 | Val Acc 0.454545 | Val RMSE 0.924416 | 0.46s
Epoch 12/50 | Train Loss 1.943719 | Val Loss 2.555522 | Val CCC 0.224543 | Val Acc 0.381818 | Val RMSE 0.990867 | 0.47s
Epoch 13/50 | Train Loss 1.948388 | Val Loss 2.562363 | Val CCC 0.180633 | Val Acc 0.436364 | Val RMSE 0.934199 | 0.46s
Epoch 14/50 | Train Loss 1.944360 | Val Loss 2.460209 | Val CCC 0.191825 | Val Acc 0.418182 | Val RMSE 1.000000 | 0.54s
Epoch 15/50 | Train Loss 1.910131 | Val Loss 2.641554 | Val CCC 0.071170 | Val Acc 0.490909 | Val RMSE 1.009050 | 0.49s
Epoch 16/50 | Train Loss 2.071122 | Val Loss 2.815421 | Val CCC 0.095437 | Val Acc 0.381818 | Val RMSE 1.136182 | 0.44s
Epoch 17/50 | Train Loss 1.982844 | Val Loss 2.724142 | Val CCC -0.006309 | Val Acc 0.400000 | Val RMSE 1.026911 | 0.45s
Epoch 18/50 | Train Loss 1.769349 | Val Loss 3.090550 | Val CCC -0.021898 | Val Acc 0.436364 | Val RMSE 1.009050 | 0.82s
Epoch 19/50 | Train Loss 1.999145 | Val Loss 4.136306 | Val CCC 0.067251 | Val Acc 0.454545 | Val RMSE 1.026911 | 0.65s
Epoch 20/50 | Train Loss 1.611080 | Val Loss 3.168305 | Val CCC 0.111086 | Val Acc 0.509091 | Val RMSE 1.136182 | 0.58s
Epoch 21/50 | Train Loss 1.881900 | Val Loss 3.158000 | Val CCC 0.126984 | Val Acc 0.418182 | Val RMSE 1.070259 | 0.52s
Epoch 22/50 | Train Loss 1.776680 | Val Loss 3.039849 | Val CCC 0.036965 | Val Acc 0.472727 | Val RMSE 0.990867 | 0.48s
Epoch 23/50 | Train Loss 1.479327 | Val Loss 4.108641 | Val CCC 0.084258 | Val Acc 0.454545 | Val RMSE 1.095445 | 0.58s
Epoch 24/50 | Train Loss 1.983118 | Val Loss 3.593285 | Val CCC 0.193448 | Val Acc 0.418182 | Val RMSE 0.924416 | 0.47s
Epoch 25/50 | Train Loss 1.541753 | Val Loss 2.952576 | Val CCC 0.224940 | Val Acc 0.400000 | Val RMSE 0.981650 | 0.60s
Epoch 26/50 | Train Loss 1.818830 | Val Loss 3.496545 | Val CCC -0.013901 | Val Acc 0.400000 | Val RMSE 1.053134 | 0.50s
Epoch 27/50 | Train Loss 1.625232 | Val Loss 3.696737 | Val CCC 0.043265 | Val Acc 0.400000 | Val RMSE 1.190874 | 0.48s
Epoch 28/50 | Train Loss 1.427614 | Val Loss 4.400464 | Val CCC 0.203668 | Val Acc 0.509091 | Val RMSE 1.044466 | 0.47s
Epoch 29/50 | Train Loss 1.749608 | Val Loss 5.756487 | Val CCC 0.026412 | Val Acc 0.490909 | Val RMSE 1.070259 | 0.49s
Epoch 30/50 | Train Loss 1.513958 | Val Loss 3.186049 | Val CCC 0.234635 | Val Acc 0.454545 | Val RMSE 1.144155 | 0.59s
Epoch 31/50 | Train Loss 1.385257 | Val Loss 3.955032 | Val CCC 0.069348 | Val Acc 0.436364 | Val RMSE 1.053134 | 0.47s
Epoch 32/50 | Train Loss 1.354175 | Val Loss 4.617466 | Val CCC 0.054146 | Val Acc 0.381818 | Val RMSE 1.355125 | 0.46s
Epoch 33/50 | Train Loss 1.340274 | Val Loss 3.066076 | Val CCC 0.138848 | Val Acc 0.454545 | Val RMSE 0.981650 | 0.47s
Epoch 34/50 | Train Loss 1.431380 | Val Loss 4.199739 | Val CCC 0.046838 | Val Acc 0.418182 | Val RMSE 1.159937 | 0.46s
Epoch 35/50 | Train Loss 1.930813 | Val Loss 3.589065 | Val CCC 0.109258 | Val Acc 0.454545 | Val RMSE 1.103713 | 0.57s
Epoch 36/50 | Train Loss 1.371798 | Val Loss 3.360847 | Val CCC 0.091686 | Val Acc 0.454545 | Val RMSE 1.026911 | 0.45s
Epoch 37/50 | Train Loss 1.303723 | Val Loss 5.082052 | Val CCC 0.076336 | Val Acc 0.509091 | Val RMSE 1.095445 | 0.45s
Epoch 38/50 | Train Loss 1.410649 | Val Loss 4.735668 | Val CCC 0.055482 | Val Acc 0.472727 | Val RMSE 1.087115 | 0.45s
Epoch 39/50 | Train Loss 1.477741 | Val Loss 5.810637 | Val CCC -0.062728 | Val Acc 0.490909 | Val RMSE 1.120065 | 0.45s
Epoch 40/50 | Train Loss 1.679458 | Val Loss 3.758434 | Val CCC 0.070991 | Val Acc 0.472727 | Val RMSE 1.120065 | 0.55s
Epoch 41/50 | Train Loss 1.467805 | Val Loss 3.475203 | Val CCC 0.234885 | Val Acc 0.454545 | Val RMSE 0.972345 | 0.44s
Epoch 42/50 | Train Loss 1.195562 | Val Loss 6.419702 | Val CCC 0.060773 | Val Acc 0.509091 | Val RMSE 1.111919 | 0.45s
Epoch 43/50 | Train Loss 1.268367 | Val Loss 5.045886 | Val CCC -0.000492 | Val Acc 0.454545 | Val RMSE 1.159937 | 0.48s
Epoch 44/50 | Train Loss 1.189378 | Val Loss 3.969858 | Val CCC 0.177813 | Val Acc 0.418182 | Val RMSE 1.018019 | 0.45s
Epoch 45/50 | Train Loss 0.992187 | Val Loss 5.221543 | Val CCC 0.084641 | Val Acc 0.363636 | Val RMSE 1.128152 | 0.46s
Epoch 46/50 | Train Loss 1.272878 | Val Loss 5.528147 | Val CCC -0.051152 | Val Acc 0.418182 | Val RMSE 1.111919 | 0.45s
Epoch 47/50 | Train Loss 1.341461 | Val Loss 3.443839 | Val CCC 0.093407 | Val Acc 0.472727 | Val RMSE 1.044466 | 0.48s
Epoch 48/50 | Train Loss 1.153197 | Val Loss 4.482824 | Val CCC 0.153445 | Val Acc 0.345455 | Val RMSE 1.087115 | 0.46s
Epoch 49/50 | Train Loss 1.402248 | Val Loss 4.218385 | Val CCC 0.158025 | Val Acc 0.381818 | Val RMSE 1.061731 | 0.45s
Epoch 50/50 | Train Loss 1.271077 | Val Loss 4.558079 | Val CCC 0.082920 | Val Acc 0.418182 | Val RMSE 1.159937 | 0.47s
====================================================================================================
训练完成：Seed=100，Q1
最佳Val Loss：2.460209，Epoch=14
最佳Val CCC：0.279613，Epoch=6
====================================================================================================
====================================================================================================
开始训练：Seed=100，Q2，PHQ_8Depressed
类别数量： [68, 63, 18, 14]
ImbOLL权重： [1.548243761062622, 1.6085091829299927, 3.009244918823242, 3.412163257598877]
====================================================================================================
Epoch 01/50 | Train Loss 2.595453 | Val Loss 2.358121 | Val CCC 0.000000 | Val Acc 0.345455 | Val RMSE 0.934199 | 0.48s
Epoch 02/50 | Train Loss 2.339807 | Val Loss 2.284547 | Val CCC 0.145631 | Val Acc 0.345455 | Val RMSE 0.934199 | 0.46s
Epoch 03/50 | Train Loss 2.292017 | Val Loss 2.334491 | Val CCC 0.000000 | Val Acc 0.345455 | Val RMSE 0.934199 | 0.47s
Epoch 04/50 | Train Loss 2.252214 | Val Loss 2.297130 | Val CCC 0.212202 | Val Acc 0.381818 | Val RMSE 0.990867 | 0.45s
Epoch 05/50 | Train Loss 2.275373 | Val Loss 2.405319 | Val CCC 0.151235 | Val Acc 0.309091 | Val RMSE 0.953463 | 0.47s
Epoch 06/50 | Train Loss 2.256164 | Val Loss 2.317423 | Val CCC 0.108108 | Val Acc 0.418182 | Val RMSE 1.018019 | 0.46s
Epoch 07/50 | Train Loss 2.260718 | Val Loss 2.374753 | Val CCC 0.097436 | Val Acc 0.309091 | Val RMSE 1.078720 | 0.46s
Epoch 08/50 | Train Loss 2.223637 | Val Loss 2.322802 | Val CCC 0.055402 | Val Acc 0.290909 | Val RMSE 1.061731 | 0.46s
Epoch 09/50 | Train Loss 2.221274 | Val Loss 2.345630 | Val CCC 0.120482 | Val Acc 0.345455 | Val RMSE 1.152073 | 0.46s
Epoch 10/50 | Train Loss 2.237091 | Val Loss 2.357219 | Val CCC 0.037037 | Val Acc 0.363636 | Val RMSE 0.972345 | 0.48s
Epoch 11/50 | Train Loss 2.201797 | Val Loss 2.431465 | Val CCC -0.022191 | Val Acc 0.309091 | Val RMSE 1.103713 | 0.48s
Epoch 12/50 | Train Loss 2.211636 | Val Loss 2.513272 | Val CCC -0.062663 | Val Acc 0.290909 | Val RMSE 1.159937 | 0.47s
Epoch 13/50 | Train Loss 2.237429 | Val Loss 2.402844 | Val CCC 0.062657 | Val Acc 0.254545 | Val RMSE 1.111919 | 0.48s
Epoch 14/50 | Train Loss 2.260401 | Val Loss 2.333226 | Val CCC 0.174662 | Val Acc 0.454545 | Val RMSE 1.053134 | 0.49s
Epoch 15/50 | Train Loss 2.249286 | Val Loss 2.416368 | Val CCC 0.062295 | Val Acc 0.327273 | Val RMSE 0.972345 | 0.49s
Epoch 16/50 | Train Loss 2.169113 | Val Loss 2.447526 | Val CCC 0.041204 | Val Acc 0.363636 | Val RMSE 1.000000 | 0.51s
Epoch 17/50 | Train Loss 2.172992 | Val Loss 2.424410 | Val CCC -0.124783 | Val Acc 0.345455 | Val RMSE 1.035725 | 0.47s
Epoch 18/50 | Train Loss 2.196874 | Val Loss 2.436542 | Val CCC 0.031746 | Val Acc 0.272727 | Val RMSE 1.053134 | 0.47s
Epoch 19/50 | Train Loss 2.117817 | Val Loss 2.634519 | Val CCC 0.106443 | Val Acc 0.363636 | Val RMSE 1.026911 | 0.46s
Epoch 20/50 | Train Loss 2.005651 | Val Loss 2.755179 | Val CCC 0.110112 | Val Acc 0.272727 | Val RMSE 1.144155 | 0.47s
Epoch 21/50 | Train Loss 1.982183 | Val Loss 2.670556 | Val CCC 0.080094 | Val Acc 0.290909 | Val RMSE 1.136182 | 0.46s
Epoch 22/50 | Train Loss 2.038240 | Val Loss 2.414906 | Val CCC 0.087986 | Val Acc 0.418182 | Val RMSE 0.943880 | 0.47s
Epoch 23/50 | Train Loss 1.991883 | Val Loss 2.947092 | Val CCC 0.171311 | Val Acc 0.309091 | Val RMSE 1.152073 | 0.46s
Epoch 24/50 | Train Loss 1.871934 | Val Loss 2.868011 | Val CCC 0.088999 | Val Acc 0.309091 | Val RMSE 1.103713 | 0.47s
Epoch 25/50 | Train Loss 1.790119 | Val Loss 2.844309 | Val CCC 0.147795 | Val Acc 0.345455 | Val RMSE 1.087115 | 0.46s
Epoch 26/50 | Train Loss 1.826420 | Val Loss 3.091219 | Val CCC 0.089172 | Val Acc 0.309091 | Val RMSE 1.087115 | 0.47s
Epoch 27/50 | Train Loss 1.771803 | Val Loss 2.935836 | Val CCC 0.113744 | Val Acc 0.381818 | Val RMSE 0.962950 | 0.48s
Epoch 28/50 | Train Loss 1.665352 | Val Loss 5.847862 | Val CCC 0.099518 | Val Acc 0.236364 | Val RMSE 1.361817 | 0.47s
Epoch 29/50 | Train Loss 2.640963 | Val Loss 3.215282 | Val CCC 0.027907 | Val Acc 0.290909 | Val RMSE 1.018019 | 0.48s
Epoch 30/50 | Train Loss 1.746343 | Val Loss 3.449004 | Val CCC 0.188295 | Val Acc 0.363636 | Val RMSE 1.026911 | 0.45s
Epoch 31/50 | Train Loss 1.608101 | Val Loss 2.888483 | Val CCC 0.174662 | Val Acc 0.327273 | Val RMSE 1.053134 | 0.46s
Epoch 32/50 | Train Loss 1.671700 | Val Loss 3.518244 | Val CCC 0.097015 | Val Acc 0.381818 | Val RMSE 1.095445 | 0.45s
Epoch 33/50 | Train Loss 1.627805 | Val Loss 3.094867 | Val CCC 0.155907 | Val Acc 0.345455 | Val RMSE 1.070259 | 0.45s
Epoch 34/50 | Train Loss 1.571013 | Val Loss 3.579727 | Val CCC 0.078378 | Val Acc 0.454545 | Val RMSE 1.061731 | 0.46s
Epoch 35/50 | Train Loss 1.776049 | Val Loss 3.081094 | Val CCC 0.145631 | Val Acc 0.436364 | Val RMSE 1.078720 | 0.45s
Epoch 36/50 | Train Loss 1.776216 | Val Loss 6.348613 | Val CCC 0.148997 | Val Acc 0.363636 | Val RMSE 1.213560 | 0.46s
Epoch 37/50 | Train Loss 1.774779 | Val Loss 3.664281 | Val CCC 0.031363 | Val Acc 0.290909 | Val RMSE 1.152073 | 0.45s
Epoch 38/50 | Train Loss 1.401593 | Val Loss 4.071149 | Val CCC 0.092016 | Val Acc 0.454545 | Val RMSE 1.053134 | 0.45s
Epoch 39/50 | Train Loss 1.456534 | Val Loss 3.892698 | Val CCC 0.052275 | Val Acc 0.327273 | Val RMSE 1.272078 | 0.45s
Epoch 40/50 | Train Loss 1.401096 | Val Loss 4.941401 | Val CCC -0.007267 | Val Acc 0.200000 | Val RMSE 1.513575 | 0.45s
Epoch 41/50 | Train Loss 1.557014 | Val Loss 3.801327 | Val CCC 0.186770 | Val Acc 0.345455 | Val RMSE 1.018019 | 0.45s
Epoch 42/50 | Train Loss 1.264213 | Val Loss 4.337370 | Val CCC 0.087336 | Val Acc 0.345455 | Val RMSE 1.018019 | 0.45s
Epoch 43/50 | Train Loss 1.302428 | Val Loss 4.709050 | Val CCC 0.160149 | Val Acc 0.400000 | Val RMSE 1.221028 | 0.45s
Epoch 44/50 | Train Loss 1.420888 | Val Loss 5.713451 | Val CCC 0.065934 | Val Acc 0.327273 | Val RMSE 1.243163 | 0.44s
Epoch 45/50 | Train Loss 1.172456 | Val Loss 5.941760 | Val CCC 0.173278 | Val Acc 0.418182 | Val RMSE 1.144155 | 0.44s
Epoch 46/50 | Train Loss 1.395050 | Val Loss 4.932557 | Val CCC 0.053763 | Val Acc 0.363636 | Val RMSE 1.078720 | 0.46s
Epoch 47/50 | Train Loss 1.248143 | Val Loss 5.599665 | Val CCC 0.114664 | Val Acc 0.327273 | Val RMSE 1.152073 | 0.46s
Epoch 48/50 | Train Loss 1.173846 | Val Loss 5.250522 | Val CCC 0.140791 | Val Acc 0.327273 | Val RMSE 1.213560 | 0.45s
Epoch 49/50 | Train Loss 1.333276 | Val Loss 5.392961 | Val CCC 0.079070 | Val Acc 0.327273 | Val RMSE 1.144155 | 0.46s
Epoch 50/50 | Train Loss 1.437105 | Val Loss 5.353815 | Val CCC 0.064368 | Val Acc 0.436364 | Val RMSE 1.159937 | 0.45s
====================================================================================================
训练完成：Seed=100，Q2
最佳Val Loss：2.284547，Epoch=2
最佳Val CCC：0.212202，Epoch=4
====================================================================================================
====================================================================================================
开始训练：Seed=100，Q3，PHQ_8Sleep
类别数量： [69, 40, 27, 27]
ImbOLL权重： [1.5369837284088135, 2.018662929534912, 2.457038164138794, 2.457038164138794]
====================================================================================================
Epoch 01/50 | Train Loss 2.779261 | Val Loss 2.595463 | Val CCC 0.143010 | Val Acc 0.272727 | Val RMSE 1.152073 | 0.45s
Epoch 02/50 | Train Loss 2.633140 | Val Loss 2.460515 | Val CCC 0.042765 | Val Acc 0.327273 | Val RMSE 1.128152 | 0.45s
Epoch 03/50 | Train Loss 2.580507 | Val Loss 2.468123 | Val CCC 0.064671 | Val Acc 0.309091 | Val RMSE 1.136182 | 0.45s
Epoch 04/50 | Train Loss 2.576437 | Val Loss 2.499950 | Val CCC 0.150485 | Val Acc 0.272727 | Val RMSE 1.128152 | 0.46s
Epoch 05/50 | Train Loss 2.565315 | Val Loss 2.469389 | Val CCC 0.128543 | Val Acc 0.254545 | Val RMSE 1.136182 | 0.46s
Epoch 06/50 | Train Loss 2.565924 | Val Loss 2.459288 | Val CCC 0.083124 | Val Acc 0.272727 | Val RMSE 1.152073 | 0.44s
Epoch 07/50 | Train Loss 2.547649 | Val Loss 2.439509 | Val CCC 0.086977 | Val Acc 0.309091 | Val RMSE 1.136182 | 0.44s
Epoch 08/50 | Train Loss 2.495002 | Val Loss 2.483616 | Val CCC 0.023397 | Val Acc 0.272727 | Val RMSE 1.243163 | 0.44s
Epoch 09/50 | Train Loss 2.491250 | Val Loss 2.419215 | Val CCC 0.072022 | Val Acc 0.327273 | Val RMSE 1.103713 | 0.43s
Epoch 10/50 | Train Loss 2.480743 | Val Loss 2.456166 | Val CCC 0.128543 | Val Acc 0.254545 | Val RMSE 1.136182 | 0.44s
Epoch 11/50 | Train Loss 2.442911 | Val Loss 2.427779 | Val CCC 0.035539 | Val Acc 0.290909 | Val RMSE 1.167748 | 0.44s
Epoch 12/50 | Train Loss 2.398039 | Val Loss 2.472127 | Val CCC 0.248068 | Val Acc 0.290909 | Val RMSE 1.120065 | 0.44s
Epoch 13/50 | Train Loss 2.341173 | Val Loss 2.519018 | Val CCC 0.090259 | Val Acc 0.272727 | Val RMSE 1.213560 | 0.44s
Epoch 14/50 | Train Loss 2.386463 | Val Loss 2.470008 | Val CCC 0.225993 | Val Acc 0.381818 | Val RMSE 1.111919 | 0.44s
Epoch 15/50 | Train Loss 2.290529 | Val Loss 2.636968 | Val CCC -0.104624 | Val Acc 0.309091 | Val RMSE 1.250454 | 0.46s
Epoch 16/50 | Train Loss 2.255898 | Val Loss 2.871535 | Val CCC 0.164595 | Val Acc 0.309091 | Val RMSE 1.414214 | 0.47s
Epoch 17/50 | Train Loss 2.167762 | Val Loss 2.692692 | Val CCC 0.054278 | Val Acc 0.290909 | Val RMSE 1.228451 | 0.43s
Epoch 18/50 | Train Loss 2.114201 | Val Loss 2.644206 | Val CCC 0.134313 | Val Acc 0.381818 | Val RMSE 1.167748 | 0.43s
Epoch 19/50 | Train Loss 2.149884 | Val Loss 2.830998 | Val CCC 0.104174 | Val Acc 0.345455 | Val RMSE 1.321157 | 0.43s
Epoch 20/50 | Train Loss 2.085054 | Val Loss 2.574665 | Val CCC 0.238863 | Val Acc 0.345455 | Val RMSE 1.152073 | 0.44s
Epoch 21/50 | Train Loss 1.961755 | Val Loss 2.787982 | Val CCC 0.266977 | Val Acc 0.400000 | Val RMSE 1.070259 | 0.44s
Epoch 22/50 | Train Loss 2.057828 | Val Loss 3.221819 | Val CCC 0.138959 | Val Acc 0.345455 | Val RMSE 1.381699 | 0.44s
Epoch 23/50 | Train Loss 1.911636 | Val Loss 2.909985 | Val CCC 0.178322 | Val Acc 0.381818 | Val RMSE 1.307322 | 0.44s
Epoch 24/50 | Train Loss 1.988888 | Val Loss 3.520072 | Val CCC 0.172505 | Val Acc 0.290909 | Val RMSE 1.543314 | 0.44s
Epoch 25/50 | Train Loss 2.007605 | Val Loss 3.552257 | Val CCC 0.179785 | Val Acc 0.309091 | Val RMSE 1.401298 | 0.45s
Epoch 26/50 | Train Loss 1.872329 | Val Loss 3.051914 | Val CCC 0.174055 | Val Acc 0.309091 | Val RMSE 1.228451 | 0.43s
Epoch 27/50 | Train Loss 1.786349 | Val Loss 3.658028 | Val CCC 0.165540 | Val Acc 0.345455 | Val RMSE 1.355125 | 0.43s
Epoch 28/50 | Train Loss 1.762035 | Val Loss 3.703775 | Val CCC 0.256329 | Val Acc 0.309091 | Val RMSE 1.307322 | 0.44s
Epoch 29/50 | Train Loss 1.902760 | Val Loss 3.114574 | Val CCC 0.081817 | Val Acc 0.254545 | Val RMSE 1.420627 | 0.44s
Epoch 30/50 | Train Loss 1.706144 | Val Loss 4.201579 | Val CCC 0.283934 | Val Acc 0.327273 | Val RMSE 1.307322 | 0.45s
Epoch 31/50 | Train Loss 2.084976 | Val Loss 5.509790 | Val CCC 0.100342 | Val Acc 0.272727 | Val RMSE 1.560886 | 0.47s
Epoch 32/50 | Train Loss 2.333221 | Val Loss 3.407077 | Val CCC 0.276152 | Val Acc 0.363636 | Val RMSE 1.452271 | 0.47s
Epoch 33/50 | Train Loss 2.344705 | Val Loss 2.926566 | Val CCC 0.107923 | Val Acc 0.309091 | Val RMSE 1.375103 | 0.45s
Epoch 34/50 | Train Loss 2.004826 | Val Loss 3.944208 | Val CCC 0.180074 | Val Acc 0.345455 | Val RMSE 1.355125 | 0.44s
Epoch 35/50 | Train Loss 1.910953 | Val Loss 3.228740 | Val CCC 0.232170 | Val Acc 0.309091 | Val RMSE 1.293340 | 0.44s
Epoch 36/50 | Train Loss 1.894578 | Val Loss 5.342234 | Val CCC 0.199258 | Val Acc 0.363636 | Val RMSE 1.361817 | 0.44s
Epoch 37/50 | Train Loss 1.853948 | Val Loss 3.120229 | Val CCC 0.261180 | Val Acc 0.436364 | Val RMSE 1.198484 | 0.44s
Epoch 38/50 | Train Loss 1.917365 | Val Loss 3.924624 | Val CCC 0.177159 | Val Acc 0.254545 | Val RMSE 1.355125 | 0.43s
Epoch 39/50 | Train Loss 1.711132 | Val Loss 5.123561 | Val CCC 0.179772 | Val Acc 0.363636 | Val RMSE 1.414214 | 0.43s
Epoch 40/50 | Train Loss 1.640250 | Val Loss 5.013187 | Val CCC 0.220301 | Val Acc 0.400000 | Val RMSE 1.348400 | 0.45s
Epoch 41/50 | Train Loss 1.590120 | Val Loss 9.858852 | Val CCC 0.091722 | Val Acc 0.254545 | Val RMSE 1.689540 | 0.44s
Epoch 42/50 | Train Loss 2.397199 | Val Loss 4.123990 | Val CCC 0.256958 | Val Acc 0.363636 | Val RMSE 1.348400 | 0.45s
Epoch 43/50 | Train Loss 1.606708 | Val Loss 4.657207 | Val CCC 0.264036 | Val Acc 0.418182 | Val RMSE 1.328020 | 0.45s
Epoch 44/50 | Train Loss 1.817308 | Val Loss 4.673030 | Val CCC 0.210904 | Val Acc 0.327273 | Val RMSE 1.348400 | 0.46s
Epoch 45/50 | Train Loss 2.153962 | Val Loss 3.976191 | Val CCC 0.319661 | Val Acc 0.290909 | Val RMSE 1.175508 | 0.44s
Epoch 46/50 | Train Loss 1.702187 | Val Loss 3.363001 | Val CCC 0.147395 | Val Acc 0.272727 | Val RMSE 1.489356 | 0.44s
Epoch 47/50 | Train Loss 1.917443 | Val Loss 3.572137 | Val CCC 0.230894 | Val Acc 0.309091 | Val RMSE 1.250454 | 0.44s
Epoch 48/50 | Train Loss 1.682584 | Val Loss 4.050382 | Val CCC 0.130764 | Val Acc 0.236364 | Val RMSE 1.629278 | 0.43s
Epoch 49/50 | Train Loss 2.002307 | Val Loss 4.369971 | Val CCC 0.214619 | Val Acc 0.290909 | Val RMSE 1.355125 | 0.46s
Epoch 50/50 | Train Loss 1.657360 | Val Loss 4.609646 | Val CCC 0.128485 | Val Acc 0.327273 | Val RMSE 1.531488 | 0.45s
====================================================================================================
训练完成：Seed=100，Q3
最佳Val Loss：2.419215，Epoch=9
最佳Val CCC：0.319661，Epoch=45

,Seed,Question_Index,Question_Number,Question_Name,Best_Val_Loss,Best_Loss_Epoch,Best_Val_CCC,Best_CCC_Epoch
0,100,0,1,PHQ_8NoInterest,2.460209,14,0.279613,6
1,100,1,2,PHQ_8Depressed,2.284547,2,0.212202,4
2,100,2,3,PHQ_8Sleep,2.419215,9,0.319661,45
3,100,3,4,PHQ_8Tired,2.383127,6,0.308466,21
4,100,4,5,PHQ_8Appetite,2.235897,3,0.132492,22
5,100,5,6,PHQ_8Failure,2.278898,3,0.478824,43
6,100,6,7,PHQ_8Concentrating,2.345040,2,0.220881,33
7,100,7,8,PHQ_8Moving,1.793559,9,0.135560,3

In [73]:
video_seed1234_results, video_seed1234_summary_df = train_all_video_questions_for_seed(seed=1234)
display(video_seed1234_summary_df)

####################################################################################################
开始训练Video-only全部问题：Seed=1234
####################################################################################################
====================================================================================================
开始训练：Seed=1234，Q1，PHQ_8NoInterest
类别数量： [81, 57, 20, 5]
ImbOLL权重： [1.4185717105865479, 1.6910496950149536, 2.854820728302002, 5.709641456604004]
====================================================================================================
Epoch 01/50 | Train Loss 2.263757 | Val Loss 2.502578 | Val CCC 0.107366 | Val Acc 0.327273 | Val RMSE 0.972345 | 0.71s
Epoch 02/50 | Train Loss 2.048276 | Val Loss 2.692895 | Val CCC 0.165376 | Val Acc 0.527273 | Val RMSE 0.943880 | 0.75s
Epoch 03/50 | Train Loss 2.107237 | Val Loss 2.505362 | Val CCC 0.034351 | Val Acc 0.472727 | Val RMSE 0.914529 | 0.62s
Epoch 04/50 | Train Loss 2.024514 | Val Loss 2.530042 | Val CCC 0.200238 | Val Acc 0.418182 | Val RMSE 1.053134 | 0.53s
Epoch 05/50 | Train Loss 2.006978 | Val Loss 2.540952 | Val CCC 0.169611 | Val Acc 0.509091 | Val RMSE 0.924416 | 0.64s
Epoch 06/50 | Train Loss 2.016927 | Val Loss 2.567376 | Val CCC 0.151473 | Val Acc 0.509091 | Val RMSE 0.894427 | 0.47s
Epoch 07/50 | Train Loss 2.050305 | Val Loss 2.543296 | Val CCC 0.123273 | Val Acc 0.490909 | Val RMSE 0.904534 | 0.60s
Epoch 08/50 | Train Loss 2.010094 | Val Loss 2.629604 | Val CCC 0.124147 | Val Acc 0.418182 | Val RMSE 0.943880 | 0.48s
Epoch 09/50 | Train Loss 1.965027 | Val Loss 2.543607 | Val CCC 0.123273 | Val Acc 0.490909 | Val RMSE 0.904534 | 0.46s
Epoch 10/50 | Train Loss 2.044394 | Val Loss 2.535234 | Val CCC 0.091210 | Val Acc 0.454545 | Val RMSE 0.953463 | 0.45s
Epoch 11/50 | Train Loss 1.986291 | Val Loss 2.644785 | Val CCC 0.174705 | Val Acc 0.400000 | Val RMSE 1.009050 | 1.09s
Epoch 12/50 | Train Loss 1.961478 | Val Loss 2.522833 | Val CCC 0.187343 | Val Acc 0.400000 | Val RMSE 0.981650 | 0.48s
Epoch 13/50 | Train Loss 1.923249 | Val Loss 2.559750 | Val CCC 0.083021 | Val Acc 0.472727 | Val RMSE 0.943880 | 0.47s
Epoch 14/50 | Train Loss 1.980597 | Val Loss 2.649053 | Val CCC 0.138249 | Val Acc 0.436364 | Val RMSE 1.111919 | 0.47s
Epoch 15/50 | Train Loss 1.884049 | Val Loss 2.452970 | Val CCC 0.216524 | Val Acc 0.490909 | Val RMSE 0.904534 | 0.44s
Epoch 16/50 | Train Loss 2.005919 | Val Loss 2.555800 | Val CCC 0.008678 | Val Acc 0.381818 | Val RMSE 0.990867 | 0.59s
Epoch 17/50 | Train Loss 1.959757 | Val Loss 2.991758 | Val CCC 0.002316 | Val Acc 0.454545 | Val RMSE 0.924416 | 0.46s
Epoch 18/50 | Train Loss 1.962231 | Val Loss 3.056789 | Val CCC 0.078431 | Val Acc 0.418182 | Val RMSE 0.924416 | 0.45s
Epoch 19/50 | Train Loss 1.940724 | Val Loss 2.687750 | Val CCC 0.124879 | Val Acc 0.381818 | Val RMSE 1.095445 | 0.45s
Epoch 20/50 | Train Loss 1.830550 | Val Loss 4.826765 | Val CCC 0.068783 | Val Acc 0.527273 | Val RMSE 1.078720 | 0.45s
Epoch 21/50 | Train Loss 1.800153 | Val Loss 2.933395 | Val CCC 0.111311 | Val Acc 0.418182 | Val RMSE 1.144155 | 0.64s
Epoch 22/50 | Train Loss 1.802625 | Val Loss 2.761937 | Val CCC 0.097244 | Val Acc 0.490909 | Val RMSE 0.981650 | 0.44s
Epoch 23/50 | Train Loss 1.757023 | Val Loss 3.346450 | Val CCC 0.109739 | Val Acc 0.436364 | Val RMSE 1.035725 | 0.44s
Epoch 24/50 | Train Loss 1.784190 | Val Loss 2.815470 | Val CCC 0.160798 | Val Acc 0.454545 | Val RMSE 0.972345 | 0.44s
Epoch 25/50 | Train Loss 1.590712 | Val Loss 3.720017 | Val CCC 0.118807 | Val Acc 0.472727 | Val RMSE 1.087115 | 0.45s
Epoch 26/50 | Train Loss 1.737704 | Val Loss 2.592215 | Val CCC 0.331347 | Val Acc 0.436364 | Val RMSE 0.962950 | 0.45s
Epoch 27/50 | Train Loss 1.573644 | Val Loss 3.385031 | Val CCC 0.075032 | Val Acc 0.436364 | Val RMSE 1.087115 | 0.45s
Epoch 28/50 | Train Loss 1.630981 | Val Loss 3.760832 | Val CCC 0.138913 | Val Acc 0.545455 | Val RMSE 1.000000 | 0.45s
Epoch 29/50 | Train Loss 1.462327 | Val Loss 3.065654 | Val CCC 0.189072 | Val Acc 0.418182 | Val RMSE 1.111919 | 0.45s
Epoch 30/50 | Train Loss 1.443110 | Val Loss 3.899003 | Val CCC 0.088563 | Val Acc 0.545455 | Val RMSE 1.053134 | 0.45s
Epoch 31/50 | Train Loss 1.554858 | Val Loss 3.098232 | Val CCC 0.178423 | Val Acc 0.454545 | Val RMSE 1.144155 | 0.46s
Epoch 32/50 | Train Loss 1.412585 | Val Loss 3.538778 | Val CCC 0.144025 | Val Acc 0.490909 | Val RMSE 1.035725 | 0.49s
Epoch 33/50 | Train Loss 1.379391 | Val Loss 4.140678 | Val CCC -0.027682 | Val Acc 0.472727 | Val RMSE 1.213560 | 0.47s
Epoch 34/50 | Train Loss 1.339012 | Val Loss 3.157994 | Val CCC 0.291317 | Val Acc 0.472727 | Val RMSE 0.914529 | 0.47s
Epoch 35/50 | Train Loss 1.349005 | Val Loss 4.163497 | Val CCC 0.066478 | Val Acc 0.436364 | Val RMSE 1.144155 | 0.48s
Epoch 36/50 | Train Loss 1.338628 | Val Loss 2.927362 | Val CCC 0.196583 | Val Acc 0.381818 | Val RMSE 1.035725 | 0.48s
Epoch 37/50 | Train Loss 1.297958 | Val Loss 5.929310 | Val CCC 0.070114 | Val Acc 0.454545 | Val RMSE 1.111919 | 0.47s
Epoch 38/50 | Train Loss 1.429230 | Val Loss 3.327804 | Val CCC 0.251052 | Val Acc 0.400000 | Val RMSE 1.000000 | 0.46s
Epoch 39/50 | Train Loss 1.210502 | Val Loss 3.784790 | Val CCC 0.084544 | Val Acc 0.509091 | Val RMSE 1.070259 | 0.45s
Epoch 40/50 | Train Loss 1.360951 | Val Loss 6.068316 | Val CCC -0.025996 | Val Acc 0.272727 | Val RMSE 1.678744 | 0.45s
Epoch 41/50 | Train Loss 1.703469 | Val Loss 3.426786 | Val CCC 0.094650 | Val Acc 0.400000 | Val RMSE 1.009050 | 0.46s
Epoch 42/50 | Train Loss 1.067826 | Val Loss 3.416208 | Val CCC 0.246225 | Val Acc 0.381818 | Val RMSE 1.035725 | 0.47s
Epoch 43/50 | Train Loss 1.376215 | Val Loss 4.399781 | Val CCC 0.101357 | Val Acc 0.436364 | Val RMSE 1.035725 | 0.45s
Epoch 44/50 | Train Loss 1.151448 | Val Loss 4.997389 | Val CCC -0.067090 | Val Acc 0.363636 | Val RMSE 1.394796 | 0.45s
Epoch 45/50 | Train Loss 1.152994 | Val Loss 3.714634 | Val CCC 0.226460 | Val Acc 0.327273 | Val RMSE 1.035725 | 0.45s
Epoch 46/50 | Train Loss 1.017019 | Val Loss 4.204427 | Val CCC 0.069625 | Val Acc 0.400000 | Val RMSE 1.120065 | 0.45s
Epoch 47/50 | Train Loss 1.254360 | Val Loss 4.119262 | Val CCC 0.154259 | Val Acc 0.454545 | Val RMSE 1.070259 | 0.46s
Epoch 48/50 | Train Loss 1.035922 | Val Loss 3.565367 | Val CCC 0.232272 | Val Acc 0.454545 | Val RMSE 0.953463 | 0.45s
Epoch 49/50 | Train Loss 1.391987 | Val Loss 3.419556 | Val CCC 0.058906 | Val Acc 0.509091 | Val RMSE 1.053134 | 0.46s
Epoch 50/50 | Train Loss 1.277366 | Val Loss 3.968120 | Val CCC 0.134944 | Val Acc 0.454545 | Val RMSE 1.120065 | 0.47s
====================================================================================================
训练完成：Seed=1234，Q1
最佳Val Loss：2.452970，Epoch=15
最佳Val CCC：0.331347，Epoch=26
====================================================================================================
====================================================================================================
开始训练：Seed=1234，Q2，PHQ_8Depressed
类别数量： [68, 63, 18, 14]
ImbOLL权重： [1.548243761062622, 1.6085091829299927, 3.009244918823242, 3.412163257598877]
====================================================================================================
Epoch 01/50 | Train Loss 2.645931 | Val Loss 2.441732 | Val CCC 0.137812 | Val Acc 0.345455 | Val RMSE 1.286291 | 0.47s
Epoch 02/50 | Train Loss 2.280080 | Val Loss 2.291186 | Val CCC 0.129241 | Val Acc 0.418182 | Val RMSE 0.943880 | 0.46s
Epoch 03/50 | Train Loss 2.260461 | Val Loss 2.328227 | Val CCC 0.106136 | Val Acc 0.327273 | Val RMSE 0.943880 | 0.44s
Epoch 04/50 | Train Loss 2.249192 | Val Loss 2.313978 | Val CCC 0.000000 | Val Acc 0.345455 | Val RMSE 0.934199 | 0.44s
Epoch 05/50 | Train Loss 2.238715 | Val Loss 2.344002 | Val CCC 0.176687 | Val Acc 0.400000 | Val RMSE 1.053134 | 0.48s
Epoch 06/50 | Train Loss 2.304222 | Val Loss 2.314411 | Val CCC 0.010791 | Val Acc 0.400000 | Val RMSE 0.953463 | 0.47s
Epoch 07/50 | Train Loss 2.240757 | Val Loss 2.398353 | Val CCC 0.036991 | Val Acc 0.290909 | Val RMSE 1.136182 | 0.48s
Epoch 08/50 | Train Loss 2.244444 | Val Loss 2.381304 | Val CCC 0.000000 | Val Acc 0.345455 | Val RMSE 0.934199 | 0.47s
Epoch 09/50 | Train Loss 2.223304 | Val Loss 2.310361 | Val CCC 0.041204 | Val Acc 0.363636 | Val RMSE 1.000000 | 0.47s
Epoch 10/50 | Train Loss 2.217470 | Val Loss 2.405901 | Val CCC 0.112026 | Val Acc 0.363636 | Val RMSE 0.943880 | 0.47s
Epoch 11/50 | Train Loss 2.212799 | Val Loss 2.373084 | Val CCC 0.098976 | Val Acc 0.381818 | Val RMSE 0.934199 | 0.45s
Epoch 12/50 | Train Loss 2.261448 | Val Loss 2.387689 | Val CCC 0.111639 | Val Acc 0.254545 | Val RMSE 1.111919 | 0.45s
Epoch 13/50 | Train Loss 2.126784 | Val Loss 2.444063 | Val CCC 0.098918 | Val Acc 0.400000 | Val RMSE 0.981650 | 0.45s
Epoch 14/50 | Train Loss 2.181551 | Val Loss 2.408522 | Val CCC 0.143511 | Val Acc 0.381818 | Val RMSE 0.962950 | 0.45s
Epoch 15/50 | Train Loss 2.119346 | Val Loss 2.559770 | Val CCC 0.016260 | Val Acc 0.236364 | Val RMSE 1.183216 | 0.44s
Epoch 16/50 | Train Loss 2.170452 | Val Loss 2.381931 | Val CCC 0.099644 | Val Acc 0.272727 | Val RMSE 1.120065 | 0.44s
Epoch 17/50 | Train Loss 2.140812 | Val Loss 2.605368 | Val CCC 0.079295 | Val Acc 0.327273 | Val RMSE 1.018019 | 0.46s
Epoch 18/50 | Train Loss 1.947203 | Val Loss 3.104251 | Val CCC 0.065487 | Val Acc 0.254545 | Val RMSE 1.321157 | 0.46s
Epoch 19/50 | Train Loss 1.944387 | Val Loss 2.404472 | Val CCC 0.068404 | Val Acc 0.363636 | Val RMSE 0.972345 | 0.45s
Epoch 20/50 | Train Loss 1.939436 | Val Loss 2.673984 | Val CCC 0.015132 | Val Acc 0.290909 | Val RMSE 1.136182 | 0.46s
Epoch 21/50 | Train Loss 1.898359 | Val Loss 2.679994 | Val CCC 0.017136 | Val Acc 0.254545 | Val RMSE 1.152073 | 0.45s
Epoch 22/50 | Train Loss 1.777243 | Val Loss 2.717188 | Val CCC 0.086741 | Val Acc 0.400000 | Val RMSE 1.103713 | 0.45s
Epoch 23/50 | Train Loss 2.000608 | Val Loss 3.666685 | Val CCC 0.097919 | Val Acc 0.272727 | Val RMSE 1.103713 | 0.45s
Epoch 24/50 | Train Loss 1.737021 | Val Loss 3.995989 | Val CCC 0.000000 | Val Acc 0.345455 | Val RMSE 0.934199 | 0.46s
Epoch 25/50 | Train Loss 1.848100 | Val Loss 3.545016 | Val CCC 0.107482 | Val Acc 0.381818 | Val RMSE 1.183216 | 0.44s
Epoch 26/50 | Train Loss 1.706526 | Val Loss 3.527948 | Val CCC 0.104235 | Val Acc 0.290909 | Val RMSE 1.167748 | 0.44s
Epoch 27/50 | Train Loss 1.720483 | Val Loss 3.164860 | Val CCC -0.002307 | Val Acc 0.254545 | Val RMSE 1.198484 | 0.46s
Epoch 28/50 | Train Loss 2.084074 | Val Loss 3.002918 | Val CCC 0.101408 | Val Acc 0.400000 | Val RMSE 1.026911 | 0.46s
Epoch 29/50 | Train Loss 1.866822 | Val Loss 3.013393 | Val CCC 0.101775 | Val Acc 0.327273 | Val RMSE 1.120065 | 0.44s
Epoch 30/50 | Train Loss 1.601466 | Val Loss 3.740668 | Val CCC 0.069652 | Val Acc 0.436364 | Val RMSE 1.111919 | 0.44s
Epoch 31/50 | Train Loss 1.735583 | Val Loss 3.443242 | Val CCC 0.017291 | Val Acc 0.381818 | Val RMSE 1.061731 | 0.44s
Epoch 32/50 | Train Loss 1.836491 | Val Loss 3.477561 | Val CCC 0.104987 | Val Acc 0.363636 | Val RMSE 1.061731 | 0.44s
Epoch 33/50 | Train Loss 1.715251 | Val Loss 2.951139 | Val CCC 0.085575 | Val Acc 0.254545 | Val RMSE 1.111919 | 0.45s
Epoch 34/50 | Train Loss 1.558322 | Val Loss 3.364490 | Val CCC 0.137515 | Val Acc 0.400000 | Val RMSE 1.087115 | 0.44s
Epoch 35/50 | Train Loss 1.465168 | Val Loss 4.708450 | Val CCC 0.100122 | Val Acc 0.454545 | Val RMSE 1.103713 | 0.44s
Epoch 36/50 | Train Loss 1.490290 | Val Loss 3.565541 | Val CCC 0.063830 | Val Acc 0.400000 | Val RMSE 1.009050 | 0.44s
Epoch 37/50 | Train Loss 1.419393 | Val Loss 4.033657 | Val CCC 0.166065 | Val Acc 0.418182 | Val RMSE 1.070259 | 0.47s
Epoch 38/50 | Train Loss 1.676038 | Val Loss 4.597464 | Val CCC 0.101775 | Val Acc 0.327273 | Val RMSE 1.120065 | 0.44s
Epoch 39/50 | Train Loss 1.619479 | Val Loss 6.092645 | Val CCC 0.080000 | Val Acc 0.272727 | Val RMSE 1.293340 | 0.44s
Epoch 40/50 | Train Loss 1.652633 | Val Loss 5.665323 | Val CCC 0.064236 | Val Acc 0.272727 | Val RMSE 1.334848 | 0.44s
Epoch 41/50 | Train Loss 1.553203 | Val Loss 3.600591 | Val CCC 0.097919 | Val Acc 0.309091 | Val RMSE 1.103713 | 0.44s
Epoch 42/50 | Train Loss 1.352027 | Val Loss 6.821538 | Val CCC 0.195862 | Val Acc 0.345455 | Val RMSE 1.388263 | 0.44s
Epoch 43/50 | Train Loss 1.692233 | Val Loss 3.991645 | Val CCC 0.067332 | Val Acc 0.290909 | Val RMSE 1.111919 | 0.45s
Epoch 44/50 | Train Loss 1.310815 | Val Loss 3.925303 | Val CCC 0.098361 | Val Acc 0.381818 | Val RMSE 1.167748 | 0.44s
Epoch 45/50 | Train Loss 1.186099 | Val Loss 6.845922 | Val CCC 0.109155 | Val Acc 0.254545 | Val RMSE 1.293340 | 0.46s
Epoch 46/50 | Train Loss 1.540506 | Val Loss 4.505219 | Val CCC 0.104987 | Val Acc 0.345455 | Val RMSE 1.061731 | 0.47s
Epoch 47/50 | Train Loss 1.321093 | Val Loss 4.407277 | Val CCC 0.144611 | Val Acc 0.345455 | Val RMSE 1.018019 | 0.45s
Epoch 48/50 | Train Loss 1.255116 | Val Loss 4.909487 | Val CCC 0.192661 | Val Acc 0.381818 | Val RMSE 1.206045 | 0.45s
Epoch 49/50 | Train Loss 1.341274 | Val Loss 4.160837 | Val CCC 0.089356 | Val Acc 0.381818 | Val RMSE 1.070259 | 0.45s
Epoch 50/50 | Train Loss 1.284755 | Val Loss 3.523131 | Val CCC 0.109739 | Val Acc 0.345455 | Val RMSE 1.035725 | 0.44s
====================================================================================================
训练完成：Seed=1234，Q2
最佳Val Loss：2.291186，Epoch=2
最佳Val CCC：0.195862，Epoch=42
====================================================================================================
====================================================================================================
开始训练：Seed=1234，Q3，PHQ_8Sleep
类别数量： [69, 40, 27, 27]
ImbOLL权重： [1.5369837284088135, 2.018662929534912, 2.457038164138794, 2.457038164138794]
====================================================================================================
Epoch 01/50 | Train Loss 2.805452 | Val Loss 2.467773 | Val CCC 0.062410 | Val Acc 0.309091 | Val RMSE 1.035725 | 0.45s
Epoch 02/50 | Train Loss 2.623400 | Val Loss 2.466308 | Val CCC -0.036060 | Val Acc 0.327273 | Val RMSE 1.128152 | 0.45s
Epoch 03/50 | Train Loss 2.620251 | Val Loss 2.489008 | Val CCC 0.150485 | Val Acc 0.272727 | Val RMSE 1.128152 | 0.48s
Epoch 04/50 | Train Loss 2.615333 | Val Loss 2.497904 | Val CCC 0.031603 | Val Acc 0.290909 | Val RMSE 1.190874 | 0.45s
Epoch 05/50 | Train Loss 2.595658 | Val Loss 2.455775 | Val CCC 0.119504 | Val Acc 0.309091 | Val RMSE 1.136182 | 0.44s
Epoch 06/50 | Train Loss 2.565015 | Val Loss 2.472189 | Val CCC 0.000000 | Val Acc 0.309091 | Val RMSE 1.061731 | 0.48s
Epoch 07/50 | Train Loss 2.572554 | Val Loss 2.447470 | Val CCC 0.064671 | Val Acc 0.309091 | Val RMSE 1.136182 | 0.47s
Epoch 08/50 | Train Loss 2.540399 | Val Loss 2.451437 | Val CCC 0.200753 | Val Acc 0.345455 | Val RMSE 0.990867 | 0.45s
Epoch 09/50 | Train Loss 2.506811 | Val Loss 2.483663 | Val CCC 0.054898 | Val Acc 0.254545 | Val RMSE 1.183216 | 0.45s
Epoch 10/50 | Train Loss 2.435392 | Val Loss 2.462476 | Val CCC 0.130713 | Val Acc 0.309091 | Val RMSE 1.159937 | 0.45s
Epoch 11/50 | Train Loss 2.583299 | Val Loss 2.681760 | Val CCC 0.137789 | Val Acc 0.327273 | Val RMSE 1.175508 | 0.47s
Epoch 12/50 | Train Loss 2.549273 | Val Loss 2.548680 | Val CCC 0.074234 | Val Acc 0.290909 | Val RMSE 1.190874 | 0.48s
Epoch 13/50 | Train Loss 2.413566 | Val Loss 2.424653 | Val CCC 0.112441 | Val Acc 0.327273 | Val RMSE 1.061731 | 0.46s
Epoch 14/50 | Train Loss 2.363765 | Val Loss 2.493320 | Val CCC 0.130926 | Val Acc 0.290909 | Val RMSE 1.070259 | 0.46s
Epoch 15/50 | Train Loss 2.262498 | Val Loss 2.522350 | Val CCC 0.185503 | Val Acc 0.327273 | Val RMSE 1.175508 | 0.46s
Epoch 16/50 | Train Loss 2.251017 | Val Loss 2.656140 | Val CCC 0.019589 | Val Acc 0.309091 | Val RMSE 1.286291 | 0.44s
Epoch 17/50 | Train Loss 2.159547 | Val Loss 2.922617 | Val CCC 0.136454 | Val Acc 0.309091 | Val RMSE 1.414214 | 0.44s
Epoch 18/50 | Train Loss 2.299917 | Val Loss 2.629946 | Val CCC 0.163183 | Val Acc 0.272727 | Val RMSE 1.286291 | 0.44s
Epoch 19/50 | Train Loss 2.197253 | Val Loss 2.649222 | Val CCC 0.121094 | Val Acc 0.327273 | Val RMSE 1.279204 | 0.43s
Epoch 20/50 | Train Loss 2.104570 | Val Loss 2.566902 | Val CCC 0.253203 | Val Acc 0.345455 | Val RMSE 1.136182 | 0.43s
Epoch 21/50 | Train Loss 2.112646 | Val Loss 2.491032 | Val CCC 0.143879 | Val Acc 0.381818 | Val RMSE 1.159937 | 0.44s
Epoch 22/50 | Train Loss 2.199435 | Val Loss 2.574851 | Val CCC 0.163360 | Val Acc 0.309091 | Val RMSE 1.293340 | 0.45s
Epoch 23/50 | Train Loss 1.988315 | Val Loss 3.256787 | Val CCC 0.168507 | Val Acc 0.345455 | Val RMSE 1.272078 | 0.48s
Epoch 24/50 | Train Loss 2.093233 | Val Loss 5.759437 | Val CCC 0.112410 | Val Acc 0.163636 | Val RMSE 1.778661 | 0.47s
Epoch 25/50 | Train Loss 2.674472 | Val Loss 2.604753 | Val CCC 0.177510 | Val Acc 0.327273 | Val RMSE 1.183216 | 0.46s
Epoch 26/50 | Train Loss 1.954958 | Val Loss 2.714786 | Val CCC 0.306126 | Val Acc 0.363636 | Val RMSE 1.228451 | 0.47s
Epoch 27/50 | Train Loss 2.089097 | Val Loss 2.856200 | Val CCC 0.384895 | Val Acc 0.472727 | Val RMSE 1.183216 | 0.47s
Epoch 28/50 | Train Loss 1.862509 | Val Loss 2.825283 | Val CCC 0.161338 | Val Acc 0.290909 | Val RMSE 1.300350 | 0.44s
Epoch 29/50 | Train Loss 1.976419 | Val Loss 3.140844 | Val CCC 0.144506 | Val Acc 0.290909 | Val RMSE 1.501514 | 0.44s
Epoch 30/50 | Train Loss 1.765958 | Val Loss 3.272402 | Val CCC 0.275549 | Val Acc 0.400000 | Val RMSE 1.257704 | 0.44s
Epoch 31/50 | Train Loss 1.955574 | Val Loss 3.481666 | Val CCC 0.164379 | Val Acc 0.309091 | Val RMSE 1.228451 | 0.44s
Epoch 32/50 | Train Loss 1.832538 | Val Loss 3.367063 | Val CCC 0.222476 | Val Acc 0.218182 | Val RMSE 1.341641 | 0.46s
Epoch 33/50 | Train Loss 1.795685 | Val Loss 3.410273 | Val CCC 0.225562 | Val Acc 0.327273 | Val RMSE 1.375103 | 0.45s
Epoch 34/50 | Train Loss 1.678340 | Val Loss 4.238526 | Val CCC 0.228104 | Val Acc 0.309091 | Val RMSE 1.198484 | 0.46s
Epoch 35/50 | Train Loss 1.752236 | Val Loss 3.256881 | Val CCC 0.220374 | Val Acc 0.381818 | Val RMSE 1.167748 | 0.45s
Epoch 36/50 | Train Loss 1.623155 | Val Loss 3.049237 | Val CCC 0.227383 | Val Acc 0.327273 | Val RMSE 1.167748 | 0.44s
Epoch 37/50 | Train Loss 1.964733 | Val Loss 4.039918 | Val CCC 0.171710 | Val Acc 0.272727 | Val RMSE 1.394796 | 0.45s
Epoch 38/50 | Train Loss 1.903304 | Val Loss 4.208173 | Val CCC 0.234956 | Val Acc 0.345455 | Val RMSE 1.293340 | 0.44s
Epoch 39/50 | Train Loss 1.680040 | Val Loss 5.192680 | Val CCC 0.216233 | Val Acc 0.290909 | Val RMSE 1.293340 | 0.44s
Epoch 40/50 | Train Loss 1.811611 | Val Loss 5.050264 | Val CCC 0.141319 | Val Acc 0.290909 | Val RMSE 1.452271 | 0.44s
Epoch 41/50 | Train Loss 1.782604 | Val Loss 3.789661 | Val CCC 0.214820 | Val Acc 0.236364 | Val RMSE 1.235829 | 0.43s
Epoch 42/50 | Train Loss 1.649984 | Val Loss 3.912836 | Val CCC 0.291921 | Val Acc 0.381818 | Val RMSE 1.206045 | 0.43s
Epoch 43/50 | Train Loss 1.643605 | Val Loss 3.169665 | Val CCC 0.222920 | Val Acc 0.345455 | Val RMSE 1.213560 | 0.43s
Epoch 44/50 | Train Loss 1.714204 | Val Loss 6.991698 | Val CCC 0.312399 | Val Acc 0.327273 | Val RMSE 1.243163 | 0.43s
Epoch 45/50 | Train Loss 1.536849 | Val Loss 4.539035 | Val CCC 0.289034 | Val Acc 0.400000 | Val RMSE 1.272078 | 0.43s
Epoch 46/50 | Train Loss 1.562869 | Val Loss 3.936110 | Val CCC 0.325980 | Val Acc 0.418182 | Val RMSE 1.206045 | 0.43s
Epoch 47/50 | Train Loss 1.541553 | Val Loss 7.183522 | Val CCC 0.128533 | Val Acc 0.254545 | Val RMSE 1.507557 | 0.43s
Epoch 48/50 | Train Loss 1.556034 | Val Loss 8.562917 | Val CCC 0.211527 | Val Acc 0.290909 | Val RMSE 1.334848 | 0.43s
Epoch 49/50 | Train Loss 2.053043 | Val Loss 3.523323 | Val CCC 0.107797 | Val Acc 0.327273 | Val RMSE 1.300350 | 0.43s
Epoch 50/50 | Train Loss 1.538241 | Val Loss 3.473965 | Val CCC 0.194434 | Val Acc 0.363636 | Val RMSE 1.206045 | 0.46s
====================================================================================================
训练完成：Seed=1234，Q3
最佳Val Loss：2.424653，Epoch=13
最佳Val CCC：0.384895，Epoch=27

,Seed,Question_Index,Question_Number,Question_Name,Best_Val_Loss,Best_Loss_Epoch,Best_Val_CCC,Best_CCC_Epoch
0,1234,0,1,PHQ_8NoInterest,2.452970,15,0.331347,26
1,1234,1,2,PHQ_8Depressed,2.291186,2,0.195862,42
2,1234,2,3,PHQ_8Sleep,2.424653,13,0.384895,27
3,1234,3,4,PHQ_8Tired,2.391727,9,0.273231,43
4,1234,4,5,PHQ_8Appetite,2.215777,2,0.213037,7
5,1234,5,6,PHQ_8Failure,2.234637,42,0.442278,49
6,1234,6,7,PHQ_8Concentrating,2.295482,1,0.213162,36
7,1234,7,8,PHQ_8Moving,1.867959,5,0.111516,2

In [74]:
all_video_training_results = {}
all_video_training_results[42] = video_seed42_results
all_video_training_results[100] = video_seed100_results
all_video_training_results[1234] = video_seed1234_results

In [75]:
for seed, seed_results in all_video_training_results.items():
    print("=" * 70)
    print("Seed：", seed)
    print("问题数量：", len(seed_results))
    print("Best Loss全部存在：", all(result["best_loss_path"].exists() for result in seed_results))
    print("Best CCC全部存在：", all(result["best_ccc_path"].exists() for result in seed_results))
    print("Last全部存在：", all(result["last_path"].exists() for result in seed_results))
    print("History全部存在：", all(result["history_path"].exists() for result in seed_results))

======================================================================
Seed： 42
问题数量： 8
Best Loss全部存在： True
Best CCC全部存在： True
Last全部存在： True
History全部存在： True
======================================================================
Seed： 100
问题数量： 8
Best Loss全部存在： True
Best CCC全部存在： True
Last全部存在： True
History全部存在： True
======================================================================
Seed： 1234
问题数量： 8
Best Loss全部存在： True
Best CCC全部存在： True
Last全部存在： True
History全部存在： True

In [76]:
video_seed100_validation_result = evaluate_video_seed_on_validation(seed=100)
video_seed1234_validation_result = evaluate_video_seed_on_validation(seed=1234)

Q1 | Epoch 06 | Val CCC 0.279613
Q2 | Epoch 04 | Val CCC 0.212202
Q3 | Epoch 45 | Val CCC 0.319661
Q4 | Epoch 21 | Val CCC 0.308466
Q5 | Epoch 22 | Val CCC 0.132492
Q6 | Epoch 43 | Val CCC 0.478824
Q7 | Epoch 33 | Val CCC 0.220881
Q8 | Epoch 03 | Val CCC 0.135560
======================================================================
验证参与者数量： 55
总分CCC：0.360905
总分RMSE：5.623004
总分MAE：4.600000
完全相等比例：0.054545
预测总分范围：0～16
真实总分范围：0～20
预测文件： /workspace/E-DAIC/checkpoints/phq8_video_paperlike/seed_100_validation_predictions.csv
Q1 | Epoch 26 | Val CCC 0.331347
Q2 | Epoch 42 | Val CCC 0.195862
Q3 | Epoch 27 | Val CCC 0.384895
Q4 | Epoch 43 | Val CCC 0.273231
Q5 | Epoch 07 | Val CCC 0.213037
Q6 | Epoch 49 | Val CCC 0.442278
Q7 | Epoch 36 | Val CCC 0.213162
Q8 | Epoch 02 | Val CCC 0.111516
======================================================================
验证参与者数量： 55
总分CCC：0.355454
总分RMSE：5.916080
总分MAE：4.927273
完全相等比例：0.054545
预测总分范围：0～18
真实总分范围：0～20
预测文件： /workspace/E-DAIC/checkpoints/phq8_video_paperlike/seed_1234_validation_predictions.csv

In [77]:
all_video_validation_results = [video_seed42_validation_result, video_seed100_validation_result, video_seed1234_validation_result]
video_validation_seed_rows = []
for result in all_video_validation_results:
    video_validation_seed_rows.append({"Seed": result["seed"], "Sample_Count": result["sample_count"], "CCC": result["ccc"], "RMSE": result["rmse"], "MAE": result["mae"], "Exact_Accuracy": result["exact_accuracy"], "Predicted_Min": int(result["predicted_totals"].min()), "Predicted_Max": int(result["predicted_totals"].max()), "True_Min": int(result["true_totals"].min()), "True_Max": int(result["true_totals"].max())})
video_validation_seed_summary_df = pd.DataFrame(video_validation_seed_rows)
display(video_validation_seed_summary_df)

,Seed,Sample_Count,CCC,RMSE,MAE,Exact_Accuracy,Predicted_Min,Predicted_Max,True_Min,True_Max
0,42,55,0.356659,5.642372,4.600000,0.090909,0,16,0,20
1,100,55,0.360905,5.623004,4.600000,0.054545,0,16,0,20
2,1234,55,0.355454,5.916080,4.927273,0.054545,0,18,0,20

In [78]:
video_validation_statistics_rows = []
for metric_name in ["CCC", "RMSE", "MAE", "Exact_Accuracy"]:
    video_validation_statistics_rows.append({"Metric": metric_name, "Mean": video_validation_seed_summary_df[metric_name].mean(), "Std": video_validation_seed_summary_df[metric_name].std(ddof=1)})
video_validation_statistics_df = pd.DataFrame(video_validation_statistics_rows)
display(video_validation_statistics_df)

           Metric      Mean       Std
0             CCC  0.357673  0.002863
1            RMSE  5.727152  0.163903
2             MAE  4.709091  0.188951
3  Exact_Accuracy  0.066667  0.020995

In [79]:
video_validation_seed_summary_path = VIDEO_CHECKPOINT_ROOT / "three_seed_validation_results.csv"
video_validation_statistics_path = VIDEO_CHECKPOINT_ROOT / "three_seed_validation_summary.csv"
video_validation_seed_summary_df.to_csv(video_validation_seed_summary_path, index=False)
video_validation_statistics_df.to_csv(video_validation_statistics_path, index=False)
print("逐Seed验证结果：", video_validation_seed_summary_path)
print("三Seed验证汇总：", video_validation_statistics_path)
print("逐Seed文件存在：", video_validation_seed_summary_path.exists())
print("汇总文件存在：", video_validation_statistics_path.exists())

逐Seed验证结果： /workspace/E-DAIC/checkpoints/phq8_video_paperlike/three_seed_validation_results.csv
三Seed验证汇总： /workspace/E-DAIC/checkpoints/phq8_video_paperlike/three_seed_validation_summary.csv
逐Seed文件存在： True
汇总文件存在： True

In [80]:
print("测试集字段：", video_test_metadata_df.columns.tolist())
print("测试参与者数量：", len(video_test_metadata_df))
print("测试集包含637：", 637 in video_test_metadata_df["Participant_ID"].astype(int).tolist())

测试集字段： ['Participant_ID', 'Gender', 'PHQ_Binary', 'PHQ_Score', 'PCL-C (PTSD)', 'PTSD Severity']
测试参与者数量： 56
测试集包含637： True

In [83]:
class VideoPHQ8TestDataset(Dataset):
    def __init__(self, metadata_df):
        super().__init__()
        self.metadata_df = metadata_df.reset_index(drop=True).copy()
        if "PHQ_Score" not in self.metadata_df.columns:
            raise KeyError(f"测试数据缺少PHQ8_Score字段，现有字段：{self.metadata_df.columns.tolist()}")
        self.participant_ids = self.metadata_df["Participant_ID"].astype(int).tolist()
        self.true_totals = torch.tensor(self.metadata_df["PHQ_Score"].to_numpy(), dtype=torch.long)
        video_feature_list = []
        video_mask_list = []
        for index, participant_id in enumerate(self.participant_ids):
            cache_path = VIDEO_CACHE_DIR / f"{participant_id}.pt"
            if not cache_path.exists():
                raise FileNotFoundError(f"Video测试缓存不存在：{cache_path}")
            cache = torch.load(cache_path, map_location="cpu", weights_only=False)
            video_features = cache["video_features"].float()
            video_padding_mask = cache["padding_mask"].bool()
            if int(cache["participant_id"]) != participant_id:
                raise RuntimeError(f"参与者编号错误：预期{participant_id}，实际{cache['participant_id']}")
            if video_features.shape != (MAX_TURNS, VIDEO_FEATURE_DIM):
                raise RuntimeError(f"参与者{participant_id}特征形状错误：{video_features.shape}")
            if video_padding_mask.shape != (MAX_TURNS,):
                raise RuntimeError(f"参与者{participant_id}Mask形状错误：{video_padding_mask.shape}")
            if not torch.isfinite(video_features).all():
                raise RuntimeError(f"参与者{participant_id}特征包含NaN或Inf")
            video_feature_list.append(video_features)
            video_mask_list.append(video_padding_mask)
            if (index + 1) % 20 == 0 or index + 1 == len(self.participant_ids):
                print(f"test Dataset加载进度：{index + 1}/{len(self.participant_ids)}")
        self.video_features = torch.stack(video_feature_list, dim=0)
        self.video_masks = torch.stack(video_mask_list, dim=0)
        if self.video_features.shape != (len(self.participant_ids), MAX_TURNS, VIDEO_FEATURE_DIM):
            raise RuntimeError(f"测试特征整体形状错误：{self.video_features.shape}")
        if self.video_masks.shape != (len(self.participant_ids), MAX_TURNS):
            raise RuntimeError(f"测试Mask整体形状错误：{self.video_masks.shape}")

    def __len__(self):
        return len(self.participant_ids)

    def __getitem__(self, index):
        return self.video_features[index], self.video_masks[index], self.true_totals[index], self.participant_ids[index]

In [84]:
video_test_dataset = VideoPHQ8TestDataset(video_test_metadata_df)
video_test_loader = DataLoader(video_test_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=0, drop_last=False)
test_batch_features, test_batch_masks, test_batch_totals, test_batch_participant_ids = next(iter(video_test_loader))
print("测试参与者数量：", len(video_test_dataset))
print("测试批次数：", len(video_test_loader))
print("测试Batch特征：", test_batch_features.shape)
print("测试Batch Mask：", test_batch_masks.shape)
print("测试Batch真实总分：", test_batch_totals.shape)
print("测试Batch参与者：", test_batch_participant_ids)
print("测试特征全部有限：", bool(torch.isfinite(test_batch_features).all()))
print("测试真实总分范围：", int(video_test_dataset.true_totals.min()), "～", int(video_test_dataset.true_totals.max()))

test Dataset加载进度：20/56
test Dataset加载进度：40/56
test Dataset加载进度：56/56
测试参与者数量： 56
测试批次数： 6
测试Batch特征： torch.Size([10, 120, 2048])
测试Batch Mask： torch.Size([10, 120])
测试Batch真实总分： torch.Size([10])
测试Batch参与者： tensor([600, 602, 604, 605, 606, 607, 609, 615, 618, 619])
测试特征全部有限： True
测试真实总分范围： 0 ～ 22

In [85]:
def evaluate_video_seed_on_test(seed):
    question_prediction_list = []
    selected_checkpoint_rows = []
    for question_index in range(len(PHQ8_QUESTION_COLUMNS)):
        checkpoint_path = VIDEO_CHECKPOINT_ROOT / f"seed_{seed}" / f"question_{question_index + 1}" / "best_ccc.pt"
        if not checkpoint_path.exists():
            raise FileNotFoundError(f"Checkpoint不存在：{checkpoint_path}")
        checkpoint = torch.load(checkpoint_path, map_location="cpu", weights_only=False)
        if checkpoint["seed"] != seed:
            raise RuntimeError(f"Checkpoint Seed错误：{checkpoint_path}")
        if checkpoint["question_index"] != question_index:
            raise RuntimeError(f"Checkpoint题号错误：{checkpoint_path}")
        if checkpoint["checkpoint_type"] != "best_ccc":
            raise RuntimeError(f"Checkpoint类型错误：{checkpoint_path}")
        model = VideoOnlyQuestModel().to(device)
        load_result = model.load_state_dict(checkpoint["model_state_dict"], strict=True)
        if load_result.missing_keys or load_result.unexpected_keys:
            raise RuntimeError(f"Checkpoint参数不一致：{checkpoint_path}")
        model.eval()
        batch_prediction_list = []
        with torch.no_grad():
            for video_features, video_masks, true_totals, participant_ids in video_test_loader:
                logits = model(video_features.to(device), video_masks.to(device))
                batch_prediction_list.append(logits.argmax(dim=1).cpu())
        question_predictions = torch.cat(batch_prediction_list)
        if len(question_predictions) != len(video_test_dataset):
            raise RuntimeError(f"Q{question_index + 1}预测数量错误")
        question_prediction_list.append(question_predictions)
        selected_checkpoint_rows.append({"Seed": seed, "Question_Index": question_index, "Question_Number": question_index + 1, "Question_Name": PHQ8_QUESTION_COLUMNS[question_index], "Checkpoint_Path": str(checkpoint_path), "Checkpoint_Epoch": checkpoint["epoch"], "Validation_CCC": checkpoint["val_metrics"]["ccc"]})
        print(f"Seed {seed} | Q{question_index + 1} | Epoch {checkpoint['epoch']:02d} | Val CCC {checkpoint['val_metrics']['ccc']:.6f}")
        del model
        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
    question_predictions = torch.stack(question_prediction_list, dim=1)
    predicted_totals = question_predictions.sum(dim=1)
    true_totals = video_test_dataset.true_totals.clone()
    total_ccc = calculate_ccc(predicted_totals, true_totals)
    total_rmse = float(torch.sqrt(torch.mean((predicted_totals.float() - true_totals.float()) ** 2)).item())
    total_mae = float(torch.mean(torch.abs(predicted_totals.float() - true_totals.float())).item())
    exact_accuracy = float((predicted_totals == true_totals).float().mean().item())
    prediction_df = pd.DataFrame({"Participant_ID": video_test_dataset.participant_ids})
    for question_index in range(len(PHQ8_QUESTION_COLUMNS)):
        prediction_df[f"Q{question_index + 1}_Predicted"] = question_predictions[:, question_index].numpy()
    prediction_df["Predicted_Total"] = predicted_totals.numpy()
    prediction_df["True_Total"] = true_totals.numpy()
    prediction_path = VIDEO_CHECKPOINT_ROOT / f"seed_{seed}_test_predictions_56.csv"
    selected_checkpoint_path = VIDEO_CHECKPOINT_ROOT / f"seed_{seed}_test_selected_checkpoints.csv"
    prediction_df.to_csv(prediction_path, index=False)
    pd.DataFrame(selected_checkpoint_rows).to_csv(selected_checkpoint_path, index=False)
    print("=" * 70)
    print(f"Video-only Seed {seed}独立测试结果")
    print("=" * 70)
    print("测试参与者数量：", len(prediction_df))
    print(f"CCC：{total_ccc:.6f}")
    print(f"RMSE：{total_rmse:.6f}")
    print(f"MAE：{total_mae:.6f}")
    print(f"完全相等比例：{exact_accuracy:.6f}")
    print(f"预测总分范围：{int(predicted_totals.min())}～{int(predicted_totals.max())}")
    print(f"真实总分范围：{int(true_totals.min())}～{int(true_totals.max())}")
    print("预测文件：", prediction_path)
    return {"seed": seed, "sample_count": len(prediction_df), "ccc": total_ccc, "rmse": total_rmse, "mae": total_mae, "exact_accuracy": exact_accuracy, "predicted_totals": predicted_totals, "true_totals": true_totals, "prediction_path": prediction_path, "selected_checkpoint_path": selected_checkpoint_path}

In [86]:
video_seed42_test_result = evaluate_video_seed_on_test(seed=42)
video_seed100_test_result = evaluate_video_seed_on_test(seed=100)
video_seed1234_test_result = evaluate_video_seed_on_test(seed=1234)

Seed 42 | Q1 | Epoch 02 | Val CCC 0.272326
Seed 42 | Q2 | Epoch 04 | Val CCC 0.224460
Seed 42 | Q3 | Epoch 21 | Val CCC 0.309804
Seed 42 | Q4 | Epoch 40 | Val CCC 0.340570
Seed 42 | Q5 | Epoch 27 | Val CCC 0.144876
Seed 42 | Q6 | Epoch 41 | Val CCC 0.429989
Seed 42 | Q7 | Epoch 09 | Val CCC 0.188525
Seed 42 | Q8 | Epoch 10 | Val CCC 0.226757
======================================================================
Video-only Seed 42独立测试结果
======================================================================
测试参与者数量： 56
CCC：0.159762
RMSE：7.063488
MAE：5.464286
完全相等比例：0.071429
预测总分范围：0～15
真实总分范围：0～22
预测文件： /workspace/E-DAIC/checkpoints/phq8_video_paperlike/seed_42_test_predictions_56.csv
Seed 100 | Q1 | Epoch 06 | Val CCC 0.279613
Seed 100 | Q2 | Epoch 04 | Val CCC 0.212202
Seed 100 | Q3 | Epoch 45 | Val CCC 0.319661
Seed 100 | Q4 | Epoch 21 | Val CCC 0.308466
Seed 100 | Q5 | Epoch 22 | Val CCC 0.132492
Seed 100 | Q6 | Epoch 43 | Val CCC 0.478824
Seed 100 | Q7 | Epoch 33 | Val CCC 0.220881
Seed 100 | Q8 | Epoch 03 | Val CCC 0.135560
======================================================================
Video-only Seed 100独立测试结果
======================================================================
测试参与者数量： 56
CCC：0.153693
RMSE：7.293588
MAE：5.660714
完全相等比例：0.089286
预测总分范围：0～18
真实总分范围：0～22
预测文件： /workspace/E-DAIC/checkpoints/phq8_video_paperlike/seed_100_test_predictions_56.csv
Seed 1234 | Q1 | Epoch 26 | Val CCC 0.331347
Seed 1234 | Q2 | Epoch 42 | Val CCC 0.195862
Seed 1234 | Q3 | Epoch 27 | Val CCC 0.384895
Seed 1234 | Q4 | Epoch 43 | Val CCC 0.273231
Seed 1234 | Q5 | Epoch 07 | Val CCC 0.213037
Seed 1234 | Q6 | Epoch 49 | Val CCC 0.442278
Seed 1234 | Q7 | Epoch 36 | Val CCC 0.213162
Seed 1234 | Q8 | Epoch 02 | Val CCC 0.111516
======================================================================
Video-only Seed 1234独立测试结果
======================================================================
测试参与者数量： 56
CCC：0.074478
RMSE：7.388456
MAE：5.910714
完全相等比例：0.089286
预测总分范围：1～19
真实总分范围：0～22
预测文件： /workspace/E-DAIC/checkpoints/phq8_video_paperlike/seed_1234_test_predictions_56.csv

In [87]:
all_video_test_results = [video_seed42_test_result, video_seed100_test_result, video_seed1234_test_result]
video_test_seed_rows = []
for result in all_video_test_results:
    video_test_seed_rows.append({"Seed": result["seed"], "Sample_Count": result["sample_count"], "CCC": result["ccc"], "RMSE": result["rmse"], "MAE": result["mae"], "Exact_Accuracy": result["exact_accuracy"], "Predicted_Min": int(result["predicted_totals"].min()), "Predicted_Max": int(result["predicted_totals"].max()), "True_Min": int(result["true_totals"].min()), "True_Max": int(result["true_totals"].max())})
video_test_seed_summary_df = pd.DataFrame(video_test_seed_rows)
display(video_test_seed_summary_df)

,Seed,Sample_Count,CCC,RMSE,MAE,Exact_Accuracy,Predicted_Min,Predicted_Max,True_Min,True_Max
0,42,56,0.159762,7.063488,5.464286,0.071429,0,15,0,22
1,100,56,0.153693,7.293588,5.660714,0.089286,0,18,0,22
2,1234,56,0.074478,7.388456,5.910714,0.089286,1,19,0,22

In [88]:
video_three_seed_rows = []
for metric_name in ["CCC", "RMSE", "MAE", "Exact_Accuracy"]:
    video_three_seed_rows.append({"Metric": metric_name, "Mean": video_test_seed_summary_df[metric_name].mean(), "Std": video_test_seed_summary_df[metric_name].std(ddof=1)})
video_three_seed_summary_df = pd.DataFrame(video_three_seed_rows)
display(video_three_seed_summary_df)

           Metric      Mean       Std
0             CCC  0.129311  0.047584
1            RMSE  7.248511  0.167108
2             MAE  5.678571  0.223749
3  Exact_Accuracy  0.083333  0.010310

In [89]:
video_test_seed_summary_path = VIDEO_CHECKPOINT_ROOT / "three_seed_test_results_56.csv"
video_three_seed_summary_path = VIDEO_CHECKPOINT_ROOT / "three_seed_test_summary_56.csv"
video_test_seed_summary_df.to_csv(video_test_seed_summary_path, index=False)
video_three_seed_summary_df.to_csv(video_three_seed_summary_path, index=False)
print("逐Seed测试结果：", video_test_seed_summary_path)
print("三Seed测试汇总：", video_three_seed_summary_path)
print("逐Seed文件存在：", video_test_seed_summary_path.exists())
print("汇总文件存在：", video_three_seed_summary_path.exists())

逐Seed测试结果： /workspace/E-DAIC/checkpoints/phq8_video_paperlike/three_seed_test_results_56.csv
三Seed测试汇总： /workspace/E-DAIC/checkpoints/phq8_video_paperlike/three_seed_test_summary_56.csv
逐Seed文件存在： True
汇总文件存在： True

In [90]:
candidate_excluded_test_id = 637
test_keep_mask_55 = torch.tensor([participant_id != candidate_excluded_test_id for participant_id in video_test_dataset.participant_ids], dtype=torch.bool)
print("排除参与者：", candidate_excluded_test_id)
print("排除前人数：", len(video_test_dataset))
print("排除后人数：", int(test_keep_mask_55.sum()))

排除参与者： 637
排除前人数： 56
排除后人数： 55

In [91]:
video_test_55_rows = []
for result in all_video_test_results:
    predicted_totals_55 = result["predicted_totals"][test_keep_mask_55]
    true_totals_55 = result["true_totals"][test_keep_mask_55]
    ccc_55 = calculate_ccc(predicted_totals_55, true_totals_55)
    rmse_55 = float(torch.sqrt(torch.mean((predicted_totals_55.float() - true_totals_55.float()) ** 2)).item())
    mae_55 = float(torch.mean(torch.abs(predicted_totals_55.float() - true_totals_55.float())).item())
    exact_accuracy_55 = float((predicted_totals_55 == true_totals_55).float().mean().item())
    video_test_55_rows.append({"Seed": result["seed"], "Sample_Count": len(predicted_totals_55), "CCC": ccc_55, "RMSE": rmse_55, "MAE": mae_55, "Exact_Accuracy": exact_accuracy_55})
video_test_55_summary_df = pd.DataFrame(video_test_55_rows)
display(video_test_55_summary_df)

   Seed  Sample_Count       CCC      RMSE       MAE  Exact_Accuracy
0    42            55  0.167893  6.998702  5.381818        0.072727
1   100            55  0.167858  7.208580  5.563636        0.090909
2  1234            55  0.089761  7.306286  5.818182        0.090909

In [92]:
video_three_seed_55_rows = []
for metric_name in ["CCC", "RMSE", "MAE", "Exact_Accuracy"]:
    video_three_seed_55_rows.append({"Metric": metric_name, "Mean": video_test_55_summary_df[metric_name].mean(), "Std": video_test_55_summary_df[metric_name].std(ddof=1)})
video_three_seed_55_summary_df = pd.DataFrame(video_three_seed_55_rows)
display(video_three_seed_55_summary_df)

           Metric      Mean       Std
0             CCC  0.141837  0.045099
1            RMSE  7.171189  0.157164
2             MAE  5.587879  0.219190
3  Exact_Accuracy  0.084848  0.010497

In [93]:
video_test_55_summary_df.to_csv(VIDEO_CHECKPOINT_ROOT / "three_seed_test_results_candidate55.csv", index=False)
video_three_seed_55_summary_df.to_csv(VIDEO_CHECKPOINT_ROOT / "three_seed_test_summary_candidate55.csv", index=False)

## text+vedio

In [94]:
TEXT_CACHE_ROOT = Path("/workspace/E-DAIC/cache/phq8_text_embeddings")
TEXT_CHECKPOINT_ROOT = Path("/workspace/E-DAIC/checkpoints/phq8_text_paperlike")
TEXT_VIDEO_CHECKPOINT_ROOT = Path("/workspace/E-DAIC/checkpoints/phq8_text_video_paperlike")
TEXT_FEATURE_DIM = 768
VIDEO_FEATURE_DIM = 2048
ENCODER_OUTPUT_DIM = 100
FUSION_NUM_EPOCHS = 20
FUSION_LEARNING_RATE = 5e-4
FUSION_ADAM_EPSILON = 1e-8
FUSION_WEIGHT_DECAY = 1e-3
FUSION_DROPOUT = 0.8
FUSION_MLP_FIRST_DROPOUT = 0.8
FUSION_MLP_LAST_DROPOUT = 0.5
TEXT_VIDEO_CHECKPOINT_ROOT.mkdir(parents=True, exist_ok=True)

In [96]:
text_cache_candidates = sorted(TEXT_CACHE_ROOT.rglob("302.pt"))
print("找到的302文本缓存：", text_cache_candidates)
if len(text_cache_candidates) != 1:
    raise RuntimeError(f"预期找到一个302文本缓存，实际找到{len(text_cache_candidates)}个")
TEXT_CACHE_DIR = text_cache_candidates[0].parent
print("正式文本缓存目录：", TEXT_CACHE_DIR)

找到的302文本缓存： [PosixPath('/workspace/E-DAIC/cache/phq8_text_embeddings/distilroberta_842eaed4_turns120_v1/302.pt')]
正式文本缓存目录： /workspace/E-DAIC/cache/phq8_text_embeddings/distilroberta_842eaed4_turns120_v1

In [97]:
def get_text_video_best_loss_paths(question_index, seed):
    text_checkpoint_path = TEXT_CHECKPOINT_ROOT / f"q{question_index + 1}_{PHQ8_QUESTION_COLUMNS[question_index]}" / f"seed_{seed}" / "best_loss.pt"
    video_checkpoint_path = VIDEO_CHECKPOINT_ROOT / f"seed_{seed}" / f"question_{question_index + 1}" / "best_loss.pt"
    if not text_checkpoint_path.exists():
        raise FileNotFoundError(f"文本Best Loss不存在：{text_checkpoint_path}")
    if not video_checkpoint_path.exists():
        raise FileNotFoundError(f"视频Best Loss不存在：{video_checkpoint_path}")
    text_checkpoint = torch.load(text_checkpoint_path, map_location="cpu", weights_only=False)
    video_checkpoint = torch.load(video_checkpoint_path, map_location="cpu", weights_only=False)
    if text_checkpoint["seed"] != seed or text_checkpoint["question_index"] != question_index or text_checkpoint["checkpoint_type"] != "best_loss":
        raise RuntimeError(f"文本Checkpoint元数据错误：{text_checkpoint_path}")
    if video_checkpoint["seed"] != seed or video_checkpoint["question_index"] != question_index or video_checkpoint["checkpoint_type"] != "best_loss":
        raise RuntimeError(f"视频Checkpoint元数据错误：{video_checkpoint_path}")
    return text_checkpoint_path, video_checkpoint_path

In [98]:
q1_text_best_loss_path, q1_video_best_loss_path = get_text_video_best_loss_paths(question_index=0, seed=42)
print("Q1文本Best Loss：", q1_text_best_loss_path)
print("Q1视频Best Loss：", q1_video_best_loss_path)

Q1文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q1_PHQ_8NoInterest/seed_42/best_loss.pt
Q1视频Best Loss： /workspace/E-DAIC/checkpoints/phq8_video_paperlike/seed_42/question_1/best_loss.pt

In [99]:
def load_text_video_cache(participant_id):
    participant_id = int(participant_id)
    text_cache_path = TEXT_CACHE_DIR / f"{participant_id}.pt"
    video_cache_path = VIDEO_CACHE_DIR / f"{participant_id}.pt"
    if not text_cache_path.exists():
        raise FileNotFoundError(f"文本缓存不存在：{text_cache_path}")
    if not video_cache_path.exists():
        raise FileNotFoundError(f"视频缓存不存在：{video_cache_path}")
    text_cache = torch.load(text_cache_path, map_location="cpu", weights_only=False)
    video_cache = torch.load(video_cache_path, map_location="cpu", weights_only=False)
    text_features = text_cache["embeddings"].float()
    text_padding_mask = text_cache["key_padding_mask"].bool()
    video_features = video_cache["video_features"].float()
    video_padding_mask = video_cache["padding_mask"].bool()
    if text_features.shape != (MAX_TURNS, TEXT_FEATURE_DIM):
        raise RuntimeError(f"参与者{participant_id}文本形状错误：{text_features.shape}")
    if text_padding_mask.shape != (MAX_TURNS,):
        raise RuntimeError(f"参与者{participant_id}文本Mask错误：{text_padding_mask.shape}")
    if video_features.shape != (MAX_TURNS, VIDEO_FEATURE_DIM):
        raise RuntimeError(f"参与者{participant_id}视频形状错误：{video_features.shape}")
    if video_padding_mask.shape != (MAX_TURNS,):
        raise RuntimeError(f"参与者{participant_id}视频Mask错误：{video_padding_mask.shape}")
    if not torch.isfinite(text_features).all():
        raise RuntimeError(f"参与者{participant_id}文本包含NaN或Inf")
    if not torch.isfinite(video_features).all():
        raise RuntimeError(f"参与者{participant_id}视频包含NaN或Inf")
    return text_features, text_padding_mask, video_features, video_padding_mask

### text+vedio dataset

In [100]:
class TextVideoPHQ8Dataset(Dataset):
    def __init__(self, metadata_df, split_name):
        super().__init__()
        self.metadata_df = metadata_df.reset_index(drop=True).copy()
        self.participant_ids = self.metadata_df["Participant_ID"].astype(int).tolist()
        self.labels = torch.tensor(self.metadata_df[PHQ8_QUESTION_COLUMNS].to_numpy(), dtype=torch.long)
        text_feature_list = []
        text_mask_list = []
        video_feature_list = []
        video_mask_list = []
        for index, participant_id in enumerate(self.participant_ids):
            text_features, text_mask, video_features, video_mask = load_text_video_cache(participant_id)
            text_feature_list.append(text_features)
            text_mask_list.append(text_mask)
            video_feature_list.append(video_features)
            video_mask_list.append(video_mask)
            if (index + 1) % 50 == 0 or index + 1 == len(self.participant_ids):
                print(f"{split_name} Text+Video加载进度：{index + 1}/{len(self.participant_ids)}")
        self.text_features = torch.stack(text_feature_list, dim=0)
        self.text_masks = torch.stack(text_mask_list, dim=0)
        self.video_features = torch.stack(video_feature_list, dim=0)
        self.video_masks = torch.stack(video_mask_list, dim=0)

    def __len__(self):
        return len(self.participant_ids)

    def __getitem__(self, index):
        return self.text_features[index], self.text_masks[index], self.video_features[index], self.video_masks[index], self.labels[index]

In [101]:
text_video_train_dataset = TextVideoPHQ8Dataset(video_train_metadata_df, split_name="train")
text_video_val_dataset = TextVideoPHQ8Dataset(video_val_metadata_df, split_name="val")

train Text+Video加载进度：50/163
train Text+Video加载进度：100/163
train Text+Video加载进度：150/163
train Text+Video加载进度：163/163
val Text+Video加载进度：50/55
val Text+Video加载进度：55/55

In [102]:
def create_text_video_dataloaders(seed):
    train_generator = torch.Generator()
    train_generator.manual_seed(seed)
    train_loader = DataLoader(text_video_train_dataset, batch_size=BATCH_SIZE, shuffle=True, num_workers=0, drop_last=False, generator=train_generator)
    val_loader = DataLoader(text_video_val_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=0, drop_last=False)
    return train_loader, val_loader

In [103]:
text_video_train_loader, text_video_val_loader = create_text_video_dataloaders(seed=42)
batch_text_features, batch_text_masks, batch_video_features, batch_video_masks, batch_all_labels = next(iter(text_video_train_loader))
print("训练样本数：", len(text_video_train_dataset))
print("验证样本数：", len(text_video_val_dataset))
print("文本特征：", batch_text_features.shape)
print("文本Mask：", batch_text_masks.shape)
print("视频特征：", batch_video_features.shape)
print("视频Mask：", batch_video_masks.shape)
print("全部标签：", batch_all_labels.shape)
print("文本全部有限：", bool(torch.isfinite(batch_text_features).all()))
print("视频全部有限：", bool(torch.isfinite(batch_video_features).all()))

训练样本数： 163
验证样本数： 55
文本特征： torch.Size([10, 120, 768])
文本Mask： torch.Size([10, 120])
视频特征： torch.Size([10, 120, 2048])
视频Mask： torch.Size([10, 120])
全部标签： torch.Size([10, 8])
文本全部有限： True
视频全部有限： True

In [104]:
class PretrainedTextEncoder(nn.Module):
    def __init__(self):
        super().__init__()
        self.lstm = nn.LSTM(input_size=TEXT_FEATURE_DIM, hidden_size=50, batch_first=True, bidirectional=True)
        self.attention = nn.MultiheadAttention(embed_dim=ENCODER_OUTPUT_DIM, num_heads=ATTENTION_HEADS, dropout=0.5, batch_first=True)

    def forward(self, text_features, text_padding_mask):
        lstm_output, _ = self.lstm(text_features)
        text_encoding, _ = self.attention(lstm_output, lstm_output, lstm_output, key_padding_mask=text_padding_mask, need_weights=False)
        text_encoding = text_encoding.masked_fill(text_padding_mask.unsqueeze(-1), 0.0)
        return text_encoding

In [105]:
class PretrainedVideoEncoder(nn.Module):
    def __init__(self):
        super().__init__()
        self.lstm = nn.LSTM(input_size=VIDEO_FEATURE_DIM, hidden_size=50, batch_first=True, bidirectional=True)
        self.attention1 = nn.MultiheadAttention(embed_dim=ENCODER_OUTPUT_DIM, num_heads=ATTENTION_HEADS, dropout=0.2, batch_first=True)
        self.attention2 = nn.MultiheadAttention(embed_dim=ENCODER_OUTPUT_DIM, num_heads=ATTENTION_HEADS, dropout=0.2, batch_first=True)

    def forward(self, video_features, video_padding_mask):
        lstm_output, _ = self.lstm(video_features)
        attention1_output, _ = self.attention1(lstm_output, lstm_output, lstm_output, key_padding_mask=video_padding_mask, need_weights=False)
        attention1_output = attention1_output.masked_fill(video_padding_mask.unsqueeze(-1), 0.0)
        video_encoding, _ = self.attention2(attention1_output, attention1_output, attention1_output, key_padding_mask=video_padding_mask, need_weights=False)
        video_encoding = video_encoding.masked_fill(video_padding_mask.unsqueeze(-1), 0.0)
        return video_encoding

In [106]:
def extract_state_dict_by_prefixes(full_state_dict, prefixes):
    selected_state_dict = {}
    for parameter_name, parameter_value in full_state_dict.items():
        if any(parameter_name.startswith(prefix) for prefix in prefixes):
            selected_state_dict[parameter_name] = parameter_value
    return selected_state_dict

In [107]:
def load_pretrained_text_video_encoders(question_index, seed):
    text_checkpoint_path, video_checkpoint_path = get_text_video_best_loss_paths(question_index, seed)
    text_checkpoint = torch.load(text_checkpoint_path, map_location="cpu", weights_only=False)
    video_checkpoint = torch.load(video_checkpoint_path, map_location="cpu", weights_only=False)
    text_encoder = PretrainedTextEncoder()
    video_encoder = PretrainedVideoEncoder()
    text_encoder_state = extract_state_dict_by_prefixes(text_checkpoint["model_state_dict"], prefixes=("lstm.", "attention."))
    video_encoder_state = extract_state_dict_by_prefixes(video_checkpoint["model_state_dict"], prefixes=("lstm.", "attention1.", "attention2."))
    text_load_result = text_encoder.load_state_dict(text_encoder_state, strict=True)
    video_load_result = video_encoder.load_state_dict(video_encoder_state, strict=True)
    print("文本Best Loss：", text_checkpoint_path)
    print("视频Best Loss：", video_checkpoint_path)
    print("文本保存Epoch：", text_checkpoint["epoch"])
    print("视频保存Epoch：", video_checkpoint["epoch"])
    print("文本缺少参数：", text_load_result.missing_keys)
    print("文本多余参数：", text_load_result.unexpected_keys)
    print("视频缺少参数：", video_load_result.missing_keys)
    print("视频多余参数：", video_load_result.unexpected_keys)
    return text_encoder, video_encoder, text_checkpoint, video_checkpoint, text_checkpoint_path, video_checkpoint_path

In [108]:
class TextVideoQuestMF(nn.Module):
    def __init__(self, text_encoder, video_encoder):
        super().__init__()
        self.text_encoder = text_encoder
        self.video_encoder = video_encoder
        self.video_to_text_cross_attention = nn.MultiheadAttention(embed_dim=ENCODER_OUTPUT_DIM, num_heads=ATTENTION_HEADS, dropout=FUSION_DROPOUT, batch_first=True)
        self.text_to_video_cross_attention = nn.MultiheadAttention(embed_dim=ENCODER_OUTPUT_DIM, num_heads=ATTENTION_HEADS, dropout=FUSION_DROPOUT, batch_first=True)
        self.text_self_attention = nn.MultiheadAttention(embed_dim=ENCODER_OUTPUT_DIM, num_heads=ATTENTION_HEADS, dropout=FUSION_DROPOUT, batch_first=True)
        self.video_self_attention = nn.MultiheadAttention(embed_dim=ENCODER_OUTPUT_DIM, num_heads=ATTENTION_HEADS, dropout=FUSION_DROPOUT, batch_first=True)
        self.mlp = nn.Sequential(nn.Flatten(), nn.Dropout(FUSION_MLP_FIRST_DROPOUT), nn.Linear(MAX_TURNS * ENCODER_OUTPUT_DIM * 2, 256), nn.ReLU(), nn.Dropout(FUSION_MLP_LAST_DROPOUT), nn.Linear(256, NUM_CLASSES))
        for parameter in self.text_encoder.parameters():
            parameter.requires_grad = False
        self.text_encoder.eval()

    def train(self, mode=True):
        super().train(mode)
        self.text_encoder.eval()
        return self

    def forward(self, text_features, text_padding_mask, video_features, video_padding_mask, return_intermediates=False):
        text_encoding = self.text_encoder(text_features, text_padding_mask)
        video_encoding = self.video_encoder(video_features, video_padding_mask)
        video_to_text, _ = self.video_to_text_cross_attention(text_encoding, video_encoding, video_encoding, key_padding_mask=video_padding_mask, need_weights=False)
        video_to_text = video_to_text.masked_fill(text_padding_mask.unsqueeze(-1), 0.0)
        text_to_video, _ = self.text_to_video_cross_attention(video_encoding, text_encoding, text_encoding, key_padding_mask=text_padding_mask, need_weights=False)
        text_to_video = text_to_video.masked_fill(video_padding_mask.unsqueeze(-1), 0.0)
        text_fused_encoding, _ = self.text_self_attention(video_to_text, video_to_text, video_to_text, key_padding_mask=text_padding_mask, need_weights=False)
        text_fused_encoding = text_fused_encoding.masked_fill(text_padding_mask.unsqueeze(-1), 0.0)
        video_fused_encoding, _ = self.video_self_attention(text_to_video, text_to_video, text_to_video, key_padding_mask=video_padding_mask, need_weights=False)
        video_fused_encoding = video_fused_encoding.masked_fill(video_padding_mask.unsqueeze(-1), 0.0)
        fused_encoding = torch.cat((text_fused_encoding, video_fused_encoding), dim=2)
        logits = self.mlp(fused_encoding)
        if return_intermediates:
            return logits, {"text_encoding": text_encoding, "video_encoding": video_encoding, "video_to_text": video_to_text, "text_to_video": text_to_video, "text_fused_encoding": text_fused_encoding, "video_fused_encoding": video_fused_encoding, "fused_encoding": fused_encoding}
        return logits

In [109]:
set_seed(42)
q1_text_encoder, q1_video_encoder, q1_text_checkpoint, q1_video_checkpoint, q1_text_checkpoint_path, q1_video_checkpoint_path = load_pretrained_text_video_encoders(question_index=0, seed=42)
q1_text_video_model = TextVideoQuestMF(q1_text_encoder, q1_video_encoder).to(device)
q1_text_video_model.train()

文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q1_PHQ_8NoInterest/seed_42/best_loss.pt
视频Best Loss： /workspace/E-DAIC/checkpoints/phq8_video_paperlike/seed_42/question_1/best_loss.pt
文本保存Epoch： 13
视频保存Epoch： 2
文本缺少参数： []
文本多余参数： []
视频缺少参数： []
视频多余参数： []

TextVideoQuestMF(
  (text_encoder): PretrainedTextEncoder(
    (lstm): LSTM(768, 50, batch_first=True, bidirectional=True)
    (attention): MultiheadAttention(
      (out_proj): NonDynamicallyQuantizableLinear(in_features=100, out_features=100, bias=True)
    )
  )
  (video_encoder): PretrainedVideoEncoder(
    (lstm): LSTM(2048, 50, batch_first=True, bidirectional=True)
    (attention1): MultiheadAttention(
      (out_proj): NonDynamicallyQuantizableLinear(in_features=100, out_features=100, bias=True)
    )
    (attention2): MultiheadAttention(
      (out_proj): NonDynamicallyQuantizableLinear(in_features=100, out_features=100, bias=True)
    )
  )
  (video_to_text_cross_attention): MultiheadAttention(
    (out_proj): NonDynamicallyQuantizableLinear(in_features=100, out_features=100, bias=True)
  )
  (text_to_video_cross_attention): MultiheadAttention(
    (out_proj): NonDynamicallyQuantizableLinear(in_features=100, out_features=100, bias=True)
  )
  (text_self_attention): MultiheadAttention(
    (out_proj): NonDynamicallyQuantizableLinear(in_features=100, out_features=100, bias=True)
  )
  (video_self_attention): MultiheadAttention(
    (out_proj): NonDynamicallyQuantizableLinear(in_features=100, out_features=100, bias=True)
  )
  (mlp): Sequential(
    (0): Flatten(start_dim=1, end_dim=-1)
    (1): Dropout(p=0.8, inplace=False)
    (2): Linear(in_features=24000, out_features=256, bias=True)
    (3): ReLU()
    (4): Dropout(p=0.5, inplace=False)
    (5): Linear(in_features=256, out_features=4, bias=True)
  )
)

In [110]:
text_total_parameters = sum(parameter.numel() for parameter in q1_text_video_model.text_encoder.parameters())
text_trainable_parameters = sum(parameter.numel() for parameter in q1_text_video_model.text_encoder.parameters() if parameter.requires_grad)
video_trainable_parameters = sum(parameter.numel() for parameter in q1_text_video_model.video_encoder.parameters() if parameter.requires_grad)
fusion_attention_parameters = sum(parameter.numel() for name, parameter in q1_text_video_model.named_parameters() if ("cross_attention" in name or "self_attention" in name) and parameter.requires_grad)
fusion_mlp_parameters = sum(parameter.numel() for parameter in q1_text_video_model.mlp.parameters() if parameter.requires_grad)
total_trainable_parameters = sum(parameter.numel() for parameter in q1_text_video_model.parameters() if parameter.requires_grad)
print("文本编码器总参数：", f"{text_total_parameters:,}")
print("文本可训练参数：", f"{text_trainable_parameters:,}")
print("视频可训练参数：", f"{video_trainable_parameters:,}")
print("融合Attention参数：", f"{fusion_attention_parameters:,}")
print("融合MLP参数：", f"{fusion_mlp_parameters:,}")
print("总可训练参数：", f"{total_trainable_parameters:,}")
print("文本编码器处于训练模式：", q1_text_video_model.text_encoder.training)
print("视频编码器处于训练模式：", q1_text_video_model.video_encoder.training)

文本编码器总参数： 368,400
文本可训练参数： 0
视频可训练参数： 920,800
融合Attention参数： 161,600
融合MLP参数： 6,145,284
总可训练参数： 7,227,684
文本编码器处于训练模式： False
视频编码器处于训练模式： True

In [111]:
q1_text_video_model.eval()
with torch.no_grad():
    q1_text_video_logits, q1_text_video_intermediates = q1_text_video_model(batch_text_features.to(device), batch_text_masks.to(device), batch_video_features.to(device), batch_video_masks.to(device), return_intermediates=True)
print("文本编码：", q1_text_video_intermediates["text_encoding"].shape)
print("视频编码：", q1_text_video_intermediates["video_encoding"].shape)
print("Video→Text：", q1_text_video_intermediates["video_to_text"].shape)
print("Text→Video：", q1_text_video_intermediates["text_to_video"].shape)
print("拼接后：", q1_text_video_intermediates["fused_encoding"].shape)
print("最终Logits：", q1_text_video_logits.shape)
print("Logits全部有限：", bool(torch.isfinite(q1_text_video_logits).all()))

文本编码： torch.Size([10, 120, 100])
视频编码： torch.Size([10, 120, 100])
Video→Text： torch.Size([10, 120, 100])
Text→Video： torch.Size([10, 120, 100])
拼接后： torch.Size([10, 120, 200])
最终Logits： torch.Size([10, 4])
Logits全部有限： True

In [112]:
def calculate_gradient_statistics(parameters):
    squared_gradient_sum = 0.0
    gradient_tensor_count = 0
    for parameter in parameters:
        if parameter.grad is not None:
            squared_gradient_sum += parameter.grad.detach().pow(2).sum().item()
            gradient_tensor_count += 1
    return squared_gradient_sum ** 0.5, gradient_tensor_count

In [113]:
q1_train_labels = text_video_train_dataset.labels[:, 0]
q1_class_counts = torch.bincount(q1_train_labels, minlength=NUM_CLASSES)
q1_class_weights = torch.pow(len(q1_train_labels) / q1_class_counts.float(), BETA)
q1_text_video_criterion = ImbOLLLoss(q1_class_weights, alpha=ALPHA).to(device)
print("Q1类别数量：", q1_class_counts.tolist())
print("Q1 ImbOLL权重：", q1_class_weights.tolist())

Q1类别数量： [81, 57, 20, 5]
Q1 ImbOLL权重： [1.4185717105865479, 1.6910496950149536, 2.854820728302002, 5.709641456604004]

In [114]:
q1_text_video_optimizer = torch.optim.AdamW((parameter for parameter in q1_text_video_model.parameters() if parameter.requires_grad), lr=FUSION_LEARNING_RATE, eps=FUSION_ADAM_EPSILON, weight_decay=FUSION_WEIGHT_DECAY)
q1_text_video_model.train()
diagnostic_text_features = batch_text_features.to(device)
diagnostic_text_masks = batch_text_masks.to(device)
diagnostic_video_features = batch_video_features.to(device)
diagnostic_video_masks = batch_video_masks.to(device)
diagnostic_targets = batch_all_labels[:, 0].to(device)
q1_text_video_optimizer.zero_grad(set_to_none=True)
diagnostic_logits = q1_text_video_model(diagnostic_text_features, diagnostic_text_masks, diagnostic_video_features, diagnostic_video_masks)
diagnostic_loss = q1_text_video_criterion(diagnostic_logits, diagnostic_targets)
diagnostic_loss.backward()
text_gradient_norm, text_gradient_tensor_count = calculate_gradient_statistics(q1_text_video_model.text_encoder.parameters())
video_gradient_norm, video_gradient_tensor_count = calculate_gradient_statistics(q1_text_video_model.video_encoder.parameters())
fusion_parameters = list(q1_text_video_model.video_to_text_cross_attention.parameters()) + list(q1_text_video_model.text_to_video_cross_attention.parameters()) + list(q1_text_video_model.text_self_attention.parameters()) + list(q1_text_video_model.video_self_attention.parameters()) + list(q1_text_video_model.mlp.parameters())
fusion_gradient_norm, fusion_gradient_tensor_count = calculate_gradient_statistics(fusion_parameters)
print("Logits形状：", diagnostic_logits.shape)
print("ImbOLL：", diagnostic_loss.item())
print("预测概率全部有限：", bool(torch.isfinite(torch.softmax(diagnostic_logits, dim=1)).all()))
print("预测类别：", diagnostic_logits.argmax(dim=1))
print("真实类别：", diagnostic_targets)
print("文本梯度范数：", text_gradient_norm)
print("文本梯度张量数：", text_gradient_tensor_count)
print("视频梯度范数：", video_gradient_norm)
print("视频梯度张量数：", video_gradient_tensor_count)
print("融合层梯度范数：", fusion_gradient_norm)
print("融合层梯度张量数：", fusion_gradient_tensor_count)

Logits形状： torch.Size([10, 4])
ImbOLL： 2.2568275928497314
预测概率全部有限： True
预测类别： tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
真实类别： tensor([1, 0, 1, 0, 0, 0, 0, 0, 0, 1], device='cuda:0')
文本梯度范数： 0.0
文本梯度张量数： 0
视频梯度范数： 0.033716787751368535
视频梯度张量数： 16
融合层梯度范数： 1.093400904704733
融合层梯度张量数： 20

In [115]:
def run_text_video_epoch(model, data_loader, question_index, criterion, optimizer=None):
    is_training = optimizer is not None
    if is_training:
        model.train()
    else:
        model.eval()
    total_loss = 0.0
    total_samples = 0
    prediction_list = []
    target_list = []
    for text_features, text_masks, video_features, video_masks, all_labels in data_loader:
        text_features = text_features.to(device)
        text_masks = text_masks.to(device)
        video_features = video_features.to(device)
        video_masks = video_masks.to(device)
        targets = all_labels[:, question_index].to(device)
        if is_training:
            optimizer.zero_grad(set_to_none=True)
        with torch.set_grad_enabled(is_training):
            logits = model(text_features, text_masks, video_features, video_masks)
            loss = criterion(logits, targets)
            if is_training:
                loss.backward()
                torch.nn.utils.clip_grad_norm_(model.parameters(), MAX_GRAD_NORM)
                optimizer.step()
        batch_size = targets.shape[0]
        total_loss += loss.item() * batch_size
        total_samples += batch_size
        prediction_list.append(logits.argmax(dim=1).detach().cpu())
        target_list.append(targets.detach().cpu())
    predictions = torch.cat(prediction_list)
    targets = torch.cat(target_list)
    metrics = calculate_video_metrics(predictions, targets)
    metrics["loss"] = total_loss / total_samples
    metrics["predictions"] = predictions
    metrics["targets"] = targets
    return metrics

In [116]:
set_seed(42)
text_video_train_loader, text_video_val_loader = create_text_video_dataloaders(seed=42)
q1_text_encoder, q1_video_encoder, q1_text_checkpoint, q1_video_checkpoint, q1_text_checkpoint_path, q1_video_checkpoint_path = load_pretrained_text_video_encoders(question_index=0, seed=42)
q1_text_video_model = TextVideoQuestMF(q1_text_encoder, q1_video_encoder).to(device)
q1_train_labels = text_video_train_dataset.labels[:, 0]
q1_class_counts = torch.bincount(q1_train_labels, minlength=NUM_CLASSES)
q1_class_weights = torch.pow(len(q1_train_labels) / q1_class_counts.float(), BETA)
q1_text_video_criterion = ImbOLLLoss(q1_class_weights, alpha=ALPHA).to(device)
q1_text_video_optimizer = torch.optim.AdamW((parameter for parameter in q1_text_video_model.parameters() if parameter.requires_grad), lr=FUSION_LEARNING_RATE, eps=FUSION_ADAM_EPSILON, weight_decay=FUSION_WEIGHT_DECAY)

文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q1_PHQ_8NoInterest/seed_42/best_loss.pt
视频Best Loss： /workspace/E-DAIC/checkpoints/phq8_video_paperlike/seed_42/question_1/best_loss.pt
文本保存Epoch： 13
视频保存Epoch： 2
文本缺少参数： []
文本多余参数： []
视频缺少参数： []
视频多余参数： []

In [117]:
q1_text_video_train_metrics = run_text_video_epoch(q1_text_video_model, text_video_train_loader, question_index=0, criterion=q1_text_video_criterion, optimizer=q1_text_video_optimizer)
q1_text_video_val_metrics = run_text_video_epoch(q1_text_video_model, text_video_val_loader, question_index=0, criterion=q1_text_video_criterion)

In [118]:
print(f"一轮训练 Loss：{q1_text_video_train_metrics['loss']:.6f}")
print(f"一轮训练 Accuracy：{q1_text_video_train_metrics['accuracy']:.6f}")
print(f"一轮训练 Micro F1：{q1_text_video_train_metrics['micro_f1']:.6f}")
print(f"一轮训练 Macro F1：{q1_text_video_train_metrics['macro_f1']:.6f}")
print(f"一轮训练 Weighted F1：{q1_text_video_train_metrics['weighted_f1']:.6f}")
print(f"一轮训练 CCC：{q1_text_video_train_metrics['ccc']:.6f}")
print(f"一轮训练 RMSE：{q1_text_video_train_metrics['rmse']:.6f}")
print(f"一轮训练 MAE：{q1_text_video_train_metrics['mae']:.6f}")
print("一轮训练混淆矩阵：")
print(q1_text_video_train_metrics["confusion_matrix"])
print(f"一轮验证 Loss：{q1_text_video_val_metrics['loss']:.6f}")
print(f"一轮验证 Accuracy：{q1_text_video_val_metrics['accuracy']:.6f}")
print(f"一轮验证 Micro F1：{q1_text_video_val_metrics['micro_f1']:.6f}")
print(f"一轮验证 Macro F1：{q1_text_video_val_metrics['macro_f1']:.6f}")
print(f"一轮验证 Weighted F1：{q1_text_video_val_metrics['weighted_f1']:.6f}")
print(f"一轮验证 CCC：{q1_text_video_val_metrics['ccc']:.6f}")
print(f"一轮验证 RMSE：{q1_text_video_val_metrics['rmse']:.6f}")
print(f"一轮验证 MAE：{q1_text_video_val_metrics['mae']:.6f}")
print("一轮验证混淆矩阵：")
print(q1_text_video_val_metrics["confusion_matrix"])

一轮训练 Loss：2.150871
一轮训练 Accuracy：0.429448
一轮训练 Micro F1：0.429448
一轮训练 Macro F1：0.271970
一轮训练 Weighted F1：0.404077
一轮训练 CCC：0.215361
一轮训练 RMSE：0.825216
一轮训练 MAE：0.607362
一轮训练混淆矩阵：
tensor([[28, 53,  0,  0],
        [17, 40,  0,  0],
        [ 1, 17,  2,  0],
        [ 0,  5,  0,  0]])
一轮验证 Loss：2.717357
一轮验证 Accuracy：0.527273
一轮验证 Micro F1：0.527273
一轮验证 Macro F1：0.300992
一轮验证 Weighted F1：0.447362
一轮验证 CCC：0.320330
一轮验证 RMSE：0.962950
一轮验证 MAE：0.600000
一轮验证混淆矩阵：
tensor([[24,  1,  0,  0],
        [15,  4,  3,  0],
        [ 2,  1,  1,  0],
        [ 2,  1,  1,  0]])

In [119]:
def save_text_video_checkpoint(path, checkpoint_type, epoch, question_index, seed, model, optimizer, train_metrics, val_metrics, class_counts, class_weights, best_val_loss, best_val_ccc, best_loss_epoch, best_ccc_epoch, text_checkpoint_path, video_checkpoint_path):
    checkpoint = {}
    checkpoint["checkpoint_type"] = checkpoint_type
    checkpoint["epoch"] = epoch
    checkpoint["question_index"] = question_index
    checkpoint["question_number"] = question_index + 1
    checkpoint["question"] = PHQ8_QUESTION_COLUMNS[question_index]
    checkpoint["seed"] = seed
    checkpoint["model_state_dict"] = model.state_dict()
    checkpoint["optimizer_state_dict"] = optimizer.state_dict()
    checkpoint["train_metrics"] = compact_video_metrics(train_metrics)
    checkpoint["val_metrics"] = compact_video_metrics(val_metrics)
    checkpoint["class_counts"] = class_counts.tolist()
    checkpoint["class_weights"] = class_weights.tolist()
    checkpoint["best_val_loss"] = float(best_val_loss)
    checkpoint["best_val_ccc"] = float(best_val_ccc)
    checkpoint["best_loss_epoch"] = int(best_loss_epoch)
    checkpoint["best_ccc_epoch"] = int(best_ccc_epoch)
    checkpoint["text_pretrained_checkpoint"] = str(text_checkpoint_path)
    checkpoint["video_pretrained_checkpoint"] = str(video_checkpoint_path)
    checkpoint["video_variant"] = "masked_padding_current_video"
    checkpoint["config"] = {"max_turns": MAX_TURNS, "text_feature_dim": TEXT_FEATURE_DIM, "video_feature_dim": VIDEO_FEATURE_DIM, "encoder_output_dim": ENCODER_OUTPUT_DIM, "attention_heads": ATTENTION_HEADS, "fusion_dropout": FUSION_DROPOUT, "mlp_first_dropout": FUSION_MLP_FIRST_DROPOUT, "mlp_last_dropout": FUSION_MLP_LAST_DROPOUT, "num_classes": NUM_CLASSES, "batch_size": BATCH_SIZE, "num_epochs": FUSION_NUM_EPOCHS, "learning_rate": FUSION_LEARNING_RATE, "adam_epsilon": FUSION_ADAM_EPSILON, "weight_decay": FUSION_WEIGHT_DECAY, "max_grad_norm": MAX_GRAD_NORM, "alpha": ALPHA, "beta": BETA, "text_frozen": True}
    torch.save(checkpoint, path)

In [120]:
def train_text_video_question(seed, question_index):
    set_seed(seed)
    train_loader, val_loader = create_text_video_dataloaders(seed)
    text_encoder, video_encoder, text_checkpoint, video_checkpoint, text_checkpoint_path, video_checkpoint_path = load_pretrained_text_video_encoders(question_index, seed)
    model = TextVideoQuestMF(text_encoder, video_encoder).to(device)
    train_labels = text_video_train_dataset.labels[:, question_index]
    class_counts = torch.bincount(train_labels, minlength=NUM_CLASSES)
    class_weights = torch.pow(len(train_labels) / class_counts.float(), BETA)
    criterion = ImbOLLLoss(class_weights, alpha=ALPHA).to(device)
    optimizer = torch.optim.AdamW((parameter for parameter in model.parameters() if parameter.requires_grad), lr=FUSION_LEARNING_RATE, eps=FUSION_ADAM_EPSILON, weight_decay=FUSION_WEIGHT_DECAY)
    checkpoint_dir = TEXT_VIDEO_CHECKPOINT_ROOT / f"seed_{seed}" / f"question_{question_index + 1}"
    checkpoint_dir.mkdir(parents=True, exist_ok=True)
    best_loss_path = checkpoint_dir / "best_loss.pt"
    best_ccc_path = checkpoint_dir / "best_ccc.pt"
    last_path = checkpoint_dir / "last.pt"
    history_path = checkpoint_dir / "history.csv"
    best_val_loss = float("inf")
    best_val_ccc = float("-inf")
    best_loss_epoch = -1
    best_ccc_epoch = -1
    history_rows = []
    print("=" * 100)
    print(f"开始训练Text+Video：Seed={seed}，Q{question_index + 1}，{PHQ8_QUESTION_COLUMNS[question_index]}")
    print("类别数量：", class_counts.tolist())
    print("ImbOLL权重：", class_weights.tolist())
    print("文本预训练模型：", text_checkpoint_path)
    print("视频预训练模型：", video_checkpoint_path)
    print("=" * 100)
    for epoch in range(1, FUSION_NUM_EPOCHS + 1):
        epoch_start_time = time.perf_counter()
        train_metrics = run_text_video_epoch(model, train_loader, question_index, criterion, optimizer)
        val_metrics = run_text_video_epoch(model, val_loader, question_index, criterion)
        elapsed_seconds = time.perf_counter() - epoch_start_time
        improved_loss = val_metrics["loss"] < best_val_loss
        improved_ccc = val_metrics["ccc"] > best_val_ccc
        if improved_loss:
            best_val_loss = val_metrics["loss"]
            best_loss_epoch = epoch
        if improved_ccc:
            best_val_ccc = val_metrics["ccc"]
            best_ccc_epoch = epoch
        if improved_loss:
            save_text_video_checkpoint(best_loss_path, "best_loss", epoch, question_index, seed, model, optimizer, train_metrics, val_metrics, class_counts, class_weights, best_val_loss, best_val_ccc, best_loss_epoch, best_ccc_epoch, text_checkpoint_path, video_checkpoint_path)
        if improved_ccc:
            save_text_video_checkpoint(best_ccc_path, "best_ccc", epoch, question_index, seed, model, optimizer, train_metrics, val_metrics, class_counts, class_weights, best_val_loss, best_val_ccc, best_loss_epoch, best_ccc_epoch, text_checkpoint_path, video_checkpoint_path)
        history_rows.append({"Epoch": epoch, "Train_Loss": train_metrics["loss"], "Train_Accuracy": train_metrics["accuracy"], "Train_CCC": train_metrics["ccc"], "Train_RMSE": train_metrics["rmse"], "Train_MAE": train_metrics["mae"], "Val_Loss": val_metrics["loss"], "Val_Accuracy": val_metrics["accuracy"], "Val_CCC": val_metrics["ccc"], "Val_RMSE": val_metrics["rmse"], "Val_MAE": val_metrics["mae"], "Elapsed_Seconds": elapsed_seconds})
        print(f"Epoch {epoch:02d}/{FUSION_NUM_EPOCHS} | Train Loss {train_metrics['loss']:.6f} | Val Loss {val_metrics['loss']:.6f} | Val CCC {val_metrics['ccc']:.6f} | Val Acc {val_metrics['accuracy']:.6f} | Val RMSE {val_metrics['rmse']:.6f} | {elapsed_seconds:.2f}s")
    save_text_video_checkpoint(last_path, "last", FUSION_NUM_EPOCHS, question_index, seed, model, optimizer, train_metrics, val_metrics, class_counts, class_weights, best_val_loss, best_val_ccc, best_loss_epoch, best_ccc_epoch, text_checkpoint_path, video_checkpoint_path)
    history_df = pd.DataFrame(history_rows)
    history_df.to_csv(history_path, index=False)
    print("=" * 100)
    print(f"训练完成：Seed={seed}，Q{question_index + 1}")
    print(f"最佳Val Loss：{best_val_loss:.6f}，Epoch={best_loss_epoch}")
    print(f"最佳Val CCC：{best_val_ccc:.6f}，Epoch={best_ccc_epoch}")
    print("=" * 100)
    return {"seed": seed, "question_index": question_index, "question_number": question_index + 1, "question": PHQ8_QUESTION_COLUMNS[question_index], "best_val_loss": best_val_loss, "best_val_ccc": best_val_ccc, "best_loss_epoch": best_loss_epoch, "best_ccc_epoch": best_ccc_epoch, "best_loss_path": best_loss_path, "best_ccc_path": best_ccc_path, "last_path": last_path, "history_path": history_path}

In [121]:
text_video_q1_seed42_result = train_text_video_question(seed=42, question_index=0)

文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q1_PHQ_8NoInterest/seed_42/best_loss.pt
视频Best Loss： /workspace/E-DAIC/checkpoints/phq8_video_paperlike/seed_42/question_1/best_loss.pt
文本保存Epoch： 13
视频保存Epoch： 2
文本缺少参数： []
文本多余参数： []
视频缺少参数： []
视频多余参数： []
====================================================================================================
开始训练Text+Video：Seed=42，Q1，PHQ_8NoInterest
类别数量： [81, 57, 20, 5]
ImbOLL权重： [1.4185717105865479, 1.6910496950149536, 2.854820728302002, 5.709641456604004]
文本预训练模型： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q1_PHQ_8NoInterest/seed_42/best_loss.pt
视频预训练模型： /workspace/E-DAIC/checkpoints/phq8_video_paperlike/seed_42/question_1/best_loss.pt
====================================================================================================
Epoch 01/20 | Train Loss 2.150871 | Val Loss 2.717357 | Val CCC 0.320330 | Val Acc 0.527273 | Val RMSE 0.962950 | 1.37s
Epoch 02/20 | Train Loss 1.317898 | Val Loss 3.563488 | Val CCC 0.374030 | Val Acc 0.600000 | Val RMSE 0.894427 | 1.21s
Epoch 03/20 | Train Loss 1.384124 | Val Loss 2.487444 | Val CCC 0.312109 | Val Acc 0.545455 | Val RMSE 0.894427 | 1.27s
Epoch 04/20 | Train Loss 1.250219 | Val Loss 2.657074 | Val CCC 0.296599 | Val Acc 0.600000 | Val RMSE 0.924416 | 0.96s
Epoch 05/20 | Train Loss 1.127223 | Val Loss 3.500033 | Val CCC 0.300673 | Val Acc 0.527273 | Val RMSE 0.962950 | 1.25s
Epoch 06/20 | Train Loss 1.164287 | Val Loss 2.729872 | Val CCC 0.430305 | Val Acc 0.618182 | Val RMSE 0.797724 | 1.08s
Epoch 07/20 | Train Loss 1.116103 | Val Loss 2.826319 | Val CCC 0.430305 | Val Acc 0.618182 | Val RMSE 0.797724 | 0.95s
Epoch 08/20 | Train Loss 1.117621 | Val Loss 2.748970 | Val CCC 0.326297 | Val Acc 0.545455 | Val RMSE 0.924416 | 1.23s
Epoch 09/20 | Train Loss 1.069562 | Val Loss 2.704762 | Val CCC 0.374480 | Val Acc 0.563636 | Val RMSE 0.863397 | 0.87s
Epoch 10/20 | Train Loss 1.039208 | Val Loss 3.443138 | Val CCC 0.290909 | Val Acc 0.454545 | Val RMSE 0.842075 | 0.99s
Epoch 11/20 | Train Loss 1.104439 | Val Loss 3.461669 | Val CCC 0.327348 | Val Acc 0.545455 | Val RMSE 0.924416 | 1.10s
Epoch 12/20 | Train Loss 0.861958 | Val Loss 2.977373 | Val CCC 0.396999 | Val Acc 0.618182 | Val RMSE 0.831209 | 0.85s
Epoch 13/20 | Train Loss 1.055153 | Val Loss 2.996811 | Val CCC 0.386266 | Val Acc 0.600000 | Val RMSE 0.842075 | 1.06s
Epoch 14/20 | Train Loss 0.930053 | Val Loss 3.002597 | Val CCC 0.374480 | Val Acc 0.563636 | Val RMSE 0.863397 | 1.03s
Epoch 15/20 | Train Loss 1.030233 | Val Loss 3.255114 | Val CCC 0.354460 | Val Acc 0.581818 | Val RMSE 0.852803 | 0.85s
Epoch 16/20 | Train Loss 0.851395 | Val Loss 3.464463 | Val CCC 0.325429 | Val Acc 0.581818 | Val RMSE 0.904534 | 1.03s
Epoch 17/20 | Train Loss 0.969348 | Val Loss 3.629579 | Val CCC 0.375909 | Val Acc 0.600000 | Val RMSE 0.842075 | 1.01s
Epoch 18/20 | Train Loss 0.884715 | Val Loss 3.380734 | Val CCC 0.416194 | Val Acc 0.527273 | Val RMSE 0.884205 | 0.91s
Epoch 19/20 | Train Loss 0.997455 | Val Loss 3.160344 | Val CCC 0.409509 | Val Acc 0.545455 | Val RMSE 0.873863 | 0.97s
Epoch 20/20 | Train Loss 0.916714 | Val Loss 3.300179 | Val CCC 0.320988 | Val Acc 0.527273 | Val RMSE 0.884205 | 0.89s
====================================================================================================
训练完成：Seed=42，Q1
最佳Val Loss：2.487444，Epoch=3
最佳Val CCC：0.430305，Epoch=6
====================================================================================================

In [122]:
print("Best Loss存在：", text_video_q1_seed42_result["best_loss_path"].exists())
print("Best CCC存在：", text_video_q1_seed42_result["best_ccc_path"].exists())
print("Last存在：", text_video_q1_seed42_result["last_path"].exists())
print("History存在：", text_video_q1_seed42_result["history_path"].exists())
print("Best Loss路径：", text_video_q1_seed42_result["best_loss_path"])
print("Best CCC路径：", text_video_q1_seed42_result["best_ccc_path"])

Best Loss存在： True
Best CCC存在： True
Last存在： True
History存在： True
Best Loss路径： /workspace/E-DAIC/checkpoints/phq8_text_video_paperlike/seed_42/question_1/best_loss.pt
Best CCC路径： /workspace/E-DAIC/checkpoints/phq8_text_video_paperlike/seed_42/question_1/best_ccc.pt

In [123]:
text_video_q1_best_ccc_path = text_video_q1_seed42_result["best_ccc_path"]
text_video_q1_checkpoint = torch.load(text_video_q1_best_ccc_path, map_location="cpu", weights_only=False)
restored_text_video_q1_model = TextVideoQuestMF(PretrainedTextEncoder(), PretrainedVideoEncoder()).to(device)
text_video_load_result = restored_text_video_q1_model.load_state_dict(text_video_q1_checkpoint["model_state_dict"], strict=True)
restored_q1_class_weights = torch.tensor(text_video_q1_checkpoint["class_weights"], dtype=torch.float32)
restored_q1_criterion = ImbOLLLoss(restored_q1_class_weights, alpha=ALPHA).to(device)
_, restored_text_video_val_loader = create_text_video_dataloaders(seed=42)
restored_q1_val_metrics = run_text_video_epoch(restored_text_video_q1_model, restored_text_video_val_loader, question_index=0, criterion=restored_q1_criterion)

In [124]:
print("Checkpoint：", text_video_q1_best_ccc_path)
print("类型：", text_video_q1_checkpoint["checkpoint_type"])
print("Epoch：", text_video_q1_checkpoint["epoch"])
print("Video变体：", text_video_q1_checkpoint["video_variant"])
print("文本预训练Checkpoint：", text_video_q1_checkpoint["text_pretrained_checkpoint"])
print("视频预训练Checkpoint：", text_video_q1_checkpoint["video_pretrained_checkpoint"])
print("缺少参数：", text_video_load_result.missing_keys)
print("多余参数：", text_video_load_result.unexpected_keys)
print("文本处于训练模式：", restored_text_video_q1_model.text_encoder.training)
print("文本可训练参数：", sum(parameter.numel() for parameter in restored_text_video_q1_model.text_encoder.parameters() if parameter.requires_grad))

Checkpoint： /workspace/E-DAIC/checkpoints/phq8_text_video_paperlike/seed_42/question_1/best_ccc.pt
类型： best_ccc
Epoch： 6
Video变体： masked_padding_current_video
文本预训练Checkpoint： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q1_PHQ_8NoInterest/seed_42/best_loss.pt
视频预训练Checkpoint： /workspace/E-DAIC/checkpoints/phq8_video_paperlike/seed_42/question_1/best_loss.pt
缺少参数： []
多余参数： []
文本处于训练模式： False
文本可训练参数： 0

In [125]:
text_video_checkpoint_metric_names = ["loss", "accuracy", "micro_f1", "macro_f1", "weighted_f1", "ccc", "rmse", "mae"]
print("保存指标与恢复指标对比：")
for metric_name in text_video_checkpoint_metric_names:
    saved_value = float(text_video_q1_checkpoint["val_metrics"][metric_name])
    restored_value = float(restored_q1_val_metrics[metric_name])
    difference = abs(saved_value - restored_value)
    print(f"{metric_name:>12} | 保存 {saved_value:.9f} | 恢复 {restored_value:.9f} | 差值 {difference:.3e}")

保存指标与恢复指标对比：
        loss | 保存 2.729871696 | 恢复 2.729871696 | 差值 0.000e+00
    accuracy | 保存 0.618181825 | 恢复 0.618181825 | 差值 0.000e+00
    micro_f1 | 保存 0.618181825 | 恢复 0.618181825 | 差值 0.000e+00
    macro_f1 | 保存 0.400655136 | 恢复 0.400655136 | 差值 0.000e+00
 weighted_f1 | 保存 0.598017915 | 恢复 0.598017915 | 差值 0.000e+00
         ccc | 保存 0.430304824 | 恢复 0.430304824 | 差值 0.000e+00
        rmse | 保存 0.797724068 | 恢复 0.797724068 | 差值 0.000e+00
         mae | 保存 0.454545468 | 恢复 0.454545468 | 差值 0.000e+00

In [126]:
maximum_metric_difference = max(abs(float(text_video_q1_checkpoint["val_metrics"][metric_name]) - float(restored_q1_val_metrics[metric_name])) for metric_name in text_video_checkpoint_metric_names)
saved_confusion_matrix = torch.tensor(text_video_q1_checkpoint["val_metrics"]["confusion_matrix"])
restored_confusion_matrix = restored_q1_val_metrics["confusion_matrix"]
assert text_video_load_result.missing_keys == []
assert text_video_load_result.unexpected_keys == []
assert maximum_metric_difference < 1e-6
assert torch.equal(saved_confusion_matrix, restored_confusion_matrix)
assert sum(parameter.numel() for parameter in restored_text_video_q1_model.text_encoder.parameters() if parameter.requires_grad) == 0
print("最大指标差值：", maximum_metric_difference)
print("Checkpoint恢复验证通过")

最大指标差值： 0.0
Checkpoint恢复验证通过

In [128]:
del restored_text_video_q1_model
gc.collect()
if torch.cuda.is_available():
    torch.cuda.empty_cache()

In [129]:
text_video_seed42_results = [text_video_q1_seed42_result]
for question_index in range(1, len(PHQ8_QUESTION_COLUMNS)):
    question_result = train_text_video_question(seed=42, question_index=question_index)
    text_video_seed42_results.append(question_result)
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q2_PHQ_8Depressed/seed_42/best_loss.pt
视频Best Loss： /workspace/E-DAIC/checkpoints/phq8_video_paperlike/seed_42/question_2/best_loss.pt
文本保存Epoch： 9
视频保存Epoch： 8
文本缺少参数： []
文本多余参数： []
视频缺少参数： []
视频多余参数： []
====================================================================================================
开始训练Text+Video：Seed=42，Q2，PHQ_8Depressed
类别数量： [68, 63, 18, 14]
ImbOLL权重： [1.548243761062622, 1.6085091829299927, 3.009244918823242, 3.412163257598877]
文本预训练模型： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q2_PHQ_8Depressed/seed_42/best_loss.pt
视频预训练模型： /workspace/E-DAIC/checkpoints/phq8_video_paperlike/seed_42/question_2/best_loss.pt
====================================================================================================
Epoch 01/20 | Train Loss 2.314834 | Val Loss 2.288081 | Val CCC 0.375887 | Val Acc 0.545455 | Val RMSE 0.934199 | 1.21s
Epoch 02/20 | Train Loss 1.596882 | Val Loss 2.111849 | Val CCC 0.471816 | Val Acc 0.472727 | Val RMSE 0.914529 | 1.41s
Epoch 03/20 | Train Loss 1.601615 | Val Loss 2.061613 | Val CCC 0.531440 | Val Acc 0.545455 | Val RMSE 0.873863 | 0.89s
Epoch 04/20 | Train Loss 1.712974 | Val Loss 2.133559 | Val CCC 0.430052 | Val Acc 0.527273 | Val RMSE 0.852803 | 1.29s
Epoch 05/20 | Train Loss 1.615389 | Val Loss 1.972233 | Val CCC 0.466019 | Val Acc 0.527273 | Val RMSE 0.852803 | 0.97s
Epoch 06/20 | Train Loss 1.566675 | Val Loss 2.012073 | Val CCC 0.493827 | Val Acc 0.563636 | Val RMSE 0.863397 | 1.07s
Epoch 07/20 | Train Loss 1.484085 | Val Loss 2.215081 | Val CCC 0.474940 | Val Acc 0.527273 | Val RMSE 0.852803 | 1.06s
Epoch 08/20 | Train Loss 1.432037 | Val Loss 2.192965 | Val CCC 0.474940 | Val Acc 0.527273 | Val RMSE 0.852803 | 0.98s
Epoch 09/20 | Train Loss 1.490066 | Val Loss 1.996232 | Val CCC 0.560924 | Val Acc 0.581818 | Val RMSE 0.831209 | 1.05s
Epoch 10/20 | Train Loss 1.582123 | Val Loss 2.057467 | Val CCC 0.363636 | Val Acc 0.400000 | Val RMSE 0.873863 | 0.99s
Epoch 11/20 | Train Loss 1.494172 | Val Loss 2.360923 | Val CCC 0.481132 | Val Acc 0.509091 | Val RMSE 0.953463 | 1.04s
Epoch 12/20 | Train Loss 1.356230 | Val Loss 2.078970 | Val CCC 0.507075 | Val Acc 0.527273 | Val RMSE 0.831209 | 0.85s
Epoch 13/20 | Train Loss 1.364679 | Val Loss 2.100789 | Val CCC 0.480100 | Val Acc 0.527273 | Val RMSE 0.831209 | 0.98s
Epoch 14/20 | Train Loss 1.418397 | Val Loss 2.222770 | Val CCC 0.362720 | Val Acc 0.381818 | Val RMSE 0.914529 | 1.03s
Epoch 15/20 | Train Loss 1.630939 | Val Loss 2.484607 | Val CCC 0.484188 | Val Acc 0.527273 | Val RMSE 0.884205 | 0.82s
Epoch 16/20 | Train Loss 1.622104 | Val Loss 2.108082 | Val CCC 0.477348 | Val Acc 0.527273 | Val RMSE 0.884205 | 0.93s
Epoch 17/20 | Train Loss 1.468704 | Val Loss 2.046956 | Val CCC 0.484157 | Val Acc 0.490909 | Val RMSE 0.820200 | 0.95s
Epoch 18/20 | Train Loss 1.295937 | Val Loss 2.213914 | Val CCC 0.466019 | Val Acc 0.527273 | Val RMSE 0.852803 | 1.02s
Epoch 19/20 | Train Loss 1.402285 | Val Loss 2.355741 | Val CCC 0.352941 | Val Acc 0.418182 | Val RMSE 0.894427 | 1.08s
Epoch 20/20 | Train Loss 1.425235 | Val Loss 2.109487 | Val CCC 0.460784 | Val Acc 0.527273 | Val RMSE 0.852803 | 0.81s
====================================================================================================
训练完成：Seed=42，Q2
最佳Val Loss：1.972233，Epoch=5
最佳Val CCC：0.560924，Epoch=9
====================================================================================================
文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q3_PHQ_8Sleep/seed_42/best_loss.pt
视频Best Loss： /workspace/E-DAIC/checkpoints/phq8_video_paperlike/seed_42/question_3/best_loss.pt
文本保存Epoch： 9
视频保存Epoch： 14
文本缺少参数： []
文本多余参数： []
视频缺少参数： []
视频多余参数： []
====================================================================================================
开始训练Text+Video：Seed=42，Q3，PHQ_8Sleep
类别数量： [69, 40, 27, 27]
ImbOLL权重： [1.5369837284088135, 2.018662929534912, 2.457038164138794, 2.457038164138794]
文本预训练模型： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q3_PHQ_8Sleep/seed_42/best_loss.pt
视频预训练模型： /workspace/E-DAIC/checkpoints/phq8_video_paperlike/seed_42/question_3/best_loss.pt
====================================================================================================
Epoch 01/20 | Train Loss 2.473498 | Val Loss 2.568857 | Val CCC 0.414987 | Val Acc 0.454545 | Val RMSE 1.103713 | 0.97s
Epoch 02/20 | Train Loss 1.896361 | Val Loss 2.407684 | Val CCC 0.449004 | Val Acc 0.400000 | Val RMSE 1.228451 | 0.84s
Epoch 03/20 | Train Loss 1.750214 | Val Loss 3.004952 | Val CCC 0.391447 | Val Acc 0.418182 | Val RMSE 1.159937 | 0.92s
Epoch 04/20 | Train Loss 1.750622 | Val Loss 2.582468 | Val CCC 0.458880 | Val Acc 0.436364 | Val RMSE 1.190874 | 0.78s
Epoch 05/20 | Train Loss 1.685998 | Val Loss 2.784379 | Val CCC 0.398027 | Val Acc 0.436364 | Val RMSE 1.136182 | 0.78s
Epoch 06/20 | Train Loss 1.715944 | Val Loss 2.361256 | Val CCC 0.354435 | Val Acc 0.418182 | Val RMSE 1.053134 | 0.77s
Epoch 07/20 | Train Loss 1.656166 | Val Loss 2.296455 | Val CCC 0.484153 | Val Acc 0.472727 | Val RMSE 1.026911 | 0.80s
Epoch 08/20 | Train Loss 1.655409 | Val Loss 2.978342 | Val CCC 0.415617 | Val Acc 0.436364 | Val RMSE 1.250454 | 0.79s
Epoch 09/20 | Train Loss 1.733271 | Val Loss 2.324919 | Val CCC 0.469453 | Val Acc 0.490909 | Val RMSE 1.144155 | 0.84s
Epoch 10/20 | Train Loss 1.646803 | Val Loss 2.297367 | Val CCC 0.444444 | Val Acc 0.436364 | Val RMSE 1.044466 | 0.78s
Epoch 11/20 | Train Loss 1.670251 | Val Loss 2.526260 | Val CCC 0.471444 | Val Acc 0.436364 | Val RMSE 1.128152 | 0.79s
Epoch 12/20 | Train Loss 1.524317 | Val Loss 2.350013 | Val CCC 0.456701 | Val Acc 0.490909 | Val RMSE 1.044466 | 0.84s
Epoch 13/20 | Train Loss 1.493417 | Val Loss 3.050083 | Val CCC 0.495027 | Val Acc 0.454545 | Val RMSE 1.144155 | 0.79s
Epoch 14/20 | Train Loss 1.536870 | Val Loss 2.361083 | Val CCC 0.425969 | Val Acc 0.454545 | Val RMSE 1.035725 | 0.81s
Epoch 15/20 | Train Loss 1.504389 | Val Loss 2.507366 | Val CCC 0.440055 | Val Acc 0.454545 | Val RMSE 1.103713 | 0.83s
Epoch 16/20 | Train Loss 1.401360 | Val Loss 2.700449 | Val CCC 0.440066 | Val Acc 0.454545 | Val RMSE 1.061731 | 0.80s
Epoch 17/20 | Train Loss 1.518153 | Val Loss 2.399010 | Val CCC 0.354435 | Val Acc 0.418182 | Val RMSE 1.053134 | 0.80s
Epoch 18/20 | Train Loss 1.469201 | Val Loss 2.580665 | Val CCC 0.390607 | Val Acc 0.418182 | Val RMSE 1.103713 | 0.79s
Epoch 19/20 | Train Loss 1.499191 | Val Loss 2.467220 | Val CCC 0.402174 | Val Acc 0.490909 | Val RMSE 1.061731 | 0.79s
Epoch 20/20 | Train Loss 1.455684 | Val Loss 2.731783 | Val CCC 0.434286 | Val Acc 0.472727 | Val RMSE 1.070259 | 1.09s
====================================================================================================
训练完成：Seed=42，Q3
最佳Val Loss：2.296455，Epoch=7
最佳Val CCC：0.495027，Epoch=13
====================================================================================================
文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q4_PHQ_8Tired/seed_42/best_loss.pt
视频Best Loss： /workspace/E-DAIC/checkpoints/phq8_video_paperlike/seed_42/question_4/best_loss.pt
文本保存Epoch： 11
视频保存Epoch： 7
文本缺少参数： []
文本多余参数： []
视频缺少参数： []
视频多余参数： []
====================================================================================================
开始训练Text+Video：Seed=42，Q4，PHQ_8Tired
类别数量： [50, 65, 27, 21]
ImbOLL权重： [1.8055469989776611, 1.5835695266723633, 2.457038164138794, 2.7860195636749268]
文本预训练模型： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q4_PHQ_8Tired/seed_42/best_loss.pt
视频预训练模型： /workspace/E-DAIC/checkpoints/phq8_video_paperlike/seed_42/question_4/best_loss.pt
====================================================================================================
Epoch 01/20 | Train Loss 2.561941 | Val Loss 2.356330 | Val CCC 0.203423 | Val Acc 0.418182 | Val RMSE 0.894427 | 0.86s
Epoch 02/20 | Train Loss 2.001268 | Val Loss 2.231690 | Val CCC 0.362675 | Val Acc 0.345455 | Val RMSE 1.018019 | 0.96s
Epoch 03/20 | Train Loss 1.716726 | Val Loss 2.269705 | Val CCC 0.386098 | Val Acc 0.363636 | Val RMSE 0.894427 | 0.82s
Epoch 04/20 | Train Loss 1.763890 | Val Loss 2.253688 | Val CCC 0.382947 | Val Acc 0.345455 | Val RMSE 0.904534 | 0.97s
Epoch 05/20 | Train Loss 1.650651 | Val Loss 2.334067 | Val CCC 0.305994 | Val Acc 0.381818 | Val RMSE 1.144155 | 0.98s
Epoch 06/20 | Train Loss 1.760497 | Val Loss 2.262020 | Val CCC 0.328098 | Val Acc 0.381818 | Val RMSE 0.943880 | 0.82s
Epoch 07/20 | Train Loss 1.763097 | Val Loss 2.280631 | Val CCC 0.379533 | Val Acc 0.418182 | Val RMSE 1.009050 | 0.97s
Epoch 08/20 | Train Loss 1.649102 | Val Loss 2.245249 | Val CCC 0.340115 | Val Acc 0.436364 | Val RMSE 0.914529 | 0.82s
Epoch 09/20 | Train Loss 1.646891 | Val Loss 2.299951 | Val CCC 0.393745 | Val Acc 0.381818 | Val RMSE 0.884205 | 0.78s
Epoch 10/20 | Train Loss 1.614561 | Val Loss 2.269840 | Val CCC 0.376700 | Val Acc 0.363636 | Val RMSE 0.953463 | 0.77s
Epoch 11/20 | Train Loss 1.499827 | Val Loss 2.300520 | Val CCC 0.320148 | Val Acc 0.381818 | Val RMSE 1.044466 | 0.85s
Epoch 12/20 | Train Loss 1.613741 | Val Loss 2.273513 | Val CCC 0.250273 | Val Acc 0.363636 | Val RMSE 0.953463 | 0.79s
Epoch 13/20 | Train Loss 1.551050 | Val Loss 2.202472 | Val CCC 0.386332 | Val Acc 0.400000 | Val RMSE 0.934199 | 0.79s
Epoch 14/20 | Train Loss 1.556697 | Val Loss 2.261138 | Val CCC 0.364709 | Val Acc 0.418182 | Val RMSE 0.924416 | 0.84s
Epoch 15/20 | Train Loss 1.431722 | Val Loss 2.300389 | Val CCC 0.348341 | Val Acc 0.363636 | Val RMSE 0.953463 | 0.87s
Epoch 16/20 | Train Loss 1.326841 | Val Loss 2.338092 | Val CCC 0.375109 | Val Acc 0.363636 | Val RMSE 1.087115 | 0.83s
Epoch 17/20 | Train Loss 1.446095 | Val Loss 2.341616 | Val CCC 0.389567 | Val Acc 0.400000 | Val RMSE 1.044466 | 0.83s
Epoch 18/20 | Train Loss 1.304123 | Val Loss 2.534836 | Val CCC 0.353376 | Val Acc 0.309091 | Val RMSE 1.128152 | 0.82s
Epoch 19/20 | Train Loss 1.244723 | Val Loss 2.461531 | Val CCC 0.345002 | Val Acc 0.345455 | Val RMSE 1.095445 | 0.84s
Epoch 20/20 | Train Loss 1.240735 | Val Loss 2.501956 | Val CCC 0.310074 | Val Acc 0.418182 | Val RMSE 1.078720 | 0.82s
====================================================================================================
训练完成：Seed=42，Q4
最佳Val Loss：2.202472，Epoch=13
最佳Val CCC：0.393745，Epoch=9
====================================================================================================
文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q5_PHQ_8Appetite/seed_42/best_loss.pt
视频Best Loss： /workspace/E-DAIC/checkpoints/phq8_video_paperlike/seed_42/question_5/best_loss.pt
文本保存Epoch： 13
视频保存Epoch： 2
文本缺少参数： []
文本多余参数： []
视频缺少参数： []
视频多余参数： []
====================================================================================================
开始训练Text+Video：Seed=42，Q5，PHQ_8Appetite
类别数量： [77, 42, 24, 20]
ImbOLL权重： [1.454951286315918, 1.9700132608413696, 2.6060826778411865, 2.854820728302002]
文本预训练模型： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q5_PHQ_8Appetite/seed_42/best_loss.pt
视频预训练模型： /workspace/E-DAIC/checkpoints/phq8_video_paperlike/seed_42/question_5/best_loss.pt
====================================================================================================
Epoch 01/20 | Train Loss 2.526698 | Val Loss 2.206584 | Val CCC 0.329961 | Val Acc 0.400000 | Val RMSE 1.035725 | 0.79s
Epoch 02/20 | Train Loss 1.846353 | Val Loss 2.487753 | Val CCC 0.362103 | Val Acc 0.381818 | Val RMSE 1.183216 | 0.82s
Epoch 03/20 | Train Loss 1.750483 | Val Loss 2.191651 | Val CCC 0.418699 | Val Acc 0.436364 | Val RMSE 0.972345 | 0.88s
Epoch 04/20 | Train Loss 1.758251 | Val Loss 2.113170 | Val CCC 0.428274 | Val Acc 0.418182 | Val RMSE 0.953463 | 0.83s
Epoch 05/20 | Train Loss 1.617929 | Val Loss 2.208309 | Val CCC 0.493435 | Val Acc 0.472727 | Val RMSE 0.924416 | 0.83s
Epoch 06/20 | Train Loss 1.564798 | Val Loss 2.216485 | Val CCC 0.473324 | Val Acc 0.454545 | Val RMSE 0.873863 | 0.79s
Epoch 07/20 | Train Loss 1.544434 | Val Loss 2.340217 | Val CCC 0.521569 | Val Acc 0.527273 | Val RMSE 0.943880 | 0.77s
Epoch 08/20 | Train Loss 1.558213 | Val Loss 3.629360 | Val CCC 0.432122 | Val Acc 0.454545 | Val RMSE 0.990867 | 0.79s
Epoch 09/20 | Train Loss 1.389131 | Val Loss 2.629044 | Val CCC 0.478467 | Val Acc 0.490909 | Val RMSE 0.934199 | 0.82s
Epoch 10/20 | Train Loss 1.524502 | Val Loss 3.158071 | Val CCC 0.408602 | Val Acc 0.436364 | Val RMSE 1.044466 | 0.79s
Epoch 11/20 | Train Loss 1.370039 | Val Loss 3.250666 | Val CCC 0.452473 | Val Acc 0.454545 | Val RMSE 1.061731 | 0.79s
Epoch 12/20 | Train Loss 1.454587 | Val Loss 2.941314 | Val CCC 0.408249 | Val Acc 0.418182 | Val RMSE 1.144155 | 0.78s
Epoch 13/20 | Train Loss 1.478926 | Val Loss 3.659681 | Val CCC 0.489907 | Val Acc 0.509091 | Val RMSE 0.962950 | 0.80s
Epoch 14/20 | Train Loss 1.565380 | Val Loss 3.034948 | Val CCC 0.435249 | Val Acc 0.418182 | Val RMSE 1.103713 | 0.81s
Epoch 15/20 | Train Loss 1.332322 | Val Loss 2.693855 | Val CCC 0.394068 | Val Acc 0.381818 | Val RMSE 0.972345 | 0.83s
Epoch 16/20 | Train Loss 1.339004 | Val Loss 3.454361 | Val CCC 0.467333 | Val Acc 0.436364 | Val RMSE 1.070259 | 0.83s
Epoch 17/20 | Train Loss 1.351060 | Val Loss 3.491180 | Val CCC 0.445583 | Val Acc 0.454545 | Val RMSE 1.035725 | 0.81s
Epoch 18/20 | Train Loss 1.383292 | Val Loss 3.166627 | Val CCC 0.497553 | Val Acc 0.454545 | Val RMSE 1.009050 | 0.82s
Epoch 19/20 | Train Loss 1.182060 | Val Loss 3.429521 | Val CCC 0.443356 | Val Acc 0.454545 | Val RMSE 1.061731 | 0.81s
Epoch 20/20 | Train Loss 1.208465 | Val Loss 3.644905 | Val CCC 0.478928 | Val Acc 0.472727 | Val RMSE 1.026911 | 0.76s
====================================================================================================
训练完成：Seed=42，Q5
最佳Val Loss：2.113170，Epoch=4
最佳Val CCC：0.521569，Epoch=7
====================================================================================================
文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q6_PHQ_8Failure/seed_42/best_loss.pt
视频Best Loss： /workspace/E-DAIC/checkpoints/phq8_video_paperlike/seed_42/question_6/best_loss.pt
文本保存Epoch： 10
视频保存Epoch： 24
文本缺少参数： []
文本多余参数： []
视频缺少参数： []
视频多余参数： []
====================================================================================================
开始训练Text+Video：Seed=42，Q6，PHQ_8Failure
类别数量： [76, 44, 24, 19]
ImbOLL权重： [1.4644919633865356, 1.9247195720672607, 2.6060826778411865, 2.9289839267730713]
文本预训练模型： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q6_PHQ_8Failure/seed_42/best_loss.pt
视频预训练模型： /workspace/E-DAIC/checkpoints/phq8_video_paperlike/seed_42/question_6/best_loss.pt
====================================================================================================
Epoch 01/20 | Train Loss 2.316333 | Val Loss 2.009878 | Val CCC 0.471694 | Val Acc 0.509091 | Val RMSE 0.924416 | 0.76s
Epoch 02/20 | Train Loss 1.750225 | Val Loss 2.084463 | Val CCC 0.454760 | Val Acc 0.436364 | Val RMSE 1.070259 | 0.77s
Epoch 03/20 | Train Loss 1.706852 | Val Loss 2.023254 | Val CCC 0.466434 | Val Acc 0.509091 | Val RMSE 0.953463 | 0.78s
Epoch 04/20 | Train Loss 1.663211 | Val Loss 2.012009 | Val CCC 0.439216 | Val Acc 0.472727 | Val RMSE 0.972345 | 0.81s
Epoch 05/20 | Train Loss 1.589257 | Val Loss 2.028607 | Val CCC 0.427188 | Val Acc 0.436364 | Val RMSE 1.018019 | 0.78s
Epoch 06/20 | Train Loss 1.548712 | Val Loss 2.069849 | Val CCC 0.458177 | Val Acc 0.472727 | Val RMSE 1.000000 | 0.76s
Epoch 07/20 | Train Loss 1.499787 | Val Loss 2.035559 | Val CCC 0.484554 | Val Acc 0.490909 | Val RMSE 0.990867 | 0.78s
Epoch 08/20 | Train Loss 1.366080 | Val Loss 2.353538 | Val CCC 0.459915 | Val Acc 0.436364 | Val RMSE 1.103713 | 0.77s
Epoch 09/20 | Train Loss 1.627829 | Val Loss 2.009271 | Val CCC 0.475987 | Val Acc 0.490909 | Val RMSE 0.943880 | 0.77s
Epoch 10/20 | Train Loss 1.518795 | Val Loss 2.124065 | Val CCC 0.485122 | Val Acc 0.472727 | Val RMSE 1.009050 | 0.76s
Epoch 11/20 | Train Loss 1.402005 | Val Loss 2.410857 | Val CCC 0.407540 | Val Acc 0.454545 | Val RMSE 1.044466 | 0.78s
Epoch 12/20 | Train Loss 1.476324 | Val Loss 2.057094 | Val CCC 0.442278 | Val Acc 0.490909 | Val RMSE 0.972345 | 0.78s
Epoch 13/20 | Train Loss 1.285449 | Val Loss 2.233061 | Val CCC 0.463902 | Val Acc 0.418182 | Val RMSE 1.035725 | 0.79s
Epoch 14/20 | Train Loss 1.333127 | Val Loss 2.876388 | Val CCC 0.415439 | Val Acc 0.509091 | Val RMSE 1.018019 | 0.80s
Epoch 15/20 | Train Loss 1.386249 | Val Loss 2.341337 | Val CCC 0.505618 | Val Acc 0.472727 | Val RMSE 1.009050 | 0.78s
Epoch 16/20 | Train Loss 1.312650 | Val Loss 2.460697 | Val CCC 0.368800 | Val Acc 0.509091 | Val RMSE 1.035725 | 0.76s
Epoch 17/20 | Train Loss 1.307794 | Val Loss 2.301739 | Val CCC 0.396879 | Val Acc 0.490909 | Val RMSE 0.972345 | 0.77s
Epoch 18/20 | Train Loss 1.340449 | Val Loss 2.465565 | Val CCC 0.366174 | Val Acc 0.509091 | Val RMSE 1.136182 | 0.78s
Epoch 19/20 | Train Loss 1.310903 | Val Loss 2.597850 | Val CCC 0.399376 | Val Acc 0.472727 | Val RMSE 1.009050 | 0.77s
Epoch 20/20 | Train Loss 1.278786 | Val Loss 2.138638 | Val CCC 0.503511 | Val Acc 0.490909 | Val RMSE 0.990867 | 0.82s
====================================================================================================
训练完成：Seed=42，Q6
最佳Val Loss：2.009271，Epoch=9
最佳Val CCC：0.505618，Epoch=15
====================================================================================================
文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q7_PHQ_8Concentrating/seed_42/best_loss.pt
视频Best Loss： /workspace/E-DAIC/checkpoints/phq8_video_paperlike/seed_42/question_7/best_loss.pt
文本保存Epoch： 15
视频保存Epoch： 1
文本缺少参数： []
文本多余参数： []
视频缺少参数： []
视频多余参数： []
====================================================================================================
开始训练Text+Video：Seed=42，Q7，PHQ_8Concentrating
类别数量： [93, 37, 14, 19]
ImbOLL权重： [1.323891282081604, 2.0989058017730713, 3.412163257598877, 2.9289839267730713]
文本预训练模型： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q7_PHQ_8Concentrating/seed_42/best_loss.pt
视频预训练模型： /workspace/E-DAIC/checkpoints/phq8_video_paperlike/seed_42/question_7/best_loss.pt
====================================================================================================
Epoch 01/20 | Train Loss 2.414542 | Val Loss 1.996084 | Val CCC 0.371600 | Val Acc 0.654545 | Val RMSE 0.873863 | 0.78s
Epoch 02/20 | Train Loss 1.479271 | Val Loss 2.619741 | Val CCC 0.412979 | Val Acc 0.472727 | Val RMSE 1.167748 | 0.78s
Epoch 03/20 | Train Loss 1.652789 | Val Loss 2.196574 | Val CCC 0.543779 | Val Acc 0.454545 | Val RMSE 0.809040 | 0.82s
Epoch 04/20 | Train Loss 1.497906 | Val Loss 1.949242 | Val CCC 0.521249 | Val Acc 0.600000 | Val RMSE 0.786245 | 0.79s
Epoch 05/20 | Train Loss 1.395185 | Val Loss 1.969999 | Val CCC 0.544861 | Val Acc 0.527273 | Val RMSE 0.831209 | 0.79s
Epoch 06/20 | Train Loss 1.390548 | Val Loss 2.140259 | Val CCC 0.503488 | Val Acc 0.418182 | Val RMSE 0.894427 | 0.79s
Epoch 07/20 | Train Loss 1.224837 | Val Loss 2.054720 | Val CCC 0.504292 | Val Acc 0.509091 | Val RMSE 0.873863 | 0.76s
Epoch 08/20 | Train Loss 1.274383 | Val Loss 2.177660 | Val CCC 0.525163 | Val Acc 0.527273 | Val RMSE 0.863397 | 0.76s
Epoch 09/20 | Train Loss 1.297342 | Val Loss 2.057773 | Val CCC 0.559585 | Val Acc 0.490909 | Val RMSE 0.786245 | 0.77s
Epoch 10/20 | Train Loss 1.395232 | Val Loss 2.063597 | Val CCC 0.561753 | Val Acc 0.454545 | Val RMSE 0.809040 | 0.79s
Epoch 11/20 | Train Loss 1.229378 | Val Loss 2.085861 | Val CCC 0.544861 | Val Acc 0.527273 | Val RMSE 0.831209 | 0.79s
Epoch 12/20 | Train Loss 1.224050 | Val Loss 1.982227 | Val CCC 0.512593 | Val Acc 0.527273 | Val RMSE 0.831209 | 0.82s
Epoch 13/20 | Train Loss 1.239506 | Val Loss 2.222515 | Val CCC 0.493827 | Val Acc 0.363636 | Val RMSE 0.863397 | 0.83s
Epoch 14/20 | Train Loss 1.183347 | Val Loss 2.590020 | Val CCC 0.429942 | Val Acc 0.490909 | Val RMSE 0.990867 | 0.83s

In [130]:
print("Seed 42结果数量：", len(text_video_seed42_results))
print("Best Loss全部存在：", all(result["best_loss_path"].exists() for result in text_video_seed42_results))
print("Best CCC全部存在：", all(result["best_ccc_path"].exists() for result in text_video_seed42_results))
print("Last全部存在：", all(result["last_path"].exists() for result in text_video_seed42_results))
print("History全部存在：", all(result["history_path"].exists() for result in text_video_seed42_results))

Seed 42结果数量： 8
Best Loss全部存在： True
Best CCC全部存在： True
Last全部存在： True
History全部存在： True

In [131]:
text_video_seed42_summary_rows = []
for result in text_video_seed42_results:
    text_video_seed42_summary_rows.append({"Seed": result["seed"], "Question_Index": result["question_index"], "Question_Number": result["question_number"], "Question_Name": result["question"], "Best_Val_Loss": result["best_val_loss"], "Best_Loss_Epoch": result["best_loss_epoch"], "Best_Val_CCC": result["best_val_ccc"], "Best_CCC_Epoch": result["best_ccc_epoch"]})
text_video_seed42_summary_df = pd.DataFrame(text_video_seed42_summary_rows)
text_video_seed42_summary_path = TEXT_VIDEO_CHECKPOINT_ROOT / "seed_42_question_summary.csv"
text_video_seed42_summary_df.to_csv(text_video_seed42_summary_path, index=False)
display(text_video_seed42_summary_df)
print("汇总文件：", text_video_seed42_summary_path)

,Seed,Question_Index,Question_Number,Question_Name,Best_Val_Loss,Best_Loss_Epoch,Best_Val_CCC,Best_CCC_Epoch
0,42,0,1,PHQ_8NoInterest,2.487444,3,0.430305,6
1,42,1,2,PHQ_8Depressed,1.972233,5,0.560924,9
2,42,2,3,PHQ_8Sleep,2.296455,7,0.495027,13
3,42,3,4,PHQ_8Tired,2.202472,13,0.393745,9
4,42,4,5,PHQ_8Appetite,2.113170,4,0.521569,7
5,42,5,6,PHQ_8Failure,2.009271,9,0.505618,15
6,42,6,7,PHQ_8Concentrating,1.949242,4,0.561753,10
7,42,7,8,PHQ_8Moving,1.833960,1,0.345725,19

汇总文件： /workspace/E-DAIC/checkpoints/phq8_text_video_paperlike/seed_42_question_summary.csv

In [132]:
text_video_seed42_best_ccc_rows = []
for result in text_video_seed42_results:
    checkpoint = torch.load(result["best_ccc_path"], map_location="cpu", weights_only=False)
    text_video_seed42_best_ccc_rows.append({"Question_Number": checkpoint["question_number"], "Question_Name": checkpoint["question"], "Checkpoint_Epoch": checkpoint["epoch"], "CCC": checkpoint["val_metrics"]["ccc"], "RMSE": checkpoint["val_metrics"]["rmse"], "MAE": checkpoint["val_metrics"]["mae"], "Accuracy": checkpoint["val_metrics"]["accuracy"]})
text_video_seed42_best_ccc_df = pd.DataFrame(text_video_seed42_best_ccc_rows)
display(text_video_seed42_best_ccc_df)

,Question_Number,Question_Name,Checkpoint_Epoch,CCC,RMSE,MAE,Accuracy
0,1,PHQ_8NoInterest,6,0.430305,0.797724,0.454545,0.618182
1,2,PHQ_8Depressed,9,0.560924,0.831209,0.509091,0.581818
2,3,PHQ_8Sleep,13,0.495027,1.144155,0.763636,0.454545
3,4,PHQ_8Tired,9,0.393745,0.884205,0.672727,0.381818
4,5,PHQ_8Appetite,7,0.521569,0.943880,0.600000,0.527273
5,6,PHQ_8Failure,15,0.505618,1.009050,0.690909,0.472727
6,7,PHQ_8Concentrating,10,0.561753,0.809040,0.581818,0.454545
7,8,PHQ_8Moving,19,0.345725,0.762770,0.472727,0.581818

In [133]:
def evaluate_text_video_seed_on_validation(seed):
    val_loader = DataLoader(text_video_val_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=0, drop_last=False)
    question_prediction_list = []
    selected_checkpoint_rows = []
    for question_index in range(len(PHQ8_QUESTION_COLUMNS)):
        checkpoint_path = TEXT_VIDEO_CHECKPOINT_ROOT / f"seed_{seed}" / f"question_{question_index + 1}" / "best_ccc.pt"
        if not checkpoint_path.exists():
            raise FileNotFoundError(f"Checkpoint不存在：{checkpoint_path}")
        checkpoint = torch.load(checkpoint_path, map_location="cpu", weights_only=False)
        if checkpoint["seed"] != seed or checkpoint["question_index"] != question_index or checkpoint["checkpoint_type"] != "best_ccc":
            raise RuntimeError(f"Checkpoint元数据错误：{checkpoint_path}")
        model = TextVideoQuestMF(PretrainedTextEncoder(), PretrainedVideoEncoder()).to(device)
        load_result = model.load_state_dict(checkpoint["model_state_dict"], strict=True)
        if load_result.missing_keys or load_result.unexpected_keys:
            raise RuntimeError(f"Checkpoint参数不一致：{checkpoint_path}")
        model.eval()
        batch_prediction_list = []
        with torch.no_grad():
            for text_features, text_masks, video_features, video_masks, all_labels in val_loader:
                logits = model(text_features.to(device), text_masks.to(device), video_features.to(device), video_masks.to(device))
                batch_prediction_list.append(logits.argmax(dim=1).cpu())
        question_predictions = torch.cat(batch_prediction_list)
        if len(question_predictions) != len(text_video_val_dataset):
            raise RuntimeError(f"Q{question_index + 1}预测数量错误")
        question_prediction_list.append(question_predictions)
        selected_checkpoint_rows.append({"Seed": seed, "Question_Index": question_index, "Question_Number": question_index + 1, "Question_Name": PHQ8_QUESTION_COLUMNS[question_index], "Checkpoint_Path": str(checkpoint_path), "Checkpoint_Epoch": checkpoint["epoch"], "Validation_CCC": checkpoint["val_metrics"]["ccc"]})
        print(f"Q{question_index + 1} | Epoch {checkpoint['epoch']:02d} | Val CCC {checkpoint['val_metrics']['ccc']:.6f}")
        del model
        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
    question_predictions = torch.stack(question_prediction_list, dim=1)
    question_targets = text_video_val_dataset.labels.clone()
    predicted_totals = question_predictions.sum(dim=1)
    true_totals = question_targets.sum(dim=1)
    total_ccc = calculate_ccc(predicted_totals, true_totals)
    total_rmse = float(torch.sqrt(torch.mean((predicted_totals.float() - true_totals.float()) ** 2)).item())
    total_mae = float(torch.mean(torch.abs(predicted_totals.float() - true_totals.float())).item())
    exact_accuracy = float((predicted_totals == true_totals).float().mean().item())
    prediction_df = pd.DataFrame({"Participant_ID": text_video_val_dataset.participant_ids})
    for question_index in range(len(PHQ8_QUESTION_COLUMNS)):
        prediction_df[f"Q{question_index + 1}_Predicted"] = question_predictions[:, question_index].numpy()
        prediction_df[f"Q{question_index + 1}_True"] = question_targets[:, question_index].numpy()
    prediction_df["Predicted_Total"] = predicted_totals.numpy()
    prediction_df["True_Total"] = true_totals.numpy()
    prediction_path = TEXT_VIDEO_CHECKPOINT_ROOT / f"seed_{seed}_validation_predictions.csv"
    selected_checkpoint_path = TEXT_VIDEO_CHECKPOINT_ROOT / f"seed_{seed}_validation_selected_checkpoints.csv"
    prediction_df.to_csv(prediction_path, index=False)
    pd.DataFrame(selected_checkpoint_rows).to_csv(selected_checkpoint_path, index=False)
    print("=" * 70)
    print(f"Text+Video Seed {seed}验证结果")
    print("=" * 70)
    print("验证参与者数量：", len(prediction_df))
    print(f"总分CCC：{total_ccc:.6f}")
    print(f"总分RMSE：{total_rmse:.6f}")
    print(f"总分MAE：{total_mae:.6f}")
    print(f"完全相等比例：{exact_accuracy:.6f}")
    print(f"预测总分范围：{int(predicted_totals.min())}～{int(predicted_totals.max())}")
    print(f"真实总分范围：{int(true_totals.min())}～{int(true_totals.max())}")
    print("预测文件：", prediction_path)
    return {"seed": seed, "sample_count": len(prediction_df), "ccc": total_ccc, "rmse": total_rmse, "mae": total_mae, "exact_accuracy": exact_accuracy, "question_predictions": question_predictions, "question_targets": question_targets, "predicted_totals": predicted_totals, "true_totals": true_totals, "prediction_path": prediction_path, "selected_checkpoint_path": selected_checkpoint_path}

In [134]:
text_video_seed42_validation_result = evaluate_text_video_seed_on_validation(seed=42)

Q1 | Epoch 06 | Val CCC 0.430305
Q2 | Epoch 09 | Val CCC 0.560924
Q3 | Epoch 13 | Val CCC 0.495027
Q4 | Epoch 09 | Val CCC 0.393745
Q5 | Epoch 07 | Val CCC 0.521569
Q6 | Epoch 15 | Val CCC 0.505618
Q7 | Epoch 10 | Val CCC 0.561753
Q8 | Epoch 19 | Val CCC 0.345725
======================================================================
Text+Video Seed 42验证结果
======================================================================
验证参与者数量： 55
总分CCC：0.680283
总分RMSE：4.421024
总分MAE：3.218182
完全相等比例：0.072727
预测总分范围：1～22
真实总分范围：0～20
预测文件： /workspace/E-DAIC/checkpoints/phq8_text_video_paperlike/seed_42_validation_predictions.csv

In [135]:
def train_all_text_video_questions_for_seed(seed):
    seed_results = []
    print("#" * 100)
    print(f"开始训练Text+Video全部问题：Seed={seed}")
    print("#" * 100)
    for question_index in range(len(PHQ8_QUESTION_COLUMNS)):
        result = train_text_video_question(seed=seed, question_index=question_index)
        seed_results.append(result)
        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
    summary_rows = []
    for result in seed_results:
        summary_rows.append({"Seed": result["seed"], "Question_Index": result["question_index"], "Question_Number": result["question_number"], "Question_Name": result["question"], "Best_Val_Loss": result["best_val_loss"], "Best_Loss_Epoch": result["best_loss_epoch"], "Best_Val_CCC": result["best_val_ccc"], "Best_CCC_Epoch": result["best_ccc_epoch"]})
    summary_df = pd.DataFrame(summary_rows)
    summary_path = TEXT_VIDEO_CHECKPOINT_ROOT / f"seed_{seed}_question_summary.csv"
    summary_df.to_csv(summary_path, index=False)
    print(f"Seed {seed}全部问题训练完成")
    print("汇总文件：", summary_path)
    return seed_results, summary_df

In [136]:
text_video_seed100_results, text_video_seed100_summary_df = train_all_text_video_questions_for_seed(seed=100)
display(text_video_seed100_summary_df)

####################################################################################################
开始训练Text+Video全部问题：Seed=100
####################################################################################################
文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q1_PHQ_8NoInterest/seed_100/best_loss.pt
视频Best Loss： /workspace/E-DAIC/checkpoints/phq8_video_paperlike/seed_100/question_1/best_loss.pt
文本保存Epoch： 10
视频保存Epoch： 14
文本缺少参数： []
文本多余参数： []
视频缺少参数： []
视频多余参数： []
====================================================================================================
开始训练Text+Video：Seed=100，Q1，PHQ_8NoInterest
类别数量： [81, 57, 20, 5]
ImbOLL权重： [1.4185717105865479, 1.6910496950149536, 2.854820728302002, 5.709641456604004]
文本预训练模型： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q1_PHQ_8NoInterest/seed_100/best_loss.pt
视频预训练模型： /workspace/E-DAIC/checkpoints/phq8_video_paperlike/seed_100/question_1/best_loss.pt
====================================================================================================
Epoch 01/20 | Train Loss 2.345769 | Val Loss 2.816593 | Val CCC 0.258903 | Val Acc 0.490909 | Val RMSE 1.009050 | 1.72s
Epoch 02/20 | Train Loss 1.495146 | Val Loss 3.161104 | Val CCC 0.273128 | Val Acc 0.527273 | Val RMSE 0.990867 | 1.21s
Epoch 03/20 | Train Loss 1.628791 | Val Loss 3.095933 | Val CCC 0.372941 | Val Acc 0.545455 | Val RMSE 0.904534 | 1.30s
Epoch 04/20 | Train Loss 1.592468 | Val Loss 2.533762 | Val CCC 0.363493 | Val Acc 0.509091 | Val RMSE 0.894427 | 1.13s
Epoch 05/20 | Train Loss 1.480403 | Val Loss 2.540253 | Val CCC 0.324183 | Val Acc 0.509091 | Val RMSE 0.924416 | 1.36s
Epoch 06/20 | Train Loss 1.429298 | Val Loss 3.179062 | Val CCC 0.309392 | Val Acc 0.545455 | Val RMSE 0.953463 | 1.01s
Epoch 07/20 | Train Loss 1.354872 | Val Loss 2.880417 | Val CCC 0.333782 | Val Acc 0.490909 | Val RMSE 0.904534 | 1.05s
Epoch 08/20 | Train Loss 1.329936 | Val Loss 3.120609 | Val CCC 0.426514 | Val Acc 0.581818 | Val RMSE 0.873863 | 1.14s
Epoch 09/20 | Train Loss 1.392017 | Val Loss 2.858819 | Val CCC 0.364418 | Val Acc 0.527273 | Val RMSE 0.884205 | 1.02s
Epoch 10/20 | Train Loss 1.217574 | Val Loss 3.319555 | Val CCC 0.364570 | Val Acc 0.581818 | Val RMSE 0.904534 | 1.27s
Epoch 11/20 | Train Loss 1.250989 | Val Loss 2.776283 | Val CCC 0.323121 | Val Acc 0.454545 | Val RMSE 0.924416 | 0.86s
Epoch 12/20 | Train Loss 1.348153 | Val Loss 2.879763 | Val CCC 0.390428 | Val Acc 0.563636 | Val RMSE 0.894427 | 1.08s
Epoch 13/20 | Train Loss 1.275077 | Val Loss 2.724122 | Val CCC 0.322079 | Val Acc 0.472727 | Val RMSE 0.914529 | 1.09s
Epoch 14/20 | Train Loss 1.337017 | Val Loss 2.701435 | Val CCC 0.382022 | Val Acc 0.490909 | Val RMSE 0.873863 | 0.87s
Epoch 15/20 | Train Loss 1.231086 | Val Loss 3.894313 | Val CCC 0.371728 | Val Acc 0.527273 | Val RMSE 0.934199 | 1.10s
Epoch 16/20 | Train Loss 1.145360 | Val Loss 3.249468 | Val CCC 0.446266 | Val Acc 0.527273 | Val RMSE 0.884205 | 1.05s
Epoch 17/20 | Train Loss 1.173392 | Val Loss 3.133763 | Val CCC 0.380440 | Val Acc 0.509091 | Val RMSE 0.894427 | 1.10s
Epoch 18/20 | Train Loss 1.116357 | Val Loss 3.306975 | Val CCC 0.401554 | Val Acc 0.545455 | Val RMSE 0.873863 | 1.25s
Epoch 19/20 | Train Loss 1.170757 | Val Loss 3.537133 | Val CCC 0.181045 | Val Acc 0.509091 | Val RMSE 1.070259 | 0.95s
Epoch 20/20 | Train Loss 1.259834 | Val Loss 3.132009 | Val CCC 0.455722 | Val Acc 0.600000 | Val RMSE 0.842075 | 1.06s
====================================================================================================
训练完成：Seed=100，Q1
最佳Val Loss：2.533762，Epoch=4
最佳Val CCC：0.455722，Epoch=20
====================================================================================================
文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q2_PHQ_8Depressed/seed_100/best_loss.pt
视频Best Loss： /workspace/E-DAIC/checkpoints/phq8_video_paperlike/seed_100/question_2/best_loss.pt
文本保存Epoch： 8
视频保存Epoch： 2
文本缺少参数： []
文本多余参数： []
视频缺少参数： []
视频多余参数： []
====================================================================================================
开始训练Text+Video：Seed=100，Q2，PHQ_8Depressed
类别数量： [68, 63, 18, 14]
ImbOLL权重： [1.548243761062622, 1.6085091829299927, 3.009244918823242, 3.412163257598877]
文本预训练模型： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q2_PHQ_8Depressed/seed_100/best_loss.pt
视频预训练模型： /workspace/E-DAIC/checkpoints/phq8_video_paperlike/seed_100/question_2/best_loss.pt
====================================================================================================
Epoch 01/20 | Train Loss 2.339814 | Val Loss 1.989424 | Val CCC 0.467942 | Val Acc 0.527273 | Val RMSE 0.884205 | 0.86s
Epoch 02/20 | Train Loss 1.784731 | Val Loss 2.014458 | Val CCC 0.500528 | Val Acc 0.527273 | Val RMSE 0.884205 | 1.01s
Epoch 03/20 | Train Loss 1.647062 | Val Loss 1.984165 | Val CCC 0.437956 | Val Acc 0.472727 | Val RMSE 0.943880 | 1.04s
Epoch 04/20 | Train Loss 1.640660 | Val Loss 2.046705 | Val CCC 0.514706 | Val Acc 0.545455 | Val RMSE 0.873863 | 0.92s
Epoch 05/20 | Train Loss 1.749993 | Val Loss 1.969292 | Val CCC 0.431274 | Val Acc 0.454545 | Val RMSE 0.863397 | 0.95s
Epoch 06/20 | Train Loss 1.652789 | Val Loss 1.957756 | Val CCC 0.467742 | Val Acc 0.545455 | Val RMSE 0.873863 | 0.81s
Epoch 07/20 | Train Loss 1.502058 | Val Loss 1.985989 | Val CCC 0.486200 | Val Acc 0.563636 | Val RMSE 0.894427 | 1.01s
Epoch 08/20 | Train Loss 1.591133 | Val Loss 1.932924 | Val CCC 0.509249 | Val Acc 0.563636 | Val RMSE 0.863397 | 0.92s
Epoch 09/20 | Train Loss 1.734874 | Val Loss 1.983565 | Val CCC 0.469112 | Val Acc 0.509091 | Val RMSE 0.953463 | 1.01s
Epoch 10/20 | Train Loss 1.533625 | Val Loss 1.978489 | Val CCC 0.468966 | Val Acc 0.490909 | Val RMSE 0.873863 | 0.80s
Epoch 11/20 | Train Loss 1.505358 | Val Loss 1.939112 | Val CCC 0.452489 | Val Acc 0.509091 | Val RMSE 0.894427 | 0.79s
Epoch 12/20 | Train Loss 1.540933 | Val Loss 1.985205 | Val CCC 0.473913 | Val Acc 0.563636 | Val RMSE 0.894427 | 0.80s
Epoch 13/20 | Train Loss 1.547093 | Val Loss 1.932262 | Val CCC 0.458128 | Val Acc 0.472727 | Val RMSE 0.852803 | 0.81s
Epoch 14/20 | Train Loss 1.703729 | Val Loss 1.949594 | Val CCC 0.481799 | Val Acc 0.563636 | Val RMSE 0.894427 | 0.86s
Epoch 15/20 | Train Loss 1.582205 | Val Loss 2.050389 | Val CCC 0.451098 | Val Acc 0.545455 | Val RMSE 0.953463 | 0.80s
Epoch 16/20 | Train Loss 1.539688 | Val Loss 2.104624 | Val CCC 0.355801 | Val Acc 0.400000 | Val RMSE 0.981650 | 0.79s
Epoch 17/20 | Train Loss 1.524849 | Val Loss 1.931162 | Val CCC 0.433255 | Val Acc 0.509091 | Val RMSE 0.894427 | 0.81s
Epoch 18/20 | Train Loss 1.557376 | Val Loss 1.953590 | Val CCC 0.440678 | Val Acc 0.490909 | Val RMSE 0.904534 | 0.80s
Epoch 19/20 | Train Loss 1.567691 | Val Loss 1.989572 | Val CCC 0.507782 | Val Acc 0.527273 | Val RMSE 0.914529 | 0.81s
Epoch 20/20 | Train Loss 1.583970 | Val Loss 1.999399 | Val CCC 0.475028 | Val Acc 0.472727 | Val RMSE 0.884205 | 0.82s
====================================================================================================
训练完成：Seed=100，Q2
最佳Val Loss：1.931162，Epoch=17
最佳Val CCC：0.514706，Epoch=4
====================================================================================================
文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q3_PHQ_8Sleep/seed_100/best_loss.pt
视频Best Loss： /workspace/E-DAIC/checkpoints/phq8_video_paperlike/seed_100/question_3/best_loss.pt
文本保存Epoch： 13
视频保存Epoch： 9
文本缺少参数： []
文本多余参数： []
视频缺少参数： []
视频多余参数： []
====================================================================================================
开始训练Text+Video：Seed=100，Q3，PHQ_8Sleep
类别数量： [69, 40, 27, 27]
ImbOLL权重： [1.5369837284088135, 2.018662929534912, 2.457038164138794, 2.457038164138794]
文本预训练模型： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q3_PHQ_8Sleep/seed_100/best_loss.pt
视频预训练模型： /workspace/E-DAIC/checkpoints/phq8_video_paperlike/seed_100/question_3/best_loss.pt
====================================================================================================
Epoch 01/20 | Train Loss 2.354433 | Val Loss 2.518474 | Val CCC 0.337712 | Val Acc 0.418182 | Val RMSE 1.264911 | 0.90s
Epoch 02/20 | Train Loss 1.764707 | Val Loss 2.430608 | Val CCC 0.327477 | Val Acc 0.454545 | Val RMSE 1.257704 | 0.95s
Epoch 03/20 | Train Loss 1.680320 | Val Loss 2.276807 | Val CCC 0.377154 | Val Acc 0.472727 | Val RMSE 1.120065 | 0.93s
Epoch 04/20 | Train Loss 1.589822 | Val Loss 2.916052 | Val CCC 0.369427 | Val Acc 0.381818 | Val RMSE 1.279204 | 0.88s
Epoch 05/20 | Train Loss 1.645461 | Val Loss 2.338046 | Val CCC 0.365619 | Val Acc 0.490909 | Val RMSE 1.152073 | 0.84s
Epoch 06/20 | Train Loss 1.715279 | Val Loss 2.375293 | Val CCC 0.391960 | Val Acc 0.472727 | Val RMSE 1.183216 | 0.83s
Epoch 07/20 | Train Loss 1.467581 | Val Loss 2.530344 | Val CCC 0.284001 | Val Acc 0.454545 | Val RMSE 1.175508 | 0.84s
Epoch 08/20 | Train Loss 1.702060 | Val Loss 2.497274 | Val CCC 0.338035 | Val Acc 0.454545 | Val RMSE 1.300350 | 0.85s
Epoch 09/20 | Train Loss 1.784876 | Val Loss 2.637651 | Val CCC 0.384984 | Val Acc 0.400000 | Val RMSE 1.235829 | 0.82s
Epoch 10/20 | Train Loss 1.651768 | Val Loss 2.385680 | Val CCC 0.373613 | Val Acc 0.472727 | Val RMSE 1.183216 | 0.82s
Epoch 11/20 | Train Loss 1.610016 | Val Loss 2.484501 | Val CCC 0.376417 | Val Acc 0.472727 | Val RMSE 1.206045 | 0.82s
Epoch 12/20 | Train Loss 1.561707 | Val Loss 2.900729 | Val CCC 0.327128 | Val Acc 0.400000 | Val RMSE 1.293340 | 0.84s
Epoch 13/20 | Train Loss 1.618216 | Val Loss 2.497304 | Val CCC 0.255669 | Val Acc 0.418182 | Val RMSE 1.159937 | 0.83s
Epoch 14/20 | Train Loss 1.549969 | Val Loss 2.478544 | Val CCC 0.396825 | Val Acc 0.490909 | Val RMSE 1.175508 | 0.85s
Epoch 15/20 | Train Loss 1.579141 | Val Loss 2.884895 | Val CCC 0.365733 | Val Acc 0.454545 | Val RMSE 1.235829 | 0.83s
Epoch 16/20 | Train Loss 1.555157 | Val Loss 3.679461 | Val CCC 0.319417 | Val Acc 0.400000 | Val RMSE 1.394796 | 0.81s
Epoch 17/20 | Train Loss 1.559432 | Val Loss 2.631339 | Val CCC 0.272581 | Val Acc 0.436364 | Val RMSE 1.221028 | 0.83s
Epoch 18/20 | Train Loss 1.563547 | Val Loss 2.783171 | Val CCC 0.322965 | Val Acc 0.436364 | Val RMSE 1.300350 | 0.86s
Epoch 19/20 | Train Loss 1.488812 | Val Loss 2.859885 | Val CCC 0.300922 | Val Acc 0.472727 | Val RMSE 1.206045 | 0.83s
Epoch 20/20 | Train Loss 1.376118 | Val Loss 3.341859 | Val CCC 0.366970 | Val Acc 0.509091 | Val RMSE 1.250454 | 0.82s
====================================================================================================
训练完成：Seed=100，Q3
最佳Val Loss：2.276807，Epoch=3
最佳Val CCC：0.396825，Epoch=14
====================================================================================================
文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q4_PHQ_8Tired/seed_100/best_loss.pt
视频Best Loss： /workspace/E-DAIC/checkpoints/phq8_video_paperlike/seed_100/question_4/best_loss.pt
文本保存Epoch： 8
视频保存Epoch： 6
文本缺少参数： []
文本多余参数： []
视频缺少参数： []
视频多余参数： []
====================================================================================================
开始训练Text+Video：Seed=100，Q4，PHQ_8Tired
类别数量： [50, 65, 27, 21]
ImbOLL权重： [1.8055469989776611, 1.5835695266723633, 2.457038164138794, 2.7860195636749268]
文本预训练模型： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q4_PHQ_8Tired/seed_100/best_loss.pt
视频预训练模型： /workspace/E-DAIC/checkpoints/phq8_video_paperlike/seed_100/question_4/best_loss.pt
====================================================================================================
Epoch 01/20 | Train Loss 2.546995 | Val Loss 2.312688 | Val CCC 0.409222 | Val Acc 0.309091 | Val RMSE 0.863397 | 0.81s
Epoch 02/20 | Train Loss 2.045777 | Val Loss 2.188810 | Val CCC 0.248366 | Val Acc 0.327273 | Val RMSE 0.914529 | 0.80s
Epoch 03/20 | Train Loss 1.871187 | Val Loss 2.206732 | Val CCC 0.426540 | Val Acc 0.309091 | Val RMSE 0.894427 | 0.79s
Epoch 04/20 | Train Loss 1.993814 | Val Loss 2.158914 | Val CCC 0.314448 | Val Acc 0.309091 | Val RMSE 0.894427 | 0.79s
Epoch 05/20 | Train Loss 1.865173 | Val Loss 2.199321 | Val CCC 0.400758 | Val Acc 0.327273 | Val RMSE 0.914529 | 0.79s
Epoch 06/20 | Train Loss 1.962764 | Val Loss 2.211928 | Val CCC 0.322155 | Val Acc 0.327273 | Val RMSE 0.884205 | 0.80s
Epoch 07/20 | Train Loss 1.910756 | Val Loss 2.168735 | Val CCC 0.382601 | Val Acc 0.345455 | Val RMSE 0.934199 | 0.80s
Epoch 08/20 | Train Loss 1.946053 | Val Loss 2.132430 | Val CCC 0.361446 | Val Acc 0.309091 | Val RMSE 0.981650 | 0.80s
Epoch 09/20 | Train Loss 1.886808 | Val Loss 2.146814 | Val CCC 0.320623 | Val Acc 0.327273 | Val RMSE 0.914529 | 0.82s
Epoch 10/20 | Train Loss 1.955475 | Val Loss 2.218014 | Val CCC 0.296275 | Val Acc 0.345455 | Val RMSE 0.904534 | 0.80s
Epoch 11/20 | Train Loss 1.875956 | Val Loss 2.184942 | Val CCC 0.337721 | Val Acc 0.327273 | Val RMSE 0.884205 | 0.81s
Epoch 12/20 | Train Loss 1.878985 | Val Loss 2.153634 | Val CCC 0.384129 | Val Acc 0.381818 | Val RMSE 0.914529 | 0.78s
Epoch 13/20 | Train Loss 1.840649 | Val Loss 2.152825 | Val CCC 0.478673 | Val Acc 0.436364 | Val RMSE 0.972345 | 0.78s
Epoch 14/20 | Train Loss 1.812776 | Val Loss 2.196086 | Val CCC 0.398066 | Val Acc 0.327273 | Val RMSE 0.884205 | 0.79s
Epoch 15/20 | Train Loss 1.789865 | Val Loss 2.302310 | Val CCC 0.380183 | Val Acc 0.309091 | Val RMSE 0.981650 | 0.78s
Epoch 16/20 | Train Loss 1.762141 | Val Loss 2.205199 | Val CCC 0.319720 | Val Acc 0.345455 | Val RMSE 0.981650 | 0.79s
Epoch 17/20 | Train Loss 1.733220 | Val Loss 2.526518 | Val CCC 0.356876 | Val Acc 0.309091 | Val RMSE 0.953463 | 0.80s
Epoch 18/20 | Train Loss 1.745433 | Val Loss 2.146735 | Val CCC 0.472912 | Val Acc 0.381818 | Val RMSE 0.943880 | 0.80s
Epoch 19/20 | Train Loss 1.738510 | Val Loss 2.275889 | Val CCC 0.373057 | Val Acc 0.309091 | Val RMSE 0.894427 | 0.78s
Epoch 20/20 | Train Loss 1.701757 | Val Loss 2.332767 | Val CCC 0.437956 | Val Acc 0.345455 | Val RMSE 0.873863 | 0.76s
====================================================================================================
训练完成：Seed=100，Q4
最佳Val Loss：2.132430，Epoch=8
最佳Val CCC：0.478673，Epoch=13
====================================================================================================
文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q5_PHQ_8Appetite/seed_100/best_loss.pt
视频Best Loss： /workspace/E-DAIC/checkpoints/phq8_video_paperlike/seed_100/question_5/best_loss.pt
文本保存Epoch： 11
视频保存Epoch： 3
文本缺少参数： []
文本多余参数： []
视频缺少参数： []
视频多余参数： []
====================================================================================================
开始训练Text+Video：Seed=100，Q5，PHQ_8Appetite
类别数量： [77, 42, 24, 20]
ImbOLL权重： [1.454951286315918, 1.9700132608413696, 2.6060826778411865, 2.854820728302002]
文本预训练模型： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q5_PHQ_8Appetite/seed_100/best_loss.pt
视频预训练模型： /workspace/E-DAIC/checkpoints/phq8_video_paperlike/seed_100/question_5/best_loss.pt
====================================================================================================
Epoch 01/20 | Train Loss 2.489724 | Val Loss 2.454198 | Val CCC 0.375229 | Val Acc 0.363636 | Val RMSE 1.061731 | 0.79s
Epoch 02/20 | Train Loss 1.859021 | Val Loss 2.353218 | Val CCC 0.381779 | Val Acc 0.400000 | Val RMSE 1.018019 | 0.78s
Epoch 03/20 | Train Loss 1.837671 | Val Loss 2.677061 | Val CCC 0.394372 | Val Acc 0.400000 | Val RMSE 0.990867 | 0.77s
Epoch 04/20 | Train Loss 1.774513 | Val Loss 2.751528 | Val CCC 0.427495 | Val Acc 0.418182 | Val RMSE 1.026911 | 0.76s
Epoch 05/20 | Train Loss 1.833601 | Val Loss 2.271753 | Val CCC 0.416083 | Val Acc 0.418182 | Val RMSE 0.924416 | 0.76s
Epoch 06/20 | Train Loss 1.705981 | Val Loss 2.557810 | Val CCC 0.403918 | Val Acc 0.436364 | Val RMSE 0.972345 | 0.76s
Epoch 07/20 | Train Loss 1.757454 | Val Loss 2.479061 | Val CCC 0.412417 | Val Acc 0.418182 | Val RMSE 0.981650 | 0.79s
Epoch 08/20 | Train Loss 1.611014 | Val Loss 2.686274 | Val CCC 0.436517 | Val Acc 0.454545 | Val RMSE 1.009050 | 0.78s
Epoch 09/20 | Train Loss 1.694387 | Val Loss 2.547736 | Val CCC 0.413835 | Val Acc 0.454545 | Val RMSE 0.981650 | 0.77s
Epoch 10/20 | Train Loss 1.603921 | Val Loss 2.812838 | Val CCC 0.391918 | Val Acc 0.418182 | Val RMSE 1.026911 | 0.76s
Epoch 11/20 | Train Loss 1.596970 | Val Loss 2.150371 | Val CCC 0.454267 | Val Acc 0.472727 | Val RMSE 1.000000 | 0.77s
Epoch 12/20 | Train Loss 1.588579 | Val Loss 3.235477 | Val CCC 0.452824 | Val Acc 0.454545 | Val RMSE 1.061731 | 0.77s
Epoch 13/20 | Train Loss 1.564437 | Val Loss 3.973700 | Val CCC 0.410639 | Val Acc 0.418182 | Val RMSE 1.009050 | 0.77s
Epoch 14/20 | Train Loss 1.613751 | Val Loss 2.377175 | Val CCC 0.438980 | Val Acc 0.454545 | Val RMSE 1.009050 | 0.77s
Epoch 15/20 | Train Loss 1.584713 | Val Loss 2.491174 | Val CCC 0.447545 | Val Acc 0.436364 | Val RMSE 0.990867 | 0.77s
Epoch 16/20 | Train Loss 1.609273 | Val Loss 3.531209 | Val CCC 0.416961 | Val Acc 0.436364 | Val RMSE 1.120065 | 0.77s
Epoch 17/20 | Train Loss 1.479553 | Val Loss 3.387661 | Val CCC 0.497122 | Val Acc 0.490909 | Val RMSE 0.990867 | 0.76s
Epoch 18/20 | Train Loss 1.464134 | Val Loss 4.383570 | Val CCC 0.461975 | Val Acc 0.454545 | Val RMSE 1.061731 | 0.77s
Epoch 19/20 | Train Loss 1.610181 | Val Loss 2.780610 | Val CCC 0.404946 | Val Acc 0.436364 | Val RMSE 0.943880 | 0.77s
Epoch 20/20 | Train Loss 1.658366 | Val Loss 2.716395 | Val CCC 0.454225 | Val Acc 0.454545 | Val RMSE 1.061731 | 0.78s
====================================================================================================
训练完成：Seed=100，Q5
最佳Val Loss：2.150371，Epoch=11
最佳Val CCC：0.497122，Epoch=17
====================================================================================================
文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q6_PHQ_8Failure/seed_100/best_loss.pt
视频Best Loss： /workspace/E-DAIC/checkpoints/phq8_video_paperlike/seed_100/question_6/best_loss.pt
文本保存Epoch： 13
视频保存Epoch： 3
文本缺少参数： []
文本多余参数： []
视频缺少参数： []
视频多余参数： []
====================================================================================================
开始训练Text+Video：Seed=100，Q6，PHQ_8Failure
类别数量： [76, 44, 24, 19]
ImbOLL权重： [1.4644919633865356, 1.9247195720672607, 2.6060826778411865, 2.9289839267730713]
文本预训练模型： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q6_PHQ_8Failure/seed_100/best_loss.pt
视频预训练模型： /workspace/E-DAIC/checkpoints/phq8_video_paperlike/seed_100/question_6/best_loss.pt
====================================================================================================
Epoch 01/20 | Train Loss 2.407248 | Val Loss 2.188915 | Val CCC 0.321785 | Val Acc 0.436364 | Val RMSE 1.070259 | 0.81s
Epoch 02/20 | Train Loss 1.749952 | Val Loss 2.279852 | Val CCC 0.279901 | Val Acc 0.400000 | Val RMSE 1.159937 | 0.84s
Epoch 03/20 | Train Loss 1.629496 | Val Loss 2.340016 | Val CCC 0.359589 | Val Acc 0.454545 | Val RMSE 1.111919 | 0.80s
Epoch 04/20 | Train Loss 1.706256 | Val Loss 2.063133 | Val CCC 0.430225 | Val Acc 0.454545 | Val RMSE 0.962950 | 0.80s
Epoch 05/20 | Train Loss 1.468986 | Val Loss 2.124106 | Val CCC 0.447357 | Val Acc 0.490909 | Val RMSE 0.914529 | 0.81s
Epoch 06/20 | Train Loss 1.430190 | Val Loss 2.178368 | Val CCC 0.357222 | Val Acc 0.454545 | Val RMSE 0.981650 | 0.81s
Epoch 07/20 | Train Loss 1.456283 | Val Loss 2.107669 | Val CCC 0.358569 | Val Acc 0.454545 | Val RMSE 1.035725 | 0.80s
Epoch 08/20 | Train Loss 1.379187 | Val Loss 2.178723 | Val CCC 0.338000 | Val Acc 0.436364 | Val RMSE 0.943880 | 0.79s
Epoch 09/20 | Train Loss 1.396084 | Val Loss 2.241083 | Val CCC 0.321811 | Val Acc 0.418182 | Val RMSE 1.053134 | 0.80s
Epoch 10/20 | Train Loss 1.354922 | Val Loss 2.115434 | Val CCC 0.397295 | Val Acc 0.418182 | Val RMSE 0.924416 | 0.80s
Epoch 11/20 | Train Loss 1.360568 | Val Loss 2.080974 | Val CCC 0.405995 | Val Acc 0.436364 | Val RMSE 0.943880 | 0.80s
Epoch 12/20 | Train Loss 1.309756 | Val Loss 2.105662 | Val CCC 0.405995 | Val Acc 0.436364 | Val RMSE 0.943880 | 0.81s

,Seed,Question_Index,Question_Number,Question_Name,Best_Val_Loss,Best_Loss_Epoch,Best_Val_CCC,Best_CCC_Epoch
0,100,0,1,PHQ_8NoInterest,2.533762,4,0.455722,20
1,100,1,2,PHQ_8Depressed,1.931162,17,0.514706,4
2,100,2,3,PHQ_8Sleep,2.276807,3,0.396825,14
3,100,3,4,PHQ_8Tired,2.132430,8,0.478673,13
4,100,4,5,PHQ_8Appetite,2.150371,11,0.497122,17
5,100,5,6,PHQ_8Failure,2.063133,4,0.447357,5
6,100,6,7,PHQ_8Concentrating,2.094383,17,0.490192,7
7,100,7,8,PHQ_8Moving,2.357591,10,0.306064,5

In [137]:
text_video_seed1234_results, text_video_seed1234_summary_df = train_all_text_video_questions_for_seed(seed=1234)
display(text_video_seed1234_summary_df)

####################################################################################################
开始训练Text+Video全部问题：Seed=1234
####################################################################################################
文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q1_PHQ_8NoInterest/seed_1234/best_loss.pt
视频Best Loss： /workspace/E-DAIC/checkpoints/phq8_video_paperlike/seed_1234/question_1/best_loss.pt
文本保存Epoch： 7
视频保存Epoch： 15
文本缺少参数： []
文本多余参数： []
视频缺少参数： []
视频多余参数： []
====================================================================================================
开始训练Text+Video：Seed=1234，Q1，PHQ_8NoInterest
类别数量： [81, 57, 20, 5]
ImbOLL权重： [1.4185717105865479, 1.6910496950149536, 2.854820728302002, 5.709641456604004]
文本预训练模型： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q1_PHQ_8NoInterest/seed_1234/best_loss.pt
视频预训练模型： /workspace/E-DAIC/checkpoints/phq8_video_paperlike/seed_1234/question_1/best_loss.pt
====================================================================================================
Epoch 01/20 | Train Loss 2.209556 | Val Loss 2.475116 | Val CCC 0.208096 | Val Acc 0.545455 | Val RMSE 0.981650 | 1.11s
Epoch 02/20 | Train Loss 1.597640 | Val Loss 2.690440 | Val CCC 0.352279 | Val Acc 0.563636 | Val RMSE 0.914529 | 0.85s
Epoch 03/20 | Train Loss 1.532114 | Val Loss 2.522180 | Val CCC 0.417463 | Val Acc 0.509091 | Val RMSE 0.863397 | 1.01s
Epoch 04/20 | Train Loss 1.428560 | Val Loss 2.658424 | Val CCC 0.464926 | Val Acc 0.563636 | Val RMSE 0.831209 | 1.02s
Epoch 05/20 | Train Loss 1.431528 | Val Loss 2.755760 | Val CCC 0.388594 | Val Acc 0.563636 | Val RMSE 0.914529 | 0.87s
Epoch 06/20 | Train Loss 1.377349 | Val Loss 3.564424 | Val CCC 0.368954 | Val Acc 0.527273 | Val RMSE 0.962950 | 1.39s
Epoch 07/20 | Train Loss 1.325002 | Val Loss 3.070123 | Val CCC 0.354793 | Val Acc 0.563636 | Val RMSE 0.863397 | 1.00s
Epoch 08/20 | Train Loss 1.562594 | Val Loss 2.654769 | Val CCC 0.488372 | Val Acc 0.581818 | Val RMSE 0.852803 | 0.81s
Epoch 09/20 | Train Loss 1.374585 | Val Loss 2.599955 | Val CCC 0.364337 | Val Acc 0.545455 | Val RMSE 0.873863 | 1.00s
Epoch 10/20 | Train Loss 1.332143 | Val Loss 2.529541 | Val CCC 0.458686 | Val Acc 0.472727 | Val RMSE 0.884205 | 0.98s
Epoch 11/20 | Train Loss 1.326997 | Val Loss 2.595349 | Val CCC 0.392601 | Val Acc 0.527273 | Val RMSE 0.852803 | 0.84s
Epoch 12/20 | Train Loss 1.285129 | Val Loss 2.863308 | Val CCC 0.422134 | Val Acc 0.545455 | Val RMSE 0.904534 | 0.82s
Epoch 13/20 | Train Loss 1.393451 | Val Loss 2.686443 | Val CCC 0.377652 | Val Acc 0.490909 | Val RMSE 0.934199 | 1.01s
Epoch 14/20 | Train Loss 1.158242 | Val Loss 3.366685 | Val CCC 0.474940 | Val Acc 0.581818 | Val RMSE 0.852803 | 0.81s
Epoch 15/20 | Train Loss 1.286062 | Val Loss 2.908023 | Val CCC 0.402036 | Val Acc 0.509091 | Val RMSE 0.924416 | 0.81s
Epoch 16/20 | Train Loss 1.440998 | Val Loss 2.439806 | Val CCC 0.400425 | Val Acc 0.509091 | Val RMSE 0.863397 | 0.79s
Epoch 17/20 | Train Loss 1.163536 | Val Loss 3.027257 | Val CCC 0.474187 | Val Acc 0.527273 | Val RMSE 0.852803 | 0.81s
Epoch 18/20 | Train Loss 1.317030 | Val Loss 2.635152 | Val CCC 0.409924 | Val Acc 0.490909 | Val RMSE 0.934199 | 0.80s
Epoch 19/20 | Train Loss 1.152990 | Val Loss 2.929397 | Val CCC 0.334278 | Val Acc 0.509091 | Val RMSE 0.924416 | 0.80s
Epoch 20/20 | Train Loss 1.123491 | Val Loss 2.868583 | Val CCC 0.414201 | Val Acc 0.545455 | Val RMSE 0.904534 | 0.80s
====================================================================================================
训练完成：Seed=1234，Q1
最佳Val Loss：2.439806，Epoch=16
最佳Val CCC：0.488372，Epoch=8
====================================================================================================
文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q2_PHQ_8Depressed/seed_1234/best_loss.pt
视频Best Loss： /workspace/E-DAIC/checkpoints/phq8_video_paperlike/seed_1234/question_2/best_loss.pt
文本保存Epoch： 12
视频保存Epoch： 2
文本缺少参数： []
文本多余参数： []
视频缺少参数： []
视频多余参数： []
====================================================================================================
开始训练Text+Video：Seed=1234，Q2，PHQ_8Depressed
类别数量： [68, 63, 18, 14]
ImbOLL权重： [1.548243761062622, 1.6085091829299927, 3.009244918823242, 3.412163257598877]
文本预训练模型： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q2_PHQ_8Depressed/seed_1234/best_loss.pt
视频预训练模型： /workspace/E-DAIC/checkpoints/phq8_video_paperlike/seed_1234/question_2/best_loss.pt
====================================================================================================
Epoch 01/20 | Train Loss 2.488579 | Val Loss 2.082069 | Val CCC 0.412565 | Val Acc 0.527273 | Val RMSE 0.962950 | 0.80s
Epoch 02/20 | Train Loss 1.758359 | Val Loss 2.123353 | Val CCC 0.514872 | Val Acc 0.527273 | Val RMSE 0.884205 | 0.82s
Epoch 03/20 | Train Loss 1.548970 | Val Loss 2.070995 | Val CCC 0.325407 | Val Acc 0.436364 | Val RMSE 0.943880 | 0.80s
Epoch 04/20 | Train Loss 1.522073 | Val Loss 1.978245 | Val CCC 0.426938 | Val Acc 0.509091 | Val RMSE 0.863397 | 0.79s
Epoch 05/20 | Train Loss 1.418449 | Val Loss 1.999234 | Val CCC 0.470829 | Val Acc 0.563636 | Val RMSE 0.924416 | 0.80s
Epoch 06/20 | Train Loss 1.335672 | Val Loss 2.504643 | Val CCC 0.502629 | Val Acc 0.581818 | Val RMSE 0.884205 | 0.79s
Epoch 07/20 | Train Loss 1.350037 | Val Loss 2.009911 | Val CCC 0.467532 | Val Acc 0.563636 | Val RMSE 0.863397 | 0.79s
Epoch 08/20 | Train Loss 1.486750 | Val Loss 2.049461 | Val CCC 0.459016 | Val Acc 0.545455 | Val RMSE 0.873863 | 0.80s
Epoch 09/20 | Train Loss 1.481590 | Val Loss 2.058057 | Val CCC 0.422434 | Val Acc 0.509091 | Val RMSE 0.894427 | 0.83s
Epoch 10/20 | Train Loss 1.326093 | Val Loss 2.031918 | Val CCC 0.454065 | Val Acc 0.563636 | Val RMSE 0.924416 | 0.79s
Epoch 11/20 | Train Loss 1.364130 | Val Loss 2.069035 | Val CCC 0.476190 | Val Acc 0.545455 | Val RMSE 0.873863 | 0.79s
Epoch 12/20 | Train Loss 1.361960 | Val Loss 2.412466 | Val CCC 0.538213 | Val Acc 0.600000 | Val RMSE 0.842075 | 0.78s
Epoch 13/20 | Train Loss 1.364112 | Val Loss 2.111353 | Val CCC 0.468314 | Val Acc 0.545455 | Val RMSE 0.904534 | 0.80s
Epoch 14/20 | Train Loss 1.275331 | Val Loss 2.407317 | Val CCC 0.451912 | Val Acc 0.527273 | Val RMSE 0.884205 | 0.78s
Epoch 15/20 | Train Loss 1.337316 | Val Loss 2.189524 | Val CCC 0.415045 | Val Acc 0.472727 | Val RMSE 0.863397 | 0.77s
Epoch 16/20 | Train Loss 1.426616 | Val Loss 2.247556 | Val CCC 0.513462 | Val Acc 0.581818 | Val RMSE 0.914529 | 0.77s
Epoch 17/20 | Train Loss 1.318373 | Val Loss 2.266711 | Val CCC 0.403531 | Val Acc 0.527273 | Val RMSE 0.884205 | 0.77s
Epoch 18/20 | Train Loss 1.414882 | Val Loss 2.111840 | Val CCC 0.382022 | Val Acc 0.454545 | Val RMSE 0.904534 | 0.78s
Epoch 19/20 | Train Loss 1.405908 | Val Loss 2.196136 | Val CCC 0.414894 | Val Acc 0.527273 | Val RMSE 0.852803 | 0.77s
Epoch 20/20 | Train Loss 1.247262 | Val Loss 2.096810 | Val CCC 0.463110 | Val Acc 0.527273 | Val RMSE 0.884205 | 0.77s
====================================================================================================
训练完成：Seed=1234，Q2
最佳Val Loss：1.978245，Epoch=4
最佳Val CCC：0.538213，Epoch=12
====================================================================================================
文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q3_PHQ_8Sleep/seed_1234/best_loss.pt
视频Best Loss： /workspace/E-DAIC/checkpoints/phq8_video_paperlike/seed_1234/question_3/best_loss.pt
文本保存Epoch： 7
视频保存Epoch： 13
文本缺少参数： []
文本多余参数： []
视频缺少参数： []
视频多余参数： []
====================================================================================================
开始训练Text+Video：Seed=1234，Q3，PHQ_8Sleep
类别数量： [69, 40, 27, 27]
ImbOLL权重： [1.5369837284088135, 2.018662929534912, 2.457038164138794, 2.457038164138794]
文本预训练模型： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q3_PHQ_8Sleep/seed_1234/best_loss.pt
视频预训练模型： /workspace/E-DAIC/checkpoints/phq8_video_paperlike/seed_1234/question_3/best_loss.pt
====================================================================================================
Epoch 01/20 | Train Loss 2.613381 | Val Loss 2.302543 | Val CCC 0.271178 | Val Acc 0.363636 | Val RMSE 1.009050 | 0.77s
Epoch 02/20 | Train Loss 2.042350 | Val Loss 2.279936 | Val CCC 0.354081 | Val Acc 0.327273 | Val RMSE 1.206045 | 0.80s
Epoch 03/20 | Train Loss 1.980152 | Val Loss 2.247361 | Val CCC 0.356725 | Val Acc 0.400000 | Val RMSE 1.111919 | 0.81s
Epoch 04/20 | Train Loss 1.871074 | Val Loss 2.226618 | Val CCC 0.351090 | Val Acc 0.436364 | Val RMSE 1.095445 | 0.82s
Epoch 05/20 | Train Loss 1.903022 | Val Loss 2.478884 | Val CCC 0.381710 | Val Acc 0.436364 | Val RMSE 1.272078 | 0.79s
Epoch 06/20 | Train Loss 1.929667 | Val Loss 2.348539 | Val CCC 0.365146 | Val Acc 0.454545 | Val RMSE 1.221028 | 0.78s
Epoch 07/20 | Train Loss 1.903283 | Val Loss 2.384334 | Val CCC 0.466428 | Val Acc 0.400000 | Val RMSE 1.175508 | 0.78s
Epoch 08/20 | Train Loss 1.884345 | Val Loss 2.296527 | Val CCC 0.368867 | Val Acc 0.381818 | Val RMSE 1.120065 | 0.78s
Epoch 09/20 | Train Loss 1.907821 | Val Loss 2.404906 | Val CCC 0.378309 | Val Acc 0.381818 | Val RMSE 1.198484 | 0.78s
Epoch 10/20 | Train Loss 1.730661 | Val Loss 2.341008 | Val CCC 0.381821 | Val Acc 0.436364 | Val RMSE 1.120065 | 0.78s
Epoch 11/20 | Train Loss 1.840666 | Val Loss 2.638393 | Val CCC 0.450828 | Val Acc 0.418182 | Val RMSE 1.152073 | 0.80s
Epoch 12/20 | Train Loss 1.841984 | Val Loss 2.386407 | Val CCC 0.477732 | Val Acc 0.436364 | Val RMSE 1.136182 | 0.80s
Epoch 13/20 | Train Loss 1.753873 | Val Loss 2.364626 | Val CCC 0.357777 | Val Acc 0.381818 | Val RMSE 1.167748 | 0.80s
Epoch 14/20 | Train Loss 1.672663 | Val Loss 2.404217 | Val CCC 0.291417 | Val Acc 0.436364 | Val RMSE 1.136182 | 0.80s
Epoch 15/20 | Train Loss 1.741503 | Val Loss 3.143113 | Val CCC 0.351528 | Val Acc 0.400000 | Val RMSE 0.990867 | 0.80s
Epoch 16/20 | Train Loss 2.110142 | Val Loss 2.467758 | Val CCC 0.351124 | Val Acc 0.418182 | Val RMSE 1.235829 | 0.79s
Epoch 17/20 | Train Loss 1.846914 | Val Loss 2.253272 | Val CCC 0.263094 | Val Acc 0.472727 | Val RMSE 1.183216 | 0.78s
Epoch 18/20 | Train Loss 1.735975 | Val Loss 2.411032 | Val CCC 0.368524 | Val Acc 0.436364 | Val RMSE 1.221028 | 0.78s
Epoch 19/20 | Train Loss 1.699740 | Val Loss 2.347081 | Val CCC 0.317779 | Val Acc 0.381818 | Val RMSE 1.070259 | 0.78s
Epoch 20/20 | Train Loss 1.792178 | Val Loss 2.419638 | Val CCC 0.332335 | Val Acc 0.381818 | Val RMSE 1.183216 | 0.78s
====================================================================================================
训练完成：Seed=1234，Q3
最佳Val Loss：2.226618，Epoch=4
最佳Val CCC：0.477732，Epoch=12
====================================================================================================
文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q4_PHQ_8Tired/seed_1234/best_loss.pt
视频Best Loss： /workspace/E-DAIC/checkpoints/phq8_video_paperlike/seed_1234/question_4/best_loss.pt
文本保存Epoch： 8
视频保存Epoch： 9
文本缺少参数： []
文本多余参数： []
视频缺少参数： []
视频多余参数： []
====================================================================================================
开始训练Text+Video：Seed=1234，Q4，PHQ_8Tired
类别数量： [50, 65, 27, 21]
ImbOLL权重： [1.8055469989776611, 1.5835695266723633, 2.457038164138794, 2.7860195636749268]
文本预训练模型： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q4_PHQ_8Tired/seed_1234/best_loss.pt
视频预训练模型： /workspace/E-DAIC/checkpoints/phq8_video_paperlike/seed_1234/question_4/best_loss.pt
====================================================================================================
Epoch 01/20 | Train Loss 2.567854 | Val Loss 2.283749 | Val CCC 0.360465 | Val Acc 0.345455 | Val RMSE 0.873863 | 0.80s
Epoch 02/20 | Train Loss 2.073069 | Val Loss 2.200739 | Val CCC 0.550302 | Val Acc 0.436364 | Val RMSE 0.914529 | 0.79s
Epoch 03/20 | Train Loss 1.918542 | Val Loss 2.164384 | Val CCC 0.417827 | Val Acc 0.290909 | Val RMSE 1.018019 | 0.81s
Epoch 04/20 | Train Loss 1.943080 | Val Loss 2.139542 | Val CCC 0.523155 | Val Acc 0.363636 | Val RMSE 0.863397 | 0.82s
Epoch 05/20 | Train Loss 1.852300 | Val Loss 2.109944 | Val CCC 0.444195 | Val Acc 0.290909 | Val RMSE 0.904534 | 0.81s
Epoch 06/20 | Train Loss 1.856962 | Val Loss 2.127473 | Val CCC 0.523466 | Val Acc 0.400000 | Val RMSE 0.934199 | 0.81s
Epoch 07/20 | Train Loss 1.883591 | Val Loss 2.211571 | Val CCC 0.417126 | Val Acc 0.363636 | Val RMSE 0.953463 | 0.80s
Epoch 08/20 | Train Loss 1.888054 | Val Loss 2.309772 | Val CCC 0.366801 | Val Acc 0.327273 | Val RMSE 0.884205 | 0.80s
Epoch 09/20 | Train Loss 1.810588 | Val Loss 2.165142 | Val CCC 0.414175 | Val Acc 0.381818 | Val RMSE 0.972345 | 0.84s
Epoch 10/20 | Train Loss 1.765042 | Val Loss 2.170212 | Val CCC 0.455446 | Val Acc 0.327273 | Val RMSE 0.884205 | 0.81s
Epoch 11/20 | Train Loss 1.765725 | Val Loss 2.317721 | Val CCC 0.391443 | Val Acc 0.290909 | Val RMSE 0.904534 | 0.80s
Epoch 12/20 | Train Loss 1.639295 | Val Loss 2.530571 | Val CCC 0.345787 | Val Acc 0.400000 | Val RMSE 1.136182 | 0.80s
Epoch 13/20 | Train Loss 1.754905 | Val Loss 2.273879 | Val CCC 0.433786 | Val Acc 0.309091 | Val RMSE 0.894427 | 0.80s
Epoch 14/20 | Train Loss 1.651432 | Val Loss 2.296334 | Val CCC 0.394697 | Val Acc 0.309091 | Val RMSE 0.894427 | 0.81s
Epoch 15/20 | Train Loss 1.701362 | Val Loss 2.298415 | Val CCC 0.469697 | Val Acc 0.290909 | Val RMSE 0.873863 | 0.82s
Epoch 16/20 | Train Loss 1.566741 | Val Loss 2.362581 | Val CCC 0.405405 | Val Acc 0.309091 | Val RMSE 1.009050 | 0.80s
Epoch 17/20 | Train Loss 1.657065 | Val Loss 2.643009 | Val CCC 0.356436 | Val Acc 0.363636 | Val RMSE 1.087115 | 0.79s
Epoch 18/20 | Train Loss 1.604019 | Val Loss 2.607535 | Val CCC 0.355388 | Val Acc 0.290909 | Val RMSE 1.061731 | 0.80s
Epoch 19/20 | Train Loss 1.587352 | Val Loss 2.724777 | Val CCC 0.242267 | Val Acc 0.254545 | Val RMSE 0.981650 | 0.86s
Epoch 20/20 | Train Loss 1.695952 | Val Loss 2.245368 | Val CCC 0.488555 | Val Acc 0.327273 | Val RMSE 0.972345 | 0.79s
====================================================================================================
训练完成：Seed=1234，Q4
最佳Val Loss：2.109944，Epoch=5
最佳Val CCC：0.550302，Epoch=2
====================================================================================================
文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q5_PHQ_8Appetite/seed_1234/best_loss.pt
视频Best Loss： /workspace/E-DAIC/checkpoints/phq8_video_paperlike/seed_1234/question_5/best_loss.pt
文本保存Epoch： 16
视频保存Epoch： 2
文本缺少参数： []
文本多余参数： []
视频缺少参数： []
视频多余参数： []
====================================================================================================
开始训练Text+Video：Seed=1234，Q5，PHQ_8Appetite
类别数量： [77, 42, 24, 20]
ImbOLL权重： [1.454951286315918, 1.9700132608413696, 2.6060826778411865, 2.854820728302002]
文本预训练模型： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q5_PHQ_8Appetite/seed_1234/best_loss.pt
视频预训练模型： /workspace/E-DAIC/checkpoints/phq8_video_paperlike/seed_1234/question_5/best_loss.pt
====================================================================================================
Epoch 01/20 | Train Loss 2.565529 | Val Loss 2.280398 | Val CCC 0.333456 | Val Acc 0.381818 | Val RMSE 1.095445 | 0.82s
Epoch 02/20 | Train Loss 1.921117 | Val Loss 2.329900 | Val CCC 0.392816 | Val Acc 0.381818 | Val RMSE 1.103713 | 0.79s
Epoch 03/20 | Train Loss 1.719025 | Val Loss 2.548176 | Val CCC 0.356557 | Val Acc 0.363636 | Val RMSE 1.103713 | 0.80s
Epoch 04/20 | Train Loss 1.937415 | Val Loss 2.083535 | Val CCC 0.413333 | Val Acc 0.363636 | Val RMSE 1.009050 | 0.77s
Epoch 05/20 | Train Loss 1.848525 | Val Loss 2.262147 | Val CCC 0.335023 | Val Acc 0.309091 | Val RMSE 1.061731 | 0.79s
Epoch 06/20 | Train Loss 1.714629 | Val Loss 2.515543 | Val CCC 0.452593 | Val Acc 0.400000 | Val RMSE 1.018019 | 0.79s
Epoch 07/20 | Train Loss 1.668566 | Val Loss 2.105708 | Val CCC 0.341171 | Val Acc 0.345455 | Val RMSE 0.990867 | 0.78s
Epoch 08/20 | Train Loss 1.667071 | Val Loss 2.354355 | Val CCC 0.370469 | Val Acc 0.345455 | Val RMSE 1.044466 | 0.78s
Epoch 09/20 | Train Loss 1.748113 | Val Loss 2.285771 | Val CCC 0.415850 | Val Acc 0.381818 | Val RMSE 0.972345 | 0.83s
Epoch 10/20 | Train Loss 1.613087 | Val Loss 2.168553 | Val CCC 0.388646 | Val Acc 0.363636 | Val RMSE 1.009050 | 0.77s
Epoch 11/20 | Train Loss 1.618853 | Val Loss 2.702195 | Val CCC 0.452593 | Val Acc 0.400000 | Val RMSE 1.018019 | 0.78s
Epoch 12/20 | Train Loss 1.797031 | Val Loss 2.033655 | Val CCC 0.514230 | Val Acc 0.454545 | Val RMSE 0.809040 | 0.78s
Epoch 13/20 | Train Loss 1.538147 | Val Loss 2.576539 | Val CCC 0.391659 | Val Acc 0.327273 | Val RMSE 1.053134 | 0.79s
Epoch 14/20 | Train Loss 1.644984 | Val Loss 2.173799 | Val CCC 0.418828 | Val Acc 0.381818 | Val RMSE 1.000000 | 0.79s
Epoch 15/20 | Train Loss 1.557038 | Val Loss 2.106427 | Val CCC 0.468536 | Val Acc 0.418182 | Val RMSE 0.863397 | 0.79s
Epoch 16/20 | Train Loss 1.674980 | Val Loss 2.489912 | Val CCC 0.430642 | Val Acc 0.345455 | Val RMSE 1.044466 | 0.78s
Epoch 17/20 | Train Loss 1.676659 | Val Loss 2.238680 | Val CCC 0.395837 | Val Acc 0.345455 | Val RMSE 1.018019 | 0.86s
Epoch 18/20 | Train Loss 1.515385 | Val Loss 2.559465 | Val CCC 0.492364 | Val Acc 0.381818 | Val RMSE 1.000000 | 0.93s
Epoch 19/20 | Train Loss 1.814868 | Val Loss 2.033050 | Val CCC 0.514473 | Val Acc 0.436364 | Val RMSE 0.884205 | 0.92s
Epoch 20/20 | Train Loss 1.562219 | Val Loss 2.269306 | Val CCC 0.433195 | Val Acc 0.400000 | Val RMSE 1.018019 | 0.93s
====================================================================================================
训练完成：Seed=1234，Q5
最佳Val Loss：2.033050，Epoch=19
最佳Val CCC：0.514473，Epoch=19
====================================================================================================
文本Best Loss： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q6_PHQ_8Failure/seed_1234/best_loss.pt
视频Best Loss： /workspace/E-DAIC/checkpoints/phq8_video_paperlike/seed_1234/question_6/best_loss.pt
文本保存Epoch： 10
视频保存Epoch： 42
文本缺少参数： []
文本多余参数： []
视频缺少参数： []
视频多余参数： []
====================================================================================================
开始训练Text+Video：Seed=1234，Q6，PHQ_8Failure
类别数量： [76, 44, 24, 19]
ImbOLL权重： [1.4644919633865356, 1.9247195720672607, 2.6060826778411865, 2.9289839267730713]
文本预训练模型： /workspace/E-DAIC/checkpoints/phq8_text_paperlike/q6_PHQ_8Failure/seed_1234/best_loss.pt
视频预训练模型： /workspace/E-DAIC/checkpoints/phq8_video_paperlike/seed_1234/question_6/best_loss.pt
====================================================================================================
Epoch 01/20 | Train Loss 2.265363 | Val Loss 1.993349 | Val CCC 0.482527 | Val Acc 0.509091 | Val RMSE 1.009050 | 0.93s
Epoch 02/20 | Train Loss 1.593575 | Val Loss 2.197157 | Val CCC 0.506329 | Val Acc 0.454545 | Val RMSE 0.842075 | 0.95s
Epoch 03/20 | Train Loss 1.573127 | Val Loss 2.122849 | Val CCC 0.476190 | Val Acc 0.472727 | Val RMSE 1.026911 | 0.93s
Epoch 04/20 | Train Loss 1.379086 | Val Loss 2.178402 | Val CCC 0.448898 | Val Acc 0.454545 | Val RMSE 1.087115 | 0.86s
Epoch 05/20 | Train Loss 1.412261 | Val Loss 2.403922 | Val CCC 0.426891 | Val Acc 0.509091 | Val RMSE 1.061731 | 0.85s
Epoch 06/20 | Train Loss 1.394262 | Val Loss 2.221762 | Val CCC 0.426769 | Val Acc 0.490909 | Val RMSE 1.018019 | 0.84s
Epoch 07/20 | Train Loss 1.255382 | Val Loss 2.523493 | Val CCC 0.484013 | Val Acc 0.490909 | Val RMSE 0.943880 | 0.86s
Epoch 08/20 | Train Loss 1.593853 | Val Loss 2.531682 | Val CCC 0.466208 | Val Acc 0.436364 | Val RMSE 1.000000 | 0.88s
Epoch 09/20 | Train Loss 1.314404 | Val Loss 2.311363 | Val CCC 0.435950 | Val Acc 0.490909 | Val RMSE 1.000000 | 0.86s
Epoch 10/20 | Train Loss 1.285008 | Val Loss 2.578478 | Val CCC 0.361597 | Val Acc 0.509091 | Val RMSE 1.035725 | 0.87s
Epoch 11/20 | Train Loss 1.319799 | Val Loss 2.557446 | Val CCC 0.382995 | Val Acc 0.490909 | Val RMSE 1.018019 | 0.90s
Epoch 12/20 | Train Loss 1.423066 | Val Loss 2.266215 | Val CCC 0.444652 | Val Acc 0.400000 | Val RMSE 0.990867 | 0.89s

,Seed,Question_Index,Question_Number,Question_Name,Best_Val_Loss,Best_Loss_Epoch,Best_Val_CCC,Best_CCC_Epoch
0,1234,0,1,PHQ_8NoInterest,2.439806,16,0.488372,8
1,1234,1,2,PHQ_8Depressed,1.978245,4,0.538213,12
2,1234,2,3,PHQ_8Sleep,2.226618,4,0.477732,12
3,1234,3,4,PHQ_8Tired,2.109944,5,0.550302,2
4,1234,4,5,PHQ_8Appetite,2.033050,19,0.514473,19
5,1234,5,6,PHQ_8Failure,1.993349,1,0.506329,2
6,1234,6,7,PHQ_8Concentrating,2.043192,13,0.514056,11
7,1234,7,8,PHQ_8Moving,1.886370,3,0.157549,3

In [138]:
all_text_video_training_results = {}
all_text_video_training_results[42] = text_video_seed42_results
all_text_video_training_results[100] = text_video_seed100_results
all_text_video_training_results[1234] = text_video_seed1234_results

In [139]:
for seed, seed_results in all_text_video_training_results.items():
    print("=" * 70)
    print("Seed：", seed)
    print("问题数量：", len(seed_results))
    print("Best Loss全部存在：", all(result["best_loss_path"].exists() for result in seed_results))
    print("Best CCC全部存在：", all(result["best_ccc_path"].exists() for result in seed_results))
    print("Last全部存在：", all(result["last_path"].exists() for result in seed_results))
    print("History全部存在：", all(result["history_path"].exists() for result in seed_results))

======================================================================
Seed： 42
问题数量： 8
Best Loss全部存在： True
Best CCC全部存在： True
Last全部存在： True
History全部存在： True
======================================================================
Seed： 100
问题数量： 8
Best Loss全部存在： True
Best CCC全部存在： True
Last全部存在： True
History全部存在： True
======================================================================
Seed： 1234
问题数量： 8
Best Loss全部存在： True
Best CCC全部存在： True
Last全部存在： True
History全部存在： True

In [140]:
text_video_seed100_validation_result = evaluate_text_video_seed_on_validation(seed=100)
text_video_seed1234_validation_result = evaluate_text_video_seed_on_validation(seed=1234)

Q1 | Epoch 20 | Val CCC 0.455722
Q2 | Epoch 04 | Val CCC 0.514706
Q3 | Epoch 14 | Val CCC 0.396825
Q4 | Epoch 13 | Val CCC 0.478673
Q5 | Epoch 17 | Val CCC 0.497122
Q6 | Epoch 05 | Val CCC 0.447357
Q7 | Epoch 07 | Val CCC 0.490192
Q8 | Epoch 05 | Val CCC 0.306064
======================================================================
Text+Video Seed 100验证结果
======================================================================
验证参与者数量： 55
总分CCC：0.625042
总分RMSE：4.837355
总分MAE：3.654546
完全相等比例：0.054545
预测总分范围：0～17
真实总分范围：0～20
预测文件： /workspace/E-DAIC/checkpoints/phq8_text_video_paperlike/seed_100_validation_predictions.csv
Q1 | Epoch 08 | Val CCC 0.488372
Q2 | Epoch 12 | Val CCC 0.538213
Q3 | Epoch 12 | Val CCC 0.477732
Q4 | Epoch 02 | Val CCC 0.550302
Q5 | Epoch 19 | Val CCC 0.514473
Q6 | Epoch 02 | Val CCC 0.506329
Q7 | Epoch 11 | Val CCC 0.514056
Q8 | Epoch 03 | Val CCC 0.157549
======================================================================
Text+Video Seed 1234验证结果
======================================================================
验证参与者数量： 55
总分CCC：0.661026
总分RMSE：4.568668
总分MAE：3.236364
完全相等比例：0.181818
预测总分范围：0～20
真实总分范围：0～20
预测文件： /workspace/E-DAIC/checkpoints/phq8_text_video_paperlike/seed_1234_validation_predictions.csv

In [141]:
all_text_video_validation_results = [text_video_seed42_validation_result, text_video_seed100_validation_result, text_video_seed1234_validation_result]
text_video_validation_seed_rows = []
for result in all_text_video_validation_results:
    text_video_validation_seed_rows.append({"Seed": result["seed"], "Sample_Count": result["sample_count"], "CCC": result["ccc"], "RMSE": result["rmse"], "MAE": result["mae"], "Exact_Accuracy": result["exact_accuracy"], "Predicted_Min": int(result["predicted_totals"].min()), "Predicted_Max": int(result["predicted_totals"].max()), "True_Min": int(result["true_totals"].min()), "True_Max": int(result["true_totals"].max())})
text_video_validation_seed_summary_df = pd.DataFrame(text_video_validation_seed_rows)
display(text_video_validation_seed_summary_df)

,Seed,Sample_Count,CCC,RMSE,MAE,Exact_Accuracy,Predicted_Min,Predicted_Max,True_Min,True_Max
0,42,55,0.680283,4.421024,3.218182,0.072727,1,22,0,20
1,100,55,0.625042,4.837355,3.654546,0.054545,0,17,0,20
2,1234,55,0.661026,4.568668,3.236364,0.181818,0,20,0,20

In [142]:
text_video_validation_statistics_rows = []
for metric_name in ["CCC", "RMSE", "MAE", "Exact_Accuracy"]:
    text_video_validation_statistics_rows.append({"Metric": metric_name, "Mean": text_video_validation_seed_summary_df[metric_name].mean(), "Std": text_video_validation_seed_summary_df[metric_name].std(ddof=1)})
text_video_validation_statistics_df = pd.DataFrame(text_video_validation_statistics_rows)
display(text_video_validation_statistics_df)

           Metric      Mean       Std
0             CCC  0.655450  0.028039
1            RMSE  4.609015  0.211078
2             MAE  3.369697  0.246854
3  Exact_Accuracy  0.103030  0.068835

In [143]:
text_video_validation_statistics_rows = []
for metric_name in ["CCC", "RMSE", "MAE", "Exact_Accuracy"]:
    text_video_validation_statistics_rows.append({"Metric": metric_name, "Mean": text_video_validation_seed_summary_df[metric_name].mean(), "Std": text_video_validation_seed_summary_df[metric_name].std(ddof=1)})
text_video_validation_statistics_df = pd.DataFrame(text_video_validation_statistics_rows)
display(text_video_validation_statistics_df)

           Metric      Mean       Std
0             CCC  0.655450  0.028039
1            RMSE  4.609015  0.211078
2             MAE  3.369697  0.246854
3  Exact_Accuracy  0.103030  0.068835

In [144]:
text_video_validation_results_path = TEXT_VIDEO_CHECKPOINT_ROOT / "three_seed_validation_results.csv"
text_video_validation_summary_path = TEXT_VIDEO_CHECKPOINT_ROOT / "three_seed_validation_summary.csv"
text_video_validation_seed_summary_df.to_csv(text_video_validation_results_path, index=False)
text_video_validation_statistics_df.to_csv(text_video_validation_summary_path, index=False)
print("逐Seed验证结果：", text_video_validation_results_path)
print("三Seed验证汇总：", text_video_validation_summary_path)
print("逐Seed文件存在：", text_video_validation_results_path.exists())
print("汇总文件存在：", text_video_validation_summary_path.exists())

逐Seed验证结果： /workspace/E-DAIC/checkpoints/phq8_text_video_paperlike/three_seed_validation_results.csv
三Seed验证汇总： /workspace/E-DAIC/checkpoints/phq8_text_video_paperlike/three_seed_validation_summary.csv
逐Seed文件存在： True
汇总文件存在： True

In [145]:
class TextVideoPHQ8TestDataset(Dataset):
    def __init__(self, metadata_df):
        super().__init__()
        self.metadata_df = metadata_df.reset_index(drop=True).copy()
        if "PHQ_Score" not in self.metadata_df.columns:
            raise KeyError(f"测试集缺少PHQ_Score字段：{self.metadata_df.columns.tolist()}")
        self.participant_ids = self.metadata_df["Participant_ID"].astype(int).tolist()
        self.true_totals = torch.tensor(self.metadata_df["PHQ_Score"].to_numpy(), dtype=torch.long)
        text_feature_list = []
        text_mask_list = []
        video_feature_list = []
        video_mask_list = []
        for index, participant_id in enumerate(self.participant_ids):
            text_features, text_mask, video_features, video_mask = load_text_video_cache(participant_id)
            text_feature_list.append(text_features)
            text_mask_list.append(text_mask)
            video_feature_list.append(video_features)
            video_mask_list.append(video_mask)
            if (index + 1) % 20 == 0 or index + 1 == len(self.participant_ids):
                print(f"test Text+Video加载进度：{index + 1}/{len(self.participant_ids)}")
        self.text_features = torch.stack(text_feature_list, dim=0)
        self.text_masks = torch.stack(text_mask_list, dim=0)
        self.video_features = torch.stack(video_feature_list, dim=0)
        self.video_masks = torch.stack(video_mask_list, dim=0)
        if self.text_features.shape != (len(self.participant_ids), MAX_TURNS, TEXT_FEATURE_DIM):
            raise RuntimeError(f"测试文本形状错误：{self.text_features.shape}")
        if self.video_features.shape != (len(self.participant_ids), MAX_TURNS, VIDEO_FEATURE_DIM):
            raise RuntimeError(f"测试视频形状错误：{self.video_features.shape}")
        if not torch.isfinite(self.text_features).all():
            raise RuntimeError("测试文本包含NaN或Inf")
        if not torch.isfinite(self.video_features).all():
            raise RuntimeError("测试视频包含NaN或Inf")

    def __len__(self):
        return len(self.participant_ids)

    def __getitem__(self, index):
        return self.text_features[index], self.text_masks[index], self.video_features[index], self.video_masks[index], self.true_totals[index], self.participant_ids[index]

In [146]:
text_video_test_dataset = TextVideoPHQ8TestDataset(video_test_metadata_df)
text_video_test_loader = DataLoader(text_video_test_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=0, drop_last=False)

test Text+Video加载进度：20/56
test Text+Video加载进度：40/56
test Text+Video加载进度：56/56

In [147]:
test_text_features, test_text_masks, test_video_features, test_video_masks, test_true_totals, test_participant_ids = next(iter(text_video_test_loader))
print("测试参与者数量：", len(text_video_test_dataset))
print("测试批次数：", len(text_video_test_loader))
print("测试文本特征：", test_text_features.shape)
print("测试文本Mask：", test_text_masks.shape)
print("测试视频特征：", test_video_features.shape)
print("测试视频Mask：", test_video_masks.shape)
print("测试真实总分：", test_true_totals.shape)
print("测试参与者：", test_participant_ids)
print("文本全部有限：", bool(torch.isfinite(test_text_features).all()))
print("视频全部有限：", bool(torch.isfinite(test_video_features).all()))
print("真实总分范围：", int(text_video_test_dataset.true_totals.min()), "～", int(text_video_test_dataset.true_totals.max()))

测试参与者数量： 56
测试批次数： 6
测试文本特征： torch.Size([10, 120, 768])
测试文本Mask： torch.Size([10, 120])
测试视频特征： torch.Size([10, 120, 2048])
测试视频Mask： torch.Size([10, 120])
测试真实总分： torch.Size([10])
测试参与者： tensor([600, 602, 604, 605, 606, 607, 609, 615, 618, 619])
文本全部有限： True
视频全部有限： True
真实总分范围： 0 ～ 22

In [148]:
def evaluate_text_video_seed_on_test(seed):
    question_prediction_list = []
    selected_checkpoint_rows = []
    for question_index in range(len(PHQ8_QUESTION_COLUMNS)):
        checkpoint_path = TEXT_VIDEO_CHECKPOINT_ROOT / f"seed_{seed}" / f"question_{question_index + 1}" / "best_ccc.pt"
        if not checkpoint_path.exists():
            raise FileNotFoundError(f"Checkpoint不存在：{checkpoint_path}")
        checkpoint = torch.load(checkpoint_path, map_location="cpu", weights_only=False)
        if checkpoint["seed"] != seed or checkpoint["question_index"] != question_index or checkpoint["checkpoint_type"] != "best_ccc":
            raise RuntimeError(f"Checkpoint元数据错误：{checkpoint_path}")
        model = TextVideoQuestMF(PretrainedTextEncoder(), PretrainedVideoEncoder()).to(device)
        load_result = model.load_state_dict(checkpoint["model_state_dict"], strict=True)
        if load_result.missing_keys or load_result.unexpected_keys:
            raise RuntimeError(f"Checkpoint参数不一致：{checkpoint_path}")
        model.eval()
        batch_prediction_list = []
        with torch.no_grad():
            for text_features, text_masks, video_features, video_masks, true_totals, participant_ids in text_video_test_loader:
                logits = model(text_features.to(device), text_masks.to(device), video_features.to(device), video_masks.to(device))
                batch_prediction_list.append(logits.argmax(dim=1).cpu())
        question_predictions = torch.cat(batch_prediction_list)
        if len(question_predictions) != len(text_video_test_dataset):
            raise RuntimeError(f"Q{question_index + 1}预测数量错误")
        question_prediction_list.append(question_predictions)
        selected_checkpoint_rows.append({"Seed": seed, "Question_Index": question_index, "Question_Number": question_index + 1, "Question_Name": PHQ8_QUESTION_COLUMNS[question_index], "Checkpoint_Path": str(checkpoint_path), "Checkpoint_Epoch": checkpoint["epoch"], "Validation_CCC": checkpoint["val_metrics"]["ccc"], "Video_Variant": checkpoint["video_variant"]})
        print(f"Seed {seed} | Q{question_index + 1} | Epoch {checkpoint['epoch']:02d} | Val CCC {checkpoint['val_metrics']['ccc']:.6f}")
        del model
        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
    question_predictions = torch.stack(question_prediction_list, dim=1)
    predicted_totals = question_predictions.sum(dim=1)
    true_totals = text_video_test_dataset.true_totals.clone()
    total_ccc = calculate_ccc(predicted_totals, true_totals)
    total_rmse = float(torch.sqrt(torch.mean((predicted_totals.float() - true_totals.float()) ** 2)).item())
    total_mae = float(torch.mean(torch.abs(predicted_totals.float() - true_totals.float())).item())
    exact_accuracy = float((predicted_totals == true_totals).float().mean().item())
    prediction_df = pd.DataFrame({"Participant_ID": text_video_test_dataset.participant_ids})
    for question_index in range(len(PHQ8_QUESTION_COLUMNS)):
        prediction_df[f"Q{question_index + 1}_Predicted"] = question_predictions[:, question_index].numpy()
    prediction_df["Predicted_Total"] = predicted_totals.numpy()
    prediction_df["True_Total"] = true_totals.numpy()
    prediction_path = TEXT_VIDEO_CHECKPOINT_ROOT / f"seed_{seed}_test_predictions_56.csv"
    selected_checkpoint_path = TEXT_VIDEO_CHECKPOINT_ROOT / f"seed_{seed}_test_selected_checkpoints.csv"
    prediction_df.to_csv(prediction_path, index=False)
    pd.DataFrame(selected_checkpoint_rows).to_csv(selected_checkpoint_path, index=False)
    print("=" * 70)
    print(f"Text+Video Seed {seed}独立测试结果")
    print("=" * 70)
    print("测试参与者数量：", len(prediction_df))
    print(f"CCC：{total_ccc:.6f}")
    print(f"RMSE：{total_rmse:.6f}")
    print(f"MAE：{total_mae:.6f}")
    print(f"完全相等比例：{exact_accuracy:.6f}")
    print(f"预测总分范围：{int(predicted_totals.min())}～{int(predicted_totals.max())}")
    print(f"真实总分范围：{int(true_totals.min())}～{int(true_totals.max())}")
    print("预测文件：", prediction_path)
    return {"seed": seed, "sample_count": len(prediction_df), "ccc": total_ccc, "rmse": total_rmse, "mae": total_mae, "exact_accuracy": exact_accuracy, "predicted_totals": predicted_totals, "true_totals": true_totals, "prediction_path": prediction_path, "selected_checkpoint_path": selected_checkpoint_path}

In [149]:
text_video_seed42_test_result = evaluate_text_video_seed_on_test(seed=42)
text_video_seed100_test_result = evaluate_text_video_seed_on_test(seed=100)
text_video_seed1234_test_result = evaluate_text_video_seed_on_test(seed=1234)

Seed 42 | Q1 | Epoch 06 | Val CCC 0.430305
Seed 42 | Q2 | Epoch 09 | Val CCC 0.560924
Seed 42 | Q3 | Epoch 13 | Val CCC 0.495027
Seed 42 | Q4 | Epoch 09 | Val CCC 0.393745
Seed 42 | Q5 | Epoch 07 | Val CCC 0.521569
Seed 42 | Q6 | Epoch 15 | Val CCC 0.505618
Seed 42 | Q7 | Epoch 10 | Val CCC 0.561753
Seed 42 | Q8 | Epoch 19 | Val CCC 0.345725
======================================================================
Text+Video Seed 42独立测试结果
======================================================================
测试参与者数量： 56
CCC：0.586931
RMSE：5.896427
MAE：4.446429
完全相等比例：0.089286
预测总分范围：1～22
真实总分范围：0～22
预测文件： /workspace/E-DAIC/checkpoints/phq8_text_video_paperlike/seed_42_test_predictions_56.csv
Seed 100 | Q1 | Epoch 20 | Val CCC 0.455722
Seed 100 | Q2 | Epoch 04 | Val CCC 0.514706
Seed 100 | Q3 | Epoch 14 | Val CCC 0.396825
Seed 100 | Q4 | Epoch 13 | Val CCC 0.478673
Seed 100 | Q5 | Epoch 17 | Val CCC 0.497122
Seed 100 | Q6 | Epoch 05 | Val CCC 0.447357
Seed 100 | Q7 | Epoch 07 | Val CCC 0.490192
Seed 100 | Q8 | Epoch 05 | Val CCC 0.306064
======================================================================
Text+Video Seed 100独立测试结果
======================================================================
测试参与者数量： 56
CCC：0.606763
RMSE：5.791003
MAE：4.464286
完全相等比例：0.125000
预测总分范围：0～20
真实总分范围：0～22
预测文件： /workspace/E-DAIC/checkpoints/phq8_text_video_paperlike/seed_100_test_predictions_56.csv
Seed 1234 | Q1 | Epoch 08 | Val CCC 0.488372
Seed 1234 | Q2 | Epoch 12 | Val CCC 0.538213
Seed 1234 | Q3 | Epoch 12 | Val CCC 0.477732
Seed 1234 | Q4 | Epoch 02 | Val CCC 0.550302
Seed 1234 | Q5 | Epoch 19 | Val CCC 0.514473
Seed 1234 | Q6 | Epoch 02 | Val CCC 0.506329
Seed 1234 | Q7 | Epoch 11 | Val CCC 0.514056
Seed 1234 | Q8 | Epoch 03 | Val CCC 0.157549
======================================================================
Text+Video Seed 1234独立测试结果
======================================================================
测试参与者数量： 56
CCC：0.633930
RMSE：5.390137
MAE：4.017857
完全相等比例：0.107143
预测总分范围：0～20
真实总分范围：0～22
预测文件： /workspace/E-DAIC/checkpoints/phq8_text_video_paperlike/seed_1234_test_predictions_56.csv

In [150]:
all_text_video_test_results = [text_video_seed42_test_result, text_video_seed100_test_result, text_video_seed1234_test_result]
text_video_test_seed_rows = []
for result in all_text_video_test_results:
    text_video_test_seed_rows.append({"Seed": result["seed"], "Sample_Count": result["sample_count"], "CCC": result["ccc"], "RMSE": result["rmse"], "MAE": result["mae"], "Exact_Accuracy": result["exact_accuracy"], "Predicted_Min": int(result["predicted_totals"].min()), "Predicted_Max": int(result["predicted_totals"].max()), "True_Min": int(result["true_totals"].min()), "True_Max": int(result["true_totals"].max())})
text_video_test_seed_summary_df = pd.DataFrame(text_video_test_seed_rows)
display(text_video_test_seed_summary_df)

,Seed,Sample_Count,CCC,RMSE,MAE,Exact_Accuracy,Predicted_Min,Predicted_Max,True_Min,True_Max
0,42,56,0.586931,5.896427,4.446429,0.089286,1,22,0,22
1,100,56,0.606763,5.791003,4.464286,0.125000,0,20,0,22
2,1234,56,0.633930,5.390137,4.017857,0.107143,0,20,0,22

In [151]:
text_video_three_seed_rows = []
for metric_name in ["CCC", "RMSE", "MAE", "Exact_Accuracy"]:
    text_video_three_seed_rows.append({"Metric": metric_name, "Mean": text_video_test_seed_summary_df[metric_name].mean(), "Std": text_video_test_seed_summary_df[metric_name].std(ddof=1)})
text_video_three_seed_summary_df = pd.DataFrame(text_video_three_seed_rows)
display(text_video_three_seed_summary_df)

           Metric      Mean       Std
0             CCC  0.609208  0.023594
1            RMSE  5.692522  0.267126
2             MAE  4.309524  0.252749
3  Exact_Accuracy  0.107143  0.017857

In [152]:
text_video_test_results_56_path = TEXT_VIDEO_CHECKPOINT_ROOT / "three_seed_test_results_56.csv"
text_video_test_summary_56_path = TEXT_VIDEO_CHECKPOINT_ROOT / "three_seed_test_summary_56.csv"
text_video_test_seed_summary_df.to_csv(text_video_test_results_56_path, index=False)
text_video_three_seed_summary_df.to_csv(text_video_test_summary_56_path, index=False)
print("56人逐Seed结果：", text_video_test_results_56_path)
print("56人汇总结果：", text_video_test_summary_56_path)

56人逐Seed结果： /workspace/E-DAIC/checkpoints/phq8_text_video_paperlike/three_seed_test_results_56.csv
56人汇总结果： /workspace/E-DAIC/checkpoints/phq8_text_video_paperlike/three_seed_test_summary_56.csv

In [154]:
text_video_test_keep_mask_55 = torch.tensor([participant_id != 637 for participant_id in text_video_test_dataset.participant_ids], dtype=torch.bool)
print("55人协议实际人数：", int(text_video_test_keep_mask_55.sum()))

55人协议实际人数： 55

In [155]:
text_video_test_55_rows = []
for result in all_text_video_test_results:
    predicted_totals_55 = result["predicted_totals"][text_video_test_keep_mask_55]
    true_totals_55 = result["true_totals"][text_video_test_keep_mask_55]
    ccc_55 = calculate_ccc(predicted_totals_55, true_totals_55)
    rmse_55 = float(torch.sqrt(torch.mean((predicted_totals_55.float() - true_totals_55.float()) ** 2)).item())
    mae_55 = float(torch.mean(torch.abs(predicted_totals_55.float() - true_totals_55.float())).item())
    exact_accuracy_55 = float((predicted_totals_55 == true_totals_55).float().mean().item())
    text_video_test_55_rows.append({"Seed": result["seed"], "Sample_Count": len(predicted_totals_55), "CCC": ccc_55, "RMSE": rmse_55, "MAE": mae_55, "Exact_Accuracy": exact_accuracy_55})
text_video_test_55_summary_df = pd.DataFrame(text_video_test_55_rows)
display(text_video_test_55_summary_df)

   Seed  Sample_Count       CCC      RMSE       MAE  Exact_Accuracy
0    42            55  0.574119  5.943675  4.490909        0.090909
1   100            55  0.594663  5.841855  4.527273        0.127273
2  1234            55  0.618996  5.437245  4.072727        0.109091

In [156]:
text_video_three_seed_55_rows = []
for metric_name in ["CCC", "RMSE", "MAE", "Exact_Accuracy"]:
    text_video_three_seed_55_rows.append({"Metric": metric_name, "Mean": text_video_test_55_summary_df[metric_name].mean(), "Std": text_video_test_55_summary_df[metric_name].std(ddof=1)})
text_video_three_seed_55_summary_df = pd.DataFrame(text_video_three_seed_55_rows)
display(text_video_three_seed_55_summary_df)

           Metric      Mean       Std
0             CCC  0.595926  0.022465
1            RMSE  5.740925  0.267877
2             MAE  4.363636  0.252590
3  Exact_Accuracy  0.109091  0.018182

In [157]:
text_video_test_results_55_path = TEXT_VIDEO_CHECKPOINT_ROOT / "three_seed_test_results_candidate55.csv"
text_video_test_summary_55_path = TEXT_VIDEO_CHECKPOINT_ROOT / "three_seed_test_summary_candidate55.csv"
text_video_test_55_summary_df.to_csv(text_video_test_results_55_path, index=False)
text_video_three_seed_55_summary_df.to_csv(text_video_test_summary_55_path, index=False)
print("55人逐Seed结果：", text_video_test_results_55_path)
print("55人汇总结果：", text_video_test_summary_55_path)

55人逐Seed结果： /workspace/E-DAIC/checkpoints/phq8_text_video_paperlike/three_seed_test_results_candidate55.csv
55人汇总结果： /workspace/E-DAIC/checkpoints/phq8_text_video_paperlike/three_seed_test_summary_candidate55.csv

### no-mask版

In [158]:
TEXT_VIDEO_NOMASK_ROOT = Path("/workspace/E-DAIC/checkpoints/phq8_text_video_nomask_ablation")
TEXT_VIDEO_NOMASK_ROOT.mkdir(parents=True, exist_ok=True)
print("No-Mask目录：", TEXT_VIDEO_NOMASK_ROOT)

No-Mask目录： /workspace/E-DAIC/checkpoints/phq8_text_video_nomask_ablation

In [159]:
class PretrainedTextEncoderNoMask(nn.Module):
    def __init__(self):
        super().__init__()
        self.lstm = nn.LSTM(input_size=TEXT_FEATURE_DIM, hidden_size=50, batch_first=True, bidirectional=True)
        self.attention = nn.MultiheadAttention(embed_dim=ENCODER_OUTPUT_DIM, num_heads=ATTENTION_HEADS, dropout=0.5, batch_first=True)

    def forward(self, text_features, text_padding_mask):
        lstm_output, _ = self.lstm(text_features)
        text_encoding, _ = self.attention(lstm_output, lstm_output, lstm_output, key_padding_mask=text_padding_mask, need_weights=False)
        return text_encoding

In [165]:
class PretrainedVideoEncoderNoMask(nn.Module):
    def __init__(self):
        super().__init__()
        self.lstm = nn.LSTM(input_size=VIDEO_FEATURE_DIM, hidden_size=50, batch_first=True, bidirectional=True)
        self.attention1 = nn.MultiheadAttention(embed_dim=ENCODER_OUTPUT_DIM, num_heads=ATTENTION_HEADS, dropout=0.2, batch_first=True)
        self.attention2 = nn.MultiheadAttention(embed_dim=ENCODER_OUTPUT_DIM, num_heads=ATTENTION_HEADS, dropout=0.2, batch_first=True)

    def forward(self, video_features, video_padding_mask):
        lstm_output, _ = self.lstm(video_features)
        attention1_output, _ = self.attention1(lstm_output, lstm_output, lstm_output, key_padding_mask=video_padding_mask, need_weights=False)
        video_encoding, _ = self.attention2(attention1_output, attention1_output, attention1_output, key_padding_mask=video_padding_mask, need_weights=False)
        return video_encoding

In [166]:
def load_pretrained_text_video_encoders_nomask(question_index, seed):
    text_checkpoint_path, video_checkpoint_path = get_text_video_best_loss_paths(question_index, seed)
    text_checkpoint = torch.load(text_checkpoint_path, map_location="cpu", weights_only=False)
    video_checkpoint = torch.load(video_checkpoint_path, map_location="cpu", weights_only=False)
    text_encoder = PretrainedTextEncoderNoMask()
    video_encoder = PretrainedVideoEncoderNoMask()
    text_encoder_state = extract_state_dict_by_prefixes(text_checkpoint["model_state_dict"], prefixes=("lstm.", "attention."))
    video_encoder_state = extract_state_dict_by_prefixes(video_checkpoint["model_state_dict"], prefixes=("lstm.", "attention1.", "attention2."))
    text_encoder.load_state_dict(text_encoder_state, strict=True)
    video_encoder.load_state_dict(video_encoder_state, strict=True)
    return text_encoder, video_encoder, text_checkpoint_path, video_checkpoint_path

In [167]:
class TextVideoQuestMFNoMask(nn.Module):
    def __init__(self, text_encoder, video_encoder):
        super().__init__()
        self.text_encoder = text_encoder
        self.video_encoder = video_encoder
        self.video_to_text_cross_attention = nn.MultiheadAttention(embed_dim=ENCODER_OUTPUT_DIM, num_heads=ATTENTION_HEADS, dropout=FUSION_DROPOUT, batch_first=True)
        self.text_to_video_cross_attention = nn.MultiheadAttention(embed_dim=ENCODER_OUTPUT_DIM, num_heads=ATTENTION_HEADS, dropout=FUSION_DROPOUT, batch_first=True)
        self.text_self_attention = nn.MultiheadAttention(embed_dim=ENCODER_OUTPUT_DIM, num_heads=ATTENTION_HEADS, dropout=FUSION_DROPOUT, batch_first=True)
        self.video_self_attention = nn.MultiheadAttention(embed_dim=ENCODER_OUTPUT_DIM, num_heads=ATTENTION_HEADS, dropout=FUSION_DROPOUT, batch_first=True)
        self.mlp = nn.Sequential(nn.Flatten(), nn.Dropout(FUSION_MLP_FIRST_DROPOUT), nn.Linear(MAX_TURNS * ENCODER_OUTPUT_DIM * 2, 256), nn.ReLU(), nn.Dropout(FUSION_MLP_LAST_DROPOUT), nn.Linear(256, NUM_CLASSES))
        for parameter in self.text_encoder.parameters():
            parameter.requires_grad = False
        self.text_encoder.eval()

    def train(self, mode=True):
        super().train(mode)
        self.text_encoder.eval()
        return self

    def forward(self, text_features, text_padding_mask, video_features, video_padding_mask, return_intermediates=False):
        text_encoding = self.text_encoder(text_features, text_padding_mask)
        video_encoding = self.video_encoder(video_features, video_padding_mask)
        video_to_text, _ = self.video_to_text_cross_attention(text_encoding, video_encoding, video_encoding, key_padding_mask=video_padding_mask, need_weights=False)
        text_to_video, _ = self.text_to_video_cross_attention(video_encoding, text_encoding, text_encoding, key_padding_mask=text_padding_mask, need_weights=False)
        text_fused_encoding, _ = self.text_self_attention(video_to_text, video_to_text, video_to_text, key_padding_mask=text_padding_mask, need_weights=False)
        video_fused_encoding, _ = self.video_self_attention(text_to_video, text_to_video, text_to_video, key_padding_mask=video_padding_mask, need_weights=False)
        fused_encoding = torch.cat((text_fused_encoding, video_fused_encoding), dim=2)
        logits = self.mlp(fused_encoding)
        if return_intermediates:
            return logits, {"text_encoding": text_encoding, "video_encoding": video_encoding, "video_to_text": video_to_text, "text_to_video": text_to_video, "text_fused_encoding": text_fused_encoding, "video_fused_encoding": video_fused_encoding, "fused_encoding": fused_encoding}
        return logits

In [168]:
set_seed(42)
nomask_text_encoder, nomask_video_encoder, nomask_text_checkpoint_path, nomask_video_checkpoint_path = load_pretrained_text_video_encoders_nomask(question_index=0, seed=42)
nomask_diagnostic_model = TextVideoQuestMFNoMask(nomask_text_encoder, nomask_video_encoder).to(device)
nomask_diagnostic_model.eval()
with torch.no_grad():
    nomask_logits, nomask_intermediates = nomask_diagnostic_model(batch_text_features.to(device), batch_text_masks.to(device), batch_video_features.to(device), batch_video_masks.to(device), return_intermediates=True)
print("No-Mask拼接形状：", nomask_intermediates["fused_encoding"].shape)
print("No-Mask Logits形状：", nomask_logits.shape)
print("No-Mask Logits全部有限：", bool(torch.isfinite(nomask_logits).all()))
print("No-Mask可训练参数：", f"{sum(parameter.numel() for parameter in nomask_diagnostic_model.parameters() if parameter.requires_grad):,}")

No-Mask拼接形状： torch.Size([10, 120, 200])
No-Mask Logits形状： torch.Size([10, 4])
No-Mask Logits全部有限： True
No-Mask可训练参数： 7,227,684

In [169]:
def save_text_video_nomask_checkpoint(path, checkpoint_type, epoch, question_index, seed, model, optimizer, train_metrics, val_metrics, class_counts, class_weights, best_val_loss, best_val_ccc, best_loss_epoch, best_ccc_epoch, text_checkpoint_path, video_checkpoint_path):
    save_text_video_checkpoint(path, checkpoint_type, epoch, question_index, seed, model, optimizer, train_metrics, val_metrics, class_counts, class_weights, best_val_loss, best_val_ccc, best_loss_epoch, best_ccc_epoch, text_checkpoint_path, video_checkpoint_path)
    checkpoint = torch.load(path, map_location="cpu", weights_only=False)
    checkpoint["video_variant"] = "no_padding_output_zero_ablation"
    checkpoint["ablation_variable"] = "masked_fill_removed"
    torch.save(checkpoint, path)

In [170]:
def train_text_video_nomask_question(seed, question_index):
    set_seed(seed)
    train_loader, val_loader = create_text_video_dataloaders(seed)
    text_encoder, video_encoder, text_checkpoint_path, video_checkpoint_path = load_pretrained_text_video_encoders_nomask(question_index, seed)
    model = TextVideoQuestMFNoMask(text_encoder, video_encoder).to(device)
    train_labels = text_video_train_dataset.labels[:, question_index]
    class_counts = torch.bincount(train_labels, minlength=NUM_CLASSES)
    class_weights = torch.pow(len(train_labels) / class_counts.float(), BETA)
    criterion = ImbOLLLoss(class_weights, alpha=ALPHA).to(device)
    optimizer = torch.optim.AdamW((parameter for parameter in model.parameters() if parameter.requires_grad), lr=FUSION_LEARNING_RATE, eps=FUSION_ADAM_EPSILON, weight_decay=FUSION_WEIGHT_DECAY)
    checkpoint_dir = TEXT_VIDEO_NOMASK_ROOT / f"seed_{seed}" / f"question_{question_index + 1}"
    checkpoint_dir.mkdir(parents=True, exist_ok=True)
    best_loss_path = checkpoint_dir / "best_loss.pt"
    best_ccc_path = checkpoint_dir / "best_ccc.pt"
    last_path = checkpoint_dir / "last.pt"
    history_path = checkpoint_dir / "history.csv"
    best_val_loss = float("inf")
    best_val_ccc = float("-inf")
    best_loss_epoch = -1
    best_ccc_epoch = -1
    history_rows = []
    print("=" * 100)
    print(f"开始No-Mask消融：Seed={seed}，Q{question_index + 1}")
    print("=" * 100)
    for epoch in range(1, FUSION_NUM_EPOCHS + 1):
        epoch_start_time = time.perf_counter()
        train_metrics = run_text_video_epoch(model, train_loader, question_index, criterion, optimizer)
        val_metrics = run_text_video_epoch(model, val_loader, question_index, criterion)
        elapsed_seconds = time.perf_counter() - epoch_start_time
        improved_loss = val_metrics["loss"] < best_val_loss
        improved_ccc = val_metrics["ccc"] > best_val_ccc
        if improved_loss:
            best_val_loss = val_metrics["loss"]
            best_loss_epoch = epoch
        if improved_ccc:
            best_val_ccc = val_metrics["ccc"]
            best_ccc_epoch = epoch
        if improved_loss:
            save_text_video_nomask_checkpoint(best_loss_path, "best_loss", epoch, question_index, seed, model, optimizer, train_metrics, val_metrics, class_counts, class_weights, best_val_loss, best_val_ccc, best_loss_epoch, best_ccc_epoch, text_checkpoint_path, video_checkpoint_path)
        if improved_ccc:
            save_text_video_nomask_checkpoint(best_ccc_path, "best_ccc", epoch, question_index, seed, model, optimizer, train_metrics, val_metrics, class_counts, class_weights, best_val_loss, best_val_ccc, best_loss_epoch, best_ccc_epoch, text_checkpoint_path, video_checkpoint_path)
        history_rows.append({"Epoch": epoch, "Train_Loss": train_metrics["loss"], "Train_CCC": train_metrics["ccc"], "Val_Loss": val_metrics["loss"], "Val_CCC": val_metrics["ccc"], "Val_RMSE": val_metrics["rmse"], "Val_MAE": val_metrics["mae"], "Elapsed_Seconds": elapsed_seconds})
        print(f"Epoch {epoch:02d}/{FUSION_NUM_EPOCHS} | Train Loss {train_metrics['loss']:.6f} | Val Loss {val_metrics['loss']:.6f} | Val CCC {val_metrics['ccc']:.6f} | {elapsed_seconds:.2f}s")
    save_text_video_nomask_checkpoint(last_path, "last", FUSION_NUM_EPOCHS, question_index, seed, model, optimizer, train_metrics, val_metrics, class_counts, class_weights, best_val_loss, best_val_ccc, best_loss_epoch, best_ccc_epoch, text_checkpoint_path, video_checkpoint_path)
    pd.DataFrame(history_rows).to_csv(history_path, index=False)
    print(f"完成：Seed={seed}，Q{question_index + 1}，Best CCC={best_val_ccc:.6f}，Epoch={best_ccc_epoch}")
    return {"seed": seed, "question_index": question_index, "best_val_loss": best_val_loss, "best_val_ccc": best_val_ccc, "best_loss_epoch": best_loss_epoch, "best_ccc_epoch": best_ccc_epoch, "best_loss_path": best_loss_path, "best_ccc_path": best_ccc_path, "last_path": last_path, "history_path": history_path}

In [171]:
all_text_video_nomask_results = {}
for seed in SEEDS:
    seed_results = []
    for question_index in range(len(PHQ8_QUESTION_COLUMNS)):
        result = train_text_video_nomask_question(seed, question_index)
        seed_results.append(result)
        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
    all_text_video_nomask_results[seed] = seed_results

====================================================================================================
开始No-Mask消融：Seed=42，Q1
====================================================================================================
Epoch 01/20 | Train Loss 2.113703 | Val Loss 2.694212 | Val CCC 0.310641 | 4.01s
Epoch 02/20 | Train Loss 1.281714 | Val Loss 3.753850 | Val CCC 0.337017 | 0.91s
Epoch 03/20 | Train Loss 1.396936 | Val Loss 2.496702 | Val CCC 0.353632 | 1.18s
Epoch 04/20 | Train Loss 1.226295 | Val Loss 2.841679 | Val CCC 0.251309 | 0.88s
Epoch 05/20 | Train Loss 1.133127 | Val Loss 3.314361 | Val CCC 0.309392 | 1.03s
Epoch 06/20 | Train Loss 1.194140 | Val Loss 3.038854 | Val CCC 0.446889 | 1.03s
Epoch 07/20 | Train Loss 1.253988 | Val Loss 2.539497 | Val CCC 0.491329 | 0.93s
Epoch 08/20 | Train Loss 1.150188 | Val Loss 3.028973 | Val CCC 0.270101 | 0.98s
Epoch 09/20 | Train Loss 1.063609 | Val Loss 2.562483 | Val CCC 0.488300 | 1.07s
Epoch 10/20 | Train Loss 1.122283 | Val Loss 2.941964 | Val CCC 0.363753 | 1.04s
Epoch 11/20 | Train Loss 1.124791 | Val Loss 3.899661 | Val CCC 0.263703 | 0.88s
Epoch 12/20 | Train Loss 0.993394 | Val Loss 2.710430 | Val CCC 0.488300 | 1.23s
Epoch 13/20 | Train Loss 1.060041 | Val Loss 2.907125 | Val CCC 0.461903 | 1.07s
Epoch 14/20 | Train Loss 1.027437 | Val Loss 2.749564 | Val CCC 0.439919 | 1.27s
Epoch 15/20 | Train Loss 1.065897 | Val Loss 2.868843 | Val CCC 0.416738 | 0.90s
Epoch 16/20 | Train Loss 0.987793 | Val Loss 3.319852 | Val CCC 0.267838 | 1.03s
Epoch 17/20 | Train Loss 1.053472 | Val Loss 2.814201 | Val CCC 0.507003 | 0.92s
Epoch 18/20 | Train Loss 1.012274 | Val Loss 2.826726 | Val CCC 0.274725 | 1.00s
Epoch 19/20 | Train Loss 1.187256 | Val Loss 2.618645 | Val CCC 0.429165 | 1.05s
Epoch 20/20 | Train Loss 0.939886 | Val Loss 2.824840 | Val CCC 0.300089 | 0.99s
完成：Seed=42，Q1，Best CCC=0.507003，Epoch=17
====================================================================================================
开始No-Mask消融：Seed=42，Q2
====================================================================================================
Epoch 01/20 | Train Loss 2.216264 | Val Loss 2.198190 | Val CCC 0.427602 | 0.86s
Epoch 02/20 | Train Loss 1.609090 | Val Loss 2.233778 | Val CCC 0.488848 | 1.34s
Epoch 03/20 | Train Loss 1.714634 | Val Loss 1.977306 | Val CCC 0.487047 | 0.94s
Epoch 04/20 | Train Loss 1.636082 | Val Loss 2.012921 | Val CCC 0.451247 | 1.18s
Epoch 05/20 | Train Loss 1.574311 | Val Loss 1.983269 | Val CCC 0.514532 | 0.92s
Epoch 06/20 | Train Loss 1.619640 | Val Loss 2.002850 | Val CCC 0.510539 | 1.02s
Epoch 07/20 | Train Loss 1.541960 | Val Loss 2.011439 | Val CCC 0.493421 | 0.96s
Epoch 08/20 | Train Loss 1.453419 | Val Loss 2.040056 | Val CCC 0.528764 | 0.86s
Epoch 09/20 | Train Loss 1.502105 | Val Loss 2.002106 | Val CCC 0.560000 | 1.06s
Epoch 10/20 | Train Loss 1.569221 | Val Loss 1.999605 | Val CCC 0.414734 | 0.89s
Epoch 11/20 | Train Loss 1.486875 | Val Loss 2.233122 | Val CCC 0.524763 | 1.50s
Epoch 12/20 | Train Loss 1.409356 | Val Loss 1.998612 | Val CCC 0.482063 | 0.85s
Epoch 13/20 | Train Loss 1.425864 | Val Loss 1.989987 | Val CCC 0.511376 | 0.94s
Epoch 14/20 | Train Loss 1.409519 | Val Loss 2.056539 | Val CCC 0.467742 | 0.93s
Epoch 15/20 | Train Loss 1.537488 | Val Loss 2.399613 | Val CCC 0.448549 | 0.83s
Epoch 16/20 | Train Loss 1.676303 | Val Loss 2.460117 | Val CCC 0.531693 | 1.03s
Epoch 17/20 | Train Loss 1.433139 | Val Loss 2.194658 | Val CCC 0.442522 | 0.82s
Epoch 18/20 | Train Loss 1.474229 | Val Loss 2.071897 | Val CCC 0.531148 | 0.88s
Epoch 19/20 | Train Loss 1.374884 | Val Loss 2.406372 | Val CCC 0.376210 | 0.92s
Epoch 20/20 | Train Loss 1.470073 | Val Loss 2.184885 | Val CCC 0.488848 | 0.90s
完成：Seed=42，Q2，Best CCC=0.560000，Epoch=9
====================================================================================================
开始No-Mask消融：Seed=42，Q3
====================================================================================================
Epoch 01/20 | Train Loss 2.413790 | Val Loss 2.515133 | Val CCC 0.399462 | 0.82s
Epoch 02/20 | Train Loss 1.884336 | Val Loss 2.268917 | Val CCC 0.359401 | 0.94s
Epoch 03/20 | Train Loss 1.776196 | Val Loss 3.091159 | Val CCC 0.420744 | 0.91s
Epoch 04/20 | Train Loss 1.696850 | Val Loss 2.401526 | Val CCC 0.451428 | 0.94s
Epoch 05/20 | Train Loss 1.684921 | Val Loss 2.866333 | Val CCC 0.424040 | 0.86s
Epoch 06/20 | Train Loss 1.710205 | Val Loss 2.356393 | Val CCC 0.407089 | 0.92s
Epoch 07/20 | Train Loss 1.705934 | Val Loss 2.214685 | Val CCC 0.386332 | 0.80s
Epoch 08/20 | Train Loss 1.691615 | Val Loss 2.401742 | Val CCC 0.486281 | 0.88s
Epoch 09/20 | Train Loss 1.636866 | Val Loss 2.823053 | Val CCC 0.478933 | 0.84s
Epoch 10/20 | Train Loss 1.714372 | Val Loss 2.411351 | Val CCC 0.430769 | 0.87s
Epoch 11/20 | Train Loss 1.616603 | Val Loss 2.299851 | Val CCC 0.417492 | 0.80s
Epoch 12/20 | Train Loss 1.674954 | Val Loss 2.292993 | Val CCC 0.376686 | 0.79s
Epoch 13/20 | Train Loss 1.542265 | Val Loss 2.697168 | Val CCC 0.481540 | 0.78s
Epoch 14/20 | Train Loss 1.530362 | Val Loss 2.438959 | Val CCC 0.389711 | 0.78s
Epoch 15/20 | Train Loss 1.453357 | Val Loss 2.766445 | Val CCC 0.230990 | 0.79s
Epoch 16/20 | Train Loss 1.491699 | Val Loss 2.357205 | Val CCC 0.444099 | 0.82s
Epoch 17/20 | Train Loss 1.433272 | Val Loss 2.669497 | Val CCC 0.426230 | 0.83s
Epoch 18/20 | Train Loss 1.465437 | Val Loss 2.476845 | Val CCC 0.445709 | 0.78s
Epoch 19/20 | Train Loss 1.449602 | Val Loss 2.430171 | Val CCC 0.291944 | 0.76s
Epoch 20/20 | Train Loss 1.403398 | Val Loss 3.077229 | Val CCC 0.479697 | 0.76s
完成：Seed=42，Q3，Best CCC=0.486281，Epoch=8
====================================================================================================
开始No-Mask消融：Seed=42，Q4
====================================================================================================
Epoch 01/20 | Train Loss 2.474274 | Val Loss 2.364870 | Val CCC 0.203423 | 0.79s
Epoch 02/20 | Train Loss 1.913875 | Val Loss 2.390320 | Val CCC 0.364113 | 0.77s
Epoch 03/20 | Train Loss 1.741599 | Val Loss 2.300400 | Val CCC 0.386098 | 0.77s
Epoch 04/20 | Train Loss 1.807323 | Val Loss 2.220974 | Val CCC 0.386098 | 0.78s
Epoch 05/20 | Train Loss 1.634366 | Val Loss 2.368927 | Val CCC 0.302566 | 0.79s
Epoch 06/20 | Train Loss 1.825997 | Val Loss 2.244689 | Val CCC 0.344560 | 0.82s
Epoch 07/20 | Train Loss 1.800964 | Val Loss 2.258065 | Val CCC 0.369111 | 0.86s
Epoch 08/20 | Train Loss 1.699721 | Val Loss 2.208552 | Val CCC 0.325843 | 0.84s
Epoch 09/20 | Train Loss 1.747272 | Val Loss 2.361330 | Val CCC 0.386098 | 0.78s
Epoch 10/20 | Train Loss 1.701501 | Val Loss 2.273286 | Val CCC 0.334764 | 0.78s
Epoch 11/20 | Train Loss 1.528179 | Val Loss 2.310831 | Val CCC 0.392713 | 0.78s
Epoch 12/20 | Train Loss 1.676543 | Val Loss 2.254397 | Val CCC 0.242267 | 0.83s
Epoch 13/20 | Train Loss 1.527020 | Val Loss 2.240882 | Val CCC 0.359893 | 0.82s
Epoch 14/20 | Train Loss 1.628672 | Val Loss 2.721914 | Val CCC 0.256962 | 0.83s
Epoch 15/20 | Train Loss 1.481033 | Val Loss 2.346400 | Val CCC 0.333254 | 0.84s
Epoch 16/20 | Train Loss 1.439591 | Val Loss 2.587052 | Val CCC 0.339210 | 0.92s
Epoch 17/20 | Train Loss 1.448301 | Val Loss 2.368787 | Val CCC 0.414504 | 0.91s
Epoch 18/20 | Train Loss 1.378010 | Val Loss 2.398875 | Val CCC 0.375458 | 0.81s
Epoch 19/20 | Train Loss 1.307679 | Val Loss 2.649201 | Val CCC 0.355401 | 0.78s
Epoch 20/20 | Train Loss 1.232933 | Val Loss 2.691842 | Val CCC 0.377432 | 0.78s
完成：Seed=42，Q4，Best CCC=0.414504，Epoch=17
====================================================================================================
开始No-Mask消融：Seed=42，Q5
====================================================================================================
Epoch 01/20 | Train Loss 2.486075 | Val Loss 2.203120 | Val CCC 0.293535 | 0.80s
Epoch 02/20 | Train Loss 1.768082 | Val Loss 2.539750 | Val CCC 0.383264 | 0.82s
Epoch 03/20 | Train Loss 1.760928 | Val Loss 2.198134 | Val CCC 0.493038 | 0.80s
Epoch 04/20 | Train Loss 1.726095 | Val Loss 2.181817 | Val CCC 0.400093 | 0.83s
Epoch 05/20 | Train Loss 1.611513 | Val Loss 2.273976 | Val CCC 0.483330 | 0.87s
Epoch 06/20 | Train Loss 1.598828 | Val Loss 2.176971 | Val CCC 0.517218 | 0.78s
Epoch 07/20 | Train Loss 1.609750 | Val Loss 2.489215 | Val CCC 0.497364 | 0.78s
Epoch 08/20 | Train Loss 1.512030 | Val Loss 3.566153 | Val CCC 0.415233 | 0.77s
Epoch 09/20 | Train Loss 1.473307 | Val Loss 2.592099 | Val CCC 0.446594 | 0.78s
Epoch 10/20 | Train Loss 1.597094 | Val Loss 2.815463 | Val CCC 0.409543 | 0.77s
Epoch 11/20 | Train Loss 1.415515 | Val Loss 3.261315 | Val CCC 0.363057 | 0.81s
Epoch 12/20 | Train Loss 1.531636 | Val Loss 2.599676 | Val CCC 0.492180 | 0.79s
Epoch 13/20 | Train Loss 1.423228 | Val Loss 2.943473 | Val CCC 0.461482 | 0.76s
Epoch 14/20 | Train Loss 1.477808 | Val Loss 3.259279 | Val CCC 0.492072 | 0.76s
Epoch 15/20 | Train Loss 1.413967 | Val Loss 2.529842 | Val CCC 0.427332 | 0.75s
Epoch 16/20 | Train Loss 1.470594 | Val Loss 2.529261 | Val CCC 0.507915 | 0.76s
Epoch 17/20 | Train Loss 1.484475 | Val Loss 3.258936 | Val CCC 0.368838 | 0.76s
Epoch 18/20 | Train Loss 1.357169 | Val Loss 3.173812 | Val CCC 0.294197 | 0.75s
Epoch 19/20 | Train Loss 1.461429 | Val Loss 3.219741 | Val CCC 0.440868 | 0.78s
Epoch 20/20 | Train Loss 1.355072 | Val Loss 3.255787 | Val CCC 0.457734 | 0.79s
完成：Seed=42，Q5，Best CCC=0.517218，Epoch=6
====================================================================================================
开始No-Mask消融：Seed=42，Q6
====================================================================================================
Epoch 01/20 | Train Loss 2.236783 | Val Loss 2.007602 | Val CCC 0.438988 | 0.80s
Epoch 02/20 | Train Loss 1.730698 | Val Loss 1.975019 | Val CCC 0.508578 | 0.80s
Epoch 03/20 | Train Loss 1.717687 | Val Loss 2.046097 | Val CCC 0.412882 | 0.77s
Epoch 04/20 | Train Loss 1.676550 | Val Loss 1.968130 | Val CCC 0.486764 | 0.77s
Epoch 05/20 | Train Loss 1.625636 | Val Loss 2.016476 | Val CCC 0.391358 | 0.78s
Epoch 06/20 | Train Loss 1.560359 | Val Loss 1.984022 | Val CCC 0.513761 | 0.89s
Epoch 07/20 | Train Loss 1.514811 | Val Loss 1.972953 | Val CCC 0.429950 | 0.93s
Epoch 08/20 | Train Loss 1.436326 | Val Loss 2.085233 | Val CCC 0.489263 | 0.93s
Epoch 09/20 | Train Loss 1.633427 | Val Loss 2.332832 | Val CCC 0.410440 | 0.79s
Epoch 10/20 | Train Loss 1.544647 | Val Loss 2.075416 | Val CCC 0.473471 | 0.77s
Epoch 11/20 | Train Loss 1.496118 | Val Loss 2.045886 | Val CCC 0.406873 | 0.77s
Epoch 12/20 | Train Loss 1.466893 | Val Loss 2.147550 | Val CCC 0.393939 | 0.78s
Epoch 13/20 | Train Loss 1.544963 | Val Loss 2.126682 | Val CCC 0.415082 | 0.77s
Epoch 14/20 | Train Loss 1.522973 | Val Loss 2.082704 | Val CCC 0.297753 | 0.78s
Epoch 15/20 | Train Loss 1.456641 | Val Loss 2.344129 | Val CCC 0.438011 | 0.81s
Epoch 16/20 | Train Loss 1.563222 | Val Loss 2.200097 | Val CCC 0.382716 | 0.77s
Epoch 17/20 | Train Loss 1.357395 | Val Loss 2.009734 | Val CCC 0.479700 | 0.76s
Epoch 18/20 | Train Loss 1.337553 | Val Loss 2.187011 | Val CCC 0.384477 | 0.77s
Epoch 19/20 | Train Loss 1.337081 | Val Loss 2.581665 | Val CCC 0.301796 | 0.77s
Epoch 20/20 | Train Loss 1.354734 | Val Loss 2.297300 | Val CCC 0.469904 | 0.76s
完成：Seed=42，Q6，Best CCC=0.513761，Epoch=6
====================================================================================================
开始No-Mask消融：Seed=42，Q7
====================================================================================================
Epoch 01/20 | Train Loss 2.368865 | Val Loss 2.080050 | Val CCC 0.439062 | 0.79s
Epoch 02/20 | Train Loss 1.457077 | Val Loss 2.707356 | Val CCC 0.439784 | 0.77s
Epoch 03/20 | Train Loss 1.690868 | Val Loss 2.111168 | Val CCC 0.531762 | 0.78s
Epoch 04/20 | Train Loss 1.557043 | Val Loss 1.988131 | Val CCC 0.447876 | 0.77s
Epoch 05/20 | Train Loss 1.465248 | Val Loss 2.010854 | Val CCC 0.447817 | 0.77s
Epoch 06/20 | Train Loss 1.441870 | Val Loss 2.102544 | Val CCC 0.471910 | 0.78s
Epoch 07/20 | Train Loss 1.306890 | Val Loss 2.184230 | Val CCC 0.458543 | 0.76s
Epoch 08/20 | Train Loss 1.357673 | Val Loss 2.172052 | Val CCC 0.553218 | 0.77s
Epoch 09/20 | Train Loss 1.404958 | Val Loss 2.129815 | Val CCC 0.514596 | 0.78s
Epoch 10/20 | Train Loss 1.409106 | Val Loss 2.035518 | Val CCC 0.558587 | 0.77s
Epoch 11/20 | Train Loss 1.404494 | Val Loss 2.199544 | Val CCC 0.475964 | 0.78s
Epoch 12/20 | Train Loss 1.274731 | Val Loss 2.001201 | Val CCC 0.478673 | 0.78s
Epoch 13/20 | Train Loss 1.325587 | Val Loss 2.088647 | Val CCC 0.558587 | 0.78s
Epoch 14/20 | Train Loss 1.275291 | Val Loss 2.450351 | Val CCC 0.448230 | 0.76s
Epoch 15/20 | Train Loss 1.271041 | Val Loss 2.008546 | Val CCC 0.476677 | 0.76s
Epoch 16/20 | Train Loss 1.196502 | Val Loss 2.628827 | Val CCC 0.436370 | 0.77s
Epoch 17/20 | Train Loss 1.339600 | Val Loss 2.398264 | Val CCC 0.534140 | 0.76s
Epoch 18/20 | Train Loss 1.566855 | Val Loss 2.693388 | Val CCC 0.458939 | 0.76s
Epoch 19/20 | Train Loss 1.392910 | Val Loss 2.046287 | Val CCC 0.502098 | 0.81s
Epoch 20/20 | Train Loss 1.298376 | Val Loss 2.535213 | Val CCC 0.490652 | 0.77s
完成：Seed=42，Q7，Best CCC=0.558587，Epoch=10
====================================================================================================
开始No-Mask消融：Seed=42，Q8
====================================================================================================
Epoch 01/20 | Train Loss 2.937596 | Val Loss 2.012799 | Val CCC 0.223790 | 0.79s
Epoch 02/20 | Train Loss 1.276674 | Val Loss 3.426754 | Val CCC 0.306794 | 0.77s
Epoch 03/20 | Train Loss 1.407949 | Val Loss 2.234841 | Val CCC 0.240838 | 0.77s
Epoch 04/20 | Train Loss 1.321958 | Val Loss 2.454560 | Val CCC 0.283175 | 0.78s
Epoch 05/20 | Train Loss 1.237447 | Val Loss 2.541689 | Val CCC 0.214559 | 0.78s
Epoch 06/20 | Train Loss 1.503707 | Val Loss 2.089130 | Val CCC 0.263941 | 0.77s
Epoch 07/20 | Train Loss 1.243797 | Val Loss 2.540438 | Val CCC 0.163145 | 0.77s
Epoch 08/20 | Train Loss 1.230292 | Val Loss 2.438540 | Val CCC 0.144599 | 0.76s
Epoch 09/20 | Train Loss 1.251787 | Val Loss 2.178127 | Val CCC 0.221571 | 0.82s
Epoch 10/20 | Train Loss 1.453875 | Val Loss 2.571315 | Val CCC 0.302162 | 0.77s
Epoch 11/20 | Train Loss 1.214544 | Val Loss 2.719202 | Val CCC 0.264565 | 0.76s
Epoch 12/20 | Train Loss 1.291589 | Val Loss 2.027161 | Val CCC 0.228532 | 0.76s
Epoch 13/20 | Train Loss 1.328412 | Val Loss 2.298061 | Val CCC 0.266667 | 0.77s
Epoch 14/20 | Train Loss 1.134638 | Val Loss 2.336326 | Val CCC 0.256128 | 0.82s
Epoch 15/20 | Train Loss 1.199897 | Val Loss 2.861584 | Val CCC 0.163145 | 0.76s
Epoch 16/20 | Train Loss 1.206271 | Val Loss 2.694227 | Val CCC 0.200855 | 0.76s
Epoch 17/20 | Train Loss 1.528162 | Val Loss 2.237055 | Val CCC 0.298048 | 0.77s
Epoch 18/20 | Train Loss 1.217856 | Val Loss 2.614513 | Val CCC 0.201302 | 0.77s
Epoch 19/20 | Train Loss 1.275296 | Val Loss 1.973772 | Val CCC 0.299363 | 0.77s
Epoch 20/20 | Train Loss 1.210265 | Val Loss 3.403101 | Val CCC 0.286401 | 0.80s
完成：Seed=42，Q8，Best CCC=0.306794，Epoch=2
====================================================================================================
开始No-Mask消融：Seed=100，Q1
====================================================================================================
Epoch 01/20 | Train Loss 2.092366 | Val Loss 3.078937 | Val CCC 0.376091 | 0.82s
Epoch 02/20 | Train Loss 1.589692 | Val Loss 2.997641 | Val CCC 0.335716 | 0.78s
Epoch 03/20 | Train Loss 1.458885 | Val Loss 3.217742 | Val CCC 0.345079 | 0.77s
Epoch 04/20 | Train Loss 1.641249 | Val Loss 2.455050 | Val CCC 0.414459 | 0.77s
Epoch 05/20 | Train Loss 1.485700 | Val Loss 2.627498 | Val CCC 0.293136 | 0.78s
Epoch 06/20 | Train Loss 1.437529 | Val Loss 3.237472 | Val CCC 0.240838 | 0.80s
Epoch 07/20 | Train Loss 1.380820 | Val Loss 2.873618 | Val CCC 0.296000 | 0.77s
Epoch 08/20 | Train Loss 1.392089 | Val Loss 3.207558 | Val CCC 0.363682 | 0.76s
Epoch 09/20 | Train Loss 1.488125 | Val Loss 2.842256 | Val CCC 0.430052 | 0.76s
Epoch 10/20 | Train Loss 1.286222 | Val Loss 3.426070 | Val CCC 0.356234 | 0.77s
Epoch 11/20 | Train Loss 1.334011 | Val Loss 2.706893 | Val CCC 0.323216 | 0.76s
Epoch 12/20 | Train Loss 1.425657 | Val Loss 2.754988 | Val CCC 0.381391 | 0.76s
Epoch 13/20 | Train Loss 1.267412 | Val Loss 2.950148 | Val CCC 0.280841 | 0.78s
Epoch 14/20 | Train Loss 1.310757 | Val Loss 2.732772 | Val CCC 0.410458 | 0.76s
Epoch 15/20 | Train Loss 1.293523 | Val Loss 3.233144 | Val CCC 0.354557 | 0.79s
Epoch 16/20 | Train Loss 1.207289 | Val Loss 2.800769 | Val CCC 0.371029 | 0.76s
Epoch 17/20 | Train Loss 1.241453 | Val Loss 3.006720 | Val CCC 0.392811 | 0.77s
Epoch 18/20 | Train Loss 1.200339 | Val Loss 3.705416 | Val CCC 0.385965 | 0.77s
Epoch 19/20 | Train Loss 1.366413 | Val Loss 3.504131 | Val CCC 0.173709 | 0.78s
Epoch 20/20 | Train Loss 1.252298 | Val Loss 3.948808 | Val CCC 0.310641 | 0.78s
完成：Seed=100，Q1，Best CCC=0.430052，Epoch=9
====================================================================================================
开始No-Mask消融：Seed=100，Q2
====================================================================================================
Epoch 01/20 | Train Loss 2.274487 | Val Loss 2.117811 | Val CCC 0.461224 | 0.78s
Epoch 02/20 | Train Loss 1.829294 | Val Loss 1.999647 | Val CCC 0.428135 | 0.77s
Epoch 03/20 | Train Loss 1.643115 | Val Loss 1.984276 | Val CCC 0.439560 | 0.77s
Epoch 04/20 | Train Loss 1.665580 | Val Loss 2.009734 | Val CCC 0.495833 | 0.78s
Epoch 05/20 | Train Loss 1.730448 | Val Loss 1.939528 | Val CCC 0.519540 | 0.82s
Epoch 06/20 | Train Loss 1.645875 | Val Loss 1.943281 | Val CCC 0.455696 | 0.82s
Epoch 07/20 | Train Loss 1.509922 | Val Loss 1.913646 | Val CCC 0.510832 | 0.81s
Epoch 08/20 | Train Loss 1.632515 | Val Loss 1.903698 | Val CCC 0.423634 | 0.83s
Epoch 09/20 | Train Loss 1.707604 | Val Loss 2.041724 | Val CCC 0.479109 | 0.81s
Epoch 10/20 | Train Loss 1.602603 | Val Loss 1.940675 | Val CCC 0.490395 | 0.80s
Epoch 11/20 | Train Loss 1.546309 | Val Loss 1.905364 | Val CCC 0.527149 | 0.83s
Epoch 12/20 | Train Loss 1.546827 | Val Loss 1.981856 | Val CCC 0.474012 | 0.82s
Epoch 13/20 | Train Loss 1.581012 | Val Loss 1.954078 | Val CCC 0.414566 | 0.93s
Epoch 14/20 | Train Loss 1.761500 | Val Loss 1.939551 | Val CCC 0.500000 | 0.87s
Epoch 15/20 | Train Loss 1.647439 | Val Loss 2.035541 | Val CCC 0.436181 | 0.81s
Epoch 16/20 | Train Loss 1.581529 | Val Loss 2.042024 | Val CCC 0.547945 | 0.80s
Epoch 17/20 | Train Loss 1.562655 | Val Loss 1.894119 | Val CCC 0.467942 | 0.82s
Epoch 18/20 | Train Loss 1.588198 | Val Loss 1.904992 | Val CCC 0.528389 | 0.83s
Epoch 19/20 | Train Loss 1.602543 | Val Loss 2.005051 | Val CCC 0.541667 | 0.87s
Epoch 20/20 | Train Loss 1.586528 | Val Loss 1.949749 | Val CCC 0.465278 | 0.83s
完成：Seed=100，Q2，Best CCC=0.547945，Epoch=16
====================================================================================================
开始No-Mask消融：Seed=100，Q3
====================================================================================================
Epoch 01/20 | Train Loss 2.259773 | Val Loss 2.629845 | Val CCC 0.368469 | 0.82s
Epoch 02/20 | Train Loss 1.805216 | Val Loss 2.298142 | Val CCC 0.309372 | 0.95s
Epoch 03/20 | Train Loss 1.770058 | Val Loss 2.267339 | Val CCC 0.415094 | 1.14s
Epoch 04/20 | Train Loss 1.624834 | Val Loss 2.847495 | Val CCC 0.314181 | 0.90s
Epoch 05/20 | Train Loss 1.709108 | Val Loss 2.298341 | Val CCC 0.417760 | 0.82s
Epoch 06/20 | Train Loss 1.685471 | Val Loss 2.346449 | Val CCC 0.387097 | 0.81s
Epoch 07/20 | Train Loss 1.523056 | Val Loss 2.378525 | Val CCC 0.359373 | 0.82s
Epoch 08/20 | Train Loss 1.718187 | Val Loss 2.534011 | Val CCC 0.325836 | 0.83s
Epoch 09/20 | Train Loss 1.759264 | Val Loss 2.618378 | Val CCC 0.326843 | 0.95s
Epoch 10/20 | Train Loss 1.665230 | Val Loss 2.360247 | Val CCC 0.389883 | 0.95s
Epoch 11/20 | Train Loss 1.634227 | Val Loss 2.399105 | Val CCC 0.331783 | 0.94s

In [172]:
for seed, seed_results in all_text_video_nomask_results.items():
    print("=" * 70)
    print("Seed：", seed)
    print("问题数量：", len(seed_results))
    print("Best Loss全部存在：", all(result["best_loss_path"].exists() for result in seed_results))
    print("Best CCC全部存在：", all(result["best_ccc_path"].exists() for result in seed_results))
    print("Last全部存在：", all(result["last_path"].exists() for result in seed_results))

======================================================================
Seed： 42
问题数量： 8
Best Loss全部存在： True
Best CCC全部存在： True
Last全部存在： True
======================================================================
Seed： 100
问题数量： 8
Best Loss全部存在： True
Best CCC全部存在： True
Last全部存在： True
======================================================================
Seed： 1234
问题数量： 8
Best Loss全部存在： True
Best CCC全部存在： True
Last全部存在： True

In [173]:
def evaluate_text_video_nomask_seed_on_validation(seed):
    val_loader = DataLoader(text_video_val_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=0, drop_last=False)
    question_prediction_list = []
    for question_index in range(len(PHQ8_QUESTION_COLUMNS)):
        checkpoint_path = TEXT_VIDEO_NOMASK_ROOT / f"seed_{seed}" / f"question_{question_index + 1}" / "best_ccc.pt"
        if not checkpoint_path.exists():
            raise FileNotFoundError(f"No-Mask Checkpoint不存在：{checkpoint_path}")
        checkpoint = torch.load(checkpoint_path, map_location="cpu", weights_only=False)
        if checkpoint["seed"] != seed or checkpoint["question_index"] != question_index or checkpoint["checkpoint_type"] != "best_ccc":
            raise RuntimeError(f"Checkpoint元数据错误：{checkpoint_path}")
        model = TextVideoQuestMFNoMask(PretrainedTextEncoderNoMask(), PretrainedVideoEncoderNoMask()).to(device)
        load_result = model.load_state_dict(checkpoint["model_state_dict"], strict=True)
        if load_result.missing_keys or load_result.unexpected_keys:
            raise RuntimeError(f"Checkpoint参数不一致：{checkpoint_path}")
        model.eval()
        batch_prediction_list = []
        with torch.no_grad():
            for text_features, text_masks, video_features, video_masks, all_labels in val_loader:
                logits = model(text_features.to(device), text_masks.to(device), video_features.to(device), video_masks.to(device))
                batch_prediction_list.append(logits.argmax(dim=1).cpu())
        question_predictions = torch.cat(batch_prediction_list)
        question_prediction_list.append(question_predictions)
        print(f"Seed {seed} | Q{question_index + 1} | Epoch {checkpoint['epoch']:02d} | Val CCC {checkpoint['val_metrics']['ccc']:.6f}")
        del model
        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
    question_predictions = torch.stack(question_prediction_list, dim=1)
    question_targets = text_video_val_dataset.labels.clone()
    predicted_totals = question_predictions.sum(dim=1)
    true_totals = question_targets.sum(dim=1)
    total_ccc = calculate_ccc(predicted_totals, true_totals)
    total_rmse = float(torch.sqrt(torch.mean((predicted_totals.float() - true_totals.float()) ** 2)).item())
    total_mae = float(torch.mean(torch.abs(predicted_totals.float() - true_totals.float())).item())
    exact_accuracy = float((predicted_totals == true_totals).float().mean().item())
    print("=" * 70)
    print(f"No-Mask Seed {seed}验证结果")
    print(f"CCC：{total_ccc:.6f}")
    print(f"RMSE：{total_rmse:.6f}")
    print(f"MAE：{total_mae:.6f}")
    print(f"完全相等比例：{exact_accuracy:.6f}")
    return {"seed": seed, "sample_count": len(true_totals), "ccc": total_ccc, "rmse": total_rmse, "mae": total_mae, "exact_accuracy": exact_accuracy, "predicted_totals": predicted_totals, "true_totals": true_totals}

In [174]:
text_video_nomask_seed42_validation_result = evaluate_text_video_nomask_seed_on_validation(seed=42)
text_video_nomask_seed100_validation_result = evaluate_text_video_nomask_seed_on_validation(seed=100)
text_video_nomask_seed1234_validation_result = evaluate_text_video_nomask_seed_on_validation(seed=1234)

Seed 42 | Q1 | Epoch 17 | Val CCC 0.507003
Seed 42 | Q2 | Epoch 09 | Val CCC 0.560000
Seed 42 | Q3 | Epoch 08 | Val CCC 0.486281
Seed 42 | Q4 | Epoch 17 | Val CCC 0.414504
Seed 42 | Q5 | Epoch 06 | Val CCC 0.517218
Seed 42 | Q6 | Epoch 06 | Val CCC 0.513761
Seed 42 | Q7 | Epoch 10 | Val CCC 0.558587
Seed 42 | Q8 | Epoch 02 | Val CCC 0.306794
======================================================================
No-Mask Seed 42验证结果
CCC：0.685568
RMSE：4.538723
MAE：3.400000
完全相等比例：0.109091
Seed 100 | Q1 | Epoch 09 | Val CCC 0.430052
Seed 100 | Q2 | Epoch 16 | Val CCC 0.547945
Seed 100 | Q3 | Epoch 05 | Val CCC 0.417760
Seed 100 | Q4 | Epoch 13 | Val CCC 0.520323
Seed 100 | Q5 | Epoch 19 | Val CCC 0.472589
Seed 100 | Q6 | Epoch 04 | Val CCC 0.446271
Seed 100 | Q7 | Epoch 20 | Val CCC 0.488423
Seed 100 | Q8 | Epoch 13 | Val CCC 0.298643
======================================================================
No-Mask Seed 100验证结果
CCC：0.639383
RMSE：4.750120
MAE：3.509091
完全相等比例：0.072727
Seed 1234 | Q1 | Epoch 03 | Val CCC 0.511910
Seed 1234 | Q2 | Epoch 06 | Val CCC 0.521739
Seed 1234 | Q3 | Epoch 18 | Val CCC 0.433305
Seed 1234 | Q4 | Epoch 06 | Val CCC 0.545021
Seed 1234 | Q5 | Epoch 11 | Val CCC 0.470691
Seed 1234 | Q6 | Epoch 03 | Val CCC 0.498613
Seed 1234 | Q7 | Epoch 03 | Val CCC 0.491968
Seed 1234 | Q8 | Epoch 17 | Val CCC 0.275256
======================================================================
No-Mask Seed 1234验证结果
CCC：0.675825
RMSE：4.612236
MAE：3.345454
完全相等比例：0.145455

In [175]:
all_text_video_nomask_validation_results = [text_video_nomask_seed42_validation_result, text_video_nomask_seed100_validation_result, text_video_nomask_seed1234_validation_result]
text_video_nomask_validation_rows = []
for result in all_text_video_nomask_validation_results:
    text_video_nomask_validation_rows.append({"Seed": result["seed"], "Sample_Count": result["sample_count"], "CCC": result["ccc"], "RMSE": result["rmse"], "MAE": result["mae"], "Exact_Accuracy": result["exact_accuracy"]})
text_video_nomask_validation_df = pd.DataFrame(text_video_nomask_validation_rows)
display(text_video_nomask_validation_df)

   Seed  Sample_Count       CCC      RMSE       MAE  Exact_Accuracy
0    42            55  0.685568  4.538723  3.400000        0.109091
1   100            55  0.639383  4.750120  3.509091        0.072727
2  1234            55  0.675825  4.612236  3.345454        0.145455

In [176]:
text_video_nomask_statistics_rows = []
for metric_name in ["CCC", "RMSE", "MAE", "Exact_Accuracy"]:
    text_video_nomask_statistics_rows.append({"Metric": metric_name, "Mean": text_video_nomask_validation_df[metric_name].mean(), "Std": text_video_nomask_validation_df[metric_name].std(ddof=1)})
text_video_nomask_statistics_df = pd.DataFrame(text_video_nomask_statistics_rows)
display(text_video_nomask_statistics_df)

           Metric      Mean       Std
0             CCC  0.666926  0.024345
1            RMSE  4.633693  0.107319
2             MAE  3.418182  0.083320
3  Exact_Accuracy  0.109091  0.036364

In [177]:
mask_nomask_paired_df = text_video_validation_seed_summary_df[["Seed", "CCC", "RMSE", "MAE"]].merge(text_video_nomask_validation_df[["Seed", "CCC", "RMSE", "MAE"]], on="Seed", suffixes=("_Mask", "_NoMask"), validate="one_to_one")
mask_nomask_paired_df["CCC_Delta_NoMask_Minus_Mask"] = mask_nomask_paired_df["CCC_NoMask"] - mask_nomask_paired_df["CCC_Mask"]
mask_nomask_paired_df["RMSE_Delta_NoMask_Minus_Mask"] = mask_nomask_paired_df["RMSE_NoMask"] - mask_nomask_paired_df["RMSE_Mask"]
mask_nomask_paired_df["MAE_Delta_NoMask_Minus_Mask"] = mask_nomask_paired_df["MAE_NoMask"] - mask_nomask_paired_df["MAE_Mask"]
display(mask_nomask_paired_df)

,Seed,CCC_Mask,RMSE_Mask,MAE_Mask,CCC_NoMask,RMSE_NoMask,MAE_NoMask,CCC_Delta_NoMask_Minus_Mask,RMSE_Delta_NoMask_Minus_Mask,MAE_Delta_NoMask_Minus_Mask
0,42,0.680283,4.421024,3.218182,0.685568,4.538723,3.400000,0.005286,0.117699,0.181818
1,100,0.625042,4.837355,3.654546,0.639383,4.750120,3.509091,0.014342,-0.087235,-0.145455
2,1234,0.661026,4.568668,3.236364,0.675825,4.612236,3.345454,0.014799,0.043569,0.109091

In [178]:
mask_nomask_summary_rows = []
mask_nomask_summary_rows.append({"Variant": "Mask", "CCC_Mean": text_video_validation_seed_summary_df["CCC"].mean(), "CCC_Std": text_video_validation_seed_summary_df["CCC"].std(ddof=1), "RMSE_Mean": text_video_validation_seed_summary_df["RMSE"].mean(), "RMSE_Std": text_video_validation_seed_summary_df["RMSE"].std(ddof=1), "MAE_Mean": text_video_validation_seed_summary_df["MAE"].mean(), "MAE_Std": text_video_validation_seed_summary_df["MAE"].std(ddof=1)})
mask_nomask_summary_rows.append({"Variant": "No-Mask", "CCC_Mean": text_video_nomask_validation_df["CCC"].mean(), "CCC_Std": text_video_nomask_validation_df["CCC"].std(ddof=1), "RMSE_Mean": text_video_nomask_validation_df["RMSE"].mean(), "RMSE_Std": text_video_nomask_validation_df["RMSE"].std(ddof=1), "MAE_Mean": text_video_nomask_validation_df["MAE"].mean(), "MAE_Std": text_video_nomask_validation_df["MAE"].std(ddof=1)})
mask_nomask_summary_df = pd.DataFrame(mask_nomask_summary_rows)
display(mask_nomask_summary_df)

   Variant  CCC_Mean   CCC_Std  RMSE_Mean  RMSE_Std  MAE_Mean   MAE_Std
0     Mask  0.655450  0.028039   4.609015  0.211078  3.369697  0.246854
1  No-Mask  0.666926  0.024345   4.633693  0.107319  3.418182  0.083320

In [179]:
mask_nomask_paired_df = text_video_validation_seed_summary_df[["Seed", "CCC", "RMSE", "MAE"]].merge(text_video_nomask_validation_df[["Seed", "CCC", "RMSE", "MAE"]], on="Seed", suffixes=("_Mask", "_NoMask"), validate="one_to_one")
mask_nomask_paired_df["CCC_Delta_NoMask_Minus_Mask"] = mask_nomask_paired_df["CCC_NoMask"] - mask_nomask_paired_df["CCC_Mask"]
mask_nomask_paired_df["RMSE_Delta_NoMask_Minus_Mask"] = mask_nomask_paired_df["RMSE_NoMask"] - mask_nomask_paired_df["RMSE_Mask"]
mask_nomask_paired_df["MAE_Delta_NoMask_Minus_Mask"] = mask_nomask_paired_df["MAE_NoMask"] - mask_nomask_paired_df["MAE_Mask"]
display(mask_nomask_paired_df)

,Seed,CCC_Mask,RMSE_Mask,MAE_Mask,CCC_NoMask,RMSE_NoMask,MAE_NoMask,CCC_Delta_NoMask_Minus_Mask,RMSE_Delta_NoMask_Minus_Mask,MAE_Delta_NoMask_Minus_Mask
0,42,0.680283,4.421024,3.218182,0.685568,4.538723,3.400000,0.005286,0.117699,0.181818
1,100,0.625042,4.837355,3.654546,0.639383,4.750120,3.509091,0.014342,-0.087235,-0.145455
2,1234,0.661026,4.568668,3.236364,0.675825,4.612236,3.345454,0.014799,0.043569,0.109091

In [180]:
mask_nomask_summary_rows = []
mask_nomask_summary_rows.append({"Variant": "Mask", "CCC_Mean": text_video_validation_seed_summary_df["CCC"].mean(), "CCC_Std": text_video_validation_seed_summary_df["CCC"].std(ddof=1), "RMSE_Mean": text_video_validation_seed_summary_df["RMSE"].mean(), "RMSE_Std": text_video_validation_seed_summary_df["RMSE"].std(ddof=1), "MAE_Mean": text_video_validation_seed_summary_df["MAE"].mean(), "MAE_Std": text_video_validation_seed_summary_df["MAE"].std(ddof=1)})
mask_nomask_summary_rows.append({"Variant": "No-Mask", "CCC_Mean": text_video_nomask_validation_df["CCC"].mean(), "CCC_Std": text_video_nomask_validation_df["CCC"].std(ddof=1), "RMSE_Mean": text_video_nomask_validation_df["RMSE"].mean(), "RMSE_Std": text_video_nomask_validation_df["RMSE"].std(ddof=1), "MAE_Mean": text_video_nomask_validation_df["MAE"].mean(), "MAE_Std": text_video_nomask_validation_df["MAE"].std(ddof=1)})
mask_nomask_summary_df = pd.DataFrame(mask_nomask_summary_rows)
display(mask_nomask_summary_df)

   Variant  CCC_Mean   CCC_Std  RMSE_Mean  RMSE_Std  MAE_Mean   MAE_Std
0     Mask  0.655450  0.028039   4.609015  0.211078  3.369697  0.246854
1  No-Mask  0.666926  0.024345   4.633693  0.107319  3.418182  0.083320

In [181]:
text_video_nomask_validation_df.to_csv(TEXT_VIDEO_NOMASK_ROOT / "three_seed_validation_results.csv", index=False)
text_video_nomask_statistics_df.to_csv(TEXT_VIDEO_NOMASK_ROOT / "three_seed_validation_summary.csv", index=False)
mask_nomask_paired_df.to_csv(TEXT_VIDEO_NOMASK_ROOT / "mask_nomask_paired_validation_comparison.csv", index=False)
mask_nomask_summary_df.to_csv(TEXT_VIDEO_NOMASK_ROOT / "mask_nomask_validation_summary.csv", index=False)

In [182]:
def evaluate_text_video_nopostzero_seed_on_test(seed):
    question_prediction_list = []
    selected_checkpoint_rows = []
    for question_index in range(len(PHQ8_QUESTION_COLUMNS)):
        checkpoint_path = TEXT_VIDEO_NOMASK_ROOT / f"seed_{seed}" / f"question_{question_index + 1}" / "best_ccc.pt"
        if not checkpoint_path.exists():
            raise FileNotFoundError(f"NoPostZero Checkpoint不存在：{checkpoint_path}")
        checkpoint = torch.load(checkpoint_path, map_location="cpu", weights_only=False)
        if checkpoint["seed"] != seed or checkpoint["question_index"] != question_index or checkpoint["checkpoint_type"] != "best_ccc":
            raise RuntimeError(f"Checkpoint元数据错误：{checkpoint_path}")
        model = TextVideoQuestMFNoMask(PretrainedTextEncoderNoMask(), PretrainedVideoEncoderNoMask()).to(device)
        load_result = model.load_state_dict(checkpoint["model_state_dict"], strict=True)
        if load_result.missing_keys or load_result.unexpected_keys:
            raise RuntimeError(f"Checkpoint参数不一致：{checkpoint_path}")
        model.eval()
        batch_prediction_list = []
        with torch.no_grad():
            for text_features, text_masks, video_features, video_masks, true_totals, participant_ids in text_video_test_loader:
                logits = model(text_features.to(device), text_masks.to(device), video_features.to(device), video_masks.to(device))
                batch_prediction_list.append(logits.argmax(dim=1).cpu())
        question_predictions = torch.cat(batch_prediction_list)
        if len(question_predictions) != len(text_video_test_dataset):
            raise RuntimeError(f"Q{question_index + 1}预测数量错误")
        question_prediction_list.append(question_predictions)
        selected_checkpoint_rows.append({"Seed": seed, "Question_Index": question_index, "Question_Number": question_index + 1, "Question_Name": PHQ8_QUESTION_COLUMNS[question_index], "Checkpoint_Path": str(checkpoint_path), "Checkpoint_Epoch": checkpoint["epoch"], "Validation_CCC": checkpoint["val_metrics"]["ccc"], "Variant": "NoPostZero"})
        print(f"Seed {seed} | Q{question_index + 1} | Epoch {checkpoint['epoch']:02d} | Val CCC {checkpoint['val_metrics']['ccc']:.6f}")
        del model
        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
    question_predictions = torch.stack(question_prediction_list, dim=1)
    predicted_totals = question_predictions.sum(dim=1)
    true_totals = text_video_test_dataset.true_totals.clone()
    total_ccc = calculate_ccc(predicted_totals, true_totals)
    total_rmse = float(torch.sqrt(torch.mean((predicted_totals.float() - true_totals.float()) ** 2)).item())
    total_mae = float(torch.mean(torch.abs(predicted_totals.float() - true_totals.float())).item())
    exact_accuracy = float((predicted_totals == true_totals).float().mean().item())
    prediction_df = pd.DataFrame({"Participant_ID": text_video_test_dataset.participant_ids})
    for question_index in range(len(PHQ8_QUESTION_COLUMNS)):
        prediction_df[f"Q{question_index + 1}_Predicted"] = question_predictions[:, question_index].numpy()
    prediction_df["Predicted_Total"] = predicted_totals.numpy()
    prediction_df["True_Total"] = true_totals.numpy()
    prediction_path = TEXT_VIDEO_NOMASK_ROOT / f"seed_{seed}_test_predictions_56.csv"
    selected_checkpoint_path = TEXT_VIDEO_NOMASK_ROOT / f"seed_{seed}_test_selected_checkpoints.csv"
    prediction_df.to_csv(prediction_path, index=False)
    pd.DataFrame(selected_checkpoint_rows).to_csv(selected_checkpoint_path, index=False)
    print("=" * 70)
    print(f"Text+Video NoPostZero Seed {seed}测试结果")
    print(f"测试人数：{len(prediction_df)}")
    print(f"CCC：{total_ccc:.6f}")
    print(f"RMSE：{total_rmse:.6f}")
    print(f"MAE：{total_mae:.6f}")
    print(f"完全相等比例：{exact_accuracy:.6f}")
    print(f"预测范围：{int(predicted_totals.min())}～{int(predicted_totals.max())}")
    print(f"真实范围：{int(true_totals.min())}～{int(true_totals.max())}")
    return {"seed": seed, "sample_count": len(prediction_df), "ccc": total_ccc, "rmse": total_rmse, "mae": total_mae, "exact_accuracy": exact_accuracy, "predicted_totals": predicted_totals, "true_totals": true_totals, "prediction_path": prediction_path}

In [183]:
text_video_nopostzero_seed42_test_result = evaluate_text_video_nopostzero_seed_on_test(seed=42)
text_video_nopostzero_seed100_test_result = evaluate_text_video_nopostzero_seed_on_test(seed=100)
text_video_nopostzero_seed1234_test_result = evaluate_text_video_nopostzero_seed_on_test(seed=1234)

Seed 42 | Q1 | Epoch 17 | Val CCC 0.507003
Seed 42 | Q2 | Epoch 09 | Val CCC 0.560000
Seed 42 | Q3 | Epoch 08 | Val CCC 0.486281
Seed 42 | Q4 | Epoch 17 | Val CCC 0.414504
Seed 42 | Q5 | Epoch 06 | Val CCC 0.517218
Seed 42 | Q6 | Epoch 06 | Val CCC 0.513761
Seed 42 | Q7 | Epoch 10 | Val CCC 0.558587
Seed 42 | Q8 | Epoch 02 | Val CCC 0.306794
======================================================================
Text+Video NoPostZero Seed 42测试结果
测试人数：56
CCC：0.609228
RMSE：6.005949
MAE：4.500000
完全相等比例：0.142857
预测范围：0～22
真实范围：0～22
Seed 100 | Q1 | Epoch 09 | Val CCC 0.430052
Seed 100 | Q2 | Epoch 16 | Val CCC 0.547945
Seed 100 | Q3 | Epoch 05 | Val CCC 0.417760
Seed 100 | Q4 | Epoch 13 | Val CCC 0.520323
Seed 100 | Q5 | Epoch 19 | Val CCC 0.472589
Seed 100 | Q6 | Epoch 04 | Val CCC 0.446271
Seed 100 | Q7 | Epoch 20 | Val CCC 0.488423
Seed 100 | Q8 | Epoch 13 | Val CCC 0.298643
======================================================================
Text+Video NoPostZero Seed 100测试结果
测试人数：56
CCC：0.656879
RMSE：5.467436
MAE：4.250000
完全相等比例：0.089286
预测范围：0～22
真实范围：0～22
Seed 1234 | Q1 | Epoch 03 | Val CCC 0.511910
Seed 1234 | Q2 | Epoch 06 | Val CCC 0.521739
Seed 1234 | Q3 | Epoch 18 | Val CCC 0.433305
Seed 1234 | Q4 | Epoch 06 | Val CCC 0.545021
Seed 1234 | Q5 | Epoch 11 | Val CCC 0.470691
Seed 1234 | Q6 | Epoch 03 | Val CCC 0.498613
Seed 1234 | Q7 | Epoch 03 | Val CCC 0.491968
Seed 1234 | Q8 | Epoch 17 | Val CCC 0.275256
======================================================================
Text+Video NoPostZero Seed 1234测试结果
测试人数：56
CCC：0.637801
RMSE：5.538824
MAE：4.071429
完全相等比例：0.125000
预测范围：0～21
真实范围：0～22

In [184]:
all_text_video_nopostzero_test_results = [text_video_nopostzero_seed42_test_result, text_video_nopostzero_seed100_test_result, text_video_nopostzero_seed1234_test_result]
text_video_nopostzero_test_rows = []
for result in all_text_video_nopostzero_test_results:
    text_video_nopostzero_test_rows.append({"Seed": result["seed"], "Sample_Count": result["sample_count"], "CCC": result["ccc"], "RMSE": result["rmse"], "MAE": result["mae"], "Exact_Accuracy": result["exact_accuracy"]})
text_video_nopostzero_test_df = pd.DataFrame(text_video_nopostzero_test_rows)
display(text_video_nopostzero_test_df)

   Seed  Sample_Count       CCC      RMSE       MAE  Exact_Accuracy
0    42            56  0.609228  6.005949  4.500000        0.142857
1   100            56  0.656879  5.467436  4.250000        0.089286
2  1234            56  0.637801  5.538824  4.071429        0.125000

In [185]:
all_text_video_nopostzero_test_results = [text_video_nopostzero_seed42_test_result, text_video_nopostzero_seed100_test_result, text_video_nopostzero_seed1234_test_result]
text_video_nopostzero_test_rows = []
for result in all_text_video_nopostzero_test_results:
    text_video_nopostzero_test_rows.append({"Seed": result["seed"], "Sample_Count": result["sample_count"], "CCC": result["ccc"], "RMSE": result["rmse"], "MAE": result["mae"], "Exact_Accuracy": result["exact_accuracy"]})
text_video_nopostzero_test_df = pd.DataFrame(text_video_nopostzero_test_rows)
display(text_video_nopostzero_test_df)

   Seed  Sample_Count       CCC      RMSE       MAE  Exact_Accuracy
0    42            56  0.609228  6.005949  4.500000        0.142857
1   100            56  0.656879  5.467436  4.250000        0.089286
2  1234            56  0.637801  5.538824  4.071429        0.125000

In [186]:
text_video_nopostzero_test_statistics_rows = []
for metric_name in ["CCC", "RMSE", "MAE", "Exact_Accuracy"]:
    text_video_nopostzero_test_statistics_rows.append({"Metric": metric_name, "Mean": text_video_nopostzero_test_df[metric_name].mean(), "Std": text_video_nopostzero_test_df[metric_name].std(ddof=1)})
text_video_nopostzero_test_statistics_df = pd.DataFrame(text_video_nopostzero_test_statistics_rows)
display(text_video_nopostzero_test_statistics_df)

           Metric      Mean       Std
0             CCC  0.634636  0.023983
1            RMSE  5.670736  0.292489
2             MAE  4.273810  0.215275
3  Exact_Accuracy  0.119048  0.027277

In [187]:
text_video_nopostzero_keep_mask_55 = torch.tensor([participant_id != 637 for participant_id in text_video_test_dataset.participant_ids], dtype=torch.bool)
text_video_nopostzero_test_55_rows = []
for result in all_text_video_nopostzero_test_results:
    predicted_totals_55 = result["predicted_totals"][text_video_nopostzero_keep_mask_55]
    true_totals_55 = result["true_totals"][text_video_nopostzero_keep_mask_55]
    ccc_55 = calculate_ccc(predicted_totals_55, true_totals_55)
    rmse_55 = float(torch.sqrt(torch.mean((predicted_totals_55.float() - true_totals_55.float()) ** 2)).item())
    mae_55 = float(torch.mean(torch.abs(predicted_totals_55.float() - true_totals_55.float())).item())
    exact_accuracy_55 = float((predicted_totals_55 == true_totals_55).float().mean().item())
    text_video_nopostzero_test_55_rows.append({"Seed": result["seed"], "Sample_Count": len(predicted_totals_55), "CCC": ccc_55, "RMSE": rmse_55, "MAE": mae_55, "Exact_Accuracy": exact_accuracy_55})
text_video_nopostzero_test_55_df = pd.DataFrame(text_video_nopostzero_test_55_rows)
display(text_video_nopostzero_test_55_df)

   Seed  Sample_Count       CCC      RMSE       MAE  Exact_Accuracy
0    42            55  0.596663  6.036254  4.509091        0.145455
1   100            55  0.646045  5.510321  4.290909        0.090909
2  1234            55  0.622839  5.574292  4.090909        0.127273

In [188]:
text_video_nopostzero_test_55_statistics_rows = []
for metric_name in ["CCC", "RMSE", "MAE", "Exact_Accuracy"]:
    text_video_nopostzero_test_55_statistics_rows.append({"Metric": metric_name, "Mean": text_video_nopostzero_test_55_df[metric_name].mean(), "Std": text_video_nopostzero_test_55_df[metric_name].std(ddof=1)})
text_video_nopostzero_test_55_statistics_df = pd.DataFrame(text_video_nopostzero_test_55_statistics_rows)
display(text_video_nopostzero_test_55_statistics_df)

           Metric      Mean       Std
0             CCC  0.621849  0.024706
1            RMSE  5.706955  0.286969
2             MAE  4.296970  0.209157
3  Exact_Accuracy  0.121212  0.027773

In [189]:
text_video_nopostzero_test_df.to_csv(TEXT_VIDEO_NOMASK_ROOT / "three_seed_test_results_56.csv", index=False)
text_video_nopostzero_test_statistics_df.to_csv(TEXT_VIDEO_NOMASK_ROOT / "three_seed_test_summary_56.csv", index=False)
text_video_nopostzero_test_55_df.to_csv(TEXT_VIDEO_NOMASK_ROOT / "three_seed_test_results_candidate55.csv", index=False)
text_video_nopostzero_test_55_statistics_df.to_csv(TEXT_VIDEO_NOMASK_ROOT / "three_seed_test_summary_candidate55.csv", index=False)

In [190]:
final_ablation_rows = []
final_ablation_rows.append({"Variant": "PostZero", "Protocol": "56", "CCC": text_video_test_seed_summary_df["CCC"].mean(), "CCC_Std": text_video_test_seed_summary_df["CCC"].std(ddof=1), "RMSE": text_video_test_seed_summary_df["RMSE"].mean(), "MAE": text_video_test_seed_summary_df["MAE"].mean()})
final_ablation_rows.append({"Variant": "NoPostZero", "Protocol": "56", "CCC": text_video_nopostzero_test_df["CCC"].mean(), "CCC_Std": text_video_nopostzero_test_df["CCC"].std(ddof=1), "RMSE": text_video_nopostzero_test_df["RMSE"].mean(), "MAE": text_video_nopostzero_test_df["MAE"].mean()})
final_ablation_rows.append({"Variant": "PostZero", "Protocol": "Candidate55", "CCC": text_video_test_55_summary_df["CCC"].mean(), "CCC_Std": text_video_test_55_summary_df["CCC"].std(ddof=1), "RMSE": text_video_test_55_summary_df["RMSE"].mean(), "MAE": text_video_test_55_summary_df["MAE"].mean()})
final_ablation_rows.append({"Variant": "NoPostZero", "Protocol": "Candidate55", "CCC": text_video_nopostzero_test_55_df["CCC"].mean(), "CCC_Std": text_video_nopostzero_test_55_df["CCC"].std(ddof=1), "RMSE": text_video_nopostzero_test_55_df["RMSE"].mean(), "MAE": text_video_nopostzero_test_55_df["MAE"].mean()})
final_ablation_df = pd.DataFrame(final_ablation_rows)
display(final_ablation_df)
final_ablation_df.to_csv(TEXT_VIDEO_NOMASK_ROOT / "postzero_vs_nopostzero_test_comparison.csv", index=False)

      Variant     Protocol       CCC   CCC_Std      RMSE       MAE
0    PostZero           56  0.609208  0.023594  5.692522  4.309524
1  NoPostZero           56  0.634636  0.023983  5.670736  4.273810
2    PostZero  Candidate55  0.595926  0.022465  5.740925  4.363636
3  NoPostZero  Candidate55  0.621849  0.024706  5.706955  4.296970